[로또] 쉐이크반 미션 제출합니다.
woowacourse/java-lotto pull request #11
Opened 2019-05-30 06:54 UTC by vsh123

안녕하세요!

로또게임 3단계까지 구현한 내용을 제출합니다!
로또 자동생성에 대해서는 Collections.shuffle이라는 메소드를 추천해주셨는데,
1~45의 숫자들을 Map에 저장하고 있어서 Random을 사용하였습니다.

List가 아닌 Map을 사용한 이유는 List를 사용할 경우 사용자가 요청한 index에 -1한 위치의 값을 리턴해야 하는데 
이 때 -1을 하는 것보다 Map을 사용하여 1~45사이의 키를 들고 있고 요청한 index에 있는 value를 리턴하는 것이
조금 더 깔끔하다고 생각하여 구현하였습니다.

혹시 위 내용에 대해서 제가 조금 더 고려해야할 점 있으면 피드백 부탁드리겠습니다!
그 외 다른 부분에서도 고쳐야할 점이 있다면 많이많이 피드백 주시면 감사하겠습니다~~ :)

감사합니다!

2019-06-09 10:33 UTC, woowahan-pjs requested changes
전체적인 설계와 깔끔한 코드 구현이 좋았습니다. 💯 
몇 가지 의견을 남겨놓았으니 충분히 고민하고 도전해보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/LottoGameMain.java
> +        } catch (NumberFormatException | InvalidLottoPriceException e) {
캡틴께서 "반복문 대신 재귀 함수로 구현할 수 있다."라고 알려주셨어요. 하지만 재귀를 사용하면 어떤 위험이 있을까요? 만약 재귀를 사용하지 않는다면 어떻게 문제를 해결할 수 있을까요?

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/view/InputView.java
> +    public static String getPrice() {
Controller에서 구입 금액을 검증할 수 있도록 int가 아닌 String을 반환하네요! 💯

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/utils/InvalidLottoPriceException.java
> +public class InvalidLottoPriceException extends RuntimeException {
커스터마이징 한 예외 클래스 👍

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/utils/InvalidLottoPriceException.java
> +package lottogame.utils;
`InvalidLottoPriceException`은 `utils` 패키지에 있는 것이 적절할까요?

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/Money.java
> +    private boolean isValidatePrice(int price) {
여기서 `InvalidLottoPriceException`이 발생하면 어떨까요?

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/LottoGameMain.java
> +        if (!lottoTickets.isCreatedNumberOfManualLotto()) {
아래의 글을 읽고 코드에 반영하면 어떨까요?
https://schneide.blog/2014/08/03/dont-ever-not-avoid-negative-logic

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/view/OutputView.java
> +                (lottoTickets.numberOfLottos() - lottoTickets.getNumberOfManualTicket()) + "개를 구매했습니다.");
`lottoTickets.numberOfLottos() - lottoTickets.getNumberOfManualTicket()`은 의미를 설명할 수 있는 메서드로 한 번 더 분리하는 것이 좋아 보여요.

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/view/OutputView.java
> +        System.out.println("총 수익률은 " + lottoResult.getRateOfLotto(money) + "%입니다.");
View는 Model의 주요 기능을 실행하는 것이 아닌 화면을 보여주는 데에 집중하면 어떨까요?

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/Money.java
> +        return (long) (profits / price) * PERCENTAGE;
아래의 글은 가볍게 참고만 해주세요.
https://isooo.github.io/java/2019/01/17/BigDecimal.html

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoResult.java
> +            stringBuilder.append(rank).append(result.get(rank)).append("개\n");
Model에 View의 요구 사항을 반영하는 것이 맞을까요? Model과 View의 기능을 분리하면 어떤 장점이 있을까요?

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/WinningLotto.java
> +        this.bonusNumber = null;
`WinningLotto`는 보너스 번호 없이 존재할 수 있을까요? 도메인 객체가 불완전한 상태로 사용되는 것을 막으려면 생성 시점에 필요한 것을 전달해 주어야 합니다.

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/Rank.java
> +            return numberOfMatch + "개 일치, 보너스 볼 일치(" + prize + "원) - ";
마찬가지로 Model에 View의 요구 사항을 반영하는 것이 맞을까요?

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/Rank.java
> +    FIRST(6, 2000000000);
Java7부터는 `100_000_000`처럼 숫자에 밑줄을 사용하여 가독성을 높일 수 있어요.

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoTickets.java
> +    private final int numberOfManualTicket;
`LottoTickets`에서 `numberOfManualTicket`을 관리하는 것이 맞을까요? 아래의 글을 읽고 일급 컬렉션 만들기에 도전해보세요!
https://jojoldu.tistory.com/412

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/ManualLottoGenerator.java
> +    private static final int LOTTO_SIZE = 6;
`AutoLottoGenerator`와 `ManualLottoGenerator`에서 코드 중복이 발생하였네요. `LOTTO_SIZE`를 적절한 위치로 이동시켜 보세요.

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoResultGenerator.java
> +    public static LottoResult create(LottoTickets lottoTickets, WinningLotto winningLotto) {
이 메서드는 두 번 이상 사용할 수 있을까요?

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoNumber.java
> +    }
인스턴스를 미리 만들어 놓거나 새로 생성한 인스턴스를 캐싱 하여 재활용하는 식으로 불필요한 객체 생성을 피할 수 있다. 👍

2019-06-09 10:33 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/WinningLotto.java
> +        return bonusNumber == lottoNumber;
인스턴스를 캐싱 하여 재활용하였기에 사용 가능한 코드 👍

2019-06-10 09:57 UTC, vsh123 commented
안녕하세요! 보내주신 피드백 반영하여 1차 수정 진행하였습니다.
혹시 더 수정해야할 부분이 있다면 언제든지 피드백 부탁드리겠습니다!

항상 감사합니다~

2019-06-10 09:57 UTC, vsh123 commented on src/main/java/lottogame/LottoGameMain.java
> +        } catch (NumberFormatException | InvalidLottoPriceException e) {
재귀를 사용한다면 메모리에 대한 오버플로우가 발생할 위험이 있습니다. 이를 해결하기 위해 반복문으로 변경을 하였고 try-catch를 각 도메인에서 실행하였습니다!

2019-06-10 09:59 UTC, vsh123 commented on src/main/java/lottogame/domain/LottoResult.java
> +            stringBuilder.append(rank).append(result.get(rank)).append("개\n");
Model과 View의 기능을 분리하게 된다면 다양한 View에 맞게 유동적으로 보여줄 수 있다는 장점이 있습니다!

2019-06-10 23:07 UTC, woowahan-pjs requested changes
테스트 코드를 꾸준히 작성하면 더 깔끔한 코드를 볼 수 있을 거예요.
몇 가지 의견을 남겨놓았으니 충분히 고민하고 도전해보세요!
다음 리뷰 요청 때는 Merge 하도록 하겠습니다.

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoTickets.java
> +        if(lotto != null){
IntelliJ IDEA의 코드 자동 정렬 기능(⌥⌘L, Ctrl+Alt+L)을 사용하면 더 깔끔한 코드를 볼 수 있을 거예요.

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/Money.java
> +            System.out.println("숫자를 입력해 주세요.");
View의 요구 사항이네요.

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/view/InputView.java
> +        } while(money.isInvalidNumber(input));
View는 Model의 주요 기능을 실행하는 것이 아닌 화면을 보여주는 데에 집중하면 어떨까요?

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/view/OutputView.java
> +        System.out.println("총 수익률은 " + rateOfLotto + "%입니다.");
View는 Model의 주요 기능을 실행하는 것이 아닌 화면을 보여주는 데에 집중한다. 👍

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoGenerator.java
> +    private static final int LOTTO_SIZE = 6;
`ManualLottoGenerator`와 `AutoLottoGenerator`를 `LottoGenerator`로 합친 이유가 있을까요? 테스트 가능한 부분과 테스트하기 힘든 부분은 분리하는 것이 좋아요.

2019-06-10 23:07 UTC, woowahan-pjs commented on src/test/java/lottogame/domain/LottoGeneratorTest.java
> +        assertThat(LottoGenerator.create("1,2,3,4,5,6")).isExactlyInstanceOf(Lotto.class);
조금 더 명확한 테스트 코드를 만들어 보세요.

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoGenerator.java
> +            return null;
정적 팩토리 메서드는 생성자의 기능을 대신합니다. `null`을 반환하는 것이 좋을지 같이 고민해봐요.

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoGenerator.java
> +    private static final int LOTTO_SIZE = 6;
`LOTTO_SIZE`는 `LottoGenerator`가 아닌 `Lotto`에 위치할 수도 있겠죠? 첨언을 하면 public static final 필드 방식을 사용해 보세요.

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoResult.java
> +    LottoResult() {
`LottoResult`를 생성할 때 완전한 상태로 생성할 수 있게 변경하면 어떤 장점이 있을까요?

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoResult.java
> +    public static LottoResult generate(LottoTickets lottoTickets, WinningLotto winningLotto) {
`LottoResult`가 `LottoTickets`와 `WinningLotto`에 의존하고 있어요. 삭제한 `LottoResultGenerator`가 필요할 것 같아요. 아래의 코멘트는 기존 `LottoResultGenerator`에서 `create()`를 두 번 이상 호출하면 예상치 못한 값을 가진 `LottoResult`가 생성된다는 뜻이었습니다.
https://github.com/woowacourse/java-lotto/pull/11#discussion_r291832974

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoResult.java
> +    public long getRateOfLotto(Money money) {
테스트 코드가 필요해 보여요.

2019-06-10 23:07 UTC, woowahan-pjs commented on src/main/java/lottogame/lottogameexception/InvalidLottoNumberException.java
> +package lottogame.lottogameexception;
`InvalidLottoPriceException`이 `domain` 패키지에 위치하면 어떨까요? 같이 고민해봐요.

2019-06-11 00:27 UTC, vsh123 commented on src/main/java/lottogame/domain/LottoGenerator.java
> +    private static final int LOTTO_SIZE = 6;
LOTTO_SIZE에 대한 중복으로 인해 합치게 되었습니다.
하지만 아래 comment 달아주신 것을 참고하면 해당 부분을 다시 분리하는 것이 더 좋을 것 같다는 생각이 듭니다!
감사합니다 :)

2019-06-11 03:37 UTC, vsh123 commented
안녕하세요! 보내주신 피드백 반영하여 다시한번 리뷰 요청드립니다.

이번 피드백 리뷰를 반영하면서 정적 팩토리 메서드에서 null을 반환하는 것에 대해 많은 고민이 있었습니다ㅠㅠ
코드 보시고 추가적으로 고칠 부분이 보인다면 코멘트 부탁드리겠습니다!!

감사합니다!

2019-06-12 02:01 UTC, woowahan-pjs approved these changes
피드백을 모두 잘 반영해주셨습니다. 💯 
생성자 대신 사용하는 것이 정적 팩토리 메서드입니다.
다른 개발자가 정적 팩토리 메서드를 사용할 때 `null`이 반환될 것을 예상할 수 있을까요?
고민에 대한 답으로 아래의 글이 도움 되면 좋겠어요.

- https://www.codebyamir.com/blog/stop-returning-null-in-java
- https://stackoverflow.com/questions/11124562/is-it-ok-for-a-factory-method-to-return-null

다음 단계를 진행하려면 woowacouse에 Merge 된 코드에서 다시 시작해야 충돌이 발생하지 않을 거예요.
아래의 과정을 진행한 후, 다음 단계 진행할 것을 추천해요.

```
1. git remote add upstream
2. git fetch upstream 자신의 github_id
3. git reset --hard upstream/자신의 github_id
```

다음 단계에서 뵙겠습니다. 이만 Merge 하겠습니다.

2019-06-12 02:01 UTC, woowahan-pjs commented on src/main/java/lottogame/LottoGameMain.java
> +    }
아래의 코드로 개선해보면 어떨까요?

```java
private static Optional<Money> createMoney(String price) {
    try {
        return Optional.of(Money.generate(Integer.parseInt(price)));
    } catch (RuntimeException e) {
        System.out.println(e.getMessage());
        return Optional.empty();
    }
}
```

2019-06-12 02:01 UTC, woowahan-pjs commented on src/main/java/lottogame/domain/LottoTickets.java
> +    public static LottoTickets generate() {
`LottoTickets`를 생성할 때 완전한 상태로 생성할 수 있게 변경하면 어떤 장점이 있을까요?

2019-06-12 02:02 UTC, merged