[라빈] 로또 1단계 - 자동 미션 제출합니다.
woowacourse/java-lotto pull request #125
Opened 2020-02-20 08:08 UTC by giantim

2020-02-22 06:33 UTC, jeonghoon1107 requested changes
안녕하세요 라빈!
깔끔하게 구현 잘 하셨네요 💯 
몇 가지 피드백 남겼으니 확인부탁드려요 :)

2020-02-22 06:33 UTC, jeonghoon1107 commented on src/main/java/controller/LottoController.java
> +public class LottoController {
LottoApplication과 LottoController의 역할이 모호한 것 같아요.
LottoApplication에서 입출력을 하는 식으로 역할이 분리되면 어떨까요?
LottoController에게는 money를 입력받고 결과를 반환하는 것으로 하면 해당 클래스가 조금 더 깔끔해 질 것 같아요.

추가로 모든 인스턴스 변수를 static으로 사용하게 되면 어떠한 문제점이 있을지 고민해보면 좋을 것 같아요!

2020-02-22 06:33 UTC, jeonghoon1107 commented on src/main/java/domain/PrizeType.java
> +    FIVE_WITH_BONUS(5, true, "5개 일치, 보너스 볼 일치 (30000000원)- ", (value -> value * 30000000)),
_를 사용해 숫자에 대한 가독성을 높일 수 있습니다!

2020-02-22 06:33 UTC, jeonghoon1107 commented on src/main/java/domain/WinningCalculator.java
> +    Map<PrizeType, Integer> prizeInfo;
접근제어자를 열어놓은 이유가 있나요?

2020-02-22 06:33 UTC, jeonghoon1107 commented on src/main/java/domain/BonusBall.java
> +        int parseNumber = validateParseInteger(input);
String 타입으로 받아야하나요?

2020-02-22 06:33 UTC, jeonghoon1107 commented on src/main/java/domain/LottoTicket.java
> +    List<Integer> lottoTicket;
규칙 3: 모든 원시값과 문자열을 포장한다.

2020-02-22 06:33 UTC, jeonghoon1107 commented on src/main/java/domain/LottoNumbers.java
> +        lottoNumbers = IntStream.rangeClosed(1, 45)
숫자 풀을 만들어놓고 사용하면 어떨까요?

2020-02-23 08:55 UTC, giantim commented on src/main/java/controller/LottoController.java
> +public class LottoController {
후니 안녕하세요. 주말에도 세세한 리뷰 감사합니다 :D
리뷰해주신 부분에 대해서 수정했고 푸시 했습니다.

저는 처음에 구현할 때 Application 에서는 Controller 를 호출해서 프로그램을 실행시키는 것이 더 깔끔하고 보기 좋을 것 같아서 그렇게 구현을 했었습니다. 하지만 리뷰 달아주신 내용을 보고 다시 생각해본 결과 Controller 에서는 Application 에서 필요한 인스턴스들을 생성하고 결과값을 반환하는 구조로 역할을 나누는 것이 더 맞다고 생각이 들었습니다. 그래서 Application 과 Controller 의 기능을 구분했습니다.

제가 Controller 에서 모든 인스턴스 변수를 static 으로 구현한 이유는 두 가지가 있습니다.
1. 로또 프로그램이 실행되었을 때 해당 객체들은 오직 한 번만 생성되기 때문에 static 으로 선언했습니다.
2. LottoController 의 메서드들이 static 메서드여서 관리하기 편해서 static 으로 구현했습니다.
리뷰 해주신 내용을 보고서 더 생각해본 결과 만약 프로그램이 확장되거나 다른 사람이 유지 보수할 때 문제가 생길 수 도 있다는 생각이 들었습니다. 그래서 이번에 리뷰 내용을 반영할 때는 LottoController 에서 전역 변수를 모두 제거했습니다.

2020-02-23 08:56 UTC, giantim commented on src/main/java/domain/PrizeType.java
> +    FIVE_WITH_BONUS(5, true, "5개 일치, 보너스 볼 일치 (30000000원)- ", (value -> value * 30000000)),
이 부분에 대해서는 처음 알게 되었습니다. 감사합니다 :)
프로그램 요구사항에 맞추어서 숫자가 출력되는 부분에는 _ 를 사용하지 않았습니다.

2020-02-23 08:57 UTC, giantim commented on src/main/java/domain/WinningCalculator.java
> +    Map<PrizeType, Integer> prizeInfo;
단순히 실수했습니다....
WinningCalculator 클래스 말고도 다른 클래스에서도 같은 실수를 했는데 더 꼼꼼히 보고 코딩해야겠습니다!

2020-02-23 09:05 UTC, giantim commented on src/main/java/domain/BonusBall.java
> +        int parseNumber = validateParseInteger(input);
저는 Scanner 를 이용하여 값을 읽을 때 nextInt 를 사용하지 않았습니다. 왜냐하면 nextInt 를 사용하면 뒤에 개행 문자가 한번 남아서 다음 값을 받아들이기 전에 값을 한번 더 읽어야 해서 번거롭기 때문입니다. 그래서 저는 정수 값이 필요한 부분도 nextLine 으로 받은 후에 parse 를 한번 하고 값의 유효성 검사는 그 값을 필요로 하는 클래스의 생성자에서 처리를 해주는 식으로 구현합니다. 이번에 LottoNumber 를 포장하면서 수정을 많이 했는데 nextInt 를 이용하여 값을 읽는 부분을 추가해봤습니다. 보너스 숫자를 입력하는 부분은 입력이 마지막으로 들어오는 부분이어서 nextInt 로 받았지만 처음에 금액을 입력을 받는 부분은 nextLine 으로 받은 후 parse 를 한번 해줬습니다 :)
혹시 제가 잘못 사용하거나 잘못 알고 있는 부분이 있다면 조언 부탁드립니다 😊

2020-02-23 09:07 UTC, giantim commented on src/main/java/domain/LottoTicket.java
> +    List<Integer> lottoTicket;
로또 숫자 하나를 LottoNumber 객체로 포장했습니다.
로또 프로그램의 가장 작은 단위인 LottoNumber 가 빠져있었어서 다시 한번 Inside -> out 으로 TDD 를 해봤습니다. 도메인을 다시 이해하고 코드를 작성하니까 굳이 BonusBall 을 따로 객체로 포장할 필요가 없다고 생각이 들어서 WinningLottoTicket 에서 BonusBall 을 없애고 LottoNumber 를 이용하였습니다.

2020-02-23 09:09 UTC, giantim commented on src/main/java/domain/LottoNumbers.java
> +        lottoNumbers = IntStream.rangeClosed(1, 45)
static 으로 LottoNumbers 를 만들어 놓고서 구현해봤습니다.
기존 페어와 계획했던 방법도 숫자 풀을 만들어 놓고서 사용하려고 했었는데 클래스 메서드를 이용하는것이 익숙하지 않고 어려워서 인스턴스를 만들어서 구현했었습니다. 이번에 리뷰 받고 다시 구현해보면서 클래스 메서드를 사용하도록 수정하였습니다 :D

2020-02-25 16:09 UTC, jeonghoon1107 requested changes
안녕하세요 라빈!
구현 잘 하셨네요 👍 
몇가지 피드백을 남겼으니 확인해주세요 :)

2020-02-25 16:09 UTC, jeonghoon1107 commented on src/main/java/domain/WinningCalculator.java
> +public class WinningCalculator {
OutputView에 money와 calculator를 넘기지 않고
Result를 담당하는 용도로 ProfitCalculator와 합쳐도 좋을 것 같아요!

2020-02-25 16:09 UTC, jeonghoon1107 commented on src/test/java/domain/LottoNumberTest.java
> +        Assertions.assertThat(same).isTrue();
Assertions.assertThat(lottoNumber).isEqualTo(new LottoNumber(10)) 가 더 깔끔할 것 같아요.
아래도 마찬가지!

2020-02-25 16:09 UTC, jeonghoon1107 commented on src/test/java/domain/LottoNumbersTest.java
> +    @DisplayName("shuffle 기능 테스트")
의미있는 테스트같지 않아요!

2020-02-25 16:09 UTC, jeonghoon1107 commented on src/test/java/domain/LottoTicketGeneratorTest.java
> +    void equalsTest() {
LottoNumberTest에 남긴 피드백을 참고해주세요!

2020-02-25 16:09 UTC, jeonghoon1107 commented on src/test/java/domain/LottoTicketTest.java
> +    void lottoTicketConstructorTest(List<LottoNumber> lottoNumbers) {
무슨 테스트인가요?
의도가 명확하게 드러나면 좋겠어요

2020-02-25 16:09 UTC, jeonghoon1107 commented on src/test/java/domain/LottoTicketTest.java
> +        Assertions.assertThat(lottoTicket.containLottoNumber(new LottoNumber(5))).isTrue();
containsExactly 등을 공부해보세요!

2020-02-25 16:09 UTC, jeonghoon1107 commented on src/main/java/LottoApplication.java
> +        LottoController.getBonusBall(winningLottoTicket, InputViewer.inputBonusBallNumber());
객체를 만든 후에 보너스볼만 set하는 방식말고
보너스볼을 받은 후에 WinningLottoTicket을 만들면 어떨까요?

2020-02-26 01:27 UTC, giantim commented on src/main/java/LottoApplication.java
> +        LottoController.getBonusBall(winningLottoTicket, InputViewer.inputBonusBallNumber());
로또 프로그램이 동작하는 순서로 보면 당첨 번호 입력 -> 보너스 볼 입력 순서인데 만약 사용자가 당첨 번호를 입력할 때 잘못된 입력값을 입력했을 때 예외 메시지를 출력하고 사용자에게 정상 입력값을 입력 받은 후에 보너스 볼을 입력 받기 위해서 위와 같이 설계했습니다.
제 설계 방식이 잘못되었거나 어색한 흐름이 있다면 조언 해주실 수 있을까요?

2020-02-26 01:28 UTC, giantim commented on src/test/java/domain/LottoTicketTest.java
> +    void lottoTicketConstructorTest(List<LottoNumber> lottoNumbers) {
DisplayName 에 좀 더 구체적으로 무엇을 테스트 하는지 적었습니다!

2020-02-26 01:32 UTC, giantim commented on src/test/java/domain/LottoNumbersTest.java
> +    @DisplayName("shuffle 기능 테스트")
이 부분에 대해서는 수정하지 않고 push 하고 질문 드릴 내용이 있습니다!
제가 이 shuffle 을 테스트 한 이유는 LottoNumbers.shuffleLottoNumbers() 라는 메소드를 실행하면 로또 숫자 풀이 정말 섞인다는 기능을 보장해주기 위해서 테스트 했습니다.
이런 의도를 갖고서 테스트 코드를 작성하는 일은 의미가 없을까요?

2020-02-26 01:35 UTC, giantim commented on src/test/java/domain/LottoNumberTest.java
> +        Assertions.assertThat(same).isTrue();
Assertions 에서 기본적으로 제공하는 메서드들을 활용하여 깔끔한 테스트 코드로 변경했습니다!
Assertions 에서 제가 테스트 하는 의도에 맞는 메서드가 있는지 먼저 찾아보고 테스트 코드를 작성 하도록 하겠습니다!

2020-02-26 02:38 UTC, giantim commented on src/main/java/domain/WinningCalculator.java
> +public class WinningCalculator {
이 부분에 대해서는 수정하지 않고 push 하고 질문 드릴 내용이 있습니다!
제가 ProfitCalculator 를 객체로 만든 이유는 WinningCalculator 에서는 자동으로 생성된 복권 중에서 당첨 복권의 개수를 계산한 결과를 이용해서 수익률만 계산하기 위해서 객체로 만들었습니다. 그런데 말씀해주신대로 ProfitCalculator 가 Result 를 담당하게 된다면 WinningCalculator 에서 계산한 결과를 ProfitCalculator 도 가져야 하는 것 아닌가요? 이렇게 된다면 데이터가 중복되는 결과가 생길 것 같습니다.
혹시 제가 잘못 이해했거나 객체의 책임을 잘못 설계한 부분이 있다면 조언 해주실 수 있을까요?

2020-02-27 14:39 UTC, jeonghoon1107 approved these changes
안녕하세요 라빈!
리팩토링 잘 하셨네요 👍 
DM으로 같이 이야기 했던 것들에 대한 수정은 다음 단계에서 반영해주세요 :)

2020-02-27 14:39 UTC, jeonghoon1107 commented on src/main/java/LottoApplication.java
> +        LottoController.getBonusBall(winningLottoTicket, InputViewer.inputBonusBallNumber());
그렇다면 winningLottoTicket을 반환하면 좋을 것 같아요.
현재 메서드 네이밍도 getBonusBall 인데 역할이 맞지 않는 것 같네요!

2020-02-27 14:39 UTC, jeonghoon1107 commented on src/main/java/domain/WinningCalculator.java
> +public class WinningCalculator {
**ProfitCalculator 가 Result 를 담당하게 된다면 WinningCalculator 에서 계산한 결과를 ProfitCalculator 도 가져야 하는 것 아닌가요?** -> 
결과를 담당하는 객체는 하나만 있어도 충분할 것 같아요.
현재는 역할이 분산되어있네요.
WinningCalculator와 ProfitCalculator 두 클래스를 합쳐도 될 것 같다는 의견이었습니다!

2020-02-27 14:39 UTC, jeonghoon1107 commented on src/main/java/domain/WinningCalculator.java
> +public class WinningCalculator {
**ProfitCalculator 가 Result 를 담당하게 된다면 WinningCalculator 에서 계산한 결과를 ProfitCalculator 도 가져야 하는 것 아닌가요?** -> 
결과를 담당하는 객체는 하나만 있어도 충분할 것 같아요.
현재는 역할이 분산되어있네요.
WinningCalculator와 ProfitCalculator 두 클래스를 합쳐도 될 것 같다는 의견이었습니다!

2020-02-27 14:58 UTC, merged