[제이미] 로또 1단계 미션 제출합니다.
woowacourse/java-lotto pull request #131
Opened 2020-02-20 08:23 UTC by jamie9504

감사합니다 (_ _)

2020-02-22 03:31 UTC, phs1116 requested changes
안녕하세요, 제이미! 리뷰어 화투입니다. :)
객체간의 책임 분리를 상당히 잘해주셨어요. 👍 
몇가지 피드백 추가했는데, 참고 부탁드릴게요.
궁금하신 점 있으시면 연락주세요. :)

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/LottoApplication.java
> +				return money.getCount();
count 보다는 LottoCount로 더 명시적으로 작성해주시는게 좋을 것 같네요 :)

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Ball.java
> +    }
캐시로 미리 생성하시는군요, 👍

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Ball.java
> +    private static final Map<Integer, Ball> ballCaches = new HashMap<>();
static final 네이밍 컨벤션은 대문자에요. :)

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Ball.java
> +        return new Ball(number);
로또 범위에 해당하는 값은 다 생성을 해놨으니 예외를 던지는게 더 좋지않을까요?

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Ball.java
> +    private final int number;
값객체로서 보장을 했다면 equals, hashCode 또한 구현해주는게 좋을 것 같습니다. :)
`이펙티브 자바 아이템 10. equals는 일반 규약을 지켜 재정의하라,
아이템 11. equals를 재정의하려거든 hashCode도 재정의하라`

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Ball> balls;
List를 사용할 이유가 없다면 Set을 자료구조로 사용해도 괜찮을 것 같네요. :) 
contains등의 로직도 더 성능도 좋을거구요.

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Money.java
> +    public static int getBuyMoney(LottoCount lottoCount) {
리턴 타입으로 Money가 더 적합하지 않나 싶네요. : )

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Prize.java
> +    public Prize(long prize) {
'돈'에 대한건 Money 값객체로 쓰기로 했으면 도메인 내에서는 다 이걸로 쓰는것도 연습해보아요. :)

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Money.java
> +public class Money {
값객체로서 의미를 가지려면 Ball과 마찬가지로 equals, hashCode를 구현해주세요. :)
이를 이용해야 '값'에 대해서 동등성이 보장이 되요. :)
[동일성과 동등성](http://wonwoo.ml/index.php/post/593)

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/LottoFactory.java
> +public interface LottoFactory {
인터페이스 분리 👍

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/WinningLotto.java
> +        }
해당 책임도 응집력 있게 LottoRank가 가져가도록 해보면 어떨까요? :)

2020-02-22 03:31 UTC, phs1116 commented on src/main/java/lotto/domain/Ball.java
> +public class Ball implements Comparable<Ball> {
값객체 분리 👍

2020-02-22 09:52 UTC, jamie9504 commented on src/main/java/lotto/domain/Ball.java
> +    private static final Map<Integer, Ball> ballCaches = new HashMap<>();
넵!

2020-02-22 09:53 UTC, jamie9504 commented on src/main/java/lotto/LottoApplication.java
> +				return money.getCount();
넵~!

2020-02-22 09:59 UTC, jamie9504 commented on src/main/java/lotto/domain/Ball.java
> +        return new Ball(number);
이 부분은 예외를 여기서 바로 던지게 되면 예외를 관리하는 곳이 두 개가 되어서, 생성자를 통해 에러를 던지게 해두었습니다만,
 만약 생성자를 통해 던지지 않고 여기서 예외를 던지는게 더 좋다면, 생성자의 유효성 검사 부분을 메서드로 분리하고 메서드로 분리한 유효성 검사를 해당 부분에 적용하는 것이 좋을 것 같아요!
 혹시 어떻게 생각하시나요?

2020-02-22 10:04 UTC, jamie9504 commented on src/main/java/lotto/domain/Ball.java
> +    private final int number;
넵! 이 부분은 일단 인텔리제이를 통해 생성했는데요,
잘 모르는 부분이라 공부해보도록 하겠습니다 (_ _)

2020-02-22 10:09 UTC, jamie9504 commented on src/main/java/lotto/domain/Money.java
> +public class Money {
값 객체가 원시값을 포장한 객체군요!
넵 적용해보았습니다!

링크 감사합니다(_ _) 오늘 바로 공부해보겠습니다!
- 이펙티브 자바 10장 / 11장 & 동일성과 동등성

2020-02-22 12:37 UTC, jamie9504 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Ball> balls;
Set으로 사용하는 것으로 변경해보았습니다.

Sort된 List는 크게 성능 차이가 나지 않는다고 생각했는데, 그래도 Set으로 관리하는 것이 더 좋은 것 같습니다! (중복도 따로 체크를 안해도 되어 좋습니다)

감사합니다

2020-02-22 12:58 UTC, jamie9504 commented on src/main/java/lotto/domain/Prize.java
> +    public Prize(long prize) {
설계시 money는 구매금액 관련된 처리, prize는 당첨금액 관련된 처리를 생각했는데요,
(현재는 검증조건이 당첨금액의 경우 구매금액에 녹일 수 있지만, 추후에 분리될 수 있다고 생각했습니다!)

money를 사용하는 것으로 리팩토링해보았습니다!

2020-02-22 13:01 UTC, jamie9504 commented on src/main/java/lotto/domain/Money.java
> +    public static int getBuyMoney(LottoCount lottoCount) {
Money에 getter를 만들지 않으려다보니 이렇게 했었던 것인데,
리턴 타입으로 int를 주면 가공이 가능하니 Money로 주는 것이 더 나을 것 같네요 :)

감사합니다!

2020-02-22 13:40 UTC, jamie9504 commented on src/main/java/lotto/domain/WinningLotto.java
> +        }
수정해보았습니다!

2020-02-23 07:49 UTC, phs1116 approved these changes
안녕하세요, 제이미!
리뷰어 화투입니다.
피드백 반영 및 구현 깔끔하게 잘해주셨어요. 👍 
1단계 머지할게요.
질문주신 사항에 대해서 코멘트 추가했는데 참고 부탁드릴게요. :)

2020-02-23 07:49 UTC, phs1116 commented on src/main/java/lotto/domain/Ball.java
> +        return new Ball(number);
반대로 생각해보자면, Ball of라는 메서드 자체가 무조건 캐시에 저장되어있는 값을 꺼낸다는게 코드만으로 표현이 되지 않을까요?
생성자에서 책임지는 예외와 여기서 발생하는 예외는 발생 원인이 달라야 할 것 같아요.

생성자는 '생성이 불가'
static factory method는 '캐시에 존재하지 않는 객체'

로직상의 오류로 캐시들이 미리 생성되지 않을 경우 원래 의도한바로는 동작하지 않지만 
코드는 동작해서 이슈를 찾기 쉽지도 않을 것 같구요!

2020-02-23 07:49 UTC, phs1116 commented on src/main/java/lotto/domain/Ball.java
> +    private final int number;
인텔리제이를 활용해도 충분합니다. :)
요새는 생성해주는 라이브러리도 많아서 직접 구현보다는 왜 필요한지에 대해 집중해서 보시면 될 것 같아요!

2020-02-23 07:49 UTC, phs1116 commented on src/test/java/lotto/domain/LottoRankTest.java
> +        assertThat(LottoRank.getRank(6, true)).isEqualTo(LottoRank.FIRST);
어느 케이스에서 실패를 하는지 쉽게 파악하기위해 여기서도 parameterizedTest를 활용하면 좋을 것 같네요. :)

2020-02-23 07:49 UTC, merged

2020-02-25 00:45 UTC, jamie9504 commented on src/main/java/lotto/domain/Ball.java
> +        return new Ball(number);
앗 그렇게 생각하니 맞는 것 같습니다!

생성자는 생성이 불가하는 것만 나타내고,
factory method는 캐시에서 값을 꺼내는 것만 나타내면, 읽을 때 확실히 더 또렷하게 보이겠네요!

2020-02-25 00:45 UTC, jamie9504 commented on src/main/java/lotto/domain/Ball.java
> +    private final int number;
넵 감사합니다!

2020-02-25 00:49 UTC, jamie9504 commented on src/test/java/lotto/domain/LottoRankTest.java
> +        assertThat(LottoRank.getRank(6, true)).isEqualTo(LottoRank.FIRST);
모두 다 성공하는 케이스인데, 어떤식으로 parameterizedTest를 이용하면 좋을까요?

매치 카운트와 보너스볼 true false만 넣자니, 뭔가 더 잘 안보이는 느낌이 들어서요!