[시카] 로또 1단계 미션 제출합니다.
woowacourse/java-lotto pull request #133
Opened 2020-02-20 08:25 UTC by dks301

안녕하세요.
우테코 크루 시카입니다 :)

잘 부탁드립니다 !! 감사합니다

2020-02-21 13:23 UTC, jaeyeonling requested changes
안녕하세요 시카 리뷰를 맡은 재연링입니다!
요구사항에 맞게 잘 구현해주셨어요. 👍 
몇 가지 코멘트 남겼으니 확인하시고 궁금하신 점 있으면 DM 주세요 :)
좋은 주말 보내세요~

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/domain/WinningNumber.java
> +	private static final int MAX_LOTTO_NUMBER = 45;
같은 뜻을 가지는 상수가 여러 곳에 존재하고 있습니다.
중복을 제거하면 어떠한 장점이 있을까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/domain/WinningNumber.java
> +public class WinningNumber {
WinningLotto라는 이름이 더욱 적절해보여요!

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/controller/LottoController.java
> +			OutputView.printWrongBonusNumberInput();
해당 `Exception`에서 `printWrongBonusNumberInput`에서 출력하는 메시지와 다른 상황이 올 경우 디버깅이 힘들어질 수 있어요.
`e.getMessage()`를 사용하여 출력한다면 이러한 문제를 해결할 수 있지 않을까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lottos.java
> +	public LottoDtos makeLottoDtos() {
DTO에서 도메인을 받아 DTO를 생성
도메인에서 DTO를 생성
DTO 생성만을 담당하는 곳에서 DTO를 생성

각 상황에 어떠한 차이가 있을지 고민해보아요

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lottos.java
> +		this.lottos = lottos;
외부에서 `lottos`의 값을 변경한다면 어떠한 일이 발생할까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/utils/InputUtil.java
> +		return Arrays.asList(bufferedReader.readLine().replace(SPACE, EMPTY).split(SPLIT_DELIMITER, SPLIT_LIMIT));
> 규칙 4: 한 줄에 점을 하나만 찍는다.

해당 규칙을 적용하면 어떠한 장점이 있을까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/controller/LottoController.java
> +	public static WinningNumber receiveWinningNumber() {
read-로 시작하는 이름와 receive-로 시작하는 이름의 규칙이 있을까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/controller/LottoController.java
> +			e.printStackTrace();
printStackTrace로 출력하는 것과 printExceptionMessage로 출력하는 규칙이 있을까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lotto.java
> +	private static final int LOTTO_SIZE = 6;
`Lotto.LOTTO_SIZE`에서 `Lotto`가 중복이 되고 있어요.
`Lotto.SIZE`라는 네이밍은 어떨까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lotto.java
> +		if (lottoNumber.size() != new HashSet<>(lottoNumber).size()) {
해당 조건은 한줄로 간결하게 작성할 수 있지만 가독성은 떨어져요.
`new HashSet<>(lottoNumber).size()`에 변수명을 부여하여 코드의 해석 없이 코드를 읽을 수 있도록 수정해보면 좋겠어요.

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lotto.java
> +		int matchCount = (lottoNumber.size() * 2) - overlapNumbers.size();
매직 넘버란 코드 안에 작성된 구체적인 숫자 혹은 문자열을 말합니다. 그리고 매직 넘버의 단점은 아래와 같습니다.

* 의미를 이해하기 어렵다.
* 복수의 장소에서 사용된다면 변경하기 힘들다.

매직 넘버를 의미를 나타낼 수 있는 상수로 치환하여 코드의 가독성을 높여 보는 것은 어떨까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/test/java/lotto/domain/LottoTest.java
> +	void 로또가_null이나_빈값인_경우(List<Integer> value) {
jUnit5에서는 `@DisplayName`을 이용하여 의미를 전달하실 수 있습니다.
만약 한글로 메서드명을 짓는것을 의도하였다면 클래스에 `@SuppressWarnings("NonAsciiCharacters")`를 적용하여 IDE의 경고를 제거해보시는게 어떨까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/dto/LottoCountDto.java
> +public class LottoCountDto {
DTO란 데이터 전송만을 담당하는 일종의 구조체와 같은 역할을 합니다.
하지만 `LottoCountDto`는 `money`를 `lottoCount`로 변경하는 로직을 가지고 있는데요.
DTO의 역할인 데이터 전송만을 담당해보는 것이 어떨까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/test/java/lotto/domain/WinningPrizeTest.java
> +	@CsvSource(value = {"6,false,1등", "5,true,2등(보너스볼 일치)", "3,true,5등", "2,false,미당첨"})
메시지의 경우 변경 가능성이 높기 때문에 테스트하지 않는 것을 선호합니다.
중요도가 높은 비즈니스와 관련된 부분만 테스트해보면 어떨까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/view/OutputView.java
> +	public static void printLottoResult(List<WinningPrize> winningPrizes) {
```suggestion
	public static void printLottoResult(LottoResult lottoResult) {
```

lottoResult에 대한 값을 OutputView에서 구하는 것이 아닌 도메인이 담당하도록 수정하면 어떠한 차이가 있을까요?

2020-02-21 13:23 UTC, jaeyeonling commented on src/main/java/lotto/controller/LottoController.java
> +	public static void run() {
만약 1등이 여러번 당첨되면 의도한 바와 같이 동작할까요!?

2020-02-22 05:42 UTC, dks301 commented on src/main/java/lotto/domain/WinningNumber.java
> +	private static final int MAX_LOTTO_NUMBER = 45;
모두 하나의 객체에서 public으로 선언하여 가져다 쓰도록 수정하였습니다.
```
public class Lotto {
	public static final int SIZE = 6;
}
```

```
public class LottoNumber implements Comparable<LottoNumber> {
	public static final int MINIMUM = 1;
	public static final int MAXIMUM = 45;
```
장점으로는 지금처럼 리팩토링시에 모두 수정을 안하고 변경 범위가 최소화되어 좋을 것 같습니다 :)

2020-02-22 05:43 UTC, dks301 commented on src/main/java/lotto/domain/WinningNumber.java
> +public class WinningNumber {
수정했습니다!

2020-02-22 05:56 UTC, dks301 commented on src/main/java/lotto/domain/Lotto.java
> +	private static final int LOTTO_SIZE = 6;
이름이 중복되는 상수들 모두 수정했습니다!

2020-02-22 06:00 UTC, dks301 commented on src/main/java/lotto/domain/Lotto.java
> +		if (lottoNumber.size() != new HashSet<>(lottoNumber).size()) {
`boolean isDuplicate = lottoNumber.size() != new HashSet<>(lottoNumber).size();`
전체에 변수명을 부여해서 코드 해석없이 이해할 수 있도록 수정했습니다.

2020-02-22 06:04 UTC, dks301 commented on src/main/java/lotto/domain/Lotto.java
> +		int matchCount = (lottoNumber.size() * 2) - overlapNumbers.size();
로또 번호를 LottoNumbers로 포장하여
```
public WinningPrize findLottoPrize(WinningLotto winningLotto) {
	int matchCount = lottoNumbers.matchCount(winningLotto.getWinningNumber());
	boolean bonusMatch = lottoNumbers.contains(winningLotto.getBonusNumber());

	return WinningPrize.of(matchCount, bonusMatch);
}
```
로 수정했습니다.

실제 구현할 때 지적해주신 부분을 알고 있었지만, 적당한 이름을 못찾아서 그냥 사용했습니다 😭

2020-02-22 06:06 UTC, dks301 commented on src/test/java/lotto/domain/LottoTest.java
> +	void 로또가_null이나_빈값인_경우(List<Integer> value) {
적용했습니다!

2020-02-23 04:20 UTC, dks301 commented on src/main/java/lotto/controller/LottoController.java
> +			e.printStackTrace();
BufferedReader.readLine() 사용으로 발생하는 IOException은 사용자에게 보여줄것이라기 보다는 개발자가 봐야한다고 생각해서 printStackTrace로 출력했습니다.
반대로 사용자에게 보여줘야할 예외라고 판단한 것들은 pirntExcpetionMessage로 출력했습니다.

2020-02-23 04:26 UTC, dks301 commented on src/main/java/lotto/controller/LottoController.java
> +			OutputView.printWrongBonusNumberInput();
`Integer.parseInt`의 `NumberFormatException`에도 사용자에게 상황별로 알려줘야 한다고 생각해서 따로 출력을 했습니다. `e.getMessage()`를 사용하면 사용자는 원인을 알 수가 없을것 같아서요.
그런데 디버깅이 힘들어질 수 있는 것은 생각을 못했습니다 😢
일단 두 가지를 모두 출력하도록 수정했습니다!

2020-02-23 06:05 UTC, dks301 commented on src/main/java/lotto/domain/Lottos.java
> +	public LottoDtos makeLottoDtos() {
1. DTO에서 도메인을 받아 DTO를 생성 - DTO를 수정하거나 삭제했을 때 도메인을 건드리지 않고 수정 삭제가 가능할것 같습니다.

2. 도메인에서 DTO를 생성 - 지금 이렇게 구현이 되어있는데 수정이 될때마다 도메인과 DTO를 모두 수정해줘야해서 안좋은 것같아 1로 수정했습니다.

3. DTO 생성만을 담당하는 곳에서 DTO를 생성 - DTO가 지금보다 많아진다면 한 곳에서 관리할 수 있어 불필요한 중복 코드가 제거되어 수정이나 관리가 편할 것 같습니다.

추가적으로 DTO는 view에서 보여줄 정보를 담고있기 때문에 수정이 많이된다고 해서 2번 사용은 앞으로 지양하겠습니다 :)

2020-02-23 06:48 UTC, dks301 commented on src/main/java/lotto/domain/Lottos.java
> +		this.lottos = lottos;
구현과정에서 lottos의 값이 변경이 안되는 것을 명시적으로 표현해주려고 final로 설정했습니다.
물론 내부적으로 `lottos.getLottos().get(0).getLottoNumbers().getLottoNumbers().get(0)` 해서 안쪽까지 접근할 수 있지만 모두 private이고 setter메소드가 없어서 값 변경이 안될 것 같습니다.

만약 값 변경이 된다면 null, empty말고도 다른 예외사항을 체크해야할 것 같습니다!

2020-02-23 06:53 UTC, dks301 commented on src/main/java/lotto/utils/InputUtil.java
> +		return Arrays.asList(bufferedReader.readLine().replace(SPACE, EMPTY).split(SPLIT_DELIMITER, SPLIT_LIMIT));
에러 발생시에 어디에서 발생한건지를 확실하게 알 수 있다는 장점이 있다고 알고 있습니다.
이 부분은 구현하면서 빼먹은거 같습니다 😞  수정했습니다!

2020-02-23 06:58 UTC, dks301 commented on src/main/java/lotto/controller/LottoController.java
> +	public static WinningNumber receiveWinningNumber() {
수정전에 WinningLotto 객체 명이 WinningNumber라 read로 지으면 readWinningNumber()와 중복되어 receive로 했습니다. 객체명이 모호해서 생긴일인 것 같습니다.
readWinningLotto()로 수정했습니다 :)

2020-02-23 07:10 UTC, dks301 commented on src/main/java/lotto/dto/LottoCountDto.java
> +public class LottoCountDto {
너무 간단한 로직이라 구현할 때 로직이 없다고 착각했었던 것 같습니다.
LottoCount객체를 만들어서 DTO와 분리했습니다!

2020-02-23 07:13 UTC, dks301 commented on src/test/java/lotto/domain/WinningPrizeTest.java
> +	@CsvSource(value = {"6,false,1등", "5,true,2등(보너스볼 일치)", "3,true,5등", "2,false,미당첨"})
메시지가 아니라 WinningPrize의 name을 사용하도록 수정했습니다!

2020-02-23 08:27 UTC, dks301 commented on src/main/java/lotto/view/OutputView.java
> +	public static void printLottoResult(List<WinningPrize> winningPrizes) {
구현할 때는 lottoResult 자체가 view에 보여주기 위한 것이라고 생각해서 OutputView에 구현했는데요,
지적해주셔서 생각해보니 도메인이 담당해야 추후에 콘솔 뷰가 아니라 다른 곳에서 결과를 보여줘야할 때 다시 구현해야하는 문제점이 있는 것 같습니다 😮  
LottoResult객체를 받아와서 출력하도록 수정했습니다!

2020-02-23 08:29 UTC, dks301 commented on src/main/java/lotto/controller/LottoController.java
> +	public static void run() {
생각을 해보았지만 동작할 것 같습니다 😭 
왜 그렇게 생각하셨는지 알고 싶습니다

2020-02-23 23:42 UTC, jaeyeonling requested changes
피드백 반영을 잘 해주셨습니다 👍 
질문에 대한 답변 드렸으니 확인하시고 반영해주세요!
궁금하신 점 있으시면 편하게 DM주세요!

2020-02-23 23:42 UTC, jaeyeonling commented on src/main/java/lotto/controller/LottoController.java
> +	public static void run() {
1등이 여러 명이 될 경우 상금의 범위가 Int를 벗어날 것 같아요!

2020-02-23 23:42 UTC, jaeyeonling commented on src/main/java/lotto/controller/LottoController.java
> +			e.printStackTrace();
확인 감사합니다 👍

2020-02-23 23:42 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lottos.java
> +		this.lottos = lottos;
```java
List<Lotto> rawLottos = ~;

// validateNullAndEmpty 통과
Lottos lottos = new Lottos(rawLottos);

// !!!
rawLottos.clear();

클라이언트가 위와 같이 사용할 경우 올바르지 않게 동작할 수 있을 것 같은데 어떻게 생각하시나요!?
```

2020-02-23 23:42 UTC, jaeyeonling commented on src/main/java/lotto/utils/InputUtil.java
> +		return Arrays.asList(bufferedReader.readLine()
https://github.com/woowacourse/java-lotto/pull/133#discussion_r382969978 피드백에 추가 답변을 드리자면

1. 가독성 상승
2. IntelliJ 사용 시 힌트 확인 가능

등의 장점도 있습니다!

2020-02-24 02:48 UTC, dks301 commented on src/main/java/lotto/domain/Lottos.java
> +		this.lottos = lottos;
`this.lottos = new ArrayList<>(lottos);`로 참조가 아닌 Lotto값 자체를 deepCopy 하도록 수정했습니다 :)

2020-02-24 02:51 UTC, dks301 commented on src/main/java/lotto/controller/LottoController.java
> +	public static void run() {
```
public long calculateEarningRate() {
	long totalEarning = INITIAL_EARNING;
```
long type으로 변경했습니다

2020-02-24 15:15 UTC, jaeyeonling approved these changes
코멘트 반영 잘 해주셨어요 💯 
해당 요청은 머지하도록 하겠습니다. 
고생하셨습니다 :)

2020-02-24 15:16 UTC, merged