[히로] 로또 1단계 - 자동 미션 제출합니다.
woowacourse/java-lotto pull request #134
Opened 2020-02-20 08:25 UTC by hotheadfactory

안녕하세요. 우테코 크루 히로입니다.
이번 미션은 stream과 일급컬렉션, DTO의 사용 연습에 중점을 두어 해 보았습니다.
잘 부탁드립니다 :smile:

2020-02-22 06:33 UTC, Hue9010 requested changes
이번 리뷰를 맡은 휴입니다! :)
개인 사정으로 인해 피드백이 늦었습니다 😭
몇가지 피드백이랑 문의드렸는데 확인 부탁드려요!

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +	private final List<Integer> lottoNumber;
final 키워드를 많이들 사용하셨던데 final은 기능적으로는 재할당만 금지하게 됩니다. 다른 리스트로의 재할당은 안되지만 리스트 내부의 값은 변경될 여지가 존재합니다.
그래서 수정이 불가능한 리스트가 필요할 때 사용하기 위해서 Collections.unmodifiableList()이 있답니다 👍 

그런면에서 어떤 목적으로 final 키워드를 사용하셨는지 궁금합니다. 재할당만 막는 목적으로 사용하셨다면 애초에 재할당 시에 컴파일 단에서 에러가 났을테니 지금은 문제가 없고, 값 변화를 막고 싶으셨다면 현재기준으론 리스트 내의 값이 변하는 부분이 없어 문제 없지만 다른 작업자가 리스트 내의 값을 바꾸게 수정할 수도 있답니다.

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +		int matchCount = (lottoNumber.size() * 2) - concatenatedSet.size();
`(lottoNumber.size() * 2)`가 아니라 `LOTTO_SIZE * 2`는 어떨까요?

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/domain/WinningNumber.java
> +			.isPresent()) {
`ifPresent`를 사용해보세요 😸

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/domain/WinningPrize.java
> +	public int getMatchCount() {
미사용 코드는 제거!

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/view/OutputView.java
> +		for (WinningPrize winningPrize : WinningPrize.values()) {
만약에 OutPutView과 지금과 같은 콘솔이 아니라 웹페이지라면 어떨까요?
웹페이지일 경우 OutPutView의 다른 부분들은 문제가 없을 것 같은데 `WinningPrize.values()` 에 한해서는 웹페이지에서는 알 방법이 없답니다.
view에서는 기능에 대한 호출은 자제해주시는게 좋습니다. `WinningPrize.values()`를 단순히 제거하는 방향이 아니라 생각보다 결과 합산을 하는 과정이 복잡해 보이는데 로또 경기에 대한 결과를 책임지는 객체를 추가하는 건 어떨까요?

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
`InputUtil`와 `InputView`를 분리할 필요가 있을까요?
웹페이지로 생각해보면 입력화면에 안내문구와 함께 입력 창이 함께 존재하죠!

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoController.java
> +			OutputView.printLottoCount(lottoCountDto.getLottoCount());
DTO는 이름 그대로 Data Transfer Object이고 LottoCountDto의 lottoCount는 DTO가 아닙니다.
DTO를 DTO스럽게 사용하고자 한다면 getLottocount가 아니라 lottoCountDto를 전달해줘야 할것 같네요.

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoController.java
> +			OutputView.printLottoCount(lottoCountDto.getLottoCount());
한가지 궁금한 부분은 DTO를 학습하시는 목적이 무엇인지 궁금합니다. 특히나 DTO에 대한 부분은 과정 상 따로 학습이 진행되지 않은걸로 보이는데 말이죠(교육 자료로 봤을 땐 말이죠..ㅎㅎ)
단순히 getter/setter를 DTO로 모두 옮겨 놓을 목적이라면 dto로의 변환 메서드, 변환 과정으로 인해 득보다 실이 많아보이네요.
혹은 DTO를 만들어서 나았다 싶었던 부분이 있었을지 궁금합니다!

+ 학습의 목적을 위해 진행하시는 부분인걸 알기 때문에 잘못됐다 잘됐다가 아니라 같이 얘기 해보고 싶어서 문의 드리는거니까 겁먹지 말아주세요!!! 😋

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/domain/WinningNumber.java
> +		return winningNumber;
여기서 질문!
`private final List<Integer> winningNumber;`이 winningNumber의 변경이 막고자 함이 아니였다면 패스하셔도 됩니다!
만약 winningNumber이 불변함을 보장하고 싶으신 의도가 있으신 것이라면 `getWinningNumber`을 통해 전달 된 winningNumber의 사용처에서 리스트에 값을 추가하면 어떻게 될까요?

final 키워드 질문 드린 것과 이어진답니다! 😄

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/domain/WinningPrize.java
> +	FIRST(6, 2_000_000_000, "1등");
Underscores에 대해서 많이들 모르는데 잘 쓰셨네요 👍

2020-02-22 06:33 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +			throw new IllegalArgumentException("null이나 빈 값은 들어올 수 없습니다!");
교육과정을 보면 커스텀 Exception에 대해 학습 한 걸로 보이는데 그게 맞다면 한번 LottoException을 만들어보세요 😄

2020-02-23 01:02 UTC, hotheadfactory commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
출력과 입력을 딱 잘라서 나누는 것이 좋다고 생각하여 한번 나누어 보았는데, 
안내 문구와 입력 창은 서로 밀접한 관계인만큼 같이 있는게 좋다는 말씀이시죠?
`inputUtil`로 통합해 보겠습니다!

2020-02-23 01:14 UTC, hotheadfactory commented on src/main/java/lotto/domain/WinningNumber.java
> +		return winningNumber;
final은 재할당만 금지하기 때문에 리스트에 값을 추가할 수는 있지요ㅠㅠ
이래서 getter 사용을 지양하는 것이 맞는데 저희는 어쩔수 없이 사용한 상태였습니다.
일단 Collections.unmodifiableList로 감싸서 return 하도록 수정했습니다!

2020-02-23 01:15 UTC, hotheadfactory commented on src/main/java/lotto/domain/WinningPrize.java
> +	FIRST(6, 2_000_000_000, "1등");
이 영광을 페어인 시카에게 돌립니다 :)
저는 이런 기능이 있는 줄 몰랐는데 사용해 보니 자릿수 계산할 때 편하고 좋았습니다.

2020-02-23 01:19 UTC, hotheadfactory commented on src/main/java/lotto/domain/Lotto.java
> +	private final List<Integer> lottoNumber;
생성자에서
`this.lottoNumber = Collections.unmodifiableList(lottoNumber);`
이렇게 수정하여 수정할 수 없도록 바꾸었습니다!
혹시 다른 좋은 방법이 있을까요???

2020-02-23 01:23 UTC, hotheadfactory commented on src/main/java/lotto/domain/WinningNumber.java
> +			.isPresent()) {
ifPresent를 사용해 보려다가 잘 안 되어서 if문을 썼는데, 람다식이었군요ㅋㅋ;;

2020-02-23 06:07 UTC, Hue9010 commented on src/main/java/lotto/domain/WinningPrize.java
> +	FIRST(6, 2_000_000_000, "1등");
사실 저도 네달 전에 알았어요 😸

2020-02-23 06:25 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +	private final List<Integer> lottoNumber;
사실 질문 드린 이유 중 하나는 말씀드린 부분을 아닌지 아닌지 알고 계신지 확인을 하고자 함이였습니다.
어떤 목적을 가지신지에 따라 방법이 나뉠 것 같습니다.

불변을 목적으로 사용했고 불변하게 관리가 안된다 - 목적에 부합하지 않으므로 final 삭제
불변하진 않지만 재할당은 막는다 - final 유지
불변하게 유지하고 싶다 - 간단하게는 LottoDto 생성자에 deep copy한 lottoNumber를 전해주는 방법이 있을 것 같네요.

어느것이 잘못됐다가 아니라 의도한대로 구현되어 있는지가 중요합니다. 👍

2020-02-23 06:32 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
InputView는 말그대로 입력화면인데 입력이 미존재하고 어떻게 보면 출력만 존재하는 상태로 보입니다.
간단히 떠올려 보면 로그인 페이지를 입력화면으로 생각하면 안내 문구와 입력 창이 존재하죠.

2020-02-23 16:00 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
> +			OutputView.printLottoCount(lottoCountDto.getLottoCount());
getter/setter를 없애기 위해서 DTO 공부를 시작한건 맞지만, 그 과정에서 DTO에서 값 검증도 가능하다는 사실을 알고 활용하려고 노력해 봤습니다!

2020-02-23 17:06 UTC, hotheadfactory commented on src/main/java/lotto/domain/Lotto.java
> +			throw new IllegalArgumentException("null이나 빈 값은 들어올 수 없습니다!");
LottoException 적용했습니다 :smile:

2020-02-23 17:08 UTC, hotheadfactory commented on src/main/java/lotto/view/OutputView.java
> +		for (WinningPrize winningPrize : WinningPrize.values()) {
로또 결과를 책임지는 `LottoResult` 클래스를 새로 만들었습니다. 

굳이 `winningPrize.values()`를 불러온 건 HashMap에서 등수가 뒤죽박죽이 되어버려서였는데, LinkedHashMap을 사용해 해결했습니다.

2020-02-24 10:21 UTC, hotheadfactory commented on src/main/java/lotto/domain/Lotto.java
> +	private final List<Integer> lottoNumber;
`final`이 없으면 `Collections.unmodifiableList` 라고 해도 재할당은 가능하므로, 수정과 재할당 모두를 막기 위해 둘 다 유지했습니다!!

2020-02-24 10:23 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
> +			OutputView.printLottoCount(lottoCountDto.getLottoCount());
LottoCountDto -> LottoCount로 변경했습니다. DTO의 정의에 잘 맞지 않는 클래스 같아서요.

2020-02-25 01:42 UTC, Hue9010 approved these changes
요구사항에 맞춰 반영 잘해주셨네요! 👍 
예외 구현에 대해서 추가 제안드렸는데 다음 단계 진행하기전에 한번 반영해봐주세요!
다음 단계 진행 전 궁금한 사항이 있다면 코멘트 혹은 DM으로 문의 주세요 😃

2020-02-25 01:42 UTC, Hue9010 commented on src/main/java/lotto/view/OutputView.java
> +						+ amount + "개"));
간단한 팁(?)을 드리자면 StringBuilder를 쓰긴 애매한 이런 상황에서는 String.format이나 printf를 사용해주시면 됩니다!

2020-02-25 01:42 UTC, Hue9010 commented on src/main/java/lotto/domain/WinningLotto.java
> +			throw new IllegalArgumentException(String.format("로또 변호는 %s개여야 합니다.", LOTTO_SIZE));
아래도 남겨드리긴 했는데 printf로 안되는 이런 상황에서 String.format을 이용하는 편이랍니다 😄 
저같은 경우는 주로 지금과 같이 예외 발생시키는 부분에서 입력값을 같이 표시 해주고자 할 때 사용한답니다

2020-02-25 01:42 UTC, Hue9010 commented on src/test/java/lotto/domain/LottosTest.java
> +	@DisplayName("Lottos가 null이 아닌지 체크")
정상적인 값이 들어갔을 때 문제없이 생성이 됐는지 테스트 하려면 
```java
assertThat().isNotNull()
```
isNotNull로 테스트 해 볼수도 있답니다. 다만 생성시 사용한 값이 제대로 들어갔는지에 대한 테스트가 아니고 지금처럼 생성시 validation 로직에 안걸리고 정상적으로 생성되는지 확인하는 테스트라는건 구분하셔야 합니다!

2020-02-25 01:42 UTC, Hue9010 commented on src/main/java/lotto/domain/Lottos.java
> +			throw new IllegalArgumentException("null이나 빈 값이 들어올 수 없습니다.");
Lottos, WinningLotto, LottoCount 도 커스텀 Exception을 만들어 보세요.
그 중에서 Lottos는 Exception 발생시에 메시지를 전달하는게 아니라 기본 생성자에 지금의 메시지를 포함하고 있는 형태로 구현해보세요 😄

2020-02-25 01:42 UTC, merged