[두강] 로또 미션 제출합니다.
woowacourse/java-lotto pull request #141
Opened 2020-02-20 08:50 UTC by ParkDooWon

안녕하세요 두강입니다!
잘 부탁드립니다!

2020-02-22 03:56 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
구현 잘 해주셨어요. :)
다만 아쉬운 부분이 있어 피드백 추가했습니다.
참고 부탁드리고 궁금하신 점 있으시면 언제든지 연락주세요!

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/domain/LottoDummy.java
> +public class LottoDummy {
'Dummy'는 가짜라는 의미를 내포하고있지 않나요?
이름으로 어떤 역할인지 잘 모르겠네요.. :)

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/controller/LottoGame.java
> +        lottoDummy.countWinningLotto(winningNumber, lottoResult);
countWinningLotto의 결과로 LottoResult가 리턴되는게 더 직관적이고 사이드이팩트 발생 여지가 적지 않을까요..???

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/domain/LottoNumber.java
> +    private int number;
1-45번이라는 제약이 있는 숫자이기 때문에 재생성 될 필요 없는 객체로 보여요.
`이펙티브 자바 아이템 1. 생성자 대신 정적 팩터리 메서드를 고려하라, 아이템 6. 불필요한 객체 생성을 피하라`
에 대해서 고민해보세요. :)

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/domain/LottoRank.java
> +                .orElse(null);
각 enum값에 matching을 위한 로직이 있다면 한번의 순회로 풀 수 있지 않을까요? :)

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/domain/LottoDummy.java
> +            lottoDummy.add(LottoFactory.createOneLotto());
LottoFactory, LottoDummy가 강결합 되어있어요.
이를 인터페이스를 통해 느슨하게 의존해보면 어떨까요?
그럼 테스트도 용이할거고 확장에 대해서도 유연하게 대응 할 수 있을거에요. :)
카운트의 갯수에 맞게 랜덤으로 로또를 생성하는게 LottoDummy의 역할이 맞는지도 고민해보면 좋겠어요!

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/domain/PurchaseAmount.java
> +        checkUnderLottoPrice();
같은 check메서드인데 시그니처가 너무 다르네요. :)
특히 checkNegativeAmount(amount), checkUnderLottoPrice() 이 두 메서드요!

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/domain/LottoFactory.java
> +public class LottoFactory {
LottoFactory도 테스트를 작성해주세요. :)

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/domain/LottoResult.java
> +    private static final Map<LottoRank, Integer> result = new HashMap<>();
변경 가능한 객체를 static 으로 구현하면 동기화 문제가 있을 수 있어요, 사이드 이펙트 여지도 많구요.
특별한 이유가 없다면 인스턴스 변수로 작성해주세요!

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/controller/LottoGame.java
> +        return profit.calculateProfitRatio(lottoResult.calculateProfit(), lottoCount);
lottoResult.calculateProfit()을 통해 Profit이 리턴되는게 객체의 책임에 더 적합하지 않을까요? :)
이미 LottoResult도 lottoCount에 대해서 알고있기도 하고요!

2020-02-22 03:56 UTC, phs1116 commented on src/main/java/controller/LottoGame.java
> +        return inputWinningNumber();
catch문 안에서 재귀가 실행되어야 어떤 케이스에 대한 재귀인지 명확 할 것 같아요!

2020-02-22 13:34 UTC, ParkDooWon commented on src/main/java/domain/LottoDummy.java
> +public class LottoDummy {
Dummy는 '구입한 로또들'의 의미를 표현한 것이었습니다. 😅
너무 부적절한 네이밍이었던 것 같아요. LottoDummy대신 LottoTickets로 클래스명을 비롯하여 변수명, 메서드명을 전부 변경했습니다! :)

2020-02-22 14:31 UTC, ParkDooWon commented on src/main/java/controller/LottoGame.java
> +        lottoDummy.countWinningLotto(winningNumber, lottoResult);
당첨된 로또 결과인 lottoResult를 바로 return하도록 수정했습니다!
`countWinningLotto의 결과로 LottoResult가 리턴되는 것`이 더 직관적인 것은 이해했습니다. 그런데 제가 했던 것처럼 `LottoResult`를 미리 만든 후에, 그것을 보내어 `countWinningLotto()`에서 return하지 않고 값을 변경하는 것은 어떤 사이드 이펙트가 있는지 궁금합니다!

2020-02-23 10:00 UTC, ParkDooWon commented on src/main/java/domain/LottoNumber.java
> +    private int number;
정적 팩토리 메서드를 활용하여 1~45까지만 계속 반복 생성되는 LottoNumber 객체의 재생성을 막았습니다. 생각지도 못한 부분이었는데 새롭게 배웠습니다. 피드백 정말 감사합니다! 🙇

2020-02-23 10:03 UTC, ParkDooWon commented on src/main/java/domain/LottoFactory.java
> +public class LottoFactory {
LottoFactory의 테스트도 작성했습니다! : )

2020-02-23 10:26 UTC, phs1116 commented on src/main/java/controller/LottoGame.java
> +        lottoDummy.countWinningLotto(winningNumber, lottoResult);
제가 드린 피드백에서는 두가지 내용이 포함되어있는데, 한가지는 addWinningRankCount를 통한 객체의 변경 가능성을 열어둔 점에 대한 것도 있습니다.

참조의 형태로 내부에서 LottoResult를 수정하기 때문에 변경 메서드가 추가가 되었기 때문이구요.
객체 자체의 변경 가능성을 많이 열어둘 수록 어디서 변경될지 알 수 없어 관리가 어렵습니다.
변경 가능성 때문에 사이드 이펙트가 많이 발생하는 것이고요, 불변 객체를 많이 사용하는 이유에도 이러한 이유가 포함됩니다.

또한 LottoResult의 addWinningRankCount를 통해 값의 변경 가능성을 열어두는것 보다는 countWinningLotto 내부에서 생성자를 통해 생성하도록 구현하도록 하면 객체 자체의 불변이 보장되니 사이드 이팩트 발생 여지가 많이 줄어들거에요.

`이펙티브 자바 아이템 17. 변경 가능성을 최소화하라`
위 내용 참고해보세요. :)

2020-02-23 13:10 UTC, ParkDooWon commented on src/main/java/domain/LottoRank.java
> +                .orElse(null);
bonusBall의 영향을 받는 2등과 3등의 처리를 enum을 활용하여 한번의 순회로 풀 수 있도록 수정해보았습니다. :)

2020-02-23 13:16 UTC, ParkDooWon commented on src/main/java/domain/PurchaseAmount.java
> +        checkUnderLottoPrice();
같은 check 메서드에 대한 시그니처를 통일하였습니다! :)
그리고 해당 클래스의 check 메서드 위치를 check하는 순서에 맞게 변경하였습니다.

2020-02-23 13:22 UTC, ParkDooWon commented on src/main/java/domain/LottoResult.java
> +    private static final Map<LottoRank, Integer> result = new HashMap<>();
변경 가능한 객체의 static을 제거하고 인스턴스 변수로 변경하였습니다!
위의 result를 static으로 구현하면, 다른 사용자가 result를 사용할 때 동일한 result 객체를 사용할 위험이 있어서 인스턴스 변수로 구현하는 것인가요??

2020-02-23 13:48 UTC, ParkDooWon commented on src/main/java/controller/LottoGame.java
> +        return profit.calculateProfitRatio(lottoResult.calculateProfit(), lottoCount);
`수익을 계산하는 것`과 `수익률을 구하는 것` 이 둘의 책임이 서로 분리되어야 한다고 생각해서 lottoResult에서 수익을 계산하고, Profit에서 수익률을 계산했었습니다. 그런데 이미 수익은 lottoResult에서 다 구했으면서, 단지 수익률만 Profit에서 구했던 것 같습니다. 수정을 통해 Profit 클래스를 삭제하고, 수익률을 구하는 책임까지 lottoResult에 두어서 계산하도록 했습니다! 아직도 객체의 책임을 나누는 일이 다소 어렵습니다.😢

2020-02-23 13:51 UTC, ParkDooWon commented on src/main/java/controller/LottoGame.java
> +        return inputWinningNumber();
네! catch문 안에서 재귀가 실행되도록 수정했습니다!

2020-02-23 14:20 UTC, ParkDooWon commented on src/main/java/domain/LottoDummy.java
> +            lottoDummy.add(LottoFactory.createOneLotto());
우선 lottoDummy를 lottoTickets로 변경하였습니다!

`lottoTickets`에 바로 `new Lotto()`가 add 되는 것이 강결합된 것이라고 생각하여 `LottoGame`에서 로또 한장을 생성한 후, `lottoTickets`에 전달함으로써 조금 느슨하게 되도록 수정해보았습니다. 그런데 이렇게 하는 것이 강결합을 푸는 일인지 아직 확신이 없습니다. 제가 제대로 피드백을 반영한건가요? 😅

그리고 위 수정 과정에서 `카운트의 갯수에 맞게 랜덤으로 로또를 생성하는 일`이 자연스럽게 `LottoGame`에서 진행되도록 변경되었습니다! :)

2020-02-24 11:16 UTC, phs1116 requested changes
안녕하세요! 두강
피드백 반영 잘해주셨어요. 👍 
간단한 피드백 몇개 추가했습니다.
참고 부탁드리고 궁금하신 점 있으시면 연락주세요!

2020-02-24 11:16 UTC, phs1116 commented on src/main/java/controller/LottoGame.java
> +        return lottoResult = lottoTickets.countWinningLotto(winningNumber, lottoResult);
lottoResult를 참조로 넘겨서 다시 결과로 lottoResult를 받을 필요가 있을까요?
countWinningLotto 내부에서 lottoResult를 생성하고, lottoResult의 변경가능성을 없애는게 더 사이드이펙트를 줄일수 있지 않을까요?

2020-02-24 11:16 UTC, phs1116 commented on src/main/java/controller/LottoGame.java
> +        lottoDummy.countWinningLotto(winningNumber, lottoResult);
제가 드린 피드백에서는 두가지 내용이 포함되어있는데, 한가지는 addWinningRankCount를 통한 객체의 변경 가능성을 열어둔 점에 대한 것도 있습니다.

참조의 형태로 내부에서 LottoResult를 수정하기 때문에 변경 메서드가 추가가 되었기 때문이구요.
객체 자체의 변경 가능성을 많이 열어둘 수록 어디서 변경될지 알 수 없어 관리가 어렵습니다.
변경 가능성 때문에 사이드 이펙트가 많이 발생하는 것이고요, 불변 객체를 많이 사용하는 이유에도 이러한 이유가 포함됩니다.

또한 LottoResult의 addWinningRankCount를 통해 값의 변경 가능성을 열어두는것 보다는 countWinningLotto 내부에서 생성자를 통해 생성하도록 구현하도록 하면 객체 자체의 불변이 보장되니 사이드 이팩트 발생 여지가 많이 줄어들거에요.

`이펙티브 자바 아이템 17. 변경 가능성을 최소화하라`
위 내용 참고해보세요. :)

2020-02-24 11:16 UTC, phs1116 commented on src/main/java/domain/Lotto.java
> +        }
`객체지향 생활 체조 원칙 규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.`
stream을 한번 활용해봐도 좋겠어요 :)

2020-02-24 11:16 UTC, phs1116 commented on src/main/java/domain/LottoFactory.java
> +            int number = RandomNumberGenerator.generate();
RandomNumberGenerator에 대해서 인터페이스로 분리하고 원하는 값을 돌려주는지 또한 테스트해보면 어떨까요?
이 과정에서 static의 장단점에 대해서도 고민해보면 좋을 것 같아요. :)

2020-02-24 11:16 UTC, phs1116 commented on src/main/java/domain/LottoTickets.java
> +    private static List<Lotto> lottoTickets = new ArrayList<>();
LottoTickets의 기능 자체는 인스턴스 기반인데 lottoTickets는 static으로 작성하신 이유가 있을까요?

이 경우 어떠한 LottoTickets인스턴스를 사용해도 lottoTickets를 공유하기에 서로 다른 인스턴스에서 수정이 일어나도 영향을 받아 부작용 발생의 여지가 있어요. 

클래스 변수, 인스턴스 변수에 대해서 한번 알아보시고 수정하면 좋을 것 같아요. :)

2020-02-24 11:16 UTC, phs1116 commented on src/test/java/lotto/LottoRankTest.java
> +        assertThat(LottoRank.findRank(2, false)).isEqualTo(null);
어떤 테스트에 대한 실패인지 테스트 케이스만으로도 쉽게 구분하기 위해
ParameterizedTest 등으로 나누어보면 좋을 것 같아요. :)

2020-02-24 11:16 UTC, phs1116 commented on src/main/java/controller/LottoGame.java
> +        }
해당 부분도 변경가능성을 최소화하기 위해서 add를 통한 추가가 아닌 메서드 범위 내에서 리스트로 생성하여(이 역할은 Factory가 가지겠네요.), 생성자를 통해 생성하도록 해보면 어떨까요? :)

2020-02-24 11:16 UTC, phs1116 commented on src/main/java/domain/LottoResult.java
> +    private static final Map<LottoRank, Integer> result = new HashMap<>();
네 맞아요. 다른 인스턴스라고 인지해서 값을 생성했는데 전혀 다른 인스턴스에도 영향을 주게 되지요.
이런 사이드 이펙트가 쌓이면 예상치 못한 이슈가 발생할 여지가 있어요. :)

2020-02-25 02:28 UTC, ParkDooWon commented on src/main/java/controller/LottoGame.java
> +        return lottoResult = lottoTickets.countWinningLotto(winningNumber, lottoResult);
countWinningLotto 내부에서 lottoResult를 생성하도록 수정했습니다! :)

2020-02-25 03:11 UTC, ParkDooWon commented on src/main/java/domain/Lotto.java
> +        }
stream을 활용해서 indent를 1로 맞췄습니다! :)

2020-02-25 03:17 UTC, ParkDooWon commented on src/main/java/domain/LottoTickets.java
> +    private static List<Lotto> lottoTickets = new ArrayList<>();
변수의 불필요한 static을 삭제해주었습니다! 피드백 감사합니다! :)

2020-02-25 05:10 UTC, ParkDooWon commented on src/main/java/controller/LottoGame.java
> +        }
Factory에서 `List<Lotto>` 리스트를 만들어서 모든 lotto들을 저장한 후, LottoTickets의 생성자에 전달하여 생성자에서 생성되도록 수정했습니다!

2020-02-25 05:41 UTC, ParkDooWon commented on src/test/java/lotto/LottoRankTest.java
> +        assertThat(LottoRank.findRank(2, false)).isEqualTo(null);
테스트 케이스만으로 알아볼 수 있게 수정했습니다!
LottoRank에 대한 테스트를 @ParameterizedTest와 @CsvSource를 활용하여 진행해봤습니다. :)

2020-02-25 09:55 UTC, ParkDooWon commented on src/main/java/controller/LottoGame.java
> +        lottoDummy.countWinningLotto(winningNumber, lottoResult);
LottoResult 클래스의 addWinningRankCount() 메서드를 삭제하고, 생성자로 전달해서 바로 생성하도록 하여 변경 가능성을 최소화했습니다! 피드백 감사합니다. :)

2020-02-25 09:59 UTC, ParkDooWon commented on src/test/java/lotto/LottoRankTest.java
> +        assertThat(LottoRank.findRank(2, false)).isEqualTo(null);
- 피드백을 반영하는 과정에서 LottoRank 클래스 내의 메서드 기능이 바뀌면서 해당 테스트는 삭제하였습니다.

2020-02-26 02:01 UTC, ParkDooWon commented on src/main/java/domain/LottoFactory.java
> +            int number = RandomNumberGenerator.generate();
RandomNumberGenerator를 인터페이스로 분리하고 lotto에 넣은 값이 제대로 들어갔는지 확인하는 과정을 가졌습니다! :)

2020-02-27 16:47 UTC, phs1116 approved these changes
안녕하세요, 두강!
리뷰어 화투입니다. 깔끔하게 매우 잘 구현해주셨습니다. 👍 
이번 단계 머지할게요. :)
1단계 구현하시느라 수고 많으셨어요!

2020-02-27 16:47 UTC, merged