[하비] 로또 1단계 - 자동 미션 제출합니다.
woowacourse/java-lotto pull request #151
Opened 2020-02-20 09:03 UTC by hyochan-Kim

리뷰하시기 전까지 최대한 리팩토링 해보겠습니다..!

2020-02-22 04:58 UTC, Hue9010 requested changes
안녕하세요. 이번 리뷰를 맡은 휴입니다!
개인사정으로 피드백이 늦었습니다 😭 개선이 필요한 부분 피드백 드렸는데 확인해보시고 궁금한 사항이 생기면 코멘트 혹은 DM으로 편하게 문의주세요!

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +            throw new IllegalArgumentException(LOTTO_NUMBER_AMOUNT_EXCEPTION_MESSAGE);
한번 커스텀 Exception으로 LottoException을 만들어 보세요. (RuntimeException으로요!)
과정을 봤을때 커스텀 Exception에 대한 학습이 있었던 걸로 보이는데 아니라면 말씀주세요!
+ 구현하시면서 어려운 부분 있으면 편히 코멘트나 DM으로 문의 주세요 :)

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +        Objects.requireNonNull(randomNumbers);
Objects 활용 👍 
다만 지금 같은 경우 `Objects.requireNonNull`를 사용하여 NPE이가 발생하는 것과 null값이 들어왔을 때 다음 문제가 될 위치로 보이는 `validateSize` 내의 `inputNumbers.size()`에서 NPE가 발생하는 것에서 다를 부분이 있을까요?

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<LottoNumber> lottoNumbers;
final 키워드를 많이들 사용하시는데 재할당을 금지하기 위해서 사용하신 것인지 List가 불변하게 하기 위해서 사용하신 것인지 사용 목적이 궁금합니다!
전자 같은 경우는 final의 기능이 재할당 금지이기 때문에 더이상 얘기할 부분이 없지만 후자 같은 경우는 List의 재 할당이 불가능 하겠지만 지금 할당 된 리스트의 내부 값은 변경이 가능하답니다.

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/PurchaseLottos.java
> +        if (Objects.isNull(purchaseLottos) || purchaseLottos.isEmpty()) {
Objects 👍

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/RandomNumberGenerator.java
> +        List<Integer> randomNumbers = this.getInstance();
getInstance가 이름과는 다르게 List<Integer>를 반환해줍니다. 그러다보니 지금처럼 this.getInstance()만 보면 리스트가 아니라 RandomNumberGenerator의 인스턴스가 반환 될 것이라고 기대되네요.

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/Rank.java
> +        this.count++;
각각의 테스트를 돌릴때는 문제가 없는데 전체 테스트를 돌릴때는 실패하는 케이스가 발생했는데 그 원인이 이곳이였네요.
지금은 한판만 진행하고 끝나는데 로또를 여러판 반복하게 되면 어떻게 될까요?

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/Rank.java
> +    public static void findRank(int rightNumber, boolean isCorrectBonusNumber) {
마찬가지로 findRank이지만 사실은 Rank를 찾은 다음 매칭된 Rank의 count를 높혀주네요

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/WinningRule.java
> +    private int countCorrectLottoNumber(List<LottoNumber> mergedLottoNumbers) {
lottoNumbers로 바꾸는건 어떨까요? 
`countCorrectLottoNumber` 입장에서는 정답 번호들이 합쳐진 로또번호인지 여부는 필요하지 않답니다. 도리어 사용자 입장에서는 mergedLottoNumbers가 무엇일까 고민 해야 할 수도 있답니다.

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +            throw new IllegalArgumentException(INVALID_PURCHASE_NUMBER_EXCEPTION_MESSAGE);
사실 `NumberFormatException`의 구현으로 들어가보시면 `IllegalArgumentException`을 구현할 걸 알 수있답니다.
그런 차원에서 `IllegalArgumentException`로 변환해줄 필요는 없답니다.

2020-02-22 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/Rank.java
> +        this.count++;
enum의 count 값을 변경한 다음 최종적으로 그 값을 사용해 계산하는 방법은 변경해야 할 것 같습니다. (최종 계산 후 count 값을 0으로 초기화하지 말고요!)
이건 enum이 실제적으로는 자바의 클래스로서 FIFTH_RANK, FOURTH_RANK, ... 인스턴스가 생성되는 구조라서 이처럼 구현이 가능한건데 enum을 클래스처럼 사용하지 않는게 좋습니다. 마찬가지로 enum내에 있는 상금이 필요에 의해 코드상에서 변경하는 경우가 아니라 애플리케이션이 돌아가는 동안 동적으로 계속 변경되어도 될까요?

2020-02-24 06:44 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Lotto.java
> +            throw new IllegalArgumentException(LOTTO_NUMBER_AMOUNT_EXCEPTION_MESSAGE);
말씀해주신대로 custom exception을 만들어 보았습니다. 
너무 간단한 역할만 하는 것 같은데 잘 구현 된 것인지 궁금합니다.

2020-02-24 06:46 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Lotto.java
> +        Objects.requireNonNull(randomNumbers);
다른 부분이 없는 것 같아서 validateInput으로 네이밍 변경 후 해당 메소드에서 함께 exception이 발생하게 하였습니다.

2020-02-24 06:47 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<LottoNumber> lottoNumbers;
내부 값이 변경되지 못하는 것을 바라고 final 키워드를 사용했었습니다. 
의도대로 진행되게 Collections.unmodifiableList를 추가 하였습니다.

2020-02-24 06:48 UTC, hyochan-Kim commented on src/main/java/lotto/domain/RandomNumberGenerator.java
> +        List<Integer> randomNumbers = this.getInstance();
해당 부분 네이밍 변경 하던 중 불필요한 것 같아 제거하는 방향으로 수정하였습니다!

2020-02-24 06:48 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Rank.java
> +        this.count++;
당첨 결과 count를 enum에서 담당하지 않고 result 클래스에서 담당하도록 수정하였습니다.

2020-02-24 06:59 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Rank.java
> +        this.count++;
enum은 고정된 상수들의 집합이니 enum 안의 값은 동적으로 변하면 안되는게 맞는 것 같습니다.

2020-02-24 06:59 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Rank.java
> +    public static void findRank(int rightNumber, boolean isCorrectBonusNumber) {
수정하였습니다! 감사합니다 :)

2020-02-24 07:00 UTC, hyochan-Kim commented on src/main/java/lotto/domain/WinningRule.java
> +    private int countCorrectLottoNumber(List<LottoNumber> mergedLottoNumbers) {
사용자가 고민하지 않게 countCorrectLottoNumber(Lotto lotto)로 파라미터를 수정하였습니다.

2020-02-24 07:01 UTC, hyochan-Kim commented on src/main/java/lotto/view/InputView.java
> +            throw new IllegalArgumentException(INVALID_PURCHASE_NUMBER_EXCEPTION_MESSAGE);
수정하였습니다. 앞으로는 exception을 던질 때 해당 내용을 확인하고 try - catch 해야겠습니다. 감사합니다 :)

2020-02-25 15:36 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<LottoNumber> lottoNumbers;
조금 더 정확히는
1. Lotto 외부에서만 변경 불가능하게 둘 것인지
2. Lotto 내부에서도 변경 불가능하게 둘 것인지 여부도 생각해 볼 수 있습니다.
1번이라면 lottoNumbers 할당시에 unmodifiableList로 생성해줄 필요는 없답니다. 중요한건 어떤 의도를 가지고 구현했으며 그 의도가 충족되었는지가 중요할 것 같네요. 😸

2020-02-25 16:21 UTC, Hue9010 approved these changes
Rank에서 count를 빼는게 쉽지 않았을텐데 잘해주셨네요! 👍 이번 단계는 머지 하도록 할게요
테스트 코드의 존재가 count를 빼는데 도움이 되었는지 궁금하네요.
간단한 피드백 남겨드렸는데 예외 부분에 한해서는 다음 단계 전에 반영해주세요!

2020-02-25 16:21 UTC, Hue9010 commented on src/main/java/lotto/ConsoleLottoApplication.java
> +        result.calculateRank(purchaseLottos, winningNumbers);
Result를 직접 생성해서 결과를 만들지 않고 WinningRule에서 PurchaseLottos를 가지고 또는 PurchaseLottos에서 WinningRule을 가지고서 번호를 맞춰봄으로 Result를 반환해주느 방법도 있을 것 같네요.

말로만 해서는 오해를 할 수도 있으니 코드로 풀면 아래와 같겠네요.
```java
Result result = winningNumbers.xxx(purchaseLottos);
```

꼭 변경하라는게 아닌 한번 생각해보시길 바랍니다! 😄

2020-02-25 16:21 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +            throw new InvalidInputSizeException(INVALID_INPUT_SIZE_EXCEPTION_MESSAGE);
`InvalidInputSizeException`과 `DuplicateExistException`의 경우는 한곳에서만 쓰이는데 message를 입력 받는게 아니라
파라미터가 없는 기본 생성자로 변경하고 메시지는 내부에서 포함하고 있게 변경해보실래요?

2020-02-25 16:23 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +            throw new IllegalArgumentException(INVALID_PURCHASE_NUMBER_EXCEPTION_MESSAGE);
사실 약간은 과도한 정보일 것 같아 알려드리는걸 고민했던 부분이긴 하나 NumberFormatException 같은 경우는 앞으로도 자주 만날 확률이 있어 보여 말씀드렸네요. 😋

2020-02-25 16:23 UTC, Hue9010 commented on src/main/java/lotto/domain/Rank.java
> +        this.count++;
수정하시는게 쉽지 않알을텐데 잘해주셨네요!

2020-02-25 18:21 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +            throw new IllegalArgumentException(LOTTO_NUMBER_AMOUNT_EXCEPTION_MESSAGE);
사실 Exception 자체가 무언가 큰 것들을 해주지 않습니다.
커스텀 Exception을 만들어 주는 이유는 지금 보다 더 많은 클래스, 큰 프로젝트를 진행하다가 RuntimeException이 발생했을때 발생한 위치, 메시지를 보고 찾는 것보다, NumberFormatException , NullPointException이 발생했을 때 무엇이 문제가 됐는지 빠르게 파악할 수 있다는 점에서 중요합니다.

마찬가지로 기존 IllegalArgumentException과 메시지가 찍히는 것보다는 InvalidInputSizeException이 발생했다는 문구 하나만 봐도 어디서 어떤 문제가 발생했는지 빠르게 알아챌수 있겠죠.

보통 Exception을 만드는 것에 익숙치 않고 다른 피드백과 같이 신경쓰셔야 하다보니까 스탭 바이 스탭으로 간단한 추가만 하면 되는 선으로 요청드리기도 했답니다. 😸 
커스텀 Exception을 만드는게 어렵지 않다는 걸 경험해보는 것만으로 앞으로도 많은 도움이 될겁니다!

2020-02-25 18:25 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +            throw new IllegalArgumentException(LOTTO_NUMBER_AMOUNT_EXCEPTION_MESSAGE);
여기서 한번 생각해 볼 수 있는게 IllegalArgumentException에 메시지를 주는 것만으로도 충분할 수도 있을텐데 NumberFormatException은 왜 IllegalArgumentException을 상속하고 있을까요?

2020-02-25 18:26 UTC, merged

2020-02-27 07:28 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Lotto.java
> +            throw new IllegalArgumentException(LOTTO_NUMBER_AMOUNT_EXCEPTION_MESSAGE);
IllegalArgumentException에서 제공하는 형태 외에도 원하는 field 혹은 method를 추가 하는 등 예외를 조금 더 디테일하게 다루기 위함이라고 생각합니다.

2020-02-27 07:30 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<LottoNumber> lottoNumbers;
단순히 2번으로 생각하였는데, 조금 더 고민해보겠습니다. 감사합니다 :)

2020-02-27 07:36 UTC, hyochan-Kim commented on src/main/java/lotto/domain/Lotto.java
> +            throw new InvalidInputSizeException(INVALID_INPUT_SIZE_EXCEPTION_MESSAGE);
말씀하신대로 변경하였습니다! 궁금한 점이 남아 질문 드립니다. 향후 재사용을 염두하여 파라미터를 이용한 생성자를 남겨두는 것이 좋은지, 아니면 기본 생성자만 남기고 지우는게 좋은지 궁금합니다. 메세지를 받을 수 없는 exception은 뭔가 어색한거 같아서요! 감사합니다 :)

2020-02-27 07:51 UTC, hyochan-Kim commented on src/main/java/lotto/ConsoleLottoApplication.java
> +        result.calculateRank(purchaseLottos, winningNumbers);
네 감사합니다 :) 바꿔보고 뭐가 더 괜찮을지 고민해보겠습니다!

2020-02-27 07:51 UTC, hyochan-Kim commented on src/main/java/lotto/view/InputView.java
> +            throw new IllegalArgumentException(INVALID_PURCHASE_NUMBER_EXCEPTION_MESSAGE);
감사합니다 !! 👍

2020-03-09 16:21 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +            throw new InvalidInputSizeException(INVALID_INPUT_SIZE_EXCEPTION_MESSAGE);
앗! 많이 늦은 답변 드립니다. 😰 
저라면 보통 지웁니다. 특히나 지금처럼 단순한 형태라면 다시 만드는게 어려운 일도 아니니까요.

지금처럼 단순 정해진 문자열로만 된 경우라면 파라미터가 없는 Exception으로 마무리하는 편이고, 메시지를 통해 상황을 구분하지 않고, 각 상황에 맞는 Exception을 만드는 편입니다.
(LottoException으로 하지않고 InvalidInputSizeException, EmptyOrNullException 만드신 것처럼 말이죠 😉  )

다만, 말씀처럼 보통은 메시지가 없는 Exception을 만들기보다는 메시지를 받는 편인데 

지금 이부분의 코드만 대략 보면 아래와 같은데
```java
private static final String INVALID_INPUT_SIZE_EXCEPTION_MESSAGE = "Lotto number amount must be 6.";

if (inputNumbers.size() != LOTTO_NUMBER_AMOUNT) {
        throw new InvalidInputSizeException(INVALID_INPUT_SIZE_EXCEPTION_MESSAGE);
```
이렇게 정적인 문자열을 받지 않고 무엇이 잘못 됐는지 알려주는 편입니다.

```java
        if (inputNumbers.size() != LOTTO_NUMBER_AMOUNT) {
            throw new InvalidInputSizeException(String.format(Lotto number amount must be 6. size : %d, inputNumber.size()));
```

지금 예같은 경우는 사이즈를 알려줬는데 로또 번호를 입력 받을 때 1~45를 벗어난 90이 들어왔다는걸 알려주는 식으로 사용한답니다. 

답변을 놓쳤다는걸 지금에서야 발견해서 많이 늦었지만 답변드립니다.. 😢