[또링] 로또 미션 제출합니다!
woowacourse/java-lotto pull request #162
Opened 2020-02-20 09:56 UTC by jnsorn

안녕하세요. 잘부탁드립니다 ☺

2020-02-23 06:29 UTC, jeonghoon1107 requested changes
안녕하세요~! 전체적으로 구현 잘하셨어요 💯 
몇가지 피드백 남겼으니 확인해주세요 :)

2020-02-23 06:29 UTC, jeonghoon1107 commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +		List<Lotto> lottos = lottoController.purchaseLotto(numberOfLotto);
일급컬렉션을 사용해보면 어떨까요?

2020-02-23 06:29 UTC, jeonghoon1107 commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +		Lotto winningLotto = new Lotto(LottoParser.parser(inputWinningLottoNumber()));
winningLotto클래스를 만들어보면 어떨까요?

2020-02-23 06:29 UTC, jeonghoon1107 commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +		Map<LottoRank, Integer> lottoRankCount =
Result를 담당하는 클래스를 따로 만들면 어떨까요?

2020-02-23 06:29 UTC, jeonghoon1107 commented on src/main/java/lotto/domain/Lotto/Lotto.java
> +	private void validateDuplication(List<LottoNumber> lottoNumbers) {
Set을 이용하면 어떨까요?

2020-02-23 06:29 UTC, jeonghoon1107 commented on src/main/java/lotto/domain/LottoMoney/LottoMoney.java
> +	private static final long MAX_BOUND = 100000;
_를 이용하면 가독성을 높일 수 있어요!

추가적으로 max에 대한 요구사항이 있나요?

2020-02-23 07:02 UTC, jnsorn commented on src/main/java/lotto/domain/LottoMoney/LottoMoney.java
> +	private static final long MAX_BOUND = 100000;
따로 요구사항은 없지만 현실에서는 1인 1회차 10만원 한도라는 룰이 있어서 적용해보았습니다! 하지만 요구사항에 명시되지 않은 내용을 구현하는 것은 개발자의 욕심이라는 생각도 드네요... 해당 부분 수정하겠습니다 :) 

enum내에서는 _로 구분을 하였는데 여기서는 깜빡한 것 같습니다😓 조언해주신대로 _를 붙여 가독성을 높이는 방향으로 수정하겠습니다!

2020-02-24 06:11 UTC, jnsorn commented on src/main/java/lotto/domain/Lotto/Lotto.java
> +	private void validateDuplication(List<LottoNumber> lottoNumbers) {
Set을 이용하게 되면 사용자로 하여금 이 자료구조가 중복이 안된다는 것을 명시적으로 표현할 수  있고, 따로 중복 검사를 수행하지 않아도 되는 장점을 가질 수 있겠네요! 해당 부분 수정하겠습니다. 😊

2020-02-24 12:54 UTC, jnsorn commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +		List<Lotto> lottos = lottoController.purchaseLotto(numberOfLotto);
말씀해주신대로 List<Lotto>를 가지고 있는 Lottos 일급 컬렉션을 생성하였습니다. 하지만 Lottos를 생성하여 얻는 이점은 List<Lotto> 타입 필드의 불변성을 보장한다는 것 밖에 깨닫지 못했습니다. 😂 혹시...! 이 점 말고 일급컬렉션 사용을 추천해주신 다른 이유가 있다면 듣고 싶습니다!😊

2020-02-24 12:54 UTC, jnsorn commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +		Lotto winningLotto = new Lotto(LottoParser.parser(inputWinningLottoNumber()));
해당 부분 수정하였습니다 :)

2020-02-24 12:54 UTC, jnsorn commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +		Map<LottoRank, Integer> lottoRankCount =
해당 부분 수정하였습니다!

2020-02-26 11:25 UTC, kingbbode approved these changes
안녕하세요!
코드가 잘 작성되었네요 :)
1단계 머지하겠습니다!

2020-02-26 11:25 UTC, kingbbode commented on src/main/java/lotto/domain/lotto/Lottos.java
> +}
일급컬렉션으로서 하는 역할이 없네요 :) 
그렇다면 `List<Lotto>` 를 사용하는게 더 편하지 않을까요?
의미없는 객체 포장은 불필요해보여요.

2020-02-26 11:25 UTC, merged