[럿고] 로또 2단계 미션 제출합니다.
woowacourse/java-lotto pull request #174
Opened 2020-02-26 06:11 UTC by ksy90101

1단계 피드백 너무 감사했습니다! 1단계 피드백들을 고치는 단계에서 2단계를 미리 준비한 느낌이여서 금방 끝난것 같습니다! 2단계도 열심히 배워가겠습니다~

2020-02-26 09:58 UTC, young891221 requested changes
1단계에서 빡세게(?) 리펙토링이 되었다니 기쁘네요ㅎㅎ
좀 더 리펙토링하면 좋아보여서 몇 가지 코멘트 남겼습니다.
반영 부탁드릴게요~!

2020-02-26 09:58 UTC, young891221 commented on src/main/java/lotto/controller/LottoController.java
>          OutputView.printEarningRate(new EarningRate(winningRanks, purchaseAmount));
의미적인 단위로 개행이 들어가면 좋아보입니다ㅎ

2020-02-26 09:58 UTC, young891221 commented on src/main/java/lotto/controller/LottoController.java
>          } catch (DuplicationException | NumberOutOfRangeException e) {
여기 3개 메서드를 모두 해당 클래스 or new 클래스로 옮겨 보면 훨씬 깔끔할 듯 합니다ㅎ

2020-02-26 09:58 UTC, young891221 commented on src/main/java/lotto/domain/LottoStore.java
> +    private LottoTickets lottoTickets = new LottoTickets();
필드가 2개 인데 하나로 줄이도록 리펙토링 할 수 있을까요?

2020-02-27 03:20 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoStore.java
> +    private LottoTickets lottoTickets = new LottoTickets();
LottoTickets를 generateLottoTickets에서 생성해서 필드를 하나로 줄였습니다!

2020-02-27 03:31 UTC, ksy90101 commented on src/main/java/lotto/controller/LottoController.java
>          } catch (DuplicationException | NumberOutOfRangeException e) {
입력하는 부분들은 View로 이동하였습니다! 아울러, generatePurchseAmount는 의미가 없는 것 같아서, play에서 바로 받는 걸로 변경하엿습니다!

2020-02-27 03:40 UTC, ksy90101 commented
개인적으로 훨씬 깔끔해진 것 같습니다. 하면서 입력부분을 Controller에서 받고 입력을 객체에게 넘겨주는 방식으로 가야되겠다는 생각도 들었습니다! 바보 같이 객체에서 바로 입력을 받는 것도 있었네요..ㅠㅠ 혹시 또 다른 피드백이 있다면 남겨주세요! 감사합니다!

2020-02-27 11:59 UTC, young891221 requested changes
피드백 반영이 잘 되었다니 좋네요 💯 
조금 더 개선점이 보여서 코멘트 남겨보았습니다.
확인 후 반영 부탁드릴게요:)

2020-02-27 11:59 UTC, young891221 commented on src/main/java/lotto/domain/LottoTickets.java
> +    private final static List<LottoTicket> LOTTO_TICKETS = new ArrayList<>();
저는 개인적인 생각으로 컨트롤러를 만든것이 멀티 쓰레드 환경을 지원하기 위한 큰 그림이라 생각했는데요ㅎㅎ
LottoTickets의 경우 static으로 생성한다면 굉장히 제약적으로 사용됩니다. 인스턴스를 새로 만드는 방향으로 리펙토링 해주세요.

2020-02-27 11:59 UTC, young891221 commented on src/main/java/lotto/domain/LottoTicketNumber.java
> +    private int automaticLottoTicketNumber;
number 필드 하나만 남겨두도록 리펙토링 하는건 어떨까요?
실제 사용하는 관점에서 LottoTicketNumber의 변수명을 totalLottoTicketNumber, manualLottoTicketNumber...으로 사용하면 더 깔끔해질 듯 하네요. 일급 객체로 변환도 되구요ㅎㅎ

2020-02-28 02:09 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoTickets.java
> +    private final static List<LottoTicket> LOTTO_TICKETS = new ArrayList<>();
의미없는 static이 였네요... getter를 어차피 사용하면서 사용한 의미가 없었던 것 같습니다! 리팩토링 하였습니다!

2020-02-28 04:12 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoTicketNumber.java
> +    private int automaticLottoTicketNumber;
없애긴 했는데, 괜찮은 방법인지를 모르겠습니다! 확인 부탁드릴께요!

2020-02-28 04:15 UTC, ksy90101 commented
LottoTicketNumber에 대한 리팩토링이 제대로 된건지 잘 모르겠습니다! 확인 부탁드리고 혹시 다른 피드백 있다면 남겨주세요~ 감사합니다!

2020-02-28 05:06 UTC, young891221 commented on src/main/java/lotto/domain/LottoTicketNumber.java
> +    private int automaticLottoTicketNumber;
음 제가 의미했던 방식은 아래와 같았지만 변경해 주신 방법도 나쁘지 않아 보이네요ㅎㅎ
```java
LottoTicketNumber totalLottoTicketNumber  = new LottoTicketNumber();
LottoTicketNumber manualLottoTicketNumber  = new LottoTicketNumber();
LottoTicketNumber automaticLottoTicketNumber = new LottoTicketNumber();
```

2020-02-28 05:06 UTC, young891221 approved these changes
피드백 반영 감사합니다:)
이제 머지해도 충분해 보이네요!
머지할게요~!

2020-02-28 05:06 UTC, merged

2020-02-28 05:13 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoTicketNumber.java
> +    private int automaticLottoTicketNumber;
아 ㅎㅎ 하나의 객체로 여러 가지로 인스턴스화 하라는 이야기였네요! 기억해놨다가 이런 기능을 구현하게 될때 사용해보도록 하겠습니다! 피드백 주시느라 고생하셨습니다!