[엘리] 로또 2단계 미션 제출합니다.
woowacourse/java-lotto pull request #193
Opened 2020-02-27 07:20 UTC by YebinK

안녕하세요! 남겨주신 피드백 바탕으로 2단계 미션도 진행해보았습니다!
이번에도 잘 부탁드립니다 :)

2020-02-27 17:17 UTC, jaeyeonling requested changes
새로운 개념에 대한 도전이 많이 보였습니다 👍 
몇가지 피드백 남겨두었으니 확인 후 반영 부탁드릴게요!
궁금하신 점 있으면 편하게 DM 주세요 :)

2020-02-27 17:17 UTC, jaeyeonling commented on src/main/java/domain/LottoStore.java
> +    private static int totalTicketSize;
클래스 변수로 존재한다면 해당 애플리케이션은 동시성이 보장되지 않기 때문에 하나의 게임만 진행할 수 있어요.
위와 같은 문제를 해결해보아요!

2020-02-27 17:17 UTC, jaeyeonling commented on src/main/java/domain/numberscontainer/LottoNumbersDtoAssembler.java
> +    private static LinkedHashSet<LottoNumber> parseSet(String numbersInput) {
```suggestion
    private static Set<LottoNumber> parse(String rawNumbers) {
```

인터페이스 타입을 참조하면 어떠한 차이가 있을지 고민해보아요.
이펙티브 자바 `아이템 64. 객체는 인터페이스를 사용해 참조하라`를 참고해주세요.

또한 이름에 Set과 같은 자료형을 네이밍에 넣는 것은 권장하고 있지 않습니다!

2020-02-27 17:17 UTC, jaeyeonling commented on src/main/java/domain/numberscontainer/LottoNumbersDtoAssembler.java
> +public class LottoNumbersDtoAssembler {
Assembler는 `DTO -> Domain` 혹은 `Domain -> DTO`의 역할만을 담당해야 합니다.
변환시키는 작업 또한 생성하는 것이지만 핵심은 `생성을 담당한다.` 보다는 `변환을 담당한다`로 보는게 맞습니다.
생성은 생성자로, `DTO` 변환은 `Assembler`가 담당하도록 수정해보아요.

2020-02-27 17:17 UTC, jaeyeonling commented on src/main/java/domain/Money.java
> +    private static final int MONEY_UNIT = 1000;
`Money.MONEY_UNIT`은 의미 파악이 힘든 것 같아요!
또한 `Ticket`의 가격을 `Money`에 위치하는 것과 `Ticket`에 위치하는 것은 어떠한 차이가 있는지 고민해보아요.

2020-02-27 17:17 UTC, jaeyeonling commented on src/main/java/domain/numberscontainer/BonusNumberDto.java
> +public class BonusNumberDto {
외부로부터 도메인을 보호하기 위하여 DTO를 분리하는데요.
LottoNumber의 경우 변경이 불가능한 상수이기 때문에 따로 DTO로 분리하지 않아도 될 것 같아요!

2020-02-27 17:17 UTC, jaeyeonling commented on src/main/java/domain/numberscontainer/LottoNumbersDto.java
> +public class LottoNumbersDto {
DTO는 도메인을 보호하기 위해 사용하는데요.
`LinkedHashSet<LottoNumber>`는 도메인일지 고민해보고 어느 부분에 DTO를 만들어야 할지 고민해보아요.

2020-02-27 17:17 UTC, jaeyeonling commented on src/test/java/domain/LottoResultMachineTest.java
>      void test2() {
테스트를 하기 위한 객체를 생성하는 작업이 매우 힘들어보여요.
객체를 생성하는 로직을 조금 단순화해보면 어떨까요?

중복의 단점을 생각해 본다면 테스트 코드의 중복 또한 제거하는게 좋습니다!

2020-02-27 17:17 UTC, jaeyeonling commented on src/main/java/LottoApplication.java
>      public static void main(String[] args) {
생성에 대한 부분과 변환이 혼동된 것 같은데요.

생성 
1. 생성은 생성자에서 담당한다.
2. 생성의 로직이 복잡하다면 Factory와 같은 생성만을 담당하는 클래스를 만든다.

DTO
1. 도메인을 보호하기 위해 DTO를 사용한다.
2. 도메인 -> DTO 혹은 DTO -> 도메인 변환 역할을 담당하는 것을 Assembler라고 한다.

생성자와 Assembler의 차이에 대해 고민해보아요!

2020-03-02 06:38 UTC, YebinK commented on src/main/java/domain/numberscontainer/LottoNumbersDto.java
> +public class LottoNumbersDto {
DTO를 삭제하고, Collections.unmodifiableSet 등의 메소드를 활용해 도메인을 보호해보았습니다! 조언 감사합니다:D

2020-03-02 07:41 UTC, YebinK commented on src/main/java/domain/numberscontainer/Ticket.java
> +    private LottoNumbers lottoNumbers;
DM 나눴던 내용을 바탕으로 리팩토링해보았습니다! :D
궁금한 점이 한 가지 있어 코멘트 남겨봅니다.
기존에는 `Ticket`과 `WinningNumbers`가 `LottoNumbers` 클래스를 상속받도록 만들었는데요,
6자리 숫자에 대한 검증 과정이 중복되어 이렇게 구현했습니다.

그런데 `이펙티브 자바 (아이템 18) 상속 대신 컴포지션을 사용하라`를 읽고 나니 상속의 단점에 대해 생각해보게 되었습니다. 그래서 컴포지션을 적용해보았더니 `LottoNumbers`클래스 내부에 `contains`와 `get`메소드를 추가하게 되었습니다. 클래스 간의 결합도는 낮아진 것 같아서 뿌듯하지만 불필요한 메소드가 두 개나 생성된 게 아닌가 싶습니다. 혹시 메소드 추가 외에 기능을 제대로 작동할 수 있는 다른 방법이 있는지 궁금합니다! :)

2020-03-04 00:40 UTC, jaeyeonling approved these changes
머지한 줄 알았는데 머지가 안됐네요 늦어서 죄송합니다 ㅜㅜ
피드백 반영을 잘 해주셨습니다 💯 
그동안 많은 피드백 반영하느라 고생 많으셨어요~
해당 요청은 머지하도록 하겠습니다!

2020-03-04 00:40 UTC, jaeyeonling commented on src/main/java/domain/numberscontainer/Ticket.java
> +    private LottoNumbers lottoNumbers;
정말 잘 리팩토링 해주셨어요 💯 
불필요한 메서드가 2개 추가 됐다고 말씀하셨는데 해당 메서드들은 by-pass를 하는 메서드이기 때문에 문제는 없는데요.
메서드 중복의 단점을 생각해본다면 조합에서의 메서드 중복은 해당이 안되는 것을 알 수 있습니다!

2020-03-04 00:40 UTC, jaeyeonling commented on src/main/java/domain/numberscontainer/Tickets.java
> +    public static final int TICKET_PRICE = 1000;
티켓의 가격이라면 `Ticket.PRICE`로 옮기는 것이 더욱 자연스럽지 않을까요?

2020-03-04 00:40 UTC, jaeyeonling commented on src/main/java/domain/LottoRank.java
> +    public static LottoRank findLottoRank(int matchCount, boolean isBonus) {
```suggestion
    public static LottoRank find(int matchCount, boolean isBonus) {
```

또는 

```suggestion
    public static LottoRank of(int matchCount, boolean isBonus) {
```

와 같은 네이밍과 어떠한 차이가 있을까요?

2020-03-04 00:40 UTC, jaeyeonling commented on src/main/java/domain/numberscontainer/Ticket.java
> +        return this.lottoNumbers.get().stream()
```suggestion
        return this.lottoNumbers.stream()
```

일급 컬렉션의 경우 `stream()` 메서드를 생성해주면 스트림 사용이 편합니다!

2020-03-04 00:40 UTC, merged