[하비] 로또 - 수동 구매 미션 제출합니다.
woowacourse/java-lotto pull request #195
Opened 2020-02-27 07:56 UTC by hyochan-Kim

늘 감사합니다:)

2020-02-29 10:01 UTC, Hue9010 requested changes
이전에 역할 분담을 잘하셔서 자동/수동 갯수, 수동 로또 생성 추가만으로 2단계 구현을 요구사항에 맞춰 깔끔히 해주셨네요 💯 
몇가지 수정사항이랑 생각해볼 만한 내용 남겨드렸습니다. 확인해주세요~!!
\+ 2단계 진행하면서 1단계때 만들었던 테스트 코드가 도움이 되던가요? 어떠셨을지 궁금하네요. 😋
(변경이 생겨도 기존 기능에 문제가 없다는 안정감을 가진다던지!)

2020-02-29 10:01 UTC, Hue9010 commented on src/main/java/lotto/domain/PurchaseAmount.java
> +    private static void validatePurchaseMoney(int randomLottoAmount, int manualLottoAmount) {
이젠 static일 필요가 없을 것 같습니다!

2020-02-29 10:01 UTC, Hue9010 commented on src/main/java/lotto/ConsoleLottoApplication.java
> +        List<Lotto> purchaseLottos = new ArrayList<>();
이제 new ArrayList<>(); 는 필요없는 것 같네요 😉

2020-02-29 10:01 UTC, Hue9010 commented on src/main/java/lotto/ConsoleLottoApplication.java
>          RandomNumberGenerator randomNumberGenerator = new RandomNumberGenerator();
이제 보니 RandomNumberGenerator의 numberPool까지 static으로 두고 Util로 사용가능하겠네요.

2020-02-29 10:01 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +        winningNumbers = inputLotto();
List<Integer> winningNumbers = inputLotto(); 로 합칠 수 있겠네요.

2020-02-29 10:01 UTC, Hue9010 commented on src/main/java/lotto/view/OutputView.java
> +    public static final String PRINT_PURCHASE_AMOUNT_FORMAT = "수동으로 %d장, 자동으로 %d개를 구매했습니다.\n";
전체적으로 문자열 상수를 많이 사용하셨는데 유머로도 좀 사용된 포스팅인데 [개발자 개발자 1년차, 5년차, 10년차 코드](https://medium.com/@webseanhickey/the-evolution-of-a-software-engineer-db854689243)를 보고 지금과 같은 형태로 문자열 상수를 뺀 것과 그대로 쓰는 것에 대해서 한번 생각해볼 수 있을 것 같네요. 😸
(노파심에 말하면 문자열 상수 자체가 불필요하다는건 아닙니다.)

2020-02-29 10:01 UTC, Hue9010 commented on src/main/java/lotto/ConsoleLottoApplication.java
>      private static PurchaseLottos makePurchaseLottos(PurchaseAmount purchaseAmount) {
PurchaseLottos 이 생각보다 복잡해지고 있는데 PurchaseLottos를 만드는 책임을 PurchaseLottos에게 옮기거나 factory를 만들어서 자동/수동 로또를 만들어 줄 수도 있을 것 같네요

2020-03-04 20:38 UTC, hyochan-Kim commented on src/main/java/lotto/domain/PurchaseAmount.java
> +    private static void validatePurchaseMoney(int randomLottoAmount, int manualLottoAmount) {
그러네요. 감사합니다 :)

2020-03-04 20:39 UTC, hyochan-Kim commented on src/main/java/lotto/ConsoleLottoApplication.java
> +        List<Lotto> purchaseLottos = new ArrayList<>();
그러네요. Intelllij에서 표시까지해주고 있는데 놓쳤네요.. 감사합니다!!

2020-03-05 07:29 UTC, hyochan-Kim commented on src/main/java/lotto/view/InputView.java
> +        winningNumbers = inputLotto();
그러네요! 항상 줄 수를 줄이도록 이런 부분들을 놓치지 않고 고려 하겠습니다.

2020-03-06 07:47 UTC, hyochan-Kim commented on src/main/java/lotto/ConsoleLottoApplication.java
>          RandomNumberGenerator randomNumberGenerator = new RandomNumberGenerator();
수정하였습니다 :)

2020-03-06 07:56 UTC, hyochan-Kim commented on src/main/java/lotto/view/OutputView.java
> +    public static final String PRINT_PURCHASE_AMOUNT_FORMAT = "수동으로 %d장, 자동으로 %d개를 구매했습니다.\n";
감사합니다:) 여러 언어를 출력할 때 이점이 있지 않을까 생각이 드는데, 확실히는 모르겠네요.. 조금 더 생각해보겠습니다!

2020-03-06 08:07 UTC, hyochan-Kim commented on src/main/java/lotto/ConsoleLottoApplication.java
>      private static PurchaseLottos makePurchaseLottos(PurchaseAmount purchaseAmount) {
PurchaseLottos로 책임을 옮겨서 수동은 파라미터로 넘겨받고 자동은 만들게끔 수정하였습니다.

2020-03-06 08:07 UTC, hyochan-Kim commented on src/main/java/lotto/ConsoleLottoApplication.java
>      private static PurchaseLottos makePurchaseLottos(PurchaseAmount purchaseAmount) {
리뷰 요청을 너무 늦게 보내서 죄송합니다.. ㅠ

2020-03-07 08:41 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +        winningNumbers = inputLotto();
줄 수를 줄이는 것보다는 불필요한 코드는 줄이고, 불필요 해진 코드는 그때 정리한다는 걸로 고려해주세요! 😉

2020-03-07 09:12 UTC, Hue9010 commented on src/main/java/lotto/view/OutputView.java
> +    public static final String PRINT_PURCHASE_AMOUNT_FORMAT = "수동으로 %d장, 자동으로 %d개를 구매했습니다.\n";
여러 언어를 출력한다는게 어떤 상황일까요? 외국어와 같은 다른 언어를 말씀 주시는 건가요?

잠시 이전 단계였던 자동차 과제를 생각해볼까요?

```java
System.out.println(INPUT_CAR_NAME_SEPARATOR_COMMA_MESSAGE);
System.out.println(INPUT_TRY_COUNT_MESSAGE);
```

```java
System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
System.out.println("시도할 회수는 몇회인가요?");
```

이미 하비같은 경우는 본인이 짠 코드에다 최근 작업을 했기 때문에 PRINT_BONUS_CORRECT_MESSAGE 과 같은 문자열 상수가 어떤 문자열을 나타내는지 바로 아시겠지만 다른 사람, 예전 작업이라면 위의 두 가지 중 어느 코드가 더 나을지 한번 생각 해 볼 수있을 것 같아요.

말씀처럼 상수를 바꿀 이점이 있는 상황(예시로 주신 여러 언어)이라면 문자열 상수로 바꾸는게 더 나을 겁니다. 어떠한 상황을 고려해서(혹은 학습을 위한 가정) 작성해주셨다면 의미가 있었겠지만 현재는 불필요해 보입니다.

[유연한 코드를 짜고싶습니다](https://kldp.org/node/124632) 문자열 상수와는 관련이 없지만 한번 생각해볼 만한 글이라고 생각됩니다. 답변에 있는 `목적에 충실하게 간결하게`에 대해서 많이 공감하는 편입니다.

사실 여기서 어려운 부분이 그렇다면 미래에 대한 대비를 무조건 하지 말라는 아니기 때문에 `변경방향이 예측이 가능한데도 설계가 제대로 안된다면`이 부분입니다. 그래서 학습 차원에서 어떠한 가정을 가지고 작성해주셨냐에 따라 의미가 있는 상수인지 아닌지가 갈릴 걸로 보입니다. 😢

2020-03-07 09:18 UTC, Hue9010 approved these changes
피드백에 맞춰 잘 반영해주셨네요 👍 이번 단계는 여기서 머지하도록 할게요!
몇가지 생각해보실 만한 내용 코멘트로 남겼는데 확인해 주세요!  궁금하신 사항 있으면 코멘트나 DM으로 문의 주세요. 
피드백과 별개로 진행하면서 궁금하셨던 것들도 문의 주셔도 됩니다. 😉

2020-03-07 09:18 UTC, merged