[로또] 철시 미션 제출합니다.
woowacourse/java-lotto pull request #20
Opened 2019-05-30 12:30 UTC by pkch93

잘부탁드립니다! :)

2019-05-31 14:58 UTC, jihan805 requested changes
안녕하세요 철시님, 
전체적으로 잘 구현하셨어요 💯, 추가로 README에 구현 과정을 꼼꼼하게 기록한 부분이 굉장히 인상적이에요 👍 
몇가지 피드백 남겼으니 확인 부탁드릴게요 :)

2019-05-31 14:58 UTC, jihan805 commented on src/main/java/lotto/domain/generator/LottoGenerator.java
> +public class LottoGenerator {
LottoGenerator 클래스 추출 👍 
로또 생성은 자동/수동 방식이 있어요.
둘다 로또를 생성한다는 공통점이 있는데 인터페이스로 충분히 추출할 수 있지 않을까요?

2019-05-31 14:58 UTC, jihan805 commented on src/main/java/lotto/domain/BoughtLottos.java
> +        for (int i = 0; i < price / 1000 - countOfBoughtManual; i++) {
상수 사용!

2019-05-31 14:58 UTC, jihan805 commented on src/main/java/lotto/domain/Lotto.java
> +    public int hasNumber(final LottoNumber number) {
has~, is~ 는 주로 boolean 리턴에 대해 사용해요!

2019-05-31 14:58 UTC, jihan805 commented on src/main/java/lotto/domain/Prize.java
> +public enum Prize {
로또 결과를 enum 이용해 구현 👍
보너스볼 여부를 판단하기 위해 bonus인지 아닌지를 판단하는 값을 추가해보면 어떨까요?

2019-05-31 14:58 UTC, jihan805 commented on src/test/java/lotto/domain/BoughtLottosTest.java
> +    void init() {
전체적인 테스트 작성 👍 
init보다는 어떤 테스트인지 나타내는 이름이 더 좋을 것 같아요!

2019-05-31 14:58 UTC, jihan805 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    }
경계값을 이용해 테스트 작성 💯

2019-05-31 14:58 UTC, jihan805 commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +        int buyPrice = cuttingThousandPiece(inputBuyPrice());
Money와 같은 객체로 추출해보면 어떨까요?

2019-05-31 14:58 UTC, jihan805 commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +    }
전체적인 구현 👍 
가독성을 위해 묶을 수 있는 단위로 줄을 띄우면 어떨까요?

2019-05-31 14:58 UTC, jihan805 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final List<LottoNumber> numbers = new ArrayList<>();
LOTTO_START_NUMBER를 1로 충분히 구현할 수 있을 것 같아요!

2019-06-03 08:57 UTC, pkch93 commented on src/main/java/lotto/domain/generator/LottoGenerator.java
> +public class LottoGenerator {
안녕하세요 서머님! 좋은 피드백 감사합니다!!

궁금한 점이 있어서 이렇게 댓글 남깁니다!

위 LottoGenerator는 상태를 가질 필요가 없다고 판단하여 하나의 LottoGenerator를 통해
static 메서드로 자동 / 수동 방식을 구현했었습니다.
피드백으로 인터페이스를 말씀해주셨는데 이 경우는 각각 static 메서드가 아닌 일반 메서드를 override하여 구현하는 게 좋을 것 같다는 말씀이신가요??

2019-06-03 09:07 UTC, pkch93 commented on src/main/java/lotto/domain/Prize.java
> +public enum Prize {
서머님께서 bonus 값을 추가하라는 피드백을 주셔서 반영을 해봤는데 결국 똑같은 코드가 되어 이렇게 질문드립니다. 

```java
// 반영 이전 (보너스 판단 값 x)
if (SECOND.matchCount(countOfNumber) && hasBonus) {
    return SECOND;
}
// 반영 이후 (보너스 판단 값 requiredBonus 적용)
if (SECOND.requiredBonus == hasBonus && SECOND.matchCount(countOfNumber)) {
    return SECOND;
}
```
위와 같이 SECOND 하나에 대해서만 Bonus 값이 필요하기 때문에 동일한 로직으로 구현이 되는 것 같습니다.
제가 주신 피드백에 대한 활용방안을 잘 모르겠어서 그런데 어떤 활용방안이 있을 수 있을 지 여쭤봐도 될까요???

2019-06-05 05:45 UTC, pkch93 commented
주신 피드백 토대로 구현해보았습니다!
아직 여전히 Generator에 대해 의문을 가지고 있습니다,, 상태값을 가질 필요가 없을때 static 메서드로 작성해야하는지와 이 과정에서 공통점이 보인다면 interface로 공통기능을 추출하여 각각의 구현체를 만드는 게 나은지에 대해서요,,

enum에 대해서는 먼저 보너스 필요 여부를 값으로 넣어봤으나 이전과 로직이 같은 코드가 나와서 enum에 대해서 알아보고 고민해 본 결과 추상메서드를 사용하여 구현해보았습니다,,

이번에도 좋은 피드백 부탁드립니다 :) 감사합니다!

2019-06-06 06:27 UTC, jihan805 commented on src/main/java/lotto/domain/generator/LottoGenerator.java
> +public class LottoGenerator {
네!!

2019-06-06 06:30 UTC, jihan805 commented on src/main/java/lotto/domain/BoughtLottos.java
> +    public static final int BUY_PRICE = 1000;
상수 활용 👍 
금액은 단위를 표현하기 위해 1_000와 같이 언더바로 구분해요!
위와 같이 표현하면 금액이 늘어나더라도 쉽게 읽을 수 있으므로 변경하면 어떨까요?

2019-06-06 06:30 UTC, jihan805 commented on src/main/java/lotto/domain/Prize.java
> +public enum Prize {
enum의 bonus가 true인 경우에만, 보너스볼로 넘어온 hasBonus를 확인하도록 하면 특정 경우(SECOND)에 대한 조건문을 줄일 수 있을 것 같아요!

2019-06-06 06:57 UTC, jihan805 approved these changes
안녕하세요 철시님!
전체적으로 피드백 반영 💯 
아주 간단한 코멘트 남겨두었으니 다음 단계 진행시 반영 부탁드릴게요!
머지 진행할게요~ 연휴 즐겁게 보내세요 :)

2019-06-06 06:57 UTC, jihan805 commented on src/main/java/lotto/domain/LottosGenerator.java
> +    List<Lotto> generate();
로또 생성은 상태가 없기 때문에 static 메서드로 구현하셨다고 코멘트에 남겨주셨습니다! 💯 
하지만 기존의 LottosGenerator에 대해 조금 더 자세히 고민해보면 수동 생성 + 자동 생성 두가지를 모두 담당하고 있고 
이는 충분히 분리할 수 있지 않을까요!?
한단계 더 나아가면 수동/자동 생성은 모두 "생성"이라는 공통점이 있으므로 이를 인터페이스로 추출할 수 있고요!
각각 로또를 생성하기 위해 필요한 인자가 다릅니다(갯수, 입력받은 리스트) 
이 부분에 대해  생성자를 활용해 처리 한 부분 역시 👍 잘하셨습니다.  💯 

추가로 피드백 남겨보겠습니다!
자동/수동 로또를 통합해 하나의 완전한 로또를 생성하도록 BoughtLottos 클래스를 수정해보면 어떨까요? 
main로직을 더 깔끔하게 변경할 수 있을 것 같아요!!

2019-06-06 06:57 UTC, jihan805 commented on src/main/java/lotto/view/validator/InputValidator.java
> +        if (!(maxBuyLotto - countOfManualBuyLotto >= 0)) {
이 부분 역시 상수를 사용할 수 있을 것 같아요!

2019-06-06 06:57 UTC, jihan805 commented on src/main/java/lotto/view/validator/InputValidator.java
> +        if (!BUY_PRICE_REGEX.matcher(buyPrice).matches()) {
InputValidator를 통해 input 에 대한 validation 체크  👍 

꼭 고민해보아야 할 중요한 부분이라고 생각해요!
로또 한장의 금액이 1000원 이상이어야 한다 - Money 클래스 / 로또한장에 중복이 있으면 안된다 - Lotto 클래스
~ 등과 같이 각 클래스에서 담당해야하는 벨리데이션도 섞여 있다고 생각해요.
Validator를 이용하는 것과 각 클래스가 역할에 맞는 벨리데이션을 책임지도록 하는 것은 어떤 차이가 있을까요?

2019-06-06 06:57 UTC, jihan805 commented on src/main/java/lotto/domain/generator/LottosAutoGenerator.java
> +        List<LottoNumber> numbers = allLottoNumbers.subList(0, 6);
0~6 역시 상수를 사용할 수 있는 의미있는 숫자라고 생각해요!

2019-06-06 06:58 UTC, merged

2019-06-10 06:16 UTC, pkch93 commented on src/main/java/lotto/view/validator/InputValidator.java
> +        if (!BUY_PRICE_REGEX.matcher(buyPrice).matches()) {
https://jojoldu.tistory.com/157

위 게시글을 통해 주신 피드백에 대해 학습하였습니다. 이번 미션에서 InputValidator는 프론트 단의 값을 처리하는 부분, 클래스가 역할에 맞는 벨리데이션을 가지는 것은 서버단이라고 생각하면서 이해해보았습니다.

현재 lotto 미션에서는 뷰에서 받은 값이 바로 Lotto나 Money등으로 전달되기 때문에 값이 변질되지는 않지만 프론트(InputView)에서 입력되는 값은 변질될 우려가 있기 때문에 실제 입력값으로 로직을 반영하는 클래스(서버)에서 예외에 따른 처리를 해줘야한다고 생각합니다.

좋은 피드백 감사합니다 :)