[소니] 로또 2단계 - 수동 로또 미션 제출합니다.
woowacourse/java-lotto pull request #200
Opened 2020-02-27 08:48 UTC by sonypark

진행중
-  Custom Exception 처리

예외 처리 부분은 보완하여 오늘 안에 추가 푸시하겠습니다!

2020-02-28 17:55 UTC, phs1116 requested changes
안녕하세요, 소니! 리뷰어 화투입니다.
구현 깔끔하게 잘해주셨어요. :)
조금 더 정리 할 수 있을 것 같아 피드백 추가했구요.
이전 피드백에서 질문하신 내용에 대해서도 답변 달았습니다.
확인 부탁드리고 궁금하신 점 있으시면 연락주세요. :)

2020-02-28 17:55 UTC, phs1116 commented on src/main/java/lotto/domain/WinningLotto.java
> +public class WinningLotto {
[이전 피드백 질문](https://github.com/woowacourse/java-lotto/pull/147/files#r384503864)에 대한 답변 추가할게요!
로또 번호와 당첨 번호는 IS A 관계라고 보기 어렵습니다.
숫자 번호를 포함하고 있지만 두 객체가 제공해야 하는 API가 상이하기 때문입니다.
일반적으로 구현체는 항상 확장을 위해 구현체가 가지고있는 추상체를 통해 참조가 이루어집니다.
하지만 bonusNumber에 대한 연산은 Lotto는 가지고 있지 않습니다. 
bonusNumber에 대한 로직을 수행하려면 WinningLotto로 명시적인 캐스팅이 이루어져야 가능합니다.
IS A 관계는 말 그대로 모두 똑같은 행위를 할 때에 적합하다고 할 수 있을 것 같습니다.
(주로 인터페이스의 구현시에 어울립니다.)
또한 만약 match를 Lotto에서 구현후 WinningLotto에서 
오버라이딩을 한다고 해도 Lotto.match(winningLotto)와 WinningLotto.match(lotto)는 bonusNumber때문에 다르게 동작할 가능성이 큽니다. 그럼 객체지향 원칙 중 리스코프 치환 원칙에 위배됩니다.

아래 블로그 내용을 참고해보면 좋을 것 같습니다. :)
[가급적 상속(Inheritance) 보다는 컴포지션(composition)을 사용하자.](https://github.com/woowacourse/java-lotto/pull/147/files)
[리스코프 치환 원칙](http://wonwoo.ml/index.php/post/1780)

2020-02-28 17:55 UTC, phs1116 commented on src/main/java/lotto/domain/LottoGame.java
>          return WinningRanksFactory.create(ranks);
현재 Ranks, WinningRanksFactory가 굳이 필요할까요? :)
Ranks, WinningRanksFactory가 가지고 있는 역할이 없다보니
WinninRanks를 winningLotto.match의 결과로 리턴해도 무방해보여서요.

2020-02-28 17:55 UTC, phs1116 commented on src/main/java/lotto/domain/LottoGame.java
>      private Result produceResult(Lottos lottos, Money purchaseMoney) {
WinningLottos내에 있는 로또의 갯수로 로또의 금액을 알 수 있으니 굳이 purchaseMoney도 전달받지 않아도 될 것 같아요. :)
그럼  `Result result = winningLotto.match(lotto)`로 더 간결해 질 수 있겠네요!

2020-02-28 17:55 UTC, phs1116 commented on src/main/java/lotto/domain/Lottos.java
> +        return new Lottos(result);
불변 객체 보장 👍

2020-02-28 17:55 UTC, phs1116 commented on src/main/java/lotto/domain/ManualLottoFactory.java
> +        return new Lotto(values.stream().map(LottoNumber::new).collect(
LottoNumber::new 매번 재 생성 될 필요가 없는데 여기선 재생성 되네요.
재사용 해보도록 수정해보면 어떨까요? :)

2020-02-28 17:55 UTC, phs1116 commented on src/main/java/lotto/domain/WinningLotto.java
> +                .count();
디미터 원칙에 위배되는 것 같네요.
getter를 통해 연산을 여기서 처리하지 말고 Lotto 스스로가 matchNumber를 가져오도록 해보면 어떨까요?

2020-02-28 17:55 UTC, phs1116 commented on src/main/java/lotto/domain/WinningLotto.java
> +        return lottoNumbers.getLottoNumbers().contains(bonusNumber);
마찬가지로 디미터 원칙 위반이네요. :)
lotto.contains(bonusNumber) 형태로 할 경우 로직도 더 심플해 질 것 같아요.

2020-02-29 14:00 UTC, sonypark commented on src/main/java/lotto/domain/WinningLotto.java
> +public class WinningLotto {
상속과 컴포지션에 대한 관계가 많이 헷갈렸는데 자세히 설명해주신 덕분에 이해가 되었습니다. 제가 헷갈렸던 부분이 개념적으로는 Lotto와 WinningLotto가 IS-A 관계로 상속 관계인 것 같았기 때문입니다. 그런데 개개념적으로 상속관계라 하더라도 구현 상에서는 상속 관계가 아닐 수 있구나라는 걸 깨달았습니다.

말씀하신대로 Lotto와 WinningLotto는 객체가 제공하는 API가 다릅니다. 즉, 생성자에서 받는 인자가 다르므로 상속관계가 아닙니다. 또한 상속관계는 부모 객체의 행위를 자식 객체도 똑같이 할 때 적합한데 이 경우에는 그렇지 않습니다. 설령 부모 객체에 자식 객체에서 사용하는 메서드를 만들어 똑같게 만든다고 해도 동작 자체가 달라지기 때문에 리스코프 치환 원칙에 어긋납니다. 그렇기 때문에 위 경우에는 상속이 아닌 컴포지션으로 구현하는게 적합하다고 판단됩니다.

덕분에 헷갈리던 부분이 정리되었습니다. 감사합니다! :)

2020-02-29 14:53 UTC, sonypark commented on src/main/java/lotto/domain/LottoGame.java
>      private Result produceResult(Lottos lottos, Money purchaseMoney) {
네 lottos의 사이즈를 이용해 로또 가격을 구하니 purchaseMoney를 인자로 전달하지 않아도 되네요! 감사합니다.

2020-02-29 15:39 UTC, sonypark commented on src/main/java/lotto/domain/WinningLotto.java
> +                .count();
Lotto 에서 매칭 번호를 확인하도록 하니 훨씬 더 간결해지고 디미터의 원칙도 지킬 수 있네요. 피드백 감사합니다!

2020-02-29 15:45 UTC, sonypark commented on src/main/java/lotto/domain/WinningLotto.java
> +        return lottoNumbers.getLottoNumbers().contains(bonusNumber);
네 이 부분도 위와 같은 로직이기 때문에 같이 해결했습니다.

2020-03-02 10:56 UTC, sonypark commented on src/main/java/lotto/domain/LottoGame.java
>          return WinningRanksFactory.create(ranks);
역할을 최대한 나누려고 하다가 불필요한 클래스를 만든 것 같습니다. 역할이 있다고 생각했는데 자세히 보니 특별한 역할이 없는 클래스들이었네요. 말씀하신대로 `winningLotto.match()`의 결과로 WinninRanks를 리턴하도록 수정했습니다 :)

2020-03-02 11:15 UTC, sonypark commented on src/main/java/lotto/domain/ManualLottoFactory.java
> +        return new Lotto(values.stream().map(LottoNumber::new).collect(
이 부분은 어떻게 수정해야할지 감이 잘 잡히지 않습니다..😢 LottoNumber 생성자를 통해 로또 번호를 만드는 로직인데, 재생성하지 않고 할 수 있는 방법이 있을까요?

2020-03-04 14:03 UTC, phs1116 requested changes
안녕하세요, 소니! 리뷰 늦어서 죄송해요. :(
구현 정말 깔끔하게 잘해주셨어요! 👍 
질문 주신 사항에 대해서 구현을 조금 더 해보면 좋을것 같아 해당 피드백이랑
간단한 피드백 더 추가했어요. :)
참고 부탁드리고 궁금하신 점 있으시면 연락주세요!

2020-03-04 14:03 UTC, phs1116 commented on src/main/java/lotto/domain/ManualLottoFactory.java
> +        return new Lotto(values.stream().map(LottoNumber::new).collect(
Lotto 내에 미리 생성하거나, 생성했던 값을 저장하고 있으면 되지 않을가요? :)
`이펙티브 자바 아이템 1. 생성자 대신 정적 팩터리 메서드를 고려하라`
해당 내용을 참고해보시면 생성자에서는 못하는 정적 팩터리 매서드의 장점으로, 생성 시 객체의 사용을 할 수 있다는 부분이 있어요.
생성자가 아닌 정적 팩터리 매서드를 활용해보고, 생성되어있는 값들을 돌려주는것도 고민해보시면 될 것 같습니다.
이 경우 생성자로의 생성은 막아야겠죠? :)

2020-03-04 14:03 UTC, phs1116 commented on src/main/java/lotto/domain/WinningLotto.java
>          }
stream을 사용해 정리해보는것도 좋을 것 같아요. :)

2020-03-04 14:03 UTC, phs1116 commented on src/main/java/lotto/domain/WinningLotto.java
> +        }
별도 null처리를 하지 않고 Map.getOrDefault을 활용해보면 어떨까요?

2020-03-04 14:03 UTC, phs1116 commented on src/main/java/lotto/domain/Rank.java
> +            .orElseThrow(() -> new InvalidRankException("당첨된 갯수에 해당하는 순위가 없습니다."));
등수 별 bonusNumber match 조건을 로직 말고 각 enum 값들이 가지고 있도록 해보면 어떨까요? :)

2020-03-05 05:14 UTC, sonypark commented on src/main/java/lotto/domain/WinningLotto.java
> +        }
Map에 `getOrDefault` 라는 메서드가 있었군요! 참고하여 적용했습니다 :)

2020-03-05 05:14 UTC, sonypark commented on src/main/java/lotto/domain/WinningLotto.java
>          }
네 이 부분은 stream으로 정리한 후 함수로 분리해보았습니다. :)

2020-03-05 06:02 UTC, sonypark commented on src/main/java/lotto/domain/Rank.java
> +            .orElseThrow(() -> new InvalidRankException("당첨된 갯수에 해당하는 순위가 없습니다."));
보너스 넘버를 체크하는 로직은 Rank의 2등(SECOND),3등(THIRD)에만 해당하고 나머지 등수에는 해당하지 않아서 enum값들이 갖지 않게 했었습니다. 하지만 말씀하신대로 enum으로 로직을 이동하니 코드가 더 깔끔해진 것 같습니다. 2,3등을 제외한 나머지 등수에는 보너스 넘버 체크할 필요가 없지만, 그럼에도 코드의 가독성 측면에서는 로직 대신에 enum값들이 갖도록하는게 더 나아 보이네요 :) 조언 감사합니다!

2020-03-05 15:26 UTC, phs1116 approved these changes
안녕하세요, 소니! 리뷰어 화투입니다.
깔끔하게 잘 구현해주셨어요. 👍 
피드백 반영도 잘해주셨습니다.
이번 단계 이만 머지할게요. :)
아 그리고 간단한 피드백 추가했는데 한번 꼭 참고 부탁드릴게요.
고생 많으셨어요. :)

2020-03-05 15:26 UTC, phs1116 commented on src/main/java/lotto/domain/Rank.java
> +            .orElseThrow(() -> new InvalidRankException("당첨된 갯수에 해당하는 순위가 없습니다."));
가독성도 가독성이지만 enum의 각 값들도 하나의 객체입니다. :)
절차적인 로직이 아닌 캡슐화하여 객체 스스로가 판단하는게 객체지향 관점에서 더 적합하다고 봐요. :)

2020-03-05 15:26 UTC, phs1116 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
정적 팩터리 메서드 활용 👍 
다만 null일 경우 전체 캐시를 생성하는것 보단, 필요한 것만 생성하여 저장하거나
애초에 static 초기화 블럭을 통해서 생성해도 괜찮지 않았을까요? :)

2020-03-05 15:26 UTC, phs1116 commented on src/main/java/lotto/domain/ManualLottoFactory.java
> +    }
이정도 책임이면 그냥 생성자를 사용해도 됬을 것 같네요. :)

2020-03-05 15:26 UTC, merged

2020-03-06 09:15 UTC, sonypark commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
static 블록으로 초기화하는 방법은 몰랐었는데 이번에 알게되었습니다. static 블록에서 1~45까지 전체 로또 번호를 초기화 한 후 null인 번호가 있을 경우에는 해당 번호만 다시 생성하는 것으로 수정했습니다. 피드백 감사합니다!

2020-03-06 09:16 UTC, sonypark commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
```java
public class LottoNumber {
    private static final int MAX = 45;
    private static final int MIN = 1;
    private static final Map<Integer, LottoNumber> CACHE = new HashMap<>();
    private int value;

    static {
        createCache();
    }

    private LottoNumber(int value) {
        this.value = value;
    }

    private static void validateValue(int value) {
        if (value < MIN || MAX < value) {
            throw new InvalidLottoNumberException("유효하지 않은 로또 번호입니다");
        }
    }

    public static LottoNumber of(int value) {
        validateValue(value);
        if (CACHE.get(value) == null) {
            createLottoNumber(value);
        }
        return CACHE.get(value);
    }

    private static void createCache() {
        List<LottoNumber> lottoNumberInBox = createLottoNumberBox();
        for (int i = MIN; i < MAX + 1; i++) {
            CACHE.put(i, lottoNumberInBox.get(i - 1));
        }
    }

    private static void createLottoNumber(int value) {
        CACHE.put(value, new LottoNumber(value));
    }
```