[로또] 뚱이 미션 제출합니다.
woowacourse/java-lotto pull request #22
Opened 2019-05-31 05:40 UTC by starkim06

[로또] 뚱이 미션 제출합니다.

2019-05-31 15:26 UTC, jihan805 requested changes
안녕하세요 뚱이님,
전체적인 클래스 추출 👍 잘 구현하셨어요!
몇가지 피드백 남겼으니 확인 부탁드릴게요 :)

2019-05-31 15:26 UTC, jihan805 commented on src/main/java/lotto/domain/factory/LottoTicketsFactory.java
> +public class LottoTicketsFactory {
LottoTicketsFactory 클래스 추출 👍 
로또 생성은 자동/수동 방식이 있어요.
둘다 로또를 생성한다는 공통점이 있는데 인터페이스로 충분히 추출할 수 있지 않을까요?

2019-05-31 15:26 UTC, jihan805 commented on src/main/java/lotto/domain/LottoMoney.java
> +        if (money % LottoTicket.PRICE != 0) {
LottoMoney 클래스 추출 💯 
상수 활용!
전체적으로 상수를 사용할 수 있는 부분을 확인해보고 적용해보면 어떨까요?

2019-05-31 15:26 UTC, jihan805 commented on src/main/java/lotto/domain/LottoRank.java
> +public enum LottoRank {
Rank를 enum 이용해 구현 👍
보너스볼 여부를 판단하기 위해 bonus인지 아닌지를 판단하는 값을 추가해보면 어떨까요?

2019-05-31 15:26 UTC, jihan805 commented on src/main/java/lotto/domain/LottoResults.java
> +        return (double) getRewardMoney() / lottoMoney.getMoney() * PERCENT;
get하지 않고 구현해보면 어떨까요?

2019-05-31 15:26 UTC, jihan805 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +
경계값을 이용한 테스트 작성 👍 
1, 2와 같은 네이밍 보다는 해당 테스트가 어떤 경우를 테스트하였고 어떤 결과를 기대하는지에 대해 나타낼 수 있도록 작성하면 좋을 것 같아요!

2019-05-31 15:26 UTC, jihan805 commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    @Test
로또 티켓 한장은 중복된 숫자를 가질 수 없어요! 
관련하여 테스트도 작성해보면 어떨까요?

2019-05-31 15:26 UTC, jihan805 commented on src/main/java/lotto/ConsoleLottoApplication.java
> +        List<LottoTicket> lottoTickets = LottoTicketsFactory.create(manualAmount, manualLottoNumbers, lottoMoney);
일급 콜렉션으로 여러장의 로또를 구현하면 어떨까요?

2019-05-31 15:26 UTC, jihan805 commented on src/main/java/lotto/domain/LottoNumber.java
> +            return LottoNumberCache.cache.get(number-1);
space  컨벤션 !

추가로, 팩터리 메서드는 생성자 다음에 위치하도록 해요!

2019-06-01 05:58 UTC, starkim06 commented on src/main/java/lotto/domain/LottoNumber.java
> +            return LottoNumberCache.cache.get(number-1);
피드백 감사합니다. 수정하였습니다.

2019-06-01 06:00 UTC, starkim06 commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    @Test
피드백 감사합니다. 수정하였습니다.

2019-06-01 06:01 UTC, starkim06 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +
피드백 감사합니다.
수정하였습니다.

2019-06-01 06:07 UTC, starkim06 commented on src/main/java/lotto/domain/LottoResults.java
> +        return (double) getRewardMoney() / lottoMoney.getMoney() * PERCENT;
피드백 감사합니다.
수정하였습니다.

2019-06-01 06:12 UTC, starkim06 commented on src/main/java/lotto/domain/LottoMoney.java
> +        if (money % LottoTicket.PRICE != 0) {
피드백 감사합니다. 수정하였습니다.
[질문]
위의 클래스의 경우에는 똑같은 0 이라는 값을 각각 다른 의미로 사용해서 상수를 2개로 정의해 주었습니다.
이런 경우에는 하나로 통합하고 두개모두 사용될수 있는 이름으로 하는게 좋을까요? 
아니면 지금처럼 같은 0 이지만 의미가 다르니 2개로 분리 시켜주는게 좋을까요 ?

2019-06-01 11:23 UTC, starkim06 commented on src/main/java/lotto/ConsoleLottoApplication.java
> +        List<LottoTicket> lottoTickets = LottoTicketsFactory.create(manualAmount, manualLottoNumbers, lottoMoney);
피드백 감사하였습니다. 수정하였습니다.

2019-06-02 06:03 UTC, jihan805 approved these changes
안녕하세요 뚱이님, 피드백 반영 💯아주 간단한 추가 피드백 남겼으니 확인 부탁드려요!
머지 진행할게요~!
감사합니다 :)

2019-06-02 06:03 UTC, jihan805 commented on src/main/java/lotto/domain/factory/LottoTicketsFactory.java
> +    private static final String DELIMITER = ",";
해당 클래스에서 DELIMITER는 사용하고 있지 않는 것 같아요!
삭제해도 좋을 것 같아요!

2019-06-02 06:03 UTC, jihan805 commented on src/main/java/lotto/domain/LottoRank.java
> +        if (countOfMatch == 5 && hasBonusBall) {
상수 활용!
추가로 상수를 활용할 수 있는 부분에 대해 전체적으로 한번 더 확인해보면 어떨까요?

2019-06-02 06:03 UTC, jihan805 commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static final int PRICE = 1000;
LottoRank 처럼 💯  1_000 와 같이 언더바를 이용해 단위를 구분할까요?

2019-06-02 06:03 UTC, jihan805 commented on src/main/java/lotto/domain/LottoTickets.java
> +    public Map<LottoRank, Integer> getRewards(WinningLotto winningLotto) {
리턴 타입을 LottoResults로 활용해도 좋을 것 같아요!

2019-06-02 06:03 UTC, merged

2019-06-02 10:56 UTC, starkim06 commented on src/main/java/lotto/domain/factory/LottoTicketsFactory.java
> +    private static final String DELIMITER = ",";
피드백 수정했습니다.
감사합니다 =)

2019-06-02 10:58 UTC, starkim06 commented on src/main/java/lotto/domain/LottoRank.java
> +        if (countOfMatch == 5 && hasBonusBall) {
피드백 수정했습니다.
감사합니다 =)

2019-06-02 10:59 UTC, starkim06 commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static final int PRICE = 1000;
피드백 수정했습니다.
감사합니다 =)