[히로]로또 2단계 - 수동 미션 제출합니다.
woowacourse/java-lotto pull request #220
Opened 2020-02-29 14:26 UTC by hotheadfactory

안녕하세요. 우테코 크루 히로입니다.

2단계 미션을 위해 코드를 수정하며 특히 원시값 포장과 MVC 패턴에 대해 고민해 보았습니다.

이번 미션을 구현하면서 생긴 질문에 대해서 짤막하게 같이 달아 봅니다. 

1. Lotto 클래스가 DTO를 만들어 리턴하고 있습니다. 이렇게 설계하는 것이 DTO의 의도에 맞는 것인가요? 아니라면 어떻게 해야 할까요?
2. 로또 번호를 보여주기 위해 원시값을 이용하는 대신 Lotto, LottoDto, LottoDtos에 toString()을 오버라이딩해 사용했습니다. 객체의 immutability를 지켜주기 위해 사용한 방법이지만, 이런 방법이 설계상 옳을까요?
3. Lotto 객체에 메시지를 보내는 식으로 등수 확인을 구현했습니다. Lotto 객체에서 등수 enum을 리턴하는 것까지 다 시키는 지금 방법이 맞는 방법일까요?
4. LottoCount 객체는 생성자로 구매 금액과 수동으로 구매할 로또수를 받습니다. 이 경우 수동 로또 수가 에러가 나면 구매 금액부터 다시 입력해야 합니다. 이걸 어떻게 해결할 수 있을까요?

2020-03-02 19:36 UTC, Hue9010 requested changes
몇가지 피드백 남겨드렸습니다!
약간 헷갈릴 수도 있는 부분이 있을 것 같은데 그런 부분은 너무 고민하지 마시고 코멘트나 DM으로 문의 주세요!

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoCount.java
> +	public int getTotalLottoCount() {
작은 부분인데 사용하지 않게 된 메서드는 그때 그때 지워주는게 좋답니다 😄

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/utils/InputUtil.java
> +	public static final String INPUT_WINNING_NUMBER = "지난 주 당첨 번호를 입력해 주세요.";
혹시 인텔리제이를 사용하신다면 사용하지 않는 메서드/변수의 이름은 회색처리가 된답니다. 이클립스는 사용한지 오래되서 확실치 않지만 마찬가지로 미사용 코드에 대해서는 특정한 처리가 됐던걸로 기억하는데 미사용하게 된 코드는 그때 그때 지워주는게 좋답니다.

예를 들어서 2년 전 자신의 코드를 유지보수 할 일이 있는데 미사용하는 코드가 있어도 그때 돼서는 지워도 되는지 아닌지 판단하는데 약간의 고민의 시간이 필요할 수도 있답니다. 더군다나 자신이 짠 코드가 아닌 다른 사람이 짠 코드면 더 그럴 수도 있답니다.

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoCount.java
> +			throw new LottoCountException(NOT_ENOUGH_MONEY);
1.  NOT_ENOUGH_MONEY는 다른 곳에서는 사용하는 곳이 없습니다. private로 둬도 충분 할 것 같습니다.
2. 문자열을 직접 쓰지 않고 상수로 치환한 이유는 무엇일까요? 혹시나 한글을 직접 입력하는게 만족스럽지 않았다면 메시지 자체를 영어로 작성하면 어떨까요?
   ```java
        throw new LottoCountException(NOT_ENOUGH_MONEY);
        throw new LottoCountException("돈이 부족합니다.");
        throw new LottoCountException("not enough money");
   ```
   [개발자 1년차, 5년차, 10년차 코드](https://zetawiki.com/wiki/%EA%B0%9C%EB%B0%9C%EC%9E%90_1%EB%85%84%EC%B0%A8,_5%EB%85%84%EC%B0%A8,_10%EB%85%84%EC%B0%A8_%EC%BD%94%EB%93%9C) 유머로 사용되는 내용이긴 한데 한번 생각 해볼 여지가 있을 것 같네요. 😸

2020-03-02 19:36 UTC, Hue9010 commented on src/test/java/lotto/domain/LottoMachineTest.java
> +		assertThat(lottoMachine.makeRandomLottos(6).size()).isEqualTo(6);
테스트가 실패하는 걸로 보입니다. 확인해주세요! ✔️ 
`makeRandomLottos(6)`

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/view/OutputView.java
> +			System.out.println(lotto.toString());
`.toString()`을 안 붙이셔도 됩니다 😄

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoController.java
>  		OutputView.printLottos(lottos.makeLottoDtos());
1. Lotto 클래스가 DTO를 만들어 리턴하고 있습니다. 이렇게 설계하는 것이 DTO의 의도에 맞는 것인가요? 아니라면 어떻게 해야 할까요?

Controller Layer -> (Output)View Layer로 전달 해 줄 때 사용한 점에서 DTO를 제대로 사용한 게 맞습니다. 👍 

2. 로또 번호를 보여주기 위해 원시값을 이용하는 대신 Lotto, LottoDto, LottoDtos에 toString()을 오버라이딩해 사용했습니다. 객체의 immutability를 지켜주기 위해 사용한 방법이지만, 이런 방법이 설계상 옳을까요?

1번에 대한 답변에 조금 이어서 마저 얘기하면 OutputView가 지금과 같이 자바 환경이 아니라면 오버라이딩 된 toString이 실행 될 수 있을까요?(예를 들면 js환경이라면?) 또한 toString으로 출력하는게 데이터를 전달 받은 걸로 볼 수 있을까요?
dto는 Data Transfer Object로서 데이터를 전달해주기 위한 객체로 단순하게 코드 레벨로 보면 getter를 통해서 자신이 가진 데이터를 전달 해 줄 수 있어야 합니다.
사실 LottosDto -> LottoDto -> LottoNumber를 가지는 구조를 띄고 있는데 LottoNumber까지 Dto나 Integer 타입(List인 관계로)으로 마저 변환을 해주셔야 합니다.

이전에 DTO 사용에 대해서 약간(?) 염려를 한 부분이 이러한 이유였답니다. 이번 로또 예제의 경우 DTO를 사용하기 때문에 생기는 변환 작업 대비 이점이 크게 보이지 않습니다. 아마 Lottos, Lotto, LottoNumber에 getter가 존재하지 않고 DTO에만 존재하는 정도 밖에는 이점이 없을 것 같네요.

toString을 사용하거나 getter를 사용하지 않는 것과 immutability를 지켜주는 것은 별개의 영역인데 getter 제공하더라도 unmodifiableList를 제공하면 외부에서 값을 변경 하지 못합니다. 혹은 딥 카피를 한 새로운 리스트를 제공해 줄 수도 있습니다. 또는 이번과 같이 Dto로 변환하여 전달해 줄 수도 있겠네요.

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotto.java
> +	public WinningPrize findLottoPrize(WinningLotto winningLotto) {
3. Lotto 객체에 메시지를 보내는 식으로 등수 확인을 구현했습니다. Lotto 객체에서 등수 enum을 리턴하는 것까지 다 시키는 지금 방법이 맞는 방법일까요?

- 로또를 가지고 당첨번호와 맞춰본다
- 당첨번호를 가지고 로또와 맞춰본다
둘 다 충분히 가능하다고 봅니다. 👍
상점을 구현한 경우라면 상점을 통해서 로또와 당첨 번호를 가지고 맞춰보는 것도 가능하다고 봅니다.

find보다는 당첨 번호와 로또를 맞춰본다는 의미로 match를 활용한 이름은 어떨까요?
혹은 enum인 `WinningPrize`을 반환하는게 마음에 들지 않았던 걸까요?

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoController.java
>  	}
4. LottoCount 객체는 생성자로 구매 금액과 수동으로 구매할 로또수를 받습니다. 이 경우 수동 로또 수가 에러가 나면 구매 금액부터 다시 입력해야 합니다. 이걸 어떻게 해결할 수 있을까요?

아주 간단한 방법으론 
```java
	private static Lottos buyLottos(int money, int manualLottoCount) {
		try {
			LottoCount lottoCount = new LottoCount(money, manualLottoCount);
			List<Lotto> lottos = new ArrayList<>();
			lottos.addAll(buyManualLottos(lottoCount));
			lottos.addAll(LottoMachine.getInstance().makeRandomLottos(lottoCount));
			OutputView.printLottoCount(lottoCount.getManualLottoCount(), lottoCount.getAutoLottoCount());
			return new Lottos(lottos);
		} catch (LottoCountException e) {
			OutputView.printExceptionMessage(e);
			return buyLottos(money, readManualLottoCount());
		}
	}
```
와 같이 바꾸는 방법이 존재할 것 같습니다. 다만, money 값에 문제가 있어도 LottoCountException이 발생하여 무한 루프에 빠진다는 점에서 사용할 방법은 아닙니다.
Exception의 메시지까지 확인해서 catch에서 분기해 줘도 되지만 그것보다는 금액과 갯수에 대한 Exception을 별도로 두는 방법도 존재하고, LottoCount를 생성하는 시점에서 잘못 된 값이 들어온 것이기 때문에 생성시 필요한 두 값에 대해서 다시 입력 받는게 정상적인 처리 로직일 수도 있습니다.

이 부분도 InputView에서 LottoCountDto를 통해 전달 받았다면 아마도
```java
public class LottoCountDto {

	private final int lottoCount;
	private final int manualLottoCount;

	public int lottoCountGetter() {
		return lottoCount;
	}

	public int maualLottoCountGetter() {
		return manualLottoCount;
	}
}
```
이 와 같은 Dto를 통해 View에서 Controller로 전달 받았을 텐데 둘 중 한 값이라도 잘 못됐다면 특정 값이 아니라 두 값을 다시 전달 받아야겠죠? 😄

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/dto/LottoDtos.java
>  	public List<LottoDto> getLottoDtos() {
Lottos의 Dto라면 s를 붙이지 말고 LottosDto로 만들어주세요!
정말로 LottosDtos만 보면 List<LottoDto>와 같은 복수개의 LottoDto와 혼동을 줄 수 있는 이름이랍니다.
메서드 이름을 짓는 규칙이 정해져 있는건 아니지만 toDto 같은 이름을 사용할 수도 있답니다. (거꾸로 dto쪽에서는 from을 사용 할 수도 있고요 😄  )

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoController.java
> +	}
약간 고민이 됐던 부분인데 InputView를 만들고 InputUtil의 내용과 Controller에 존재하는 readManualLottoCount와 같이 입력에 관여되는 부분은 모두 InputView로 옮겨보세요.
현재 Controller에서 입력에 대한 처리가 너무 많아 보이네요. 일단 NumberformatException 같은 부분도 InputView로 옮겨보세요! 

사실 아래 존재하는 readLottoNumber의 경우도 이름상으로는 로또넘버를 읽어오는 메서드지만 Lotto를 생성하고 있습니다

2020-03-02 19:36 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoMachine.java
> +	public List<LottoNumber> pickDedicatedBalls(List<Integer> LottoNumbers) {
테스트 코드에서밖엔 사용을 안하네요.
LottoMachine을 보면 LottoNumber와 Lotto 둘다 생성을 하는데 어떤 역할/책임을 가진 걸까요?

또한 LottoNumber, Lotto, Lottos 중에서 의도하신 것에 대해서만 만들어주는 책임을 가지게 하는게 좋을 것 같네요.(이건 어떤 역할을 고려하신 건지에 따라 나뉘겠네요.)
이미 List<LottoNumber>의 일급 컬렉션으로 Lotto가, List<Lotto>의 일급 컬렉션인 Lottos가 존재하는데 List를 반환하지 않을 수 있다면 일급 컬렉션으로 제공해주는 방향으로 가는게 좋을 것 같네요.(다만 이건 LottoNumber, Lotto, Lottos가 생성되는 방식이 바뀔 수도 있을 것 같아 일단 보류하는게 좋을 것 같습니다..)

2020-03-03 04:36 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoCount.java
> +			throw new LottoCountException(NOT_ENOUGH_MONEY);
2. 문자열을 상수로 치환한 것은 코드 상단부에 출력해야할 메시지들을 모아두고 추후 유지보수를 쉽게 하기 위해서입니다. 너무 오버한 걸까요? ㅠㅠ

2020-03-03 11:18 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
> +	}
readLottoNumber에서 Lotto를 직접 생성하지 않고 LottoMachine.pickDedicatedNumbers()를 사용하도록 리팩토링 했습니다. 만들어 놓고 테스트 코드에서밖에 사용을 안하고 있었네요ㅎㅎ;;

2020-03-03 11:30 UTC, hotheadfactory commented on src/main/java/lotto/domain/Lotto.java
> +	public WinningPrize findLottoPrize(WinningLotto winningLotto) {
반환형이 `WinningPrize`이기 때문에 match를 활용한 이름 대신 `findLottoPrize`로 명명했습니다!

2020-03-03 11:30 UTC, hotheadfactory commented on src/main/java/lotto/view/OutputView.java
> +			System.out.println(lotto.toString());
👍

2020-03-03 11:31 UTC, hotheadfactory commented on src/test/java/lotto/domain/LottoMachineTest.java
> +		assertThat(lottoMachine.makeRandomLottos(6).size()).isEqualTo(6);
✔️ 해결했습니다!

2020-03-03 11:31 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoCount.java
> +	public int getTotalLottoCount() {
✔️ 해결했습니다!

2020-03-03 11:31 UTC, hotheadfactory commented on src/main/java/lotto/utils/InputUtil.java
> +	public static final String INPUT_WINNING_NUMBER = "지난 주 당첨 번호를 입력해 주세요.";
✔️ 해결했습니다!

2020-03-03 11:35 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoMachine.java
> +	public List<LottoNumber> pickDedicatedBalls(List<Integer> LottoNumbers) {
최대한 일급컬렉션을 반환하도록 수정했습니다!! 
다만, `makeRandomLottos()`는 직전에 입력받은 수동 로또 리스트에 `addAll()` 하고 나서 최종적으로 `Lottos`로 포장하는 절차 중에 있기 때문에 List<Lotto>를 반환하도록 하였습니다.

2020-03-03 11:36 UTC, hotheadfactory commented on src/main/java/lotto/dto/LottoDtos.java
>  	public List<LottoDto> getLottoDtos() {
반영했습니다 :)

2020-03-03 11:48 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoCount.java
> +			throw new LottoCountException(NOT_ENOUGH_MONEY);
모든 상수를 다 확인해보진 못했지만 대부분의 상수가 한번만 사용되더군요. 그렇다면 printXX내의 문자열을 직접 고치는 것과 상수의 문자열을 고치는 것의 유지보수 비용에 큰 차이가 존재 할 것 같지 않습니다.

상단부에 출력을 모아 관리하고자 했는데 어떻게 보면 지나친 상수 변수를 만든건 아닐지 생각해볼 수 있다고 생각해요. 변수가 늘어났다는 것은 유지보수 해줘야 할 코드도 더 늘어났다는게 되거든요 😉 

잠시 좋은 글이 없나 찾아보다 보니 옛날에 비슷한 고민을 하신분을 보게 됐네요.
https://kldp.org/node/124632
답변에 마음에 드는 부분이 있네요 `목적에 충실하게 간결하게` 👍

2020-03-04 09:33 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
> +	}
InputUtil 자체의 이름을 InputView로 바꾸고 View 패키지로 옮기라는 말씀이신가요?

2020-03-04 09:34 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
>  	}
그럼 현 상태 그대로 유지하는 쪽으로 하겠습니다 :)

2020-03-04 09:36 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
>  		OutputView.printLottos(lottos.makeLottoDtos());
좀더 많은 고민이 필요하겠네요 ㅜㅜ toString() 대신 unmodifiableList를 사용하도록 수정해보겠습니다!

2020-03-04 09:54 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
>  		OutputView.printLottos(lottos.makeLottoDtos());
Lotto나 LottoNumber의 숫자 정보를 굳이 다른 도메인이나 컨트롤러에게 노출할 필요가 없고, 단지 출력만 하면 되므로 이 둘의 toString()은 유지하고, LottosDto의 사용하지 않는 toString() 만 지웠습니다.

> OutputView가 지금과 같이 자바 환경이 아니라면 오버라이딩 된 toString이 실행 될 수 있을까요?(예를 들면 js환경이라면?) 또한 toString으로 출력하는게 데이터를 전달 받은 걸로 볼 수 있을까요?

이 부분에 대해서 생각을 해봤는데, 뷰에서 도메인을 import하지 않는 쪽으로 리팩토링해 보겠습니다.

2020-03-04 15:15 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoController.java
>  		OutputView.printLottos(lottos.makeLottoDtos());
코멘트 확인하고서 답변드립니다.(진행중인 코드 확인X) 이전 답변에 부족했던 부분이 있었네요. 그것도 중요한.. 😭 
toString 부분은 pr 당시 코드로 보면 stream을 사용하는 등 객체 자신을 문자열로 바꾸는 단순한 형태가 아닌 일정 수준의 로직이 들어가 있는 상태라 자바 구현에 많이 얽매여 있었습니다. 그러다보니 자바 외 환경을 얘기 드렸던 겁니다. 정작 중요한 얘기를 빠트렸었네요. 😰 
LottoDto :
```java
    @Override
    public String toString() {
        return lottoNumbers.stream()
                .map(LottoNumber::toString)
                .collect(Collectors.toList())
                .toString();
    }
```

특정한 로직이 들어가지 않았다면 toString을 그대로 사용하는 방향가셔도 됩니다. 도리어 import하지 않는 방향으로 가면 많이 복잡해질 걸로 보입니다. (OupView에서  단순 반복문까지도 사용하셔도 됩니다.)

사실 Stream을 사용하지 않고 아래와 같이 바꾸면 아주 간단하게 해결이 된답니다.
```java
    @Override
    public String toString() {
        return lottoNumbers.toString();
    }
```

2020-03-04 15:24 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoController.java
> +	}
넵, 이 부분은 한번 옮기고 어떨지 보고자 함도 있습니다. Input에 대한 코드가 양쪽에 나오면서 복잡해 보이는 것도 있어서 한곳으로 모아보는게 좋을 것 같아서 제안드렸습니다.

2020-03-04 17:06 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
>  		OutputView.printLottos(lottos.makeLottoDtos());
`lottoNumbers`의 자료형은 `List<LottoNumber>` 로 한번 포장된 상태이기 때문에 toString()을 저렇게 풀어서 넣어주지 않으면 로또숫자가 아닌`LottoNumber` 객체의 주소값이 나온다고 생각하고 있었습니다. 
그런데 `LottoNumber`의 toString()을 구현해서 그런가 아래 코드로 바꿔도 잘 나오네요! 훨씬 깔끔해졌습니다! 감사합니다.

2020-03-05 19:40 UTC, Hue9010 approved these changes
피드백 잘 반영해주셨네요~!! 👍 
이번 단계는 여기서 마무리하도록 할게요.
몇가지 문의사항 남겨드렸는데 확인 부탁드려요! 🙇

2020-03-05 19:40 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoMachine.java
>  public class LottoMachine {
싱글톤 생성시 고민해 볼만한 사항들 추가드립니다.
https://javaplant.tistory.com/21

여기서 질문! 이번에는 static class로 만들어도 충분하지 않았을까요?

2020-03-05 19:40 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +	}
컨트롤러에 있는게 좀더 맞겠지만 컨트롤러가 너무 복잡해지고 있는 느낌이라 정상적인 입력값이 들어오는 것에 대한 것까지 Input에서 담당하면 어떨까해서 옮겨보는걸 제안드렸던 부분입니다.
이 부분은 히로도 어떻게 생각하는지 궁금하네요.

2020-03-05 19:40 UTC, Hue9010 commented on src/main/java/lotto/domain/Lottos.java
> +	public LottosDto makeLottosDto() {
toDto라는 이름도 많이 쓰인답니다.
마찬가지로 Lotto도 makeLottoDto가 아니라 toDto로 쓸수 있겠죠! 👍
거꾸로 XXDto에서 XX를 받아 Dto로 변환하는 경우는 from을 사용하기도 한답니다.
ex) LottosDto lottosDto = LottosDto.from(lottos);

2020-03-05 19:40 UTC, Hue9010 commented on src/main/java/lotto/domain/Lottos.java
> +	public LottosDto makeLottosDto() {
DTO를 사용해보고 어떠셨는지 궁금해요.
사실 저같은 경우도 https://www.slipp.net/questions/22 이 글에 있는 포비처럼 dto가 필요한 경우가 아니면 잘 안쓰는 편입니다.
getter를 사용안하기 위해서 dto <-> domain의 변환과정이 도리어 더 번거롭고 관리해야 할 대상도 많아지기도 해서요. 그래서 주로 request/response에서 사용하고 그외에는 dto가 필요해지는 시점에서야 사용을 하는 편입니다.

위 글의 경우 예전글이라 포비의 생각도 바뀌셨을 수는 있을 겁니다. 😺

2020-03-05 19:40 UTC, merged

2020-03-06 03:56 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoMachine.java
>  public class LottoMachine {
LottoNumber 객체 45개를 만들어야 하기 때문에 생성자가 필요하다고 생각했습니다.(물론 초기화 메소드를 만들 수도 있겠지만요)
'static 초기화'라는 기능이 있다는 건 처음 알았습니다. 이걸 이용했어도 됐겠네요...

2020-03-06 03:57 UTC, hotheadfactory commented on src/main/java/lotto/view/InputView.java
> +	}
Input이 도메인 종속적으로 되는걸 원치 않아서 정상 입력값인지만 확인하고 넘기게 했습니다.
컨트롤러가 복잡한데 대해서는 클래스 분리를 더 하거나 하는 쪽으로 해결해 보겠습니다.

2020-03-06 04:10 UTC, hotheadfactory commented on src/main/java/lotto/domain/Lottos.java
> +	public LottosDto makeLottosDto() {
그냥 unmodifiableList 걸고 getter를 쓸걸... 하는 생각이 많이 들긴 했어요.
다음부턴 포비 말씀대로 DTO에서 데이터 가공이 필요한 경우에만 쓰는 게 더 적절할 것 같습니다.

2020-03-07 09:35 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoMachine.java
>  public class LottoMachine {
덕분에 싱글톤을 공부해 보셨으니 충분히 성공적인 학습이였다고 생각돼요. 👍
그래서 약간의 의문을 가지긴 했지만 가만 있었습니다. 😉

2020-03-07 09:44 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +	}
사실 인풋 관련 고려를 해야 할 것들이 꽤나 있는데 그것들을 세세하게 챙기면 과제의 규모에 비해 인풋 처리에 대한 비율이 높아져서 생기는 부분이라고 생각해요. 약간은 인풋에 대한 처리는 최소한의 처리로 비중을 낮추는 방향으로 생각했는데 확실히 MVC 패턴을 고려했을 때는 히로의 방향이 맞는 방향이라고 생각합니다. 👍

2020-03-07 09:52 UTC, Hue9010 commented on src/main/java/lotto/domain/Lottos.java
> +	public LottosDto makeLottosDto() {
해당 링크에 포비가 작성한 위키의 글에 나오는 `과거의 악몽이 되살아 난다고 치를 떠는 개발자`가 느낀 감정의 일부를 느껴보신 것 같네요. 😄 
지금 같은 경우는 getter를 안쓰기 위한 방법으로 dto를 활용해서 배보다 배꼽이 더 커진 상황으로 보여요.