[1단계 - 로또 구현]수리(이다원) 미션 제출합니다.
woowacourse/java-lotto pull request #235
Opened 2021-02-18 07:59 UTC by DWL5

안녕하세요. 닉! 이번에 리뷰 요청을 하게 된 수리 입니다.
로또 구현 1단계 리뷰 요청 드려요~

이번 미션에서는 아래와 같은 내용을 신경 쓰면서 구현해보았어요

1. 스트림에 익숙해지기
2. 모든 원시값과 문자열을 포장하기
3. 일급콜렉션 쓰기
4. 객체지향적으로 생각하기!
5. enum 사용해보기

감사합니다.

2021-02-20 00:40 UTC, wbluke requested changes
안녕하세요 수리! 로또 미션 리뷰를 맡은 닉입니다 🙇 
1단계 요구사항을 잘 구현해주셨네요 ㅎㅎ
몇 가지 코멘트 남겼으니, 확인해보시고 재요청 부탁드려요! 🙂

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/view/InputViewMessages.java
> +    private final String message;
오 안내 메시지를 enum으로 관리하고 있군요! 👍 
메시지를 한 공간에서 관리하는 시도는 좋다고 생각하지만, 애플리케이션의 사이즈가 많이 커졌을 경우 관리하기 어려울 수 있다는 점을 고려해보시는게 좋습니다 ㅎㅎ (저는 웬만하면 각 객체에서 메시지를 관리하려고 해요)

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
static method로만 이루어진 클래스에는 private 기본 생성자를 명시하여 방어적인 코드를 작성하는 습관을 들이면 좋습니다 :)

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
> +        String[] splitLottoNumbersInput = lottoNumbersInput.replace(" ", "").split(",");
안내 메시지를 상수로 관리하는 부분보다 구분자를 상수로 관리하는 부분이 더 중요하다고 생각해요 :)

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/utils/Config.java
> +    public static final int PRICE_EACH_LOTTO = 1000;
이 상수들은 각각 충분히 특정 객체에서 관리될 수 있을 것 같아요 :)

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +        Money money = new Money(InputView.getMoney());
대부분의 숫자 객체들이 InputView에서 String 값을 받아서 타입 변환의 책임까지 담당하고 있는데요, 
InputView에서 타입 보장을 해줄 수 있지 않을까요? :)
새로운 객체가 생길 때마다 항상 타입에 대한 부담을 안고 가야할 것 같아요 ㅎㅎ

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
> +    public static List<LottoNumber> getLottoLine() {
Domain이 변경되면 View도 같이 변경되는 구조인데요, domain 객체의 생성은 다른 부분에서 해보면 어떨까요? :)

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +        LottoLine lottoLine = new LottoLine(InputView.getLottoLine());
사용자가 구입한 LottoLine과 1등 LottoLine의 차이가 없어보이네요. (이름이나 설계 구조 상)
명시적으로 바꿔볼 수 있을까요? :)

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +        LottoNumber bonusLottoNumber = new LottoNumber(InputView.getBonusLottoNumber());
우승 로또와 보너스볼은 하나의 객체로 묶을 수 있을 것 같아요. 그렇게 되면 설계가 어떤 식으로 변경될까요? :)

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoTicket.java
> +                    .matchLottoNumbers(lottoLine.getValues(), bonusNumber, answerLottoNumbers));
줄바꿈을 하고 있는 이유가 있을까요? :)
```suggestion
    public List<Rank> matchLottoLines(List<LottoNumber> answerLottoNumbers, LottoNumber bonusNumber) {
        List<Rank> ranks = new ArrayList<>();
        for (LottoLine lottoLine : lottoLines) {
            ranks.add(lottoLine.matchLottoNumbers(lottoLine.getValues(), bonusNumber, answerLottoNumbers));
```

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoTicketFactory.java
> +public class LottoTicketFactory {
Factory는 보통 정적 클래스가 아니라 전역적으로 하나만 생성해서 특정 객체를 특별한 생성 방식으로 만들고 싶을 때 사용하는 패턴입니다 :)

2021-02-20 00:40 UTC, wbluke commented on src/main/java/lotto/domain/Rank.java
> +    public static Rank check(int matchCount, boolean hasBonusNumber) {
`check`는 보통 boolean을 반환하는 메서드에서 사용합니다 :)

2021-02-21 14:53 UTC, DWL5 commented on src/main/java/lotto/utils/Config.java
> +    public static final int PRICE_EACH_LOTTO = 1000;
넵! 한가지 질문은 START = 1, END = 45 의 경우에는 쓰이는 곳이 2군데 인데, 해당 경우에도 각 객체에서 관리하는 것이 더 좋을까요?

Config로 분리한 이유가 이런 중복을 없애기 위함이었습니다!!

2021-02-21 15:05 UTC, DWL5 commented on src/main/java/lotto/controller/LottoController.java
> +        Money money = new Money(InputView.getMoney());
밑에 코멘트 달아주신 "Domain이 변경되면 View도 같이 변경되는 구조인데요, domain 객체의 생성은 다른 부분에서 해보면 어떨까요? :)" 해당 리뷰와 헷갈립니다 ㅜ

저는 해당 리뷰가 InputView에서 Money객체를 만들어서 전달하는 것이 더 좋다는 의미로 이해가 되는데.. 또 아래 리뷰에서는 domain객체 생성은 또 다른 부분에서 하라고 되어 있어서 혹시 조금 더 설명 부탁 드려도 될까요???

2021-02-21 18:21 UTC, DWL5 commented on src/main/java/lotto/domain/lotto/LottoTicketFactory.java
> +public class LottoTicketFactory {
넵 LottoTicket를 발행하는 책임을 가진 클래스로 사용을 했었는데 이름이 조금 헷갈리게 되어 있었네요! 해당 클래스의 이름을 RandomLottoGenerator로 변경하였습니다.

2021-02-21 18:22 UTC, DWL5 commented on src/main/java/lotto/domain/lotto/LottoTicket.java
> +                    .matchLottoNumbers(lottoLine.getValues(), bonusNumber, answerLottoNumbers));
별다른 이유는 없습니다 ㅜ 컨벤션 실수 였던것 같습니다

2021-02-21 18:23 UTC, DWL5 commented on src/main/java/lotto/controller/LottoController.java
> +        LottoNumber bonusLottoNumber = new LottoNumber(InputView.getBonusLottoNumber());
WinningNumbers 객체를 생성하여 당첨번호에 관한 처리를 담당하도록 하였습니다.

2021-02-21 18:27 UTC, DWL5 commented on src/main/java/lotto/domain/Rank.java
> +    public static Rank check(int matchCount, boolean hasBonusNumber) {
matchRank로 함수 명 수정 하였습니다.

2021-02-22 02:22 UTC, wbluke requested changes
안녕하세요 수리! 피드백 반영 잘 해주셨네요 👍 
아직 조금 더 수정해야 할 부분들이 많이 보여서 코멘트 남겼는데요!
객체지향 설계에 대한 부분, getter 사용에 대한 부분을 위주로 피드백 남겼어요ㅎㅎ
다음 단계로 가기 위한 초석이니 수정 후 재요청 부탁드려요 🙂

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +        Money money = new Money(InputView.getMoney());
아 네네! 제가 말씀드린건 기본적인 String, int 등의 타입까지만 InputView에서 보장해주고,
도메인 객체의 생성은 Controller에서 담당하면 어떨까 하는 의미였습니다 :)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +    private static final int END = 45;
> 넵! 한가지 질문은 각 상수마다 쓰이는 곳이 2군데 인데, 해당 경우에도 각 객체에서 관리하는 것이 더 좋을까요?
Config로 분리한 이유가 이런 중복을 없애기 위함이었습니다!! 이렇게 같은 상수의 중복이 많이 일어난다면 설계에 문제가 있다고도 볼 수 있을까요?

아뇨 설계에 문제가 있다는건 아니고, LottoNumber의 상수를 다른 곳에서 사용해야한다면 접근제어자를 열어주면 될 것 같네요 :)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +    private static final int END = 45;
추가적으로 상수의 이름을 조금 더 구체적으로 지어보면 좋겠네요ㅎㅎ
`LottoNumber.START` 가 자연스러운지, 어떤 의미의 상수인지 쉽게 알아볼 수 있을까 한번 고민해주세요! :)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +        return winningNumbers;
```suggestion
        return new WinningNumbers(lottoLine, bonusLottoNumber);
```

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/domain/lotto/WinningNumbers.java
> +        if (lottoNumbers.getValues().contains(bonusNumber)) {
- 객체지향 생활체조 규칙9. `getter 사용을 지양하라`

메시지를 보내서 해결하면 어떨까요? :)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoTicketGenerator.java
> +public class LottoTicketGenerator {
> Factory는 보통 정적 클래스가 아니라 전역적으로 하나만 생성해서 특정 객체를 특별한 생성 방식으로 만들고 싶을 때 사용하는 패턴입니다 :) 

> 넵 LottoTicket를 발행하는 책임을 가진 클래스로 사용을 했었는데 이름이 조금 헷갈리게 되어 있었네요! 해당 클래스의 이름을 RandomLottoGenerator로 변경하였습니다.

아, 이름을 변경하라는 의미보다는 인스턴스를 전역적으로 하나만 생성해서 사용하면 어떨까? 하는 의도였어요 ㅎㅎ
정적 클래스는 객체지향 설계에서 안티패턴이긴 하거든요. (상태를 가지고 있지 않은 클래스)
저도 꼭 필요한 유틸 클래스 외에는 정적 클래스를 최대한 지양하고 있습니다. 참고해서 수정해보면 좋겠네요 :)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +        LottoLine lottoLine = new LottoLine(getLottoLine(InputView.getLottoLine()));
라인 수를 줄이기 위해 이처럼 중첩해서 작성하는 부분이 많은데요ㅎㅎ
가독성이 조금 떨어지는 듯 해서, 적절히 선언하면서 step by step으로 작성하는게 좋아보입니다 :)
추가로 getLottoLine인데 실제로는 `List<LottoNumber>`를 반환하고 있는데요, `LottoLine을 get해서 다시 LottoLine 생성자에 넣는` 그림이라 어색한 것 같네요 :)
(getLottoLine에서 바로 LottoLine 생성까지 해줘도 되겠네요)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +    private LottoResult checkLottoTicket(LottoTicket lottoTicket, WinningNumbers winningNumbers) {
여기도 `check`로 시작하는 메서드가 있네요 :)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoLine.java
> +        return Rank.matchRank(matchCount, hasBonusNumber);
getter로 모든 데이터를 다 꺼내서 가공하고 있는데요, WinningNumbers를 만든 이유를 잘 살려서 다시 고민해보면 좋겠어요 ㅎㅎ
가장 좋은 방법은 **getter가 없다고 생각하고** 구현해보는겁니다!
getter가 없기 때문에 객체에 메시지를 보내서 구현할 수밖에 없기 때문이죠 :)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoLine.java
> +        return Rank.matchRank(matchCount, hasBonusNumber);
추가적으로 위에 LottoLine 생성자에서도 매직 넘버와 빠뜨린 제네릭 선언이 보이는데요, 같이 수정 부탁드려요 :)

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoLine.java
> +        int matchCount = (int) lottoNumbers.stream().filter(winningLottoNumbers::contains).count();
```suggestion
        int matchCount = (int) lottoNumbers.stream()
                .filter(winningLottoNumbers::contains)
                .count();
```

stream 구문은 한줄에 하나씩 쓰는 것이 좋습니다 :) 다른 곳도 같이 체크해주세요

2021-02-22 02:22 UTC, wbluke commented on src/main/java/lotto/domain/lotto/WinningNumbers.java
> +            throw new IllegalArgumentException(ERROR_BONUS_LOTTO_NUMBER_DUPLICATED.getMessage());
메시지를 enum으로 관리하면 항상 해당 enum을 참조하고 getter로 꺼내와야 하는 그림이라, 메시지는 각 담당 객체에서 관리하도록 하면 어떨까요? :)

2021-02-22 12:08 UTC, DWL5 commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +    private static final int END = 45;
해당 상수들은 lotto package안에서만 사용할 듯하여 protected로 설정하였습니다!

LOTTO_START_NUMBER /  LOTTO_FINAL_NUMBER 로 변경하였습니다!

2021-02-22 12:09 UTC, DWL5 commented on src/main/java/lotto/domain/lotto/WinningNumbers.java
> +        if (lottoNumbers.getValues().contains(bonusNumber)) {
WinningLotto에 관련 데이터들이 있으니 여기로 메시지를 보내 해결하는 것 더 좋았겠네요!
수정했습니답

2021-02-22 12:10 UTC, DWL5 commented on src/main/java/lotto/domain/lotto/LottoTicketGenerator.java
> +public class LottoTicketGenerator {
네 Singleton 패턴을 적용하여 전역으로 인스턴스 하나만 사용하도록 수정하였습니다.

Singleton 패턴 생성방법에도 여러가지가 있던데 이것은 조금 더 공부를 해보아야 겠어요!

2021-02-22 12:10 UTC, DWL5 commented on src/main/java/lotto/domain/lotto/WinningNumbers.java
> +            throw new IllegalArgumentException(ERROR_BONUS_LOTTO_NUMBER_DUPLICATED.getMessage());
543fa0e 여기에 반영하였습니다!

2021-02-22 12:11 UTC, DWL5 commented on src/main/java/lotto/domain/lotto/LottoLine.java
> +        int matchCount = (int) lottoNumbers.stream().filter(winningLottoNumbers::contains).count();
b45725c 여기에 반영하였습니다!

2021-02-22 12:11 UTC, DWL5 commented on src/main/java/lotto/controller/LottoController.java
> +    private LottoResult checkLottoTicket(LottoTicket lottoTicket, WinningNumbers winningNumbers) {
682c688 여기에 반영하였습니다!

2021-02-22 12:13 UTC, DWL5 commented on src/main/java/lotto/domain/lotto/LottoLine.java
> +        return Rank.matchRank(matchCount, hasBonusNumber);
WinningNumbers에 Rank를 반환 할 수 있도록 구현을 변경하였습니다. 
LottoLine에서도 자기가 가지고 있는 데이터를 이용하면 되는데, List<LottoNumber>를 받아서 처리하는 부분을 제거 하였습니다!

2021-02-22 12:14 UTC, DWL5 commented on src/main/java/lotto/controller/LottoController.java
> +        LottoLine lottoLine = new LottoLine(getLottoLine(InputView.getLottoLine()));
fe7f7877d5b9b8a41de8e85f278d5170f43dbd01 여기에 반영하였습니다!

2021-02-22 12:15 UTC, DWL5 commented on src/main/java/lotto/controller/LottoController.java
> +        return winningNumbers;
fe7f7877d5b9b8a41de8e85f278d5170f43dbd01 여기에 반영하였습니다!

2021-02-23 02:38 UTC, wbluke approved these changes
피드백 반영 감사합니다 👍 
훨씬 깔끔해진 것 같아요 ㅎㅎㅎ
다음 단계 진행해주세요! 🙂

2021-02-23 02:38 UTC, wbluke commented on src/main/java/lotto/domain/lotto/LottoTicketGenerator.java
> +    }
단순히 Controller에서 하나 만들어서 사용하는걸 말씀드린거였는데, 싱글턴까지 적용하셨군요 👍

2021-02-23 02:38 UTC, merged

2021-02-25 17:46 UTC, DWL5 commented
# 수리의 학습로그🐣

[로또 1단계 - 자동] 과제를 수행하면서 공부했던 점을 남겨봅니다.



# 자바 스트림 - 3

- ```List<LottoNumber>```를 어떻게 정렬 된``` List<String>```으로 바꾸지?

  ```java
  for (LottoLine line : lottoTicket.getLottoLines()) {
              List<String> lottoNumbers = line.getValue().stream()
                      .sorted()
                      .map(lottoNumber -> String.valueOf(lottoNumber.getValue()))
                      .collect(Collectors.toList());
              System.out.println("[" + String.join(",", lottoNumbers) + "]");
          }
  ```



- 스트림에 대한 내용은 크게 3가지로 나눠 진다.
  - 생성하기 : 스트림 인스턴스 생성
  - 가공하기 : 필터링 및 맵핑 등 원하는 결과를 만들어가는 중간 작업
  - 결과 만들기 : 최종적으로 결과를 만들어내는 작업



- 위의 내가 사용했던 코드는 어떻게 동작하는 걸까?

  - 생성하기 - ```List<LottoNumber>```를 받아와서 컬렉션 스트림을 사용하여 스트림을 만든다.

    ```
    line.getValue().stream()
    ```

  - 가공하기 - 전체 요소 중에서 내가 원하는 것만 뽑아낼 수가 있다. 이러한 작업은 스트림을 리턴하기 때문에 여러 작업을 이어 붙여서 작성가능 하다.

    ```
    .sorted()
    .map(lottoNumber -> String.valueOf(lottoNumber.getValue()))
    ```

    - filter

      - 스트림 내 요소들을 하나씩 평가해서 걸러내는 작업

        ```java
        Stream<String> stream = names.stream()
        	.filter(name -> name.contains("a"));
        ```

      - 스트림의 각 요소에 대해서 평가식을 실행하게 되고 'a'가 들어간 이름에 대한 스트림이 리턴

    - map

      - 스트림 내 요소들을 하나씩 특정 값으로 변환해준다. 스트림에 들어가 있는 값이 input이 되어서 특정 로직을 거친 후 output이 되어 리턴 되는 새로운 스트림에 담긴다.
      - 위의 예제에서는 LottoNumber의 value값(int)를 가져와 String으로 변환하는 작업을 하였다.

    - sorted

      - 정렬 할 때 사용

    - peek

      - 결과에 영향을 미치지 않는다. 작업을 처리하는 중간중간 결과를 확인 해 볼때 사용 한다.

        ```java
        int sum = IntStream.of(1, 3, 5, 7, 9)
          .peek(System.out::println)
          .sum();
        ```

  - 결과 만들기

    - count(), sum(), min(), max(), average()등의 API 제공
    - reduce
    - collect
    - reduce와 collect는 관련 링크 참조

  ## 링크

  - https://futurecreator.github.io/2018/08/26/java-8-streams/





# ENUM - 4

- java에서 Enum은 완전한 기능을 갖춘 클래스

- 이번 로또 과제에서는 Rank를 관리하는데 쓰였다.

  ```java
  FIRST(6, 2_000_000_000),
  SECOND(5, 30_000_000),
  THIRD(5, 1_500_000),
  FOURTH(4, 50_000),
  FIFTH(3, 5_000),
  NO_MATCH(0, 0);
  ```

- Rank와 matchCount, money를 연결 시켰다. 이를 하기 위해선 생성자를 정의 해 주어야 한다.

  ```
  Rank(int matchCount, int money) {
          this.matchCount = matchCount;
          this.money = money;
      }
  ```



## 링크

- https://velog.io/@kyle/%EC%9E%90%EB%B0%94-Enum-%EA%B8%B0%EB%B3%B8-%EB%B0%8F-%ED%99%9C%EC%9A%A9
- https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html



# 싱글톤 생성방법 - 3

- 싱글톤 이란?
  - 어떤 클래스가 최초 한번만 메모리를 할당하고(static) 그 메모리에 객체를 만들어 사용하는 디자인 패턴
- 싱글톤을 사용하는 이유
  - 한번의 객체 생성으로 재 사용이 가능하기 때문에 메모리 낭비 방지 가능하다. 싱글톤으로 생성된 객체는 무조건 한번 생성으로 전역성을 띄기에 다른 객체와 공유가 용이하다.
- 싱글톤의 문제점
  - 싱글톤으로 만든 객체의 역할이 간단한 것이 아닌 역할이 복잡한 경우라면 해당 싱글톤 객체를 사용하는 다른 객체간의 결함도가 높아져서 객체지향 설계 원칙에 어긋나게 된다. (개방-폐쇄)
    - 개방폐쇄 원칙 - 객체의 확장에 대해서는 개방적이고, 수정에 대해서는 폐쇄적이어야 한다.
  - 싱글톤 객체를 수정할 경우 싱글톤 객체를 사용하는 곳에서 사이드 이팩트 발생 확률이 생기게되며, 멀티 쓰레드 환경에서 동기화 처리 문제등이 생길 수 있다.

- 내가 구현한 방법 - lazy init

  ```java
  private static LottoTicketGenerator instance;
  private LottoTicketGenerator() {
          randomLottoGenerator = new RandomLottoGenerator();
      }
  
      public static LottoTicketGenerator getInstance() {
          if (instance == null) {
              instance = new LottoTicketGenerator();
          }
  
          return instance;
      }
  
  ```

- 해당 방법은 쓰레드가 동시에 getInstance() 메서드를 호출하게 되면 인스턴스가 두 번 생성되는 문제가 발생 있다.

- getInstnace()에 synchronized 키워드를 사용하는 방법도 있지만 해당 방법은 성능저하를 발생 시킨다고 한다.

- 대표적인 방법 Holder 사용

  ```java
  public class Singleton {
  	private String name;
  	
  	private Singleton(String name) {
  		this.name = name;
  	}
  	
  	public static Singleton getInstance() {
  		return LazyHolder.INSTANCE;
  	}
  	
  	private static class LazyHolder {
  		private static final Singleton INSTANCE = new Singleton("unique");  
  	}
  	
  	public String getName() {
  		return name;
  	}
  }	
  
  ```

  - Singleton 클래스는 LazyHolder 클래스의 변수가 존재하지 않기 때문에 로더가 Singleton 클래스를 로드 하더라도 LazyHolder를 초기화 하지 않는다.
  - 이후 getInstance()를 호출하는 순간 LazyHolder 클래스를 참조하여 해당 클래스를 로딩 하게 되고 초기화를 진행한다. Class를 로딩하고 초기화하는 시점은 Thread-safe를 보장한다.