[1단계 - 로또 구현] 파피(김태완) 미션 제출합니다.
woowacourse/java-lotto pull request #236
Opened 2021-02-18 08:06 UTC by TaewanKimmmm

안녕하세요, 닉! 파피라고 합니다. 잘 부탁드립니다!

미션 진행 중 가장 궁금했던 점은 뷰에서 도메인을 어느 정도까지 의존해도 되는가?입니다.

아래 코드를 보시면 
InputView에서 구입금액을 입력받고, 예외 검증 후 int 타입으로 리턴하는 것이 아니라 
UserPurchase라는 객체를 만들어서 리턴하는 방식으로 했는데요.

```java
public class InputView {
    private static final Scanner scanner = new Scanner(System.in);
    private static final String NUMERIC_REGULAR_EXPRESSION = "\\d+";
    public static final String LOTTO_NUMBER_DELIMITER = ", ";

    private InputView() {
    }

    public static UserPurchase getUserPurchase() {
        InputPrinter.printPurchasePriceInputGuideMessage();
        String purchasePriceInput = scanner.nextLine();
        int purchasePrice = validateNaturalNumber(purchasePriceInput);
        return new UserPurchase(purchasePrice);
    }
```

> '뷰에서 객체를 만든다는 것은 엄밀히 따지면 책임 분리가 제대로 되지 않은 것이지 않을까?' 

라는 생각과,

> '뷰에서는 입력에 대한 최소한의 검증을 하고, 비즈니스 룰에 대한 검증은 도메인 객체가 생성자에서 맡고 있으니 각자의 책임은 명확할 것이다!'

라는 생각이 싸우고 있네요..뭐가 맞는 걸까요?

소중한 시간 내어 주셔서 감사합니다 😀

2021-02-18 10:56 UTC, TaewanKimmmm commented
# 학습 로그
------
# [설계] 요구사항 분석 - 3
## 내용
- 요구사항 분석 문서를 기반으로 객체 추출하는 것이 수월함을 느꼈다.

# [설계] 클래스 다이어그램 - 5
## 내용
- 추출한 객체를 토대로 객체가 가지고 있어야 할 필드와 메소드를 정의하면서 클래스 다이어그램을 그렸다.
- 시간이 꽤 걸렸지만 코드 구현에 들어갈 때 막막함과 부담이 덜어졌다는 것을 느꼈다.
- 가독성 문제와 시간 소요 문제는 간소화시키면서 해결할 수 있을 것 같다.
## 링크
- https://imgur.com/2zMbWpu

# [TDD] 테스트 주도 개발 - 4
## 내용
- 기존에 프로그램을 실행시키면서 System.out.println , 디버깅 등에 의존했던 방식과 달리 
TDD 방식을 사용하면서 여러 장점을 느낄 수 있었다.
- 단위별 기능 테스트를 진행할 수 있음
- 특정 기능을 변경한 후 전체 테스트 코드 실행으로 빠르게 전체 실행 결과에 미치는 영향이 있는지 확인할 수 있음 
구현물에 확신을 가질 수 있음

# [OOP] - 원시값 포장 - 2
## 내용
- 포장을 함으로써 예외 검증 책임을 분리할 수 있으며 객체를 믿고 쓸 수 있음을 몸소 느꼈다.
## 링크
- https://github.com/woowacourse/java-lotto/commit/b65a7ee39bfae5ae99335161fc2da9447a169087

# [OOP] - 일급 컬렉션과 불변 객체 - 2
## 내용
- 리스트를 포장하면서 일급 컬렉션을 만들고 관련 행위들도 구현했다.
- 방어적 복사와 unmodifiableList를 사용하여 불변 객체화도 진행했다.
- 역시 믿고 쓸 수 있다는 장점을 느꼈다.
## 링크
- https://github.com/woowacourse/java-lotto/pull/236/commits/7696761a60bb511f3f95dfb6c9e8879e1c3ec860
- https://velog.io/@rito/%EB%B6%88%EB%B3%80-%EA%B0%9D%EC%B2%B4Immutable-Object

2021-02-20 00:10 UTC, wbluke requested changes
안녕하세요 파피! 로또 미션 리뷰를 맡은 닉입니다 🙇 
코드가 많이 깔끔하네요! 잘 구현해주셨습니다 ㅎㅎ
가끔씩 객체에 있는 정보를 직접 꺼내서 작업하는 부분들이 보이는데요, 코멘트와 함께 전체적으로 점검해보면 좋을 것 같아요!
수정 후 재요청 부탁드려요! 🙂

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
> +    private static void validateAllNaturalNumbers(String winningNumbersInput) {
> validate 함수 네이밍, 어떻게 할 것인가?
예외를 던지는 함수의 이름을 어떻게 짓는 게 바람직한 것인지 헷갈립니다.
> 
> 저는 validate 뒤에 is를 넣고 조건을 붙이는 방식을 선호했고, 페어는 명사형을 선호했어요.
> 
> 입력이 자연수여야 하는 조건을 검증한다면
> 
> `validateIsNaturalNumber`
> `validateAllNaturalNumbers`
> 어떤 게 더 적합할까요?

저는 validate가 동사여서 지금의 네이밍이 좀 더 자연스러워보여요 :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/LottoTicket.java
> +        lottoNumbers.sort(Comparator.comparingInt(LottoNumber::getNumber));
> Comparable vs Comparator
LottoTicket에서 티켓에 포함된 로또 숫자 객체들을 오름차순 정렬할 때 아래와 같이 구현했는데요,
> 
> `lottoNumbers.sort(Comparator.comparingInt(LottoNumber::getNumber));`
숫자를 오름차순 정렬하는 건 일반적인 정렬이기 때문에 LottoNumber에서 Comparable 인터페이스의 compareTo 메소드를 구현하는 것이 더 나을까요?

맞아요. Comparator도 (마땅히 해당 객체의 정렬 조건이 될 수 있다면) 내부로 숨길수록 더 좋은 구조가 나올 것 같아요 :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
> +    }
> `'뷰에서 객체를 만든다는 것은 엄밀히 따지면 책임 분리가 제대로 되지 않은 것이지 않을까?'`
라는 생각과,
`'뷰에서는 입력에 대한 최소한의 검증을 하고, 비즈니스 룰에 대한 검증은 도메인 객체가 생성자에서 맡고 있으니 각자의 책임은 명확할 것이다!'`
라는 생각이 싸우고 있네요..뭐가 맞는 걸까요?

저는 후자의 생각이에요.
InputView는 외부 세계(사용자 입력)로부터 받은 값에 대해 최소한의 타입만 보장해주는 역할이라 생각하구요.
나머지는 도메인 객체와 도메인 객체를 조합하는 Controller의 역할이라고 생각해요!

지금의 구조라면 Domain이 조금이라도 변경될 경우 View도 같이 변경되어야겠네요 ㅎㅎ

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/ticketgenerator/LottoMachine.java
> +    private final LottoGenerator lottoGenerator;
LottoMachine과 LottoGenerator가 큰 차이가 없다고 보여지네요.
By-Pass만 하는 역할로 보이는데 어떻게 생각하시나요? :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/ticketgenerator/LottoGenerator.java
> +    private static final int SIZE = 6;
LottoTicket에 있는 그 SIZE가 아닐까요? :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +            throw new IllegalArgumentException("로또 번호는 1이상, 45이하여야 합니다.");
예외 메시지도 상단의 상수를 사용하여 유연한 구조로 만들어보면 어떨까요? :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/LottoTicket.java
> +        return Collections.unmodifiableList(this.numbers);
일급컬렉션 방어로직 👍

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/ticketresult/WinningLottoNumbers.java
> +    private final LottoNumber bonusNumber;
Composition으로 잘 묶었네요 👍

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/ticketresult/WinningLottoNumbers.java
> +        if (winningTicket.getLottoTicketNumbers().contains(bonusNumber)) {
객체에 메시지를 던지도록 구성해보면 좋겠네요 :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
> +    }
메서드 이름은 validate 인데 실제로는 int 변환의 역할까지 담당하고 있네요.
차라리 `변환`에 포커싱을 맞추고, 변환하는 과정에서 숫자가 아닌 경우 예외를 던지는 형태가 더 자연스러운 네이밍으로 보여요 :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/type/LottoMatchType.java
> +                lottoMatchType -> lottoMatchType.getCountMatchedNumbers() == countMatchedNumbers)
이 부분도 getter를 사용하지 않고 구현해볼 수 있을까요? :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/type/LottoMatchType.java
> +    private final String matchCountMessage;
이 메시지는 View의 책임이 아닐까요? :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/ticketresult/LottoComparator.java
> +        PurchasedLottoTickets purchasedLottoTickets) {
혹시 들여쓰기를 이렇게 하는 이유가 있을까요? 
메서드마다 줄바꿈이 달라보이네요 ㅎㅎ
파라미터나 메서드 내부에서도 한줄에 표현할 수 있는 부분들을 한줄에 표현하는 것이 좋아 보여요 :)

2021-02-20 00:10 UTC, wbluke commented on src/main/java/lotto/domain/ticketresult/LottoComparator.java
> +        LottoTicket winningLottoTicket) {
이렇게 되면 실수로 두 파라미터의 순서를 바꿔서 호출했을 경우 다른 결과가 나타날 여지가 있어요. (심각하게 말하면 장애로...ㅎㅎ)
같은 타입의 여러 파라미터를 사용할 때는 항상 다른 형태로 구현할 수 없을지 고려해보면 좋습니다 :)

2021-02-22 03:37 UTC, TaewanKimmmm commented
안녕하세요, 닉! 한 가지 피드백 제외하고 모두 반영하여 코드들 수정하였습니다.

```
지금의 구조라면 Domain이 조금이라도 변경될 경우 View도 같이 변경되어야겠네요 ㅎㅎ
```
라고 하신 피드백은 어떻게 수정해야 될지 감을 못 잡겠습니다..😥

DTO 개념을 도입해야된다는 것을 말씀하신 걸까요?

2021-02-22 09:49 UTC, wbluke approved these changes
피드백 반영 꼼꼼히 잘 해주셨네요 👍 
추가 질문에 대한 답변과, getter 사용에 대한 의견 남겼어요.
다음 단계와 같이 진행 부탁드려요! 🙂

2021-02-22 09:49 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +            throw new IllegalArgumentException("로또 번호는 "+ MINIMUM + " 이상, " + MAXIMUM + " 이하여야 합니다.");
잘 수정해주셨네요 👍 
String.format()을 활용하면 더 깔끔해질 것 같아요 :)

2021-02-22 09:49 UTC, wbluke commented on src/main/java/lotto/domain/LottoTicket.java
> +        return this.numbers.contains(lottoNumber);
메서드명이 철저하게 WinningLottoNumbers에만 맞춰진 네이밍으로 보이네요 ㅎㅎ
파라미터와 반환형을 고려하여 범용적으로 다시 지어보면 좋겠네요 :)

2021-02-22 09:49 UTC, wbluke commented on src/main/java/lotto/domain/ticketgenerator/LottoGenerator.java
> +            lottoTickets.add(new LottoTicket(new ArrayList<>(allNumbers.subList(ZERO, LottoTicket.SIZE))));
한줄 안에서 하는 일이 너무 많아서, 변수나 메서드로 분리하면 좋을 것 같아요 :)

2021-02-22 09:49 UTC, wbluke commented on src/main/java/lotto/domain/ticketresult/LottoComparator.java
> +    private int getEachLottoResult(LottoTicket purchasedOneLottoTicket) {
이 메서드에서 LottoTicket의 숫자들도 꺼내고, WinningLottoTicket의 숫자들도 꺼내서 비교를 하고 있는데요, 객체에 메시지를 던져서 최대한 안쪽으로 로직을 숨길 수는 없을까요?
항상 초기 OOP 설계 및 구현을 하실 때는, **getter가 없다고 생각하고 구현**하다가 도저히 안되겠을 때 getter를 만드시는 것을 추천합니다 :)

2021-02-22 09:49 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
>      private static LottoNumber getBonusNumberInput() {
> `지금의 구조라면 Domain이 조금이라도 변경될 경우 View도 같이 변경되어야겠네요 ㅎㅎ`
라고 하신 피드백은 어떻게 수정해야 될지 감을 못 잡겠습니다..😥
> 
> DTO 개념을 도입해야된다는 것을 말씀하신 걸까요?

아 제 의도는 InputView에서 최소한의 타입 보장(String, int 등)만 제공하고, Controller 등에서 도메인 객체의 생성을 담당하는 것이 좋겠다는 것이었어요.
지금은 View가 직접적으로 LottoNumber 등의 존재에 대해서 알고 있으니 Model과 View에 의존 관계가 생겼다고 생각해요 :)

2021-02-22 09:50 UTC, merged

2021-02-22 10:10 UTC, TaewanKimmmm commented on src/main/java/lotto/view/InputView.java
>      private static LottoNumber getBonusNumberInput() {
아..! 이해 됐어요!!감사합니다😀