[1단계 - 로또 구현] 인비(김태희) 미션 제출합니다.
woowacourse/java-lotto pull request #241
Opened 2021-02-18 08:19 UTC by taehee-kim-dev

안녕하세요, 휴!! 😃 

정말 반갑습니다!!

제가 이번 미션을 하면서 고민하고 공부하고, 적용해보려고 노력한 것들을 
이번 미션부터 적용된 우아한테크코스 학습 로그 형식으로 정리해 보여드리려고 합니다!

그리고, 궁금했던 것을 질문드리고 싶어요.

<br>

# 인비의 학습로그

## [설계] 클래스 다이어그램 - 5
### 내용
- 맨 처음 설계 과정에서 페어와 함께 클래스다이어그램을 그렸다(첫 번째 링크). 
모든 세부사항, 구체적인 연관관계를 그렸다.
하지만 UML 정식 형식과 많이 달랐고, 너무 복잡해 이해하기 힘들었다.

- 페어프로그래밍을 종료하고, __\[UML 실전에서는 이것만 쓴다 / 로버트 C.마틴\]__ 책을 보았다. 
그런데 오히려 로버트 마틴은 __"세세하게 이것저것 다 적어놔봤자 알아보기만 힘들고, 
구체적인것은 코드 구현시점에 정하면 된다. 모두가 잘 이해할 수 있도록 간소화 된 형식으로 UML을 작성해야 한다."__ 
라고 했다. 
점선, 집합, 합성도 그냥 구분하지 말고, 단순히 관련 관계만 표시하라고 했다. 

- 로버트 마틴의 말을 참고해 최대한 이해하기 쉽도록 다시 UML을 그렸다(두 번째 링크). 

### 링크
- https://drive.google.com/file/d/1WDzeRYf3-g120NugP9Qva0rP8TvUbVx7/view?usp=sharing
- https://drive.google.com/file/d/1Wh35NfypyENLsiDnOUr5HSi8oWNV2pO-/view?usp=sharing

<br>

## [설계] MVC - 3
### 내용
- 핵심 비지니스 로직을 가지는 도메인 객체를 domain 패키지에, UI와 관련된 객체를 view 패키지에 구현했다.

- MVC 패턴 기반으로 view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만, 
domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현했다.
### 링크

<br>

## [TDD] 테스트 주도 개발 - 4
### 내용
- 모든 코드작성을 페어와 함께 TDD로 구현하였다.
- TDD로 진행하니 구현된 코드의 기능에 확신을 가질 수 있었다.
- 리팩토링시, 테스트코드의 위력을 느낄 수 있었다.

<br>

## [OOP] - 원시값 포장 - 2
### 내용
- 로또 번호 등 모든 원시값을 포장하였다.
- 포장된 원시값이 하나의 도메인이 되는것을 경험했다.
- 생성자에서 유효성 검사가 가능해짐을 깨달았다.
### 링크

<br>

## [OOP] - 일급 컬렉션 적용 - 2
### 내용
- 도메인을 담는 컬렉션들은 모두 일급 컬렉션으로 감싸서 최대한 캡슐화를 하고, 다양한 비즈니스 로직을 내부에 구현했다.
- 외부에서는 내부의 구현은 모른 채, 단순히 요청 메시지만 보내고 응답 메시지를 받을 수 있는 OOP를 경험할 수 있었다.
### 링크

<br>

## [JDK] - Enum - 4
### 내용
- 당첨 순위를 Enum 타입으로 처리했다.
- 각 등수를 명확히 구분하고, 관련된 메시지나 당첨 상금들을 각각 묶으니 분리와 활용이 편리했다.
- 해당 Enum 클래스와 관련된 함수들 또한 클래스 내부에 위치시켜, OOP에 맞도록 구현했다.
### 링크

<br>

## [JDK] - Stream API - 2
### 내용
- 모든 함수의 인덴트를 1로 맞추고, 가독성 좋은 코드를 작성하기 위해 Stream API를 적극 활용했다.
### 링크

<br>

## [OOP] - Domain validation - 2
### 내용
- Validation을 최대한 도메인 객체 내부의 생성자 했다.

- 아무리 생각해도 도메인 내부에 어울리지 않는 Validation 작업들은 도메인 외부의 InputView의 함수에서 했다.
### 링크

<br>

# 질문
1. 실무에서는 UML을 어떤 방식으로 그리나요? 
정식 UML 방식대로 구체적으로 그리는지, 로버트 마틴 말대로 최대한 이해하기 쉽게 그리는지 궁금합니다.
아무래도 회사마다, 팀마다 다른겠죠?
어떻게 그려야 잘 그리는 건지 궁금합니다!

1. 페어가 클래스 내의 함수들 순서가 public 함수들이 위로, private 함수들이 아래로 위치해야 한다고 배웠다는데, 
이게 맞는건가요? 
클린코드 책을 읽었을 때는 신문 읽듯이 위에서 아래로 편하게 읽혀야 한다 해서, 
저는 private, public을 신경쓰지 않고 무조건 가독성이 좋도록 순서를 위치시켰거든요. 
휴의 생각은 어떠신가요?

<br>

긴 글 읽어주셔서 감사합니다.
이번 미션동안 잘 부탁드립니다!! 🙇

2021-02-19 15:40 UTC, Hue9010 requested changes
안녕하세요 인비! 이번 리뷰를 맡은 휴입니다.
요구사항에 맞춰 잘 구현해주셨네요! 👍
몇가지 개선하면 좋을 것 같은 내용 피드백 남겼어요. 
질문에 대한 답변도 남겼는데 혹시 답변드리지 않은 부분이 있다면 말씀주세요!!! 🙏 
확인하시고 궁금한 내용은 코맨트나 DM으로 질문주세요!

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketpurchase/UserPurchase.java
> +        if (purchasePrice <= ZERO || purchasePrice % ONE_TICKET_PRICE != ZERO) {
`purchasePrice % ONE_TICKET_PRICE != ZERO`처럼 두가지 연산이 들어가면 괄호로 묶어주는게 가독성에 도움이 됩니다.

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoMain.java
> +    private static void checkLottoResult(PurchasedLottoTickets purchasedLottoTickets,
메서드 명만 보면 최종적으로 결과 확인을 할 것 같은데 당첨번호 생성까지 담당하고 있네요.
담청번호를 입력받아 생성하고, 결과를 확인하는 두가지의 책임을 가진 것 같은데 분리해주는게 좋을 것 같아요.  😉

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketgenerator/LottoMachine.java
> +public class LottoMachine {
LottoMachine과 LottoGenerator를 분리한 이유가 있을까요? 왠지 다음 단계인 수동 로또 생성을 위한 초석일까요? 🤔 
그런게 아니라면 의미를 가지게 객체를 세분화하는 것도 좋지만 단순화 시키는건 어떨까요?

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +    private static final int ONE_COUNT = 1;
ZERO나 ONE_COUNT가 매직넘버일까요?
코드상의 모든 숫자를 상수화 할 필요는 없습니다.
 ```java
    public LottoResult(WinningLottoNumbers winningLottoNumbers, UserPurchase userPurchase) {
        this.winningLottoNumbers = winningLottoNumbers;
        this.resultCounts = new HashMap<>();
        initializeLottoCounts();
        this.purchasePrice = userPurchase.getPurchasePrice();
        this.totalLottoWinningMoney = ZERO;
    }
```
아니라면 위처럼 ZERO를 할당해야하지 않을까요?

OutputPrinter의 START_BRACKET도 다시한번 생각해볼 수 있을 것 같아요.

리뷰어마다 성향이 다를 수 있을 것 같은데 저는 매직넘버너 중복되어 사용되는 특정 메시지를 제외하고는 상수화를 지양하는 편입니다. 이유는 지나친 상수화로 도리어 어떤 값이 할당 되어 있는지 확인하는 과정이 필요하고 클래스의 필드 영역이 지나치게 많아지기 때문입니다.

이건 앞서 말씀드린 것처럼 약간의 취향문제일 수도 있으니 참고만 하고 한번쯤 생각해보면 좋을 것 같아요. 😉

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/view/printer/OutputPrinter.java
> +    private static final String NEW_LINE = "\n";
OS마다 개행 문자가 다르답니다.
그래서 자바에서는 `System.lineSeparator()`를 제공해주는데 이게 무엇인지 직접 설명드리는 것보다는 굉장히 간단한 api이니 한번 자바독을 직접 보시는걸 추천드려요. 자바독을 보고 이해하면 살짝 뿌듯한 기분도 느껴지죠. 😉

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/view/printer/OutputPrinter.java
> +public class OutputPrinter {
한가지 궁금한 점이 있습니다!(피드백이 아닙니다. 🙄 )
Printer와 View를 분리하신 이유가 무엇일까요?
MVC에 대해 설명할 때 웹페이지를 예시로 드리는 편인데 웹페이지를 생각해보면 약간은 js와 html을 분리한 느낌이긴 하네요.

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoMain.java
> +    }
다로 메서드로 뺀 이유는 main의 라인수를 줄이기 위함과 출력 때문일까요? 🤔 
별도 메서드로 빼지 않아도 `lottoMachine.purchaseLottoTicket(userPurchase)`로도 충분히 표현이 된다고 봅니다.

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoMain.java
> +            = purchaseLottoTickets(lottoMachine, userPurchase);
클래스와 변수명이 길어서 개행을 한걸까요?
일반적으로 한라인으로  작성하기 때문에 개행을 하기보다는 지금정도의 길이라면 한라인으로 작성해주는게  좋습니다.

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketpurchase/PurchasedLottoTickets.java
> +public class PurchasedLottoTickets {
여러타임의 Tickets가  존재하지도 않는데 Purchased가 필요할지 약간 고민되네요.
더군다나 변수명이 길어 불편을 겪고 있는걸로 보이네요.
이후의 RandomLottoTickets를 고려한 네이밍이 아닐까 싶은데 RandomLottoTickets과 PurchasedLottoTickets 분리가 꼭 필요할까요? 분리가 필요해도 미래의 요구사항을 지나치게 의식한게 아닐까 싶습니다. 🤔

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketpurchase/PurchasedLottoTickets.java
> +    private final List<LottoTicket> tickets;
List에 final을 사용해주셨는데 이 final은 어떤걸 의도한걸까요?
final로 인해 재할당은 불가능합니다. 하지만 
```java
    public void add(LottoTicket lottoTicket) {
        tickets.add(lottoTicket);
    }
```
를 보면 알수 있다시피 tickets가 변하고 있습니다. 즉 불변의 상태는 아닙니다. 꼭 불변하게 만들 필요는 없습니다!
중요한건 final 키워드를 어떤 의도를 가지고 사용했으며 의도대로 구현되어 있는지 입니다. 😉

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +    }
LottoMatchType.getLottoMatchType에서 보너스 번호가 일치했는지만 전달받는다면 이 과정이 불필요해 보입니다.
특히나 어떤 타입인지 알려면 최종적으로 handleFiveMatchType를 수행해야지만 되는 불안정한 상태로 보이네요.

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +        totalLottoWinningMoney += lottoMatchType.getPrizeMoney();
handleXXXMatchTypes이라는 이름과 다르게 전체 상금에 대한 집계도 진행되네요.
MatchTypes에 대한 처리가 끝난 다음 Map을 한번만 순회하면 계산 할 수 있을 것 같네요.

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/type/LottoMatchType.java
> +    public static List<LottoMatchType> getLottoMatchType(int countMatchedNumbers) {
다른 피드백에도 언급했지만 여기서 FIVE_MATCH, FIVE_AND_BONUS_MATCH도 구분해서 반환해준다면 List를 반환해줄 필요가 없을 것 같네요. 🤔

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketresult/WinningLottoNumbers.java
> +public class WinningLottoNumbers {
네이밍만 봤을 때는 
```java
private final LottoTicket winningTicket;
```
가 아닌
```java
private final List<LottoNumber> lottoNumbers;
```
을 가질걸로 기대됩니다.
실제 사용될 때도 
```java
    private int getOneLottoTicketNumbersMatchedCountResult(LottoTicket purchasedOneLottoTicket) {
        LottoTicket winningLottoTicket = winningLottoNumbers.getWinningTicket();

        return (int) purchasedOneLottoTicket.getLottoTicketNumbers()
            .stream()
            .filter(purchasedLottoNumber -> winningLottoTicket.getLottoTicketNumbers()
                .contains(purchasedLottoNumber))
            .count();
    }
```
List\<LottoNumber>를 활용합니다. WinningLottoNumbers의 이름을 바꾸는 등 여러가지 방법으로 개선이 가능해보이네요. 😉

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketresult/WinningLottoNumbers.java
> +        if (winningTicket.getLottoTicketNumbers().contains(bonusNumber)) {
ticketNumbers를 getter로 가져오지 말고 winningTicket.contains()를 제공해 줄 수 있을 것 같아요.

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +    }
> 아무리 생각해도 도메인 내부에 어울리지 않는 Validation 작업들은 도메인 외부의 InputView의 함수에서 했다.

비밀번호 길이가 6자리 이상인 사이트의 회원가입을 생각하면 6자리 이상인지에 대한 검증은 프론트와 백 어디서 해야할까요?
가능하면 둘 다 입니다. 그리고 같은 검증을 한다해도 프론트와 백에서 하는 검증은 서로 독립적이며 서로 의미가 다릅니다.
화면에서의 검증은 사용자가 입력한 값이 맞는지에 대한 검증이 될 테고, 지금과 같이 도메인 생성자에 검증이 있다면 사용자의 입력을 확인하는게 아닌 객체가 생성되는데 문제 없는 값인지 검증을 하는 겁니다.

flow상 사용자의 입력이 흘러들어오는 건 똑같지만 서로 다른 의미를 가지고 서로의 독립적입니다. 그렇다고 validation을 모든 영역에 추가하면 코드가 복잡해지는 것 대비 얻는게 없기 때문에 과제를 진행함에 있어서는 지금 정도로 분리된 체크가 딱 좋아보입니다. 그리고 각 검증 코드를 해당 검증을 책임져야 할 도메인에 잘 두셨네요. 👍

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoMain.java
> +        }
> 3. 함수 뒤에 붙이는 throws XXXException을 언제 사용하는지 궁금합니다.
> 우선 상위의 함수에서 try\~catch문을 사용하면 throws XXXException을 하위 함수들에 적어놓지 않아도
XXXException이 발생하면 알아서 main함수까지 타고올라가다가 try\~catch문을 만나면 해당 Exception 처리가 되잖아요??
만약 throws XXXException을 타고 올라가는 모든 함수마다 적어줄 경우, 상위 Exception 클래스로 적어주지 않는이상
XXXException이 변경될 때 마다 모든 throws XXXException을 수정해 줘야 하고요..
그렇다보니 throws XXXException은 언제 써야 이득을 볼까? 안쓰는 것과 무슨 차이가 있을까?
라는 궁금증이 생겼습니다!!

상위의 함수에서 try-catch를 한다 해도 exception이 발생하는 곳에서 try-catch를 하지 않으면 throws를 적어줘야 합니다.
단, 전제조건이 있습니다. 발생하는 예외가 checked exception인지 unchecked exception인지 여부입니다.
관련 내용은 아래 글들을 참고하면 좋을 것 같아요.
[Java 예외(Exception) 처리에 대한 작은 생각](https://www.nextree.co.kr/p3239/)
[Java의 예외 처리](https://johngrib.github.io/wiki/java-exception-handling/)

이펙티브 자바 3판 item 70, 71도 추천드립니다. (잘 정리된 포스팅이 안보이네요. 😢)

한가지 정리르 하자면 과정을 진행하면서는 일반적으로 Checked Exception은 사용하지 않는다고 생각하시면 됩니다. 😉

2021-02-19 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +public class LottoResult {
> 2. 페어가 클래스 내의 함수들 순서가 public 함수들이 위로, private 함수들이 아래로 위치해야 한다고 배웠다는데,
> 제가 클린코드 책을 읽었을 때는 신문 읽듯이 위에서 아래로 편하게 읽혀야 한다는 내용을 봤거든요.
그래서 저는 private, public을 신경쓰지 않고 무조건 가독성이 좋도록 순서를 위치시켰습니다.
휴의 생각은 어떠신가요?

저도 인비가 말씀 하신 것처럼 클린코드의 가이드 처럼 세로 방향으로 가깝게 두는 편입니다.
하지만 팀의 컨벤션이 public, private 순으로 나열된다면 그에 대해서 팀과 논의 후 결정에 따를 것 같습니다. 아마 이는 IDE의 발전(?)으로 메서드를 찾아가는게 마우스 클릭 한번으로 간단해져서도 있을 것 같아요. 예전은 바로 밑에 있지 않으면 찾기가 어려웠을 것 같네요.(경험해보진 않아서 모르지만... 🤣 )
주로 참고로 삼는 클린코드, 이펙티브 자바 등등은 제안으로 생각하는게 좋아요. 실제로도 팀 컨벤션이 자신의 스타일과 상이한 부분이 발생 할 수도 있는점에서 서로 의견이 다르다면 협의해가는 과정을 겪어보는 것도 좋다고 봅니다. 😉

2021-02-19 15:40 UTC, Hue9010 commented on README.md
> +  를 출력한다.
> 1. 실무에서는 UML을 어떤 방식으로 그리나요?
> 정식 UML 방식대로 구체적으로 그리는지, 로버트 마틴 말대로 최대한 이해하기 쉽게 그리는지 궁금합니다.
> 아무래도 회사마다, 팀마다 다른겠죠?
> 어떻게 그려야 잘 그리는 건지 궁금합니다!

살짝 찔리네요. 🙄 찔리는 이유는 UML을 잘 작성하지 않습니다. 
간혹 작성할 때는 구조가 바뀔 정도의 레거시의 개선이 이뤄질 때 as-is > to-be 차이점과 상태 flow를 표현 할 필요가 있을 때 정도 작성하고 있습니다.
이유(변명) 중 하나는 팀의 개발자는 두명 뿐으로 서로 해당 도메인에 이미 익숙한 상태에서 작업이 진행되기 때문에 기본적인 UML을 참고할 상황이 없기 때문입니다.(하지만 신규 입사자가 오게 되면 약간 얘기가 달라지긴 하죠...)

그런면에서 실무적인 측면에서의 UML에 대한 조언을 드리진 못할 것 같네요. 😢
공유 주신 문서를 봤을 때 제 기준으로는 단순하게 작성된 UML로 전체적인 윤곽을 파악 한 후 세세한 관계는 코드를 보고 파악하는게 나은 것 같습니다.

2021-02-19 15:40 UTC, Hue9010 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    @ValueSource(ints = {1, 10, 45})
경계값 테스트 👍

2021-02-19 15:40 UTC, Hue9010 commented on src/test/java/lotto/domain/LottoTicketTest.java
> +        ));
직접 할당하기 보다는 용도에 맞게 beforeXXX 애노테이션을 활용해주세요.

2021-02-19 15:40 UTC, Hue9010 commented on src/test/java/lotto/domain/ticketpurchase/UserPurchaseTest.java
> +    @DisplayName("구입 금액이 1000원 단위가 아닐 시 에러")
에러 상황에 대한 테스트 👍

2021-02-19 21:07 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketpurchase/UserPurchase.java
> +        if (purchasePrice <= ZERO || purchasePrice % ONE_TICKET_PRICE != ZERO) {
앗, 방심했네요.. 반영했습니다!!

2021-02-19 21:09 UTC, taehee-kim-dev commented on src/main/java/lotto/controller/LottoMain.java
> +    private static void checkLottoResult(PurchasedLottoTickets purchasedLottoTickets,
main 메소드의 줄 수를 줄이려고 따로 함수로 분리한다는게,
오히려 해당 함수에 두 가지의 책임을 주는 상황을 초래했군요 😱

함수 분리를 제거하여 해결했습니다!!

2021-02-19 21:11 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketgenerator/LottoMachine.java
> +public class LottoMachine {
곰곰이 생각해보니 휴의 말이 프로그래밍적으로 맞는 것 같아요!!
저와 페어는 현실세계를 자꾸 생각하다보니 굳이 필요하지 않은 객체를 생성해버렸네요.. 😓 

LottoMachine을 제거하여 해결했습니다!!

2021-02-19 21:13 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +    private static final int ONE_COUNT = 1;
저도 휴와 같은 생각입니다!!

(변명을 하자면...) 제 페어의 전 리뷰어분은 지금은 학습하는 과정이니 오버엔지니어링이더라도 모든 하드코딩값들을 상수화 하라고 했다고 해서 제가 거기에 맞췄거든요..

이제 페어프로그래밍 이후 제 개인 리팩토링 시간에 매직넘버가 아니면 상수화 하지 않는게 제 취향에도 맞는 것 같아요!! 😄 

바로 반영했습니다!!

2021-02-19 21:15 UTC, taehee-kim-dev commented on src/main/java/lotto/view/printer/OutputPrinter.java
> +    private static final String NEW_LINE = "\n";
오... 맞아요 OS마다 개행문자가 다르다는걸 간과하고 있었네요.. 😮 
이런 아주 좋은 꿀팁을 알려주다니!! 정말 고마워요!! 😊

2021-02-19 21:18 UTC, taehee-kim-dev commented on src/main/java/lotto/view/printer/OutputPrinter.java
> +public class OutputPrinter {
음.. 프로그래밍 요구사항인 __"규칙 3: 모든 원시값과 문자열을 포장한다."__ 에 신경쓰다보니 그런 것 같아요!!

코드에 단순 문자열이 중간중간 끼어있으면 뭔가....찝찝한 느낌.... 😂 

또한, 코딩할 때 항상 분류하고 분리하는 습관과 강박(?)이 있다보니.. 따로 분리했습니다!!

2021-02-19 21:27 UTC, taehee-kim-dev commented on src/main/java/lotto/controller/LottoMain.java
> +    }
네 맞습니다.. main의 라인들이 다닥다닥 붙어있고 꽉차서 뭔가 별도 메서드로 빼야겠다는 생각을 했습니다 😢 
바로 반영했습니다!!

2021-02-19 21:29 UTC, taehee-kim-dev commented on src/main/java/lotto/controller/LottoMain.java
> +            = purchaseLottoTickets(lottoMachine, userPurchase);
앗, 그런가요?? 사실 위와 같은 부분이 꽤 있는데, 구글 자바 컨벤션으로 설정해놓은 자동 포맷팅을 마지막에 하고 제출하다보니 자동 개행이 된 경우도 있어요..ㅠㅠ 축약하지 않으면서 너무 길지 않은 이름을 짓고싶은데 항상 어렵네요.. :sob:
반영했습니다!!

2021-02-19 21:32 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketpurchase/PurchasedLottoTickets.java
> +public class PurchasedLottoTickets {
뭔가 이름을 구체적인 의미로 지으려다보니 저렇게 지어버렸네요 ㅠㅠ

일반적인 컬렉션 이름은 단순하게 복수명사로만 쓰긴 하더라구요..

LottoTickets로 변경하였습니다!!

2021-02-19 21:36 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketpurchase/PurchasedLottoTickets.java
> +    private final List<LottoTicket> tickets;
휴가 말씀해주신 내용은 알고 있었습니다!!

그런데도 불구하고 final을 붙인 이유는.

final을 안붙이면 인텔리제이가 "may be final"이라고 노란 형광펜 경고를 줘서.. 찝찝하더라구요...ㅋㅋㅋ

여러 블로그들을 참고해도 다들 저렇게 쓰는 것 같고, 저도 뭔가 습관이 된 것 같습니다!!

2021-02-19 21:38 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +    }
오....맞아요.. 가장 난잡하고 크리티컬한 부분이었던 것 같습니다.

휴의 말을 참고해 더 깔끔하고 정돈되도록 리팩토링 적용하였습니다!!

2021-02-19 21:40 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +        totalLottoWinningMoney += lottoMatchType.getPrizeMoney();
와 정말 그러네요!!

왜 그 생각을 못했는지 😭 

좋은 피드백 감사해요 휴!! 😃

2021-02-19 21:41 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketresult/WinningLottoNumbers.java
> +public class WinningLottoNumbers {
다시 생각해보니 정말 그렇군요.

클래스의 이름만 보고도 내부를 예상할 수 있도록 이름을 지었어야 하는데 말이죠ㅠㅠ

고민고민끝에 WinningTicketAndBonusNumber로 이름을 바꿨습니다!!

2021-02-19 21:43 UTC, taehee-kim-dev commented on src/main/java/lotto/type/LottoMatchType.java
> +    public static List<LottoMatchType> getLottoMatchType(int countMatchedNumbers) {
맞아요.. 단순히 FIVE_MATCH 타입과 FIVE_AND_BONUS_MATCH 를 구분하기 위해 List를 반환할 필요는 없었네요 ㅠㅠ

반영했습니다!!

2021-02-19 21:44 UTC, taehee-kim-dev commented on src/main/java/lotto/domain/ticketresult/WinningLottoNumbers.java
> +        if (winningTicket.getLottoTicketNumbers().contains(bonusNumber)) {
앗 그러네요.. 안으로 감추고 밖에서는 단순히 메시지를 던지고 응답을 받아야하는데..

반영했습니다!!

2021-02-19 21:46 UTC, taehee-kim-dev commented on src/main/java/lotto/view/InputView.java
> +    }
와우 그렇군요!! 감사합니다!! 🙇

2021-02-19 22:05 UTC, taehee-kim-dev commented on src/main/java/lotto/controller/LottoMain.java
> +        }
오... 그렇군요!!

## 질문이 있습니다!!

그러면 Validation에서 던지는 Exception이나 Optional의 orElseThrow에서 던지는 Exception은 RuntimeException, 즉 Unchecked Exception 이니까, try~catch 와 throws를 통해 처리하지 않아도 괜찮은건가요??

2021-02-19 22:20 UTC, taehee-kim-dev commented
# 인비의 학습로그
## [JDK] - OS 독립적 개행문자 - 2
### 내용
- OS마다 개행문자가 다르다는것을 간과하고 코드에 개행문자를 __\n__ 로 지정해버렸다.
- 리뷰어 휴가 이에 대한 피드백으로 __System.lineSeparator()__ 에 대해 찾아보라고 해서 오라클 자바 문서를 찾아보았다.
- 해당 함수는 운영체제에 맞는 개행문자를 반환해준다. 즉, OS로부터 독립적인 개발을 할 수 있는 것이다. 이런게 있었다니!! 엄청난 꿀팁이다!!
### 링크
- <a href="https://docs.oracle.com/javase/7/docs/api/java/lang/System.html" target="_blank">오라클 자바 문서 System.lineSeparator()</a>

2021-02-19 22:23 UTC, taehee-kim-dev commented
안녕하세요 휴!!
좋은 리뷰 정말정말 감사합니다!!

휴가 저에게 질문하셨던 것에 대한 답변, 제 생각, 
그리고 추가적인 질문들을 휴의 리뷰 코멘트 밑에 코멘트로 달았어요!!

그리고 반영한것들은 모두 __Resolve conversation__ 했습니다.
이렇게 하는 것 맞나요..??

감사합니다!! 🙇

2021-02-20 04:50 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoMain.java
> +            = purchaseLottoTickets(lottoMachine, userPurchase);
`구글 자바 컨벤션으로 설정해놓은` 자동 포맷팅
블락 구문이 원인(?)이 된거기 때문에 이건 팀 컨벤션에 맞출테니 문제 없을 걸로 보입니다!

느낌이 80자였나 120자 관련 컨벤션일 것 같은데 요즘처럼 모니터가 커진 환경에서는 조금 너프하게 적용해도 되지 않을까 싶어요.
그렇다면 이건 인비가 선호하는 컨벤션으로 적용하면 될 것 같습니다. 😉

2021-02-20 04:58 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketpurchase/PurchasedLottoTickets.java
> +    private final List<LottoTicket> tickets;
재할당만 불가한 걸 알고 쓰는지와 왜 사용했는지가 중요합니다.
고기도 먹어본 사람이 맛을 안다고 😋
아직 확신이 안서면 우선 이곳저곳에 사용해보면서 기준을 잡아가는 걸 추천드려요.

2021-02-20 05:04 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoMain.java
> +        }
이펙티브 자바가 있다면 한번 쯤 예외 파트를 보는걸 추천드려요. 😉 
아니라면 [(이펙티브 자바 3) 10장 예외 정리](https://ckddn9496.tistory.com/122) 이것도 전체적인 내용을 볼 수 있을 것 같네요.

throws는 굳이 안해주셔도 되지만 try-catch와 같이 예외를 핸들링 하는 건 필요합니다. 예외 처리를 하지 않을거라면 예외를 발생시킬 이유도 적죠. 
하지만 try-catch를 적용해보시면 알텐데 잘못하면 예외 처리에 대한 코드로 인해 코드가 비대해지고 복잡해지는 경험을 할 수도 있습니다. 예외처리가 쉽지 않아요. 그런면에서 지금은 예외를 집중적으로 다룰 시기가 아니기 때문에 궁금하다면 관련 내용을 한번쯤 보는 정도까지만 추천드립니다. 시간은 한정적이기 때문에 학습을 할 때 선택과 집중이 중요하다고 생각돼요.

2021-02-21 06:38 UTC, Hue9010 approved these changes
잘 반영해주셨네요. 👍 
이번 단계는 여기서 머지하도록 할게요.
몇가지 개선필요한 점 남겨뒀는데 다음 단계를 진행할 때 반영해주셔도 충분해 보입니다. 😉 
궁금한건 이전처럼 코멘트나 DM으로 문의주세요!
수고하셨습니다!

2021-02-21 06:38 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +        resultCounts.put(lottoMatchTypes, resultCounts.get(lottoMatchTypes) + 1);
[자바 HashMap을 효과적으로 사용하는 방법](http://tech.javacafe.io/2018/12/03/HashMap/)
computeIfPresent를 알아두면 편하답니다. 😉

2021-02-21 06:38 UTC, Hue9010 commented on src/main/java/lotto/type/LottoMatchType.java
> +    THREE_MATCH(3, 5_000,
`_`  👍

2021-02-21 06:38 UTC, Hue9010 commented on src/main/java/lotto/controller/LottoMain.java
> +    private static UserPurchase getUserPurchaseInput() {
이건 지극히 개인적인 의견인데 잘못된 값을 입력 했을 때 재입력을 받는건 InputView에서 처리 해 줄 수도 있을 것 같네요.
1. 잘못된 `입력`에 대한 검증이기 때문에
2. 회원가입 시 사용불가한 비밀번호 입력시 화면 내에서 재입력 요청하는걸 참조

컨트롤러를 좀더 가볍게 가져가고 싶은 개인적인 욕심(?)에 드리는 의견이기 때문에 인비가 판단하고 결정지으면 될 것 같습니다. 😉

2021-02-21 06:38 UTC, Hue9010 commented on src/main/java/lotto/view/printer/OutputPrinter.java
> +public class OutputPrinter {
View를 어떻게 관리하는게 좋을지 확실치 않아서 요건 프론트 쪽 관리로 보고 별도 피드백을 드리진 않을게요. 😢

2021-02-21 06:38 UTC, Hue9010 commented on src/main/java/lotto/type/LottoMatchType.java
> +        "5개 일치, 보너스 볼 일치(30000000원) - %d개"),
왜 6이 됐을까요?  🤔
LottoMatchTypeTest.java Line 59도 같이 확인해주세요ㅎㅎ

2021-02-21 06:38 UTC, Hue9010 commented on src/main/java/lotto/domain/ticketresult/LottoResult.java
> +    }
```java
    private int getOneLottoTicketNumbersMatchedCountResult(LottoTicket lottoTicket) {
        LottoTicket winningLottoTicket = winningLottoNumbers.getWinningTicket();

        return (int) lottoTicket.getLottoTicketNumbers()
            .stream()
            .filter(lottoNumber -> winningLottoTicket.getLottoTicketNumbers()
                .contains(lottoNumber))
            .count();
    }
```
이전과 달리 lottoNumbers. getMatchedLottoNumbers로도 동일한 표현이 되고 있고 사용처도 한 곳인데 별도 메서드로 추출할 필요가 있을까요? 🤔

2021-02-21 06:39 UTC, merged