[1단계 - 로또 구현] 소롱(최솔지) 미션 제출합니다.
woowacourse/java-lotto pull request #247
Opened 2021-02-18 08:35 UTC by soulgchoi

안녕하세요, 지노! 소롱입니다.
앞으로 저의 코드에 많은 지적 부탁드립니다.

이번 로또 미션은 자동차 경주 미션보다 난이도가 훨씬 높다고 느꼈어요.
서로 엮여 있는 관계들이 많아 객체를 분리하고 책임을 관리하기 매우 힘들었습니다.
우선 필요한 모든 테스트와 기능을 구현하는 것으로 1차적인 목표를 잡고 진행했습니다.
일급 콜렉션에 대한 이해가 부족해서, 더 보완한 뒤 1단계 안에 반영해보도록 하겠습니다.

지난 미션부터 `main` 메서드가 구체적으로 어떤 역할을 해야하는지 잘 모르겠어요.
제가 제출했던 자동차 미션에서는 단순히 컨트롤러를 불러오는 역할만 했었는데,
홈페이지의 리팩토링 항목을 보면 컨트롤러와 거의 유사한 역할을 하고 있다고 느껴졌습니다.
레이어 차원의 문제라고 볼 수 있을까요?

아무쪼록 많은 피드백 부탁드리고, 더 발전된 코드 계속 제출하겠습니다.

2021-02-18 08:36 UTC, soulgchoi commented
# 학습 로그

## [JDK] Stream API - 1

### 내용

- 로또 추첨 결과 중에 각각의 `Rank`가 몇 개인지 확인하기 위해 `filter` 사용

### 링크

- [https://coderanch.com/t/538049/java/compare-ArrayList-objects-count](https://coderanch.com/t/538049/java/compare-ArrayList-objects-count)
- [https://stackoverflow.com/questions/7687062/count-occurrences-of-a-given-string-in-an-arraylist](https://stackoverflow.com/questions/7687062/count-occurrences-of-a-given-string-in-an-arraylist)
- [https://www.geeksforgeeks.org/stream-count-method-java/](https://www.geeksforgeeks.org/stream-count-method-java/)
- [https://www.baeldung.com/java-stream-filter-count](https://www.baeldung.com/java-stream-filter-count)

## [JDK] ArrayList - 2

### 내용

- 포함 관계를 확인하기 위해 여러 메서드를 시도해봄
- 배열과 인덱스 접근이 달라 헷갈리는 지점들이 있었음

### 링크

- [https://howtodoinjava.com/java/collections/arraylist/compare-two-arraylists/](https://howtodoinjava.com/java/collections/arraylist/compare-two-arraylists/)

## [JDK] Map - 1

### 내용

- `Rank`와 개수를 표현하기 위해 사용하게 되었음
- 출력 과정에서 순서가 뒤죽박죽이라 `HashMap`은 순서를 보장하지 않고, `TreeMap`으로 바꿔 key 순서대로 사용

### 링크

- [https://ponyozzang.tistory.com/404](https://ponyozzang.tistory.com/404)
- [https://ithub.tistory.com/34](https://ithub.tistory.com/34)

## [Testing] TDD - 4

### 내용

- 테스트 코드를 먼저 짜고 프로덕션 코드를 짜는 방식으로 최대한 작업
- 이에 따라 페어 프로그래밍에서 Ping-Pong 방식을 자연스럽게 쓰게 되었음
- 리팩토링은 테스트를 최대한 해치지 않는 선에서 이루어지도록 함
- 클래스 분리에 따른 테스트 분리 외에 테스트 코드는 큰 변화가 없었다고 생각함

## enum - 4

### 내용

- 등수 판별에 `enum` 사용
- 반복문 사용과 길이 구하는 부분에서 많은 구글링

### 링크

- 도서 <자바의 정석>
- 우테코 선배님들의 코드
- [https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html](https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html)
- [https://opentutorials.org/module/1226/8025](https://opentutorials.org/module/1226/8025)
- [https://johngrib.github.io/wiki/java-enum/](https://johngrib.github.io/wiki/java-enum/)
- [https://www.baeldung.com/java-enum-iteration](https://www.baeldung.com/java-enum-iteration)

2021-02-18 08:40 UTC, soulgchoi commented
그리고 이번 미션 중에 접근제어자가 매우 어려웠어서 이 부분을 특히 많이 봐주시면 좋겠습니다!

2021-02-20 09:27 UTC, hyunssooo requested changes
안녕하세요 소롱! 지노입니다!
빠르게 잘 구현해주셨어요! 🙂
몇 가지 코멘트 남겼어요! 참고해주시고 함께 고민해보면 좋을 거 같아요! 
언제든 편하게 dm 주세요!!
리뷰가 늦어서 죄송합니다! 🙇‍♂️

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/Application.java
> +}
안녕하세요 소롱 지노 입니다! 
우선 질문에 답변을 드리면 지금은 controller 클래스를 따로 작성하지 않고 main()을 controller라고 생각하셔도 상관없습니다! 
하지만 소롱이 controller 클래스를 작성하고 싶다고 하면 따로 작성하는 것두 방법입니다!

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/controller/LottoController.java
> +    private static WinningLotto winningLotto;
컨트롤러에 꼭 필드가 있어야 할까요?? 
또한, 필드들로 요구사항을 풀어내는데 static이면 어떤 문제점이 있을까요?
사용자가 1명이 아닌 여러명이라면 모두가 해당 필드들을 공유하지 않을까요??

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +    }
Lotto가 6개의 숫자를 가지고 있네요! 
각각의 6개의 숫자를 LottoNumber라는 객체로 분리하면 더 좋을 거 같아요! 
객체로 분리하면서 해당 객체의 책임을 생각해보면 더 좋을 거 같아요 🙂

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(ArrayList<Integer> numbers) {
ArrayList 대신 List를 사용하는것이 좋습니다 :) 다형성을 활용하세요!
```suggestion
    private final List<Integer> lotto;

    public Lotto(List<Integer> numbers) {
```
코드 전체적으로 변경하면 좋을 거 같습니다!

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +    }
여기처럼 
```java
List<Integer> numbers = new ArrayList<>();
```
이런식으로 수정해주세요!

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoGenerator.java
> +        Collections.shuffle(nums);
리턴 값도 마찬가지 입니다! List로 변경해주세요!

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +
중복을 허용하지 않는 자료구조는 없을까요??

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoGroup.java
> +
해당 객체의 역할은 무엇일까요??
Lotto 여러개를 가지고 있는 일급컬렉션을 의도하신걸까요??
https://brainbackdoor.tistory.com/140
https://woowacourse.github.io/javable/post/2020-05-08-First-Class-Collection/
두 글을 참고하면 좋을 거 같아요!

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/domain/Money.java
> +
거의 모든 메서드가 static 이군요
https://woowacourse.github.io/javable/post/2020-07-16-static-method/ 
읽어보면 좋을 거 같아요🙂

2021-02-20 09:27 UTC, hyunssooo commented on src/main/java/lotto/domain/Money.java
> +    }
테스트에서만 사용하는 메서드네요! 테스트를 위한 코드가 프로덕션 코드에 있는 것에 대해서 고민해보면 좋을 거 같아요 :)

2021-02-20 09:27 UTC, hyunssooo commented on src/test/java/lotto/domain/BonusBallTest.java
> +    void 보너스볼이_숫자인지_확인() {
```@DisplayName``` 에 관해서 찾아 보면 좋을 거 같아요 :)

2021-02-23 07:45 UTC, soulgchoi commented
안녕하세요, 지노~!
말씀드린 것처럼 LottoNumber를 분리하려다 점점 고칠 범위가 커져버려서.. 삽질 시간이 굉장히 길어졌어요.

처음에는 분리만 했다가, 정적 팩토리 메서드를 적용도 하고,
그러다보니 바꿀 것도 많아지고 더 바꿔보려는 욕심도 생기고 그랬습니다!
정적 팩토리 메서드 외에는 static 사용을 줄이고 한 곳에서 일을 처리하게 만드려고 노력했습니다.

사실 아직도 일급 콜렉션에 대한 이해가 확실하지 않아서 객체를 최대한 쪼개는 것으로 연습해보고 있습니다.

저는 DisplayName은 왠지 이름을 두 번 짓는 기분이라 사용을 안했었는데,
테스트 환경이나 가독성을 고려하면 쓰는 게 훨씬 나은 것 같습니다.
역시 뭐든 일단 사용해보고 결정하는 것이 옳다는 깨달음도 있었네요😋

메서드 오버로딩이나 오버라이딩 하는 것 모두 자바는 처음인 부분이 많아 항상 확신이 없는데요,
이번에도 가감없는 피드백 부탁드립니다🙏

2021-02-23 17:48 UTC, hyunssooo requested changes
안녕하세요 소롱!
많이 고민한 흔적이 보이네요! :) 
몇 가지 코멘트 남겼어요! 고민해보면 좋을 거 같습니다!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +
중복을 허용하지 않는 자료구조는 없을까요?

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Rank.java
> +    FIRST(6, 2_000_000_000);
언더바를 사용해서 읽기 수월하네요 👍

2021-02-23 17:48 UTC, hyunssooo commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    }
엣지 케이스로 테스트 작성을 하면 더 좋을 거 같아요! 에러 발생일 경우 0, 46이 되겠네요!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/view/LottoView.java
> +
뷰도 input과 out으로 나누면 역할이 분리될 거 같아요!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/controller/LottoController.java
> +    private List<Lotto> lottos;
컨트롤러에 필드를 모두 제거할 수 있을 거 같아요! :) 보통 컨트롤러는 인스턴스 하나로 무상태입니다! 현재 구조라면 사용자가 여러명이면 원하지 않은 결과를 받을 수 도 있겠네요!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/controller/LottoController.java
> +    private List<Lotto> lottos;
또한 Lotto 여러개를 가지고 있는 일급컬렉션도 나올 수 있겠네요!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +    public static final int LOTTO_SIZE = 6;
셋다 public일 이유가 있을까요? 또한, 상수와 필드를 개행으로 분리하면 가독성이 더 좋아질 거 같아요!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +
unmodifiableList로 반환하면 어떤 장점이 있을까요??

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Lotto.java
> +    }
toString()을 view에서 사용하기 위해 재정의하셨네요! 보통 toString()은 디버깅을 위해 재정의합니다! 
```이펙티브 자바 아이템 12. toString은 항상 재정의하라``` 를 참고하면 좋을 거 같아요!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoNumber.java
> +
여기도 확인 부탁드려요! 
클래스 내 변수/메서드 선언 순서는 다음과 같습니다.
class A {
  상수(static final) 또는 클래스 변수
  인스턴스 변수
  생성자
  메소드
}

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
클래스 이름이 LottoGenerator이기 때문에 메서드는 generate()로도 충분한거 같아요! 
클래스 이름을 봤을땐 Lotto를 반환할거라 생각했는데 아니군요.

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/controller/LottoController.java
> +        );
WinningLotto도 seller가 sell하는 것 일까요?

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/WinningLotto.java
> +    }
getter를 사용하지 않을 수는 없을까요? 필드에 있는 winLotto에게 메세지를 보내는 것은 어떨까요??

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoGenerator.java
> +
이러면 LottoNumber에서 캐싱한 이유가 없지 않을까요?? 
한곳에서 관리하는 것은 어떨까요? generator에서는 int값을 가지고 있어도 괜찮을 거 같아요! :)

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/Application.java
> +        lottoController.drawLotto();
메서드를 하나로 줄여봐요 :) 모든 메서드가 public일 이유는 없을 거 같아요!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/Application.java
> +        lottoController.drawLotto();
메서드 파라미터로 객체를 넘기고 리턴 값으로 객체를 받으면 Main에서는 하나의 메서드만 실행하면 될 거 같아요!

2021-02-23 17:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Money.java
> +        return money;
```suggestion
        try {
            return Integer.parseInt(input);
        } catch (Exception e) {
            throw new IllegalArgumentException(MONEY_INT_ERROR);
        }
```
이렇게도 가능할 거 같아요 :)

2021-02-24 12:53 UTC, soulgchoi commented
안녕하세요 지노!
언제 시간이 이렇게 갔나 하면 꼭 같이 드는 생각은.. 코드의 양은 삽질에 비례하지 않는다는 것이에요🤣
LottoNumber와 LottoGenerator사이에서 아주 삽질을 하다가 어찌저찌 끝냈는데요,
LottoGenerator가 int를 가지고 있어도 되지 않냐는 지노의 피드백을 제가 잘 이해한건지 모르겠습니다.

Input/Output은 메시지랑 함께 값을 받아야 제가 편해서 보통 그렇게 썼는데,
생각해보니 Input 받는 부분은 늘 같아서 그거 하나만 두고 쓰는게 더 간결해보이더라구요🤔

상수에 public을 남발했던건 이리저리 복사하다가 실수가 생겼었는지.. 꼼꼼하게 체크해주셔서 감사합니다. 정말 눈치 못챘어요..

그리고 미션 내내 떠오르는 궁금증입니다!
저는 뷰를 정말 프론트단에서 작업한다는 느낌으로 하고 있었어요.
그래서 뷰에는 데이터 그 자체를 전달하려고 하고, 뷰에서 도메인을 호출해서 데이터를 가공하는건 지양하고 있었거든요.
도메인에서 가장 로우한 데이터를 리턴하려고 하고, 그러다보면 로직이 점점 복잡해져서 어려움을 느끼고 있습니다.
뷰에서 처리하는 로직의 범위가 어느 정도일까요? 이번 미션을 예로 알려주신다면 감사하겠습니다. 

모쪼록 이번에도 잘 부탁드립니다.🙏

2021-02-25 18:36 UTC, hyunssooo commented
안녕하세요 소롱! 

사실 저는 개인적으로 int값 혹은 String 이정도는 view에서 데이터를 가공해서 넘겨줘도 괜찮다고 생각해요! 혹은 ```List<Integer>```, ```List<String>``` 이정도 까지는 괜찮다고 생각합니다! 
지금 현재 InputView에 메서드가 하나가 있고 모든 것을 SCANNER.nextLine()으로 처리하고 있네요! 제가 말한 방법으로도 한번 개발해보시고 두 가지 방법의 장단점을 느껴보면 좋을 거 같아요! 아니면 도메인 객체에서 여러가지 생성을 지원하는 것도 방법이겠네요!

2021-02-25 18:48 UTC, hyunssooo approved these changes
안녕하세요 소롱! 
피드백이 늦어서 죄송합니다..😭
step1 진행하신다고 정말 수고 많으셨어요! 👏👏👏👏
몇 가지 코멘트 남겼어요! step2 진행하시면서 어렵거나 궁금한 점 있다면 언제든 편하게 연락 주세요! 
감사합니다!

2021-02-25 18:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoGroup.java
> +        return lottoGroup;
```suggestion
        return Collections.unmodifiableList(lottoGroup);
```
unmodifiableList를 사용하면 어떤 장점이 있을까요?

2021-02-25 18:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoGenerator.java
> +
static으로 미리 생성해둬도 괜찮을 거 같아요 :)

2021-02-25 18:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
numbers를 미리 생성해둔다면 
```suggestion
    public Set<LottoNumber> generateAuto() {
        Collections.shuffle(numbers);
        List<Integer> lottoNumbers = numbers.subList(0, LOTTO_NUMBER_LIMIT);
        return lottoNumbers.stream()
            .map(LottoNumber::of)
            .collect(Collectors.toSet());
    }
```
불필요한 객체 생성도 줄일 수 있을거 같아요! 그리고 LottoGenerator인데 generate()했을때 Lotto를 반환해 주는 것은 어떨까요??

2021-02-25 18:48 UTC, hyunssooo commented on src/main/java/lotto/domain/LottoResult.java
> +    }
생성자로 Map을 받는 방법도 있겠네요!

2021-02-25 18:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Rank.java
> +    }
지난번에 toString에 대한 코멘트를 남겼는데 여기는 반영이 안되었네요 ㅠㅠ 확인 부탁드려요!

2021-02-25 18:48 UTC, hyunssooo commented on src/test/java/lotto/domain/SellerTest.java
> +import java.util.List;
사용하지 않는 import는 제거해주세요!

2021-02-25 18:48 UTC, hyunssooo commented on src/main/java/lotto/domain/Seller.java
> +
랜덤은 테스트하기 어렵습니다! 랜덤에 대한 의존을 분리할 수도 있겠네요!

2021-02-25 18:48 UTC, merged