[1단계 - 로또 구현] 바다(조아라) 미션 제출합니다.
woowacourse/java-lotto pull request #260
Opened 2021-02-18 09:00 UTC by xrabcde

안녕하세요 데이브! 바다입니다🌊
이번 미션동안 잘 부탁드려요!!

이번 미션을 진행하며 `객체 분리`에 대해 어려움을 겪어 질문드립니다!

- 이번 미션을 진행하며 페어와 기능을 구현하다가 객체 분리가 필요하다는 생각이 들 때마다(~~혹은 한 클래스의 코드가 너무 길어질 때마다~~) 클래스를 생성했었는데, 기능을 구현하기 전에 객체를 만들지 미리 설계를 한 후 개발을 진행하는 것이 더 좋은 방법인가요?

미션을 진행하면 할수록 공부를 더 많이 해야겠다는 생각이 드네요😂

미션을 진행하며 학습한 내용에 대한 로그는 작성하는 대로 아래 코멘트로 달아두겠습니다!
부족한 코드 봐주셔서 감사드리고 따끔한 피드백 부탁드리겠습니다! ㅎㅎ

2021-02-18 09:56 UTC, xrabcde commented
# 로또 1단계 학습로그
## [JCF] Map - 2
### 내용
- 각 등수별 당첨 개수를 저장하기 위한 자료형이 필요해 사용하게 되었음
- 출력 시 5등부터 순서대로 출력하기 위해 key 순서대로 정렬해주는 자료형인 `TreeMap` 사용
- 총 당첨금액 계산 시 Map Iteration을 위해 `EntrySet` 사용
### 링크
- https://ithub.tistory.com/34
- https://stove99.tistory.com/96
## [OOP] Enum - 4
### 내용
- 각 등수별 당첨 금액과 몇 등인지를 저장하기 위해 enum 사용
- enum에 어디까지 책임을 줘야하는지 결정하는 부분이 어려웠음
### 링크
- https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

2021-02-20 05:08 UTC, dave915 commented
> 객체분리
페어와 기능을 구현하다가 객체 분리가 필요하다는 생각이 들 때마다(혹은 한 클래스의 코드가 너무 길어질 때마다) 클래스를 생성했었는데, 기능을 구현하기 전에 어떤 객체들을 만들지(+어떤 책임들을 줄지) 미리 설계를 한 후 개발을 진행하는 것이 더 좋은 방법인가요?

기능을 구현하기전에 대략적인 설계를 하면 개발을 진행 할 때 도움이 되겠지만, 반드시 모든 객체를 생각할 필요는 없다고 생각합니다 :) 

> stream과 반복문
로또 미션 중 로또 그룹의 로또들을 생성하거나 당첨 결과를 확인하는 과정에서 반복을 사용하는 경우가 많았는데 이 경우 for문을 사용하는 것보다 stream의 forEach를 활용하는 것이 좋은 방법일까요? 아니면 상황에 따라 더 나은 방법을 적용해야 하나요?

`Collection.foreach` 와 `for`문은 상황에 따라 적용하고, `Stream.foreach`는 출력용 아니면 지양 해야한다는 의견들이 있어요. 
`Stream.foreach`는 조금 더 찾아보는걸 추천드릴게요!

2021-02-20 08:36 UTC, dave915 requested changes
바다 안녕하세요! 리뷰를 맡게된 데이브입니다 :) 
요구사항에 맞춰 구현 잘 해주셨네요 ㅎㅎ 
질문주신 부분에 대한 답변과 몇가지 피드백 남겼어요. 확인 부탁드립니다! 
궁금한 점이 있으면 언제든 DM주세요!

2021-02-20 08:36 UTC, dave915 commented on src/main/java/lotto/controller/LottoController.java
> +    private static void drawResult() {
메소드가 static인 이유가 있을까요? 

아래 링크 `3. Variables/Methods Declaration  변수와 메소드의 선언` 도 읽어보면 좋을 것 같아요 :) 
https://itdar.tistory.com/entry/클린코딩더-나은-코딩을-하는-10가지-방법-10-Tips-for-clean-code-better-code-quality-code

2021-02-20 08:36 UTC, dave915 commented on src/main/java/lotto/domain/Lotto.java
> +            validateNumRange(nums.get(i));
```suggestion
        for (int i = 0; i < nums.size(); i++) {
            validateNumRange(nums.get(i));
        }
```
아래 링크 `7. 2 복합문` 부분 참고 부탁드릴게요! 
https://myeonguni.tistory.com/1596

2021-02-20 08:36 UTC, dave915 commented on src/main/java/lotto/domain/Lotto.java
> +    private final ArrayList<Integer> lottoNumbers;
`ArrayList<Integer> lottoNumbers` vs `List<Integer> lottoNumbers` 🤔

2021-02-20 08:36 UTC, dave915 commented on src/main/java/lotto/domain/Lottos.java
> +    private static int count;
Lottos가 money와 count를 계속 들고다닐 이유가 있을까요? 🤔

2021-02-20 08:36 UTC, dave915 commented on src/main/java/lotto/domain/Rank.java
> +        return matchCount + "개 일치 (" + prize + "원) - ";
View의 출력 형식을 도메인에서 만들어 주면 어떤 문제가 있을까요? 🤔

2021-02-20 08:36 UTC, dave915 commented on src/main/java/lotto/domain/Rank.java
> +        if (match == 5 && bonusMatch)
`match == 5` 매직 넘버를 제거해주세요! 
https://hoonmaro.tistory.com/44

2021-02-20 08:36 UTC, dave915 commented on src/test/java/lotto/domain/MoneyTest.java
> +                .hasMessageContaining(MONEY_INT_ERROR);
이렇게도 사용할 수 있을 것 같아요. 
```suggestion
                .hasMessageContaining(Money.MONEY_INT_ERROR);
```

2021-02-20 08:36 UTC, dave915 commented on src/test/java/lotto/domain/MoneyTest.java
> +    void 구입금액이_숫자인지_확인() {
아래 링크 `JUnit5 @DisplayName 추가` 부분을 읽어보면 좋을 것 같아요 :) 

https://www.freeism.co.kr/wp/archives/1061

2021-02-21 03:36 UTC, xrabcde commented on src/main/java/lotto/domain/Lotto.java
> +            validateNumRange(nums.get(i));
헉 중괄호에도 컨벤션이 있는지 몰랐네요..! 😂
컨벤션 지켜 수정하겠습니다!

2021-02-22 05:23 UTC, xrabcde commented on src/main/java/lotto/domain/Lottos.java
> +    private static int count;
> Lottos가 money와 count를 계속 들고다닐 이유가 있을까요? 🤔

와... 정말 들고다닐 이유가 없었네요😂 😂

2021-02-22 05:37 UTC, xrabcde commented
안녕하세요 데이브! 
리뷰 반영하여 코드 수정해보았습니다.
피드백해주신 내용 참고하였더니 코드가 훨씬 깔끔해진 것 같아요! 
꼼꼼한 리뷰 감사드립니다 😊

2021-02-22 16:33 UTC, dave915 approved these changes
바다 피드백 반영 확인했습니다! 
코멘트 몇개 남겼으니 다음단계 진행하면서 반영해보세요!

2021-02-22 16:33 UTC, dave915 commented on src/main/java/lotto/domain/Rank.java
> +        }
Rank에서 아래처럼 보너스볼 체크 여부도 갖고있으면 이부분도 없앨 수 있지 않을까요? 
```
    FIFTH(3, false, 5000),
    FOURTH(4, true, 50000),
```

2021-02-22 16:33 UTC, dave915 commented on src/main/java/lotto/domain/Rank.java
> +    FIFTH(3, 5000),
https://countryxide.tistory.com/52
```suggestion
    FIFTH(3, 5_000),
```

2021-02-22 16:33 UTC, dave915 commented on src/main/java/lotto/domain/BonusBall.java
> +        if (bonusBall < 1 || bonusBall > 45) {
여기도 매직넘버가 있네요!

2021-02-22 16:33 UTC, dave915 commented on src/test/java/lotto/domain/LottoTest.java
> +        ArrayList<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));
아래 링크 읽어보시면 좋을 것 같아요 :) 

https://crazythink.github.io/2019/02/13/Fixture/

2021-02-22 16:33 UTC, dave915 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> lottoNumbers;
LottoNumber를 만들어서 List<LottoNumber> 로 변경해보면 어떨까요? 
BonusBall 의 매직넘버 문제도 해결될 수 있지 않을까 싶어요 😁

2021-02-22 16:33 UTC, merged