[1단계 - 로또 구현] 시드(김현식) 미션 제출합니다.
woowacourse/java-lotto pull request #266
Opened 2021-02-18 09:08 UTC by hsik0225

2021-02-20 02:12 UTC, wbluke requested changes
안녕하세요 시드! 로또 미션 리뷰를 맡은 닉입니다 🙇 
1단계 미션 잘 구현해주셨어요 ㅎㅎ
코멘트에도 남겼지만, MVC 구조와 부족한 테스트에 대해서 한번 체크해주세요 ㅎㅎ
수정 후 재요청 부탁드려요! 🙂

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/LottoMachine.java
> +    }
공백 라인도 의미를 가져요ㅎㅎ
문맥에 맞게 라인을 나눠보는 연습을 하면 좋겠어요 :)

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/LottoMachine.java
> +    private final OutputView outputView;
LottoMachine은 도메인 객체인데, View 객체를 직접적으로 가지고 있네요.
(LottoMachine의 역할에도 맞지 않아보여요 ㅎㅎ)
Controller 쪽에서 풀어보면 어떨까요? :)

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/LottoMachine.java
> +        Lottos lottos = Lottos.makeLottos(purchaseCount);
PaymentAmount가 있는데 다시 꺼내는 이유는 뭔가요?
꼭 필요한 순간에 getter를 사용하는 것이 좋습니다 :)

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/domain/Lottos.java
> +    public static Lottos makeLottos(int payCount) {
Lottos가 payCount 수만큼 Lotto를 생성해야하는 책임을 가지는 것에 대해 고민해보면 좋겠네요 ㅎㅎ
Lottos는 Lotto 리스트를 가공하는 역할만을 가지는 일급컬렉션으로 두고, 생성에 대한 책임은 다른 객체로 분리해보면 어떨까요? :)

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/domain/Lottos.java
> +    public List<List<Integer>> toInts() {
List 내의 List 구조는 복잡도가 높아서, 사용하는 클라이언트 쪽에서 추가 가공을 해야할 것 같아요.
다른 방식으로 풀어낼 수는 없을까요? :)

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/domain/WinningLotto.java
> +        return new WinningLotto(Lotto.fromNumbers(numbers), bonusNumber);
lotto에 bonusNumber가 포함된 경우에 대한 예외 처리가 있으면 좋겠네요 :)

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/domain/Rank.java
> +        }
이 부분이 조금 이상한데요. 보너스볼은 matchCount와 무관한 정보인데, 한번 확인해주세요 :)

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/domain/RankComparator.java
> +    INSTANCE;
Rank에 대한 비교 책임은 Rank에서 담당해도 되지 않을까요? :)

2021-02-20 02:12 UTC, wbluke commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
테스트가 없는 것 같은데요, 전체적으로 빠진 테스트가 없는지 체크해주세요! 
처음 구현할 때 TDD로 진행해보면 좋겠네요 :)

2021-02-21 22:59 UTC, hsik0225 commented
# 학습로그
## [JDK] Enum - 5
### 내용
- enum이 Comparable#compareT()를 오버라이드 하지 못하는 이유가 궁금해서 공부 시작. enum에 대해 전반적으로 학습

### 링크
- https://hsik0225.github.io/java/Enum/

## [JDK] Comparator & Comparable - 3
### 내용
- Comparator와 Comparable를 잘 몰라서 공부 시작

### 링크
- https://hsik0225.github.io/java/ComparatorVsComparable/

2021-02-21 23:50 UTC, hsik0225 commented
안녕하세요 닉!
이번 리뷰에서 전달받은 피드백을 적용했습니다.
혹시 잘못된 부분이 있다면 알려주세요 😃

### 피드백 적용 사항
- 문맥에 맞게 공백 수정
- Application을 Controller로 수정. View가 Application과 연결이 되도록 함
- PaymentAmount에서 Getter로 꺼낸 값을 매개변수로 전달해주는 것이 아닌 PaymentAmount를 매개변수로 전달
- Lotto의 생성 책임을 Lottos에서 새로운 클래스 LottoFactory로 이동
- Lotto#List<List<Integer>> toInts()가 아닌 Lottos#getLotto()로 변경하여, 클라이언트가 가공을 하도록 수정
- Lotto에 BonusNumber가 포함된 경우 예외 처리
- Rank에 대한 비교 책임을 Rank가 갖도록 수정
- Rank#searchRank() 테스트 코드 작성

### 변경 사항
- Lottos가 LottoStatisticResult를 생성할 때, Map 구현체를 EnumMap으로 설정
- Rank의 Comparator를 Comparator의 디폴트 메소드를 이용하여 작성

### 그 외
- 보너스볼은 matchCount와 연관된 정보라고 생각해 수정하지 않았습니다.
보너스 넘버와 로또 숫자가 일치하면 matchCount가 1 증가합니다. 

예를 들어, 로또 숫자가 1,2,3,4,5,45이고, 보너스 넘버가 5이며, 당첨 로또 번호가 1,2,3,4,34,35이면, 일치하는 개수는 5개이어야 합니다. 즉, 일치 개수는 로또 숫자 [1,2,3,4,5,45] 6개와 당첨 로또 번호와 보너스 넘버[1,2,3,4,5,34,35] 7개를 비교해서 도출해야 한다고 생각합니다.

2021-02-22 03:07 UTC, wbluke approved these changes
DM으로 이야기한 내용 잘 반영해주셔서 감사해요 👍 
추가적으로 간단한 코멘트와, 보너스볼 정책에 대한 부분 남겼는데요!
참고해서 다음 단계와 같이 진행해주세요 🙂

2021-02-22 03:07 UTC, wbluke commented on src/main/java/lotto/Application.java
> +        outputView.printStatistic(result);
같이 고민해주셔서 감사합니다 💯 
(아시겠지만) 참고로 main이 항상 Controller 역할을 할 필요는 없구요, 별도의 Controller 객체를 만들어도 됩니다 :)

```java
public class Application {
    public static void main(String[] args) {
        LottoController lottoController = new LottoController();
        lottoController.run();
    }
}
```

2021-02-22 03:07 UTC, wbluke commented on src/main/java/lotto/Application.java
> +        List<Integer> lotto = inputView.readWinningLotto();
Integer가 아니라 LottoNumber여도 될 것 같네요 :)

2021-02-22 03:07 UTC, wbluke commented on src/main/java/lotto/domain/LottoFactory.java
> +                                   .collect(Collectors.toList());
stream 들여쓰기 컨벤션에 대해서 고민해보시면 좋겠는데요.
IDE의 자동정렬 기능을 사용하는 것이 가장 좋습니다.
(mac 기준) Option + Cmd + L 을 누르면 기본 컨벤션에 맞게 자동 정렬이 됩니다. (사용하지 않는 import도 정리가 됩니다)
특정 패키지를 클릭한 후 단축키를 눌러서 모든 파일을 한꺼번에 정렬할 수 있으니 참고해주세요 :)

2021-02-22 03:07 UTC, wbluke commented on src/main/java/lotto/domain/Lotto.java
위 부분이 안보여서 여기에 남겨요.
matchesLength() : boolean 반환 메서드에 `!` 부정 연산자를 적용하는건 가독성이 떨어져서요, 
메서드 내에서 부정의 의미를 다 해결해주는 것이 좋습니다 :)

2021-02-22 03:07 UTC, wbluke commented on src/main/java/lotto/view/OutputView.java
>      private static final String VIEW_OF_INCOME_RATE = "총 수익률은 %.2f입니다.";
필드를 선언할 때도 공백 라인에 의미를 부여해서 종류별로 잘 나눠주면 좋을 것 같아요 ㅎㅎ
매번 줄바꿈을 한다면 필드가 많아질수록 파일이 엄청 길어지겠네요 :)

2021-02-22 03:07 UTC, wbluke commented on src/main/java/lotto/domain/Rank.java
>      private final int matchCount;
> 보너스볼은 matchCount와 연관된 정보라고 생각해 수정하지 않았습니다.
보너스 넘버와 로또 숫자가 일치하면 matchCount가 1 증가합니다.
> 
> 예를 들어, 로또 숫자가 1,2,3,4,5,45이고, 보너스 넘버가 5이며, 당첨 로또 번호가 1,2,3,4,34,35이면, 일치하는 개수는 5개이어야 합니다. 즉, 일치 개수는 로또 숫자 [1,2,3,4,5,45] 6개와 당첨 로또 번호와 보너스 넘버[1,2,3,4,5,34,35] 7개를 비교해서 도출해야 한다고 생각합니다.

음 실제 로또 규칙을 한번 검색해보시면 좋을 것 같은데요.
보너스볼은 2등과 3등을 구별할 때만 사용되고, 나머지 등수에서는 효력이 없는 번호입니다.
참고해서 다시 수정 부탁드려요 :)

2021-02-22 03:07 UTC, merged