[로또] 로비 미션 제출합니다.
woowacourse/java-lotto pull request #27
Opened 2019-06-01 07:43 UTC by kangmin46

브라운 코치님 잘 부탁드립니다~

2019-06-06 02:09 UTC, gracefulBrown requested changes
안녕하세요. 리뷰어 브라운입니다.
구현하느라 고생하셨습니다ㅎㅎ Exception분리도 잘하셨고 enum사용도 잘 하셨어요 👍 
별도의 팩토리 클래스를 통해서 객체를 생성하는 경향이 있는것 같아요ㅎㅎ
몇가지 코멘트 남겼으니 확인해주세요 ^^
궁금한점 있으면 언제든 DM주세요~

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/controller/ConsoleUILottoApplication.java
> +        Lottoes lottoes = createLottoes(customLottoCount,customLottoNumbersInput,money); // ConsoleUILottoApplication -> createLottoes
Reformat Code 로 띄어쓰기 컨벤션을 지켜보세요~

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoFactory.java
> +                    return Arrays.stream(s.split(","))
1. 혹시 여러줄이라서 return을 명시해주었나요? 반드시 return을 해줄 필요는 없습니다 :)
```.map(s -> Arrays.stream(s.split(",")).collect(Collectors.toList()))```

2. Stream을 열지 않아도 될 것 같습니다
``` .map(s -> Arrays.asList(s.split(","))) ```

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoFactory.java
> +    public static Lottoes createLottoes(String[] customLottoNumbersInput,Money money) {
수동생성과 자동새성 메서드를 분리할 수 있을까요?

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoFactory.java
> +    public static Lotto createLotto(List<String> winningNumberInput) {
당첨번호를 만들때만 해당 메서드를 사용하는 것이 아닌 것 같은데 파라미터명을 좀 더 고민해보면 좋을 것 같아요 :)

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final List<LottoNumber> lottoNumbers = new ArrayList<>();
여러 번 사용되는 LottoNumber를 static 변수로 만들었네요 !
lottoNumbers에 대해서 고민을 많이 한 것 같아요 👍

lottoNumbers가 현재 LottoNumber 내부에 위치하고 있는데 이 점에 대해서는 어떻게 생각하세요?
어쩌면 LottoFactory의 역할이 Lotto를 생성해주는 것이 아니라 LottoNumber를 할당해주는 것 일 수도 있겠네요ㅎㅎ

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoNumber.java
> +                .collect(Collectors.toList())
혹시 .. Stream이 꼭 필요할까요?
```List<LottoNumber> autoLottoNumbers = new ArrayList<>(lottoNumbers)```

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoNumber.java
> +                .subList(LOTTO_NUMBER_START_INDEX, LOTTO_NUMBER_END_INDEX);
ArrayList의 subList를 호출 할 경우 새로 List가 생성이 되네요
```
/**
     * Returns a view of the portion of this list between the specified
     * {@code fromIndex}, inclusive, and {@code toIndex}, exclusive.  (If
     * {@code fromIndex} and {@code toIndex} are equal, the returned list is
     * empty.)  The returned list is backed by this list, so non-structural
     * changes in the returned list are reflected in this list, and vice-versa.
     * The returned list supports all of the optional list operations.
     *
     * <p>This method eliminates the need for explicit range operations (of
     * the sort that commonly exist for arrays).  Any operation that expects
     * a list can be used as a range operation by passing a subList view
     * instead of a whole list.  For example, the following idiom
     * removes a range of elements from a list:
     * <pre>
     *      list.subList(from, to).clear();
     * </pre>
     * Similar idioms may be constructed for {@link #indexOf(Object)} and
     * {@link #lastIndexOf(Object)}, and all of the algorithms in the
     * {@link Collections} class can be applied to a subList.
     *
     * <p>The semantics of the list returned by this method become undefined if
     * the backing list (i.e., this list) is <i>structurally modified</i> in
     * any way other than via the returned list.  (Structural modifications are
     * those that change the size of this list, or otherwise perturb it in such
     * a fashion that iterations in progress may yield incorrect results.)
     *
     * @throws IndexOutOfBoundsException {@inheritDoc}
     * @throws IllegalArgumentException {@inheritDoc}
     */
    public List<E> subList(int fromIndex, int toIndex) {
        subListRangeCheck(fromIndex, toIndex, size);
        return new SubList(this, 0, fromIndex, toIndex);
    }
```
새로 List를 생성해주지 않아도 될 것 같습니다 :)

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/domain/CustomLottoCountFactory.java
> +public class CustomLottoCountFactory {
하는 역할이 없는 것 같은데... 없어도 되지 않을까요?

2019-06-06 02:09 UTC, gracefulBrown commented on src/main/java/lotto/domain/WinningLotto.java
> +        return lotto.toString()+"\n"+"보너스볼 : "+bonusBall;
도메인에 출력 정보가 있으면 도메인이 출력에 종속되는데요, 분리를 시켜주면 어떨까요?

2019-06-07 05:43 UTC, kangmin46 commented on src/main/java/lotto/domain/LottoNumber.java
> +                .subList(LOTTO_NUMBER_START_INDEX, LOTTO_NUMBER_END_INDEX);
List<LottoNumber> autoLottoNumbers = new ArrayList<>(lottoNumbers)
                .subList(LOTTO_NUMBER_START_INDEX, LOTTO_NUMBER_END_INDEX);
에서의 subList와  

List<LottoNumber> autoLottoNumbers = lottoNumbers.subList(LOTTO_NUMBER_START_INDEX,LOTTO_NUMBER_END_INDEX);
의 subList가 차이가 있군요!

2019-06-07 05:46 UTC, kangmin46 commented on src/main/java/lotto/domain/CustomLottoCountFactory.java
> +public class CustomLottoCountFactory {
CustomLottoCount 라는 객체를 생성해주는 역할을 하려고 넣게되었습니다.
사실 value Object를 생성하는 팩토리를 일일이 따로 만들어줘야 할까? 에대한 고민도 조금 했었어요.
그렇게 되면 팩토리가 점점 많아지게 되니까요. 
브라운 코치님의 의견이 궁금합니다!

2019-06-07 05:49 UTC, kangmin46 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final List<LottoNumber> lottoNumbers = new ArrayList<>();
저도 정확하게 그 고민을 했었는데 역시나 언급을 해주셨네요. 
LottoNumber안에 저는 LottoNumbers가 들어가있는 형태라서 어울리지 않는것이 아닐까? 하고
생각을 했었습니다. 
그래서 LottoNumbers 에 대한 클래스를 따로 만들까에 대한 생각도 했었는데 이번에 한번 만들어 보겠습니다!

2019-06-07 06:02 UTC, kangmin46 commented on src/main/java/lotto/domain/WinningLotto.java
> +        return lotto.toString()+"\n"+"보너스볼 : "+bonusBall;
출력을 테스트하는 과정에서 생성한 코드인데 빠뜨리고 수정을 안했었네요 ㅠ 
역시 꼼꼼하십니다..

2019-06-08 08:11 UTC, gracefulBrown commented on src/main/java/lotto/domain/CustomLottoCountFactory.java
> +public class CustomLottoCountFactory {
제 개인적인 취향은 팩토리(creator)를 만들지 않는 방법을 선호합니다만.. 취향입니다ㅎㅎ

2019-06-08 08:56 UTC, gracefulBrown approved these changes
수고하셨습니다!
Factory클래스와 Validation클래스를 별도로 분리하기 보다는
도메인과 관련된 기능이라면 도메인으로 옮겨오는걸 고민해보는건 어떨까요?ㅎㅎ
이어서 웹 미션도 화이팅입니다. 👍

2019-06-08 08:56 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final List<LottoNumber> lottoNumbers = new ArrayList<>();
LottoNuber를 미리 생성해 놓고 담아두는 클래스를 하나 만들면되지않을까요??
(질문이 이게 맞나요??ㅎㅎ;;)

2019-06-08 08:56 UTC, gracefulBrown commented on src/main/java/lotto/controller/ConsoleUILottoApplication.java
> +        // ConsoleUILottoApplication -> createCustomLottoCount
주석이 많네요 :)
메서드를 분리하여 주석의 일을 대신해주고 있다면 주석은 제거하는게 어떨까요?

2019-06-08 08:56 UTC, gracefulBrown commented on src/main/java/lotto/domain/Lottoes.java
> +                .map(l -> {
저는 스트림 사용 시 한 줄 씩 해놓는게 가독성이 좋더라구요 :)
```
        return lottoes.stream()
                .map(l -> Rank.valueOf(winningLotto.getMatchCount(l),winningLotto.isMatchBonus(l)))
                .collect(Collectors.toList());
```

2019-06-08 08:56 UTC, gracefulBrown commented on src/main/java/lotto/InputValidator.java
> +    private static boolean isNotValidPriceRange(String price) {
Money의 속성으로 볼 수 있는 로직 같아서 Money 내부로 옮겨도 좋을 것 같아요.

2019-06-08 08:56 UTC, gracefulBrown commented on src/main/java/lotto/InputValidator.java
> +public class InputValidator {
도메인이 가지고 있는 속성이 유효성검사를 하는 로직이라면
별도로 분리하기 보다는 도메인이 가지고 있는게 좋을 것 같아요 :)

2019-06-08 08:56 UTC, gracefulBrown commented on src/main/java/lotto/Exception/duplicateBonusBallException.java
> +public class duplicateBonusBallException extends RuntimeException {
실수겠지만.. 클래스 네이밍!!

2019-06-08 08:56 UTC, merged