[로또] 마틴 미션 제출합니다.
woowacourse/java-lotto pull request #28
Opened 2019-06-01 11:36 UTC by oeeen

인터페이스와 전략 패턴을 사용해보려고 노력했습니다만, 괜히 디자인 패턴에 끌려다닌 것 같습니다.
잘 부탁 드립니다.

2019-06-06 03:42 UTC, gracefulBrown requested changes
안녕하세요. 리뷰어 브라운입니다.
인터페이스를 잘 사용해주셨는데요, 만든 인터페이스를 잘 이용하면 중복코드도 줄일 수 있고
코드 가독성 증가 및 유연하게 구현할 수 있을 것 같습니다 :)
관련해서 코멘트를 남겨놨는데요~ 궁금한점 있으면 언제든 DM주세요 :)

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +
의미를 가지고 라인을 나누면 가독성이 조금 더 좋아질꺼에요 :)

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/domain/generator/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
현재 구조상으로는 LottoNumberGenerator interface를 구현하지 않아도 잘 동작하는 것 같은데요
interface를 사용한 특별한 이유가 있나요?

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoContainer.java
> +    private static final List<LottoNumber> lottoNumbers = new ArrayList<>();
재사용되는 로또번호 👍

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +        } catch (IllegalArgumentException e2) {
e1, e2를 구분한 이유가 있나요?

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoMoney.java
> +            throw new IllegalArgumentException(MAX_PURCHASE_PRICE + UPPER_PRICE_MESSAGE);
MAX_PURCHASE_PRICE인 경우 출력되는 에러메시지가 의도된 것인가요?
```
구입금액을 입력해 주세요.
1111111111111111
숫자만 입력해주세요.
```

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/domain/NumberRandomShuffle.java
> +    public List<LottoNumber> shuffle(List<LottoNumber> lottoNumbers) {
static으로 하면 객체를 생성하지 않아도 될 것 같아요 :)

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/domain/NumberShuffle.java
> +public interface NumberShuffle {
인터페이스 만든 이유가 있나요?

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/domain/Rank.java
> +    FIRST(6, 2_000_000_000), // 1등
언더바로 구분 👍

2019-06-06 03:42 UTC, gracefulBrown commented on src/main/java/lotto/domain/Lottos.java
> +    private void generateRandomLottos(int randomLottoCount) {
generateManualLottos과 generateRandomLottos의 로직을 만든 LottoNumberGenerator 인터페이스를 이용하면
좀 더 유연한 코드가 될 수 있지 않을까요?ㅎㅎ

2019-06-06 06:12 UTC, oeeen commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +        } catch (IllegalArgumentException e2) {
숫자 입력하는 부분에서 숫자가 아닌것이 들어오는 부분과 다른 예외처리부분(1~45 범위 밖의 숫자, 1000원 이하의 구매금액 등)을 나눠서 처리하려고 했습니다.
현재는 단순히 메시지 출력 후 끝나는 구조여서 굳이 나눈 것이 큰 의미는 없지만 예외처리는 예상 할 수 있는 범위라면 나누어서 처리하는 것이 좋지 않을까? 하는 생각으로 나누었습니다. (현재 IllegalArgumentException 으로 퉁쳐서 다른 예외를 한꺼번에 받고 있습니다만.. 일관성 있게 작성하려면 한번에 퉁쳐서 받는 부분도 작게 나누어야 할 것 같습니다.)

2019-06-06 06:20 UTC, gracefulBrown commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +        } catch (IllegalArgumentException e2) {
그렇군요! 혹시 e1과 e2대신 둘다 exception이나 e라고 해주면 어떨까요?
번호로 구분한 이유가 있는것 같아서 물어봤습니다 ㅎㅎ;;

2019-06-06 06:30 UTC, oeeen commented on src/main/java/lotto/domain/LottoMoney.java
> +            throw new IllegalArgumentException(MAX_PURCHASE_PRICE + UPPER_PRICE_MESSAGE);
Integer 범위(~2,147,483,647)를 넘어가는 Input이 들어오면 parseInt에서 NumberFormatException으로 빠지는데 의도한 예외는 아닙니다.
범위를 조금 늘리기 위해서 int형에서 long 자료형으로 변경 했습니다만, 이 경우에도 결국에는 long 범위 (~9,223,372,036,854,775,807) 를 넘어가면 동일한 문제가 생깁니다. 그래서 메시지를 변경했습니다.

2019-06-06 07:10 UTC, oeeen commented on src/main/java/lotto/domain/NumberShuffle.java
> +public interface NumberShuffle {
제가 생각하기에는 현재 Lotto 미션에서는 사용해야하는 이유가 없습니다.
Strategy pattern을 이해하기 위해 사용해보자. 라는 느낌으로 만들어보았습니다.
Lotto 미션에서 억지로 활용해본다면, 전체 랜덤으로 로또 번호를 받는 것이 아니라 다른 섞는 조건(홀수중에 랜덤, 짝수중에 랜덤 등)을 추가해서 활용 해볼 수 있을 것 같습니다.
```java
public class OddNumberRandomShuffle implements NumberShuffle {
    private static final int LOTTO_FROM_INDEX = 0;
    private static final int LOTTO_TO_INDEX = 6;

    @Override
    public List<LottoNumber> shuffle(List<LottoNumber> lottoNumbers) {
        List<LottoNumber> oddLottoNumbers = new ArrayList<>();
        for (int i = 0; i < lottoNumbers.size(); i+=2) {
            oddLottoNumbers.add(lottoNumbers.get(i));
        }
        Collections.shuffle(oddLottoNumbers);
        return oddLottoNumbers.subList(LOTTO_FROM_INDEX, LOTTO_TO_INDEX);
    }
}
```
홀수 중에 랜덤으로 섞는 것이 필요하다면 위와 같은 활용으로 사용할 수도 있을 것 같습니다. 계속해서 섞는 조건들이 추가 된다면 섞는 조건을 위한 클래스를 만들어주고, 그 조건을 사용하면서 LottoNumberGenerator를 상속받는 클래스들을 만들어 주면 확장성에 도움이 될 것 같습니다.

디자인 패턴을 공부한다고 억지로 적용하게 되면서 '쓰다보니 이게 좋다' 라며 쓰는 것이 아니라 '이걸 꼭 써봐야해!' 라는 느낌으로 쓰다보니 조금 억지스럽게 사용하게 된 것 같습니다.

2019-06-06 10:20 UTC, oeeen commented on src/main/java/lotto/domain/generator/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
처음에는 인터페이스를 배웠으니 인터페이스를 써봐야겠다 라는 생각에 사용했습니다.

Random과 Manual number generator에서 동일하게 로또 숫자 생성을 해줘야 하는데, 내부 로직은 다르지만 숫자리스트를 생성해준다는 것(리턴타입과 파라미터)은 동일하기 때문에 인터페이스로 따로 빼봤습니다. 
아래 코멘트 달아주신대로 하위 구현체들 사용하는데 유연성 있게 사용해야 하는데 현재 구조에서는 Random과 Manual의 필요한 정보들이 달라서 지금은 또 따로 라우팅 해줘야하는 단계가 생기게 될 것 같습니다. 
그래서 interface로 나눴던 부분을 빼버리고 Random, Manual Generator 각각 구현하도록 변경했습니다.

2019-06-06 10:25 UTC, oeeen commented
안녕하세요!
전략패턴을 사용해보자 라는 의도로 코드를 짜다보니 굳이 쓰지 않아도 되는 인터페이스의 사용이 좀 생겼던 것 같습니다!
써보면서 조금 더 전략패턴에 대한 이해를 하게 되었고, 고친 코드에서는 사용하지 않는 것으로 변경했습니다!
아직 객체지향적인 사고가 잘 안돼서 인터페이스 활용이 어렵네요;

도움을 주셔서 감사합니다!

2019-06-06 10:39 UTC, oeeen commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +
나름의 기준으로 라인을 구분했는데, 가독성이 떨어지는 것 같네요.
1. 구입 금액 처리
2. 수동 구매 처리 (입력 받고 생성)
3. 자동 구매 후 전체 로또 목록
4. 당첨 번호 처리
5. 최종 결과 출력

어떤 기준으로 나누어야 가독성이 올라갈 수 있을까요?
사용자 입력을 그대로 받아서 컨트롤러가 각 도메인 객체 생성을 해야 한다고 생각 해서 현재 구조에서 수정을 어떻게 해야 가독성이 올라갈까 하는 생각이 떠오르지가 않아서 변경을 못했습니다ㅠ

2019-06-08 08:08 UTC, gracefulBrown approved these changes
패턴을 사용하고자 하는 노력 좋습니다! 
패턴의 목적과 의도를 한번에 이해 하기란 쉬운일이 아니니까요ㅎㅎ
다음번에는 단순히 패턴의 형태만 적용해보기 보다는 패턴 사용 목적에 맞는 경우에 사용해보는 노력을 해보면 좋을 것 같아요 :) 고생하셨습니다 :)

2019-06-08 08:08 UTC, gracefulBrown commented on src/main/java/lotto/ConsoleUILottoApplication.java
> +
15\~17라인이 한 묶음, 19\~22라인이 한 묶음 24~26라인이 한 묶음 처럼 보이네요ㅎㅎ
코멘트의 의도는 2줄 띄워쓰기가 의도가 있는것인지 물어보기 위함이였습니다ㅎㅎ

추가적으로 말씀드리면 라인을 잘 나누면 메서드 분리할 포인트가 발견 되기도 합니다ㅎㅎ

2019-06-08 08:08 UTC, gracefulBrown commented on src/main/java/lotto/domain/Lotto.java
> +        return "["
도메인에 출력 포맷이 정의되어있으면 뷰에 종속됩니다ㅠ
뷰가 변경되어도 도메인은 변경되지 않도록 고민해보세요 ^^

2019-06-08 08:08 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoMoney.java
> +        return (int) (this.purchasePrice % LOTTO_PRICE);
OutputView에서 필요한 대로 형변환 하여 출력하도록 하면 어떨까요?

2019-06-08 08:08 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoResult.java
> +            rank = winningLotto.getCountOfMatch(lottos.getLottoByIndex(i));
```Rank rank = winningLotto.getCountOfMatch(lottos.getLottoByIndex(i));```
로 해도 좋습니다 :)

2019-06-08 08:08 UTC, merged