[2단계 - 로또 구현] 제리(박재성) 미션 제출합니다.
woowacourse/java-lotto pull request #284
Opened 2021-02-22 00:26 UTC by jaeseongDev

안녕하세요, 고래🐳
궁금한 점에 대해서 자세하고 이해하기 쉽게 이해해주셔서 빠르게 피드백을 반영할 수 있었어요!!
혹시나 코드 보시고 또 고칠 부분이나 개선할 부분 있으면 언제든 가감없이 피드백 해주세요:)
귀중한 시간 내주셔서 감사합니다^^

2021-02-22 00:28 UTC, jaeseongDev commented
# 객체를 편하게 만들기 위해, 생성자(or 정적 팩토리 메소드)는 여러개 만들어도 괜찮다. - 3

## 예 1)

### **객체를 여러번 포장해야 된다면, 생성자를 그냥 여러 개 만들어서 편하게 객체를 생성할 수 있도록 만들어라.**

```java
public class Lotto {

    private static final int LOTTO_LENGTH = 6;

    private final Set<LottoNumber> lottoNumbers;

    private Lotto(Set<LottoNumber> lottoNumbers) {
        this.lottoNumbers = lottoNumbers;
    }

    public static Lotto fromGenerator(LottoNumberGenerator generator) {
        return fromLottoNumbers()mapIntToLottoNumber(generator.generateNumbers());
    }

    public static Lotto fromNumbers(List<Integer> numbers) {
        return fromLottoNumbers(mapIntToLottoNumber(numbers));
    }

    public static Lotto fromLottoNumbers(Set<LottoNumber> lottoNumbers) {
        if (!matchesLength(lottoNumbers.size())) {
            throw new IllegalArgumentException();
        }

        return new Lotto(lottoNumbers);
    }

    private static boolean matchesLength(int size) {
        return size == LOTTO_LENGTH;
    }

    private static Set<LottoNumber> mapIntToLottoNumber(List<Integer> numbers) {
        return numbers.stream()
                      .map(LottoNumber::from)
                      .collect(Collectors.toSet());
    }
}
```

## 예 2)

### 비효율적인 코드

```java
public class Car {
    private final Name name;

    public Car(Name name) {
        this.name = name;
    }

    public static Car from(Name name) {
        return new Car(name);
    }
}
```

```java
public class Main {
  public static void main(String[] args) {
    Car car = Car.from(new Name("json")); // Car 객체 생성
  }
}
```

Car 객체를 생성할 때 코드가 복잡하다. 

### 개선된 코드

```
public class Car {
    private final Name name;

    public Car(Name name) {
        this.name = name;
    }

    public static Car from(**String name**) {
        return new Car(**new Name(name)**);
    }
}
```

```java
public class Main {
  public static void main(String[] args) {
    Car car = **Car.from("json");** // Car 객체 생성
  }
}
```

사용자가 Car에 대한 객체를 생성할 때, 사용하기 편하도록(코드가 간결하도록) 생성자를 만들었다. 이로 인해 Car에 대한 객체를 생성하기가 쉬워졌다. 

## 예 3)

[[1단계 - 로또 구현] 제리(박재성) 미션 제출합니다. by jaeseongDev · Pull Request #264 · woowacourse/java-lotto](https://github.com/woowacourse/java-lotto/pull/264#)

### View에서만 사용하기 위한 객체 생성 코드는 만들지 마라.

View에서만 사용하기 위한 객체 생성 코드는 만들지 마라. 왜냐하면 MVC에 따르면 Model이 View가 하는 일에 간섭을 할 필요가 없기 때문이다. 

### **테스트 코드에서만 사용되는 객체 생성 코드는 되도록이면 만들지 마라.**

도메인의 영역에서 객체를 생성할 때 조금 더 편하게 생성하기 위해서 다양한 생성자나 정적 팩토리 메서드를 추가로 만들어도 되지만, 테스트 코드에서만 사용되는 생성자나 정적 팩토리 메서드를 만드는 것은 최대한 자제해라. 

그래도 정 불편하다고 느껴지면, 테스트 코드에 생성자나 정적 팩토리 메서드를 추가해서 사용해라.

2021-02-22 00:30 UTC, jaeseongDev commented
# MVC 패턴 - 4

# MVC는 왜 생겨난걸까?

**(MVC가 생겨나게 된 배경가 이유를 알게 되면, MVC의 핵심을 파악할 수 있게 된다.)**

과거의 많은 사람들이 코딩을 했었는데 코드가 많아지면 많아질수록 코드가 복잡해졌다. 코드를 복잡한 채로 놔두니 나중에 기능 수정 및 변경이 일어날 때마다 코드를 파악하기도 힘들고, 어떤 기능을 살짝 수정하려고 했는데 대부분의 코드를 수정해야 하는 경우가 빈번했다. 즉, **'유지보수'가 불편했다**. 그러다가 코딩을 잘하는 사람들이 코드를 짜다보니 효율적으로 코드를 구성할 수 있는 패턴들이 생겼었다. 여기서 **효율적으로 코드를 구성한다는 것은 '유지보수'가 편하다**는 뜻이다. 그래서 그 패턴을 하나의 '공식'처럼 만들어서 논문으로 발표하게 됐다. 그렇게 소프트웨어 설계자들 사이에서 유명한 패턴인 MVC가 탄생하게 됐다. 

요약하자면, **유지보수를 편하게 할 수 있는 패턴** 중 하나가 **MVC**인 것이다. 

# 유지보수가 편한 코드란?

유지보수가 편한 코드라는 뜻은, 특정 기능을 추가 및 변경할 때 가능한 한 최소한의 코드만을 수정해서 기능을 변경할 수 있음을 의미한다. 최소한의 코드만을 수정해서 기능을 변경하려면, 변하는 것과 변하지 않는 것을 분리해야 한다. SOLID, 전략 패턴, State 패턴, MVC 패턴 등 대부분의 디자인 패턴이 '변하는 것과 변하지 않는 것을 분리'해서 유지보수를 편하게 하려고 한다. 즉, '변하는 것과 변하지 않는 것을 분리'하는 것이 디자인 패턴의 핵심이다. 

# MVC 전체 구조 맛보기

MVC의 전체 구조를 웹에 비유해서 이해해보자. 

![image](https://user-images.githubusercontent.com/41244373/108622874-03e5ea00-747f-11eb-952a-99113f0f6658.png)

위의 예시를 일반화해서 정리하면, 사용자가 Controller를 조작하면, Controller는 Model에 명령을 보내고, Model이 View에 데이터를 전달하고, View가 전달받은 데이터를 바탕으로 시각적으로 표현을 한 후 사용자에게 전달한다.

# Model, View, Controller의 1줄 요약

- Model : 데이터
- View : 사용자한테 보여주는 부분 + 데이터
- Controller : Model과 View를 활용해 전체 로직을 작성하는 곳

# MVC를 지키려면...

****참고) A가 B에 의존하다. = A에 B에 관련된 코드가 있다.**

### Model

- **Model**은 Controller와 View에 의존하지 않아야한다. 
****(= Model 클래스 내부에 특정 Controller 클래스의 코드와 특정 View 클래스의 코드가 있으면 안 된다.)

### View

- **View**는 Model에만 의존해야하고, Controller에는 의존하면 안 된다.
(= View 클래스 내부에 Model 클래스의 코드만 있고, 특정 Controller 클래스의 코드가 있으면 안 된다.)
- **View**가 Model로부터 데이터를 받을 때에는 직접 받으면 안 되고, Controller를 통해서 받아야 한다.
- **View**가 Model로부터 데이터를 받을 때는, 사용자마다 다르게 보여주어야 하는 데이터에 대해서만 받는다.

### Controller

- **Controller**는 Model과 View에 의존한다. 
(= Controller 클래스 내부에 Model 클래스, Controller의 클래스의 코드가 있다.)
- **Controller**는 Model의 데이터를 받아서 View로 전달해주어야 한다.

## 예제

**Model**

```java
public class Student {
    private String name;
    private int age;

    public Student(String name, int age) {
        this.name = name;
        this.age = age;
    }
    
    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }
}
```

**View**

```java
public class OutputView {
    public void printProfile(Student student) {
        System.out.println(
            "내 이름은 " + student.getName() + "입니다.");
        System.out.println(
            "내 나이는 " + student.getAge() + "입니다.");
    }
}
```

**Controller**

```java
public class Controller {
    public static void main(String[] args) {
        Student student = new Student("기철", 25);
        OutputView.printProfile(student);
    }
}
```

**콘솔 결과**

![image](https://user-images.githubusercontent.com/41244373/108622886-1bbd6e00-747f-11eb-8ab2-60da843539de.png)

# MVC의 장점

Model, View, Controller가 분리되어 있어서, 내가 필요한 부분만 쉽게 찾아내거나 수정할 수 있게 된다. 예를 들면, 나이를 조회하는 `getAge()` 메서드에서 한국 나이 계산법에서 미국 나이의 계산법으로 바꾸고자 할 때, View와 Controller 부분은 신경쓰지 않고 수정이 필요한 Model의 코드만 수정하면 된다. 또한 데이터와 로직은 그대로 사용하는데, 사용자한테 보여주는 부분의 디자인을 변경하고자 할 때, Model과 Controller 부분의 코드를 건드리지 않고 View의 코드만 수정하면 되므로 훨씬 코드를 읽기도 쉽고 수정하기도 쉬워진다. 

# Q&A

### Q. MVC라는 개념이 백엔드에만 적용되는 개념인가요 ?

A. 소프트웨어를 설계하는 곳에 전반적으로 활용되는 개념이다. 

- 백엔드의 관점으로 봤을 때에는 Model을 데이터를 관리하는 데이터베이스, Controller를 사용자로부터 요청을 받아 로직을 처리하는 곳, View를 사용자의 요청에 대한 응답을 하는 곳이라고 생각할 수 있다.
- 프론트엔드의 관점으로 봤을 때에는 Model을 백엔드로부터 받은 데이터를 관리하는 곳, Controller를 사용자로부터 받은 이벤트들을 처리해서 Model과 View를 연결시켜주는 역할을 하는 곳, View를 HTML, CSS와 같이 사용자에게 보여주는 화면을 꾸미는 역할을 하는 곳이라고 생각할 수 있다.
- 백엔드, 프론트엔드를 통틀어서 봤을 때에는 백엔드가 Model과 Controller의 역할을 하고, 프론트엔드가 View의 역할을 한다고 볼 수 있다.

이와 같이 MVC는 여러 소프트웨어 설계 방식에 녹아들어져있다. 

### Q. MVC는 만능인가요 ?

A. MVC도 단점을 가지고 있다. Controller에 Model과 View의 코드가 모여있다보니, 프로젝트의 규모가 커지면서 Controller가 너무 비대해져서 복잡성이 증가한다. 이로 인해 유지 보수가 어려워지고 가독성이 떨어지게 된다. 이러한 문제점을 보완하기 위해 MVC 이외에 MVVM, MVP 등의 다양한 패턴들도 있다. 

어떤 아키텍처든 만능은 없다. 적재적소에 잘 활용하는 것이 중요하다. 극단적인 예로, 아주 적은 양의 코드만을 필요로 하는 프로그램이면서 한 번 쓰고 버릴 코드라면 MVC라는 패턴따위는 신경쓰지 않고 하나의 파일에 뭉터기로 코딩하는 것이 효율적인 방식일 것이다.

# References

- [세상에서 제일 쉬운 MVC 패턴](https://hodol.dev/journal/mvc-pattern/)
- [모델-뷰-컨트롤러](https://ko.wikipedia.org/wiki/%EB%AA%A8%EB%8D%B8-%EB%B7%B0-%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC)
- [MVC구조가 생겨난 계기, 이유가 뭔가요?](https://okky.kr/article/453210)
- [MVC, MVP, MVVM 무엇인가? :: 마이구미](https://mygumi.tistory.com/304)

2021-02-22 00:33 UTC, jaeseongDev commented
# 테스트 주도 개발의 Cycle - 3

# '테스트 주도 개발(TDD)' 전체 과정

## 1. 어떤 기능들을 추가해야 하는 지 파악하기 → 테스트 코드 리스트 작성

테스트 과정에서 새로운 테스트 사례를 발견하면 그 사례를 목록에 추가해서 놓치지 않도록 해야 한다. 당연한 얘기지만 처음부터 모든 사례를 정리하려면 시간도 오래 걸릴뿐더러 쉽지도 않다. 개발을 진행하다 보면 생각지도 못한 테스트 사례를 발견하기 마련이다. 이때 새로 발견한 내용을 테스트 목ㄹ혹에 추가해서 놓치지 말아야 한다. 

### **예시)**

왼쪽의 형태에서 오른쪽의 형태로 표현하기 위해 기능을 추가해야하는 상황이라고 가정하자. 즉, 1가지의 통화(돈의 종류)만 지원하다가 여러가지 통화를 제공할 수 있게 되었다. 

**참고)** CHF : USD = 2 : 1

**[테스트 리스트]**

- `$5 * 2 = $10`

    → 위의 예에서 `1000 * 25 = 25000`를 계산하는 로직은 이미 내장되어 있기 때문에 테스트 할 필요가 없지만, `1000 * 25USD = 25000USD`와 같이 통화 단위(USD)가 붙은 숫자를 계산하는 로직은 없기 때문에 테스트 코드를 추가해야 한다. 

- `$5 + 10CHF = $10`

    → 다른 통화들끼리 연산이 가능해야 하기 때문에 테스트 코드를 추가한다. 

> 한 번에 테스트 리스트를 다 적을 필요 없이, 또다른 테스트가 생각날 때마다 그때그때 추가하면 된다.

> **TDD**가 기존에 개발하던 방식과 다른 점은 새로 구현할 기능에 대해서 리스트를 작성하는 것이 아니라, '**새로 구현할 기능에 대해 테스트할 리스트'를 작성한다.** 즉, 구현할 기능에 집중하는 것이 아니라 **'구현할 테스트 코드'**에 집중하는 것이다.

## 2. 테스트 리스트 중 하나를 골라 테스트 코드 추가하기

**주의) 첫 번째 테스트를 선택할 때에는 '가장 구현하기 쉬운 것' 또는 '가장 예외적인 상황'을 선택해야 한다. 즉, 빠른 시간 내에 구현을 완료해서 테스트를 통과시킬 수 있을 만큼 쉬운 것을 선택해야 한다.**

**2.1. 클래스 이름 고민하기**

**2.2. 메서드 이름 고민하기**

**2.3. 메서드에서 사용할 파라미터 이름, 파라미터 타입, 리턴 타입 정하기**

### 예시)

`$5 * 2 = $10`의 테스트가 간단해보여서 먼저 추가하려고 한다.

> 구현하기 어려워 보이는 테스트 코드보다 간단해보이는 테스트 코드 먼저 추가해라.

```java
public void testMultiplication() {
		Dollar five = new Dollar(5);
		five.times(2);
		assertEquals(10, five.amount);
}
```

아무 것도 구현되지 않은 상태에서 위와 같이 테스트 코드를 먼저 작성하려면, 오퍼레이션의 완벽한 인터페이스에 대해 상상해야 한다. 그러고 상상한 인터페이스를 바탕으로 위와 같이 테스트 코드를 작성해야 한다.

하지만 위 코드에서는 밑과 같은 4가지 요인들 때문에 테스트 코드 조차 제대로 돌아가지 않는 컴파일 에러가 발생할 것이다. 

- Dollar 클래스가 없음 (`Dollar five`라는 코드에서 에러 발생)
- Dollar의 생성자가 없음 (`new Dollar(5)`라는 코드에서 에러 발생)
- times(int) 메서드가 없음 (`five.times(2)`라는 코드에서 에러 발생)
- amount 필드가 없음 (`five.amount`라는 코드에서 에러 발생)

## 3. 테스트 코드에서 발생하는 컴파일 에러 먼저 해결하기

**3.1. 컴파일만 될 수 있게 해주는 최소한의 구현만 하기 → 필요한 빈 클래스, 메서드, 변수 추가하기**

### 예시)

```java
public class Dollar {
    int amount;

    Dollar(int amount) {
    }

    void times(int multiplier) {
    }
}
```

## 4. 테스트 코드 빠르게 통과시키기 (=초록막대로 만들기)

> TDD의 핵심 중 하나가, 가능한 한 빠르게 초록 막대를 보는 것이다. 즉, 실행 가능하게 만드는 것이다. 깔끔하고 단순한 해법이 명백히 보인다면 바로 로직을 작성하면 되지만, 그렇지 않다면 **가짜로 구현하거나, 삼각측량 전략을 활용**해서라도 빠르게 초록 막대를 보자.

### 방법 1) 올바르게 작동하는 로직을 바로 작성하기

```java
public class Dollar {
    int amount;

    Dollar(int amount) {
        this.amount = amount;
    }

    void times(int multiplier) {
        amount = amount * multiplier;
    }
}
```

바로 정상적으로 구현할 로직이 바로 보인다면 빠르게 정상 로직을 작성하면 된다. 하지만 막상 로직을 작성해보면 단 번에 테스트를 통과하지 못하는 경우가 많이 나타난다. 이럴 때에는 한 번에 테스트를 통과시키려는 조급함을 내려놓고, 차근차근 테스트를 통과시키는 방법인 '가짜로 구현하기', '삼각 측량'을 활용해야 한다. 

이과 같이 로직의 난이도에 따라서 속도를 조절할 수 있어야 한다. 쉬운 난이도에서는 올바르게 작동하는 로직을 바로 작성하고, 어려운 난이도에서는 '가짜로 구현하기', '삼각 측량'을 활용해서 차근차근 테스트를 통과시키면서 로직을 작성해나가면 된다.

### 방법 2) 가짜로 구현하기

'가짜로 구현하기'의 방법은 상수를 반환하게 만들고 진짜 코드를 얻을 때까지 단계적으로 상수를 변수로 바꾸어가는 전략이다. 가짜 구현은 테스트가 잘못작성되었을때 빠르게 알아차릴 수 있으며, 자신이 어디를 가야하는지, 어디쯤 왔는지 알게 해주기 때문에 심리적인 확신을 준다. 

**과정 1**

```java
public class Dollar {
    int amount = 10;

    Dollar(int amount) {
    }

    void times(int multiplier) {
    }
}

```

올바른 로직은 아니지만, 테스트 코드는 통과하게 된다. 즉, 초록 막대를 볼 수 있게 되었다.

**과정 2**

```java
public class Dollar {
    int amount;

    Dollar(int amount) {
        this.amount = amount;
    }

    void times(int multiplier) {
        amount = amount * multiplier;
    }
}
```

올바르게 작동하도록 로직을 수정했다. 

### 방법 3) 삼각 측량 활용하기 (다양한 테스트 추가 ⇒ 가짜로 구현) 
→ 이를 바탕으로 로직 일반화하기

'삼각 측량' 방법은 예제를 2개 이상 활용해서 코드를 일반화하는 전략이다. 하지만 삼각측량은 어떻게 리팩토링해야 하는 지 전혀 감이 안 올 때에만 삼각측량을 사용한다. 왜냐하면 너무나도 쉽게 테스트를 통과시킬 로직이 보인다면 굳이 한 번만 하면 될 테스트를 두 번 이상 하면서까지 코드를 더 늘릴 필요가 없기 때문이다.

몇 차례 상수를 사용해서 테스트를 통과시키고 뒤에 구현을 일반화하는 과정이 처음에는 지루하게 느껴질 수 있다. 하지만 나중에 만들어야 할 코드가 잘 떠오르지 않을 때 점진적으로 구현을 진행할 수 있는 밑거름이 된다. 단순 덧셈이나 길이 비교와 같은 명백한 구현은 상수를 사용하지 않고 바로 구현하고 한 번에 구현을 시도했는데 잘 안 되면 한발 물러서서 천천히 단계를 밟아 나가면 된다. 

- **다른 예시**

## 5. 중복을 제거할 수 있는 부분이 있다면 리팩토링 하자.

```java
public class Dollar {
    int amount;

    Dollar(int amount) {
        this.amount = amount;
    }

    void times(int multiplier) {
        amount *= multiplier;
    }
}
```

> 최종 목표는 '작동하는 깔끔한 코드'를 얻는 것인데, 여기서 '작동하는'에 해당하는 문제를 먼저 해결해라. 그러고 나서 '깔끔한 코드' 부분을 해결해라.

# 테스트 해야 할 예외 사항

### 값이 없는 경우 (null인 경우, 빈 문자열인 경우)

값이 없는 경우(null, 빈 문자열)를 테스트 해야 한다. 특히 특정 메서드에 null을 전달하면 NullPopinterException의 에러가 발생하는 경우가 많다. 프로그램은 null에 대해서도 알맞게 동작해야 한다.

# 주의점

- **테스트를 통과시킬'만큼'의 코드를 작성한다.** 테스트를 통과하는 데 불필요한 코드는 절대 작성하지 마라. 미리 구현할 것이 떠올라도 미리 코드를 작성하지 마라.
- 코드를 추가하거나 수정할 때마다 매번 테스트에 통과하는 지 확인해라. 정말 **빈번하게 테스트에 통과하는 지를 체크**해야 한다.
- 테스트 코드도 코드이기 때문에 유지보수 대상이다. 즉 **테스트 메서드에서 발생하는 중복을 알맞게 제거**하거나 의미가 잘 드러나게 코드를 항상 리팩토링 해주어야 한다. 단, 테스트 코드의 중복을 무턱대고 제거하면 안 된다. 왜냐하면 각 테스트 메서드는 스스로 무엇을 테스트하는지 명확하게 설명할 수 있어야 하기 때문이다. 중복을 제거한 뒤에도 테스트 코드의 가독성이 떨어지지 않고 수정이 용이한 경우에만 중복을 제거해야 한다. 중복을 제거한 뒤에 오히려 테스트 코드 관리가 어려워진다면 제거했던 중복을 되돌려야 한다.
- 특정 기능에 대해 테스트 코드 구현을 완료한 뒤에 **리팩토링**을 진행한다. 리팩토링할 대상이 눈에 들어오면 리팩토링을 진행해서 코드를 정리한다. 당장 리팩토링할 대상이나 어떻게 리팩토링해야 할 지 생각나지 않으면 다음 테스트를 진행하면 된다.

    TDD를 진행하는 과정에서 지속적으로 리팩토링을 진행하면 코드 가독성이 높아진다. 코드 가독성이 높아지면 개발자는 더욱 빠르게 코드를 분석할 수 있어 수정 요청이 있을 때 변경할 코드를 빠르게 찾을 수 있다. 이는 코드 변경의 어려움을 줄여주어 향후 유지보수에 도움이 된다. 

- **테스트 대상 코드의 리팩토링 시점**은 다음과 같다. 테스트 대상 코드에서 상수를 변수로 바꾸거나 변수 이름을 변경하는 것과 같은 작은 리팩토링은 발견하면 바로 실행한다. 반면에 메서드 추출과 같이 메서드의 구조에 영향을 주는 리팩토링은 큰 틀에서 구현 흐름이 눈에 들어오기 시작한 뒤에 진행한다.

    구현 초기에는 아직 구현의 전반적인 흐름을 모르기 때문에 메서드 추출과 같은 리팩토링을 진행하면 코드 구조를 잘못 잡을 가능성이 있다. 코드 구조가 잘못되면 다음 테스트를 통과시키는 과정에서 코드가 복잡해지거나 구현을 더는 진행하지 못하고 막힐 수 있다. 이런 상황이 오면 구현을 멈추고 메서드 추출 리팩토링을 되돌려야 한다. 리팩토링을 취소해서 코드를 원상 복구한 뒹에 다음 테스트를 진행한다. 그런 뒤 코드의 의미나 구조가 더 명확해지면 그때 다시 리팩토링을 시도한다. 

    리팩토링을 통해 지속해서 코드를 정리하는데 개발을 진행하다 보면 변경 범위가 매우 큰 리팩토링 거리를 발견할 때도 있다. 변경 범위가 큰 리팩토링은 시간이 오래 걸리므로 TDD 흐름을 깨기 쉽다. 이때는 리팩토링을 진행하지 말고 테스트를 통과시키는 데 집중한다. 대신 범위가 큰 리팩토링은 다음 할 일 목록에 추가해서 놓치지 않고 진행할 수 있게 한다. 

- 범위가 큰 리팩토링을 진행하기 전에는 코드를 커밋하거나 별도 브랜치를 만드는 것을 잊지 말자. 그래야 큰 범위의 리팩토링이 실패했을 때 다시 동작하는 마지막 상태로 쉽게 돌아올 수 있다.

2021-02-23 01:17 UTC, ep1stas1s requested changes
1단계 피드백까지 잘 반영해주셨네요 👍 
저번에 SOLID개념을 학습하셨으니 이번에 적용해봐도 좋을 것 같아서 피드백 남겼으니 한 번 같이 고민해봐주세요ㅎㅎ
혹시나 이견이나 궁금한 점이 있다면 언제든 DM주세요!

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoCount.java
> +public class LottoCount {
원시값 포장 👍

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoCount.java
> +        return new LottoCount(count - inputLottoCount.get());
일반적으론 `inputLottoCount.get()`을 
`inputLottoCount.count` 또는 `inputLottoCount.getCount()`를 사용할 것 같은데 의도하신 건가요~?

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/domain/PayAmount.java
> +    public LottoCount getLottoCount() {
get~ 보단 계산하는 의미의 메서드명은 어떨까요?

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoNumber.java
> +        if (!isInRange(lottoNum)) {
[이런 방식](https://schneide.blog/2014/08/03/dont-ever-not-avoid-negative-logic/)도 있으니 참고해주세요~!

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/domain/Rank.java
>      public static LottoStatisticResult match(Lottos lottos, WinningLotto winningLotto) {
`Lottos`나 `WinningLotto`에 위치시키면 getter를 사용하지 않을 수 있겠네요 :)

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/view/OutputView.java
> +             .forEach(rank -> {
별 다른 로직이 없다면 collection의 forEach를 사용해주세요 :)

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/view/OutputView.java
> +        List<Rank> ranks = new ArrayList<>(Arrays.asList(
요친구는 ArrayList가 2겹이네요ㅎㅎ

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/view/OutputView.java
> +            Rank.FIRST
현재 구조에서는 Rank가 추가될 경우, 항상 요기도 신경써서 추가를 해줘야 해요 😢
보다 효율적인 방법을 고민해보는건 어떨까요?

2021-02-23 01:17 UTC, ep1stas1s commented on src/main/java/lotto/controller/LottoMachineController.java
> +            manualLottos.add(Lotto.fromNumbers(lottoNumbers));
`LottoNumberGenerator`라는 interface를 만드신 만큼, 이 친구를 활용해보는건 어떨까요?

2021-02-23 01:17 UTC, ep1stas1s commented on src/test/java/lotto/domain/LottoCountTest.java
> +    @DisplayName("LottoCount 객체들끼리 뺄셈을 할 때 0 미만의 객체가 나오면 예외 발생")
꼼꼼한 테스트 👍

2021-02-23 01:54 UTC, jaeseongDev commented on src/main/java/lotto/domain/PayAmount.java
> +    public LottoCount getLottoCount() {
앞으로 변수명을 지을 때, 내부 로직을 조금 더 반영할 수 있는 메서드 명을 사용할 수 있도록 하겠습니다! 
디테일한 피드백 감사합니다😄

2021-02-23 02:05 UTC, jaeseongDev commented on src/main/java/lotto/domain/LottoCount.java
> +        return new LottoCount(count - inputLottoCount.get());
`inputLottoCount.count()` 또는 `inputLottoCount.getCount()`로 변수를 명명하지 않고, `inputLottoCount.get()`로 명명한 이유는 다음과 같은 생각에 의해서 `inputLottoCount.get()`로 명명하게 되었습니다. 
- `LottoCount` 클래스에서 getter로 꺼낼 필드가 `count` 밖에 없어서 `count()`나 `getCount()`로 변수명을 굳이 지정하지 않고 `get()`으로 변수명을 지정해도 괜찮다고 생각했습니다. 
- `LottoCount.get()`라는 변수를 보게 되면, 클래스 이름에 `LottoCount`라는 말이 들어가서 메서드에 굳이 중복적으로 `getCount()`로 메서드명을 지을 필요가 없다고 생각했었습니다. 

위와 같은 근거로 변수명을 지었는데, 혹시 문제가 될 부분이 있을까요 ... ?

2021-02-23 02:36 UTC, jaeseongDev commented on src/main/java/lotto/view/OutputView.java
> +            Rank.FIRST
Rank.NOTHING이 빠져야되고 원하는 순서대로 출력을 해야 한다는 조건이 있어서 List에 일일이 입력을 했는데, 
유지보수 측면을 생각하지 못했네요😭😭

Rank가 추가될 경우, 저 부분을 신경써서 추가하지 않아도 되도록 다시 코드를 수정하겠습니다!!

2021-02-23 03:04 UTC, jaeseongDev commented on src/main/java/lotto/controller/LottoMachineController.java
> +            manualLottos.add(Lotto.fromNumbers(lottoNumbers));
```java
private List<Lotto> getInputManualLottos(LottoCount count) {
    List<Lotto> manualLottos = new ArrayList<>();
    for (int i = 0; i < count.get(); i++) {
        List<Integer> lottoNumbers = inputView.readManualLottoNumbers();
        FixedNumberGenerator fixedNumberGenerator = new FixedNumberGenerator(lottoNumbers);
        manualLottos.add(Lotto.fromNumbers(fixedNumberGenerator.generateNumbers()));
    }
    return manualLottos;
}
```

고래가 말씀하신대로 LottoNumberGenerator라는 interface를 만들었으므로, 로또 숫자에 대한 List<Integer>를 만들 때에 LottoNumberGenerator를 사용해서 만들려고 시도해봤어요. 그런데 다른 코드에서도 보면 로또 넘버의 List<Integer>를 만들 때에 LottoNumberGenerator 인터페이스를 사용하지 않고 만든 경우가 대부분이었어요!  

LottoNumberGenerator 인터페이스를 만든 만큼, 로또 넘버의 List<Integer>를 만들 때에는 무조건 LottoNumberGenerator 인터페이스를 거쳐서 만들어야만 하는걸까요 ? 로또 넘버의 List<Integer>를 만들 때면 매번 LottoNumberGenerator를 상속받은 객체를 만들어야 해서 코드가 조금 더 장황해질 것 같애서 LottoNumberGenerator를 사용해서 구현하는 방식과 사용하지 않고 구현하는 방식 2가지를 사용하면 어떨까라고 생각해봤었어요! 

어떤 방식을 선택해야 맞는 것일까요 ... ? 🤔

2021-02-23 05:42 UTC, jaeseongDev commented on src/main/java/lotto/view/OutputView.java
> +             .forEach(rank -> {
stream.forEach()가 Collection.forEach()에 비해 stream 객체를 생성해야 하는 오버헤드가 있어서, 
단순 반복만을 사용할 때에는 Collection.forEach()를 사용하는 것이 좋음을 알 수 있었습니다!

2021-02-23 06:16 UTC, jaeseongDev commented on src/main/java/lotto/domain/Rank.java
>      public static LottoStatisticResult match(Lottos lottos, WinningLotto winningLotto) {
getter를 사용하는 로직이 있다면, 혹시나 다른 클래스한테 책임을 옮길 수 있는 지를 항상 체크해야 될 것 같다는 생각이 드네요!!
피드백 감사합니다😄😄😄

2021-02-23 06:33 UTC, jaeseongDev commented on src/main/java/lotto/domain/LottoNumber.java
> +        if (!isInRange(lottoNum)) {
!(부정 연산자)가 들어감으로써 코드의 가독성을 해칠 수 있다는 것을 알 수 있었습니다. 되도록이면 !(부정 연산자)를 빼서 코드를 작성해서 가독성을 높일 수 있도록 신경써보겠습니다!!

2021-02-23 17:03 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoCount.java
> +        return new LottoCount(count - inputLottoCount.get());
전혀 문제는 없습니다!!ㅎㅎㅎ
get()도 충분히 깔끔한 방법이라고 생각해요~!
여쭤본 이유는  제리의 의견이 궁금했어요 😄 

1. 우선 저는 위와 같은 코드에선, 일반적으로 아래와 같이 사용합니다 (자세히보면 `inputLottoCount.count()`가 아닌 `inputLottoCount.count`입니다...ㅎㅎ)
    ```suggestion
            return new LottoCount(count - inputLottoCount.count);
    ```
2. 반면 외부에서 사용할 땐 당연히 메서드로 필드에 접근해야하는데, 원하지 않아도 POJO를 만들어야 하는 상황들이 있어서 관례를 따르는 편입니다.

2021-02-23 17:40 UTC, ep1stas1s commented on src/main/java/lotto/controller/LottoMachineController.java
> +            manualLottos.add(Lotto.fromNumbers(lottoNumbers));
항상 그렇듯 정답은 없습니다. 유연한 설계도 좋고, YAGNI도 좋으나 둘은 대립할 수 밖에 없는 관계니까요 :)
다만, [제리가 정리하신 OCP](https://github.com/woowacourse/java-lotto/pull/264#issuecomment-781204023)가 생각나서 이번엔 유연한 코드 방향으로 가면 더 좋지 않을까 생각했습니다^_^

그럼 반대로 `LottoNumberGenerator`를 만드신 이유가 있을까요??

2021-02-24 16:06 UTC, jaeseongDev commented on src/main/java/lotto/controller/LottoMachineController.java
> +            manualLottos.add(Lotto.fromNumbers(lottoNumbers));
와우.....!!! 저는 처음에 LottoNumberGenerator를 만들었던 이유가 랜덤으로 생성하는 로또에 대해서 테스트를 작성하기 위해서, LottoNumberGenerator라는 인터페이스를 만들었었어요! 고래가 말씀하신대로 YAGNI로 처음에 코드를 작성했고, 테스트 코드는 작성하고 싶었어서 인터페이스를 적용시켰었어요. 하지만 OCP를 접목시켜서 실제 코드를 바라보진 않았었네요!! 그래서 고래가 주신 피드백을 바탕으로 OCP의 관점에서 다시 한 번 코드를 음미할 수 있었어요!!! 고래가 피드백해주신 덕분에 코드를 바라보는 안목을 조금 더 키울 수 있었던 기회가 된 것 같애요. 감사합니다😄😄

2021-02-24 16:14 UTC, jaeseongDev commented on src/main/java/lotto/domain/LottoCount.java
> +        return new LottoCount(count - inputLottoCount.get());
새로운 적용 방식을 소개해주셔서 고마워요, 고래😄 
해주신 피드백 중에서 POJO의 의미랑 연관시켜서 이해를 하지 못했어요ㅠㅠ 
POJO의 의미에 대해서 검색해서 의미를 파악하려 했는데, 위에서 해주신 피드백이랑 연관지어서 이해하지 못했네요...

"원하지 않아도 POJO를 만들어야 하는 상황이 있어서 관례를 따르는 편입니다." 이 부분에 대해서 조금만 더 자세하게 설명 부탁드려도 될까요 ? 😂

2021-02-24 17:37 UTC, ep1stas1s commented on src/main/java/lotto/domain/LottoCount.java
> +        return new LottoCount(count - inputLottoCount.get());
특정 프레임워크를 사용하다보면, 그 기능을 사용하기 위해 POJO(일반적인 getter를 포함한 객체)를 만들어야하는 상황이 있어요.
필드가 `count`이면, `getCount()`라는 메서드가 있어야 정상적으로 인식하여 동작하죠.
물론 커스텀하게 변경할 순 있어서 `get()`메서드에도 추가적인 액션을 취해주면 동일하게 작동하긴 하지만... 그 추가적인 액션이 번거롭다보니 일반적인 getter를 사용한다는 의미였습니다!

그리고 대부분의 개발자가 일반적인 getter를 사용하다보니, `get()`를 직접 들어가서 확인해봐야 할 것 같아요.
맞는 비유인진 모르겠지만, 나 혼자 `맥북`을 `맥`이라고 부르는 느낌?ㅋㅋㅋ
사람들이 맥이라고하면 노트북을 의미하는지, 데스크탑을 의미하는 지 한 번 더 물어봐야할 수도 있잖아요?ㅎㅎ
get도 마찬가지로 뭘 의미하는 지 정확히 보려면 메서드를 한 번 더 타고 들어가봐야 정확히 파악할 수 있을 것 같은 느낌이 있었어요.

**주관적인 의견이 많이 포함되어있으니 페어와 코딩하듯이 하나의 의견으로 보시길 바랍니다 😄**

2021-02-25 00:08 UTC, jaeseongDev commented on src/main/java/lotto/domain/LottoCount.java
> +        return new LottoCount(count - inputLottoCount.get());
자세하게 설명해주셔서 감사합니다😄  이번에는 정말 확실하게 이해됐어요!!!
고래가 얘기해주신대로 다른 개발자들이 익숙해져있는 메서드명으로 작성할 수 있는 방법을 알 수 있어서 너무 좋았어요!!ㅎㅎㅎ

2021-02-26 00:50 UTC, ep1stas1s approved these changes
미션 진행하시느라 고생하셨습니다 👍 
학습양도 많으신데 잘 정리하셔서 보기 좋았어요ㅎㅎ
다음 미션도 화이팅하시고 더 궁금하신 점이 있으면 언제든 DM 주세요~!

2021-02-26 00:50 UTC, ep1stas1s commented on src/main/java/lotto/controller/LottoMachineController.java
> +        return lottos;
요 부분이 조금 어색하다고 느꼈어요...ㅎㅎ
일급 컬렉션에 로또를 추가해줘도 되지 않을까요?

2021-02-26 00:50 UTC, merged

2021-02-26 08:51 UTC, jaeseongDev commented on src/main/java/lotto/controller/LottoMachineController.java
> +        return lottos;
다시 로직을 일급 컬렉션을 잘 활용하지 못한 로직이었네요! 저 부분도 수정하겠습니다!!😄