[2단계 - 로또 구현] 나봄(윤보민) 미션 제출합니다.
woowacourse/java-lotto pull request #285
Opened 2021-02-22 01:49 UTC by qhals321

게이츠! 이전 피드백 너무너무 감사해요!
게이츠 피드백에서 힌트를 많이 얻어서 적용해봤어요!
이전에는 `Application`을 프론트 컨트롤러 역할을 생각하고 뒤에서 또 다른 컨트롤러로 흐름을 정리하는 것이 조금 더 코드를 명확하게 할 수 있지 않을까? 라는 생각에 `Application`과 `LottoManager` 을 나누게 되었는데 어플리케이션 규모도 그렇게 크지 않고 `Application` 내부에서 모든 흐름을 정리해보니 훨씬 눈에 잘 들어오게 되었네요! 피드백 감사합니다! =]

구입한 모든 로또와 당첨 로또를 비교하는 작업과 결과 생성을 컨트롤러에서 제가 하고 있었더라고요! 그래서 게이츠가 피드백 남겨줬듯이 `LottoGroup` 자체에서 당첨 로또를 비교해서 바로 `LottoResult`를 리턴하는 방식으로 바꾸었어요~! 확실히 컨트롤러도 명확하게 되어진 것 것 같네요!!

또 이전에 `LottoGame`  피드백 부분은 `LottoGroup`를 만들다가 적용이 된 것 같아요! `Result` 를 `LottoGroup`에서 리턴하게 되었어요!!

2단계에서는 수동구매와 자동구매를 나누어 구매하는 기능을 구현했어요!
최대한 모델 레이어에서는 구매 자체의 행위는 같게 하고 외부에서 주입하는 방식에 따라 수동구매와 자동구매가 가능하게끔 신경을 많이 쓰게 되었어요! 그러다보니 `LottoSeller` 부분이 바뀌게 되었네요!

아침이든 늦은 밤이든 항상 꼼꼼한 피드백 감사합니다!!! =]

2021-02-23 19:39 UTC, serverwizard requested changes
안녕하세요 나봄!

로또 2단계 구현 잘 해주셨네요. 👍 
몇 가지 피드백 남겨두었으니 확인 부탁드릴게요

궁금한점 있으시면 편하게 코멘트 또는 DM 남겨주세요

2021-02-23 19:39 UTC, serverwizard commented on src/main/java/lotto/domain/LottoGroup.java
> +  private final List<Lotto> lottoGroup;
현재 LottoGroup에서 List< Lotto >를 멤버 변수로 가지기 때문에 아래 책임도 가지는 건 어떨까요? 
```
public List<Lotto> createLottos(int price, LottoGenerator lottoGenerator) {
      LottoGameValidator.validatePrice(price);
      
      int lottoCount = price / LOTTO_PRICE;
      for (int i = 0; i < lottoCount; i++) {
            lottos.add(new Lotto(lottoGenerator));
      }
      
       return lottos;
}
```

2021-02-23 19:39 UTC, serverwizard commented on src/main/java/lotto/view/InputView.java
> +      money = LottoSeller.sellLotto(money, lottoGroup, InputView::lottoNumbers);
현재 View에서 비즈니스 로직을 수행하고 있는데 이를 도메인 객체에서 수행하는 건 어떨까요?

2021-02-23 19:39 UTC, serverwizard commented on src/main/java/lotto/view/InputView.java
> +      LottoSeller.sellLotto(money, lottoGroup, new RandomLottoStrategy());
현재 View에서 비즈니스 로직을 수행하고 있는데 이를 도메인 객체에서 수행하는 건 어떨까요?

2021-02-23 19:39 UTC, serverwizard commented on src/main/java/lotto/controller/Application.java
> +    OutputView.printLottoResult(lottoResult);
설계에 정답은 없지만, 아래와 같이 설계해 볼 수도 있을 것 같아요.
참고만 하세요~

LottoApplication
```
LottosGenerator generator = new ComplexLottosGenerator(
        new AutoLottosGenerator(amount),
        new ManulLottosGenerator(manualNumbers)
);
LottoGroup lottoGroup = new LottoGroup(generator);
```
ManualLottoTicketGenerator
```
public class ManualLottoTicketGenerator implements LottosGenerator {

    private final List<String> manualTicketStrings;

    public ManualLottoTicketGenerator(List<String> manualTicketStrings) {
        this.manualTicketStrings = manualTicketStrings;
    }

    @Override
    public List<Lotto> generate() {
        List<Lotto> manualLottos = manualNumbers.stream()
                .map(LottoNumberFactory::createLottoNumbers) // 로또 번호 생성기에서 로또 번호 생성
                .map(Lotto::manual) // 수동으로 생성된 로또 번호들을 Lotto에 주입
                .collect(Collectors.toList());

        return manualLottos;
    }
}
```
ComplexLottosGenerator
```
public class ComplexLottosGenerator implements LottosGenerator {

    private final AutoLottoTicketGenerator auto;
    private final ManualLottoTicketGenerator manual;

    public ComplexLottosGenerator(AutoLottoTicketGenerator auto, ManualLottoTicketGenerator manual) {
        this.auto = auto;
        this.manual = manual;
    }

    @Override
    public List<Lotto> generate() {
        List<Lotto> lottos = manual.generate();
        lottos.addAll(auto.generate());
        return lottos;
    }
}
```

2021-02-26 05:41 UTC, serverwizard approved these changes
나봄! 로또 미션 진행하느라 고생 많았고 구현 잘해주셨네요! 👍

이번 단계는 여기서 merge하도록 할게요.
몇 가지 피드백 남겨두었으니 다음 단계 진행하실 때 참고만 부탁드릴게요!

수고하셨습니다! 🙏
(오늘 휴가라 이 시간에 리뷰드려요~)

2021-02-26 05:41 UTC, serverwizard commented on src/main/java/lotto/view/InputView.java
> +    }
View에서 로또 관련 로직을 수행하기 보다, View는 최대한 I/O(Input, Ouput)역할만 하도록 구현하는 건 어떨까요?

2021-02-26 05:41 UTC, serverwizard commented on src/main/java/lotto/view/InputView.java
>        return Money.of(money);
View에서 직접 도메인 객체에게 메시지를 전달하기 보단, View는 Controller를 통해 도메인 객체와 메시지를 주고 받는 건 어떨까요?
![image](https://user-images.githubusercontent.com/23587638/107108391-df80ef80-687a-11eb-869f-ed3707f9cca2.png)

2021-02-26 05:41 UTC, serverwizard commented on src/main/java/lotto/domain/lottoGroup/ManualLottoGroup.java
> +  private Lotto mapToLotto(String[] lotto) {
로또를 생성하는 책임을 Lotto에게 위임하는 건 어떨까요?

2021-02-26 05:41 UTC, merged

2021-02-26 05:44 UTC, qhals321 commented on src/main/java/lotto/domain/lottoGroup/ManualLottoGroup.java
> +  private Lotto mapToLotto(String[] lotto) {
그러네요!! 아예 String[] 자체를 받아 Lotto를 생성할 수 있는 생성자를 더 만드는 방법이 있었네요!!

2021-02-26 05:45 UTC, qhals321 commented on src/main/java/lotto/view/InputView.java
>        return Money.of(money);
머니 자체에 String을 받아서 Parsing할 때 생기는 예외를 거기서 던지는 것이 좋겠네요!! 감사합니다!

2021-02-26 05:46 UTC, qhals321 commented on src/main/java/lotto/view/InputView.java
> +    }
아예 도메인 관련에서 count까지 받아서 해결하는 것이 더 좋았겠네요...!!