[2단계 - 로또구현] 춘식(안예장) 미션 제출합니다.
woowacourse/java-lotto pull request #299
Opened 2021-02-23 12:43 UTC by RinSabbit

반가워요 닉!!!! 후딱 고치고 어제 PR을 보낼 계획이었는데 이것저것 고치다 보니 늦어버렸네요 😂 
1단계가 머지되고 다음과 같이 리팩토링을 해보았어요!

1. 수동 로또 티켓 구매 기능 + TC 추가
2. 거스름돈 출력 기능  + TC 추가
3. TicketFactory에서 랜덤 숫자를 만들던 기능을 RandomUtils로 이동
4. Controller에서 수동, 자동 로또 티켓을 구매하도록 함

4번의 경우 원래는 money와 lottotickets를 조합하여 **티켓을 구매하는 책임을 맡은 객체**를 생성하려고 했습니다.
그런데 수동 로또 티켓은 입력값을 받아야만 티켓을 생성할 수 있어서, 객체 내에서 InputView를 사용해야 했어요.
InputView를 사용하게 되면 도메인에서 뷰를 쓰니 MVC 패턴을 위반하게 됩니다.. 😢
InputView가 필요없는 자동 로또 티켓만 구매하는 객체를 만들어보기도 했지만 책임이 애매하게 분산되는 느낌이 들어 기각했습니다.
이걸 해결해보려고 다이어그램을 그려 구조가 너무 복잡하진 않은지 검토도 해보고,
전략 패턴도 알아봐서 적용을 시도해보다가 잘 되지 않아서...
일단 Controller에서 수동, 자동 티켓을 구매하는 로직을 짜고 닉에게 SOS를 치기로 결정했습니다!!! 😇 

요약하자면, Controller에서 티켓 구매 로직을 진행해도 문제가 없는 걸까요?
만약 구매하는 역할을 객체로 분리하고 싶다면 어떻게 해야 MVC 패턴을 지킬 수 있을까요?

2021-02-23 13:36 UTC, RinSabbit commented
# [TDD] JUnit5 - 4
## 내용
- WinningBoardTest에서 선언된 변수에 재할당을 여러번 하는 대신 `ParameterizedTest`를 사용했다.
    - 여러 인자를 받기 위해 `MethodSource`로 파라미터 인자들을 담은 Object 메소드를 만들었다.
    - ParameterizedTest에서 String name을 이용해 인자들의 순서와 이름을 지정해 준다. (아래 예시)

```java
@ParameterizedTest(name = "{index} => hits = {0}, hitBonus = {1}, winning = {2}")
    @MethodSource("testFreeParams")
    void checkBoard(int hits, boolean hitBonus, WinningBoard winning) {
        // Test code...
    }

    private static Object[] testFreeParams() {
        return new Object[]{
            new Object[]{5, true, WinningBoard.SECOND},
            new Object[]{5, false, WinningBoard.THIRD},
            new Object[]{2, true, WinningBoard.ZERO},
            new Object[]{4, false, WinningBoard.FOURTH}
        };
    }
```

## 링크
- [파라미터 테스트를 하는 방법](https://velog.io/@ashesglow/파라미터-테스트를-하는-방법-Junit5-JUnitParams)
- [Guide to JUnit 5 Parameterized Tests](https://www.baeldung.com/parameterized-tests-junit-5)

# [디자인 패턴] 전략 패턴 - 3
## 내용
- 적용은 못했지만 아래와 같이 BuyStrategy를 만들어 전략 패턴을 적용해보려 했다.

```java
interface BuyStrategy {

    Lottoticket buy(int count);

}

class ManualStrategy implements BuyStrategy {

    public Lottoticket buy(int count) {
    // 입력값을 받아 티켓을 만들어 반환하는 로직
    }

}

class RandomStrategy implements BuyStrategy {

    public Lottoticket buy(int count) {
    // 자동으로 로또 번호를 만들어 반환하는 로직
    }

}
```

```java
abstract class Machine {

    private BuyStrategy buyStrategy;

    public LottoTickets buyTickets(int count) {
         // buy() 를 count만큼 반복해 Lottotickets에 추가
     }

    public LottoTicket buy() {
         buyStrategy.buy();
     }

    public BuyStrategy set(BuyStrategy buyStrategy) {
        this.buyStrategy = buyStrategy;
    }

}

// ManualMachine과 RandomMachine이 Machine을 상속받는다.
```
## 링크
- https://victorydntmd.tistory.com/292
- https://wikidocs.net/219

2021-02-24 10:03 UTC, wbluke requested changes
2단계 잘 구현해주셨네요!
질문주신 부분 외에는 크게 피드백 드릴 부분이 없네요 ㅎㅎ
답변 남겼으니 한번 고민해보면 좋겠습니다 🙂

2021-02-24 10:03 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +        OutputView.printAllTickets(fixedTickets, money, lottoTickets);
> 4번의 경우 원래는 money와 lottotickets를 조합하여 티켓을 구매하는 책임을 맡은 객체를 생성하려고 했습니다.
그런데 수동 로또 티켓은 입력값을 받아야만 티켓을 생성할 수 있어서, 객체 내에서 InputView를 사용해야 했어요.
InputView를 사용하게 되면 도메인에서 뷰를 쓰니 MVC 패턴을 위반하게 됩니다.. 😢
InputView가 필요없는 자동 로또 티켓만 구매하는 객체를 만들어보기도 했지만 책임이 애매하게 분산되는 느낌이 들어 기각했습니다.
이걸 해결해보려고 다이어그램을 그려 구조가 너무 복잡하진 않은지 검토도 해보고,
전략 패턴도 알아봐서 적용을 시도해보다가 잘 되지 않아서...
일단 Controller에서 수동, 자동 티켓을 구매하는 로직을 짜고 닉에게 SOS를 치기로 결정했습니다!!! 😇
> 
> 요약하자면, Controller에서 티켓 구매 로직을 진행해도 문제가 없는 걸까요?
만약 구매하는 역할을 객체로 분리하고 싶다면 어떻게 해야 MVC 패턴을 지킬 수 있을까요?

네네 ㅎㅎ 한번 다음과 같은 관점으로 생각해볼까요?
- 자동차게임에서 테스트하기 어려운 랜덤숫자 생성 로직을 외부로 (바깥 계층으로) 분리했었음
- 현재 구조에서는, [테스트가 어려운 + 객체 추상화를 어렵게 하는] InputView 로직이 다수의 private 메서드를 끼고 내부에 있음
- 외부로 분리하면 어떨까? 가장 바깥에서 먼저 입력값을 다 받은 뒤, 추가 가공하는 형식으로

추가적으로 (이미 느끼셨겠지만) 하나의 클래스에 private 메서드가 많아지면 새로운 객체를 만들어야 한다는 신호로 볼 수 있습니다 :)

2021-02-24 10:03 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +    private void buyManualTickets(LottoTickets lottoTickets, int count) {
메서드 순서도 중요한데요, 상위 메서드에서 호출하는 순서대로 나열해주세요 ㅎㅎ
(읽는 사람이 자연스럽게 읽히도록)
애플리케이션 전체적으로 한번 체크해보세요! :)

2021-02-24 10:03 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static final String DUPLICATE_NUMBERS_BY_BONUS_BALL_ERROR_MESSAGE = "보너스 볼은 지난 주 당첨번호와 중복될 수 없습니다.";
상수 접근제어자도 챙겨주세요 :)

2021-02-24 10:03 UTC, wbluke commented on src/test/java/lotto/domain/WinningBoardTest.java
> +    @MethodSource("testFreeParams")
ParameterizedTest 👍

2021-02-25 08:16 UTC, RinSabbit commented
안녕하세요 닉!!
피드백을 반영해 아래 과정을 거쳐 리팩토링 해보았습니다!!

제일 큰 변화는 Controller의 run()에서만 예외를 catch하게 만든 겁니다.
만일 에러가 발생하면 에러 메세지와 함께 프로그램을 종료하도록 했어요. 
또한 최대한 외부에서 입력값을 받아올 수 있도록 수정해보는 도중에
함수형 인터페이스를 알게 되어 같은 기능을 하는 두 메소드를 하나로 통일시켜보았습니다.
함수형 인터페이스는 거의 써본 적이 없어 이렇게 쓰는 게 잘 맞는지 모르겠네요.

확인해주시면 감사하겠습니다!! 😆

2021-02-25 08:56 UTC, RinSabbit commented
# [JDK] 함수형 인터페이스 - 3
## 내용
- Controller에서 사실상 같은 기능을 하는 두 메소드를 함수형 인터페이스 `Supplier`를 이용해 하나로 통일시켰다.
    - Supplier는 인자를 받지 않고 반환값이 있는 < R > 형태 함수형 인터페이스이다.
    - Supplier는 추상 메소드 get()으로 값을 반환한다.

```java
    // 리팩토링 전
    private List<LottoTicket> inputManualTickets(int count) {
        List<LottoTicket> tickets = new ArrayList<>();
        IntStream.rangeClosed(1, count)
            .forEach(index -> tickets.add(new LottoTicket(InputView.inputNumbers())));
        return tickets;
    }

    private List<LottoTicket> inputRandomTickets(int count) {
        List<LottoTicket> tickets = new ArrayList<>();
        IntStream.rangeClosed(1, count)
            .forEach(index -> tickets.add(new LottoTicket(RandomUtils.generateNumbers())));
        return tickets;
    }

     // 리팩토링 후
     (...)
          Supplier<List<Integer>> manualNumbersGenerator = inputView::inputNumbers;
          Supplier<List<Integer>> randomNumbersGenerator = RandomUtils::generateNumbers;
     (...)

    private List<LottoTicket> inputTickets(int count, Supplier<List<Integer>> numbersGenerator) {
        List<LottoTicket> tickets = new ArrayList<>();
        IntStream.rangeClosed(1, count)
            .forEach(index -> tickets.add(new LottoTicket(numbersGenerator.get())));
        return tickets;
    }
```

## 링크
- [Java8#02. 함수형 인터페이스(Functional Interface)](https://multifrontgarden.tistory.com/125)
- [Modern Java (Java 8) - 함수형 인터페이스](https://velog.io/@litien/Modern-Java-Java-8-함수형-인터페이스)

2021-02-26 09:36 UTC, wbluke approved these changes
구조 개선 잘 해주셨네요 👍 
소소한 코멘트 남겼으니 참고해주세요 ㅎㅎ
고생 많았어요!! 🙂

2021-02-26 09:36 UTC, wbluke commented on src/main/java/lotto/domain/Count.java
> +public class Count {
Count 추상화 👍 
이런 값 객체는 항상 eq & hc 도 재정의하는게 좋아요 :)

2021-02-26 09:36 UTC, wbluke commented on src/main/java/lotto/controller/LottoController.java
> +    private List<LottoTicket> inputTickets(Count count, Supplier<List<Integer>> numbersGenerator) {
좋은 시도네요 💯 
이름이 Generator인건 살짝 안어울리는 것 같아서, 별도의 객체로 만들던지 적절한 이름을 고민해보면 좋겠네요 ㅎㅎㅎ 👍 
Generator는 뭔가 가공을 거쳐야할 것 같아요 :)

2021-02-26 09:36 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final String NOT_PROPER_RANGE_NUMBER_ERROR_MESSAGE = "로또 번호는 %d-%d 사이의 숫자이어야 합니다.";
다른 부분 상수도 public인데, 혹시 intellij 단축키 사용하고 있나요?
https://stackoverflow.com/questions/37431594/how-can-i-default-constants-in-intellij-to-private/37436540
여기 참고하면 단축키로 상수 뽑았을 때 기본 private 제어자로 설정할 수 있어요 :)

2021-02-26 09:36 UTC, merged

2021-02-27 15:45 UTC, RinSabbit commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final String NOT_PROPER_RANGE_NUMBER_ERROR_MESSAGE = "로또 번호는 %d-%d 사이의 숫자이어야 합니다.";
매번 바뀌기 번거로웠는데 설정을 할 수 있었군요!! 감사합니다!!!!!

2021-02-27 15:48 UTC, RinSabbit commented on src/main/java/lotto/domain/Count.java
> +public class Count {
eq랑 hc가 뭔가 했는데 equals랑 hashcode였군요ㅎㅎ 급하게 추가해서 잊고 있었네요 감사합니다!!

2021-02-27 15:53 UTC, RinSabbit commented on src/main/java/lotto/controller/LottoController.java
> +    private List<LottoTicket> inputTickets(Count count, Supplier<List<Integer>> numbersGenerator) {
Provider로 수정했습니다!! 확실히 Generator는 생성에만 역할이 충실해보이네요.