[2단계 - 로또 구현] 바다(조아라) 미션 제출합니다.
woowacourse/java-lotto pull request #308
Opened 2021-02-24 08:14 UTC by xrabcde

안녕하세요 데이브! 바다입니다🌊
지난번에 추가해주신 피드백과 2단계 수동구매 미션을 구현해보았습니다.
이번 리뷰도 잘 부탁드립니다 ㅎㅎ 🙏
감사합니다!

2021-02-25 15:52 UTC, dave915 requested changes
바다 안녕하세요! 리뷰가 늦었네요 ㅠㅠ
몇가지 피드백 남겼어요. 확인 부탁드릴게요! 

1. 객체에게 메세지를 보내 결과에 해당하는 객체를 얻는다
2. Controller가 들고있는 필드를 제거 한다

이러게 두가지를 생각하면서 피드백을 적용해보면 좋겠어요 :) 
혹시 궁금한 부분이 있다면 편하게 DM 주세요!

2021-02-25 15:52 UTC, dave915 commented on src/main/java/lotto/controller/LottoController.java
> +    }
혹시 manualCount가 구매 가능한 전체  Count보다 클 경우 체크가 가능할까요?

2021-02-25 15:52 UTC, dave915 commented on src/main/java/lotto/controller/LottoController.java
>      private void drawLotto() {
Lottos 에게 WinningLotto를 넘겨줘서 wins를 반환하도록 하면 어떨까요? 
`Lottos에게 우승 번호를 알려줄테니까 결과줘~ 이런느낌입니다`

2021-02-25 15:52 UTC, dave915 commented on src/main/java/lotto/controller/LottoController.java
>      private void countEachRank() {
위 코멘트를 반영해서 나온 객체로 부터 countByRank에 해당하는 객체를 얻을 수 있을 것같아요!

2021-02-26 11:59 UTC, xrabcde commented on src/main/java/lotto/controller/LottoController.java
> +    }
> 혹시 manualCount가 구매 가능한 전체 Count보다 클 경우 체크가 가능할까요?

`lottos` 를 생성할 때 생성자에서 `validateManualCount`를 통해 수동구매 개수의 유효성을 검증하고 있긴 합니다..!

2021-03-01 14:04 UTC, xrabcde commented
안녕하세요 데이브! 바다입니다🌊
리뷰 반영하여 코드 수정해보았습니다. 이번에도 역시 코드가 훨씬 깔끔해진 것 같아요!
리뷰를 최대한 반영하려고 고민하느라 리뷰요청이 늦어졌네요ㅠㅜ 
말씀해주신 두가지를 최대한 적용해보려고 했는데 몇 가지 문제가 있었어요😥
1. _객체에게 메세지를 보내 결과에 해당하는 객체를 얻는다_
객체에게 메세지를 보내라는 뜻을 getter 메서드의 사용을 최소화하라는 뜻으로 이해했는데 맞을까요? 최대한 제가 사용한 getter 메서드들을 다른 방식으로 대체해보았는데 대체불가능하다고 판단된 부분이 **두 곳** 있었습니다..
- 먼저, `LottoView`에서 `manualCount`와 `randomCount`를 출력해주는 부분인데요! 지난 1차 리뷰에서 도메인에서 toString을 이용해 출력형식을 지정해주는 방식은 좋은 방법이 아니라고 배웠었는데 getter를 사용하지 않고 두 변수를 어떻게 출력하면 좋을지 도무지 생각나지가 않더라구요.. 이런식으로 view에서만 필요로 하는 변수들은 public 변수로 두는 것이 좋을까요?
- 두 번째로는 `LottoNumber`의 `getNumber`를 제거하려고 했지만 `Lotto`에서 `changeToList`를 할 때 `getNumber`를 대체할 방식이 떠오르지 않아 결국 `getNumber`를 다시 추가해버렸습니다.. getter 메서드 사용을 최소화하는 것이 너무 어렵네요😂
2. _Controller가 들고있는 필드를 제거 한다_
앞서 1차로 페어와 미션을 하면서도 Controller가 필드를 들고있는 것에 대해서 고민이 많았는데, 리뷰를 반영하여 controller가 들고있던 필드들은 최대한 제거하는 방향으로 코드를 개선해보았습니다! 조언해주신대로, 필드를 제거하니 코드가 훨씬 깔끔해진 것 같아요! 그런데 `lottos` 필드의 경우, controller 안에서 `lottos`를 사용하는 메서드가 많은데 메서드의 인자가 늘어나더라도 `lottos`를 제거하고 메서드끼리 서로 인자로 전달/반환해주는 것이 좋을까요? 아니면 이런 경우는 그냥 controller가 `lottos`필드를 갖고있는 것이 나은 방향인지 헷갈리네요.. 

부족한 코드 리뷰해주셔서 감사합니다 😊

2021-03-02 14:33 UTC, dave915 commented
>객체에게 메세지를 보내 결과에 해당하는 객체를 얻는다

보통 객체 상태를 변경하는 작업을 getter로 값을 꺼내와서 변경하는 것을 하지 않기위해 getter를 지양하자는 것으로 알고있어요.
바다가 질문 주신 View에 전달하기 위한 값을 추출하기 위해서는 어쩔수없이 getter가 필요하다고 생각합니다 :) 
단, getter를 이용하여 객체의 상태를 반환 할 때 원시값 또는 불변객체로 전달하여 객체의 상태를 외부에서 변경 불가능 하도록 하면 될 것 같아요.

>Controller가 들고있는 필드를 제거 한다

저는 Controller가 View와 Domain의 연결 지점이라고 생각하고 있어서, Controller의 인스턴스는 하나만 있어도 된다고 생각하고 있어요. 
지금 같은 경우 LottoController가 Lottos라는 상태를 갖게 되어서 Lotto게임이 여러번 또는 동시에 실행될때마다 LottoController가 생성되어야 할 것 같아요.

2021-03-02 14:33 UTC, dave915 requested changes
바다 안녕하세요! 
수정해 주신 부분 확인했습니다 ㅎㅎ 
몇가지 피드백 및 질문하신 부분에 관한 코멘트 남겼으니 확인 부탁드릴게요 :)

2021-03-02 14:33 UTC, dave915 commented on src/main/java/lotto/domain/Lottos.java
>      private final ArrayList<Lotto> lottoGroup = new ArrayList<>();
필드를 List<Lotto> 으로 선언 하는 것과 ArrayList<Lotto> 로 선언하는 것과 어떤 차이가 있을까요? 
```suggestion
    private final List<Lotto> lottoGroup = new ArrayList<>();
```

2021-03-02 14:33 UTC, dave915 commented on src/main/java/lotto/controller/LottoController.java
> +        String winningInput = LottoView.requestManualNumber();
변수명 수정이 필요 할 것 같아요 :)

2021-03-02 14:33 UTC, dave915 commented on src/main/java/lotto/controller/LottoController.java
>      }
count 부분을 아래처럼 makeAllLotto 메소드 밖으로 꺼내오면 고민하셨던 부분이 해결 될 것 같아요 :) 
```
        Money money = new Money(LottoView.requestMoney());
        // int manualCount = getMenualCount();
        // int autoCount = money.getLeftCount(menualCount);

        // Lottos menualLotto = makeMenualLotto(menualCount);
        // Lottos autoLotto = makeAutoLotto(autoCount);

        // 두 로또 합치는 과정
        LottoView.displayLottoCount(menualCount, autoCount);
        LottoView.displayLottoGroup(lottos);
```

2021-03-02 14:33 UTC, dave915 commented on src/main/java/lotto/controller/LottoController.java
> +        }
Controller에서 하나씩 만들어서 추가해주지 않고 Lottos가 List<String> 을 받아서 Lottos 내부에서 만들도록 해보면 좋을것 같아요 :)

2021-03-02 14:33 UTC, dave915 commented on src/main/java/lotto/controller/LottoController.java
>      }
Lotto가 String 타입의 numberInput을 받아서 해당 String으로 Lotto를 만들도록 해보면 어떨까요? 
그렇게되면 이 메소드도 Lotto내부로 들어갈 수 있을 것 같아요 🤔

2021-03-03 04:13 UTC, xrabcde commented on src/main/java/lotto/domain/Lottos.java
>      private final ArrayList<Lotto> lottoGroup = new ArrayList<>();
앗 강의에서 이 부분 배우고 수정하려고 했었는데 깜빡했네요 😂

2021-03-03 04:27 UTC, xrabcde commented
안녕하세요 데이브! 바다입니다🌊
말씀해주신대로 변수를 불변객체로 전달하는 방식으로 고민했던 부분을 해결해보았습니다!
감사합니다 ㅎㅎ

2021-03-04 13:13 UTC, dave915 requested changes
바다 추가적인 피드백 남겼어요! 
반영 하시면서 새로생긴 메소드, 생성자, 정적팩토리패턴에 관한 테스트도 작성하면 좋을 것 같아요 :) 
궁금한점 있다면 언제든지 DM주세요!

2021-03-04 13:13 UTC, dave915 commented on src/main/java/lotto/domain/Lottos.java
> +    }
이렇게 List<String> 으로 수동 번호들을 받고 그 String들을 Lotto에게 전달해서 Lotto 생성과 Lottos 생성이 동시에 일어났으면 했습니다 :) 

```suggestion
    public void generateManualLottos(List<String> manualNumberInput) {
        this.lottoGroup = new ArrayList<>();
        for (int i = 0; i < Integer.parseInt(manualCount); i++) {
            this.lottoGroup.add(Lotto.changeStringToLotto(manualNumberInput));
        }
    }
```

2021-03-04 13:13 UTC, dave915 commented on src/main/java/lotto/domain/Lottos.java
> +    public ArrayList<Rank> drawLotto(WinningLotto winningLotto) {
```suggestion
    public List<Rank> drawLotto(WinningLotto winningLotto) {
```

2021-03-04 13:13 UTC, dave915 commented on src/main/java/lotto/domain/Lottos.java
> +        return wins;
```suggestion
        return new Result(wins);
```

```
public class Result {
    private Map<Rank, Integer> countByRank;

    public Result(List<Rank> wins) {
        Map<Rank, Integer> countByRank = new TreeMap<>();
        for (int i = 1; i < Rank.values().length; i++) {
            Rank rank = Rank.values()[i];
            int rankCount = (int) wins.stream().filter(win -> win == rank).count();
            countByRank.put(rank, rankCount);
        }
    }
}
```

이런 Result객체를 만들어서 Controller에 있는 countEachRank로직을 이동시켜도 좋을 것 같네요.

2021-03-04 13:13 UTC, dave915 commented on src/main/java/lotto/domain/Lotto.java
> +    public static Lotto changeStringToLotto(String numberInput) {
정적 팩토리 메소드 패턴은 보통 정해진 네이밍 방법이 있습니다 :) 

https://multifrontgarden.tistory.com/255

2021-03-06 10:10 UTC, xrabcde commented
안녕하세요 데이브!
피드백 주신대로 Result 클래스를 생성하면서 전체적으로 다시 리팩토링을 진행해보았어요
프로그램 전체가 아니라 급하게 부분부분 수정/추가/이동을 하다보니 엉망이 되어버린 로또 로직도 다시 다잡아보았습니다.
제가 미처 발견하지 못 한 부분이 있다면 알려주세요..!
부족한 코드 봐주셔서 감사드립니다😂

2021-03-06 16:04 UTC, dave915 approved these changes
바다! 피드백 반영한 부분 확인했습니다 :) 
그동안 고생하셨습니다! 이만 머지할게요!

2021-03-06 16:04 UTC, merged