[2단계 - 로또 구현] 파피(김태완) 미션 제출합니다.
woowacourse/java-lotto pull request #316
Opened 2021-02-24 20:13 UTC by TaewanKimmmm

안녕하세요, 닉! 😃

2단계 피드백도 잘 부탁드립니다!🙏

솔직히 2단계 시작 전에 어렵지 않을 거라고 생각했는데 많이 벅찼어요..

패키지 구조와 코드를 전체적으로 많이 변경했는데 쏟아지는 피드백을 받을 수 있다는 생각에 두려움 반 설렘 반(?)입니다.

# 이번 미션 진행하면서 느낀 문제점
- 구현할 기능이 추가되었는데 리팩토링 시작 전에 할 일 목록을 추가로 작성하지 않았다.
- 테스트 코드보다 프로덕션 코드에 먼저 손이 갔다. 
- 커밋도 기능 단위로 하지 않고 구현에 급급했다.

# 궁금한 점
- 사용자에게서 받은 입력을 검증한 후에 예외가 발생하면 재귀를 통해 다시 입력하게 하는데, 더 괜찮은 방법이 있을까요?

소중한 시간 내어 주셔서 감사합니다!🙏

2021-02-26 00:17 UTC, wbluke requested changes
안녕하세요 파피! 2단계 버거웠다고 했는데 잘 구현해주셨네요 ㅋㅋ 👍 
주신 질문 포함해서 코멘트 남겼어요 ㅎㅎ
수정 후 재요청 부탁드려요! 🙂

2021-02-26 00:17 UTC, wbluke commented on src/main/java/lotto/controller/LottoMain.java
> +        List<LottoNumber> lottoNumbers = numbers.stream().map(LottoNumber::new).collect(Collectors.toList());
```suggestion
        List<LottoNumber> lottoNumbers = numbers.stream()
                .map(LottoNumber::new)
                .collect(Collectors.toList());
```

stream은 가독성을 위해 한줄에 하나씩 쓰는게 좋아요 :)

2021-02-26 00:17 UTC, wbluke commented on src/test/java/lotto/domain/ticketresult/LottoComparatorTest.java
> +    @BeforeEach
`@BeforeEach`는 매 테스트 전에 할 일을 구성하는 곳이기 때문에 하나만 작성하는 것이 좋습니다 :)

2021-02-26 00:17 UTC, wbluke commented on src/test/java/lotto/domain/ticketresult/LottoComparatorTest.java
> +        Assertions.assertThat(lottoResult.get(FIFTH)).isEqualTo(0);
```suggestion
        Assertions.assertThat(lottoResult.get(FIFTH)).isZero();
```
요렇게 할 수도 있습니다 :)

2021-02-26 00:17 UTC, wbluke commented on src/main/java/lotto/domain/ticketpurchase/PurchasedTickets.java
> +    public PurchasedTickets(LottoTickets manualTickets, LottoTickets autoTickets) {
같은 타입의 파라미터가 나열된 생성자면, 이 객체를 사용하는 클라이언트가 순서를 신경써야할 것 같아요 ㅎㅎ
(수동-자동 으로 넣었는지, 실수로 자동-수동으로 넣었는지 컴파일 타임에 디버깅이 안됩니다.)
상황에 따라 잘못하면 큰 장애로 이어질 수도 있어서 늘 조심해야하는 부분이에요 ㅎㅎ

이런 상황을 조금이나마 회피하는 방법(100% 피하긴 어려울 수 있지만)은 여러가지가 있을텐데요, 어떤 방법이 있을까요? :)

2021-02-26 00:17 UTC, wbluke commented on src/main/java/lotto/domain/ticketpurchase/UserPurchase.java
> +        }
if문 내의 내용을 한눈에 알아볼 수 있게 추상화를 해보면 좋겠네요 :)

2021-02-26 00:17 UTC, wbluke commented on src/main/java/lotto/strategy/AutoStrategy.java
> +package lotto.strategy;
패키지 나누는 연습 잘 하셨네요 👍 
다음과 같은 질문을 드리고 싶어요 ㅎㅎ
- strategy가 domain 패키지 하위가 아닌 이유는 무엇일까요?
- LottoNumber, LottoTicket, LottoTickets도 하나의 패키지로 묶일 수 있을 것 같은데 어떻게 생각하시나요? :)

2021-02-26 00:17 UTC, wbluke commented on src/main/java/lotto/controller/LottoMain.java
> +    private static LottoNumber getBonusNumberInput() {
> 사용자에게서 받은 입력을 검증한 후에 예외가 발생하면 재귀를 통해 다시 입력하게 하는데, 더 괜찮은 방법이 있을까요?

보통 Controller를 구현하면서 재입력을 받기 위해 재귀를 사용하다가, 구조가 많이 굳어지고 private 메서드도 많아지는데요.
(다들 너무 친절하셔서...ㅋㅋ)
저는 재입력 기능이 없어도 된다고 생각해요 ㅎㅎ
지금은 Console 기반이라 재입력 등이 가능하도록 설계할 수 있지만, 보통의 Web, HTTP 통신에서는 하나의 요청이 상태를 가지고 있지 않기 때문에 재입력이라는 개념이 없거든요. (개별 요청이 성공/실패 하는 경우만 있죠. HTTP 상태코드가 그 결과값이고요)

한번 고민해보시면 좋겠네요! :)

2021-02-26 13:31 UTC, TaewanKimmmm commented on src/main/java/lotto/strategy/AutoStrategy.java
> +package lotto.strategy;
strategy는 전략..이라는 추상적 개념이라고 생각해서 따로 뺐는데 이러면 mvc랑 대등해 보일 수도 있겠네요..! 도메인에 속하는 게 맞는 것 같네요!

2021-02-26 13:32 UTC, TaewanKimmmm commented on src/main/java/lotto/strategy/AutoStrategy.java
> +package lotto.strategy;
LottoNumber, LottoTicket, LottoTickets도 ticket이라는 패키지로 묶는 게 나을 것 같습니다 ㅎㅎㅎ

2021-02-27 07:36 UTC, TaewanKimmmm commented
안녕하세요, 닉!!! 피드백 반영하였습니다!!!

피드백 중에 가장 고민을 많이 하게 된 부분은 아래 코드에 대한

```java
private final LottoTickets manualTickets;
private final LottoTickets autoTickets;

public PurchasedTickets(LottoTickets manualTickets, LottoTickets autoTickets) {
```

```같은 타입의 파라미터가 나열된 생성자면, 이 객체를 사용하는 클라이언트가 순서를 신경써야할 것 같아요 ㅎㅎ``` 였어요.

해결책을 찾다가 https://dave.cheney.net/2019/09/24/be-wary-of-functions-which-take-several-parameters-of-the-same-type 에서,

 헬퍼 메소드를 두어 점진적으로 타입을 일치시키는 방법도 알게 되었어요.

그런데 곰곰이 생각해보니 
1. 원래 있던 LottoTickets 클래스를 객체화 할 수 없게 abstract 클래스로 수정한 뒤,
2. LottoTickets를 상속받는 ManualTickets 클래스와 AutoTickets 클래스를 만들면
3. 타입만 다르게 할 수 있지 않을까? 라는 생각이 들어서, 그대로 진행해봤어요!

이 방법..괜찮을까요? 너무 궁금해서 닉한테 정답을 알려달라고 DM을 드릴까도 생각했지만 일단 혼자 힘으로 해보고 싶었어요😂

닉이라면 이 문제를 어떻게 다루셨을까요?

---
# 추가 수정 사항
1. 구입 금액 포장
```java
public UserPurchase(int purchasePrice, int manualTicketNumber) {
```
였는데요. 이것 또한 닉의 피드백대로라면 문제가 생길 여지가 있다고 판단되어 
```java
public UserPurchase(PurchasePrice purchasePrice, int manualTicketNumber) {
```
purchasePrice를 포장했습니다. 덤으로 책임 분리와 테스트 용이함을 얻었어요!

2. 로또 티켓 한장의 가격을 의미하는 상수의 이름과 위치 변경
기존에는 UserPurchase 클래스에 위치하던 
```java
private static final int ONE_TICKET_PRICE = 1000;
```
을 LottoTicket 클래스로 옮기고,
```java
public static final int PRICE = 1000;
```
으로 변경하고, PurchasePrice 클래스와 UserPurchase 클래스에서 사용할 수 있도록 했어요.

3. LottoNumber를 캐싱하였습니다.

4. LottoTicket의 List 자료구조를 Set으로 바꿨습니다.

---

이번 미션을 진행하기 전까지는 InputView에서도 domain을 알고 있어도(의존해도) 된다고 생각하고 있었어요.

그래서인지 domain 관련 코드를 변경하기에 앞서, 다른 것들은 얼마나 고쳐야 될까? 라는 막연한 두려움이 들었는데, 

InputView는 기본 타입만 보장하게 하면서 domain과의 의존성을 없애고 나니 리팩토링이 훨씬 수월하다고 느껴졌어요.

많이 생각해 볼 수 있는 피드백을 주셔서 정말 도움이 많이 됐어요.

시간 내어 주셔서 감사합니다!!!!😀😀😀😀😀

2021-02-28 13:20 UTC, wbluke approved these changes
피드백 잘 반영해주셨네요 💯 
고민해보라고 말씀드린 부분에 대해서 방법을 고민하고 적용해주셔서 감사합니다 ㅎㅎ
제 생각도 같이 남겼으니 참고해주시고, 긴 로또 미션 고생 많으셨어요! 🙂

2021-02-28 13:20 UTC, wbluke commented on src/main/java/lotto/domain/ticket/LottoTickets.java
> +public abstract class LottoTickets {
> 그런데 곰곰이 생각해보니
> 
> 원래 있던 LottoTickets 클래스를 객체화 할 수 없게 abstract 클래스로 수정한 뒤,
LottoTickets를 상속받는 ManualTickets 클래스와 AutoTickets 클래스를 만들면
타입만 다르게 할 수 있지 않을까? 라는 생각이 들어서, 그대로 진행해봤어요!
이 방법..괜찮을까요? 너무 궁금해서 닉한테 정답을 알려달라고 DM을 드릴까도 생각했지만 일단 혼자 힘으로 해보고 싶었어요😂
> 
> 닉이라면 이 문제를 어떻게 다루셨을까요?

오 추상클래스를 사용하셨군요 👍 
저는 순서를 착각할 수 있는 생성자 대신 각 로또티켓을 받는 메서드를 별도로 만들거나, 빌더 패턴을 사용하는 것을 생각했어요 ㅎㅎ
(타입이 같아서 완벽히 막을 수는 없겠지만, 최소한의 방어 정도?)
추상클래스로 하면 하위 클래스가 별도의 타입으로 인식되어 구별이 가능하겠네요!

좋은 시도지만 조금 첨언을 하자면, 상속 구조는 상속으로 설계했을 때 구조가 명확한 경우에만, 중복 필드나 행위를 공통으로 관리할 수 있는 경우에 적용하는 것이 좋아요 ㅎㅎ
한번 상속 구조를 적용하면 구조가 굳어져버리기 때문에 신중하게 고려하는 것이 좋습니다!

저도 저라면 이렇게 했을 것 같다, 라고 말씀드리려다가 한번 열린 답변을 드려봤는데, 좋은 고민의 시간이었다면 좋겠네요 🙏

2021-02-28 13:20 UTC, wbluke commented on src/main/java/lotto/domain/ticketpurchase/PurchasePrice.java
> +public class PurchasePrice {
> 구입 금액 포장
```java
public UserPurchase(int purchasePrice, int manualTicketNumber) {
```
> 였는데요. 이것 또한 닉의 피드백대로라면 문제가 생길 여지가 있다고 판단되어

```java
public UserPurchase(PurchasePrice purchasePrice, int manualTicketNumber) {
```
> purchasePrice를 포장했습니다. 덤으로 책임 분리와 테스트 용이함을 얻었어요!

추가로 적용하시다니 멋집니다 👍  
앞으로의 미션들에서도 값 객체로 묶을 수 있는 것들이 없을지 항상 고민해보면 좋겠네요 :)

2021-02-28 13:20 UTC, merged

2021-03-01 14:21 UTC, TaewanKimmmm commented on src/main/java/lotto/domain/ticket/LottoTickets.java
> +public abstract class LottoTickets {
빌더 패턴은 멤버 변수가 많을 때 사용한다고 해서 후보에서 제외했었는데,  나중에 적용해봐야겠어요!
상속은 역시 신중하게 생각해봐야겠군요..감사합니다!!!