[1단계 - 로또(자동)] 아스피(신동석) 미션 제출합니다.
woowacourse/java-lotto pull request #343
Opened 2022-02-24 05:51 UTC by shindong96

안녕하세요 에단! 1단계 로또 미션 리뷰를 부탁드리게 된 아스피입니다 :)
먼저 바쁘실텐데 제 코드를 리뷰해주셔서 감사하단 말을 꼭 전하고 싶어요. 시간 아깝지 않게 피드백을 열심히 반영하며 발전할게요!

이번 미션을 진행하면서 페어와 고민하던 것들이 몇 가지 있었는데요...그 중에 결론내지 못한 것들에 대해서 조언을 좀 구하고 싶어요. 그래서 이렇게 코멘트에 몇 자 적어 남깁니다!

1. Controller 객체가 멤버 변수를 가져도 되냐는 고민을 하였어요. 저는 이제껏 MVC패턴을 사용해본 경험이 많지 않아서 Controller 객체도 멤버변수를 가져도 된다고 생각해왔습니다. 그 이유는 로또 게임을 할 때마다 새로운 Controller를 선언해서 한 게임에 한 Controller가 배정되는 느낌으로 설계한다면 멤버 변수를 가져도 문제가 없다고 판단했기 때문이에요. 혹시 아닌가요?

2. 처음에 설계할 때는 Controller가 지금은 없는 LottoGame이라는 객체와 View들만 가지고 있게 하였습니다. 이렇게 설계를 하게 되면 LottoGame이라는 객체에서 Lotto에 관한 객체들, WinningNumber에 대한 객체들, BonusBall에 관한 객체들을 가지고 있어야해요. 그런데 시작할 때 입력 -> (로또 관련)출력 -> 입력 순으로 진행하기 때문에 LottoGame 생성자에서 한 번에 객체들을 초기화 할 수 없는 상황이 생기더라구요. 순차적으로 set시키자니 그건 setter를 만드는 것과 동일한 것 같고요...객체들을 다 만들고 한 번에 생성자에 넣어서 생성하게 되면 어차피 Controller에서 다하는 거라 별로 존재의 이유가 느껴지지 않고요. 어떻게 하는게 좋을지 고민입니다!

3. LottoTest에 있는 test 2개를 한 번에 진행하면 앞의 테스트 결과가 뒤의 테스트 결과에 영향을 줘요...앞의 테스트가 끝난 뒤에 Enum클래스를 초기화 할 수 있는 방법이 있을까요?

부끄럽지만 피드백을 주시면 열심히 고쳐보겠습니다!

2022-02-24 13:17 UTC, Laterality requested changes
안녕하세요 아스피, 리뷰어 에단입니다.

구현하느라 고생 많으셨어요!

몇가지 간단한 코멘트를 남겨드렸으니 참고 부탁드릴게요.

## Q&A

1. 컨트롤러가 멤버 변수를 가져도 되는지
    인스턴스이 재사용성 관점에서 생각해볼 수 있겠어요. 결론 먼저 말씀드리면 인스턴스는 재사용 가능할 수록 좋습니다. 상황에 따라 차이가 있지만 인스턴스를 생성하는 일은 리소스가 필요한 작업입니다. 특히 생성이 빈번할수록 재사용 가능한 경우와 그렇지 않은 경우의 차이가 현저하게 드러날 거에요.
    여기서 오해하면 안되는 부분은 "인스턴스가 멤버 변수를 가지면 재사용할 수 없는가?"인데요. 인스턴스가 멤버 변수를 가져도 재사용할 수 있습니다. 어떤 인스턴스가 재사용 가능한지, 지금 구현하신 컨트롤러를 재사용 가능하도록 만들려면 어떻게 해야 할 지 고민해보시면 좋겠어요.

2. 순차적으로 입력받은 파라미터를 한번에 넘길 방법
    이 부분은 질문의 의도를 이해하기가 어렵네요 😅 
    컨트롤러가 하는 일을 다른 객체가 똑같이 한다면 한쪽은 불필요한 일을 하고 있는 거라고 봐야겠죠? 컨트롤러와 다른 객체 사이의 책임을 잘 나눠보시면 도움이 될 것 같아요.

3. 테스트 사이에 영향을 주는 클래스의 상태
    코멘트에도 남겨드리긴 했지만, enum을 사용한 것이 적절한지 고민해볼 필요가 있겠어요. 테스트 사이에서도 서로 결과에 영향을 미친다면 당연히 로또 게임에서 사용될 때도 마찬가지일 수 있겠죠?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/bonusball/BonusBall.java
> +        InputValidateUtils.inputNumber(number, BONUS_BALL_NUMBER_ERROR_MESSAGE);
인자가 `int`라면 두 메서드는 불필요할텐데 `String`으로 선언하신 이유가 있을까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/lotto/Lotto.java
> +    public void compare(BonusBallDTO bonusBallDTO, LottoWinningNumberDTO winningNumberDTO) {
`compare`로 시작하는 메서드는 두 인자를 받아서 어떤 방법으로 비교한 뒤 그 결과를 반환하는 형태가 보편적인데요(e.g., `Integer.compare(int, int)`). 이 메서드는 반환하는 결과도 없고 내부에서 어떤 동작을 하는지 파악하기도 어렵네요. 메서드의 동작을 더 잘 나타내는 이름으로 바꿔보면 어떨까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/lotto/Lotto.java
> +    private long compareWithWinningNumber(List<Integer> winningNumbers) {
일치하는 횟수를 세는 것이 핵심 동작이라면 `count`로 시작하는 이름은 어떨까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/lotto/LottoCount.java
> +	}
`makeLotto`라는 이름과 달리 내부에서 로또를 만들지 않고 있네요. 더 적절한 이름으로 바꿔보면 어떨까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/lotto/LottoCount.java
> +	private static final int ZERO = 0;
이 상수는 어떤 의미가 있을까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/lotto/LottoDTO.java
> +        return numbers;
필드를 그대로 반환하면 외부에서 `numbers` 필드의 참조를 갖게 되어 필드를 조작할 수 있습니다. 어떻게 하면 해결할 수 있을까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/lotto/LottoStorage.java
> +}
파일 끝에는 빈 줄을 추가해주세요~

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/lotto/RandomLottoNumbersGenerator.java
> +        randomNumbers.addAll(LottoNumbers.getLottoNumbers());
아래처럼 한 줄로 줄일 수도 있겠네요.

```suggestion
        ArrayList<Integer> randomNumbers = new ArrayList<>(LottoNumbers.getLottoNumbers());
```

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/result/RateOfReturn.java
> +    public double getRateOfReturn() {
이 메서드의 테스트도 작성해보면 어떨까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/result/Statistics.java
> +}
두가지 역할을 갖는 것으로 보여요.

1. 등수 정의
2. 등수 별 통계

한 가지 역할만 하도록 분리해보면 어떨까요?

또한 enum이 mutable한 상태를 갖는 것이 바람직한지에 대해서도 고민해보시면 좋겠어요.

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/winningnumber/LottoWinningNumber.java
> +	public LottoWinningNumber(String numbers) {
인자가 `String`인 것으로 미루어보아 "1,2,3,4"와 같은 문자열이 전달되겠네요.

`List<Integer>`로 받으면 불필요한 유효성 검사를 할 필요가 없을텐데요. 문자열로 받아야만 하는 이유가 있을까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/model/lotto/LottoNumbers.java
> +public class LottoNumbers {
이 클래스는 어떤 역할을 하는 걸까요?

2022-02-24 13:17 UTC, Laterality commented on src/main/java/utils/InputValidateUtils.java
> +    private static final int LOTTO_MAX_NUMBER = 45;
로또 숫자의 최소/최댓값은 상당히 의미있는 숫자인데요. 그럼에도 불구하고 동일한 값의 상수가 여러 클래스에서 중복으로 사용되고 있습니다. 어떻게 하면 중복을 줄이고 이 정보들을 한곳에 모을 수 있을까요?

2022-02-24 13:17 UTC, Laterality commented on src/test/java/model/bonusball/BonusBallTest.java
> +    void validateBonusBallBlank(String number) {
앞의 코멘트에서 말씀드린 것처럼 `BonusBall`과는 별로 관계가 없는 로직임에도 불구하고 `String`을 인자로 받으면서 이런 검증까지 테스트가 필요한데요. 어떻게하면 불필요한 검증 로직을 줄이고 더 중요한 부분에 집중할 수 있을까요?

2022-02-26 08:45 UTC, shindong96 commented on src/main/java/model/bonusball/BonusBall.java
> +        InputValidateUtils.inputNumber(number, BONUS_BALL_NUMBER_ERROR_MESSAGE);
nextInt()를 이용하게 되면 따로 메서드를 만들 필요는 없을 것 같아요! 그런데 제가 아직 정수형이 입력되지 않은 경우에 어떻게 처리해야 하는지 익숙치 않네요...view에서 바로 InputMismatchException를 catch해서 반복해도 되나 싶은 생각도 들구요. 그리고 지금 공백이 입력되는 경우에 유효성 검사하는 법을 찾고 싶은데 잘 안보이네요..공백을 입력하면 그냥 무언가를 입력할 때까지 줄바꿈만 일어나요 혹시 방법이 있을까요?

2022-02-26 09:08 UTC, shindong96 commented on src/main/java/model/lotto/LottoCount.java
> +	private static final int ZERO = 0;
개인적으로 현재 미션에서 별 의미없는 상수라고 생각합니다. 말 그대로 0개를 뜻한다고 생각해요. 단순히 값을 하드코딩 하지 않기 위해 만든 상수인데 상수에 어떤 의미(e.g. 최소 남겨 둬야 하는 개수 등)를 부여해서 상수명을 바꾸는게 맞나요? 아니면 이런 류의 값은 상수화를 하지 않고 0을 써도 문제가 없는 걸까요?

2022-02-26 09:17 UTC, shindong96 commented on src/main/java/model/lotto/LottoDTO.java
> +        return numbers;
DTO객체는 단순히 값을 전달해주기 위한 객체이기 때문에 단순히 getter를 사용해도 된다고 생각했어요ㅜ Lotto객체의 값만 바뀌지 않으면 된다고 생각했는데 아닌건가요?...

2022-02-27 06:17 UTC, shindong96 commented on src/main/java/model/result/Statistics.java
> +}
고민해본 결과 enum은 등수 정의라는 역할만 갖는 것이 맞다는 생각을 했습니다! 그리고 역할을 나누니 테스트 케이스에서 생기던 문제도 자연히 해결되었습니다.

2022-02-27 06:18 UTC, shindong96 commented on src/main/java/model/lotto/Lotto.java
> +    private long compareWithWinningNumber(List<Integer> winningNumbers) {
좋은 것 같아요! 바꿔보겠습니다!

2022-02-27 06:36 UTC, shindong96 commented on src/main/java/utils/InputValidateUtils.java
> +    private static final int LOTTO_MAX_NUMBER = 45;
LottoRule 이라는 객체를  만들었습니다!

2022-02-27 06:37 UTC, shindong96 commented on src/main/java/model/lotto/LottoNumbers.java
> +public class LottoNumbers {
RandomLottoNumbersGenerator객체와 합쳐도 될 것 같아요. 수정했습니다!

2022-02-27 08:59 UTC, shindong96 commented on src/main/java/model/lotto/Lotto.java
> +    public void compare(BonusBallDTO bonusBallDTO, LottoWinningNumberDTO winningNumberDTO) {
compare라는 단어 뒤에 부연 설명이 있다면 결과 반환하지 않아도 써도 될까요? 비교한다는 의미를 나타내고 싶은 경우에 더 좋은 용어가 생각이 나지 않아요...

2022-02-27 09:23 UTC, shindong96 commented
안녕하세요 에단, 아스피입니다.
피드백 너무 감사해요! 덕분에 여러 고민들을 해보았습니다 :)

피드백 중에 가장 큰 고민을 하게 하고 아직 해결하지 못한 부분이 있는데요...int형으로 입력받으면 유효성 검사를 줄일 수 있는 부분입니다ㅜ
제가 한 번도 안해봐서 그런지 nextInt를 사용할 때 에러 처리를 애먹고 있습니다. 때문에 해당 피드백에 대한 수정을 주석처리 해둔 상태예요. nextInt를 사용할 때 아무것도 입력하지 않은 상황에서 enter를 칠 경우 무언가 입력될 때까지 줄바꿈만 일어납니다. 이 경우는 에러발생을 시키지 않아도 될까요?

그리고 인스턴스의 재사용에 대해서 고민을 해보았는데요. 제가 제대로 생각한 것인지 모르겠지만 main에서 컨트롤러를 하나만들어서 playGame 메서드를 여러번 사용할 수 있는가에 대한 고민을 해보았어요. 그러다보니 enum의 사용법이 잘못되었다는걸 쉽게 알 수 있더라구요! 그래서 수정하게 되었습니다.
제가 혹시 재사용에 대해 더 생각해봐야 할 부분이 있을까요? 피드백을 주시면 열심히 고민해보겠습니다!

마지막으로, view에서 에러처리를 바로 해도 되는가에 대한 고민입니다. 개인적으로 에러가 발생하면 컨트롤러에서 다시 inputView가 입력을 받도록 시키는 구조를 만들고 싶었습니다. 에러 메세지에 대한 출력은 outputView에게 시키고요. 그런데 nextInt를 사용하려고 하니 inputView에서 처리하는게 더 용이할 수도 있겠다는 생각이 들었습니다. 개인적으로 전자를 고집하고 싶은데 어떤가요?

피드백 주시면 더 좋은 코드를 열심히 고민해볼게요! 부탁드리겠습니다 :)

2022-02-27 12:34 UTC, Laterality requested changes
안녕하세요 아스피,

고민되는 부분들이 있으셨군요. 아래 남겨드린 답변 참고해보시고, 궁금하신 점은 또 질문 남겨주세요 :)

변경해주신 부분들에 대해서도 코멘트 남겨드렸습니다. 확인 부탁드릴게요.

## Q&A

* 뷰의 예외 처리에 관해 과제에 나와있지 않은 부분들은 자유롭게 정하시면 됩니다. 오류 메시지를 출력하고 종료하는 방법도 있고, 일정 횟수까지 다시 입력받는 방법도 있겠네요. 코멘트에 따로 남겨드렸지만 공백을 받아 예외처리 하시려면 `nextLine`을 사용하셔야 할 듯해요.
* 피드백 해드린 내용을 이해하셨다면 현재로서는 충분해보입니다. 앞으로 과제나 프로젝트를 수행하시면서 재사용성에 관해 본인의 철학이나 기준을 잡아나가시면 되겠습니다.
* 반대로 질문하면, 왜 뷰에서 예외처리를 하면 안된다고 생각하시나요?

2022-02-27 12:34 UTC, Laterality commented on src/main/java/utils/InputValidateUtils.java
> +    private static final int LOTTO_MAX_NUMBER = 45;
public 상수로 모아두면 여러 클래스가 이 상수를 참조할 수 있게 되는데요. 오히려 상수와 관련된 비지니스 로직들이 여러 군데에서 수행될 수 있어 응집성을 떨어뜨리지 않을까요?

2022-02-27 12:34 UTC, Laterality commented on src/main/java/model/result/Statistics.java
> +public enum Statistics {
더 적절한 이름으로 바꿔보면 어떨까요?

2022-02-27 12:34 UTC, Laterality commented on src/main/java/model/lotto/LottoCount.java
> +	private static final int ZERO = 0;
주변에서 매직 넘버를 상수로 만들라는 이야기를 종종 하는데요. 그 이유를 고민해보시면 답을 찾으실 거라 생각해요.

2022-02-27 12:34 UTC, Laterality commented on src/main/java/model/lotto/LottoDTO.java
> +        return numbers;
DTO는 이름에서 알 수 있듯 서로 다른 컴포넌트(클래스) 사이에 값을 주고 받는 것을 목적으로 하는 객체입니다. 경우에 따라서는 인스턴스가 여러 클래스 사이를 오갈 수도 있고요. 그 중간에 어떤 컴포넌트에서 DTO의 컬렉션 필드를 조작했다면 그 변경이 DTO에 그대로 남고, 이 DTO를 전달하는 다른 인스턴스에도 그대로 남을 수 있어요.

DTO 뿐만 아니라 클래스를 불변으로 만들라는 것과 동일한 관점으로 볼 수 있겠습니다. 컬렉션이 완전하게 불변이 되려면 컬렉션 객체와 컬렉션의 아이템 둘 다 불변이어야 합니다.

2022-02-27 12:34 UTC, Laterality commented on src/main/java/model/lotto/LottoCount.java
> +		count--;
`count`는 음수가 돼도 괜찮은 값일까요?

2022-02-27 12:34 UTC, Laterality commented on src/main/java/model/lotto/Lotto.java
> +    public void compare(BonusBallDTO bonusBallDTO, LottoWinningNumberDTO winningNumberDTO) {
반환타입이 `void`인 메서드는 내부에서 처리한 결과를 호출자에게 반환하지 않는다는 뜻인데요. 즉, 처리된 결과를 반환하는 대신 자신의 내부 혹은 다른 필드를 변형시킨다는 의미인 경우가 많습니다. 수정하신 코드를 에서는 인자로 넘긴 `RateOfReturn` 객체를 조작하는 방식으로 결과를 처리하고 있네요.

메서드의 인자가 많고 이름을 떠올리기 어렵다면 메서드가 너무 많은 일을 하고 있는 것은 아닌지 고민해볼 필요가 있겠습니다. 

테스트할 때 어떤 식으로 결과가 처리되면 테스트하기 용이할까요?

아래와 같은 형태로 로또의 당첨 결과를 알 수 있다면 어떨까요?

```java
Rank rank = winningNumber.match(lotto);
assertThat(rank).isEqualTo(Rank.SECOND);
```

TDD가 주는 큰 이점 중 하나는 단순히 테스트를 작성하게 되는 것이 아니라 그 테스트를 통해 어떤 형태로 기능(메서드)를 제공하면 테스트, 즉, 사용하기 용이한지를 미리 나타낼 수 있다는 점입니다.

모델에 대한 테스트를 먼저 작성하다보면 모델 별로 어떤 역할과 책임을 가져야 할지도 미리 고민하게 되고요.

2022-02-27 12:34 UTC, Laterality commented on src/main/java/model/bonusball/BonusBall.java
> +        InputValidateUtils.inputNumber(number, BONUS_BALL_NUMBER_ERROR_MESSAGE);
뷰의 요구사항에 따라 다를 것 같은데요. 공백 라인이 입력된 경우에 오류 처리하고 싶으신 거라면 `nextLine`으로 입력받고 이를 정수로 변환해야겠네요. 특별히 `nextInt`를 사용해야만 하는 이유는 없어보입니다.

2022-02-27 13:39 UTC, shindong96 commented on src/main/java/model/lotto/LottoCount.java
> +		count--;
count가 0이 아닐 경우에 사용되는 메서드입니다. 좀 더 명확하게 하기 위해 조건을 0 초과일 경우로 바꾸었는데 해결됬다고 볼 수 있을까요? 아니면 해당 메서드 자체에도 문제가 있는 걸까요?

2022-02-27 14:29 UTC, shindong96 commented on src/main/java/utils/InputValidateUtils.java
> +    private static final int LOTTO_MAX_NUMBER = 45;
제가 응집성에 대해 잘 알지 못해서 이해가 어렵네요...ㅜ
해당 상수가 여러 클래스에서 사용됨으로 변경이 불가하게 만들어야 한다고 이해해도 될까요?
아니면 응집성을 위해 한 곳에서 해당 상수가 사용되는 모든 클래스에 지정해주어야 한다는 말인가요?

2022-02-27 14:35 UTC, shindong96 commented
안녕하세요 에단,
피드백을 반영하여 생각해본 결과 저는 공백에 대한 검증도 하기로 생각했습니다! :)
피드백에서 로또의 규칙에 쓰이는 상수들을 모으는 부분을 아직 잘 이해하지 못하는 것 같아요...혹시 조금만 더 힌트를 부탁드려도 될까요?

2022-02-28 03:48 UTC, Laterality requested changes
안녕하세요 아스피,

코멘트에도 남겨드렸지만 추가로 설명해드릴게요 :)

상수로 만들어진 값들 중에는 그 값이 문제 영역(여기서는 로또)에 중요한 의미를 갖고 있는 경우가 있습니다. 예를 들면 로또 숫자의 최소/최댓값이나 로또 숫자 6개로 티켓 하나를 구성한다는 점 등이 있겠네요.

이렇게 문제 영역과 관련된 상수는 문제를 이해하는 데 중요한 역할을 하기도 하고, 언제든 바뀔 수도 있는 값인데요.

이러한 상수를 여러 코드에서 중복해 선언하고 사용한다면 어떻게 될까요?

1. 코드를 이해하기 어렵게 만들고 잠재적으로 응집성을 떨어뜨릴 수 있습니다. 로또 숫자와 관련이 적은 클래스(이를테면 뷰)에서 1과 45라는 값을 상수로 선언해두면 나중에 이 코드를 읽는 다른 사람(혹은 미래의 자신)은 이 숫자가 무얼 의미하는지 한참 고민해야 할 수도 있어요. 또, 이런 상수를 관련성이 적은 곳에 선언하더라도 관련된 지식이 있는 이상 관련된 로직을 수행하게 될 수도 있고요. 입력 뷰에서 로또 숫자의 최대/최솟값을 검증할 수도 있게 되는 것이죠.
2. 요구사항은 언제든 변할 수 있습니다. 만약 게임의 규칙이 바뀌어서 1~60 사이의 숫자를 7개 선택해야 한다면 그에 맞게 코드도 수정이 필요할텐데요. 이와 관련된 상수를 여러 코드에 중복해 선언했다면 이들을 모두 찾아 바꿔야 합니다. 굉장히 번거롭고 실수하기 쉬운 일이에요.

주로 위와 같은 이유로 어떤 문제에 관한 (코드로 표현되는)지식들은 관련된 것들끼리 모아두는 것이 중요합니다.

2022-02-28 03:48 UTC, Laterality commented on src/main/java/model/lotto/LottoCount.java
> +		count--;
count가 0이 아니어야 한다는 것은 이 클래스가 정상적으로 동작하기 위해 필요한 조건인데요.

이 조건을 외부에서 검증한다는 것은 클래스가 외부의 조건에 의존해야 하는 걸까요?

이 메서드를 호출하는 모든 코드가 그 조건을 검증한다는 것을 보장할 수 있을까요?

2022-02-28 03:48 UTC, Laterality commented on src/main/java/utils/InputValidateUtils.java
> +    private static final int LOTTO_MAX_NUMBER = 45;
문제 영역에 관련된 지식들이 한 곳에 모일수록 응집성이 높다고 합니다. 만약 상수가 이러한 지식에 해당한다면 관련된 코드와 함께 두는 것이 문제의 특성을 파악하거나 조건이 바뀌었을 때 대응하기 용이하겠죠?

2022-03-01 02:39 UTC, shindong96 commented on src/main/java/utils/InputValidateUtils.java
> +    private static final int LOTTO_MAX_NUMBER = 45;
관련 코드가 여러 군데 있으면...가장 빈번하게 일어나는 곳에 둬야하나요..?지금 RandomLottoNumbersGenerator, LottoWinningnumber, InputValidateUtils 에서 사용 중인데 어디에 둬야할지 잘 모르겠어요...저는 개인적으로 Rule이라는 객체에 모아 놓으면 규정이 바뀌었을때 바꾸기 더 용이하지 않을까라고 생각했어요!

2022-03-01 02:45 UTC, shindong96 commented
안녕하세요 에단, 
위에 코멘트에도 적었는데 이 규칙에 관한 상수들을 사용하는 코드가 여러군데 있는데 어디에 정의를 해둬야 될지 판단이 잘 안서네요...이건 제가 응집도가 낮게 코드를 짰다는 의미인가 싶은 생각도 드네요. 저는 게임인만큼 rule이라는 객체 안에 상수와 관련된 것들을 정의해두면 규정이 바뀌어도 쉽게 찾아가서 바꿀 수 있을 거라 생각했어요! 
피드백 기다리겠습니다!

2022-03-01 08:58 UTC, Laterality requested changes
안녕하세요 아스피,

질문주신 부분 먼저 답변드릴게요.

미션인 로또 게임에 다양한 규칙이 있을텐데요.

이 규칙들을 어떻게 나눠야 할 지 혼란스러우신 것으로 보여요.

이번에는 코드에 관한 리뷰는 생략하고, 우선 고민하신 아이디어에 관해 이야기해볼게요.

말씀하신 것처럼 `Rule`이라는 클래스에 게임의 규칙과 관련된 모든 상수를 추가한다고 가정하면, 

* 로또 번호의 최소/최댓값
* 로또 번호의 개수
* 로또의 가격

위와 같은 상수들이 추가될텐데요. 이 상수들과 관련된 규칙들이 어떻게 처리되느냐에 따라 두가지 경우를 생각해볼 수 있습니다.

1. `Rule`은 `public` 상수만 정의하고 `Lotto`, `LottoWinningNumber`와 같은 다른 클래스에서 이 상수를 참조하는 경우
    * 규칙을 처리하는 데 굳이 위의 모델 클래스들을 활용할 필요가 없어집니다. 컨트롤러나 심지어는 뷰에서도 저 상수를 참조할 수 있으니까요. 어떤 영역의 코드에서도 상수에 접근 가능하기 때문에 어디서든 비지니스 로직을 구현할 수 있게 됩니다. 비슷한 로직이 중복으로 발생할 수 있겠죠.
    * "default 접근 제어자로 외부 패키지에서 접근하지 못하게 하면 되지 않나?"라고 반문할 수 있을텐데요. 모델 패키지 내에서도 접근을 철저히 관리하지 않으면 여러 모델에서 비지니스 로직이 중복 구현되는 상황은 마찬가지로 발생할 수 있어요. 중복된 코드가 갖는 문제점에 대해서는 일단 생략하도록 할게요.
2. `Rule`이 상수를 `private`으로 선언하고 상수와 관련된 규칙을 모두 내부에서 처리하는 경우
    * `Rule`이 변경에 취약해집니다. 게임의 규칙이 바뀔 때마다 `Rule`을 수정해야 하게 될 텐데요. 만약 기존 규칙이 바뀌는 것 외에 새로운 규칙이나 기능이 100가지 쯤 추가된다면, 그와 관련된 상수나 기능도 이 클래스에 구현해야 할까요? 만약 기존에 이 상수와 규칙들을 사용하던 다른 코드에서는 이 변경에 어떤 영향을 받게 될까요?
    * **단일 책임 원칙**은 클래스가 수정될 이유가 하나여야 한다는 객체지향 원칙 중 하나인데요. 위에서 말씀드린 것처럼 이 클래스는 변경될 이유가 너무 많고, 앞으로도 더 생기게 될 거에요.

위와 같이 `Rule`에 모든 규칙이 집약되면 그 규칙을 내부에서 처리하든, 외부에서 처리하든 문제점이 있어요. 공통적인 문제는 `Rule` 클래스가 변경됐을 때 영향을 받는 코드(=`Rule` 클래스를 사용하는 코드)가 굉장히 많을 거라는 점입니다.

요구사항이 한 번만 주어지는 게 아니라면 소프트웨어는 계속 변화해야 하는데요. 소프트웨어가 안정적으로 계속 변화하려면 변화할 때마다 생기는 영향을 최소한으로 유지할 수 있어야 합니다.

이전 리뷰에서 특정 문제와 관련된 지식을 관련된 것들끼리 두라고 말씀드렸는데요. 소프트웨어에 변화하면서 문제나 지식이 함께 바뀌었을 때, 그 영향을 가능한 문제 영역 내로 한정하기 위함이라고 볼 수 있어요.

2022-03-01 12:41 UTC, shindong96 commented
에단, 피드백을 받고 수정했습니다!
뭔가 스스로 짜놓은 코드 안에서만 방법을 찾다가 더 헤매게 된 기분이네요...ㅜ
피드백 기다리겠습니다!

2022-03-02 12:20 UTC, Laterality requested changes
안녕하세요 아스피,

이전보다 코드가 많이 개선됐네요.

추가로 개선해볼 만한 부분들에 코멘트 남겨드렸는데, 참고 부탁드릴게요.

추가로, 이전 리뷰에서 코멘트 남겨드린 것들 중에 별도로 수정이나 코멘트가 없는 것들이 있는데요. 함께 확인해주세요:

* https://github.com/woowacourse/java-lotto/pull/343/files#r813852869
* https://github.com/woowacourse/java-lotto/pull/343/files#r813844248

2022-03-02 12:20 UTC, Laterality commented on src/main/java/model/lotto/Lotto.java
> +	private static final int CHECKING_BONUS_NUMBER = 5;
이 상수는 `Rank`와 더 관련성이 높은 상수 아닌가요?

2022-03-02 12:20 UTC, Laterality commented on src/main/java/model/lotto/LottoCount.java
> +	private static final int UNIT = 1000;
`RateOfReturn`에도 같은 상수가 선언돼 있네요. 중복을 없앨 수 있을까요?

2022-03-02 12:20 UTC, Laterality commented on src/main/java/model/result/RateOfReturn.java
> +			.filter(rank -> rank.getMatchNumber() >= 3)
이 `3`은 어떤 의미를 갖는 값일까요?

2022-03-02 12:20 UTC, Laterality commented on src/main/java/model/winningnumber/LottoWinningNumber.java
> +		return winningNumbers;
컬렉션을 그대로 반환하고 있네요. 새 컬렉션으로 감싸서 반환하면 어떨까요?

2022-03-02 12:25 UTC, shindong96 commented on src/main/java/model/winningnumber/LottoWinningNumber.java
> +	public LottoWinningNumber(String numbers) {
nextInt와 useDelimeter()를 활용해서 해보려고 생각하였습니다. 그런데 구입 금액을 입력받을 때와 마찬가지로 공백에 대한 검증이 어려울 것 같아 nextLine 메서드를 사용하였습니다!

2022-03-02 12:29 UTC, shindong96 commented on src/test/java/model/bonusball/BonusBallTest.java
> +    void validateBonusBallBlank(String number) {
공백에 대한 검증이 필요없다면 nextInt와 InputMismatchExcpetion을 이용할 수 있을 것 같습니다! 그런데 공백 입력 시에 대한 검증을 위해 nextLine메서드를 활용하였습니다.

2022-03-02 13:02 UTC, shindong96 commented on src/main/java/model/winningnumber/LottoWinningNumber.java
> +		return winningNumbers;
새 컬렉션에 감싸서 반환하는 방식이 훨씬 좋은 것 같아요! 그런데 하나 궁금한 점이 getter 함수도 새 컬렉션으로 감싸서 반환을 하나요?

2022-03-02 13:03 UTC, shindong96 commented on src/main/java/model/result/RateOfReturn.java
> +			.filter(rank -> rank.getMatchNumber() >= 3)
REWARD_NUMBER로 Rank에 선언한다음 Rank 내부 메서드 확인하는 방식으로 처리할 수 있게 수정했습니다! 그게 더 응집도가 높아진다고 생각하는데 맞을까요...?

2022-03-02 13:05 UTC, shindong96 commented on src/main/java/model/lotto/LottoCount.java
> +	private static final int UNIT = 1000;
LottoNumber에서 처리하려다가 LottoCount가 정상 생성이 된다면 RateOfReturn에는 그냥 입력한 금액을 저장해주면 된다는 생각을 하게 되었어요! 수익률을 위해 money를 저장하는 것이기 때문에 RateOfReturn에서는 단위에 대한 생각은 필요없다고 여겨져서 수정했습니다.

2022-03-02 13:07 UTC, shindong96 commented on src/main/java/model/lotto/Lotto.java
> +	private static final int CHECKING_BONUS_NUMBER = 5;
그렇네요! 
그런데 이 상수를 Rank에 선언하는 것 보다 Rank.BONUS.getMatchNumber를 사용해서 비교하는게 더 맞다고 생각하게 되었어요! BONUS의 matchNumber를 수정하게 되면 상수도 변경해야하니까요. 어떨까요...?

2022-03-02 13:14 UTC, shindong96 commented
안녕하세요 에단!
제가 너무 수동적으로 보완해서 비슷한 피드백을 또 받게 되었네요. 좀 더 능동적으로 하겠습니다!
사실 앞선 피드백에서 수정하지 않은 점은 LottoCount에 구입 금액을 입력받을 경우에 공백 검증을 위해서 nextLine 메서드를 쓰기로 생각해서 winningNumber나 BonusBall의 입력 또한 공백 검증을 위해 nextLine 메서드를 사용해야겠다고 생각했습니다. 혹시 다른 경우인가요?
피드백 늘 감사드리고 기다리겠습니다!!

2022-03-02 23:57 UTC, Laterality requested changes
안녕하세요 아스피,

모델에 관해 좀더 고민해볼 만한 부분에 코멘트를 남겨드렸어요.

공백 검증에 관해 질문을 남겨주셨는데요. 

모델(`LottoCount`, `BonusBall` 등)이 입력 방법(`nextInt`를 사용하는지, `nextLine`을 사용하는지)에 대해 알고 있어야 하는 걸까요?

뷰가 바뀌어서 입력 방식이 변경되면 뷰가 `List<String>` 같은 입력을 반환하는 경우도 생길 수 있을텐데요. 이 경우에는 어떻게 해야할까요? 

컨트롤러에서 `,`로 리스트를 `join`하거나 모델에 `List<String>`을 인자로 받는 생성자와 이 인자에 대한 검증도 추가해야 할까요?

모델의 책임이 어디까지일지 한번 고민해보시면 좋은 인사이트가 생길 거라 생각해요.

궁금하신 점은 언제든 DM 남겨주세요~

2022-03-02 23:57 UTC, Laterality commented on src/main/java/model/winningnumber/LottoWinningNumber.java
> +		return winningNumbers;
getter가 내부의 컬렉션을 그대로 반환하면 외부에서 필드를 마음대로 조작할 수 있게 됩니다. 

결과적으로는 setter를 노출하는 것과 크게 다르지 않겠죠?

2022-03-02 23:57 UTC, Laterality commented on src/main/java/model/result/RateOfReturn.java
> +			.filter(rank -> rank.getMatchNumber() >= 3)
네, `Rank`와 관련된 상수라면 함께 두는 편이 좋겠네요. 관련된 지식을 잘 모아두는 것도 중요하지만, 다른 사람이 이해하기 쉽게 명명하고 배치하는 것도 중요합니다 :)

2022-03-02 23:57 UTC, Laterality commented on src/main/java/model/lotto/Lotto.java
> +	private static final int CHECKING_BONUS_NUMBER = 5;
👍

2022-03-02 23:57 UTC, Laterality commented on src/test/java/model/bonusball/BonusBallTest.java
> +    void validateBonusBallBlank(String number) {
공백 뿐만 아니라 다른 문자열 입력에 대해서도 유효성 검증이 필요한 상황으로 보여요. 이러한 입력값을 검증하는 것이 `BonusBall`의 관심사일까요?

2022-03-02 23:57 UTC, Laterality commented on src/main/java/model/winningnumber/LottoWinningNumber.java
> +	public LottoWinningNumber(String numbers) {
이 클래스가 입력 방법에 대해서도 알고 있는 걸까요?

2022-03-02 23:57 UTC, Laterality commented on src/main/java/model/lotto/LottoNumber.java
> +public class LottoNumber {
static 메서드만 있는 모델은 어떤 역할을 하는 걸까요?

2022-03-03 11:23 UTC, shindong96 commented on src/main/java/model/lotto/LottoNumber.java
> +public class LottoNumber {
LottoNumber의 역할이 검증뿐인가에 대해 생각하다가 방향을 바꿔서 LottoNumber를 1-45까지의 int를 나타내는 자료형?처럼 구현해보았습니다! 그리고 Integer처럼 사용하게 해봤는데, 사실 질문해주신 처음에 구현한 static 메서드만 있는 모델은 어떤 역할을 하지는 검증말고는 잘모르겠네요...

2022-03-03 11:25 UTC, shindong96 commented
안녕하세요 에단!
피드백을 받고 수정해보았습니다!
이번 피드백에서 무언가 제일 많이 느낀거 같아요 :)
감사하고 또 피드백 기다리겠습니다!!

2022-03-03 13:16 UTC, Laterality approved these changes
안녕하세요 아스피,

잘 수정해주셨어요 👍 

코드를 더 간결하고, 의도는 명확하게 나타낼 수 있도록 코멘트를 남겨드렸는데요. 

아직 2단계 미션이 남아 있으니 1단계는 여기서 머지하도록 할게요.

코멘트 남겨드린 부분은 2단계 미션 진행하시면서 함께 확인해주시면 좋겠어요.

고생 많으셨고, 2단계에서 봬요 :)

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/lotto/LottoNumber.java
> +public class LottoNumber {
좋습니다 👍 

클래스를 추가할 때는, 이 클래스에 어떤 역할과 책임을 부여해야 할 지 깊이 고민해보시는 게 중요합니다. 단순히 메서드나 상수를 분리할 목적으로 만들어진 클래스는 모델이 복잡해질수록 제 역할을 찾지 못할 가능성이 높아요.

추가로, 최소/최댓값을 나타내는 상수를 `LottoMachine`이 이용해 숫자를 생성하는데요. 어떻게 하면 상수를 `private`으로 유지하면서 숫자를 생성할 수 있을지 고민해보시면 좋겠습니다.

예를 들면 아래와 같은 형태가 될 수 있을텐데요.

```java
LottoNumber autoLottoNumber = LottoNumber.from(new AutoLottoGenerator)
```

만약 위와 같은 코드로 로또 번호를 생성하려면 `LottoGenerator` 인터페이스는 어떻게 바뀌어야 할까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/bonusball/BonusBall.java
> +public class BonusBall {
단순히 `LottoNumber`를 래핑한 클래스네요. 무엇을 위해 필요한 클래스일까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/winningnumber/LottoWinningNumber.java
> +	public void validateReduplicationWithBonusBall(LottoNumber number) {
이 메서드는 왜 외부에서 호출되는 걸까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/controller/LottoController.java
> +			//InputValidateUtils.inputNumber(String.join("", numbers), WINNING_NUMBER_ERROR_MESSAGE);
불필요한 코드라면 제거해주세요~

2022-03-03 13:16 UTC, Laterality commented on src/main/java/controller/LottoController.java
> +	}
재귀호출로 해결하시는 거라면 아래와 같은 방식은 어떨까요?

```suggestion
        private LottoStorage makeLottos() {
		try {
			String money = inputView.inputMoney();
			InputValidateUtils.inputBlankAndNumber(money, LOTTO_COUNT_BLANK_ERROR_MESSAGE,
				LOTTO_COUNT_NUMBER_ERROR_MESSAGE);
			storeMoneyInRateOfReturn(Integer.parseInt(money));
			LottoStorage lottoStorage = new LottoStorage(new LottoCount(Integer.parseInt(money)));
                        outputView.printLottos(lottoStorage.getLottoStorageDTO());
                        return lottoStorage;
		} catch (Exception e) {
			outputView.printErrorMessage(e.getMessage());
			return makeLottos();
		}
	}
```

2022-03-03 13:16 UTC, Laterality commented on src/main/java/controller/LottoController.java
> +	private static final String WINNING_NUMBER_ERROR_MESSAGE = "[Error]: 당첨 번호는 숫자여야 합니다.";
사용되지 않는 상수는 제거하면 어떨까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/lotto/LottoStorage.java
> +public class LottoStorage {
`Storage`라는 이름으로 보아 어떤 객체(아마 `Lotto`겠네요)를 저장하는 역할로 보이는데요. 

단순히 인자로 받은 객체를 저장하는 게 아니라 정해진 규칙에 따라 내부에서 로또를 생성하고 내부 컬렉션에 추가하네요.

뿐만 아니라 로또를 비교하는 역할도 하고 있는데요. 

이 클래스는 어떤 책임을 갖는 걸까요? 역할을 더 잘 나타낼 수 있는 이름으로 바꿔보면 어떨까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/lottonumber/LottoNumber.java
> +	LottoNumber(int number) {
정적 팩토리 메서드로 생성하는 방식이라면 생성자는 `private`으로 선언하면 어떨까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/lottonumber/LottoNumber.java
> +	static final int LOTTO_MAX_NUM = 45;
이 클래스에서만 사용되는 상수라면 `private`으로 선언하면 어떨까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/lottonumber/LottoNumber.java
> +	}
`LOTTO_SIZE` 상수는 위 두 메서드에서만 사용되는데, 두 메서드는 `static`으로 선언돼 있고 로또 숫자를 다루는 `LottoNumber` 클래스의 역할과는 연관성이 적어보입니다.

`LottoNumbers` 같은 클래스가 로또 숫자의 길이(`6`)를 갖고 로또 숫자들을 생성하면 어떨까요?

아래와 같은 코드가 될 수 있겠네요.

```java
public class LottoNumbers {
    private static final int LOTTO_SIZE = 6;
    
    private final List<LottoNumber> lottoNumbers;
    
    private LottoNumbers(List<LottoNumber> lottoNumbers) {
        this.lottoNumbers = lottoNumbers;
    }
    
    public static LottoNumbers from(LottoNumberGenerationStrategy generationStrategy) {
        List<LottoNumber> generatedLottoNumbers = IntStream.range(0, LOTTO_SIZE)
                .map(() -> LottoNumber.of(generationStrategy))
                .collect(Collectors.toList());
        
        return new LottoNumbers(generatedLottoNumbers);
    }
}
```

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/lottonumber/LottoNumber.java
> +	}
만들어진 컬렉션을 반환하는 대신 인자로 받은 컬렉션 객체에 추가하는 방식은 어떤 이점이 있을까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/lottonumber/LottoNumber.java
> +		return Integer.valueOf(number);
불필요한 박싱은 아닐까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/result/Rank.java
> +	TWO(2, 0),
위 세 인스턴스는 쓰이는 곳이 없습니다.

1등을 나타내기에는 `SIX`보다 `FIRST`가 명확하지 않을까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/result/RateOfReturn.java
> +	public void saveResult(Rank rank) {
결과를 저장한다기보다는 특정 등수의 당첨 횟수를 증가시키는 동작으로 보여요. 더 적절한 이름으로 바꿔보면 어떨까요?

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/result/RateOfReturn.java
> +		countOfResult.put(rank, countOfResult.getOrDefault(rank, 0) + 1);
생성자에서 미리 아래처럼 맵을 초기화해두면 더 간결하게 처리할 수 있겠어요.

```java
    public RateOfReturn(int money) {
        this.money = money;
        this.sumMoneyOfReturns = 0;
        countOfResult = new HashMap<>();
        for (final Rank r : Rank.values()) {
            countOfResult.put(r, 0);
        }
    }

    public void saveResult(Rank rank) {
        countOfResult.compute(rank, (r, count) -> count + 1);
    }
```

2022-03-03 13:16 UTC, Laterality commented on src/main/java/model/result/RateOfReturn.java
> +	public int countStatistics(Rank rank) {
`getCountOfRank` 같은 이름은 어떨까요?

2022-03-03 13:16 UTC, merged

2022-03-03 15:10 UTC, shindong96 commented on src/main/java/model/lottonumber/LottoNumber.java
> +	}
크게 없을 것 같아요! 수정하겠습니다!

2022-03-04 14:48 UTC, shindong96 commented on src/main/java/controller/LottoController.java
> +	}
혹시 이렇게 하는 방식의 이점이 있나요?