[1단계 - 로또(자동)] 루나(남민정) 미션 제출합니다.
woowacourse/java-lotto pull request #349
Opened 2022-02-24 06:25 UTC by RunaNam

안녕하세요 제이! 😀
이번 미션에 도움받게될 루나라고 합니다. 잘부탁드려요 :)

미션 진행중에 생겼던 궁금증을 몇가지 질문드리려고 합니다. 

-----

## 질문사항들
### 1. Stream API와 for

- 저는 Stream API가 다소 어색해서 사용할 때마다 조금씩 헤메거나 자연스럽게 for문부터 생각하는 경향이 있는데요, 페어와 이야기를 해보았으나 정확하게 결론이 나지는 않은 것 같습니다. 
- 혹시 제이는 `Stream`과 `for문` 둘 중 하나를 선택하시는 것에 있어서 나름의 기준이 있으실까요? 공유해주시면 감사할 것 같습니다.

### 2. 정적 팩터리 메서드
- 이번에 정적 팩터리 메서드를 사용해보려고 시도해보았는데요, 이펙티브 자바를 통해서 공부를 하기는 했으나, 아직은 어색한 것이 사실인 것 같습니다. 
- public 생성자와 정적팩터리 메서드를 사용하는 것에 있어 조언을 부탁드려도 될까요?
- 일단 현재는 정적 팩터리 메서드가 이름을 통해서 명확하게 보여준다는 장점과 같은 객체를 반환할 수 있다는 장점을 이해하고 있습니다. (해당 장점은 `LottoNumber`의 캐싱에 활용하였습니다.)

### 3. 상수의 위치
- 페어와 상수의 위치에 대해서 고민을 조금 해보았는데, 상수의 위치를 기존에는 `Constants`라는 파일에 전부 넣어놓는 방식을 사용했다가 이렇게 사용하면 오히려 부적절할 수 있다는 이야기를 하였습니다.
- 이에 `Messages`는 따로 모아서 관리하되, 각 파일 내에서만 사용되는 내용들은 각 파일에 두는 방식으로 구현하였는데요, 제이가 생각하는 상수의 적절한 배치는 어떤 방식인지 여쭤보고 싶습니다.

2022-02-24 15:15 UTC, jjj0611 requested changes
안녕하세요 루나! 리뷰어 제이입니다.


1. Stream API와 for

forEach 메서드를 사용하는 경우가 아니라면 대부분 Stream을 사용하는데, 최근 몇개월간은 for를 쓸 일이 거의 없었던 것 같아요!


2. 정적 팩터리 메서드

정적 팩토리 메서드의 특징을 생각해보면 활용도가 있을 것 같아요. 언제 쓰고 언제 안 쓰고는 이런 상황에서 써야한다는 것보다 그 특성을 이해하면 조금 더 자연스러운 사용성이 보일거에요. 일단 정적 팩토리 메서드의 특징을 루나가 한 번 정리해보고 사용성의 장점도 한 번 정리해보면 어떨까요??


3. 상수의 위치

상수가 가지는 '역할'이 분명히 있을 것 같아요. 그 역할에 따라 위치가 정해져야 하지 않을까요? 결국 데이터는 그 데이터가 필요한 곳에 있어야 적절한 곳이라고 생각합니다. 이번에 메시지 같은 것을 한데 모아두셨는데, 그렇게 되면 메시지에 대한 변경이 일어날 때 그곳을 가면 된다는 장점은 있지만, 모든 클래스들이 해당 상수 클래스에 대한 의존성을 갖는 객체가 되겠죠! 이것도 적절한 트레이드오프라고 생각해요. 정답은 없고, 그 트레이드 오프에서 잘 고민해보면 좋을 것 같아요 :)

---

로또 1단계 진행하시느라 고생하셨습니다!
간단하게 코멘트 몇 개 드렸으니 확인 해보시고 전체적으로 반영해주시면 좋을 것 같아요!
혹시 코멘트 관련해서 이해가 가지 않는 부분이 있으면 코멘트 주시거나 DM 주시면 답변 드릴게요 :)

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/Money.java
> +    private final int UNIT = 1000;
키워드 하나가 빠진 것 같지 않나요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/Money.java
> +        MoneyValidator.validate(money);
Validator를 따로 생성하신 이유가 있을까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/LottoNumber.java
> +    private static final List<LottoNumber> CACHE = new ArrayList<>();
static block에서 생성하면 어떨까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/LottoNumber.java
> +        LottoNumberValidator.validate(number);
여기도 Validator를 따로 생성하신 이유가 있을까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/LottoNumber.java
> +        return CACHE.get(number - 1);
-1은 어떤 의미일까요? 매직 넘버에 의미를 부여해주세요!
혹은 number를 기반으로 LottoNumber를 찾는 다른 방법도 있을 것 같아요 :)

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
LottoNumber라는 객체로 모든 원시값을 포장하면서, 의미를 잘 부여해주셨네요.
더불어서 cache를 사용해서 객체의 재생성을 막은 부분도 좋습니다.

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/LottoNumbers.java
> +    public LottoNumbers(List<LottoNumber> lottoNumbers) {
LottoNumbers에 대한 규칙도 있을 것 같아요. 이 부분은 아마 2단계를 진행하시면서 반영이 될 것 같네요 :)

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/LottoNumbers.java
> +public class LottoNumbers {
LottoNumbers에 대한 의미가 LottoNumber cache를 의미할 수도 있지 않나요?
좀 더 의미를 명확하게 만들어볼까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/LottoNumbers.java
> +    }
여기에 있어야 하는 메서드일지 고민해보면 좋을 것 같아요!

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/LottoNumbers.java
> +    }
역시 여기에 있어야 하는 메서드일지 고민해보면 좋을 것 같아요 :)

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/controller/MainController.java
> +        }
루나! 로또를 구매하게 되면, 내 번호에 당첨 번호를 가져와서 비교하기보다는
당첨 번호에 내 번호를 가져가서 비교하게 될거에요!
좀 더 자연스러운 흐름으로 비교를 해볼까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/controller/MainController.java
> +        OutputView.printProfit((float) result.getPrice() / (float) money.get());
객체에서 꺼내지 말고 메시지를 보내보면 어떨까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/Rank.java
> +    DEFAULT(0, 0),
Defulat라는 이름을 지어주신 이유가 뭘까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/domain/Rank.java
> +    FIRST(2000000000, 6);
2등과 3등의 차이를 어떻게 알 수 있을까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/utils/Separator.java
> +public class Separator {
Separator는 어떤 의미일까요??
사용되는 곳이 한 곳인데 Validator처럼 따로 클래스로 뺀 이유가 있나요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/utils/Separator.java
> +    public static final String REGEX = ", ";
public일 이유가 있을까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/validator/InputValidator.java
> +	}
어떤 역할을 하는지 정확하게 알기가 어려워요.
입력 검증자가 옳바른 패턴인지를 REGEX라는 친구를 이용해서 판단하는데,
어떤 입력인지?
옳바르다는 것은 어떤 것인지?
REGEX는 뭐에 대한 REGEX인지?
를 알기가 어려운 것 같아요

전체적으로 Validator를 사용하면서 의미가 모호한 것들이 많은데,
조금 단호한 피드백을 드릴게요 Validator를 모두 제거해주세요!

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/validator/LottoNumberValidator.java
> +		isRightNumberRange(number);
메서드로 따로 분리하신 이유가 있을까요?

2022-02-24 15:15 UTC, jjj0611 commented on src/main/java/view/InputView.java
> +		Scanner scanner = new Scanner(System.in);
Scanner를 매 메서드마다 생성하는 이유가 있을까요??

2022-02-24 15:15 UTC, jjj0611 commented on src/test/java/domain/MoneyTest.java
> +class MoneyTest {
예외 상황에 대한 테스트가 작성되지 않은 것 같아요!

2022-02-24 15:15 UTC, jjj0611 commented on src/test/java/domain/LottoNumberTest.java
> +class LottoNumberTest {
역시 예외 상황에 대한 테스트가 누락되었네요!

2022-02-25 08:33 UTC, RunaNam commented on src/main/java/domain/Money.java
> +    private final int UNIT = 1000;
MONEY_UNIT으로 바꿔보겠습니다.

2022-02-25 08:37 UTC, RunaNam commented on src/main/java/domain/LottoNumber.java
> +    private static final List<LottoNumber> CACHE = new ArrayList<>();
그렇게 수정해보도록 하겠습니다!

2022-02-25 08:41 UTC, RunaNam commented on src/main/java/domain/LottoNumber.java
> +        LottoNumberValidator.validate(number);
validator를 생성한것은 아니고, 캐시에서 값을 가져오기 전 validator 내부의 validate 메서드를 호출(해당 number range가 적절한지 확인)한 것인데, 이해하기 어려운 코드였을까요...?

2022-02-25 08:41 UTC, RunaNam commented on src/main/java/domain/LottoNumber.java
> +        return CACHE.get(number - 1);
해당 부분에 상수화 혹은 로직 수정해보겠습니다!

2022-02-25 08:42 UTC, RunaNam commented on src/main/java/domain/LottoNumbers.java
> +    public LottoNumbers(List<LottoNumber> lottoNumbers) {
맞습니다! 해당 부분은 2단계를 진행하며 넣게될 것 같아 현재는 자동으로 만들어주기 때문에 추가적인 검증로직을 추가하지는 않았습니다.

2022-02-25 08:44 UTC, RunaNam commented on src/main/java/domain/LottoNumbers.java
> +public class LottoNumbers {
네 모호하겠네요. 클래스 명 수정해보겠습니다!

2022-02-25 08:46 UTC, RunaNam commented on src/main/java/controller/MainController.java
> +        }
위의 두개 피드백과 동일한 것 같아 이곳에서 답변드립니다.
왠지 개발 과정에서 자연스럽게 `로또에서 확인하면 되겠지` 라고 생각했는데, 생각해보니 당첨번호에 비교하게 되는게 더 자연스러운 흐름인 것 같네요. 수정하겠습니다!

2022-02-25 08:47 UTC, RunaNam commented on src/main/java/controller/MainController.java
> +        OutputView.printProfit((float) result.getPrice() / (float) money.get());
getter 말고 다른 방식을 말씀하시는 걸까요...? 고민해서 수정해보도록 하겠습니다!

2022-02-25 08:49 UTC, RunaNam commented on src/main/java/domain/Rank.java
> +    FIRST(2000000000, 6);
2등과 3등의 차이는 보너스 번호의 일치 여부로 확인하도록 구성하였습니다.  주석이 필요했던 부분이었던 것 같네요. Rank의 내용에 대한 추가적인 주석을 추가하도록 하겠습니다.


```
    public static Rank of(int matchCount, boolean isBonus) {
        return Arrays.stream(Rank.values())
                .filter(rank -> rank.isMatch(matchCount))
                .filter(rank -> rank.equals(SECOND) || !isBonus)
                .findFirst()
                .orElse(DEFAULT);
    }
```

2022-02-25 08:49 UTC, RunaNam commented on src/main/java/domain/Rank.java
> +    DEFAULT(0, 0),
로또가 3개 이상 맞지 않았을 경우 기본적으로 들어가는 값이기 때문에 default 라는 이름을 정했습니다.

2022-02-25 08:50 UTC, RunaNam commented on src/main/java/utils/Separator.java
> +    public static final String REGEX = ", ";
이부분은 실수였네요....! 수정하겠습니다.

2022-02-25 08:52 UTC, RunaNam commented on src/main/java/validator/InputValidator.java
> +	}
다른 부분에도 Validator에 대한 피드백이 있어서, 한 곳에 대답하는 것이 보시기 편하실 것 같아 한곳에서 답변드리도록 하겠습니다.

일단 Validator를 나누게 된 이유는 `검증하는 메서드가 해당 도메인의 책임인가?` 에 대해서 고민하다가 `각각 도메인의 검증부분을 분리하는 것이 더 명확한 책임이지 않을까` 라는 결론이 나왔기 때문이었습니다.

하지만 말씀해주셨던 대로 의미가 모호한 것 역시 단점이라고 생각합니다.  질문 주신 내용들에 대해서 생각을 해본 결과, 어떤 입력이고 무엇에 대한 검증인지 확실하게 표현하기 위해서 해당 검증 관련 클래스들을 모두 해당 내용에 넣어서 진행하도록 하겠습니다. 👍

2022-02-25 08:53 UTC, RunaNam commented on src/test/java/domain/MoneyTest.java
> +class MoneyTest {
예외상황의 테스트 추가하겠습니다!

2022-02-25 08:53 UTC, RunaNam commented on src/test/java/domain/LottoNumberTest.java
> +class LottoNumberTest {
위와같이 추가하도록 하겠습니다.

2022-02-25 08:54 UTC, RunaNam commented on src/main/java/validator/LottoNumberValidator.java
> +		isRightNumberRange(number);
Validator에서 validate - 각각의 개별 검증 메서드의 구조로 짠 이유는 혹시 이후에 다른 검증 로직이 추가될 경우 보다 유연하게 하기 위해서 일단 기본적으로 다음과 같은 구조를 짠 것이었습니다!

2022-02-25 08:55 UTC, RunaNam commented on src/main/java/view/InputView.java
> +		Scanner scanner = new Scanner(System.in);
이유가 없던 부분이었습니다... 코드 중복이네요. 수정하겠습니다.

2022-02-25 09:00 UTC, RunaNam commented on src/main/java/domain/Money.java
> +        MoneyValidator.validate(money);
아래와 동일한 내용인 것 같아, 아래에 진행했습니다!

2022-02-25 09:04 UTC, RunaNam commented on src/main/java/utils/Separator.java
> +public class Separator {
쉼표로 나누는 부분을 따로 뺀 것이었는데, 해당 부분도 validator와 동일하게 사용하는 부분으로 넣어서 진행하도록 하겠습니다.

2022-02-26 07:39 UTC, RunaNam commented
안녕하세요 제이, 정성스러운 리뷰 정말 감사합니다. 👍👍😆
덕분에 오래 생각해보는 시간을 갖게된 것 같아요.

## 1. Stream API와 for
Stream API 같은 경우에는 제가 더 공부를 해서 제대로 적용해보아야겠네요..! 다음 미션의 목표로 삼아보도록 하겠습니다.

## 2. 정적 팩터리 메서드
간단하게 정리해보았습니다. 이펙티브 자바를 참고하였습니다 :) 

장점
- 반환될 객체의 특성을 묘사하는 이름을 지을 수 있다.
- 호출될 때마다 새로운 인스턴스를 생성하지 않아도 된다 (이는 LottoNumber를 만들때 고려한 점과 일치합니다)
- 변환 타입의 하위 객체를 반환할 수 있다.
- 매개변수에 따라 다른 클래스 인스턴스를 반환할 수 있다.

단점
- 상속을 하려면 public이나 protected 생성자가 필요하다. 
- 프로그래머가 찾기 어려울 수 있으나, 기본적으로 알려진 네이밍 컨벤션을 활용하여 사용할 수 있다.

결론적으로 LottoNumber와 WinLottoNumber를 사용함에 있어서 정적 팩터리 메서드를 사용한 것은 괜찮은 방향성이었던 것 같습니다. 아직은 조금 어색한 부분이 있으나, 이 또한 구현을 계속 연습하며 익혀나갈 부분이라고 생각합니다. 생각해볼 수 있도록 도와주셔서 감사합니다! :)

## 3. 상수의 위치
상수는 조금 더 고민해보았는데, 현재 프로그램은 그렇게 구조가 복잡하지는 않은 것 같습니다.
따라서 메시지는 일단 지금처럼 두고, 해당 상수가 사용되는 곳에 따로 나머지는 두는 방식으로 해도 좋을 것 같아서 다른 수정을 하지 않았습니다.

----

피드백 주신 사항들에 대해서 여러모로 생각해보며 코드를 수정해보았습니다. 
감사합니다! 😊

2022-02-26 07:41 UTC, RunaNam commented on src/main/java/view/InputView.java
> +    private static Scanner scanner;
이부분에서
private static Scanner scanner = new Scanner(System.in);으로 생성한 뒤 메서드들에서 사용하려고 하니 제대로 작동이 되지 않는 문제가 있어 지금과 같이 구현을 했는데요... 찾아도 원인이 잘 나오지 않네요 ㅠㅠ...
정적 변수이기 때문에 공용으로 사용되어 메서드 내에서 스캐너가 close 되는 걸까요?

2022-02-26 14:20 UTC, jjj0611 approved these changes
안녕하세요 루나! 리뷰어 제이입니다.

남겨드린 내용에 대해서 아주 잘 정리하고,
고민하여 적용해주셨네요! 감사합니다.

정적 팩토리 메서드의 장점으로 언급해주신, 
`호출될 때마다 새로운 인스턴스를 생성하지 않아도 된다 (이는 LottoNumber를 만들때 고려한 점과 일치합니다)` 
이 부분은 항상 그런 것은 아니고, 이미 생성된 인스턴스를 재사용 할 수 있다. 정도로 이야기하는 것이 좋을 것 같아요! WinLottoNumbers 같은 부분은 정적 팩토리 메서드를 사용했지만, 호출될 때마다 새로운 인스턴스를 생성하고 있거든요!

그 외 다른 고민할만한 부분은 코멘트로 드렸어요!
1단계 코드는 이만 머지하고, 해당 내용들은 2단계를 진행하시면서 적용해주세요!
그리고 2단계 pr을 주실 때 이번 코멘트에서 이해가지 않는 점이나 반영한 부분들도 같이 이야기 해주시면 좋을 것 같아요 :)

1단계 고생하셨습니다!
2단계에서 뵈어요~~(2단계 요청을 빨리 주시면 빨리 주실수록 저랑 더 많이 이야기 해볼 수 있을 것 같아요!)

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/Money.java
> +    private final int MONEY_UNIT = 1000;
엇 이 부분은 네이밍에 대한 것보다 static 키워드가 빠지지 않았나 해서 여쭤봤던 부분이었어요!!

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/Rank.java
> +    DEFAULT(0, 0),
3개 이상 맞지 않았을 경우는 기본값이라기보다는 미당첨 혹은 꽝 정도이지 않을까요??!
기본값이라는 의미가 정확한가에 대한 고민을 해보면 좋을 것 같아요

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/Rank.java
> +    FIRST(2000000000, 6);
이 역시도 enum하나하나는 각각의 인스턴스입니다!
그렇다면 인스턴스가 본인의 조건 (보너스 볼 일치 여부)에 대해 알고 있어야 하지 않을까요?
일부(일치하는 번호의 개수)는 알고 있고 일부(보너스 볼 일치 여부)는 모르고 있는 것 같은데 어떻게 생각하시나요??

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/Rank.java
> +            .filter(rank -> rank.equals(SECOND) || !isBonus)   // 2등과 3등을 구별짓는 로직. (보너스 여부 확인)
루나 지금은 주석을 하나도 사용하지 않고 작성하는 연습을 해보면 좋을 것 같아요!

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/Money.java
> +    }
수익률은 돈에서 구하는게 좋을까요? 결과에서 구하는게 좋을까요??

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/Result.java
> +        return price;
간단하게 stream 예제로 보여드리면
```
results.entrySet()
            .stream()
            .mapToLong(entry -> (long) entry.getKey().getPrizeMoney() * entry.getValue())
            .sum();
```

요렇게 표현이 가능하겠네요!
stream을 연습해두면 유용하게 사용하실 수 있습니다!

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/WinLottoNumbers.java
> +    }
validate를 호출하는 곳이 static factory method네요.
실제 호출하는 곳은 생성자인 것이 더 좋지 않을까요?
또다른 메서드가 추가되어도 검증이 생성자에서 된다면 중복 체크를 피할 수 있을거에요 :)

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/WinLottoNumbers.java
> +    }
test에서만 사용중인 메서드 같은데, 어떤 용도로 만들어두셨을까요? ??

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/domain/WinLottoNumbers.java
> +    }
당첨 번호와 로또 티켓이 함께 일해서 결과물을 만들어낼 수 있지 않을까요??

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/utils/Separator.java
> +public class Separator {
엇 아뇨 util 클래스를 따로 빼는 것은 문제라고 생각하진 않아요.
다만 그런 util성 클래스를 무분별하게 만들경우 문제가 많이 발생할 수 있습니다.
학습을 하시면서는 최대한 역할을 객체 내로 응축시킬 필요가 있다고 생각합니다!

현재 WinLottoNumbers가 정말 쉼표에 대한걸 모른다고 생각하시나요??
Separator라는 클래스를 만들어서 쉼표 자체를 옮길 수는 있지만,
어짜피 WinLottoNumbers는 Seperator에 대한 의존이 생기고, 쉼표와 완전히 분리된 상태라고 말하기 어려울 것 같아요.
이 내용이 WinLottoNumbers에 들어갔을 때 모호해진다고 생각을 하셨는데, 그렇다면, Separator를 가지고 있는 순간 이미 모호한 상태인 것 아닐까요??

2022-02-26 14:20 UTC, jjj0611 commented on src/main/java/view/InputView.java
> +    private static Scanner scanner;
어떤 부분에서 제대로 작동하지 않는다는지 이해 갔어요!
scanner의 nextInt와 nextLine이 어떻게 동작하는지 한 번 찾아볼까요? :)

2022-02-26 14:21 UTC, merged