[1단계 - 로또(자동)] 로마(김범수) 미션 제출합니다.
woowacourse/java-lotto pull request #353
Opened 2022-02-24 06:33 UTC by kbsat

안녕하세요 럿고! 이번 로또 미션에서 만나게 되서 반갑습니다!
이번 로또 미션도 잘 부탁드립니다!

2022-02-24 09:33 UTC, lowoon requested changes
반가워요 로마! 리뷰어 로운입니다! 😄
작성하신 코드 잘 확인했습니다. 👍
피드백 몇 가지 남겨봤으니 확인 부탁드려요.
궁금한 점이 생기면 언제든지 DM 혹은 댓글남주세요 ^-^

2022-02-24 09:33 UTC, lowoon commented on src/main/java/lotto/view/ResultView.java
> +    }
기본 생성자를 만든 이유가 있나요??

2022-02-24 09:33 UTC, lowoon commented on src/main/java/lotto/domain/LottoPrize.java
> +    FIRST(6, 0, new Money(2000000000));
5_000와 같이 세번째 단위마다 _를 넣어주는게 보기 좋답니다 😄

2022-02-24 09:33 UTC, lowoon commented on src/main/java/lotto/utils/LottoGenerator.java
> +                .forEach(number -> originLottoNumbers.add(new LottoNumber(number)));
forEach를 쓰기 보다 for를 쓰는게 더 명확해요.
stream을 쓴다면 List를 반환해서 originLottoNumbers에 할당할 수도 있겠네요.

https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/

2022-02-24 09:33 UTC, lowoon commented on src/main/java/lotto/domain/Money.java
> +    }
단지 get()을 하는 것은 어떤 것을 return 하는지 불명확하지 않을까요??

2022-02-24 09:33 UTC, lowoon commented on src/main/java/lotto/controller/LottoController.java
> +        Money purchaseMoney = new Money(InputView.requestPurchaseMoney());
controller에서 view를 호출하는게 맞을까요??
controller의 역할은 무엇일까요??

2022-02-24 09:33 UTC, lowoon commented on src/main/java/lotto/view/ResultView.java
> +        for (LottoPrize prize : LottoPrize.values()) {
view까지 domain이 넘어와도 괜찮을까요??

https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/

2022-02-24 09:33 UTC, lowoon commented on src/main/java/lotto/domain/Lottos.java
> +        int purchaseNumber = money.canBuyNumber(LOTTO_PRICE);
Lottos에 money가 넘어와서 개수만큼 사게되는데요. 역할에 맞는 로직의 메서드일까요??
LottoGame, Lottos, Money의 역할이 어떻게 될까요??

2022-02-24 09:35 UTC, kbsat commented on src/main/java/lotto/view/ResultView.java
> +    }
내부에 static 메서드만 사용하기 때문에 인스턴스 생성을 막기 위해서 private 생성자를 사용했습니다.

2022-02-24 09:51 UTC, kbsat commented on src/main/java/lotto/domain/LottoPrize.java
> +    FIRST(6, 0, new Money(2000000000));
오 감사합니다! 바로 적용해보겠습니다 👍

2022-02-24 10:17 UTC, kbsat commented on src/main/java/lotto/utils/LottoGenerator.java
> +                .forEach(number -> originLottoNumbers.add(new LottoNumber(number)));
for를 이용해서 구현해보겠습니다

2022-02-24 10:25 UTC, kbsat commented on src/main/java/lotto/domain/Money.java
> +    }
클래스 네임이 Money이기 때문에 충분히 의미전달이 될 것이라고 생각했는데 getAmount()로 바꾸는 것이 더 명확하겠네요!

2022-02-24 10:28 UTC, kbsat commented on src/main/java/lotto/controller/LottoController.java
> +        Money purchaseMoney = new Money(InputView.requestPurchaseMoney());
컨트롤러는 뷰와 도메인을 연결하는 다리 역할을 하고있다고 생각합니다.
그렇기 때문에 컨트롤러에서 도메인의 정보를 뷰로 전달하기 위해 view를 호출했습니다!

2022-02-24 10:35 UTC, kbsat commented on src/main/java/lotto/domain/Lottos.java
> +        int purchaseNumber = money.canBuyNumber(LOTTO_PRICE);
생각해보니 역할에 맞지 않은 것 같습니다. 또한 Lottos에서 생성하고 purchase를 하는 순서를 지켜서 동작해야 정상 동작하는 불편함이 있었는데 이를 생성자로 주입받도록 바꾸고 Lottos 내부에 들어가는 로또 구매 로직은 Lottos 바깥의 LottoGame에 주어야겠다고 생각합니다.

이를 기준으로 다시 잡아본 역할로는 아래와 같습니다.
- LottoGame : 로또를 구매하고 로또스에 당첨 확인 메세지를 전송하는 역할
- Lottos : 구매한 로또들을 한 곳에서 관리하고 로또를 당첨번호와 확인하는 역할
- Money : 돈을 담당하는 변수를 포장하여 음수의 돈이 나오지 못하게 막는 역할

2022-02-26 09:08 UTC, kbsat commented on src/main/java/lotto/utils/LottoGenerator.java
> +                .forEach(number -> originLottoNumbers.add(new LottoNumber(number)));
foreach를 사용하지 않고 stream을 써서 할당하는 방법으로 변경해보았습니다.

2022-02-26 12:03 UTC, kbsat commented on src/main/java/lotto/view/ResultView.java
> +        for (LottoPrize prize : LottoPrize.values()) {
저는 도메인에 뷰에 관련된 로직을 넣는 것은 안되지만 뷰에서는 도메인 관련해서 어느정도 알고 있는 것은 괜찮다고 생각하기 때문에 view까지 어느정도 domain이 넘어와도 괜찮다고 생각합니다.

물론 DTO를 사용하면서 얻는 이점도 있겠지만 저는 현재의 수준에서는 DTO의 이점이 과연 필요할까라는 의문이 듭니다.

현재 LottoResults는 외부에서 내부 상태를 변경하는 로직이 없고 domain에서 값을 처리해서 내보내주는 getter의 로직만 있습니다. 그렇기 때문에 view에서 알더라도 사이드이펙트가 발생하지 않을 것이라고 생각합니다. DTO를 사용해서 한 번 더 감싸서 보내주는 것과 LottoResults를 그대로 보내주는 것의 큰 차이를 느끼지 못했고 저는 도메인을 그대로 넘기는 선택을 했습니다.

로운은 이 부분에 대해서 어떻게 생각하시는지 로운의 생각도 궁금합니다!

2022-02-26 13:26 UTC, lowoon commented on src/main/java/lotto/view/ResultView.java
> +    }
생성자를 만들지 않으면 생성을 할 수가 없으니 private도 만들 필요가 없지 않을까요??

2022-02-26 13:28 UTC, lowoon commented on src/main/java/lotto/view/ResultView.java
> +        for (LottoPrize prize : LottoPrize.values()) {
현재 정도의 프로그램에서는 필요가 없을 수 있으나 현재 학습을 하는 것이기 때문에 dto를 사용해 보는것을 추천드립니다.
그리고 로마가 생각하는 사이드 이펙트에는 어떤것이 있을까요?? 설명에 나온 비지니스 method를 호출하는 것이외에요.
도메인에 개인정보와 같이 중요한 정보가 있을 때에 그대로 노출될 수 있지 않을까요??

2022-02-26 13:31 UTC, lowoon commented on src/main/java/lotto/controller/LottoController.java
> +        Money purchaseMoney = new Money(InputView.requestPurchaseMoney());
현재는 console의 형태로 되어 있어서 동작을 할텐데요.
만약 web이나 app의 형태로 되었을 때에는 어떻게 될까요??

2022-02-26 14:02 UTC, lowoon requested changes
고생하셨어요. 로마! 
리뷰 반영 잘 해주셨어요! 단순히 코멘트대로 하는 것이 아닌 자신만의 방법을 찾아보는 것 좋았습니다 👍 
몇 가지 코멘트 남겼으니 확인해주시고 궁금한 점은 언제든지 DM 주세요 :)

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/utils/LottoGenerator.java
> +                .collect(Collectors.toList());
테스트가 없네요??
그리고 로또 숫자만 생성을 하는 것인데 생성하는 로또 숫자 개수를 여기에서 알고 있는 것이 맞을까요??

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/domain/Money.java
> +        if (number < 0) {
0도 상수화하는 것이 좋지 않을까요??

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/utils/LottoGenerator.java
> +public class LottoGenerator {
생성하는 것이 Lotto가 아닌 LottoNumber인데 이름이 맞을까요??

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/domain/LottoPrize.java
> +    private final int lottoNumberMatches;
matches는 의미가 명확하지 않은거 같아요. 개수를 명시해주는게 낫지 않을까요??

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/domain/LottoPrize.java
> +    private final int bonusNumberMatches;
true/false값으로 하지 않은 이유가 있을까요??

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/domain/LottoPrize.java
> +                .filter(prize -> !(prize.equals(THIRD)) || prize.bonusNumberMatches == bonusNumberMatches)
실제 결과가 3등일 때 2등과 3등이 모두 통과된 후 findFirst에서 첫번째 것을 가져오게 될텐데 이게 맞을까요??
enum의 순서가 지금과 같지 않으면 제대로 동작을 하지 않겠네요??

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/domain/Lottos.java
> +            result.put(prize, result.get(prize) + 1);
`result.merge(prize, 1, Integer::sum)`도 가능하답니다

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/domain/LottoResults.java
> +            totalReward += prize.getTotalReward(prizeNumber);
이 부분도 돈과 관련된 로직인데 money를 통해서 로직이 동작하지 않은 이유가 있나요??

2022-02-26 14:02 UTC, lowoon commented on src/main/java/lotto/domain/LottoResults.java
> +        if (results == null) {
`Objects.isNull()`을 사용해주는 것이 좋답니다.

2022-02-27 18:54 UTC, kbsat commented on src/main/java/lotto/view/ResultView.java
> +    }
생성자를 만들지 않으면 자동으로 디폴트 생성자가 생성되기 때문에 static 메서드만 존재하는 클래스는 private으로 생성를 제한해주어야 합니다!

2022-02-28 03:10 UTC, kbsat commented on src/main/java/lotto/utils/LottoGenerator.java
> +public class LottoGenerator {
로운 말을 듣고 생각해보니 LottoGenerator라고 하면 Lotto 객체를 생성해야 할 것 같네요!
그래서 해당 클래스 이름을 LottoNumbersGenerator로 변경했습니다!😄

2022-02-28 03:14 UTC, kbsat commented on src/main/java/lotto/domain/Money.java
> +        if (number < 0) {
제 생각에는 매직 넘버, 매직 리터럴을 상수화하여 사용하는 이유는 해당 넘버, 리터럴이 무엇을 의미하는지 모르고 코드를 읽는데 어려움을 준다는데 있는 것 같습니다. 
하지만 해당 부분에 사용된 0의 경우에는 그 의미가 분명하고 코드를 보면 바로 이해가 가기 때문에 상수화의 대상이 되지 않아도 된다고 생각합니다. 🤔
NUMBER_ZERO와 같은 상수도 생각해보았지만 이보다는 0이라는 숫자 그대로 놓는 것이 더 가독성에 도움이 될거라 생각하여 상수화하지 않았습니다!

2022-02-28 03:20 UTC, kbsat commented on src/main/java/lotto/utils/LottoGenerator.java
> +                .collect(Collectors.toList());
1. 아마 shuffle을 사용해서 테스트가 어려울 것이라 생각했기 때문에 테스트 코드를 작성을 미루다가 깜빡하고 작성하지 않은 것 같습니다. shuffle 자체를 테스트하기 어려우니 해당 메서드로 생성된 리스트의 사이즈가 6인지 확인하는 테스트를 작성해보았습니다.

2. 처음에 클래스 내에서 상수를 작성할 때 private만 사용해야된다는 생각을 가지고 있었습니다. 😅 하지만 크루들과 이야기해보니 이는 고정관념이었고 public으로 풀어줘도 되겠다는 생각이 들었습니다. 로운의 말대로 로또 숫자 개수는 이미 로또에서 상수처리 되어 관리되고 있었습니다. 이를 public으로 풀어주어 해당 LottoGenerator에서도 사용할 수 있도록 변경했고 해당 클래스는 직접 상수를 작성해 사용하지 않는 방향으로 바꾸었습니다. 😄

2022-02-28 03:21 UTC, kbsat commented on src/main/java/lotto/domain/LottoPrize.java
> +    private final int lottoNumberMatches;
로운 말에 동의합니다! `lottoNumberMatchCount` 로 이름을 변경해주었습니다. 이름이 좀 길지만 의미는 명확하게 전달될 것이라 생각합니다!

2022-02-28 03:24 UTC, kbsat commented on src/main/java/lotto/domain/LottoPrize.java
> +    private final int bonusNumberMatches;
처음에 설계를 잘못했던 것 같습니다.😅 
지금 생각해보니 단순히 0과 1의 값만 가지는데 이를 굳이 담아낼 필요가 없을 뿐더러 LottoPrize 상수 내에 이를 적용함으로써 2등과 3등은 문제없지만 4등, 5등에 대해서는 BONUS가 0일 때만 당첨될 수 있다는 잘못된 의미를 담을 수도 있다고 생각이 듭니다. 그렇기에 저는 이 BONUS에 대한 필드를 제거하고 match 시에 보너스 넘버가 존재하는지 boolean값을 인자로 받아 판별하는 방식으로 변경해보았습니다. 😀

```java
public enum LottoPrize {

    FIRST(6, 2_000_000_000),
    SECOND(5, 30_000_000),
    THIRD(5, 1_500_000),
    FOURTH(4, 50_000),
    FIFTH(3, 5_000),
    MISS(0, 0);

    private final int lottoNumberMatchCount;
    private final int reward;

    LottoPrize(int lottoNumberMatchCount, int reward) {
        this.lottoNumberMatchCount = lottoNumberMatchCount;
        this.reward = reward;
    }
}
```

2022-02-28 03:29 UTC, kbsat commented on src/main/java/lotto/domain/LottoPrize.java
> +                .filter(prize -> !(prize.equals(THIRD)) || prize.bonusNumberMatches == bonusNumberMatches)
이것 또한 로직을 잘못 짠 것 같습니다. 😅 
로운의 말대로 enum의 순서가 변경된다면 제대로 동작하지않습니다. 저 코드를 작성할 때 stream으로 어떻게든 해결해보려 생각하다가 저런 로직을 작성했던 것 같습니다. 반성하고 있습니다. 😂

그래서 이번에는 stream 이전에 미리 2등과 3등에 대한 처리를 해버리자 라고 생각했습니다. 그래서 다음과 같이 코드를 작성했습니다.

```java
  public static LottoPrize match(int lottoNumberMatches, boolean bonusNumberMatch) {
      if (lottoNumberMatches == SECOND.lottoNumberMatchCount) {
          return getSecondOrThirdPrize(bonusNumberMatch);
      }

      return Arrays.stream(LottoPrize.values())
              .filter(prize -> prize.lottoNumberMatchCount == lottoNumberMatches)
              .findFirst()
              .orElse(MISS);

  }

  private static LottoPrize getSecondOrThirdPrize(boolean bonusNumberMatch) {
      if (bonusNumberMatch) {
          return SECOND;
      }
      return THIRD;
  }

```

2022-02-28 03:30 UTC, kbsat commented on src/main/java/lotto/domain/Lottos.java
> +            result.put(prize, result.get(prize) + 1);
오 그런 방법도 있었군요! 감사합니다 로운 😃

2022-02-28 03:39 UTC, kbsat commented on src/main/java/lotto/domain/LottoResults.java
> +        if (results == null) {
크루들과 이야기해보니 `Objects.requireNonNull` 에서 validateNull의 기능을 해줄 수 있다고 알게되었습니다! 이를 사용해도 괜찮을 것 같습니다.

근데 고민이 되는 부분이 있습니다. null 체크의 정도에 대해서인데 입력받은 인자가 null일 때 NPE를 미리 잡아내고 지정된 에러 메세지를 호출하기 위해 사용하는 것이 null 체크라고 생각합니다.
그런데 이렇게 생각하면 참조변수가 인자로 달린 모든 메서드에서 null 체크를 해줘야 할 것 같은 생각이 들었습니다. 현재 코드에서는 그럴 일은 없지만 만일 프로그램이 커져서 협업을 한다면? 동료가 인자로 잘못 null 값을 넣어줄 수 있기 때문에 이를 방지할 수 있습니다. 그런데 한편으로 생각해보면 너무 과하다 라는 생각도 듭니다.

로운은 이 점에 대해서 어떻게 생각하시는지 궁금합니다! 🧐

2022-02-28 03:45 UTC, kbsat commented on src/main/java/lotto/view/ResultView.java
> +        for (LottoPrize prize : LottoPrize.values()) {
로운의 말에 동의합니다! 
제가 생각하는 추가적인 사이드 이펙트는 만약 도메인이 커져서 필드가 많아지게 된다면 도메인을 그대로 넘길 경우에 필요하지 않은 getter 마저 노출될 우려가 있다고 생각합니다. 그리고 DTO를 사용하지 않는다면 뷰에서 원하는 내용이 추가됨에 따라 도메인에 뷰를 위한 필드나 로직이 추가될 우려 또한 존재합니다! 

위와 같은 경우에는 도메인을 넘기는 것을 고집하는 것이 아닌 DTO를 무조건 사용해야된다고 생각합니다! 뷰는 변경이 잦고 이에 대응하기 위해서 도메인을 변경하는 것보다 DTO를 변경하는 것이 더 안전하다고 생각합니다. 😀

2022-02-28 03:57 UTC, kbsat commented on src/main/java/lotto/controller/LottoController.java
> +        Money purchaseMoney = new Money(InputView.requestPurchaseMoney());
로운의 리뷰를 듣고 고민도 많이 해보고 크루들과 해당 내용을 가지고 토론도 해보았습니다. 그리고 제가 정리한 내용을 커멘트로 달아보겠습니다! 

웹 형태를 생각해보면 Controller는 단순히 url로 입력을 받으면 이를 매핑하고 이에 적합한 작업을 도메인을 이용해 수행하도록 합니다. 그리고 작업의 결과를 포장하여 반환합니다. view에서는 이 작업된 결과물을 받아 화면에 뿌려주게 됩니다. 

이 관점에서 본다면 제 코드와 같이 Controller 내부에 View가 호출되는 것은 굉장히 어색해보입니다. 어쩌면 Controller와 View가 어느 한쪽에 소속된 것이 아니라 각각 동등한 위치에서 작업을 하는 느낌이랄까요? Controller에서 직접 View에게 "이거 호출해!" 라고 말하는 것이 아닌 단순히 값을 반환하고 이를 View가 알아서 처리하는 구조로 보입니다.

크루들과 이야기해보면서 느낀건 어쩌면 그동안 제가 MVC 패턴을 잘못 이해하고 있고 그저 이름만 가져다 붙인 것이 아닌가 생각이 들어 반성도 하게 되었습니다. 로운의 생각도 궁금한데요 ㅋㅋ.. 🧐 

이런 고민들은 생각도 못해봤던 것 같습니다. 양질의 고민을 할 수 있게 도움을 준 로운에게 감사드립니다 😁

2022-02-28 05:33 UTC, lowoon commented on src/main/java/lotto/view/ResultView.java
> +    }
대부분 util을 만들때 기본생성자를 막아두지 않아서 생각해보지 않았던 문제네요!
util의 경우 static 메서드만 있어 개발자가 생성을 하는 경우가 없어 그런거 같은데 로마처럼 막아주는 것이 확실하겠네요! 💯

2022-02-28 05:38 UTC, lowoon commented on src/main/java/lotto/domain/Money.java
> +        if (number < 0) {
Money 객체 안에 상수로 적용된 것이 있길래 말씀드린 것이었어요.
혹시나 실수로 넘겼나 해서요!
의도적으로 한 것이고 로마의 의견이 있으면 좋은 방법이라고 생각합니다 💯 
상수를 무조건적으로 사용하는 것도 가독성이나 다른 개발자들이 파악하기 힘들 수 있으니까요!

2022-02-28 05:49 UTC, lowoon commented on src/main/java/lotto/controller/LottoController.java
> +        Money purchaseMoney = new Money(InputView.requestPurchaseMoney());
토론과 고민 너무 좋네요! 💯 중간에 '각각 동등한 위치에서 작업'이라는 느낌이 맞을 거 같아요!

제가 물어본 이유는 `View는 Console에만 국한된 것이 아니라 웹과 같이 다른 종류도 위치할 수 있다` 때문이었어요.
view를 통해 사용자의 값을 입력받은 것을 web에서 아이디/패스워드를 입력한 것이라고 한다면, 서버가 아이디와 패스워드 값만 받아 검증 및 처리를 하는 것과 같이 controller에 view를 통해 입력된 값만 전달되야하지 않을까요??
기본적으로 서버는 front(view)에 상관없이 요청이 들어오면 같은 형태의 데이터를 보내줄 수 있어야 해서 여쭤보게 됐어요!

물론 위의 경우는 api의 형태이고, controller에서 view자체를 반환하는 경우도 있지만 이러한 부분에 대해 생각해보는게 좋을거 같아 말씀드렸습니다!

2022-02-28 06:19 UTC, lowoon approved these changes
고생하셨어요. 로마! 코멘트에 대해 많이 고민하고, 작성한 코드마다 로마의 생각이 있다는 걸 느꼈어요! 💯 
이전 코멘트 중에 반영이 되지 않은 것들이 있는데요. 이번에 단 몇가지 코멘트와 함께 2단계에서 반영해주세요.
추가적인 궁금증은 이 pr이 머지되어도 댓글 남겨주셔도 좋구 DM도 좋습니다.

2022-02-28 06:19 UTC, lowoon commented on src/test/java/lotto/domain/LottoGameTest.java
> +        assertThatNoException().isThrownBy(LottoGame::new);
`assertDoesNotThrow(() -> LottoGame::new)`를 사용하는 방법도 있답니다~

2022-02-28 06:19 UTC, lowoon commented on src/test/java/lotto/domain/LottoTest.java
> +                .withMessage("로또 숫자는 중복되면 안됩니다.");
```suggestion
        assertThatThrownBy(() -> new WinningLotto(winningLotto, bonusNumber))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("로또 숫자는 중복되면 안됩니다.");
```
를 사용하지 않은 이유가 있을까요??

2022-02-28 06:19 UTC, lowoon commented on src/main/java/lotto/domain/Lotto.java
> +        return LottoPrize.match(lottoNumberMatches, winningLotto.containsBonusNumber(this));
confirmWinning메서드를 WinningLotto에 만들면 this를 넘기는 방식은 사라지지 않을까요??
그리고 메서드명 중에 `lottoGame.purchase`, `winningLotto.containsBonusNumber` 가 있는데요.
`lottoGame이 로또를 산다`, `winningLotto가 보너스번호를 가지고 있는지 확인한다`로 해석이 되는데 어색하지 않을까요??

2022-02-28 06:19 UTC, merged

2022-02-28 06:25 UTC, lowoon commented on src/main/java/lotto/domain/LottoResults.java
> +        if (results == null) {
저의 개인적인 생각은 과하지 않다고 생각해요. 해당 객체를 사용하는 부분에서 객체가 null인지 검증해야 npe가 발생하지 않고, 사용자가 불편을 느끼지 않게 되겠죠??
로마가 말한 것처럼 프로그램이 커지고 협업을 하다보면 모든 부분을 다 알고 있기 힘들고, 객체를 넘겨주는 곳의 로직을 모른채 개발을 할 수도 있습니다. 그렇기 때문에 사용하는 곳에서 null체크를 해주는 것이 개발적으로나 사용성을 위해서나 좋다고 생각해요 😄

2022-03-01 07:52 UTC, kbsat commented on src/main/java/lotto/domain/LottoResults.java
> +            totalReward += prize.getTotalReward(prizeNumber);
결과값을 계산해주는 책임이라고 생각했기 때문에 money를 통해서 로직을 동작하지 않고 Results 내에서 처리했습니다.

2022-03-06 04:08 UTC, lowoon commented on src/main/java/lotto/view/ResultView.java
> +        for (LottoPrize prize : LottoPrize.values()) {
위와 같은 기준과 생각이 있다면 dto를 꼭 사용하지 않아도 된다고 생각합니다ㅎㅎ