[1단계 - 로또(자동)] 토르(손인준) 미션 제출합니다.
woowacourse/java-lotto pull request #361
Opened 2022-02-24 07:04 UTC by injoon2019

안녕하세요 앨런! 리뷰 요청을 드리게 된 토르입니다. 
리뷰 잘 부탁드립니다!

2022-02-24 15:46 UTC, hongbin-dev requested changes
안녕하세요 토르! 리뷰어 앨런입니다.
로또미션 전반적으로 잘 구현해주셨네요 👍
몇 가지 의견 코멘트 남겨봐요. 확인해주세요!

2022-02-24 15:46 UTC, hongbin-dev commented on docs/Rule.md
> +# 페어프로그래밍 시 지켜야 할 규칙
페어를 시작하기전에 규칙을 정해놓고하는게 인상적이네요 👍

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/controller/LottoController.java
> +                .buy(new RandomNumberGenerator(LottoNumber.MIN_LOTTO_NUMBER, LottoNumber.MAX_LOTTO_NUMBER), money);
`LottoTickets.buy()`라는 네이밍으로 코드읽기가 더 좋아졌네요 👍

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/controller/LottoController.java
> +        int[] winningNumbers = InputView.requestWinningNumber();
배열을 꼭 반환해야하는 상황이 아니라면 컬렉션을 사용하는게 어떨까요?

이펙티브 자바 [28. 배열보다 리스트를 사용하라]
[https://rok93.tistory.com/entry/%EC%95%84%EC%9D%B4%ED%85%9C-28-%EB%B0%B0%EC%97%B4%EB%B3%B4%EB%8B%A4-%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC](https://rok93.tistory.com/entry/%EC%95%84%EC%9D%B4%ED%85%9C-28-%EB%B0%B0%EC%97%B4%EB%B3%B4%EB%8B%A4-%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/money/Money.java
> +    }
도메인 객체 내의 매직넘버는 모두 상수로 포장하면 좋겠네요~

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/result/LottoStatistics.java
> +    private final Map<LottoRank, Long> lottoRankCountMap;
자바에서 변수네이밍을 지을 때 관습상 자료구조를 쓰지 않는편이에요.
자료구조를 변경하면 네이밍까지 변경해야하는 의존성을 갖을 것 같아요.

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/result/LottoStatistics.java
> +                .sum();
x가 어떤 의미인지 이해하기 어렵네요. 또 `x.getKey().getPrize() * x.getValue()` 이 부분은 객체에게 메시지를 주는형태로 변경할 순 없을까요?

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/LottoTicket.java
> +    }
이 부분의 생성자가 여러가지 일을 하는 것 같아요. 정렬도하고, 생성도하고요.
만약 정렬하는게 오래걸린다면, 코드를 사용하는 클라이언트 입장에서는 예상치못한 부하가 생길 수 있다고 생각하는데요.

- 생성자에서 정렬을 빼는건 어떨까요? 정적팩토리를 통해서, `정렬한 값을 만든다` 라는 네이밍을 지어질 수 있을 것 같아요
- 정말로 정렬이 필요할까요?

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/LottoTickets.java
> +    private final List<LottoTicket> tickets;
일급컬렉션으로 포장한 점 좋네요 👍

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/LottoTickets.java
> +    }
이 부분 반환타입을 Object로 하신 이유가 있을까요?

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/LottoTickets.java
> +        }
lottoRanks를 생성하고, lottoRanks값을 하나씩 추가하고 있는 구조인데요.
명령형으로 코드를 작성하면 lottoRanks가 가변변수가 되고, 사이드이펙트가 생길 수 있는 여지가 생기는데요.
이 부분을 선언적으로 작성해보는걸 추천드려요.

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/WinningTicket.java
> +    }
어떤 번호인지까지 **상세하게 피드백** 해주시면 좋을 것 같아요

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/WinningTicket.java
> +    }
관습상 boolean을 리턴할 것 같은 네이밍이네요 🤔

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/number/LottoNumber.java
> +    public static final LottoNumber[] LOTTO_NUMBER_CACHE = new LottoNumber[MAX_LOTTO_NUMBER + 1];
배열 자료구조로 사용하신 이유가 있을까요?

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/number/LottoNumber.java
> +    }
- LOTTO_NUMBER_CACHE 선언 + 값을 할당해놓고, 값을 수정하고있는데요. 가변객체로 보입니다. 이 부분을 불변객체로 선언하면 좋을 것 같아요~!
- forEach는 스트림 최종연산으로 비즈니스 로직을 지양하고 있어요. [https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/](https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/) 이 글 한번 읽어보시면 좋을 것 같아요.

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/number/LottoNumber.java
> +    }
두 곳다 validation해주는 게 좋네요 💯

2022-02-24 15:46 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/number/LottoNumber.java
> +    }
이렇게 작성 된 이유가 있을까요?

2022-02-25 06:53 UTC, injoon2019 commented on src/main/java/lotto/controller/LottoController.java
> +                .buy(new RandomNumberGenerator(LottoNumber.MIN_LOTTO_NUMBER, LottoNumber.MAX_LOTTO_NUMBER), money);
네이밍을 하면서 헷갈렸던 부분입니다. 현실에서 로또 티켓은 수동적인 존재이니 사람 같은 클래스가 buy를 해야하나 고민을하다가 로또 티켓을 주관적 객체로 만들었는데 가독성이 더 좋아져서 좋네요 :)

2022-02-25 07:12 UTC, injoon2019 commented on src/main/java/lotto/controller/LottoController.java
> +        int[] winningNumbers = InputView.requestWinningNumber();
감사합니다 수정하였습니다!

2022-02-25 07:15 UTC, injoon2019 commented on src/main/java/lotto/model/money/Money.java
> +    }
네 문자열을 따로 상수로 뺐습니다! 
질문이 하나 있습니다. 여기서 0도 매직넘버로 빼야할까요? 0 자체가 주는 의미가 간결하다고 생각을 하기도해서 앨런의 생각은 어떤지 궁금하네요!

2022-02-25 07:22 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/LottoTicket.java
> +    }
- 정적 팩토리메서드로 빼는 것 좋은 것 같습니다!

- 정렬이 필요한지 페어와 고민을 많이 했는데요, 크게 
1. 정렬된 순서를 유지하는 것은 도메인 규칙이다 (로또를 구매해도 항상 정렬된 번호를 보여주니) 
2. 정렬되지 않아도 로또는 로또다. 그것은 출력 양식일 뿐이다. 라는 의견이 있었습니다. 

만약 출력 양식일 뿐이라면 `OutputView`에서 해줘야하는데, 정렬 같은 비교적 무거운 기능이 `View`에 들어가도 될까하는 생각이 있었습니다. 또한, 현재 `unmodifiableList`로 반환해주기 때문에 `OutputView`에서 정렬을 하려면 `Dto`를 통해서 받아야할 것 같다는 생각이 들어서 도메인에 넣게되었습니다!

2022-02-25 07:26 UTC, injoon2019 commented on src/main/java/lotto/model/result/LottoStatistics.java
> +    private final Map<LottoRank, Long> lottoRankCountMap;
그런 문제가 있네요. 수정하였습니다!

2022-02-25 07:34 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/LottoTickets.java
> +    private final List<LottoTicket> tickets;
일급 컬렉션에 대한 질문이 있습니다. 저는 `LottoRanks`라는 일급 컬렉션을 만들었는데요, 그 이유가
`LottoController`에서 `lottoTickets.compareResult(winningTicket)` 이후 `List<LottoRank>`로 받는게 그 메서드에서 유일하게 `List`로 받으니 조금 안맞다는 생각이 들어서였습니다. 

실제 `LottoRanks`에서는 도메인 로직도 없고 코드가 간단한데 이런 경우데도 일급 컬렉션으로 만들어주는게 맞는걸까요?

2022-02-25 07:36 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/number/LottoNumber.java
> +    }
int를 문자열로 돌려주고 싶어서였는데, 찾아보니 다른 방법이 있네요. `String.valueOf(int)`로 수정하였습니다!

2022-02-26 01:36 UTC, injoon2019 commented on src/main/java/lotto/model/result/LottoStatistics.java
> +                .sum();
그렇네요! `entrySet()`의 stream에서 나왔으니 x는 entry를 의미해서 entry로 변경했습니다. 
안에 객체에게 메시지로 주는 형태를 고민을 해보다가 `lottoRankCountMap` (현재는 `lottoRankCounter`로 수정)은 미리 정의된 자료구조(`Map`)여서 메시지를 보내기 힘들다고 생각하였습니다. 그래서 `lottoRankCounter`를 일급컬렉션으로 재정의해야하나 싶은데 앨런의 생각이 궁금합니다.

2022-02-26 01:38 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/LottoTickets.java
> +    }
인텔리제이 기능을 사용하다가 들어간거 같습니다. `int`로 수정하였습니다!

2022-02-26 01:59 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/WinningTicket.java
> +    }
`judgeRank()`로 한번 수정해보았습니다!

2022-02-26 02:04 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/number/LottoNumber.java
> +    public static final LottoNumber[] LOTTO_NUMBER_CACHE = new LottoNumber[MAX_LOTTO_NUMBER + 1];
코드 작성할 때는 캐싱의 효과를 최대화하기 위해 O(1)에 접근 가능한 자료구조를 택했습니다. 금요일 네오의 강의를 들으니 `ArrayList`는 동적배열이나 내부 구조가 배열과 같다는 것을 알게되었습니다! 그래서 `ArrayList`로 수정을 하였습니다.

2022-02-26 10:46 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/LottoTickets.java
> +        }
`명령형`과 `선언적`에 대해 잘 알지 못해 [이 글](https://iborymagic.tistory.com/73)을 참고하였습니다. 
글을 읽고나서 명령형은 `어떻게`를 직접 일일이 간섭을 하는 것이고, 선언형은 `무엇을`에 집중하고 나머지는 맡긴다고 생각이 들었습니다. 또한 함수형 프로그래밍은 그 선언형을 하도록 도와주는 프로그래밍 방법 중 하나라고 이해했습니다. 
제가 이해한게 맞을까요?

제가 코드를 
``` java
    public LottoRanks compareResult(WinningTicket winningTicket) {
        List<LottoRank> lottoRanks = tickets.stream()
                .map(winningTicket::judgeRank)
                .collect(Collectors.toList());
        return new LottoRanks(lottoRanks);
    }
```
이런식으로 변경하였는데요, 이러면 `lottoRanks`가 여전히 가변적이다고 생각이 들어요. 

``` java
    public LottoRanks compareResult(WinningTicket winningTicket) {
        return new LottoRanks(tickets.stream()
                .map(winningTicket::judgeRank)
                .collect(Collectors.toList()));
    }
```
이렇게 따로 변수로 빼지 않고 바로 인수로 빼면 노출이 안되지만 가독성이 떨어진다고 생각하는데, 앨런의 의견은 어떠신가요?

2022-02-26 11:10 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/number/LottoNumber.java
> +    }
네 감사합니다! 불변객체로 선언하기 위해서 [이 글](https://tecoble.techcourse.co.kr/post/2020-05-18-immutable-object/)을 참고해보았습니다! 

여기서 가변객체로 선언되어서 걱정하시는 부분은, 예를 들어 static 블록안에서 다른 개발자가 getter를 이용해서 List안의 요소 변경을 우려하시는 것 맞으실까요?

2022-02-28 13:43 UTC, hongbin-dev commented on src/main/java/lotto/model/money/Money.java
> +    }
> 0 자체가 주는 의미가 간결하다고 생각을 하기도해서

저도 공감하는 부분입니다! 이 부분에 대해서 코멘트를 남긴 건, 객체지향 생활체조 원칙 `규칙 3: 모든 원시값과 문자열을 포장한다.`처럼 학습을 목적으로 요청드린거에요~

2022-02-28 13:49 UTC, hongbin-dev commented on src/main/java/lotto/model/result/LottoStatistics.java
> +                .sum();
생각해보면 LottoStatistics가 LottoStatistics의 일급컬렉션이라.. 더 복잡해질 우려가 있네요 🥲

코멘트 드린 의미는 rank의 있는 prize(getPrice())를 꺼내서 계산하고 있는데요. 이 부분을
`return entry -> entry.getKey().calculateProfit(entry.getValue());` 이런 형태로 메시지를 전송할 수 있겟다고 생각했어요.

2022-02-28 13:53 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/LottoTicket.java
> +    }
> 정렬된 순서를 유지하는 것은 도메인 규칙이다

- 모델 내에서 정렬이 안되어있으면 문제가 발생하는 부분이 있을까요?
- unmodifiableList로 내려주는 이유가 무엇일까요? 모델에서 뷰에 unmodifiableList를 내려주면, 그 값 그대로 그려줘야할까요?

2022-02-28 14:18 UTC, hongbin-dev approved these changes
안녕하세요 토르!
코멘트 반영해주신거 확인했습니다 🙂 
다음 미션에서 구조가 변경될 것 같아, approve하겠습니다. 고생하셨어요~

2022-02-28 14:18 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/LottoTickets.java
> +    private final List<LottoTicket> tickets;
`로또티켓들 > 로또결과들 > 로또통계` 이런 구조로 설계하셨군요.

지금 당장은 LottoRanks가 생성되고, 값을 반환하는 형태로 되어있어서 무의미하다고 생각이 드실 것 같네요. 이 부분은 학습을 목적으로 생각하셔도 좋을 것 같습니다.

이 부분이 정말 불필요하다면 '로또결과들' 이라는 과정을 생략하고, 로또티켓들에서 로또 통계를 바로 구할 수 있을 것 같아요.

2022-02-28 14:18 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/LottoTickets.java
> +        }
넵 맞습니다. 제가 참고링크를 드리면 좋았을텐데 아쉽네요. 😅

진짜 문제는 이전에 빈 배열을 선언해놓고, 값을 추가하는 행위였어요. 그 중간에 값이 언제든 바뀔 수 있었거든요.
코드 적용해주신 거 둘 다 좋은 것 같아요. 정 걱정되신다면

- 컬렉팅을 `.collect(toUnmodifiableList())` 로 불변 List반환
- `collectingAndThen()` 메서드 사용
두 개도 고려해볼 수 있을 것 같아요 🙂

2022-02-28 14:18 UTC, hongbin-dev commented on src/main/java/lotto/model/ticket/number/LottoNumber.java
> +    }
넵, 이전에 배열구조라면 `LOTTO_NUMBER_CACHE[0] = null` 이런 코드도 사용가능할 가능성이 있네요.

2022-02-28 14:18 UTC, hongbin-dev commented on src/main/java/lotto/model/result/LottoStatistics.java
> +        return 0;
```suggestion
        if (!lottoRankCountMap.contains(rank)) {
            throw...
        }
        return lottoRankCountMap.get(rank); 
```
개인적으로 `return 0;` 같은 방어적코드 보단 throw를 내서 빠른 피드백을 받는형태를 선호해요.

엘레강트 오브젝트에 '절대 NULL을 반환하지 마세요' 부분을 읽어보시면 좋을  것 같아요!

2022-02-28 14:19 UTC, merged

2022-03-01 14:54 UTC, injoon2019 commented on src/main/java/lotto/model/result/LottoStatistics.java
> +                .sum();
아 그 말씀이셨군요. `lottoRankCounter`를 일급 컬렉션으로 한번 더 재정의할지 한번 생각을 해봐야겠네요!

2022-03-01 14:55 UTC, injoon2019 commented on src/main/java/lotto/model/ticket/LottoTicket.java
> +    }
- 모델 내에서 정렬되어 있지 않다고 해서 문제가 발생하는 부분은 없습니다!
- unmodifiableList를 `Dto`로 받아서 그 `Dto`를 정렬하면 될 것 같네요!

2022-03-01 14:58 UTC, injoon2019 commented
> 안녕하세요 토르! 코멘트 반영해주신거 확인했습니다 🙂 다음 미션에서 구조가 변경될 것 같아, approve하겠습니다. 고생하셨어요~

감사합니다. merge 하셨으니 피드백 한번 더 생각해보고 2단계에서 반영해보도록 하겠습니다!

2022-03-02 14:15 UTC, injoon2019 commented on src/main/java/lotto/model/result/LottoStatistics.java
> +        return 0;
제가 코드를 가독성 좋지 않게 작성했던 것 같아요! 
여기서 0은 방어적 코드라기보다는 `lottoRankCounter`에서 해당 등수의 당첨된 것이 없으면 0개 당첨됐다고 반환해주는 값입니다!