[1단계 - 로또(자동)] 라쿤(이병훈) 미션 제출합니다.
woowacourse/java-lotto pull request #368
Opened 2022-02-24 07:13 UTC by nbalance97

안녕하세요 루피!! 이번 2단계 로또 미션 잘 부탁 드립니다!!
원피스를 좋아해서 닉네임에 시선이 많이 가네요ㅎㅎㅎㅎ

이번 미션을 하면서 두가지 질문사항이 있습니다!!

---

1. getter에 대한 질문입니다.

이번에 페어프로그래밍을 하면서 getter을 많이 사용하게 되었습니다. 처음에 LottoTicket에서 하나의 Ticket에 여러개의 Lotto를 가지도록 설계하였으나, 이후 살펴보니 LottoTicket 클래스에서 하는 일은 사실상 LottoTicket 인스턴스를 만들때 Lotto를 생성해주고, 생성된 Lotto 리스트를 반환해주는 역할만 하고 있었습니다.  LottoMachine에서는 각각의 Lotto들의 등수를 구해서 LottoResult 객체에게 전달하기 때문에 실제로 필요한건 LottoTicket의 Lotto 리스트라 이부분을 getter로 구현하였습니다. 이런식으로 구현해도 괜찮을지 루피의 조언을 구하고자 합니다!!

``` java
public class LottoTicket {
    private final List<Lotto> lottos = new ArrayList<>();

    public LottoTicket(int lottoCount, LottoNumberGenerator generatorPolicy) {
        for (int i = 0; i < lottoCount; i++) {
            lottos.add(new Lotto(generatorPolicy.generate()));
        }
    }

    public List<Lotto> getLottos() {
        return Collections.unmodifiableList(lottos);
    }
}
```

``` java
   // LottoMachine
    public LottoResult getResults(WinningLotto winningLotto) {
        for (Lotto lotto : lottoTicket.getLottos()) { // 이부분입니다!!
            lottoResult.putLottoRank(winningLotto.countLottoRank(lotto));
        }
        return lottoResult;
    }
```

2. LottoMachine의 위치
LottoMachine이 domain에 속해야 하는지, controller에 속해야 하는지 모호합니다. LottoMachine에서 View와 상호작용 하는 부분은 없기 때문에 domain인거 같기도 하고, 도메인 객체를 가지기 때문에 controller에 속해야 하는거 같기도 하고 모호하게 느껴져서 이부분에 대해 루피의 생각이 궁금해서 질문 드립니다!

바쁜 와중에도 코드 리뷰를 위해 시간 내어주셔서 감사합니다!!

2022-02-24 13:57 UTC, TheDevLuffy requested changes
안녕하세요 라쿤~

이번에 로또 미션에서 리뷰를 하게 된 루피입니다. 🤠

작성해주신 코드를 기반으로 코멘트 남겨두었는데요.
확인해보시고 추가로 고민한 뒤 다시 리뷰 요청 주세요~

아래는 리뷰요청시 남겨주신 질문에 대한 답변입니다.

1. getter 관련 질문

> 관련해서 코멘트 남겨두었습니다. 도메인의 객체 간에는 메시지를 전달하여 getter 사용을 지양하는 것이 좋습니다. 남겨주신 예시도 도메인에 해당하는 객체들이니, 메시지를 전달하여 풀어내는 것이 충분히 가능해보입니다.

2. LottoMachine 위치

> 도메인 객체를 가진다고 해서 controller 에 속해야 하는 것은 아니고요. 도메인 객체는 객체의 역할과 책임으로 분류하는 것이 더 적절한 방법이라고 생각하는데요. 도메인 객체로 분류해도 괜찮은 것으로 보입니다~ 

고생하셨습니다~ 
궁금한 점은 DM 이나 코멘트 남겨주세요~! 다음 리뷰요청에서 뵈어요 !

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/controller/LottoController.java
> +        LottoMachine lottoMachine = new LottoMachine(money, new ShuffleNumberGenerator());
money 를 LottoMachine 으로 전달하고, 생성자에서 나누기해서 LottoTicket 으로 전달하고 있는데요.

LottoCount 같은 객체를 추가해보는 것은 어떨까요 ?

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/controller/InputController.java
> +                .mapToInt(Integer :: parseInt)
컨벤션을 확인해주세요~

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/Lotto.java
> +    }
생성과 동시에 초기화를 해도 괜찮을 것 같아요.
모든 수가 검증에 통과해야 하니 검증에 통과할때마다 list 에 push 하는 것이 아닌 한번에 초기화하는 방법이 있을 것 같아요.

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/Lotto.java
> +    }
두 가지 검증을 하고 있는데요.
로또 숫자 하나를 표현하는 객체를 추가해서 역할을 분리해보는 것은 어떨까요 ?

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/Lotto.java
> +    public List<Integer> getLottoNumbers() {
해당 메서드는 사용되지 않고 있어요~

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/Lotto.java
> +        return (int) lottoNumbers.stream()
형변환을 하시는 이유가 따로 있으신가요 ?

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoMachine.java
> +        return lottoResult;
getter 없이 메시지를 보내서 구현해보는 것이 어떨까요 ?

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoMachine.java
> +        return lottoResult;
도메인 객체들 끼리는 getter 를 굳이 사용하지 않아도 괜찮을 것 같아요

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoRank.java
> +    private static final int SECOND_AND_THIRD_RANK_COUNT = 5;
사용되지 않고있어요~

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoRank.java
> +                .orElse(RANK_NOTHING);
`RANK_NOTHING(0, false,0)` 를 따로 정의하신 것은 좋아보이네요 ㅎㅎ

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoRank.java
> +public enum LottoRank {
맥 command + option + L
윈도우 ctrl + alt + L
을 누르시면 기본적인 띄어쓰기나 코드 배열이 정리가 되어요

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoResult.java
> +            totalPrice += (long) rank.getPrice() * resultCount.get(rank);
price 를 long 으로 정의해도 괜찮지 않을까요 ?

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoResult.java
> +    private final Map<LottoRank, Integer> resultCount = new LinkedHashMap<>();
자바 11이라면 `Map.of()` 를 사용하셔도 좋을 것 같아요

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoTicket.java
> +    private final List<Lotto> lottos = new ArrayList<>();
자바 11 을 사용하시면 `List.of()` 를 사용하셔도 괜찮을 것 같아요.

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/WinningLotto.java
> +        }
초기화 후에 값을 변경하지 않는 방법도 있지 않을까요 ?

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/util/ShuffleNumberGenerator.java
> +    private final List<Integer> candidateNumber = IntStream.range(LOTTO_NUMBER_MINIMUM, LOTTO_NUMBER_MAXIMUM + 1)
`IntStream range(int startInclusive, int endExclusive)` 와 비슷한
`IntStream.rangeClosed(int startInclusive, int endInclusive)` 도 있어요

참고해보셔도 좋을 것 같아요

2022-02-24 13:57 UTC, TheDevLuffy commented on src/main/java/domain/LottoMachine.java
> +    public void putLotto(LottoRank rank) {
테스트에서만 사용되는 메서드인데요.
꼭 필요한 메서드인가요 ?

2022-02-24 14:13 UTC, TheDevLuffy commented on src/main/java/domain/Lotto.java
> +        return Collections.unmodifiableList(lottoNumbers);
원본인 lottoNumbers 가 변경되어도 괜찮을까요 ?

```
List.copyOf()
```
자바11 에는 위와 같은 메서드가 있어요. 확인해보셔요~

2022-02-25 09:40 UTC, nbalance97 commented on src/main/java/controller/LottoController.java
> +        LottoMachine lottoMachine = new LottoMachine(money, new ShuffleNumberGenerator());
개인적인 생각으로는 로또의 개수를 구할 때 1000으로 나누는 간단한 작업이라 생각해서 객체로 나눌 생각은 하지 않았었습니다. 이러한 경우에도 LottoCount 객체를 만들어서 해당 객체에서 Count를 구해주는 것이 더 나을까요..??

2022-02-25 09:41 UTC, nbalance97 commented on src/main/java/domain/Lotto.java
> +        return (int) lottoNumbers.stream()
.count()의 결과가 long형이 반환되어서 int형으로 형변환을 해주었습니다!! 형변환을 따로 해주지 않으면 에러가 나타나더라구요!!..

2022-02-25 09:42 UTC, nbalance97 commented on src/main/java/controller/InputController.java
> +                .mapToInt(Integer :: parseInt)
수정했습니다!

2022-02-25 09:42 UTC, nbalance97 commented on src/main/java/domain/Lotto.java
> +    public List<Integer> getLottoNumbers() {
수정했습니다!!

2022-02-25 10:13 UTC, nbalance97 commented on src/main/java/domain/LottoRank.java
> +    private static final int SECOND_AND_THIRD_RANK_COUNT = 5;
수정했습니다!!

2022-02-25 10:15 UTC, nbalance97 commented on src/main/java/domain/LottoResult.java
> +            totalPrice += (long) rank.getPrice() * resultCount.get(rank);
감사합니다!! 그부분은 생각 못하고 있었습니다..

2022-02-25 10:22 UTC, nbalance97 commented on src/main/java/domain/WinningLotto.java
> +        }
루피의 조언을 듣고 생각해보니 SECOND_AND_THIRD_RANK_COUNT인 경우에만 BONUS 매개변수에 lotto.checkBonus(bonusNumber)을 넘겨주고, 나머지 경우에는 false를 넘겨주는 방식으로 구현하는게 더 좋을것 같아서 반영하였습니다!!

2022-02-25 13:01 UTC, nbalance97 commented on src/main/java/domain/LottoMachine.java
> +    public void putLotto(LottoRank rank) {
실제 프로덕션에서 필요하지 않은 메소드인것 같아서 삭제하고 해당 메소드를 사용하던 테스트 코드를 수정하였습니다!

2022-02-25 15:20 UTC, nbalance97 commented on src/main/java/domain/Lotto.java
> +    }
루피의 조언을 듣고 중복 검증을 Set 자료구조를 활용하는걸로 변경하였으며, 통과 시에 addAll 메소드를 사용하는걸로 변경하였습니다!ㅎㅎ

2022-02-25 15:29 UTC, nbalance97 commented on src/main/java/domain/Lotto.java
> +    }
처음에는 LottoNumber을 굳이 만들어야 하나 싶기도 했었습니다..ㅋㅋㅋ.. 루피의 조언을 듣고 고민하다 일단 해보자는 마음으로 LottoNumber로 분리해 보니 위 코드에서의 검증의 수를 한개로 줄이는것 뿐 아니라 로또 번호에 대한 검증을 LottoNumber에서 처리해 주니 Lotto나 WinningLotto에서는 중복 검증만 해주면 되니 훨씬 편했습니다! 혹시 도메인을 추출하는 팁이 따로 있을까요??

2022-02-25 15:35 UTC, nbalance97 commented on src/main/java/util/ShuffleNumberGenerator.java
> +    private final List<Integer> candidateNumber = IntStream.range(LOTTO_NUMBER_MINIMUM, LOTTO_NUMBER_MAXIMUM + 1)
감사합니다!! range만 알고 있어서 끝값 처리가 애매했었는데 해결했습니다!!

2022-02-25 16:00 UTC, nbalance97 commented
안녕하세요 루피!! 피드백 덕분에 코드가 훨씬 나아진 것 같습니다 ㅎㅎ

다름이 아니라 추가적인 질문이 있습니다!! List.of, Map.of 메소드를 말씀해 주셨는데 해당 메소드를 타고 넘어가보니 
ImmutableCollections를 반환하는걸 확인했습니다. 사용하기 위해서는 Map같은 경우에는 Entry를 만들어 주고, Entry를 of의 매개변수로 넘겨주는 방식으로 사용할거라고 생각합니다, 제 생각에는 객체에서 List나 Map에 접근해서 값을 수정하거나 추가하기 때문에 현재 방식이 맞는것 같다고 생각이 됩니다.  만약 of 메소드를 쓴다면 어떤 이점이 있는지 궁금합니다! 

또한, 금액으로 로또의 개수를 계산하는 부분이 있는데 해당 부분은 1000으로 나누어주기만 하면 되는 부분이라 LottoCount라는 도메인으로 빼주기엔 너무 도메인이 하는 일이 없는것 같다고 생각이 되서 개인적으로 조금 모호하게 느껴졌습니다. 이 부분에 대해 루피는 어떻게 생각하실지 궁금합니다! 

바쁘신 와중에도 코드리뷰 해주셔서 항상 감사드립니다!!

2022-02-26 13:46 UTC, TheDevLuffy commented on src/main/java/controller/LottoController.java
> +        LottoMachine lottoMachine = new LottoMachine(money, new ShuffleNumberGenerator());
프로그래밍에 답이 없어서 라쿤이 생각해주신 것도 어떤 의도인지 이해가 갑니다 ! ㅎㅎ

아래에 제가 코멘트를 남견 배경은 참고만 해주세요.

`LottoMachine` 라는 도메인 객체에 input 을 그대로 전달하기 보다 값 객체를 만들어 전달하는 것이 어떨까 하여 남긴 코멘트였습니다 ㅎㅎ

2022-02-26 13:52 UTC, TheDevLuffy commented on src/main/java/domain/Lotto.java
> +    }
로버트 마틴의 클린 아키텍처, SOLID 중 [단일 책임 원칙](https://velog.io/@gooreum_90/SRP%EB%8B%A8%EC%9D%BC-%EC%B1%85%EC%9E%84-%EC%9B%90%EC%B9%99) 을 참고해보시면 도움이 될 것 같아요.

기존에 작성하신 Lotto 객체는 "**숫자 하나**의 범위를 변경" 과 "**여러 숫자**의 중복 허용 여부" 두 가지 이유로 인해 변경될 여지가 있겠지요 ? ㅎㅎ

2022-02-26 14:09 UTC, TheDevLuffy approved these changes
안녕하세요 라쿤~

피드백 반영해주신 것 확인하였어요.

다만 곳곳에 미사용 코드들이 보이는 곳이 있는데요. 남겨드린 코멘트와 함께 Step2 리뷰 요청시에 확인 한번씩만 부탁드려요.

1. Map.of() 나 List.of() 의 경우 불변의 관점에서 고민해보시는 것이 어떨까 하고 리뷰를 남겨드렸는데요. 어디까지 불변하도록 하게 할지에 대한 의견도 많이 갈려서 하나의 의견으로 고민만 한번 해주시면 좋을 것 같아요. 불변성에 대한 장점은 여기 저기서 많이 다루고 있으니 한번 학습해보셔요 ㅎㅎ

2. LottoCount 를 나누는 것에 대해서는 코멘트를 남겨두었습니다. 참고 부탁드려요

1단계는 이만 머지하도록 하겠습니다 ! 고생하셨습니다 💪

남은 주말 푹 쉬시고 step 2 에서 뵙겠습니다 !

2022-02-26 14:09 UTC, workromancer commented on src/main/java/domain/Lotto.java
> +    }
생성자 안에서 초기화를 하는 것도 좋을 것 같아요~!

2022-02-26 14:09 UTC, workromancer commented on src/main/java/domain/Lotto.java
> +        return (int) lottoNumbers.stream()
형 변환을 하여 사용하기보다 long 으로 그대로 사용해도 좋을 것 같아요.

해당 메서드의 반환값을 사용하는 곳과 관련된 곳을 변경할 수 있는 것으로 보이네요 😁

2022-02-26 14:09 UTC, merged