[1단계 - 로또(자동)] 연로그(권시연) 미션 제출합니다.
woowacourse/java-lotto pull request #391
Opened 2022-02-24 08:25 UTC by yeon-06

안녕하세요 닉!
만나서 반갑습니다 저는 연로그입니다😆

질문 사항에 대해서는 파일에 직접 코멘트 남겨둘테니 확인 후 답변 주시면 감사합니다

많이 노력한다고 계속 고치고 고친 코드인데 충실하게 구현이 되었는지 잘 모르겠네요
따끔한 지적과 조언 부탁드립니다 감사합니다😊👍

2022-02-24 08:31 UTC, yeon-06 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static LottoNumber of(String input) {
정적 팩토리 메소드를 적용시켜보고자 도전해보았는데 처음 도전하다보니 의문 사항이 많습니다ㅠㅠ

1. 이런식으로 static 선언 후 인스턴스를 가져오도록 구성해도 괜찮나요?
2. of메소드에서 input에 대해 검증하는 로직이 들어가도 괜찮을까요?
3. 이미 존재하는 인스턴스를 가져오는거라 equals()와 hashcode() 오버라이드를 삭제했는데 명시적으로 두는 것이 더 좋을까요?

2022-02-24 08:36 UTC, yeon-06 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int toInt() {
getter의 기능을 하지만 좀 더 **의미 있는 메소드명**을 짓기 위해 toInt() 식의 이름을 사용했습니다
getter로 사용하는게 좀 더 의미가 명확해보일까요?

2022-02-24 08:43 UTC, yeon-06 commented on src/main/java/lotto/domain/WinningResult.java
> +        Ranking[] rankings = Ranking.sortByPrize();
Ranking에 대한 순서를 원하는대로 정렬하고 이 순서에 따라 LinkedHashMap의 정렬도 동일하게 초기화하고자 했습니다
다만 이 정렬은 나중에 View에서 원하는대로 출력하게끔 하기 위한 정렬이라 WinningResult의 역할은 아니라는 생각도 듭니다.
닉은 어떻게 생각하시나요?

2022-02-24 08:44 UTC, yeon-06 commented on src/main/java/lotto/view/InputView.java
> +        System.out.println("구입금액을 입력해 주세요.");
InputView에서의 문자열도 하드 코딩일까요?
단 한 곳에서만 사용하는데 이 문자열도 상수화를 해야할지 고민이 됩니다.

2022-02-24 08:46 UTC, yeon-06 commented on src/main/java/lotto/domain/LottoNumbers.java
> +    static final String COUNT_ERROR = "로또 개수는 " + LOTTO_COUNT + "여야 합니다.";
중복 에러, 개수 에러 나는 경우를 따로 테스트하기 위해 상수를 default로 지정했습니다
(메시지에 해당 문자열이 포함되는지를 테스트)
해당 문자열을 테스트 코드에 복붙해갈수도 있지만 에러 문구가 바뀌게 되면 원본 코드, 테스트 코드 둘 다 수정해야한다는 번거로움 때문에 위 방법을 택했는데 어떻게 생각하시나요??

2022-02-24 08:48 UTC, yeon-06 commented on src/test/java/lotto/domain/WinningNumbersTest.java
> +    @DisplayName("1등 당첨 결과 반환")
1등부터 5등까지 유사한 테스트코드가 계속 반복되고 있습니다
본래 `@ParameterizedTest`와 `@CsvSource`를 활용할까 했는데 Enum은 받지 못하더라고요ㅠㅠ
혹시 다른 방법이 있을까요?

2022-02-26 05:06 UTC, wbluke requested changes
안녕하세요 연로그~! 로또 미션 리뷰를 맡은 닉입니다 🙌 
일급컬렉션 활용해서 잘 구현해 주셨네요 ㅎㅎ
질문 주신 것들 포함해서 코멘트 남겼으니 확인하고 리팩토링 진행해 주세요 🙂

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/Amount.java
> +public class Amount {
`로또를 구입하기 위한` 금액 이라는 의미를 가진 객체인데 그냥 Amount네요.
클라이언트가 해당 객체로 500원이라는 금액을 만들려다가 예외가 발생할 것 같아요.
네이밍을 좀 더 구체적으로 해보면 좋을 것 같네요 :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/Amount.java
> +public class Amount {
그리고 VO 객체는 항상 eq & hc 에 대한 재정의를 고려해 주세요 :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +        int number = convertToInt(input);
여기서 고민해봐야 할 포인트는 다음과 같습니다.

**모든 validation이 다 도메인의 역할일까?**

저는 View라는 계층이 별도로 있다는 점에서, View에서 최소한의 사용자 입력 유효성은 보장해주어야 하지 않을까? 라고 생각해요.
우리가 로또 숫자 1개를 입력 받을 때 고려해야 할 validation은 다음과 같은 것들이 있죠.

1. 해당 입력이 숫자인가?
2. 해당 입력이 1과 45 사이의 숫자인가?

분명 1번 validation과 2번 validation은 성격이 다릅니다.
1번은 우리가 정한 도메인 요구사항과 관련 없이, 숫자를 원한다면 숫자를 받아야 하는 최소한의 값 정합성인 것이고,
2번은 우리가 정한 도메인 요구사항의 규칙에 맞는지 검사한 것이죠.

어떻게 수정하면 좋을지 한번 고민해보시고, 여기 뿐만 아니라 전체적으로 리팩토링 해보셔요 :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static LottoNumber of(String input) {
1. 네네 그럼요. 로또 숫자를 미리 만들어서 캐싱하셨군요 👍  잘 하셨습니다 ㅎㅎ
2. 보통 validation은 생성자에서 하는 것이 좋고요, 지금 같은 경우는 캐싱된 인스턴스를 찾기 전에 검사하느라 그런 것 같은데, `캐싱된 곳에서 찾기 -> 없으면 예외` 와 같은 플로우면 어떨까요?
3. eq & hc 를 왜 쓸까요? (한번 알아보고 답변 남겨주세요 ㅎㅎ) 이미 존재하는 인스턴스를 가져오는 것과 무관하게 필요할 것 같아요.

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +        return lottoNumbers.get(number - 1);
이 부분이 조금 더 개선되었으면 하는데요, 로또숫자의 의미를 갖는 number와 리스트의 인덱스를 연결시키는 것은 코드의 흐름 상 단번에 이해하기가 어렵습니다.
더불어 캐싱한 자료구조가 연속된 숫자가 아니게 된다면 문제가 발생하겠죠.
캐싱한 자료구조를 다른 자료구조로 바꿔보면 어떨까요? :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int toInt() {
보통 VO의 경우는 객체의 이름과 필드의 이름이 겹치는 경우가 많기 때문에, 보통 필드명을 `value`로 두고 `getValue()`로 값을 반환하는 편입니다 :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumbers.java
> +    private static final int MAX_NUMBER = 45;
이 상수들은 LottoNumber의 상수들 아닐까요? :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumbers.java
> +    static final String COUNT_ERROR = "로또 개수는 " + LOTTO_COUNT + "여야 합니다.";
네네 좋은 시도입니다ㅎㅎ
저는 조금 다르게 생각하는 부분이 있는데요.
만약 누군가 실수로 사용자향 에러 메시지를 수정했다고 가정하면, 해당 테스트가 그래도 통과할 것이기 때문에 그대로 배포가 나갈 수도 있다고 생각해요. (일종의 장애인거죠)
문자열 메시지를 수정했을 때 테스트가 깨져야 개발자가 더 인지를 할 수 있고, 체크를 할 수 있게 되어서 테스트에서는 문자열 날것으로 검증하는 것이 좋다고 생각합니다 :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/Ranking.java
> +    }
Stream을 사용해보면 어떨까요? 그리고 보통은 배열 보다는 리스트를 사용하는 것이 변경/확장에 용이합니다 :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/WinningResult.java
> +        Ranking[] rankings = Ranking.sortByPrize();
네네 그러면 사실 Map으로 구성한 의미에 견주었을 때 조금 애매해보여요. (Key의 순서가 보장되어야 하니)
말씀하신대로 View의 책임으로 보고 구성하는 것이 더 자연스러워 보입니다 :)

2022-02-26 05:06 UTC, wbluke commented on src/test/java/lotto/domain/WinningNumbersTest.java
> +    @DisplayName("1등 당첨 결과 반환")
음 아뇨 ㅎㅎ 말씀하신 `@ParameterizedTest`와 `@CsvSource`로 가능합니다. 한번 더 고민해 보셔요 :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
> +        System.out.println("구입금액을 입력해 주세요.");
**상수화를 왜 하는가?**

에 대한 자신만의 답을 내려보길 바라요 ㅎㅎ
왜 할까요? :)
이유가 정립된다면 위 문자열을 상수로 만들지 아닐지에 대한 기준이 나올 것 같아요 ㅎㅎ

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/WinningResult.java
> +        return sum;
Stream을 사용해보면 어떨까요? :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumbers.java
> +        return new ArrayList<>(candidateLottoNumbers.subList(0, 6));
6이라는 숫자는 매직 넘버네요! 어딘가에 있는 상수를 사용하면 되겠네요 :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumbers.java
> +public class LottoNumbers {
LottoTickets가 있던데, 1장의 티켓을 의미한다면 이름이 LottoTicket이 되어야 하지 않을까요? :)

2022-02-26 05:06 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumbers.java
> +    public boolean isContain(LottoNumber otherLottoNumber) {
동사가 2개라서 ㅎㅎ 보통 `contains`라고 지어요 :)

2022-02-26 13:33 UTC, yeon-06 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static LottoNumber of(String input) {
equals와 hashcode는 객체의 동등성을 보장하기 위해 재정의하는 것으로 알고 있습니다!
말씀하신 것처럼 이미 존재하는 인스턴스를 가져오니까 동등성을 보장할 이유가 없어지지 않을까?라는 생각이 들더라고요
명시적으로라도 재정의해주는 것이 더 좋은지에 대해서는 잘 모르겠어서 질문 드렸습니다 😂

2022-02-26 13:38 UTC, yeon-06 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int toInt() {
현재 같은 경우에는 필드가 단 하나뿐이라 value로 정의해도 상관 없을 것 같은데 필드가 여러개인 경우에도 VO로 정의할 일이 생기지 않을까요?
예를 들어 Book에 title, price, author 필드가 있을 때도 동등성을 보장해야할 것 같은데 현재는 필드가 하나뿐이라 value를 추천해주신걸까요? 😵
(참고로 현재 저는 VO를 클래스 내부의 모든 상태가 동일한 경우 동등성을 보장해야하는 객체로 이해하고 있습니다.)

2022-02-26 13:42 UTC, yeon-06 commented on src/main/java/lotto/view/InputView.java
> +        System.out.println("구입금액을 입력해 주세요.");
재사용 가능 여지가 충분한 경우 재사용을 위해, 또는 유지보수를 쉽게 하기 위함이라고 이해하고 있습니다!
상수는 기본적으로 클래스 내부의 최상단에 위치하니 해당 메소드의 위치를 찾을 필요 없이 좀 더 쉽게 접근할 수 있기 때문에 유지 보수를 쉽게 할 수 있다고 생각을 합니다
정리해놓고 보니 상수화를 진행해야 겠네요 ㅎㅎ
혹시 닉은 이견 있으시다면 추가로 의견 부탁드립니다!

2022-02-26 13:45 UTC, yeon-06 commented on src/main/java/lotto/domain/LottoNumbers.java
> +    private static final int MAX_NUMBER = 45;
이 부분에 대해서는 고민해보았는데 랜덤 숫자 발생을 위한 List를 생성하려면 해당 숫자가 꼭 필요하네요ㅠㅠ
좀 더 힌트를 주실 수 있을까요?

2022-02-26 17:33 UTC, yeon-06 commented
안녕하세요 닉 리팩토링 후 다시 리뷰 요청 드립니다😊
기존 피드백 외에도 몇가지 시도를 해보았는데 참고하시며 함께 피드백 주시면 감사합니다!

2022-02-26 17:35 UTC, yeon-06 commented on src/main/java/lotto/domain/WinningResult.java
> +    private final Map<Ranking, Integer> winningResult = new EnumMap<>(Ranking.class);
- LinkedHashMap<Ranking,Integer> 대신 EnumMap<Ranking, Integer> 활용

👉 HashMap보다 EnumMap의 성능 차이에 대해 [공부](https://yeonyeon.tistory.com/195)하고 현재 상황에서는 EnumMap이 더 적합하다고 판단

2022-02-26 17:37 UTC, yeon-06 commented on src/main/java/lotto/domain/LottoNumbers.java
> +        return List.copyOf(candidateLottoNumbers.subList(0, LOTTO_COUNT));
List를 반환하는 경우 불변 컬렉션 도입
👉 List의 add/remove가 일어나면 안된다고 판단

2022-02-26 17:38 UTC, yeon-06 commented on src/main/java/lotto/domain/Ranking.java
> +                .orElse(DEFAULT);
DEFAULT라는 새로운 상태 생성
👉 기존엔 null을 반환하는 방식이었는데 위 메소드 사용할때마다 null처리를 만드는 것이 번거롭게 느껴짐

2022-02-27 05:46 UTC, yeon-06 commented on src/main/java/lotto/domain/Ranking.java
> +    }
리팩토링을 진행하며 사라진 메소드긴 하지만 궁금점이 생겨 코멘트 답니다!
리스트가 변경, 확장에 용이하기 때문에 오히려 배열을 사용했는데요
(변경이나 확장될 일이 없어야 한다고 판단)
이런 경우에는 보통 배열보다는 불변으로 만드시나요?

2022-02-28 01:57 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static LottoNumber of(String input) {
맞아요 말씀하신 내용도 맞습니다 ㅎㅎ
다만 LottoNumber 자체의 eq & hc만으로 동등성을 보장해주는 구현과 
LottoNumber가 이미 캐싱되어 있고, 이를 반환한다는 구현을 비교한다면 저는 전자가 우선되어야 한다고 생각해요.
추후에 애플리케이션의 변경이 일어난다거나 해서 현재 구현한 후자의 로직이 변경된다면 LottoNumber의 동등성이 침해받을 수도 있거든요.
지금은 문제가 없겠지만, 어떤 것이 더 우선되어야 하는지, 안전장치의 느낌으로 생각해보시면 좋을 듯 합니다 :)

2022-02-28 02:00 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +    public int toInt() {
아 네네 LottoNumber와 같이 필드가 하나인 경우를 말씀드린 거였어요 ㅎㅎ
LottoNumber의 필드는 클래스 이름과 동일한 의미의 number일텐데, 외부에서 LottoNumber를 하나의 값으로 본다면
`LottoNumber.getNumber()` 보다는 `LottoNumber.getValue()`가 더 자연스럽다고 생각해요 ㅎㅎ (제 생각이에요)
말씀하신대로 필드가 여러 개라면 getter도 각각의 필드에 맞게 getTitle(), getPrice()로 지어지겠네요.

2022-02-28 02:03 UTC, wbluke commented on src/main/java/lotto/view/InputView.java
> +        System.out.println("구입금액을 입력해 주세요.");
네네 좋습니다. 사실 지금 단계에서는 View가 단순한 편이라 굳이 상수화를 진행하지 않아도 괜찮다고 생각하긴 해요.
애플리케이션이 커지면 사용자향 메시지 같은 경우는 별도의 파일로 관리할 수도 있을거고요 :)

2022-02-28 02:04 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumbers.java
> +    private static final int MAX_NUMBER = 45;
LottoNumber의 상수를 공개로 열면 되지 않을까요? :)

2022-02-28 02:11 UTC, wbluke commented on src/main/java/lotto/domain/Ranking.java
> +    }
네네 그런 의도라면 불변 리스트로 만들어서 반환합니다.
공개 API를 설계할 때, 클라이언트가 어떻게 사용할지는 모르지만 배열의 경우 사용하면서 추가 가공이 필요하기 때문에 (stream을 사용한다던가) 사용성이 떨어지는 편입니다.

2022-02-28 02:25 UTC, wbluke approved these changes
질문해 주신 내용들 보면서 고민을 많이 해주신 것 같다고 느꼈어요 👍 
답변이랑 추가 코멘트 남겼으니 다음 단계 진행하시면서 같이 고려해 주세요 🙂

2022-02-28 02:25 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
> +                .forEach(i -> cacheLottoNumber[i] = new LottoNumber(i));
음 Map을 사용해보는건 어떨까요?
이 코드를 읽는 사람이 cacheLottoNumber의 생성 과정과 존재 의미를 파악하기 위해서는 해석이 필요한 상황입니다.
`어떤 숫자 -> 해당하는 인스턴스` 의 구조로 구성해보면 어떨까요 ㅎㅎ
사실 그렇게 되면 미리 45개의 인스턴스를 만들 필요도 없고, 생성 요청이 올때마다 캐싱이 되어있는지 판단해서, 있으면 기존 인스턴스를 반환하고 없으면 새로 생성해서 캐싱 후 반환하는 방법도 가능합니다 :)

2022-02-28 02:25 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumber.java
>      private static final String NUMBER_RANGE_ERROR = "로또 숫자는 " + MIN + " 이상 " + MAX + " 이하의 숫자만 가능합니다.";
String.format()을 사용해보면 어떨까요? ㅎㅎ 그러면 메시지 구조가 한눈에 들어올 것 같아요.
전체적으로 한번 체크해보셔요 :)

2022-02-28 02:25 UTC, wbluke commented on src/main/java/lotto/domain/LottoNumbers.java
> +        this.lottoNumbers = convertStringArrToIntegerList(stringArr);
https://github.com/woowacourse/java-lotto/pull/391#discussion_r815265557

요 피드백 고려해서 한번 고민해 주세요 :)

2022-02-28 02:25 UTC, wbluke commented on src/main/java/lotto/domain/Ranking.java
> +                .orElse(DEFAULT);
당첨 등수를 나타내니까 DEFAULT 보다는 NONE 같은 네이밍이 어떨까 싶네요 :)

2022-02-28 02:25 UTC, wbluke commented on src/test/java/lotto/domain/WinningNumbersTest.java
> +    void prize(String input, Ranking expect) {
방법 잘 찾으셨네요 👍

2022-02-28 02:25 UTC, wbluke commented on src/test/java/lotto/domain/WinningResultTest.java
> +        assertThat(winningResult.calculatePrizeSum()).isEqualTo(expect);
calculatePrizeSum()을 테스트하기 위함인가요?
그러면 23, 24 라인은 given절이고, `winningResult.calculatePrizeSum()` 이 when이 되어야 할 것 같아요 :)
보통 테스트하기 위한 모든 테스트픽스처와 준비과정은 given, 테스트하고자 하는 행위(기능)는 when, 검증을 then에 둡니다.

2022-02-28 02:26 UTC, merged