[1단계 - 로또(자동)] 범고래(조충범) 미션 제출합니다.
woowacourse/java-lotto pull request #392
Opened 2022-02-24 08:25 UTC by cndqjacndqja

### **LotteryTickets에 add가 추가되면 안되는지?**

**문제 상황**
```
불변하게 만든 후, LotteryTickets의 상태 값은 아무도 접근할 수 없게 한다.

vs

LotteryTicket를 다른 객체가 의존하지 않게 하고, 외부에서 LotteryTickets의 멤버변수에 add할 수 있게 한다.
```

**현재 코드**

```java
LotteryMachine.class

private static List<LotteryTicket> createLotteryTickets(int numberOfTickets) {
        List<LotteryTicket> lotteryTickets = new ArrayList<>();
        for (int i = 0; i < numberOfTickets; i++) {
            lotteryTickets.add(new LotteryTicket(generate()));
        }
        return lotteryTickets;
    }
```
현재 LotteryTickets는 외부에서 LotteryTicket 리스트를 생성하여 LotteryTickets 생성시, 주입 받게 되어있습니다.

**고민했던 코드**

```java
LotteryTickets.class

add(List<Integer> input) {
	tickets.add(input);
}
```

당시 고민했던 부분은 LotteryTickets외에 LotteryTicket을 의존하지 않게 하기 위해 위와 같은 코드를 생각 했으나, LotteryTickets의 상태 값을 변경할 여지를 없애기 위해 외부에서 LotteryTicket리스트를 생성해서 전달해주는 방식을 선택했습니다.

이 같은 상황에서 리뷰어님의 생각은 어떠신지 궁금합니다.

---

### InputView에서 validate를 해도 괜찮을지?

현재 InputView에서의 검증 로직이 많이 있다고 느껴서, InputViewValidator클래스로 검증 로직을 분리시켜 주는 것을 고민했습니다. 하지만 불필요한 클래스를 늘리는 것 같아서 결국 하지 않았지만, 이에 대한 리뷰어님의 의견이 궁금합니다.

---

### 원시값 포장한 객체는 어디 패키지에 위치하는 것이 좋을지?

현재 원시값을 포장하기 위해 Count, Money 클래스가 있습니다. 현재는 dto에 있지만, 원시값이기 때문에 다른 패키지의 클래스에서도 사용하게 되었는데요. 이럴 경우 Count, Money와 같은 클래스는 어느 패키지에 위치하는 것이 좋을지 궁금합니다.

2022-02-24 17:37 UTC, lxxjn0 requested changes
안녕하세요, 범고래 :)
이번에 범고래의 리뷰를 맡게 된 스티치라고 합니다 😄 

구현해주신 코드 잘 봤습니다 :) 전체적으로 클래스 분리를 하고 관리하려고 노력한 부분이 보였습니다 👍🏼 그러나 이번 코드에서 아쉬운 부분들이 조금 많이 보였던 것 같아요.. ㅠㅠ

전체적으로 기능이 정상적으로 동작하지 않는 부분, 예외에 대한 적절한 처리가 되지 않는 부분, 도메인이 각각 적절한 책임을 가지지 못한 부분 등이 아쉬웠습니다. 우선 가장 중요한 기능 동작이 정상적으로 되지 않고 있어요!! 코드의 구현도 중요하지만 가장 중요한 것은 정상적으로 동작하는 코드를 작성하는 것입니다!! 

이번 리뷰에서는 저의 피드백을 반영하는 것도 중요하지만 그보다 전체 코드가 정상적으로 동작하는지 꼼꼼하게 확인하고 개선하는 것, 추가적으로 사용자들의 다양한 입력에 적절하게 대응할 수 있도록 방어 로직을 구현하는 것에 집중하여서 개선해보면 좋을 것 같아요!!!

그리고 범고래가 남겨준 질문에 대한 답변을 달아두도록 하겠습니다!! :)

### 1번 질문

저는 생성과 동시에 초기화하는 것이 더 좋아보입니다!! 

add 메서드를 구현해둔 순간 언제든지 로또 티켓에 새로운 숫자를 추가할 수 있는 위험성이 생겨요! 만약 그런 부분이 의도된 부분이라면 괜찮겠지만 그렇지 않은 상황에 대해서는 안전하지 못할 것 같습니다!!

추가적으로 LottoTickets 객체라면 add 함수가 그렇게 부정적이진 않았을 것 같아요!! 만약 이후 추가로 구매를 할 수 있다는 요구사항도 생길 수 있구요!! (물론 이러한 과한 가정은 오버엔지니어링이 될 수 있습니다 ㅎㅎ) 

하지만 LottoTicket은 항상 6자리 숫자 리스트를 가지도록 제한되어야 하는 만큼 생성과 동시에 추가, 삭제가 불가능하도록 제한하는 것이 좋을 것 같습니다!! 각각의 객체가 가져야 하는 책임, 그에 따른 제약 조건 등을 고려해서 구현하면 좋을 것 같습니다!!!

### 2번 질문

현재는 InputView에 검증 로직이 조금 많은 것처럼 보여지긴 합니다. 그러나 코드를 한번 더 꼼꼼히 확인해보면 입력한 값에 대한 검증이 아닌 비즈니스 로직적인 검증도 InputView에 함께 존재하는 것 같아요!! (`getBonusNumber` 메서드 참고)

사용자의 입력에 대한 유효성 검증은 어떠한 범위까지 해야 하는지, 비즈니스 적인 검증은 어떠한 범위까지로 봐야하는 지에 대한 고민을 한번 해보면 좋을 것 같습니다!!

해당 부분은 범고래가 고민하고 고민한 내용에 대해 다음 리뷰에 공유해주시면 그에 대한 저의 생각도 함께 말씀드려보도록 할게요 😄 

### 3번 질문

우선은 현재 원시값 포장 객체를 dto로 사용하는 부분이 잘못된 것으로 보여집니다!! 먼저 dto가 어떠한 역할을 하는 객체인지, 그리고 원시값을 포장해야 하는 목적이 뭔지, 만약 그렇지 않은 경우에 꼭 원시값을 포장해야 하는지 여부를 고민해보고 범고래의 생각을 정리해보면 좋을 것 같아요!!

지금의 코드들은 목적 없는 원시값 포장이 존재하는 것 같아보입니다. 항상 클래스를 분리할 때는 목적을 생각하고 작성해야 합니다!! 이번 기회에 새로운 클래스를 만들 때 어떠한 점을 고려하고 고민해야 하는지 한번 학습해보시면 좋을 것 같아요!!

2022-02-24 17:37 UTC, lxxjn0 commented on README.md
> +## 구현 기능 목록
구현 목록을 꼼꼼하게 작성하고 체크하면서 구현한 부분 좋아요 👍🏼 
하지만 실제로 코드를 실행해보니 유효하지 않은 상황에 대해서도 동작하는 것 같습니다!!

- 1000원 단위가 아닌 금액을 입력해도 로또 구매 가능
- 로또를 구매하지 못하더라도 당첨 번호를 입력하는 창이 등장
- 로또 번호 범위를 초과하는 입력이 들어오더라도 프로그램이 정상 동작 (로또 번호로 555를 입력하더라도 그대로 동작)

이 외에도 정상적으로 예외가 처리되거나 해야하는 부분들이 누락이 된 것 같아요!!! 구현 기능 목록에서는 이러한 예외에 대한 처리를 해야 한다는 부분은 없습니다. 

그러나 해당 프로그램을 사용하는 사용자에게 예상되는 동작을 하도록 어느정도의 예외 처리는 필요하다고 생각해요!! 해당 프로그램이 사용자의 다양한 입력에 대응되면서 정상적으로 동작하도록 개선해보면 좋을 것 같아요!!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/dto/Count.java
> +public class Count {
Count 클래스는 dto로 보기엔 어려울 것 같아요!! 
dto가 어떠한 역할을 하는 객체인지, 그리고 그런 관점에서 Count가 왜 dto에 어울리지 않는지 한 번 고민해보면 좋을 것 같아요!!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/utils/LotteryNumbersGenerator.java
> +    }
체이닝 메서드의 경우는 적절히 개행을 한다면 코드의 가독성을 높일 수 있습니다!!

```suggestion
    public static List<Integer> generate() {
         return ThreadLocalRandom.current()
                 .ints(MINIMUM.getNumber(), MAXIMUM.getNumber())
                 .distinct()
                 .limit(TICKET_SIZE.getNumber())
                 .boxed()
                 .collect(Collectors.toList());
    }
```

그리고 추가적으로 이러한 방법이 아닌, 이번 미션에서 제안한 `Collections.shuffle()`을 사용해서 구현해보는 것도 좋을 것 같아요 :)

<img width="517" alt="Screen Shot 2022-02-25 at 1 39 03 AM" src="https://user-images.githubusercontent.com/48052622/155567780-4e56de6f-abc3-4707-8818-fb79ef13bf21.png">

2022-02-24 17:37 UTC, lxxjn0 commented on README.md
> +## 구현 기능 목록
추가적으로 생성된 로또 번호의 경우도 오름차순으로 정렬하여서 보여주면 좋을 것 같아요 :)
미션의 실행 결과를 살펴보면 모두 오름차순으로 정렬되어 출력하는 것을 확인할 수 있습니다!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +    }
해당 유효성 검증 로직은 정상적으로 동작하지 않을 것 같아요!! 한 번 확인해보면 좋을 것 같아요!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/utils/LotteryRule.java
> +public enum LotteryRule {
로또와 관련된 규칙을 enum으로 관리하고 있군요!! 👍🏼

그러나 객체를 표현하는 Name이 조금 더 구체적이면 좋을 것 같아요!! 그리고 대부분 getter를 사용해서 Enum 객체가 가지는 number를 가져간 후 연산을 진행하고 있는데, 객체지향적인 관점에서 개선해보는 것도 좋을 것 같습니다!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryMachine.java
> +    }
해당 코드에서 Money를 보면 Money 객체가 가지는 책임이 어떤 것인지 헛갈리네요. 혹시 Money 객체가 어떠한 책임을 가지도록 구현하셨을까요??

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryMachine.java
> +        Money ticketAmount = new Money(numberOfTickets.getNumber() * TICKET_PRICE.getNumber());
main 함수에서 처음 사용자의 입력으로 받은 Money가 아니라 새로 티켓의 수와 가격을 연산해서 Money를 생성한 이유가 있을까요?

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/utils/LotteryCalculator.java
> +    private static final int LOTTERY_PRICE = 1000;
LotterryRule에서 관련 금액을 관리하고 있는 것으로 확인했는데 여기서 따로 정의하신 이유가 있을까요?

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
상수의 경우 대문자로 명명을 해주면 좋을 것 같아요 :)

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +    }
해당 코드에서 발생 가능한 예외는 NumberFormatException 밖에 없는데 RuntimeException으로 처리한 이유가 있을까요?

예외를 catch 할 때는 명확한 목적을 가지고 최대한 적절한, 구체적인 범위로 처리하는 것이 좋습니다. 현재는 전체적으로 RuntimeException으로 모든 예외를 처리하려고 하는 것 같아요. 어떠한 예외가 발생하는지, 그리고 해당 예외를 어떻게 처리할 것인지 목적을 가지고 코드를 작성하면 더 좋을 것 같습니다!! :)

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +    }
해당 피드백을 참고삼아 다른 부분들도 전체적으로 확인해보면 좋을 것 같아요!!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +        }
if문의 조건 내부에 들어갈 값이 이처럼 체이닝 메서드로 길어질 경우엔 따로 변수로 추출 후 코드를 작성하면 더 가독성 좋은 코드가 될 것 같아요!! 👍🏼

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +    }
해당 메서드 명만 보면 전달되는 매개변수가 어떠한 목적으로 사용되는지 파악하기 어려울 것 같아요!! 

'보너스 숫자를 가져온다. 그런데 int형 숫자들을 넘겨줘야해' 로 메서드 명을 이해할 수 있을 것 같은데, 이때 어떠한 숫자를 넘겨줘야 하는지 메서드를 사용하는 사람들이 알 수 있을까요?? 
getBonusNumber는 보너스 숫자만 받아오는 역할을 가지고 받아온 숫자가 적절한 지를 이후에 검증하는 것이 더 좋을 것 같아요!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/OutputView.java
> +    }
해당 코드에서 로또 번호를 출력할 때 List<Integer>의 toString 메서드를 사용하여서 출력문을 구성한 것 같습니다!! 

toString은 해당 객체의 상태를 파악할 때 사용하는 함수에요. 그래서 만약 출력 양식이 변경되거나 하면 유연하게 대응하기가 어려울 것 같아요!! 출력문에서 사용해야 하는 양식에 맞춰서 출력 데이터를 가공해보는 것도 좋을 것 같습니다!! 👍🏼

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/OutputView.java
> +        stringBuilder.append("당첨 통계").append("\n").append("---------").append("\n");
해당 코드는 하나의 문자열로 처리를 할 수 있는데 append 함수로 합친 이유를 알 수 있을까요?? 굳이 필요하지 않은 부분에 대한 연산은 최소한으로 하는 것이 좋을 것 같아요!!

2022-02-24 17:37 UTC, lxxjn0 commented on README.md
> +## 구현 기능 목록
<img width="327" alt="image" src="https://user-images.githubusercontent.com/48052622/155573094-37e55b95-7f97-4f2c-a1ff-1cab3d7da464.png">

추가적으로 실행 결과도 일치하지 않는 것으로 보여져요!! 정상적으로 동작하도록 코드 개선이 필요할 것 같습니다!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/OutputView.java
> +    }
꼼꼼한 출력문 처리 좋습니다!! 👍🏼 
추가로 1에 대한 매직넘버 처리도 해주면 더 좋을 것 같아요!! :)

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/OutputView.java
> +    }
[Java Style Guide](https://github.com/woowacourse/woowacourse-docs/tree/master/styleguide/java)가 지켜지지 않은 것으로 보여집니다!! 확인하시고 적용하시면 좋을 것 같아요!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/utils/LotteryRule.java
> +    }
boolean을 반환하는 경우 주로 hasXXX, isXXX와 같은 식의 메서드 명을 사용합니다. check의 경우 보편적으로 유효성 검증 후 유효하지 않을 때 예외를 발생하는 코드에서 사용되는 메서드 명에요. 아래 글도 한번 참고해보면 좋을 것 같아요!!

https://soojin.ro/blog/naming-boolean-variables

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/model/WinningLottery.java
> +    private final int price;
자바 코딩 컨벤션을 확인하신 후 적절하게 공백을 추가해주면 좋을 것 같습니다!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/model/WinningLottery.java
> +    }
해당 로직으로는 정상적으로 동작하지 않을 것으로 보입니다!! 기능 요구사항과 실행 결과를 참고해서 다시 한번 개선해보시면 좋을 것 같아요!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/model/WinningLottery.java
> +                .orElse(null);
null을 반환하는 대신에 적절한 Enum 객체를 만들어서 반환하면 어떨까요?? 그러면 NPE에 대해서 보다 안전한 코드가 될 것 같아요!!

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/dto/Money.java
> +public class Money {
Money 객체가 하는 역할이 전혀 없어보입니다!! 혹시 어떠한 목적으로 구현한 클래스일까요?

2022-02-24 17:37 UTC, lxxjn0 commented on src/main/java/lotterymachine/model/LotteryTicket.java
> +    }
외부에서 수정하지 못하도록 unmodifiableList로 감싼 부분 굿 👍🏼

2022-02-28 06:52 UTC, cndqjacndqja commented on src/main/java/lotterymachine/dto/Count.java
> +public class Count {
해당 부분은 깊게 생각하지 않고 급하게 작성하는 과정에서 생긴 문제 같습니다😭
리팩토링 하는 과정에서 Count, Money와 같은 클래스는 제거 되었습니다!

2022-02-28 06:53 UTC, cndqjacndqja commented on src/main/java/lotterymachine/utils/LotteryNumbersGenerator.java
> +    }
현재는 ThreadLocalRandom을 사용하지 않고, 1~45개의 숫자를 가지는 LotteryNumber 리스트를 미리 생성하여 shuffle()후에 반환하는 형태로 변경했습니다😊

2022-02-28 06:55 UTC, cndqjacndqja commented on src/main/java/lotterymachine/utils/LotteryRule.java
> +public enum LotteryRule {
LotteryRule에서 Lottery와 관련된 규칙을 관리했었는데요! Lottery관련 클래스에서 모두 LotteryRule에 의존하는 것이 좋아 보이지 않아서 해당 클래스들이 가지는 규칙을 각 클래스들 안에서 관리하는 것으로 변경했습니다😊

2022-02-28 06:55 UTC, cndqjacndqja commented on src/main/java/lotterymachine/LotteryMachine.java
> +    }
이것도 위에서 언급했듯이, 리팩토링 하는 과정에서 제거되었습니다..!🤣

2022-02-28 06:56 UTC, cndqjacndqja commented on src/main/java/lotterymachine/utils/LotteryCalculator.java
> +    private static final int LOTTERY_PRICE = 1000;
현재는 LotteryRule에서 모든 Lottery관련 규칙을 관리하는 것이 좋지 않다고 판단하여 LotteryRule을 제거했습니다!

2022-02-28 06:58 UTC, cndqjacndqja commented on src/main/java/lotterymachine/view/InputView.java
> +    }
예외 메시지를 직접 던져주는 상황이다 보니, RuntimeException으로 해도 문제되지 않을 것이라 생각했습니다!
하지만 생각해보니 NumberFormatException등 RuntimeException을 상속하여 구현한 예외 클래스들은 단순히 메시지만 변경하는 것이 아니라 해당 클래스명으로도 좀 더 구체적인 Exception을 표현할 수 있는 것 같다고 생각되어, 상황에 맞는 구체적인 Exception을 catch하는 것으로 수정했습니다!

2022-02-28 06:59 UTC, cndqjacndqja commented on src/main/java/lotterymachine/view/OutputView.java
> +        stringBuilder.append("당첨 통계").append("\n").append("---------").append("\n");
"당첨 통계\n---------\n" 보다 append로 끊어주는 것이 가독성이 좀 더 좋다고 생각했던 것 같습니다! 큰 이유는 없었지만, 다시 보니 append를 하는데도 연산하는 비용이 들어가니 가독성이 많이 떨어지는 것이 아니라면 연산은 최소화 하는 것이 좋을 것 같네요!😊

2022-02-28 07:01 UTC, cndqjacndqja commented on src/main/java/lotterymachine/model/WinningLottery.java
> +    }
당첨된 등수가 없다는 것은 null로 표현되기 보단 ZERO와 같은 상수로 표현하는 것이 더 명확한 것 같아서 수정되었습니다!

2022-02-28 07:08 UTC, cndqjacndqja commented
안녕하세요 스티치! 꼼꼼한 리뷰 정말 감사드립니다 😭
피드백 반영 후, 다시 리뷰 요청 드립니다!
피드백 반영을 하면서, 왜 이렇게 수정하게 되었는지 노션에 정리를 하게 되었는데요!
혹시 왜 이렇게 수정되었는지 이해가 되지 않는 부분도 있을 것 같아서 같이 첨부하겠습니다!
[노션 링크](https://beomwhale.oopy.io/09b5e240-63d9-4475-a49d-781c5293307b)

그리고 추가 질문 사항이 있는 것은 해당 코드에 코멘트로 남기겠습니다!

2022-02-28 07:10 UTC, cndqjacndqja commented on src/main/java/lotterymachine/view/InputView.java
> +    }
위에서는 RuntimeException으로 예외 처리를 catch하고 있는데요! toInt에서는 NumberFormatException이 발생할 수 있고, LotteryNumber에서는 `IllegalArgumentException`이 발생할 수 있어서 RuntimeException으로 catch하게 되었습니다.

이렇게 하나의 메서드 안에서 서로 다른 Exception이 발생할 수 있는 상황이라면, RuntimeException으로 catch해도 괜찮은 것일까요?
아니면 현재 하나의 메소드 안에서 두가지 일을 하고 있다고 보는게 맞을까요??

2022-03-01 19:58 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +    }
아닙니다!! 현재 범고래가 작성한 방법으로 진행하시는 것이 맞습니다!! NumberFormatException과 RuntimeException에서 처리해야 하는 로직이 다르다면 구분해야 하지만 동일하다면 하나의 상위 Exception 클래스로 잡아서 처리하시면 됩니다!! 👍🏼

2022-03-01 20:19 UTC, lxxjn0 approved these changes
범고래, 리뷰 반영해주신 부분 잘 봤습니다!!!
전체적으로 코드가 많이 좋아진 것 같아요!!! 제가 코멘트 남긴 부분 참고해서 2단계 진행해주시면 될 것 같습니다!! 2단계에서 뵐께요 👍🏼

2022-03-01 20:19 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    }
메서드는 사용하는 곳에 가깝게 두는 것이 좋습니다!! 위에서 아래로 코드가 자연스럽게 읽히도록 배치하면 더 가독성이 좋은 코드가 될 것 같아요!!! 👍🏼

2022-03-01 20:19 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    }
현재는 1000원 단위의 금액이 아닐 경우에 대해서 대응이 안될 것 같아요!! 해당 부분에 대한 검증도 이뤄지면 좋을 것 같습니다!!

2022-03-01 20:19 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTickets.java
> +    private final TicketCount ticketCount;
해당 클래스가 ticketCount를 맴버 변수로 가지고 있는 것이 어색한 것 같아요!! 로또 티켓들을 관리하는 클래스에서 현재 count를 감소시키면서 사용하고 있습니다!! 현재 티켓을 하나씩 추가하고 있는데 외부에서 개수에 맞는 티켓을 생성해서 LotteryTickets를 생성하면 현재 맴버 변수는 따로 관리되지 않아도 될 것 같습니다!!

2022-03-01 20:19 UTC, lxxjn0 commented on src/main/java/lotterymachine/utils/LotteryCalculator.java
> +    private static final int LOTTERY_PRICE = 1000;
현재는 해당 변수가 두 곳에서 관리되고 있는 것 같아요!! (LotteryPurchase) 적절한 책임을 가지는 클래스에서 1개로 관리하면 추후 변경에 대응하기가 더 좋을 것 같습니다!!

2022-03-01 20:19 UTC, lxxjn0 commented on src/main/java/lotterymachine/utils/LotteryNumbersGenerator.java
> +public class LotteryNumbersGenerator {
현재는 Generator에서 LottoNumber를 생성해서 관리하고 있습니다!! 해당 부분을 LottoNumber가 캐싱해서 가지도록 하면 어떨까요??
지금의 코드는 LottoNumber 생성자가 열려있는 상태라서 언제든지 생성할 수 있습니다!! IntegerCache 클래스를 한번 참고해서 개선해본다면 LottoNumber 생성을 제한해둘 수 있을 것 같아요!!!

2022-03-01 20:19 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/WinningLottery.java
> +    private static final int TICKET_SIZE = 6;
해당 변수도 LottoTicket에서 관리되고 있는 상수를 사용하는 것이 좋을 것 같아요!!

2022-03-01 20:19 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryMachine.java
> +    }
해당 메서드에서 LottoTicket을 모두 생성하고 해당 list를 사용해 LotteryTickets를 생성하면 더 안전하게 생성할 수 있을 것 같아요!!

2022-03-01 20:19 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/WinningLotteryRank.java
> +    }
현재 bonus 변수의 경우 기본이 false이고 BONUS_FIVE의 경우 true로 생성되어 있습니다!! 해당 부분을 생성자 오버로딩을 사용하면 더 깔끔하게 바꿔볼 수 있을 것 같아요!!

2022-03-01 20:19 UTC, merged

2022-03-02 03:32 UTC, cndqjacndqja commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    }
현재 1000원 미만의 금액을 투입하면 Exception을 throw하고 있는데, 혹시 이 부분을 말씀하시는 것 일까요~? 1500원을 넣으면 정상 작동 하지만, 1000미만 일 경우에는 예외 처리를 해줘야 한다고 생각했습니다!😊

2022-03-02 13:58 UTC, cndqjacndqja commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    }
1000원 미만일 때는 Exception을 thorw 하지만, 1000원 단위가 아닌(ex. 1500) 단위에 대해서는 검증을 하지 않았습니다!
<img width="210" alt="image" src="https://user-images.githubusercontent.com/48307960/156375685-278944a3-a5ce-4449-bb0e-c90a12889c4e.png">