[1단계 - 로또(자동)] 스컬(김윤기) 미션 제출합니다.
woowacourse/java-lotto pull request #393
Opened 2022-02-24 08:29 UTC by skullkim

레이싱 게임에 비해 시간이 모자르다는 느낌을 받았습니다. 아직 구입 금액을 저장하는 원시타입에 대한 포장, 중복되는 일부 코드를 수정하지 못했지만 PR을 해야될 시간이 되서 제출합니다. 나머지 리팩토링은 주시는 피드백과 함께 수정하겠습니다.

질문:
일부 입력 검증을 생성자에서 구현했습니다. 만약 생성자에서 검증을 할 때 올바르지 않은 입력에 대해 사용자에게 다시 입력을 받을 수 있는 방법이 있나요?

2022-02-25 03:45 UTC, lowoon requested changes
반가워요 스컬! 리뷰어 로운입니다! 😄
작성하신 코드 잘 확인했습니다. 👍
피드백 몇 가지 남겨봤으니 확인 부탁드려요.

질문하셨던 부분 답변을 드리면

1.
올바르지 않은 입력일 경우 에러를 던질텐데 이 에러를 handling하는 방법을 찾아보면 되지 않을까요??

2.
말씀하신 경우에는 원시값을 포장하지 않아도 된다고 생각해요. 서버 자체에서 값을 설정하기도 하고, 특별한 검증이 필요한 부분도 아니기 때문이죠. 다만, 상금이 고객이 입력한 돈과 비교하거나 로직이 필요한 경우에는 같은 객체로 만드는 것이 좋지 않을까 생각합니다.

답변이 도움이 되었으면 좋겠네요 😸
궁금한 점이 생기면 언제든지 DM 혹은 댓글남주세요 ^-^

2022-02-25 03:45 UTC, lowoon commented on src/main/java/controller/LotteryGameController.java
> +		OutputView.printLotteries(lotteryGame.getLotteries());
view가 controller에 있는게 맞을까요??

2022-02-25 03:45 UTC, lowoon commented on src/main/java/controller/LotteryGameController.java
> +		return InputView.inputValidMoney();
돈에 대해서는 객체를 만들어 검증이 필요하지 않을까요??

2022-02-25 03:45 UTC, lowoon commented on src/main/java/domain/generatestrategy/LotteryGenerateFamily.java
> +public interface LotteryGenerateFamily {
family를 붙인 이유가 있나요???

2022-02-25 03:45 UTC, lowoon commented on src/main/java/domain/generatestrategy/LotteryRandomGeneratorStrategy.java
> +		for (int i = 1; i <= MAX_BOUND; i++) {
MAX를 상수로 했다면 MIN도 상수로 하는 것이 낫지 않을까요??

2022-02-25 03:45 UTC, lowoon commented on src/main/java/domain/Lotteries.java
> +		lotteriesNumber.forEach(lotteryNumber ->
forEach보다는 for가 더 명확하답니다.

https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/

2022-02-25 03:45 UTC, lowoon commented on src/main/java/domain/generatestrategy/LotteryGenerateFamily.java
> +	List<LotteryNumber> getNumbers();
LotteryGenerate인데 번호만 넘기는 이유가 있을까요??
Lottery를 반환할 수도 있지 않을까요??

2022-02-25 03:45 UTC, lowoon commented on src/main/java/domain/LotteryNumber.java
> +	}
hashCode가 없는데 어떤 이슈가 발생할까요??

https://tecoble.techcourse.co.kr/post/2020-07-29-equals-and-hashCode/

2022-02-25 03:45 UTC, lowoon commented on src/main/java/domain/Rank.java
> +	FOURTH(4, 50_000), FIFTH(3, 5_000), NONE(1, 0);
한 줄에 하나씩 표현해주는 것이 보기 좋답니다~

2022-02-25 03:45 UTC, lowoon commented on src/main/java/domain/Lottery.java
> +		return LOTTERY_SIZE - differences.size();
```suggestion
                       (int) numbers.stream()
				.filter(lottery::contains)
				.count();
```
도 가능할거 같은데 위와 같이 한 이유가 있을까요??

2022-02-25 03:45 UTC, lowoon commented on src/test/java/domain/LotteryTest.java
> +				new Lottery(Parser.toLotteryNumberList(Arrays.asList(1,2,3,4,5,6)));
`assertThatDoesNotThrow(() -> new Lottery(Parser.toLotteryumberList(Arrays.asList(1,2,3,4,5,6)));`
궁금해서 여쭤봅니다ㅎㅎ. 위의 메서드와 차이가 있나요?? 전 위의 메서드를 써서요.

2022-02-26 06:35 UTC, skullkim commented on src/main/java/controller/LotteryGameController.java
> +		OutputView.printLotteries(lotteryGame.getLotteries());
inputMoney() / 1000 부분이 view인거 같네요. 이 부분은 로또 구입 금액을 나타내는, int money를 포장한 PurchaseAmount를 만들어 로또 구입 금액과 장수에 대한 연산을 해당 객체에거 진행하는 방식으로 바꾸겠습니다.

2022-02-26 06:35 UTC, skullkim commented on src/main/java/controller/LotteryGameController.java
> +		return InputView.inputValidMoney();
위 피드백을 반영하면서 같이 수정하겠습니다

2022-02-26 07:30 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryGenerateFamily.java
> +public interface LotteryGenerateFamily {
어디서 봤는지는 정확히 기억나지 않지만 디자인 패턴을 사용하는 경우 디자인 패턴을 사용 했음을 패턴 이름으로 해당 클래스와 인스턴스에 명시하라는 글을 읽었습니다. 예를 들어 팩토리 패턴을 사용할 경우 xxxFactory이런 식으로 명시하죠. LotteryGeenrateFamily의 경우 전략 패턴을 사용했습니다. 전략 패턴에서는 최상위에 존재하는 인터페이스를 "알고리즘 패밀리"라 칭하고 그의 구현채를 "전략"이라 칭하는 걸로 알고 있습니다. 그에 따라 알고리즘 패밀리인 LotteryGenerateFamily에는 "Family"라는 post fix를 붙였고 구현체의 post fix를 "Strategy"로 했습니다.

2022-02-26 07:30 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryRandomGeneratorStrategy.java
> +		for (int i = 1; i <= MAX_BOUND; i++) {
수정하겠습니다.

2022-02-26 07:37 UTC, skullkim commented on src/main/java/controller/LotteryGameController.java
> +		OutputView.printLotteries(lotteryGame.getLotteries());
1차 수정 완료

2022-02-26 07:37 UTC, skullkim commented on src/main/java/controller/LotteryGameController.java
> +		return InputView.inputValidMoney();
1차 수정 완료

2022-02-26 07:37 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryRandomGeneratorStrategy.java
> +		for (int i = 1; i <= MAX_BOUND; i++) {
1차 수정 완료

2022-02-26 07:40 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryGenerateFamily.java
> +	List<LotteryNumber> getNumbers();
그 생각을 못했네요... 수정하겠습니다.

2022-02-26 08:06 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryGenerateFamily.java
> +	List<LotteryNumber> getNumbers();
1차 수정 완료

2022-02-26 08:06 UTC, skullkim commented on src/main/java/domain/Rank.java
> +	FOURTH(4, 50_000), FIFTH(3, 5_000), NONE(1, 0);
수정하겠습니다.

2022-02-26 08:09 UTC, skullkim commented on src/main/java/domain/Rank.java
> +	FOURTH(4, 50_000), FIFTH(3, 5_000), NONE(1, 0);
1차 수정 완료

2022-02-26 08:33 UTC, skullkim commented on src/main/java/domain/Lottery.java
> +		return LOTTERY_SIZE - differences.size();
저 부분을 설계하면서 스트림을 사용할 생각을 하지 못했네요. 수정하겠습니다.

2022-02-26 08:42 UTC, skullkim commented on src/main/java/domain/Lottery.java
> +		return LOTTERY_SIZE - differences.size();
1차 수정 완료

2022-02-26 09:00 UTC, skullkim commented on src/main/java/domain/LotteryNumber.java
> +	}
hashCode를 재정의 하지 않으면 hash 값을 사용하는 컬랙션 사용 시 올바른 동작을 보장하지 않습니다. 수정하겠습니다.

2022-02-26 09:00 UTC, skullkim commented on src/main/java/domain/LotteryNumber.java
> +	}
1차 수정 완료

2022-02-26 09:31 UTC, skullkim commented on src/test/java/domain/LotteryTest.java
> +				new Lottery(Parser.toLotteryNumberList(Arrays.asList(1,2,3,4,5,6)));
우선 assertThatNoException과 assertThatDoesNotThrow의 차이를 찾아보기 위해 구글링을 했지만 assertThatDoesNotThrow에 대한 정보를 찾지 못했습니다. 따라서 https://www.javadoc.io/doc/org.assertj/assertj-core/latest/index.html 에서 해당 메서드를 검색했지만 assertThatNoException은 검색이 되고, assertThatDoesNotThrow는 검색이 되지 않았습니다. 혹시나 버전 차이인가 싶어서 3.22.0~3.13.0까지 모두 검색을 해보았지만 assertThatDoesNotThrow에 대한 정보를 찾을 수 없었습니다.

현재 저는 assertj-core:3.22.0을 사용하고 있는데 혹시 어느 assertj의 어느 버전을 사용하고 있는지 알려주실 수 있나요?

2022-02-26 13:04 UTC, lowoon commented on src/test/java/domain/LotteryTest.java
> +				new Lottery(Parser.toLotteryNumberList(Arrays.asList(1,2,3,4,5,6)));
죄송합니다 제가 메서드 명을 잘못썼네요
위에 수정해 놓았지만 다시 알려드릴게요. `assertDoesNotThrow`입니다.

2022-02-26 14:08 UTC, skullkim commented on src/main/java/domain/Lotteries.java
> +		lotteriesNumber.forEach(lotteryNumber ->
우선 난수를 생성하는 로직 부분을 수정하면서 Lotteries 생성자 부분에 있는 forEach는 없어졌습니다.

피드백을 통해 주신 글을 보았음에도 저는 여기서 forEach를 사용하는 것이 상관 없다고 생각합니다. 
우선 저는 list에 존재하는 forEach를 사용한 것이지 stream에 존재하는 forEach를 사용한 것이 아닙니다. 
이 둘의 차이는 다음과 같습니다:
list의 forEach:
```java
// List의 forEach는 Iterable에 존재하는 forEach입니다
public interface Iterable<T> {
    default void forEach(Consumer<? super T> action) {
        Objects.requireNonNull(action);
        for (T t : this) {
            action.accept(t);
        }
    }
}
// lotteriesNumber는 ArrayList이며 ArrayList는 위의 forEach를
// override해 다음과 같이 사용합니다.
@Override
    public void forEach(Consumer<? super E> action) {
        Objects.requireNonNull(action);
        final int expectedModCount = modCount;
        final Object[] es = elementData;
        final int size = this.size;
        for (int i = 0; modCount == expectedModCount && i < size; i++)
            action.accept(elementAt(es, i));
        if (modCount != expectedModCount)
            throw new ConcurrentModificationException();
    }
```
그에 반해 stream의 forEach는 다음과 같습니다.
```java
public interface Stream<T> extends BaseStream<T, Stream<T>> {
    void forEach(Consumer<? super T> action);
}

abstract class ReferencePipeline<P_IN, P_OUT>
        extends AbstractPipeline<P_IN, P_OUT, Stream<P_OUT>>
        implements Stream<P_OUT>  {

    @Override
    public void forEach(Consumer<? super P_OUT> action) {
        evaluate(ForEachOps.makeRef(action, false));
    }
  
    @Override
        public void forEach(Consumer<? super E_OUT> action) {
            if (!isParallel()) {
                sourceStageSpliterator().forEachRemaining(action);
            }
            else {
                super.forEach(action);
            }
        }
}
```
결론적으로 List의 forEach는 stream의 forEach와 다르기 stream에서의 forEach 메서드의 본질을 해치지 않는다 생각합니다. 그리고 가독성 측면에서도 단순 for문 보다는 forEach가 더 좋다고 생각하는 데 혹시 제가 착각하고 있는 부분이 있나요?

2022-02-27 00:44 UTC, lowoon commented on src/main/java/controller/LotteryGameController.java
> +		OutputView.printLotteries(lotteryGame.getLotteries());
현재는 console로 입력을 받고 있는데요.
web이나 app같은 경우일 때는 어떻게 될까요??? 
InputView 호출을 Controller에서 하는게 맞는지는 여쭤본거랍니다~

2022-02-27 00:50 UTC, lowoon commented on src/main/java/domain/generatestrategy/LotteryGenerateFamily.java
> +public interface LotteryGenerateFamily {
전략 패턴일 경우 interface도 Strategy로 호칭을 많이 하는 걸로 알고 있어요.
family로 할 경우 이해가 바로되지 않을거 같아요.
<img width="722" alt="스크린샷 2022-02-27 오전 9 50 52" src="https://user-images.githubusercontent.com/45028630/155863768-795852c8-5471-4eef-9eeb-3756b6385c5d.png">

2022-02-27 01:06 UTC, lowoon commented on src/main/java/domain/Lotteries.java
> +		lotteriesNumber.forEach(lotteryNumber ->
`가독성` 측면에서도 for문을 쓰는 것을 추천하는데요.
가독성과 명확성 이라는 부분을 왜 신경을 쓰는걸까요??
함께 일하는 개발자 혹은 새롭게 투입된 개발자가 코드를 봤을 때 좀 더 파악하기 쉽도록 하기 위해서 아닐까요??
forEach의 경우 내부적인 로직은 for문과 같지만 서버 개발자들이 로직을 돌릴 때 주로 사용하지 않아요. javascript에서는 주로 사용하지만요. 
함께 일하는 개발자들에게 for문이 더 명확하다면 그게 가독성이 더 높은 것일 수 있지 않을까요??

2022-02-27 01:39 UTC, lowoon requested changes
고생하셨어요. 매트!
리뷰 반영 잘 해주셨어요! 자신의 생각과 의견 너무 좋네요👍
몇 가지 코멘트 남겼으니 확인해주시고 궁금한 점은 언제든지 DM 주세요 :)

2022-02-27 01:39 UTC, lowoon commented on src/main/java/domain/generatestrategy/LotteryRandomGeneratorStrategy.java
> +		}
```suggestion
		numbers = IntStream.rangeClosed(MINIMUM_RANGE, MAXIMUM_RANGE)
                                             .mapToObj(LottoNumber::new)
                                             .collect(Collectors.toList()); 
```
로 할 수도 있을거 같아요.

2022-02-27 01:39 UTC, lowoon commented on src/main/java/domain/Lottery.java
> +	private static final int LOTTERY_SIZE = 6;
이 숫자를 LotteryRandomGenerator와 Lottery 두 곳에서 관리를 하고 있네요??
한 곳에서 관리하는게 낫지 않을까요??

2022-02-27 01:39 UTC, lowoon commented on src/main/java/domain/PurchaseAmount.java
> +	private final int purchaseAmount;
상수, 변수, 생성자 등등 메서드 순서에 맞게 작성할 때 빈줄을 한줄씩 추가하여 나눠 주는게 보기 명확하답니다~

2022-02-27 01:39 UTC, lowoon commented on src/main/java/domain/WinningLottery.java
> +	final LotteryNumber bonusBall;
접근제어자가 없네요??

2022-02-27 01:39 UTC, lowoon commented on src/main/java/domain/PurchaseAmount.java
> +	public int getPurchasedLotteries() {
개수를 명시해주는게 명확하지 않을까요??

2022-02-27 01:39 UTC, lowoon commented on src/main/java/domain/WinningLottery.java
> +		if(winningNumbers.stream()
if 문 안에 로직이 있는 경우, 다른 로직이 추가되거나 하면 확인이 쉽지 않아 해당 로직을 메서드로 빼는것이 좋답니다~

2022-02-27 01:39 UTC, lowoon commented on src/main/java/domain/Lotteries.java
> +		return rankResult;
```suggestion
		return Rank.getValues()
		               .stream()
		               .collect(Collectors.toMap(Function.identity(), value -> INITIAL_RANKS));
```
로 할 수도 있을거 같아요.
그리고 getValues의 경우 values()와 혼동될거 같은데 좀더 자세하게 표현하는게 좋지 않을까요??

2022-02-27 01:39 UTC, lowoon commented on src/main/java/domain/Lotteries.java
> +			winners.put(rank, winners.get(rank) + 1);
`winners.merge(rank, 1, Integer::sum)`를 사용할 수도 있답니다

2022-02-27 01:39 UTC, lowoon commented on src/main/java/view/OutputView.java
> +		lotteries.forEach(lottery -> printLotteryNumbers(lottery.getNumbers()));
view에 도메인이 넘어와도 괜찮을까요??

https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/

2022-02-27 01:39 UTC, lowoon commented on src/test/java/domain/generateStrategy/LotteryGenerateMock.java
> +		index = 0;
mock 데이터 만들어 둔 것 좋은데요 👍 
index를 사용하여 한개씩 증가시키게 되면 테스트 케이스가 늘어나면 생각해야하는 부분이 많아지지 않을까요?
테스트를 짜면서 mock개체의 순서를 생각하는게 맞을까요??
index를 증가시키는 방식이 아니라 특정 로또를 꺼내는 방식으로 사용하는게 낫지 않을까요??

2022-02-27 02:53 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryGenerateFamily.java
> +public interface LotteryGenerateFamily {
수정하겠습니다

2022-02-27 03:17 UTC, skullkim commented on src/main/java/domain/Lotteries.java
> +		lotteriesNumber.forEach(lotteryNumber ->
우테코 하기 전까지 자바스크립트 위주로 하다 와서 제 눈에만 그게 명확해 보였나 보네요. 수정하겠습니다.

2022-02-27 05:06 UTC, skullkim commented on src/test/java/domain/LotteryTest.java
> +				new Lottery(Parser.toLotteryNumberList(Arrays.asList(1,2,3,4,5,6)));
assertThatNoException은 assertJ에 존재하고 assertDoesNotThrow는 Junit5 부터 Junit에서 지원하는 메서드네요. 

두 메서드를 뜯어 봤을 때 assertThatNoException은 다음과 같이 서술되 있습니다.
```java
Entry point to check that no exception of any type is thrown by a given throwingCallable.

```
assertDoesNotThrow는 다음과 같이 서술되 있습니다.
```java
AssertDoesNotThrow is a collection of utility methods that support explicitly asserting that a given code block does not throw an exception.
```
따라서 둘 다 exception을 발생시키지 않는지를 검사한다는 점은 같습니다.

이 둘은 내부 동작 과정과 프레임워크가 다르다는 차이가 있습니다.

우선 assertThatNoException은 assertJ가 제공하는 메서드이고 assertDoesNotThrow는 Junit5가 제공하는 메서드입니다.

assertThatNoeException의 내부 동작은 다음과 같이 이루어집니다.
```java
// NotThrownAssert 인스턴스를 만들어 반환 합니다.
public static NotThrownAssert assertThatNoException() {
    return new NotThrownAssert();
 }
 
// 에러가 없음을 확인하기 위해서는 NotThrownAssert에서
// isThrownBy 메서드를 사용해야 합니다.
// Assert that no exception of any type is thrown by the throwingCallable.
public class NotThrownAssert implements Descriptable<NotThrownAssert> {
 public void isThrownBy(final ThrowingCallable code) {
    Throwable throwable = ThrowableAssert.catchThrowable(code);
    assertThat(throwable).as(description).doesNotThrowAnyException();
  }
}

// assertJ는 Junit과 다르게 Throwable를 그대로 사용하지 않고
// ThrowingCallable이라는, Throwsable을 extends하는 별도의 구현채를 만들어 사용합니다.
// ThrowingCallable 일부 구조는 다음과 같습니다.

/**
 * Assertion methods for {@link Throwable}s.
 * <p>
 * To create a new instance of this class, invoke <code>{@link Assertions#assertThat(Throwable)}</code>.
 * </p>
 */
public class ThrowableAssert<ACTUAL extends Throwable> extends AbstractThrowableAssert<ThrowableAssert<ACTUAL>, ACTUAL> {

  public interface ThrowingCallable {
    void call() throws Throwable;
  }

public static Throwable catchThrowable(ThrowingCallable shouldRaiseThrowable) {
    try {
      shouldRaiseThrowable.call();
    } catch (Throwable throwable) {
      return throwable;
    }
    return null;
  }
}

// 위의 isThrownBy에서는 ThrowAbleAssert의 catchThrowable를
// 호출해 반환값이 null이면 에러가 없고, Throwable 인스턴스를 반환
// 한다면 에러가 있다는 것으로 판단합니다.
// 그 후 doesNotThrowAnyException 메서드를 호출해 예외 발생 여부를
// 최종적으로 판단합니다.
// doesNotThrowAnyException의 구현은 다음과 같습니다.
// Verifies that the ThrowableAssert.ThrowingCallable didn't raise a throwable.
public void doesNotThrowAnyException() {
    if (actual != null) throw Failures.instance().failure(info, shouldNotHaveThrown(actual));
  }
```

그에 비해 assertDoesNotThrow의 내부 동작 과정은 다음과 같습니다.
```java

// assertDoesNotThrow는 많은 오버로드가 존재하지만 크게는 다음과 같은 두 개의 메서드로 나뉘어집니다.
class AssertDoesNotThrow {
    private static void assertDoesNotThrow(Executable executable, Object messageOrSupplier) {
        try {
	    executable.execute();
	}
	catch (Throwable t) {
	    UnrecoverableExceptions.rethrowIfUnrecoverable(t);
	    throw createAssertionFailedError(messageOrSupplier, t);
	}
    }

    private static <T> T assertDoesNotThrow(ThrowingSupplier<T> supplier, Object messageOrSupplier) {
        try {
	    return supplier.get();
        }
	catch (Throwable t) {
	    UnrecoverableExceptions.rethrowIfUnrecoverable(t);
	    throw createAssertionFailedError(messageOrSupplier, t);
        }
    }
}

// 이 두 메서드의 가장 큰 차이는 첫 번째 파라미터의 타입입니다. 
// 하지만 두 타입을 뜯어보면 결국에는 같은 일은 한다는 것을 알 수 있습니다.
//Executable is a functional interface that can be used to implement any generic block of code that potentially throws a Throwable.
//The Executable interface is similar to Runnable, except that an Executable can throw any kind of exception.
@FunctionalInterface
@API(status = STABLE, since = "5.0")
public interface Executable {
    void execute() throws Throwable;
}

// ThrowingSupplier is a functional interface that can be used to implement any generic block of code that returns an
// object and potentially throws a Throwable.
// The ThrowingSupplier interface is similar to java.util.function.Supplier, except that a ThrowingSupplier can throw any // kind of exception, including checked exceptions.
@FunctionalInterface
@API(status = STABLE, since = "5.0")
public interface ThrowingSupplier<T> {
	/**
	 * Get a result, potentially throwing an exception.
	 *
	 * @return a result
	 */
	T get() throws Throwable;
}

// 따라서 assertDoesNotThrow는 수 많은 오버로드가 존재하지만
// 결국에는 다음과 같은 하나의 일을 합니다.
try {
    // 첫 번째 인자로 받은 코드를 실행시킨다.
    executable.execute();
} catch (Throwable t) {
    // 예외가 발생 하면 예외가 unrecoverable exception인지를 판단해
    // unrecoverable exception 이면 해당 exception을 다시
    // 던진다
    UnrecoverableExceptions.rethrowIfUnrecoverable(t);
   // assertionFailedError를 만들어 던진다.
    throw createAssertionFailedError(messageOrSupplier, t);
}
private static AssertionFailedError createAssertionFailedError(Object messageOrSupplier, Throwable t) {
    String message = buildPrefix(nullSafeGet(messageOrSupplier)) + "Unexpected exception thrown: "
	    + t.getClass().getName() + buildSuffix(t.getMessage());
	return new AssertionFailedError(message, t);
}

//  UnrecoverableExceptions 구현:
/**
 * Internal utilities for working with <em>unrecoverable</em> exceptions.
 *
 * <p><em>Unrecoverable</em> exceptions are those that should always terminate
 * test plan execution immediately.
 *
 * <h4>Currently Unrecoverable Exceptions</h4>
 * <ul>
 * <li>{@link OutOfMemoryError}</li>
 * </ul>
 *
 * <h3>DISCLAIMER</h3>
 *
 * <p>These utilities are intended solely for usage within the JUnit framework
 * itself. <strong>Any usage by external parties is not supported.</strong>
 * Use at your own risk!
 *
 * @since 1.7
 */
@API(status = INTERNAL, since = "1.7")
public final class UnrecoverableExceptions {

	private UnrecoverableExceptions() {
		/* no-op */
	}

	/**
	 * Rethrow the supplied {@link Throwable exception} if it is
	 * <em>unrecoverable</em>.
	 *
	 * <p>If the supplied {@code exception} is not <em>unrecoverable</em>, this
	 * method does nothing.
	 */
	public static void rethrowIfUnrecoverable(Throwable exception) {
		if (exception instanceof OutOfMemoryError) {
			ExceptionUtils.throwAsUncheckedException(exception);
		}
	}
```

결론: 내부 동작 과정과 프레임워크의 차이가 존재합니다. 현재 테스트에서는 assertJ를 사용했기 때문에 assertDoesNotThrow 보다는 assertThatNoException을 사용하는 것이 일관성 측면에서 좋다고 생각됩니다.

2022-02-27 05:32 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryRandomGeneratorStrategy.java
> +		}
그러네요... 아직 스트림에 있는 모든 기능을 숙지하지 못한거 같네요. 수정하겠습니다.

2022-02-27 05:44 UTC, skullkim commented on src/main/java/domain/Lottery.java
> +	private static final int LOTTERY_SIZE = 6;
그러네요. 추가적으로 로또 숫자 범위 관련 상수도 LotteryRandomGeneratorStrategy와 LotteryNumber 두 곳에서 관리하고 있네요. 숫자 범위의 경우 LotteryNumber에서, 숫자 개수의 경우 Lottery에서 관리하는 게 적합하다 생각하기 때문에 LotteryRandomGeneratorStrategy에 있는 해당 상수들을 없애고 Lottery와 LotteryNumber에서 해당 상수들을 private에서 public으로 바꾼 후 사용하겠습니다.

2022-02-27 05:58 UTC, skullkim commented on src/main/java/domain/PurchaseAmount.java
> +	private final int purchaseAmount;
상수와 변수의 경계에서 빈 줄을 추가하란 의미인가요? 아니면 하나를 선언할 때마다 빈줄을 추가하란 의미인가요?
예를 들어
1번:
```java
private static final int AMOUNT_MIN_RANGE = 1_000;
private static final int AMOUNT_MAX_RANGE = 100_000;

private final int purchaseAmount;
```
2번:
```java
private static final int AMOUNT_MIN_RANGE = 1_000;

private static final int AMOUNT_MAX_RANGE = 100_000;

private final int purchaseAmount;
```
이 두 개 중 어느것을 말하신 건가요?

2022-02-27 05:59 UTC, skullkim commented on src/main/java/domain/WinningLottery.java
> +	final LotteryNumber bonusBall;
빼먹었네요... 수정하겠습니다.

2022-02-27 06:05 UTC, skullkim commented on src/main/java/domain/PurchaseAmount.java
> +	public int getPurchasedLotteries() {
저 메서드 명을 지정할 때는 명확하다 생각했는데 다시 생각해 보니 구매한 로또 들을 반환하는 건지 개수를 반환하는 건지 명확하지가 않네요. 조금 길긴 하지만 getTheNumberOfPurchasedLotteries로 바꾸겠습니다.

2022-02-27 06:22 UTC, skullkim commented on src/main/java/domain/WinningLottery.java
> +		if(winningNumbers.stream()
잘 이해가 되지 않는데 조금만 더 상세히 설명해 주실 수 있나요?
우선 제가 지금까지 생각한 바는 다음과 같습니다.
조건문을 메서드 내에서 쓴다는 것이 코드의 흐름을 다른 방향으로 바꾸는 것이라 조건문 내부와 외부에 있는 코드가 길어지면 의도를 명확히 파악할 수 없다. 따라서 조건문을 사용하면 하나의 메서드 내에 두 개의 흐름(if 내부와 외부)이 생기기 때문에 해당 흐름들을 별도의 메서드로 빼내야 한다. 

혹시 이 의도가 맞나요?

2022-02-27 10:02 UTC, skullkim commented on src/main/java/domain/Lotteries.java
> +		return rankResult;
values와 비슷한 기능을 하기 때문에 getValues로 지었는데 혼동의 여지가 있네요.. 바꾸겠습니다.

2022-02-27 11:19 UTC, skullkim commented on src/main/java/domain/Lotteries.java
> +			winners.put(rank, winners.get(rank) + 1);
이런게 있는 줄은 처음 알았네요. 한번 사용해 볼게요

2022-02-27 11:31 UTC, skullkim commented on src/test/java/domain/generateStrategy/LotteryGenerateMock.java
> +		index = 0;
원하는 등수와 구매해야 할 갯수를 입력 받아 해당 등수를 입력 받은 갯수 만큼 반환하는 방식으로 바꾸겠습니다.

2022-02-28 03:36 UTC, skullkim commented on src/main/java/controller/LotteryGameController.java
> +		OutputView.printLotteries(lotteryGame.getLotteries());
뷰가 필요한 데이터를 요청하면 컨트롤러가 모델에서 필요한 데이터를 뽑아와서 뷰에게 데이터를 응답한 뒤 뷰가 알아서 출력을 해야 합니다. 즉, 컨트롤러는 그저 뷰에게서 데이터를 받고, 모델의 데이터중 필요한 것을 반환하는 역할을 해야 하지만 현재 코드에서는 뷰가 컨트롤러에 포함되 있네요. 수정하겠습니다.

2022-02-28 11:41 UTC, skullkim commented on src/main/java/controller/LotteryGameController.java
> +		OutputView.printLotteries(lotteryGame.getLotteries());
2차 수정 완료

2022-02-28 11:41 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryGenerateFamily.java
> +public interface LotteryGenerateFamily {
2차 수정 완료

2022-02-28 11:41 UTC, skullkim commented on src/main/java/domain/Lotteries.java
> +		lotteriesNumber.forEach(lotteryNumber ->
2차 수정 완료

2022-02-28 11:41 UTC, skullkim commented on src/main/java/domain/generatestrategy/LotteryRandomGeneratorStrategy.java
> +		}
2차 수정 완료

2022-02-28 11:41 UTC, skullkim commented on src/main/java/domain/Lottery.java
> +	private static final int LOTTERY_SIZE = 6;
2차 수정 완료

2022-02-28 11:41 UTC, skullkim commented on src/main/java/domain/WinningLottery.java
> +	final LotteryNumber bonusBall;
2차 수정 완료

2022-02-28 11:41 UTC, skullkim commented on src/main/java/domain/PurchaseAmount.java
> +	public int getPurchasedLotteries() {
2차 수정 완료

2022-02-28 11:42 UTC, skullkim commented on src/main/java/domain/Lotteries.java
> +		return rankResult;
2차 수정 완료

2022-02-28 11:42 UTC, skullkim commented on src/main/java/domain/Lotteries.java
> +			winners.put(rank, winners.get(rank) + 1);
2차 수정 완료

2022-02-28 11:42 UTC, skullkim commented on src/main/java/view/OutputView.java
> +		lotteries.forEach(lottery -> printLotteryNumbers(lottery.getNumbers()));
2차 수정 완료

2022-02-28 11:42 UTC, skullkim commented on src/test/java/domain/generateStrategy/LotteryGenerateMock.java
> +		index = 0;
2차 수정 완료

2022-02-28 12:12 UTC, lowoon commented on src/main/java/domain/PurchaseAmount.java
> +	private final int purchaseAmount;
1번을 말씀드린거에요.
예시를 보여드리면서 말씀드리는게 더 명확했을거 같네요!

2022-02-28 12:19 UTC, lowoon commented on src/test/java/domain/LotteryTest.java
> +				new Lottery(Parser.toLotteryNumberList(Arrays.asList(1,2,3,4,5,6)));
현재는 테스트를 할 때 assertj만 쓰고 있는데요. 추후에는 mock도 쓰시게 될거에요.
필요에 의해 여러 프레임워크를 이미 쓰고 있기 때문에 여러 프레임워크를 한 테스트에서 쓰는 것을 불편해하지 않으셔도 될거 같아요. 😄 
한가지 예시를 추가해드리면 로또 개수를 검증하면서 안의 로또가 내가 원하는대로 생성됐는지 테스트하는 것처럼 여러 assert 테스트를 하는 경우가 생길텐데요. 이 경우에 assertAll을 쓰기도 합니다.
```
assertAll(
        () -> assertThat(lotteries.getLotteries().size()).isEqualTo(lotteryNumber),
        () -> assertThat(lotteries.getLotteries().get(0)).isEqualTo(lottery)
)
```
아래와 같이 되어 있을 경우, 첫번째 assertThat에서 에러가 발생할 경우 두번째 asserThat 테스트는 돌지 않는데, assertAll을 쓰는 경우에는 첫번째 assertThat에서 에러가 발생하더라도 두번째 assertThat테스트가 돌게 됩니다.
```
assertThat(lotteries.getLotteries().size()).isEqualTo(lotteryNumber);
assertThat(lotteries.getLotteries().get(0)).isEqualTo(lottery);
```

2022-02-28 12:21 UTC, lowoon commented on src/main/java/domain/generatestrategy/LotteryRandomGeneratorStrategy.java
> +		}
저도 스트림의 모든 기능을 알지 못합니다ㅎㅎ
이렇게 알아가시면 되세요. 이러한 방법도 있다라고 말씀드린겁니다 😄

2022-02-28 12:27 UTC, lowoon commented on src/main/java/domain/WinningLottery.java
> +		if(winningNumbers.stream()
네 맞습니다! 
다만, Objects.isNull() 혹은 flag == true와 같이 단순한 경우에는 분리를 하지 않아도 파악이 쉬우니 따로 해주지 않아도 됩니다.
위와 같이 조건문의 분기 로직이 긴 경우에 분리를 시켜주는 것이 파악하기 좋습니다~

2022-02-28 13:02 UTC, lowoon approved these changes
고생하셨어요. 스컬! 이전 리뷰 내용을 잘 반영해주셨습니다 💯
코멘트 내용이 많았는데 다 반영을 해주셨네요 👍 
몇가지 코멘트를 달아봤는데요. 코멘트 반영은 2단계에서 부탁드릴게요.
추가적인 궁금증은 이 pr이 머지되어도 댓글 남겨주셔도 좋구 DM도 좋습니다.

2022-02-28 13:02 UTC, lowoon commented on src/main/java/domain/WinningLottery.java
> +	}
```suggestion
	private void validateBonusBall(final List<LotteryNumber> winningNumbers, final LotteryNumber bonusBall) {
		if (hasDuplicatedNumber()) {
		        throw new IllegalArgumentException(LotteryMessage.DUPLICATED_WINNING_NUMBER_WITH_BONUS_NUMBER);
		}
	}

	private boolean hasDuplicatedNumber(final List<LotteryNumber> winningNumbers, final LotteryNumber bonusBall) {
		return winningNumbers.stream()
				 .anyMatch(winningNumber -> winningNumber.equals(bonusBall));
		}
	}
```

2022-02-28 13:02 UTC, lowoon commented on src/main/java/utils/LotteryMessage.java
> +	public static final String LOTTERY_SIZE_ERROR = LOTTERY_NUMBER + "는 6개여야 합니다.";
메세지를 정해놓고 쓰고 있는데요.
해당 메세지의 값들이 변하는 경우에는 메세지도 같이 변해야하지 않을까요?
예를 들어 로또 개수가 6개에서 7개로 바뀌는 경우에는 이부분도 같이 수정이 되야할 텐데요.
이러한 값들을 서버에서 정의한 값을 사용하도록 할 수 있지 않을까요??

그리고 이렇게 메세지를 한곳에서 관리하게 되면 실제 사용하는 곳에서는 이곳으로 넘어와 확인을 해야할텐데요.
로또 개수에 대한 에러인데 다른 에러를 파악할 때 이부분을 알아야 할까요?? 한곳에서만 사용하는 메세지의 경우에는 사용하는 곳에 정의하는 것이 파악하기 더 좋지 않을까요??

2022-02-28 13:02 UTC, lowoon commented on src/main/java/controller/dto/LotteriesDto.java
> +
이해하기 어렵다고 하셨는데 잘 반영하셨네요!
어려운 내용은 생각이 들거나 나중에 또 쓰게 될때 읽으시면 지금은 이해 안갔던 부분이 이해가 가실거에요.
링크에 나와있던 이유 말고 간단한 이유을 추가해드리면, 도메인에 개인정보와 같이 민감한 정보가 있는 경우에 도메인을 넘기게되면 민감한 정보도 같이 넘어가게 될거에요. 이렇게 넘겨주는 데이터에 대한 검증을 한다고 보시면 될거 같아요.

추가한 이유때문에 더 어려워지지 않으셨으면 좋겠네요... 😱

2022-02-28 13:02 UTC, lowoon commented on src/test/java/domain/generateStrategy/LotteryGenerateMock.java
> +		if (theNumberOfLotteries-- > 0) {
테스트에서는 개발자가 직접 테스트할 객체를 만들어 주기 때문에 `LotteryGenerateStrategy`를 상속받지 않고 util형태로 만들어도 되지 않을까요??

참고용입니다. 제가 생각한 방식은 이런 방식이었어요. 
Integer대신 Rank를 넣을 수도 있겠죠?? 혹은 static으로 만들어 놓아서 사용할 수도 있을거 같구요??
```
private final Map<Integer, Lottery> rankToLottery;

public LotteryGenerateMock() {
                 rankToLottery = new HashMap<>();
		rankToLottery.put(1, toLottery(Arrays.asList(1, 2, 3, 4, 5, 6)));
		rankToLottery.put(2, toLottery(Arrays.asList(1, 2, 3, 4, 5, 7)));
		rankToLottery.put(3, toLottery(Arrays.asList(1, 2, 3, 4, 5, 9)));
		rankToLottery.put(4, toLottery(Arrays.asList(1, 2, 3, 4, 9, 10)));
		rankToLottery.put(5, toLottery(Arrays.asList(1, 2, 3, 8, 9, 10)));
		rankToLottery.put(6, toLottery(Arrays.asList(1, 2, 10, 11, 12, 13)));
}
```

2022-02-28 13:02 UTC, lowoon commented on src/main/java/domain/PurchaseAmount.java
> +	private static final int AMOUNT_MAX_RANGE = 100_000;
참고용입니다. 수정하지 않으셔도 됩니다.
PurchaseAmount라고 해서 고려하지 않아도 될거 같지만 생각해보시면 좋은 부분일거 같아 코멘트 달아요~

PurchaseAmount가 아닌 Money라고 했을 때입니다.
money의 책임을 어떻게 주었느냐에 따라 개발자마다 다를거 같은데요.
로또 한장 가격에 대한 책임을 LottoGame에 주는게 더 맞을지 money에 주는게 맞을지 생각해 봐주세요ㅎㅎ

2022-02-28 13:04 UTC, lowoon commented on src/main/java/domain/Rank.java
> +		if (properRank.getCorrectedBalls() == SECOND_THIRD_CORRECTED_BALLS && !hasBonusBall) {
rank나 purchaseAmount에 대한 테스트가 없네요??

2022-02-28 13:04 UTC, merged

2022-03-02 03:36 UTC, skullkim commented on src/main/java/utils/LotteryMessage.java
> +	public static final String LOTTERY_SIZE_ERROR = LOTTERY_NUMBER + "는 6개여야 합니다.";
메시지를 여러 군데에서 선언해 사용하는 경우, 메시가 변경 되었을 때 해당 메시지가 어디 있는지를 찾는 불편함을 줄일 수 있을 거 같아서 별도의 클래스로 분리했습니다. 

실제 사용되는 곳에서 메시지를 확인하기 위해서는 해당 static 변수에 커서를 갖다 대면 내용을 확인할 수 있어 넘어오는 불편함은 없을거라 생각합니다. 혹여나 해당 기능을 지원하지 않는 IDE를 사용한다면 그것은 그 사람의 잘못이라 생각합니다. 클린 코드 30페이지 "멤버 변수 접두어" 부분을 보면 멤버 변수에는 prefix로 "m_"을 붙이지 말라면서 멤버 변수를 다른 색으로 표시해야 하는 IDE를 사용해야 마땅하다 라는 내용이 나옵니다. 따라서 커서를 변수에 갖다 댔을 때 해당 변수의 선언을 보여주지 않는 IDE라면 사용하지 말아야 하며 코드를 작성할 때 좋은 IDE에 기능을 활용하는 것이 좋다고 생각합니다. 이 기능을 활용할 경우 다른 에러를 파악하지 않아도 됩니다.

해당 메세지의 값들이 변하는 경우에는 메세지도 같이 변해야하지 않을까요?
해당 메시지의 값들이 변하는 경우에 대비해 아예 LotteryMessage 내부에 클래스 메서드를 정의해 해당 값을 활용해 만든 문자열을 반환하게 하면 될거 같습니다.

2022-03-02 03:55 UTC, skullkim commented on src/main/java/domain/PurchaseAmount.java
> +	private static final int AMOUNT_MAX_RANGE = 100_000;
우선 저 역시 Money라는 도메인에 대해 고민을 했었습니다. 하지만 로또 게임에서는 돈을 오직 로또는 구입할 때 사용하기 때문에 Money라는 도메인을 만들어 버리면 목적에 맞지 않는 광범위한 의미로 사용될 거 같아서 "로또 구입 금액"을 나타내기 위해 PurchaseAmount를 사용했습니다.

만약 Money라는 것을 사용한다면 Money는 (광범위한 의미의)돈에 관련된 책임만 가져야 된다고 생각합니다. 따라서 입력한 돈의 범위, 로또 한 장에 대한 가격에 대한 책임은 Money가 아닌 LotteryGame에 주는 것이 맞다고 생각합니다.

따라서 기존에는 다음과 같았던 PurchaseAmount가
```java
public class PurchaseAmount {

	private static final int AMOUNT_MIN_RANGE = 1_000;
	private static final int AMOUNT_MAX_RANGE = 100_000;
	private final int purchaseAmount;

	public PurchaseAmount(final int purchaseAmount) {
		validateRange(purchaseAmount);
		this.purchaseAmount = purchaseAmount;
	}

	private void validateRange(final int number) {
		if (isOutOfRange(number)) {
			throw new IllegalArgumentException(LotteryMessage.PURCHASE_AMOUNT_RANGE_ERROR);
		}
	}

	private boolean isOutOfRange(final int number) {
		return number < AMOUNT_MIN_RANGE || number > AMOUNT_MAX_RANGE;
	}

	public int getTheNumberOfPurchasedLotteries() {
		return purchaseAmount / AMOUNT_MIN_RANGE;
	}

	public double calculateEarningRate(final int earningAmount) {
		return (double) earningAmount / purchaseAmount;
	}

}
```
Money로 바뀐다면 대략적으로는 다음과 같이 바뀌어야 될 거 같습니다.
```java
public class Money {

	private final int money;

	public Money(final int money) {
		this.money = money;
	}

	public int getTheNumberOfPurchasedStuff(final int price) {
		return money / price;
	}

	public double calculateEarningRate(final int earningAmount) {
		return (double) earningAmount / purchaseAmount;
	}

}
```

2022-03-02 04:42 UTC, skullkim commented on src/test/java/domain/generateStrategy/LotteryGenerateMock.java
> +		if (theNumberOfLotteries-- > 0) {
Map을 사용하고 Rank를 키로 사용하는 방법이 더 좋은거 같네요. 그럼에도 상속을 받지 않아도 된다는 것에서는 한 가지 의문이 생깁니다. 상속을 받지 않고 사용을 하면 의도하지 않은 에러가 발생할 수 있을 거 같습니다. 

현재 LotteryGenerateStrategy를 생성자의 인자로 받고 있는 LotteryGame에서 LotteryGenerateStrategy의 구현체 인스턴스를 사용하는 곳에서는 getNumbers메서드를 사용하고 있습니다. 따라서 상속을 하지 않는다면 생성자의 인자로 넘길 수 도 없습니다. 넘겨 진다고 가정을 해도 getNumbers 메서드가 다른 이름으로 바뀐다면 목 객체와 LotteryGenerateStrategy의 추상 메서드 이름 불일치로 인한 에러가 발생하지 않아 이를 인지하지 못해 에러가 발생할 거 같은데 이에 대한 해결책이 있나요?

2022-03-02 04:43 UTC, skullkim commented on src/main/java/domain/Rank.java
> +		if (properRank.getCorrectedBalls() == SECOND_THIRD_CORRECTED_BALLS && !hasBonusBall) {
추가하겠습니다.

2022-03-03 09:21 UTC, lowoon commented on src/main/java/utils/LotteryMessage.java
> +	public static final String LOTTERY_SIZE_ERROR = LOTTERY_NUMBER + "는 6개여야 합니다.";
1. 제가 말한 부분은 `해당 객체의 책임으로 에러를 던지는데 다른 클래스로 이동해야할 필요가 있느냐` 였어요.
메세지가 변경되었을 때 해당 메세지가 객체 내에 있다면 객체의 상단으로 올라가거나 스컬이 말한거처럼 ide를 활용할 수 있지 않을까요??
객체에 대해 **응집도**과 **결합도**를 얘기하면서, 응집도는 높이고 결합도는 낮춰야 한다고 얘기를 많이 하죠.
응집도는 하나의 기능, 역할과 관련해서 변경하는 부분이 적어야 한다는 부분이고, 결합도는 다른 객체와 결합된 정도를 낮춰 수정이 일어났을때 영향을 받는 부분을 줄여야 한다는 부분인데요.
이 관점에서 보면 로또에 대한 수정으로 인해 LottoMessage도 수정이 필요하게 될 수 있기 때문에 안좋을 수 있는거죠.
![응집도](https://user-images.githubusercontent.com/45028630/156535400-9dadae2f-ca74-4fd4-8c5e-debfd093375a.jpeg)
![결합도](https://user-images.githubusercontent.com/45028630/156535427-19d59df2-c3b8-4353-88f5-857f00336953.jpeg)

현재 저희팀에서도 스컬과 같이 메세지를 모아서 사용을 하고 있는데요.
그 이유는 저희는 메세지뿐만이 아니라 에러에 해당되는 코드들을 정의해서 쓰고 있어 코드가 겹치면 안되기 때문에 다른 에러들의 코드들도 함께 확인을 해야하고, 공통으로 쓰는 에러와 메세지도 많기 때문에 함께 관리를 하고 있습니다.
현재 프로그램의 경우 이러한 필요성이 있나요??

2. 해당 값을 활용해 만든 문자열을 반환하도록 하는 부분이 아직 반영이 안된거 같아요.

2022-03-03 09:31 UTC, lowoon commented on src/test/java/domain/generateStrategy/LotteryGenerateMock.java
> +		if (theNumberOfLotteries-- > 0) {
제가 말씀드린 활용법은 LotteryGenerateMock으로만 사용하는 것이 아니라 
`new Lottery(Parser.toLotteryNumberList(Arrays.asList(1, 2, 3, 4, 5, 6)))`
로 다른 테스트에서도 중복되고 있는 Lottery를 반환하는 객체를 만드는 것이였습니다.
공통으로 사용할 수 있는 Lottery를 반환하는 객체가 있다면 LotteryGenerateMock에서도 활용할 수 있고, 다른 테스트에서도 활용할 수 있겠죠??
그래서 util을 말씀드렸었던 거랍니다~ 예시 때문에 더 헷갈렸을 수도 있었겠네요

2022-03-03 09:33 UTC, lowoon commented on src/main/java/domain/PurchaseAmount.java
> +	private static final int AMOUNT_MAX_RANGE = 100_000;
제가 생각한 것과 똑같네요!ㅎㅎ 한번 고민해보면 나중에도 도움이 될거 같아 말씀드려 봤습니다.

2022-03-04 07:03 UTC, skullkim commented on src/main/java/utils/LotteryMessage.java
> +	public static final String LOTTERY_SIZE_ERROR = LOTTERY_NUMBER + "는 6개여야 합니다.";
수정하겠습니다.

2022-03-04 09:39 UTC, skullkim commented on src/test/java/domain/generateStrategy/LotteryGenerateMock.java
> +		if (theNumberOfLotteries-- > 0) {
LotteryGenerateMock은 로또를 생성하는 책임을 갖고 있기 때문에 그렇게 하면 좋을 거 같네요. 일단 나머지 피드백을 수정하고 시간이 있다면 수정하겠습니다.

2022-03-05 05:46 UTC, skullkim commented on src/main/java/utils/LotteryMessage.java
> +	public static final String LOTTERY_SIZE_ERROR = LOTTERY_NUMBER + "는 6개여야 합니다.";
수정하겠습니다