[1단계 - 로또(자동)] 리버(구동희) 미션 제출합니다.
woowacourse/java-lotto pull request #406
Opened 2022-02-24 08:49 UTC by gudonghee2000

안녕하세요 던😊😊
이번 미션 리뷰 요청을 드리게된 리버입니다!

이번에 페어인 알렉스와 함께 미션을 진행해나가면서
TDD를 잘지키며 구현해 나가는 것에 집중하면서 미션을 진행해 나갔는데요!

미션을 진행하면서 궁금한점이 있습니다!

<br/>
<br/>
 
### 기능별로 view를 나눠주기
미션을 진행하면서 페어인 알렉스와 함께 단순히 InputView, OutputView에 입,출력 로직을 담게되면 가독성이 좋지 않을 것을 고려하여 각 기능별로 view클래스를 나누어 구현해주었습니다. 그리고 view 클래스들의 공통되는 기능을 interface로 구현해주었는데요. interface를 사용 했지만 view클래스간에 관계를 맺어 준다거나 다형성을 적용하지는 않았습니다. 그리고 프로그램의 규모에 비해 view클래스가 많아 진건 아닐까 하는 의문이 들었는데요! 이런 경우에는 인터페이스를 적용하는것은 바람직하지 않은것일까요?!

<br/>
<br/>

### model enum 클래스를 view에 그대로 가져와도 될까요?
로또 미션을 알렉스와 함께 진행하면서 model에 있는 enum객체의 데이터를 view에게 전달하는 부분에서 고민을 했는데요,
저희는 우선 model에 있는 enum객체를 그대로 view에게 전달해주었어요! 그런데, enum객체에 set과 같이 상태를 변경하는 로직이 없다면 저희가 진행햇던 방식과 같이, view에 그대로 enum 객체를 전달해도 되는 것인지 의문이 들었습니다! enum객체에 set과 같은 상태를 변경하는 로직이 없다면, view에게 enum객체를 전달해도 괜찮을까요??

<br/>
<br/>

 ### 하나의 model 객체에 여러가지 model 객체가 들어있는 경우 
```java
import java.util.List;
import java.util.Map;

public class LottoGame {
    private Money money;
    private LottoTickets lottoTickets;
    private WinningNumbers winningNumbers;
    private WinningStatistics statistics;

    public void insertMoney(final int money) {
        this.money = new Money(money);
    }

    public void purchaseLottoTickets(final GenerateStrategy generateStrategy) {
        final int purchaseCount = money.generatePurchaseCount();
        lottoTickets = new LottoTickets(purchaseCount, generateStrategy);
    }
```
위 코드는 LottoController와 연결해주는 LottoGame 객체인데요! 다른 model들이 직접 LottoController와 연결되기보다는 LottoGame 모델 객체를 통해 연결되도록 구현했습니다!
그런데 구현 하다보니 LottoGame 모델에 다른 model 객체들이 위 코드처럼 필드로 들어가게 됫습니다! 이렇게 하나의 model이 많은 수의 model 객체를 필드로 가지는 것이 문제가 있을까요?!

<br/>
<br/>
코드를 리팩터링하는 과정에서 테스트 코드를 추가 수정해야하는데 마감시간이 있어 진행하지 못했습니다..(주석처리하였습니다!)
PR을 제출한 뒤에 추가로 수정하여 올려놓겠습니다!!
감사합니다 던😊😊!!

2022-02-26 07:29 UTC, ghost requested changes
안녕하세요 리버! 리뷰어 던입니다.
테스트 코드 위주로 코멘트 드렸습니다. 확인 부탁 드려요~

---
따로 질문주신것에 답변드릴게요!

1. `프로그램의 규모에 비해 view클래스가 많아 진건 아닐까 하는 의문` -> 프로그램 규모와 상관없이 필요하다면 개수가 많아져도 상관없어보여요. 근데 정말로 필요한건지를 다시한번 고민해보면 좋을 것 같아요! 가독성을 위해서 view클래스를 나누었다고 하셨는데 가독성이 향상되었는지에 대해 약간 의문이 있네요. 왜 InputView, OutputView이 입출력로직을 갖게되면 가독성이 좋지않다고 생각했는지 궁금합니다.

2. enum 객체에 set이 있는것과 enum객체를 view에 넘겨주는것이 어떤 관계가 있다고 생각하셔서 의문이 들었는지가 궁금합니다.

3. 인스턴스 필드의 수가 많다고 생각되시면 아래 사항들을 고민해보면 좋을 것 같아요!
- 반드시 인스턴스 필드로 선언해야하는 변수인지?
- 객체가 많은 책임을 갖고 있는것이 아닌지?
고민의 결과가 많은 수의 필드를 갖는 것이라면 그대로 두셔도 무방해보입니다.

2022-02-26 07:29 UTC, ghost commented on src/main/java/model/lottonumbergenerator/LottoNumberGenerator.java
> +    public static final int MAX_SIZE = 6;
MAX_SIZE 상수를 public으로 설정한 이유가 있을까요~?

2022-02-26 07:29 UTC, ghost commented on src/main/java/controller/MachineController.java
> +    private final OutputController outputController;
InputController와 OutputController를 사용한 이유를 알 수 있을까요?
그리고 리버는 인스턴스 변수로 선언하는 기준을 어떻게 정하고 있는지 알 수 있을까요~?

2022-02-26 07:29 UTC, ghost commented on src/main/java/validator/LottoNumberValidator.java
> +        if (isNotCorrectNumber(parsedNumber)) {
입력된 숫자가 로또 번호(1~45)에 속하는지는 로또게임의 비즈니스 로직인지에 대해 리버는 어떻게 생각하는지 궁금합니다.

2022-02-26 07:29 UTC, ghost commented on src/main/java/model/money/Money.java
> +    private final int money;
리버가 생각하는 원시값을 포장하는 이유에 대해서 알 수 있을까요?

2022-02-26 07:29 UTC, ghost commented on src/main/java/model/lottotickets/LottoTickets.java
> +            Rank key = lottoTicket.selectRank(winningNumbers, bonusNumber);
key라는 변수명으로 변수의 의미를 드러내기는 어렵지않을까요?

2022-02-26 07:29 UTC, gch01410 commented on src/test/java/model/lottonumbergenerator/LottoNumberGeneratorTest.java
> +class LottoNumberGeneratorTest {
생성된 번호의 개수가 6개인지도 검증해봐야 하지않을까요~?

2022-02-26 07:29 UTC, gch01410 commented on src/test/java/model/lottotickets/vo/LottoNumberTest.java
> +public class LottoNumberTest {
생성된 로또번호가 1미만인지도 검증해봐야 할 것 같아요

2022-02-26 07:29 UTC, gch01410 commented on src/test/java/model/lottotickets/LottoTicketsTest.java
> +class LottoTicketsTest {
통계 결과를 구하는 로직이 잘 동작하는지 검증이 필요해보여요!

2022-02-26 07:29 UTC, gch01410 commented on src/test/java/model/lottotickets/LottoTicketTest.java
> +class LottoTicketTest {
당첨등급을 결정하는 로직도 검증해봐야 할 것 같네요!

2022-02-26 07:29 UTC, gch01410 commented on src/test/java/model/winning/RankTest.java
> +        final boolean hasBonusNumber = true;
분기되는 모든 로직을 검증하는게 좋습니다!

2022-02-26 07:29 UTC, gch01410 commented on src/main/java/model/winning/Statistics.java
> +public class Statistics {
Statistics 가 갖고 있는 로직들도 테스트 코드를 작성해서 검증해볼 수 있을까요?

2022-02-26 07:29 UTC, gch01410 commented on src/test/java/model/winning/WinningNumbersTest.java
> +        WinningNumbers winningNumbers = new WinningNumbers(numbers, bonusNumber);
테스트 코드 작성이 누락된 것 같네요!

2022-02-26 07:29 UTC, gch01410 commented on src/test/java/validator/LottoNumberValidatorTest.java
> +    @ValueSource(strings = {"ada", "46"})
1미만인 케이스의 검증도 필요해보여요!

2022-03-01 13:07 UTC, gudonghee2000 commented on src/main/java/model/lottonumbergenerator/LottoNumberGenerator.java
> +    public static final int MAX_SIZE = 6;
리팩토링과정에서 발견하지못한것같아요! private로 변경하였습니다!

2022-03-01 13:16 UTC, gudonghee2000 commented on src/main/java/controller/MachineController.java
> +    private final OutputController outputController;
처음에 출력과 입력 종류별로 view클래스를 만들었어요! 그래서 lottoController에 입출력 view 객체들을 연결하면 필드가 너무많아 지지않을까 하는 우려에 InputController와 OutputController를 사용햇습니다!
지금은 view를 OutputView와 InputView로 변경하면서 InputController, OutputController를 제거하고 LottoController객체 내부에서 InputView와 OutputView 인스턴스 변수를 선언해주었습니다!
저는 객체 내부의 함수들에서 자주 사용되거나, 지역변수로 선언하면 가독성이 안좋아지는 경우에 인스턴스 변수를 선언하고있어요! 
그리고, Model, Controller, View와 같이 MVC 패턴에서 주요한 역할을 하는 객체들은 클래스 변수로 선언할시, 객체의 캡슐화를 저해한다고 생각하여  Model, Controller, View와 관련된 객체들은 인스턴스 변수로 선언하였습니다!

2022-03-01 13:22 UTC, gudonghee2000 commented on src/main/java/validator/LottoNumberValidator.java
> +        if (isNotCorrectNumber(parsedNumber)) {
저는 비지니스 로직에서 로또번호를 가지는 Number객체의 역할이라고 생각합니다! 
그런데, 페어와 함께 이야기를해보면서 모델에게 입력값을 주기전에 우선, "검증을 통해 정제된 값을 주는 것이 어떨까"에 대해 이야기를 해보았는데요. 
그래서 저는 어느정도 Validator를 통해 로또 번호라는 검증된 값을 전달해주는 것도 괜찮을 것 같다는 생각이 들어 validator를 통해 올바른 숫자인지 검증하게끔 구현해보았습니다!
지금은 로또게임의 비지니스 로직내부에서 로또번호를 가지는 Number 객체가 스스로 올바른 숫자인지 검증하도록 변경하였습니다!

2022-03-01 13:28 UTC, gudonghee2000 commented on src/main/java/model/money/Money.java
> +    private final int money;
저는 money라는 원시값을 포장함으로써 Money 객체가 스스로 몇개의 로또를 구매할지 판단하도록 하려고했어요!
그리고, 사용자가 moeny(투입금액)을 입력할때, 발생할수 있는 오류를 money가 스스로 검증하도록 하고자했어요!
저는 원시값이 검증이 필요하거나, 요청에 따라 스스로의 역할을 가질수 있다면 원시값을 포장해야 한다고 생각해요!

2022-03-01 13:30 UTC, gudonghee2000 commented on src/main/java/model/lottotickets/LottoTickets.java
> +            Rank key = lottoTicket.selectRank(winningNumbers, bonusNumber);
key라는 변수명을 좀더 의미를 들어내기 쉽게 foundRank라는 변수명으로 변경하였습니다!
그리고, lotto객체**(lottoTicket의 클래스명을 lotto로 수정하였습니다!)** 에게 요청을 보낼 함수명도 findWinningRank라고 변경하여 좀더 의미를 분명하게 하고자 변경했습니다!

2022-03-01 13:32 UTC, gudonghee2000 commented on src/test/java/model/lottotickets/vo/LottoNumberTest.java
> +public class LottoNumberTest {
@ParameterizedTest 와 @ValueSource를 통해 1미만인 경우(음수, 0)등 다양한 경우를 테스트 하도록 변경했습니다!

2022-03-01 13:33 UTC, gudonghee2000 commented on src/test/java/model/lottotickets/LottoTicketsTest.java
> +class LottoTicketsTest {
통계 결과를 테스트하는 코드를 추가로 작성하였습니다!!

2022-03-01 13:34 UTC, gudonghee2000 commented on src/test/java/model/lottotickets/LottoTicketTest.java
> +class LottoTicketTest {
일치하는 번호와 보너스볼 일치 여부에 따라 당첨 등급별로 테스트하도록 코드를 추가로 작성하였습니다!

2022-03-01 13:34 UTC, gudonghee2000 commented on src/test/java/model/winning/RankTest.java
> +        final boolean hasBonusNumber = true;
분기가 되는 당첨 등수를 모두 테스트하도록 테스트 코드를 추가로 작성하였습니다!!

2022-03-01 13:36 UTC, gudonghee2000 commented on src/main/java/model/winning/Statistics.java
> +public class Statistics {
WinningResult(**Statistics에서 WinningResult로 클래스명을 변경햇습니다!**)클래스의 당첨결과가 정상적으로 생성되는지와 수익률 계산이 당첨 결과와 일치하는지를 테스트하는 코드를 추가 작성햇습니다!

2022-03-01 13:36 UTC, gudonghee2000 commented on src/test/java/model/winning/WinningNumbersTest.java
> +        WinningNumbers winningNumbers = new WinningNumbers(numbers, bonusNumber);
WinningNumbers클래스의 기능들을 테스트하는 코드를 작성했습니다!

2022-03-01 13:38 UTC, gudonghee2000 commented on src/test/java/validator/LottoNumberValidatorTest.java
> +    @ValueSource(strings = {"ada", "46"})
1미만의 번호가 입력된 경우의 테스트를 Model 내부의 비지니스 로직에서 로또번호를 가지는 Number객체가 검증하도록 하였습니다! 
1미만이 입력되는경우도 테스트코드를 NumberTest클래스에 작성하였습니다!

2022-03-01 13:41 UTC, gudonghee2000 commented on src/test/java/model/lottonumbergenerator/LottoNumberGeneratorTest.java
> +class LottoNumberGeneratorTest {
추가로 생성된 번호가 6개인지 검증하는 테스트 코드를 작성하였습니다!!

2022-03-01 14:06 UTC, gudonghee2000 commented
안녕하세요 던!!
질문에 대해 말씀해주신 답변과 의문점 그리고 꼼꼼하게 봐주신 피드백 내용을 바탕으로 코드를 많이 수정해보았어요!😊😊
아래의 내용은 말씀해주신 답변과 던져주신 의문점을 바탕으로 내린 결과와 의문점입니다!

1. 처음에는 이번 미션에서 OutputView와 InputView로 모든 입출력 로직을 담기엔 하나의 클래스의 코드가 길어 질 수 있다고 생각했어요! 
그리고 입출력 단위별로 view클래스를 나누어 생성한다면 이후에 단위별로 입출력 조건이 추가되도 코드의 수정이 쉬어지지 않을까 생각하여 view클래스들을 나누어 입출력 로직을 가지게 하였어요! 그런데 막상 코드를 작성하고 보니 오히려 가독성이 많이 떨어진다고 느꼈어요!
피드백 주신 내용을 바탕으로 고민을 통해 OutputView와 InputView클래스로 입출력에 대해 작성하는 것이 좋을것 같다고 생각이 들었어요! 그래서 OutputView와 InputView클래스가 입출력을 담당하도록 코드를 수정햇어요! 
수정이후에 오히려 view클래스들을 입출력단위로별로 나눴을 때보다 가독성이 많이 좋아졌다고 느꼈습니다! 

2. 저는 model내부의 객체를 view에 그대로 전달하는 것은 사용자에게 model내부의 비지니스 로직을 노출 시키는 문제를 발생시킬수 있다고 생각해요! 
만약, view에게 전달된 model 객체가 암호화된 정보를 가지거나 set과 같이 객체의 상태를 변화 시킬수 있는 로직이 있다면 입출력 단에서 model을 변경시키는 문제가 발생 할 수 있다고 생각해요!
그래서 저는 view에게 model의 객체를 직접 전달하면 안된다고 생각해요!
그런데 enum 객체는 상수의 집합이고 또한, set과 같이 객체의 상태를 변경시키는 메소드가 없다면 enum객체는 model내부에 있다고해도 view에게 전달해도 괜찮지 않을까 하는 생각이 들어서 의문이 생겼어요!!

3.  던께서 말씀해주신 의문점들을 고민해보았어요! 
저는 LottoMachine객체가 가지는 인스턴스 필드들이 반드시 인스턴스 필드로 필요한 변수들이 아니라고 생각이 들었어요! 동시에 LottoMachine객체를 보면서 Controller가 할 일을 한번 더 반복하고 있다는 느낌이 들었어요!
그래서 LottoMachine객체를 제거하고 Controller단에서 model객체들을 연결해주었어요! 
이를 통해서, 불필요한 인스턴스 필드들을 제거 할 수 있었고, LottoMachine이 가지는 책임인 **전체 model객체의 연결**이라는 너무 큰책임을 제거하고 Controller에서 model 객체들이 스스로 연결되도록 할수 있었어요!

꼼꼼한 피드백과 질문에 대해 답변과 의문점을 던져주셔서 감사합니다 던!
이번 리뷰도 잘부탁드립니다😊😊!!

2022-03-02 15:47 UTC, gch01410 approved these changes
안녕하세요 리버!
1단계 권장 merge기간이 지나서 고민해볼만한 내용으로 간단히 코멘트드렸습니다.
코멘트 확인해주시고 2단계 추가구현과 같이 다시 pr보내주세요!
1단계 구현하시느라 수고 많으셨습니다! 👍

2022-03-02 15:47 UTC, gch01410 commented on src/main/java/controller/LottoController.java
> +    private final Generator generator;
인스턴스 변수로 선언하는 기준에 대해 리버의 생각을 말씀해주셨는데요!
`객체지향의 사실과 오해` 라는 책이 필독서로 알고 있는데 한번 읽어보면 도움될 것 같습니다!

2022-03-02 15:47 UTC, gch01410 commented on src/main/java/controller/LottoController.java
> +        showWinningResult(lottos, winningNumbers, money);
Money, Lottos, WinningNumbers 객체를 컨트롤러에서 생성하고 있네요!
이 객체들을 생성하는건 비즈니스 로직이 아닐까 생각하는데 리버는 어떻게 생각하시나요?

2022-03-02 15:47 UTC, merged

2022-03-03 08:48 UTC, gudonghee2000 commented on src/main/java/controller/LottoController.java
> +    private final Generator generator;
넵! 감사합니다 던!!