[1단계 - 로또(자동)] 소주캉(강승주) 미션 제출합니다.
woowacourse/java-lotto pull request #409
Opened 2022-02-24 08:52 UTC by sojukang

안녕하세요👋👋!!! 저는 `소주캉`입니다. 페어와 함께 열심히 로또 미션을 구현해보았습니다. 
부족하지만 잘 부탁드립니다!!

2022-02-25 10:39 UTC, KIMSIYOUNG requested changes
안녕하세요 소주캉! 
자동차경주에서 배우신 내용을 잘 적용해주셨네요🙂
많은 고민을 하신게 느껴지네요. 몇 가지 코멘트 달았으니 확인해주세요.
궁금하신 내용은 언제나 댓글 / DM 주세요!  

작성해주신 내용들에 대해서는 코멘트에 같이 답변해두었습니다.

2022-02-25 10:39 UTC, KIMSIYOUNG commented on README.md
> +- [x] 로또 구입 금액을 입력하면 구입 금액에 해당하는 로또를 발급해야 한다.
완료하신 요구사항들을 체크해주셔서 이해하는데 도움이 많이 되었어요👏

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +    public static void runGame() {
컨트롤러를 매번 생성하지 않고 스태틱으로 사용하시고 있으시네요! 어떤 이유로 이렇게 구현하기로 선택하셨을까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +    private static final String ERROR_NOT_MATCH_LOTTO_NUMBER_SIZE = "로또 번호 개수는 6개로 입력해주세요.";
로또의 갯수가 7개로 늘어났을 때 변경해야하는 곳을 줄이기 위해 상수를 재활용해보는 건 어떨까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +    private static final String ERROR_DUPLICATION_LOTTO_NUMBERS = "로또 번호에 중복이 존재합니다.";
매직넘버를 상수화하는 것은 매우 좋은 것 같아요. 다만 해당 메시지가 매직넘버의 속성을 가지고 있다고 생각하셔서, 상수화 하신 것 같은데 이러한 메시지를 상수화하는 이유가 있으실까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +        Collections.sort(lottoNumbers);
외부에서 주입받은 파라미터를 직접 변경하여서 인스턴수 변수 값에 할당하고 있네요. 이렇게 되는 경우 어떤 문제가 생길 수 있을까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +        List<Integer> lottoNumbers = generateSequentialIntegers();
생성자가 아닌, 정적팩토리패턴을 사용하는 소주캉의 기준에 대해서 공유해주시면 좋을 것 같아요🙂

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +    private List<LottoNumber> convertIntegersToLottoNumbers(List<Integer> integers) {
객체의 생성과정이 전반적으로 복잡하여 `Lotto`전체 메소드의 대부분이 생성과 관련된 기능을 담당하고 있어요. 

팩토리라는 것을 고민해보는 것도 좋을 것 같아요🙂

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +    public int matchWinningNumbers(WinningNumbers winningNumbers) {
소주캉은 프라이빗과 퍼블릭 메소드가 군집을 이루는 것을 좋아하시나요? 메소드를 위치시키는 기준이 어떻게 되는지, 이유도 같이 공유해주시면 좋을 것 같아요.

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +    public boolean matchNumber(Object number) {
파라미터를 오브젝트로 받는 이유가 있을까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoNumber.java
> +        validateRangeLottoNumber(number);
불변객체와 방어적 복사에 대해서 학습해보시면 좋을 것 같아요. 

파라미터의 값을 그대로 사용할 때 발생할 수 있는 문제들도 고민해보아요.

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoNumber.java
> +    Integer getNumber() {
최소한의 접근제어자를 통해서 접근제어자를 관리하시네요👏

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/WinningNumbers.java
> +    public WinningNumbers(List<Integer> winningNumbers) {
조합을 사용하여 구현해주셨네요👏

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Rank.java
> +        if (matchBonus && matchWinningNumbers == SECOND.value) {
보너스볼의 유무는 Enum의 값으로 관리하지 않고 따로 관리하는 이유가 있나요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Rank.java
> +            .filter(rank -> rank.value == matchWinningNumbers && rank != Rank.SECOND)
2등은 위에서 이미 Early Return 해버렸기 때문에 불필요한 조건일 것 같아요.

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Money.java
> +    private static final String ERROR_NOT_DIVIDED_BY_UNIT_PRICE = "거스름돈을 지급하지 않습니다. 금액이 남지 않게 지불해주세요.";
센스있는 안내메시지👏

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Money.java
> +    public Money(Integer money) {
원시자료형이 아닌 래퍼타입을 전체적으로 사용하고 계신데 이유가 있을까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoResult.java
> +    private final Map<Rank, Integer> result = new HashMap<>();
스태틱한 메소드를 사용하여 해당 값을 관리한다면 어떤 이슈가 있을 수 있을까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoResult.java
> +            .map(entry -> entry.getKey().getMoney() * entry.getValue())
`Money`도 로또게임 내에서 역할을 담당하고 있는 객체이기에 메시지를 보내는 건 어떨까요?

추가로 현재 `Money`는 1000원 이라는 단위를 지켜줘야 하는데요. 로또미션에서 금액적 제약을 잘 지키고 있지만, 네이밍으로 인해서 단순히 금액을 포장한 객체라고 생각할 수 있는 여지를 제공하는 것 같아요. 보다 명확한 네이밍을 사용하는 건 어떨까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoGame.java
> +        return new Yield(money.calculatePercentage(lottoResult.getTotalWinningMoney()));
수익률이라는 객체가 존재한다면 해당 객체가 수익률을 구할 수 있도록 변경해보는 건 어떨까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/test/java/lotto/model/LottoResultTest.java
> +    void rankFirstTest() {
각 등수에 대한 평가를 파라미터라이즈드 테스트로 작성해보면 어떨까요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/test/java/lotto/model/LottosTest.java
> +        assertThat(lottos.getLottos().size()).isEqualTo(3);
작은 단위로 객체를 분리하고 객체들끼리의 메시지를 보내게 될 때 항상 `Null`에 대한 고민을 같이 하시면 더 좋을 것 같아요.

어디서 널을 체크할 것인지를 전반적으로 고민해보시면 좋을 것 같아요.

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/test/java/lotto/view/ResultViewTest.java
> +    private final ByteArrayOutputStream outputStreamCaptor = new ByteArrayOutputStream();
뷰에 대한 테스트도 작성해주셨네요👏 테스트 전체가 종료되면 해당 자원도 없어지겠지만, 언제나 자원을 닫아주는 습관을 가지면 더 좋을 것 같아요.

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/test/java/lotto/view/ResultViewTest.java
> +        WinningNumbers winningNumbers = new WinningNumbers(Arrays.asList(1, 2, 3, 4, 5, 6));
패키지레벨을 최소한의로 가져가려는 소주캉의 태도가 참 멋있습니다👏

리플렉션을 통해서도 구현할 수 있고 테스트 패키지에 더미객체를 만들어서 구현할 수도 있을 것 같아요 

뷰를 테스트하는 것과 도메인 내부로직을 테스트하는 것은 일반적으로 분리되어 있기에 너무 깊게 고민하지 않으셔도 될 것 같습니다.

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/view/ResultView.java
> +        System.out.println(lottos.size() + "개를 구매했습니다.");
상수에 대한 특성이 꼭 재활용만 있는 것은 아닌 것 같아요. 현재 소주캉의 의견에 저도 동의하는데 상수로 빼야하는 것에 대한 소주캉의 기준은 어떤게 있나요?

2022-02-25 10:39 UTC, KIMSIYOUNG commented on src/main/java/lotto/view/InputView.java
> +        System.out.println("구입금액을 입력해 주세요.");
5번에서 말씀주신 것에 대해 저도 동의합니다.🙂 1번과 이어서 조금 이야기해보면, 오버프로그래밍에 대해서 저는 개인적으로 현재 미션에서 배워야하고 고민해야하는 것들에 대해 충분히 고민한 이후에 시간이 남는다면 해보면 좋을 것 같아요. 

DTO와 VO의 개념도 이해하고 있다면 좋지만 미션에서 익혀야하는 것들을 익히는게 우선되는게 좋을 것 같습니다. 

여기다 답변을 단김에, 상속이라는 것이 왜 복잡도가 높고 수정이 용이하지 않다고 생각하시나요?

2022-02-28 12:26 UTC, sojukang commented on src/main/java/lotto/model/Lotto.java
> +    private static final String ERROR_NOT_MATCH_LOTTO_NUMBER_SIZE = "로또 번호 개수는 6개로 입력해주세요.";
`LottoNumber`의 상수를 `default`로 열고 재활용해보도록 수정하였습니다. 감사합니다.

2022-02-28 12:31 UTC, sojukang commented on src/main/java/lotto/model/Lotto.java
> +    private static final String ERROR_DUPLICATION_LOTTO_NUMBERS = "로또 번호에 중복이 존재합니다.";
저는 이번 미션의 조건인 `모든 문자열을 포장하라`의 일환으로 `View`를 제외한 계층의 하드코딩을 전부 제거하였습니다. 제가 생각하는 효과로 `ERROR`인 경우와 아닌 경우를 한눈에 파악할 수 있고 수정, 관리가 편하다는 점이 있었습니다. 하지만 단점으로 필드 멤버가 길어지고 메시지가 메서드에서 분리되어 가독성이 떨어지는 단점이 있었습니다. 저는 이러한 장단점에 관해 고려해보라는게 조건의 의도(?)라고 생각했습니다.

2022-02-28 12:33 UTC, sojukang commented on src/main/java/lotto/model/Lotto.java
> +        Collections.sort(lottoNumbers);
내부에서 마음대로 파라미터를 수정해버리니 객체가 어떻게 생성됐는지 파악하기 어렵게 되어 믿고 사용하기 힘든 객체가 되었군요😅. 변경을 허용하지 않는 방향으로 수정해보았습니다.

2022-02-28 12:39 UTC, sojukang commented on src/main/java/lotto/model/Lotto.java
> +        List<Integer> lottoNumbers = generateSequentialIntegers();
처음 의도는 다음과 같았습니다.
1. 생성자로 하기에는 너무 복잡하지 않나?
2. 초기화 되지 않은 객체가 생성되어 돌아다니는 것을 방지 
3. `generate` 등 초기화 내용을 명확하게 파악할 수 있게 하는 게 좋지 않을까? 

그런데 생성자로 바꾸고 다시 고민해보니 현재 어플리케이션과 같이 다양한 초기화 방법을 제공할 필요가 없는 경우 오히려 정적 팩토리 패턴을 사용한 경우가 사용자 입장에서 파악하기 어렵다는 것을 느꼈습니다. 그리고 2 번 항목도 생성자로 이룰 수 있었고, 덤으로 `static`메소드로 참조형 필드에 수정이 일어나기 때문에 동시성 측면에서 신뢰할 수 없겠다는 생각이 들어서 불필요한 `static` 메소드를 전부 제거하고 최대한 `instance`로 처리할 수 있게 수정하였습니다.

2022-02-28 12:41 UTC, sojukang commented on src/main/java/lotto/model/Lotto.java
> +    private List<LottoNumber> convertIntegersToLottoNumbers(List<Integer> integers) {
`카일`이 남겨주신 내용을 보니 `Lotto`에 생성과 관련한 책임이 너무 큰 것으로 보였습니다😅. 그래서 `LottoNumberGenerator` 클래스로 분리하고 `Lottos`에서 사용하도록 수정해보았습니다.

2022-02-28 12:49 UTC, sojukang commented on src/main/java/lotto/model/Lotto.java
> +    public int matchWinningNumbers(WinningNumbers winningNumbers) {
메소드 정렬 순서는 첫 미션에서도 피드백을 받았습니다. 그래서 여러 글을 참조한 결과 다음과 같은 결론을 얻었습니다.
1. 스코프 순서가 아닌 논리적으로 위에서 아래로 읽었을 때 클래스를 파악할 수 있도록 배치한다.
2. 관련 메서드들은 논리적으로 결합되어있는 것이 좋다.
그래서 메서드 이름만으로 내용을 파악할 수 있다면 아래로 내리고 외부에 공개하는 메서드를 우선으로 배치하는 걸 선호하게 되었습니다. 
그런데 이번 페어 프로그래밍을 하며 컨벤션을 정하는 과정에서는 페어의 컨벤션을 팀 컨벤션으로 수용하기로 하였습니다. 현재 코드와 같이 `public` 내에 `private`과 같은 내부 메서드가 있다면 순서상 정렬하여 군집을 이루게 하였습니다.  비교해보니 서로 장단점이 있었고, 충돌할 경우 `팀 컨벤션`이 우선해야한다고 생각하여 로또 미션에서는 계속 따르고자 하였습니다.

2022-02-28 12:50 UTC, sojukang commented on src/main/java/lotto/model/Lotto.java
> +    public boolean matchNumber(Object number) {
`contains`가 `Object`로 받는 걸 보고 결정하였는데, 이번 미션에서는 명확하게 타입을 정해주는 게 옳다고 생각하여 수정하였습니다.

2022-02-28 13:34 UTC, sojukang commented on src/main/java/lotto/model/LottoNumber.java
> +        validateRangeLottoNumber(number);
파라미터의 값을 그대로 사용할 경우 `null`이 넘어오거나 참조 값인 경우 외부에서 수정할 수 있는 등 사용자의 잘못된 사용에 안전하지 못하군요! 해당 클래스도 박싱된 타입으로 `null`값이 넘어올 수 있는 등 문제 여지가 있네요😅. 전체적으로 생성자로 참조 값이 들어온 경우 방어적 복사를 하고, `primitive` 값을 사용하도록 변경하였습니다.

2022-02-28 13:34 UTC, sojukang commented on src/main/java/lotto/model/Rank.java
> +            .filter(rank -> rank.value == matchWinningNumbers && rank != Rank.SECOND)
그렇군요😅! 아래 stream 조건과 통합하게 수정해보았습니다.

2022-02-28 13:37 UTC, sojukang commented on src/main/java/lotto/model/Rank.java
> +        if (matchBonus && matchWinningNumbers == SECOND.value) {
`Enum`이 가지도록 하면 3개의 필드를 갖게 되는데, 그 전과 비교하여 깔끔하지 않게 보였고, 보너스 볼의 유무는 'Lotto'가 책임지는 게 더 낫다고 생각하였습니다.

2022-02-28 13:39 UTC, sojukang commented on src/main/java/lotto/model/Money.java
> +    public Money(Integer money) {
이 부분은 원시 자료형과 래퍼 타입을 신경쓰지 않고 사용하였는데, `이펙티브 자바` 등 자료 참고 결과 원시 자료형을 사용하는 게 낫다는 학습을 하였습니다😅. 감사합니다!

2022-02-28 17:20 UTC, sojukang commented on src/main/java/lotto/model/LottoResult.java
> +    private final Map<Rank, Integer> result = new HashMap<>();
위의 `static method`와 같은 이유에서 최대한 인스턴스 메소드를 사용하였습니다!

2022-02-28 17:23 UTC, sojukang commented on src/main/java/lotto/model/LottoResult.java
> +            .map(entry -> entry.getKey().getMoney() * entry.getValue())
해당 메서드는 현재 `money`가 가진 상태와 관련이 없고 `LottoResult`의 상태인 `Map<Rank, Long>`만 필요한 점, 최종 당첨 금액이라는 `LottoResult`에 어울리는 메소드라는 점에서 `LottoResult`내에 위치시키도록 변경하지 않았습니다. 
`money`의 네이밍엔 저도 공감하여 `LottoMoney`로 수정해보았습니다.

2022-02-28 17:25 UTC, sojukang commented on src/main/java/lotto/model/LottoGame.java
> +        return new Yield(money.calculatePercentage(lottoResult.getTotalWinningMoney()));
`Yield` 객체에서 생성자와 함께 초기화하도록 수정해보았습니다!

2022-02-28 17:26 UTC, sojukang commented on src/test/java/lotto/model/LottoResultTest.java
> +    void rankFirstTest() {
다소 `ParameterizeTest`를 적용하기 힘들 것이라 생각했는데, 방법은 언제나 있군요😮!

2022-02-28 17:30 UTC, sojukang commented on src/test/java/lotto/model/LottosTest.java
> +        assertThat(lottos.getLottos().size()).isEqualTo(3);
`Collection`을 필드로 갖는 객체들은 `null`에 관한 고민과 `방어적 복사`에 관한 고민을 항상 해야 하겠다는 깨닳음을 얻었습니다. 감사합니다👍. `primitive value`을 주고 받을 때는 이런 문제가 없다고 생각하여 따로 도메인에 관한 검증 만을 두었는데, `카일`은 어떻게 생각하시는지 궁금합니다!

2022-02-28 17:31 UTC, sojukang commented on src/test/java/lotto/view/ResultViewTest.java
> +    private final ByteArrayOutputStream outputStreamCaptor = new ByteArrayOutputStream();
`Stream`을 닫아주는 걸 고려하지 못했네요😅! 수정하였습니다!

2022-02-28 17:33 UTC, sojukang commented on src/test/java/lotto/view/ResultViewTest.java
> +        WinningNumbers winningNumbers = new WinningNumbers(Arrays.asList(1, 2, 3, 4, 5, 6));
감사합니다! 뷰를 테스트하는 것이 일반적으로 분리되어 있다는 말씀을 보고 `ViewTest`에서만 쓰이기 위해 개방된 `public 생성자`를 `package-private`으로 바꾸고 리플렉션을 사용해보았습니다.

2022-02-28 17:51 UTC, sojukang commented on src/main/java/lotto/view/ResultView.java
> +        System.out.println(lottos.size() + "개를 구매했습니다.");
저는 다음 기준으로 생각해보았습니다.
1. 상수가 반복해서 쓰일 경우
2. 상수화 하는 게 의미를 명확하게 전달할 수 있는 경우
3. 상수가 해당 객체의 핵심 로직과 관련되어 있을 경우
4. 상수로 모으는 것이 관리하기 편한 경우
이번 미션에는 필요한 것보다 더 상수화해보려고 시도하였는데, 일반적인 문자열 메시지까지는 필요 없다고 생각 들었지만 `ERROR` 메시지는 상수화한 것이 더 파악하기 편하다고 느꼈습니다.

2022-02-28 17:56 UTC, sojukang commented on src/main/java/lotto/view/InputView.java
> +        System.out.println("구입금액을 입력해 주세요.");
현재 어플리케이션과 같이 간단한 경우, 파악하기 쉽지만 프로그램이 복잡해진다면 상속의 상위 - 하위 객체의 변경이 파악하기 힘들 것이라 생각하였습니다. 하위 객체는 상위 객체의 메서드를 오버라이딩하여 의도치 않은 행동을 하게 할 수 있고, 상위 객체의 수정으로 하위 객체까지 수정해야하는 깊은 연관이 발생한다고 생각했습니다. 이런 문제가 객체 사이의 독립성을 해칠 수 있다고 보았습니다.

2022-02-28 18:04 UTC, sojukang commented
안녕하세요 `카일`👋👋! 정성들여 리뷰해주셔서 정말 감사드립니다🙏!
이번 리팩토링에서는 기본적으로 `카일`이 남겨주신 피드백을 수용하면서 다음 내용을 중점으로 두었습니다. 
1. 참조 값을 전달하거나 받는 경우 `방어적 복사` 고려
2. `static method`를 가능한 `instance method`로 수정
3. `parameter`의 `Null`  값 고려
  
이번에도 잘 부탁 드립니다!!

2022-03-01 09:45 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +    private static final String ERROR_DUPLICATION_LOTTO_NUMBERS = "로또 번호에 중복이 존재합니다.";
좋은 관점인 것 같습니다. 저 개인적으로는 해당 값을 포장했을 때 장점보다 단점 (가독성과 필드 멤버가 길어짐에 따른 객체 역할 가독성 저하)가 크다고 생각하는데, 소주캉은 배운 내용을 극단으로 적용해보면서, 장단점을 비교하고 소주캉에게 적절한 방법을 선택하시면 될 것 같아요🙂

2022-03-01 09:47 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +    public int matchWinningNumbers(WinningNumbers winningNumbers) {
크 너무 좋은 관점이네요🙂 장단점에 대해서 인지하고 계시다면 본인이 익숙한 그리고 함께하는 사람과의 룰을 맞춰 나가는게 가장 좋은 것 같아요. 👏

2022-03-01 09:48 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +    public boolean matchNumber(Object number) {
많은 부분을 공부하고 고민하시는게 느껴지네요🙂 범용적인 형태의 API를 만들어야하는 자바 API와 현재 해당 객체의 역할은 분명 다르다고 생각해요🙂

좋은 관점이라고 생각하고, 현재는 타입을 명시해주는게 조금 더 적절해보이네요!

2022-03-01 09:50 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Rank.java
> +        if (matchBonus && matchWinningNumbers == SECOND.value) {
`필드를 3개를 가졌을 때가 가독성이 좋지 않아보인다`라는 측면으로 접근해서 역할을 분리한다면, 랭크를 관리하는 시스템은 현재 Rank 와 Lotto로 분산되게 되는 것 같아요. 

해당 단점보다 전자의 단점이 크게 느껴지신거죠?

2022-03-01 09:51 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Money.java
> +    public Money(Integer money) {
null이 허용된다면, 혹은 null이 의미를 갖는다면(예를들어 엔티티라면 id가 Integer에 null인 경우 아직 저장되지 않은 객체라는 의미를 가지니까요) 래퍼타입을 쓰는 것도 좋은 방법인 것 같아요. 

다만 현재구조에서 조금 더 적절한 것은 원시타입이라고 생각이 드네요🙂

2022-03-01 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoResult.java
> +            .map(entry -> entry.getKey().getMoney() * entry.getValue())
좋은 관점인 것 같습니다. `LottoMoney`일 때와 `Money`일 때는 확실히 다른 역할을 수행하는 객체가 되니까요!

2022-03-01 09:54 UTC, KIMSIYOUNG commented on src/test/java/lotto/model/LottosTest.java
> +        assertThat(lottos.getLottos().size()).isEqualTo(3);
원시타입에서는 null이라는 형태가 존재하지 않지만, null을 검증하는 것은 결국 의도하지 않은 동작을 방지한다라는 맥락인 것 같아요. 

그렇기때문에 int와 같은 원시타입이라도 0이라는 디폴트 값에 대한 검증이 필요한지, 어디서 하는 것이 좋은지에 대한 것은 항상 고려할 요인이라고 생각합니다🙂

2022-03-01 09:55 UTC, KIMSIYOUNG commented on src/test/java/lotto/view/ResultViewTest.java
> +    private final ByteArrayOutputStream outputStreamCaptor = new ByteArrayOutputStream();
처음 보는 테스트 방법이고 이 부분도 테스트를 위해서 학습하시는 것이 대단하신 것 같습니다👏

2022-03-01 09:57 UTC, KIMSIYOUNG commented on src/test/java/lotto/view/ResultViewTest.java
> +        WinningNumbers winningNumbers = new WinningNumbers(Arrays.asList(1, 2, 3, 4, 5, 6));
학습과 실행이 빠르시네요👏 
테스트를 위한 리플렉션이나 생성자의 접근제어자 수정을 사용할 때는 항상 아래의 고민들을 같이 해보신 후 방법이 없는 경우에만 사용하는 습관을 가지면 좋을 것 같아요.

- 테스트 할 수 있는 다른 방법은 어떤 것이 있을까?
- 꼭 테스트해야하는 것인가?

2022-03-01 09:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/view/ResultView.java
> +        System.out.println(lottos.size() + "개를 구매했습니다.");
좋은 기준들을 가지고 계시네요🙂

상수를 사용하는 의미에 대해서 충분히 잘 인지하고 계시기 때문에, 마지막 문장처럼 소주캉이 느끼는 가독성이 이젠 가장 중요한 지표가 될 것 같아요.🙂

2022-03-01 10:01 UTC, KIMSIYOUNG commented on src/main/java/lotto/view/InputView.java
> +        System.out.println("구입금액을 입력해 주세요.");
상속이라는 것이 중복을 줄여준다는 장점이 있지만, 내부적으로는 객체간의 결합도를 매우 증가시키는 요인이라고 동일하게 생각해요🙂

WinningNumbers를 따로 두는 것은 취향차이 일 수 있지만, 저는 좋다고 생각했습니다🙂 같은 로또라도 분명 다른 의미를 지니고 있기에 분리하여 관리하는 것도 이점이 있다고 생각했고, 반대로 같은 로또이기에 하나로 간주할 수도 있겠죠🙂

2022-03-01 10:25 UTC, KIMSIYOUNG approved these changes
안녕하세요 소주캉!
리뷰 잘 반영해주셨네요. 객체간의 역할분리에 있어서 많은 고민을 하신 것 같아요. 
조금 더 고민해보면 좋을 것들에 대해서 코멘트 남겼으니 2단계 진행하면서 같이 고민해주세요🙂
대댓글로 질문주신 내용들 답변 달아두었는데, 궁금하신 내용이 있다면 편하게 디엠 / 댓글 주세요! 고생하셨습니다. 2단계 때 뵈어요.

2022-03-01 10:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoGame.java
> +    public static Lottos buyLottos(LottoMoney lottoMoney) {
`LottoGame`은 인스턴스화 되어 사용되는 형태인데, 해당 메소드는 스태틱하게 제공하는 이유가 있을까요?

2022-03-01 10:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoGame.java
> +        ArrayList<Integer> winningNumbers = new ArrayList<>(integers);
방어적 복사를 사용해주셨네요👏 

여기서 List<Integer>이 아닌 ArrayList 타입으로 선언하여 사용하시는 이유가 있으실까요?

2022-03-01 10:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoGame.java
> +    private final Lotto winningNumbers;
LottoGame의 인스턴스변수에서 `Lottos`는 제외된 기준이 무엇인지 공유해주시면 좋을 것 같아요.

2022-03-01 10:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lottos.java
> +    public Lottos(LottoNumberGenerator lottoNumberGenerator, int count) {
생성자가 2개이상인 경우, 일반적으로 부생성자가 주 생성자를 부르도록 구현하여 필수적인 검증로직들의 중복을 방지하는 게 좋습니다🙂

현재 구조에서는 랜덤으로 생성된 값이 비어있을리 없겠지만 습관을 좋게 만들면 좋을 것 같아요.

2022-03-01 10:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lottos.java
> +    public List<Lotto> getLottos() {
현재 Lottos 는 로또를 생성하는 역할만을 담당하고 있는데요. 로또들을 모두 가지고 있기에 값을 반환하지 않고, 각 로또들에게 메시지를 보내는 역할을 조금 더 이관받을 수 있지 않을까요?

2022-03-01 10:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lottos.java
> +    public Lottos(List<Lotto> lottos) {
해당 생성자는 테스트에서만 사용되네요🙂 

랜덤으로 생성되는 `Generator`를 인터페이스화 한다면 해당 생성자는 필요없어지지 않을까요?

2022-03-01 10:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoResult.java
> +            .collect(groupingBy(rank -> rank, () -> new EnumMap<>(Rank.class), counting())));
() -> new EnumMap<>(Rank.class)는 불필요할 것 같아요🙂

2022-03-01 10:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoGame.java
> +        return new LottoResult(lottos, winningNumbers, bonusNumber);
로또의 결과인 랭크별 갯수와, 수익률은 모두 결과라는 점에서 동일하기 때문에 `LottoResult`에서 수익률까지 같이 관리해준다면, 파라미터로 전달해주고 다시 전달 받을 필요가 없을 것 같아요.

2022-03-01 10:25 UTC, merged