[2단계 - 로또(수동)] 후니(최재훈) 미션 제출합니다.
woowacourse/java-lotto pull request #419
Opened 2022-02-28 05:33 UTC by jayjaehunchoi

안녕하세요 앨런 !

1단계 머지하면서 남겨주셨던 리뷰 반영하면서 Step2도 동시에 진행했습니다!!

이번 2단계에서는 수동으로 변경되면서 발생하는 코드의 변화를 ```LottoGenerator```라는 객체를 만들어 반영할 수 있었습니다.
이전에 리뷰를 잘 해주신 덕에 어렵지 않게 수정할 수 있었으나 코드의 유지보수 측면에서 리뷰 주신다면 더욱 감사하겠습니다!!

이번에도 잘 부탁드립니다.

감사합니다.
후니 드림.

2022-02-28 05:39 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
정적 팩토리 메서드의 인자로 money와 수동 개수를 넣었는데 , 이부분에서 자동 개수를 판별하여 생성자를 실행시키는게 괜찮을까요?

2022-02-28 05:39 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoNumber.java
> +        checkNumberRightRange(number);
생성자에 검증을 추가했습니다!

2022-02-28 05:39 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/Rank.java
> +    NOT_THING(0, 0),
hitCount 를 로직상 의미있게 활용하기 위해 함수형 인터페이스를 제거하고 ```calculateCurrentRank``` 로직을 변경했습니다!

2022-02-28 05:39 UTC, jayjaehunchoi commented on src/main/java/lotto/view/InputView.java
> +    }
input view 에서 개수를 인자로 받아 반복문을 실행시켜주는 것 정도는 view의 역할에 적합하다고 생각했는데 앨런의 생각은 어떠세요?

2022-03-02 13:37 UTC, hongbin-dev requested changes
안녕하세요 후니! 리뷰어 앨런입니다.
미션 로또 2단계미션 잘 구현해주셨군요 💯
몇 가지 피드백 남겼습니다. 확인해주세요

2022-03-02 13:37 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
로또생성기의 책임을 어디까지 가져갈지에 따라 다를 것 같아요.
지금처럼 금액과 수동갯수를 입력받았을 때, 나머지 자동티켓을 구매해주는건 좋은데요.

`of`라는 메서드 네이밍에서 남은금액은 자동으로 구매한다' 이런 뉘앙스가 들어가면 좋겠네요.

2022-03-02 13:37 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
금액이 부족한건가요? 코드흐름상 갯수가 부족해보이네요~

2022-03-02 13:37 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
예외를 던질 때 상세하게 피드백해주세요. 어떤 값 때문에 예외가 발생했는지 추가되면 디버깅하기 좋을 것 같아요.

2022-03-02 13:37 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
제가 이해하기론 수동로또를 구매하고, 자동로또를 추가하는구조로 보이는데요.

List에서 add하는 형태라 리스트가 가변이네요. 이 부분을 불변형태로 바꿀 순 없을까요?
이 형태라서 그런지, manualLottos의 네이밍이 애매한 것 같습니다. 자동로또도 품고 있어요

2022-03-02 13:37 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoGenerator.java
> +        return manualLottos;
스트림 내에서 스트림을 사용하고 있어서, 가독성이 떨어지는 것 같아요.
메서드 분리하시면 좋을 것 같습니다~

2022-03-02 13:37 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
현재 싱글톤이 시작~종료까지 메모리에 상주하고있는데요.
싱글톤 객체를 사용하는시점에 초기화할 수 있도록 변경해보는 것도 좋을 것 같아요 🙂

https://gmlwjd9405.github.io/2018/07/06/singleton-pattern.html

2022-03-02 13:37 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoResult.java
> +        return new LottoResult(rankResults);
put대신 replace를 사용하신 이유가 있을까요?
또 매직넘버를 상수로 포장하면 좋을 것 같아요 🙂

2022-03-02 13:37 UTC, hongbin-dev commented on src/main/java/lotto/view/InputView.java
> +    }
뷰에서 적절한 처리는 좋아보이는데요! 
이게 stream으로 입력받다보면 디버깅이 어려울 수도 있을 것 같아요.

2022-03-03 02:00 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoResult.java
> +        return new LottoResult(rankResults);
사실 존재하지 않는 값이 들어올 일은 없겠지만 replace를 사용함으로써 initialize한 key값 외 예외적인 값이 들어올 상황을 방지하고자 했습니다!!

2022-03-03 02:05 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
Stream의 concat 메서드를 사용하여 수정하였습니다.

합쳐서 불변형태의 List하나를 만들어주기 때문에 문제를 해결할 수 있을 것 같습니다!

2022-03-03 02:06 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoGenerator.java
> +        return manualLottos;
메서드 분리하였습니다!

2022-03-03 02:08 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
좋은 팁 감사합니다! 사용되는 시점에 초기화 되도록 수정하였습니다!

다만 링크에서는 멀티 스레드 상황에서의 임계 구역 분리에 대해 고려하고 있는데, 현재 저희 프로그램에서도 이를 고려해야할까요?

2022-03-04 12:30 UTC, hongbin-dev requested changes
안녕하세요 후니.
빠르게 피드백 적용해주셨군요!
몇 가지 의견 더 남겼어요. 확인해주세요 🙂

2022-03-04 12:30 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
고려하면 좋을 것 같습니다! 
해당 포스팅에 `정적 메서드로만 이루어진 정적 클래스를 사용하면 싱글턴과 동일한 효과를 얻을 수 있다.` 이 부분을 참고하시면 두 가지 다 챙길 수 있을 것 같아요.

이런 패턴을 Initialization-on-demand holder idiom 라고하나보군요! [https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom](https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom)

2022-03-04 12:30 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
```suggestion
    private void checkManualCountPositiveNumber(final int manualCount) {
        if (manualCount < MIN_LOTTO_COUNT) {
            throw new IllegalArgumentException("[ERROR] 구매할 수동 로또 수는 0이상을 입력해주세요.");
        }
    }

    private void checkInputMoneyEnough(final int autoCount) {
        if (autoCount < MIN_LOTTO_COUNT) {
            throw new IllegalArgumentException("[ERROR] 자동 구매 개수는 0개 이상이어야 합니다.");
        }
    }
```

2022-03-04 12:30 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoResult.java
> +        return new LottoResult(rankResults);
Map을 초기화시켜놓고, 거기에 하나씩 put하는 형태인데요. 집계함수(groupingBy)도 고려해볼 수 있을 것 같아요. 🙂

[https://www.baeldung.com/java-groupingby-collector](https://www.baeldung.com/java-groupingby-collector)

2022-03-04 12:30 UTC, hongbin-dev commented on src/main/java/lotto/domain/Rank.java
> +                .filter(rank -> !rank.equals(SECOND) || hasBonusNumber)
이 부분은 메서드로 분리하면 더 읽기 좋을 것 같아요

2022-03-04 12:33 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoResult.java
> +        return new LottoResult(rankResults);
`replace를 사용함으로써 initialize한 key값 외 예외적인 값이 들어올 상황을 방지`
개인적으로 방어적인 코드보다, 빠른 피드백을 받을 수 있도록 예외를 던지는게 더 좋다고 생각하고있어요.

근본적으로 `Rank.initResultMap();`로 씨드를 만든 Map으로 put해주는 구조가 조금 특이하긴 하네요..🤔

2022-03-04 14:28 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoResult.java
> +        return new LottoResult(rankResults);
initial하는 로직을 제거하고 전반적으로 리팩토링 했습니다 . [24e46e1](https://github.com/woowacourse/java-lotto/pull/419/commits/24e46e13a7e379df8c16edc16762c69e6300a80a)

다만 여기서 걸리는 부분이 outputView에서 출력을 위해 Rank에 reverseList라는 순서를 역으로 가져와주는 메서드를 만들게 됐습니다. 차라리 Enum에서 각 등수를 거꾸로 적을지, 이렇게 메서드로 반환할지가 고민됩니다. 지금처럼 역순 리스트로 반환해주는 형태가 문제가 될 수 있을까요?

 다만 initial을 위한 메서드들이 모두 간소화되고 삭제돼서 코드는 훨씬 더 깔끔해진 것 같습니다. 또 아래에서 조언해주신 내용대로
 >Map을 초기화시켜놓고, 거기에 하나씩 put하는 형태인데요. 집계함수(groupingBy)도 고려해볼 수 있을 것 같아요. 🙂

groupingBy를 이용하여 수정하였더니 훨씬 더 명확한 코드가 된 듯 합니다!

2022-03-04 14:29 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/Rank.java
> +                .filter(rank -> !rank.equals(SECOND) || hasBonusNumber)
메서드 분리하였습니다!

2022-03-04 14:30 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
기존의 불필요한 getter를 삭제하고 toString으로 변환했습니다. 더 안정성이 높은 코드가 된 것 같아요!!

2022-03-04 14:31 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
네 조언주신대로 수정하였습니다. 다만 캐싱된 형태를 유지하면서 LazyHolder를 사용하는 것이 감이 잘 오지않아 전체적으로 static 메서드를 사용하는 형태로 변경하였고 synchronized를 붙여주었습니다.

그런데 toString, equals, hashcode는 static으로 변경하지 못하였는데, 이런 경우에도 싱글턴과 동일한 효과를 얻을 수 있을까요?

2022-03-06 05:49 UTC, hongbin-dev requested changes
안녕하세요 후니!
피드백 반영해주신거 확인했습니다 💯
몇 가지 의견 추가했으니 확인해주세요!

2022-03-06 05:49 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoResult.java
> +                * Lotto.LOTTO_PURCHASE_MONEY;
```suggestion
        return rankResults.entrySet().stream()
        .mapToInt(Entry::getValue)
        .sum() * Lotto.LOTTO_PURCHASE_MONEY;
```
IntStream 스트림을 사용하면 sum() 메서드 활용이 가능해서, 더 읽기좋을 것 같아요.
그리고 메서드체이닝(.)을 행 단위로 나눠주시면 더 읽기 좋습니다 👍

2022-03-06 05:49 UTC, hongbin-dev commented on src/main/java/lotto/domain/Lottos.java
> -
결과를 만들어주는 책임을 LottoResult으로 옮기셨군요 👍

2022-03-06 05:49 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoResult.java
> +        return new LottoResult(rankResult);
💯

2022-03-06 05:49 UTC, hongbin-dev commented on src/main/java/lotto/domain/Rank.java
> +        return !rank.equals(SECOND) || hasBonusNumber;
isSecond 메서드 시그니처와 `!rank.equals(SECOND)` 이 부분 때문에 조금 헷갈립니다 🥲
필터에 필요한 로직인지 고민해보시는 것도 좋을 것 같아요.

또 static을 제거할 수 있어보이는데요. 그럼 rank에게 메시지를 보내는 형태로 풀어낼 수 있겠네요

2022-03-06 05:51 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
일단 싱글톤은 **인스턴스 생성**의 의미가 있는 것 같아요.
- 생글턴 인스턴스의 정의는 런타임에 개발자가 강제로 인스턴스를 1개만 생성하도록 만든 패턴인데요. 동일한 인스턴스를 재활용하는거에 의미가 있는 것 같아요.
- 클래스의 메서드는 여러 인스턴스를 생성해도, 추가로 메모리를 잡아먹지않기 때문에 걱정안하셔도 될 것 같습니다.

이 부분은 싱글턴 패턴과 자바메모리구조를 한번 알아보시는 것도 좋을 것 같아요 🙂

2022-03-06 05:51 UTC, hongbin-dev commented on src/main/java/lotto/domain/LottoResult.java
> +        return new LottoResult(rankResults);
toReverseList 는 뷰에 의존적인 코드라고 생각해요. 거꾸로 순서가 필요한 건 뷰의 책임이라고 생각하는데, 뒤집어주는 건 뷰에서 처리하는게 좋을 것 같아요.

2022-03-06 06:07 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/Rank.java
> +        return !rank.equals(SECOND) || hasBonusNumber;
필터링 할 때는 2등을 찾기위해 필요한 로직입니다! 다만 메서드명을 조금더 명확하게 필터링 하는 내용으로 변경했고 메시지를 보내는 형태로 풀었습니다.

2022-03-06 06:08 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoResult.java
> +                * Lotto.LOTTO_PURCHASE_MONEY;
해당 부분 반영했습니다. 확실히 IntStream을 이용하는게 가독성이 좋네요

2022-03-06 06:08 UTC, jayjaehunchoi commented on src/main/java/lotto/domain/LottoResult.java
> +        return new LottoResult(rankResults);
네 확실히 뷰에 의존적인 부분이라 뷰로 책임 변경했습니다!

2022-03-06 06:35 UTC, hongbin-dev approved these changes
안녕하세요 후니! 
피드백 반영해주신 것 확인했고, 이제 머지해도 좋겠네요.
로또 미션하느라 고생많으셨어요 👍

2022-03-06 06:35 UTC, hongbin-dev commented on src/main/java/lotto/view/OutputView.java
> +                .map(LottoNumber::toString)
toString보단 getter를 사용하는게 나을 것 같아요.

비슷한 고민을 하신분이 포스팅한 글이 있어서 남겨봐요
https://velog.io/@ozragwort/toString-%EB%B9%84%EC%A6%88%EB%8B%88%EC%8A%A4-%EB%A1%9C%EC%A7%81%EA%B3%BC-UI-%EB%A1%9C%EC%A7%81%EC%9D%98-%EB%B6%84%EB%A6%AC

2022-03-06 06:36 UTC, merged