[로또] 코니 미션 제출합니다.
woowacourse/java-lotto pull request #42
Opened 2019-06-05 05:24 UTC by choihz

많이 지적해 주세요 😂 감사합니다~

2019-06-06 05:26 UTC, gracefulBrown requested changes
안녕하세요. 리뷰어 브라운 입니다.
객체 설계를 깔끔하게 잘 하신것 같아요 💯 
몇가지 참고가 될만한 코멘트를 남겼으니 확인해주세요
궁금한 점 있으시면 언제나 DM 주세요 ^^

2019-06-06 05:26 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoMachine.java
> +public class LottoMachine {
LottoMachine이라는 개념 좋은거 같아요 👍

2019-06-06 05:26 UTC, gracefulBrown commented on src/main/java/lotto/domain/Money.java
> +    private static final int MAX_MONEY = 100_000;
언더바를 이용한 숫자 상수 표현 👍

2019-06-06 05:26 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoResult.java
> +        stringBuilder.append(String.format("총 수익률은 %.1f%%입니다.", getRateOfReturn() * 100));
현재 콘솔에서 사용하는 OutputView에 종속된 LottoResult인가요?
만약 공용으로 사용 할 객체라면 출력 포맷을 도메인에서 정의하는 것 대신 뷰에서 처리하도록 해보면 어떨까요?

2019-06-06 05:26 UTC, gracefulBrown commented on src/main/java/lotto/ConsoleUIApplication.java
> +            return LottoMachine.generateTickets(money, manualLotto);
좋은 방법인 것 같습니다 👍 
혹시 로또를 생성하는 것은 **로또 머신**에서만 수행하도록 해볼 수 있을까요?
만약 그렇게 된다면 새로운 로또를 생성하는 룰이 생겼을 때 로또머신에서만 변화가 일어날 수 있도록 될 것 같아요.

ManualLottoGenerator와 RandomLottoGenerator를 잘 묶어보면 팩토리 메서드 패턴과 비슷한 형태가 가능할 것 같은데
참고만한번 해보세요 :)

2019-06-11 04:32 UTC, choihz commented
피드백 감사합니다!
피드백에 따라 LottoResult의 toString()을 OutputView로 빼고, 컨트롤러에서 분기하는 부분을 LottoMachine 안으로 넣었습니다. ManualLottoGenerator와 RandomLottoGenerator는 처음에 LottoGenerator라는 추상 클래스를 만들어 상속받게 했었는데, RandomLottoGenerator에서  Collections.shuffle을 쓰다보니 필드를 공유할 수 없어 이렇게 만들게 되었습니다. 😥 혹시 더 좋은 방법이 있다면 알려주시고, 이외에도 많이 지적해 주세요!

2019-06-11 06:44 UTC, gracefulBrown approved these changes
피드백 반영하시느라 수고하셨습니다 👍 
몇가지 피드백 추가로 남겨놓았으니
웹 미션하시면서 같이 고민하면 좋을 것 같아요 :)

2019-06-11 06:44 UTC, gracefulBrown commented on src/main/java/lotto/view/InputView.java
> +    private static void validateNumberOfManualLotto(int numberOfManualLotto, Money money) {
입력받은 금액이라는 원시값을 랩핑한 클래스가 있다면 해당 메서드는 그 곳에 들어가 좋을 것 같네요 :)

2019-06-11 06:44 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoMachine.java
> +            List<Lotto> manualLotto = InputView.getManualLotto(numberOfManualLotto);
LottoMachine이 도메인의 개념 맞나요?
그렇다면 Input을 도메인에서 하는 것 보단 Controller에서 넘겨 받아서 생성하는게 더 좋겠네요 :)

2019-06-11 06:44 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoMachine.java
> +    static LottoTickets generateTickets(Money money, List<Lotto> manualLotto) {
위의 메서드와 중복인 부분이 조금 있는 것 같아요ㅎㅎ
위의 피드백(Input분리)을 수행하시면서 가능하면 중복도 줄여가는 방법도 고민해보면 좋을 것 같아요 :)

2019-06-11 06:45 UTC, merged