[2단계 - 로또(수동)] 알파(배철환) 미션 제출합니다.
woowacourse/java-lotto pull request #420
Opened 2022-02-28 07:14 UTC by bcc0830

안녕하세요 루피!! 알파입니다

저번 1단계 미션에서 주신 피드백이 2단계 구현시 정말 많이 도움이 되었습니다.
덕분에 1단계 구조를 변경하지 않고 약간의 메소드만 추가하여 2단계 미션을 완료하였습니다.
정말 감사합니다!!

이번에도 루피의 피가 되고 살이 되는 피드백을 기다리고 있겠습니다. 감사합니다!!

2022-02-28 12:01 UTC, TheDevLuffy requested changes
알파, 안녕하세요~

2단계 미션 리뷰 요청을 빠르게 주셨네요.
2단계 미션을 진행하시면서 기존 코드에서 구현 했던 내용을 변경하면서 수동으로 로또 번호를 받도록 구현해주셨는데요.

남겨드린 피드백에 대해 고민해보시면서, 기존 코드를 확장하기 쉬운 구조로 변경하고, 기존 코드에서 구현 했던 내용을 최대한 변경하지 않는 방향으로 수동 로또를 추가한다면 어떻게 해야할지 한번 고민해보시면 좋을 것 같아요.

충분히 고민하신 후 다시 리뷰 요청 주셔요 ㅎㅎ

2022-02-28 12:01 UTC, workromancer commented on src/main/java/controller/LottoGameController.java
>  			processResults(lottoTickets, answerLotto);
결과가 좀 이상한 것 같아요~
확인 한번 부탁드려요 ㅎㅎ

```
구입금액을 입력해 주세요.
5000

수동으로 구매할 로또 수를 입력해 주세요.
2

수동으로 구매할 번호를 구분자(, ) 기준으로 입력해 주세요.
1, 2, 3, 4, 5, 6
1, 2, 3, 4, 5, 6
수동으로 2장, 자동으로 3개를 구매했습니다.
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[14, 27, 6, 26, 11, 24]
[32, 33, 17, 28, 8, 2]
[15, 23, 28, 35, 36, 13]

지난 주 당첨 번호를 구분자(, ) 기준으로 입력해 주세요.
1, 2, 3, 4, 5, 6
보너스 볼을 입력해 주세요.
7

당첨 통계
---------
3개 일치 (5000원) - 0개
4개 일치 (50000원) - 0개
5개 일치 (1500000원) - 0개
5개 일치, 보너스 볼 일치(30000000원) - 0개
6개 일치 (2000000000원) - 2개
총 수익률은 -58993.4592입니다.(기준이 1이기 때문에 결과적으로 손실이라는 의미임)
```

2022-02-28 12:01 UTC, workromancer commented on src/main/java/domain/Lotto.java
> +	public Lotto(List<LottoNumber> lottoNumbers) {
👍

2022-02-28 12:01 UTC, workromancer commented on src/main/java/domain/LottoTickets.java
> +	public LottoTickets(int price, int manualLottoSize) {
`LottoTickets` 가 담당하는 역할이 점점 많아지는 것 같은데요.

담당하는 역할을 나눠볼 수 있지 않을까요 ?

2022-02-28 12:01 UTC, workromancer commented on src/main/java/controller/LottoGameController.java
> +		for (int index = 0; index < lottoTickets.getManualLottoSize(); index++) {
getter 를 사용하지 않고 구현할 수는 없을까요 ?

2022-02-28 12:01 UTC, workromancer commented on src/main/java/controller/LottoGameController.java
> +		for (int index = 0; index < lottoTickets.getLottoTicketsCapacity() - lottoTickets.getManualLottoSize();
lottoTickets 에 메시지를 보내도록 구현할 수 있지 않을까요 ?

2022-02-28 12:22 UTC, bcc0830 commented on src/main/java/controller/LottoGameController.java
>  			processResults(lottoTickets, answerLotto);
수익률 계산 중 오버플로우가 발생하여 해당 결과가 나왔습니다. int가 아닌 long으로 변경했습니다!

2022-03-02 14:31 UTC, bcc0830 commented on src/main/java/domain/LottoTickets.java
> +	public LottoTickets(int price, int manualLottoSize) {
`LottoGenerator` 라는 인터페이스를 생성하고 자동 로또 번호 생성기인 `AutoGenerator`와 수동 로또 생성기인 `ManualGenerator`가 공통 추상 클래스인 `generateLottoNumbers`를 오버라이딩하도록 하였습니다!

2022-03-02 14:32 UTC, bcc0830 commented on src/main/java/controller/LottoGameController.java
> +		for (int index = 0; index < lottoTickets.getManualLottoSize(); index++) {
파라미터에 수동 로또 입력 갯수를 넣어주면 getter없이 구현가능하다고 생각합니다!

2022-03-02 14:33 UTC, bcc0830 commented on src/main/java/controller/LottoGameController.java
> +		for (int index = 0; index < lottoTickets.getLottoTicketsCapacity() - lottoTickets.getManualLottoSize();
`LottoTickets`의 전체 로또 티켓 갯수인 capacity에서 현재 로또 티켓 갯수를 뺀 수를 리턴하는 메소드를 만들어 수동 입력이 끝난 후에 메세지를 보내서 자동 로또 갯수를 알 수 있도록 변경했습니다!

2022-03-03 08:48 UTC, TheDevLuffy approved these changes
알파~ 안녕하세요.

피드백 드린 내용 고민하시고 반영 하시느라 고생하셨습니다 !

이번 미션에서 기존 코드에 새로운 요구사항을 추가하는 연습을 하셨을텐데요.
로또 미션에서 고민하신 내용들 잘 기억하셔서 다음 미션에서 새로운 요구사항을 추가하실 때 도움이 되시길 기원합니다 ㅎㅎ

전반적으로 잘 구현해주셨는데요. 몇 가지 코멘트 남겨두었으니 한번 참고 부탁드려요.

미션 진행하시느라 고생 많으셨습니다 !

추가로 궁금하신 점은 DM, 게더 대화 주셔도 좋습니다 !

2022-03-03 08:48 UTC, TheDevLuffy commented on src/main/java/controller/LottoGameController.java
> +		return new AnswerLotto(manualGenerator.generateLottoNumbers(), bonusNumber);
AnswerLotto 는 자동 발행 혹은 수동 발행과 다를 것 같아요.
`ManualGenerator` 를 사용하면 자칫 혼동을 줄수도 있을 것 같아요 ㅎㅎ

2022-03-03 08:48 UTC, TheDevLuffy commented on src/main/java/domain/LottoGenerator.java
> +public interface LottoGenerator {
잘 구현해주셨어요 👍

2022-03-03 08:48 UTC, TheDevLuffy commented on src/main/java/domain/ManualGenerator.java
> +		validateDuplicate(this.candidates);
객체가 생성되는 시점에 검증하는 것이 예외가 발생하는 시점을 더 명확하게 나타낼 수 있겠지요 ?

2022-03-03 08:48 UTC, TheDevLuffy commented on src/main/java/domain/LottoTickets.java
> +		return this.lottoCounter.getTotalSize() - this.lottoCounter.getManualSize();
lottoCounter 에 메시지를 보내서 구현해도 괜찮지 않았을까요 ?!

2022-03-03 08:48 UTC, TheDevLuffy commented on src/main/java/domain/LottoTickets.java
>  	}
`LottoTickets` 이 `LottoCounter` 를 가지고 있고, LottoCounter 를 getter 로 꺼내서 사용하지 않고, `LottoTickets` 의 메서드를 통해 `LottoCounter` 에 특정 로직을 위임하면 큰 장점을 얻을 수 있는데요. 어떤 장점이 있을지 고민해보시면 좋을 것 같아요.

잘 구현해주셨어요 👍

2022-03-03 08:48 UTC, merged

2022-03-04 12:27 UTC, bcc0830 commented on src/main/java/controller/LottoGameController.java
> +		return new AnswerLotto(manualGenerator.generateLottoNumbers(), bonusNumber);
그렇다면 `LottoGenerator` 를 implement하는 `AnswerGenerator` 를 만드는 것도 생각해볼 수 있겠네요

2022-03-04 12:29 UTC, bcc0830 commented on src/main/java/domain/LottoTickets.java
> +		return this.lottoCounter.getTotalSize() - this.lottoCounter.getManualSize();
그렇네요... 어차피 전체로또갯수와 수동로또갯수를 알고 있는 도메인은 `LottoCounter`의 관심사니까 그곳에서 계산을 하는 게 더 직관적이겠네요!

2022-03-04 12:32 UTC, bcc0830 commented on src/main/java/domain/ManualGenerator.java
> +		validateDuplicate(this.candidates);
그렇네요! 애초에 저 validate 조건 메소드 들을 통과되어야 생성하는 게 자연스러우니까요