[2단계 - 로또(수동)] 릭(나일성) 미션 제출합니다.
woowacourse/java-lotto pull request #425
Opened 2022-02-28 15:08 UTC by nailseong

안녕하세요 희봉 😵‍💫
1단계 미션 마지막 피드백 반영하고, 2단계 요구사항 구현했습니다!!!

2022-02-28 16:24 UTC, nailseong commented on src/main/java/lotto/domain/Lotto.java
> +                .collect(Collectors.toCollection(TreeSet::new)));
`.collect()`로 최종 연산할 때 Collectors.toSet()을 썼는데, `Collectors.toCollection()`을 써야 컬랙션의 구현 클래스를 지정할 수 있더라구요! 😓

2022-02-28 16:24 UTC, nailseong commented on src/main/java/lotto/domain/Money.java
> +    private static final int PRICE = 1000;
로또의 가격 `PRICE`를 Money 클래스로 옮겼어요.
`Lottos`가 몇개의 로또를 생성해야 하는지는 로또의 가격을 알 필요없이 Money에게 메시지를 던지기 때문에 `Lottos`는 로또 가격이 얼마인지 알 필요가 없더라구요... 😓

2022-02-28 16:24 UTC, nailseong commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
이름을 Rank로 변경하고 타입의 이름도 Rank에 맞는 이름으로 변경하였어요 😵‍💫

2022-02-28 16:24 UTC, nailseong commented on src/test/java/lotto/domain/WinningNumbersTest.java
> +                        Arguments.of(List.of(1, 2, 3, 7, 43, 44), Rank.Fifth)
https://github.com/woowacourse/java-lotto/pull/342#discussion_r815630789
우선 4등, 5등일때 보너스 번호도 맞춘 경우의 테스트 케이스를 추가했어요.
만약 아래 `getRank`메서드에서 5개를 맞춘 경우에만 보너스볼 여부를 확인하지 않으면 `Rank.of`메서드에서 확인을 해야했어요.
이 로직은 아래 메서드에 있는게 더 좋을것 같아서 테스트 케이스만 추가하고 그대로 뒀어요... 😓
```java
    public Optional<Rank> getRank(Lotto lotto) {
        int count = getCount(lotto);
        boolean containsBonus = false; // default로 false를 넘겨준다.

        if (count == Rank.Third.getCount()) { // 당첨 번호와 5개 일치할 때만 보너스 볼 포함 여부 확인!!
            containsBonus = lotto.contains(bonusNumber);
        }

        return Rank.of(count, containsBonus);
    }
```

2022-02-28 16:24 UTC, nailseong commented on src/main/java/lotto/domain/Lotto.java
> +    public static Lotto createByAuto() {
자동, 수동 생성한다는 행위를 이름으로 드러내기 위해서 정적 팩토리 메서드를 활용했어요.

2022-02-28 16:24 UTC, nailseong commented on src/main/java/lotto/domain/Lottos.java
> +    public Lottos(Money money, List<Lotto> lottos) {
생성자가 매개변수로 인스턴스 변수가 아닌 값을 받는 것에 대해서 희봉은 어떻게 생각하나요??

우선 저는 생성자가 매개변수를 갖는다면 `인스턴스 변수만` 갖는 게 좋다고 생각해요. 만약 클라이언트가 이 생성자를 호출하면 `Lottos 는 Money랑 List<Lotto>를 인스턴스 변수로 갖겠구나!!` 라고 생각할 것 같아요... 도메인 내부에 코드가 점점 기괴해지는 느낌도 들었고요.... 😵‍💫
이렇게 매개변수로 인스턴스 변수가 아닌 값을 받는 생성자를 public으로 노출하는 게 구현을 잘 감추지 못한, 즉 `추상화`가 잘 이루어지지 않은 건가?라는 생각이 들었어요.
어쩌면 이전에 고민하던 새로운 계층을(Service가 되겠죠?) 지금 도입해야 하는 걸까?라는 생각도 들었어요...
이 부분에 대해서 희봉의 생각이 궁금해요!!! 🧐

2022-02-28 16:24 UTC, nailseong commented on src/main/java/lotto/domain/Lottos.java
>      }
지금 생성자는 수동으로 생성한 `List<Lotto> lottos`를 받아서 Money에게 자동으로 몇개 생성할까?라고 메시지를 던져요.
그리고 매개변수로 받은 `lottos`에 자동으로 생성한 로또를 `.add()` 하고 인스턴스 변수를 초기화하는데요...
이렇게 Lottos를 하나만 생성하지 말고, 컨트롤러에서 `Lottos manualLottos`, `Lottos autoLottos`로 나눠서 생성하는게 좋을까요?
- 수동, 자동으로 몇개의 로또를 구입했는지 출력하기 편리하다.
- 수동, 자동으로 나눠서 따로 객체를 생성하고 관리할 수 있다.

이런 장점이 있는것 같지만 Lottos 입장에서 보면 `내가 갖고 있는 로또들이 자동이든 수동이든 뭐가 중요하지??`라는 생각도 들어요.
지금 상황이라면 나눠서 생성하고 관리하는 쪽이 더 장점이 크겠죠?? 🧐

➕ 질문을 작성하다보니 생성자가 너무 많은 일을 하는것 같다는 생각이 들어요. 생성자의 책임을 덜어주는 방향을 고민해봐야겠어요😓

2022-03-01 06:47 UTC, heebong requested changes
안녕하세요, 릭! 리뷰어 희봉입니다 😄 
2단계 미션을 빠르게 구현해주셨네요! 1단계 머지시 드린 피드백과 2단계 미션을 잘 구현해주셨습니다 💯 
추가로 피드백을 코멘트로 몇개 남겼는데요, 확인 부탁드립니다. 궁금한점이 있다면 댓글 혹은 DM 아시죠? 😎

2022-03-01 06:47 UTC, heebong commented on src/main/java/lotto/domain/Lottos.java
> +    public Lottos(Money money, List<Lotto> lottos) {
생성자가 매개변수로 인스턴스 변수만 갖도록 기준을 잡는 것 👍 안된다는건 아닙니다. 생성하는데 필요한 내용을 받을 수 있어요. 물론 될 수 있으면 각 객체끼리 의존을 최소로 하는 것도 좋습니다. (닉이 생각한 것 장점들도 맞고요.)
그래도 `Money`를 받으며 찝찝-한 기분을 느끼는 것도 훌륭합니다. 코드 스멜을 느꼈다는 것이니까요!! 😄 
`Money`가 필요한 이유를 볼까요? 해당 객체가 필요한 이유는 자동으로 구매할 수 있는 수, 즉 `quantityOfAuto`값이 필요하기 때문입니다. 그러면 `quantityOfAuto` 자체를 받으면 안될까요?

advance ⬆️  우선 이것으로 `Lottos`와 `Money`간에 의존관계는 사라졌네요! 하지만 여전히 인스턴스 필드가 아닌 값, `quantityOfAuto`와 `lottos`가 있지요. (lottos도 자동으로 만든 값도 인스턴스 필드에 추가되니까 엄밀히 말하면 인스턴스 필드의 값은 아니죠)
만약 이것도 찝찝하다면, `Lotto`에서 사용했던 정적 팩토리 메서드를 사용해보는건 어떨까요? [이 글](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)을 읽어보시면 정적팩토리 메서드에 대해 알 수 있습니다. 글의 예시가 로또라서 혹시 해당 구현을 정답으로 생각할까 우려되긴 하지만 😅 글이 나타내는 정보를 잘 생각해보길 바랍니다.

2022-03-01 06:47 UTC, heebong commented on src/main/java/lotto/domain/Lottos.java
>      }
좋은 접근법입니다! 확실히 지금 `Lottos` 생성자는 `로또 자동으로 생성해서 받은 변수와 합쳐`라는 일을 하고있죠. 생성자의 책임을 덜어준다면 확실히 더 유연해질겁니다. 😄 
그 방법으로 생성자에서 `manual`, `auto`를 따로 만드는 것도 좋은 방법이에요. 릭이 생각한 것 처럼 각각의 장단점이 있겠지만, 현재 어떤 방법의 장점이 더 좋은지 판단해서 결정했으면 좋겠습니다. 👍

2022-03-01 06:47 UTC, heebong commented on src/main/java/lotto/domain/Money.java
> +        return value / PRICE;
해당 값이 계속 변하지 않고, `getAvailableQuantity()`를 호출할 때 마다 계산해야하니 `static`으로 미리 들고있는건 어떨까요?

2022-03-01 06:47 UTC, heebong commented on src/main/java/lotto/domain/WinningNumbers.java
> +        if (count == Rank.Third.getCount()) {
advance ⬆️ `Rank.Third.getCount()`를 꺼내서 직접 비교하지 말고 `Rank`한테 `count`값을 건내며 `true/false`값을 물어보는건 어떨까요? `bonus값 확인 해야하니?`

2022-03-01 09:49 UTC, nailseong commented on src/main/java/lotto/controller/LottoController.java
> +        return Lottos.of(manualLottos.getLottos(), autoLottos.getLottos());
로또를 수동, 자동으로 나누어서 생성하도록 변경했어요, 모든 로또를 생성한 후에는 하나의 로또로 합쳐서 반환하도록 했어요.
이렇게 나눠서 입력 받고 생성한 후에 합쳐서 반환하는 방법이 지금 구조에서 더 좋은것 같아요!!

2022-03-01 09:49 UTC, nailseong commented on src/main/java/lotto/domain/Lottos.java
> +    }
정적 팩토리 메서드를 활용해서 `Money`와 의존관계를 끊었어요!!!
추가로 정적 팩토리 메서드를 활용하니까 이름을 통해서 의도를 명확하게  드러낼수있어서 좋았어요 😆

2022-03-01 09:49 UTC, nailseong commented on src/main/java/lotto/domain/Lottos.java
>      }
두개의 `로또 List`를 받아서 하나의 `Lottos`로 합쳐주는 정적 팩토리 메서드인데요.
매개변수가 타입이 같아서 이름을 짖기 어려워서 `lottos1`, `lottos2`로 지었어요. 메서드 이름도 뭔가 명확하지 않아보여요.
물론 메서드의 역할은 2개의 List를 합친 리스트로 Lottos를 만들어서 더하는 순서 (lotto1과 lotto2의 순서)는 중요하지 않아요.

그래서 생각해본 더 좋은 방법으로는
- `public Lottos add(Lottos lottos)` 메서드로 변경한다. (매개 변수를 1개만 받고, 이름으로 의도를 더 명확하게 할 수 있다.)
- 매개변수를 `List<Lotto> ...args` 가변인수로 변경한다. (메서드이름 `of`에 더 어울리는 매개변수인 것 같아요.)

이렇게 매개변수의 타입이 동일한 경우, 타입이 동일하지만 매개변수를 받는 순서가 중요하지 않는 경우 희봉은 어떤 식으로 이름을 짓나요??🧐

2022-03-01 09:49 UTC, nailseong commented on src/main/java/lotto/domain/Result.java
> -    }
`Result`가 Money를 받아서 직접 메서드를 호출하지 않고 중간 결과값인 `totalProfit`(총 상금액) 을 반환하도록해서 Money와 의존관계를 끊었어요!!!😆

2022-03-01 09:49 UTC, nailseong commented on src/main/java/lotto/domain/WinningNumbers.java
> +        if (Rank.needCheckBonus(count)) {
특정 필드의 값을 직접 꺼내서 비교하지 않고 객체에게 메시지를 던지도록 변경했어요!! 😆

2022-03-02 14:15 UTC, heebong commented on src/main/java/lotto/domain/Lottos.java
>      }
각자의 장점을 나열해서 고민해보는 것 👍  우선 제가 정답이 아님을 다시 말씀드릴게요 😄 
저는 `public Lottos add(Lottos lottos)`방식을 선택할 것 같아요. (new Lottos를 반환한다는 조건)
이유는 `List<Lotto>`를 한 번에 2개 이상 여러개 연결하는 경우가 드물 것 같아 이름의 의도를 명확하게 하는게 더 효과적으로 보이기 때문이에요. 그리고 혹시 3개 이상을 연결해야 하면 체인으로 연결할 수도 있고요. 그래서 `add()`를 사용할 것 같습니다.

advance ⬆️  그리고 `List<T>... args`는 `public` 함수의 인자로 사용하는걸 지양하려 합니다. (아마 사용하면 `warning`이 나올텐데요) 확실하게 `<T>`가 들어온다는 보장이 없는 상황에선 사용하지 않으려고 합니다. 물론 이건 제 생각이에요. 이펙티브 자바의 `아이템 32 제네릭과 가변인수를 함께 쓸 때는 신중하라`를 읽어보길 추천합니다! (추가로 `List.of()` 함수들을 확인하길 추천해요)

2022-03-02 14:54 UTC, heebong approved these changes
안녕하세요, 릭! 리뷰어 희봉입니다.
빠르게 피드백을 반영하셨네요! 코드가 많이 깔끔해졌어요 👍 
이번 과제는 여기서 머지하도록 하겠습니다 😄 릭이 자신만의 기준을 정해서 개발하고, 기준을 정해가는 과정을 함께해서 즐거웠습니다.
추가로 생각해볼 내용들을 코멘트로 남겼어요. 지금 해봐도 괜찮고 앞으로 과제를 해가면서 생각해도 괜찮습니다. 궁금한 내용이 있다면 댓글이나 DM 주세요. 과제하느라 고생하셨어요 💰

2022-03-02 14:54 UTC, heebong commented on src/main/java/lotto/domain/Lottos.java
>      }
각자의 장점을 나열해서 고민해보는 것 👍  우선 제가 정답이 아님을 다시 말씀드릴게요 😄 
저는 `public Lottos add(Lottos lottos)`방식을 선택할 것 같아요. (new Lottos를 반환한다는 조건)
이유는 `List<Lotto>`를 한 번에 2개 이상 여러개 연결하는 경우가 드물 것 같아 이름의 의도를 명확하게 하는게 더 효과적으로 보이기 때문이에요. 그리고 혹시 3개 이상을 연결해야 하면 체인으로 연결할 수도 있고요. 그래서 `add()`를 사용할 것 같습니다.

advance ⬆️  그리고 `List<T>... args`는 `public` 함수의 인자로 사용하는걸 지양하려 합니다. (아마 사용하면 `warning`이 나올텐데요) 확실하게 `<T>`가 들어온다는 보장이 없는 상황에선 사용하지 않으려고 합니다. 물론 이건 제 생각이에요. 책 이펙티브 자바의 `아이템 32 제네릭과 가변인수를 함께 쓸 때는 신중하라`를 읽어보길 추천합니다! (추가로 `List.of()` 함수들을 확인하길 추천해요)

2022-03-02 14:54 UTC, heebong commented on src/main/java/lotto/domain/Lottos.java
> +    public static Lottos createByAuto(int quantity) {
advance ⬆️ `Lottos`와 `Lotto`의 `createByAuto`, `createByManual` 같은 `static` 함수를 따로 `Factory` 객체에게 위임하는건 어떨까요? 어떤 방식으로 `Lotto`를 만들건지는 `Lotto`가 몰라도 될 영역이라고 생각해요. 어차피 `Lotto`는 `List<Number>`, `Lottos`는 `List<Lotto>`만 받으면 되니까요. `Factory` 객체에게 위임하면 역할이 더 줄어들 것 같아요 😄

2022-03-02 14:54 UTC, heebong commented on src/main/java/lotto/domain/Money.java
> -    public String toString() {
`toString`은 왜 제거했을까요? 🤔 

hint 책 이펙티브 자바의 `아이템 12 toString은 항상 재정의하라`를 읽어보아요

2022-03-02 14:54 UTC, heebong commented on src/main/java/lotto/controller/LottoController.java
> +            final int quantityOfManual = InputView.inputManualCount();
advance ⬆️ `controller`에서 `input`, `output`을 분리해봅시다. 😄 
현재 `controller`에서 `input`을 사용해 객체를 생성하고있어요. 만약 `input` 방식이 바뀐다면 해당 `controller` 모두 변경 대상이됩니다. `input`과 `output`을 main에서 사용하고, `controller`는 `input`의 값을 받는 형식으로 변경할 수 없을까요? 쉽진 않겠지만 한번 생각해보길 추천드려요 🙂

2022-03-02 14:55 UTC, merged