[2단계 - 로또(수동)] 아리(양유림) 미션 제출합니다.
woowacourse/java-lotto pull request #427
Opened 2022-02-28 16:05 UTC by ulimy

안녕하세요 또링! 아리입니다 : )

DM으로 답변해주셨던 부분들을 고려하며 2단계를 진행해보았습니다.

잘부탁드립니다!

2022-03-01 08:08 UTC, jnsorn requested changes
안녕하세요, 아리! 리뷰어 또링입니다. 반가워요 👋
2단계 잘 구현해주셨어요. 개선되면 좋을 부분에 코멘트 남겨두었으니 확인해보시고 다시 리뷰요청 해주세요! :) 
궁금하거나 얘기 나누고 싶은 내용은 언제든 DM 주시구요! ☺️

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
> +	private final ArrayList<Integer> LottoNumberCandidates = new ArrayList<>();
```suggestion
	private final List<Integer> LottoNumberCandidates = new ArrayList<>();

```
구현클래스가 아닌 인터페이스를 사용하여 선언하면 어떤 장점이 있을까요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
>  public class LottoGameController {
아리가 생각하는 Controller의 역할은 무엇인가요?
현재 LottoGameController는 LottoNumberCandidate도 초기화 해주고, 자동 로또를 생성해주는 역할도 하고 있어요. controller의 역할이 맞을까요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
> +		printLottoTickets(manualCount, randomCount, this.lottoTickets);
this를 사용하는 기준은 무엇인가요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
> +		for (int eachNumber = 1; eachNumber <= 45; eachNumber++) {
1과 45의 의미는 무엇일까요? 👀

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
> +			randomLottoNumbers.add(LottoNumbers.of(LottoNumberCandidates.subList(0, 6)));
6의 의미는 무엇일까요? 👀

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/AnswerLotto.java
> +	private final LottoNumber bonusNumber;
LottoNumbers와 LottoNumber를 조합해서 AnswerLotto를 만들었네요! 💯

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +	}
Object o 에 LottoNumber가 아닌 다른 클래스가 들어간다면 어떤 일이 일어날까요? 
[[이펙티브 자바 3판] 아이템 10. equals는 일반 규약을 지켜 재정의하라](https://madplay.github.io/post/obey-the-general-contract-when-overriding-equals)

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/LottoNumbers.java
> +	private final List<LottoNumber> numbers;
`LottoNumber들은 중복될 수 없다`는 규칙과 잘 맞는 자료구조를 사용해볼까요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/LottoNumbers.java
> +		return (int) numbers.stream().filter(n -> target.contains(n)).count();
```suggestion
		return (int) numbers.stream()
			.filter(target::contains)
			.count();
```

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/LottoTickets.java
> +	public Result generateResult(AnswerLotto answerLotto) {
테스트를 작성해볼까요? 🔍

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/Money.java
> +public class Money {
원시값 포장 💯

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/Money.java
> +	private final int inputMoney;
보통 원시값을 감싼 객체의 변수는 `value`라는 이름으로 짓기도 합니다! 참고해주세요 :)

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/Result.java
> +	private float profitRate;
Result가 profitRate를 인스턴스 변수로 갖게 된 이유는 무엇일까요? 🤔

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/Result.java
>  	private Map<ResultStatics, Integer> results;
아리가 final을 사용하는 기준은 무엇인가요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/ResultStatics.java
>  	NOTHING(0, 0, false),
```java
	NOTHING(0, 0, false),
	THREE(3, 5000, false),
	FOUR(4, 50000, false),
	FIVE(5, 1500000, false),
	FIVE_AND_BONUS(5, 30000000, true),
	SIX(6, 2000000000, false); // -> FIRST(6, 2000000000, false)
```
ResultStatics의 값들을 맞춘 갯수가 아닌 등수로 관리하면 코드를 이해하기 더 쉬울 것 같아요 :)

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/ResultStatics.java
>  		if (numberMatches == 6) {
`of` 메서드의 길이가 10줄을 넘어가네요! stream을 이용해서 바꿔볼까요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/view/InputView.java
> +		List<List<Integer>> inputs = new ArrayList<>();
inputs보다 더 좋은 이름은 없을까요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/view/InputView.java
>  	public static List<Integer> inputAnsNumbers() {
축약 금지 😱

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/view/InputView.java
> +	private InputView(){}
### InputView.validateEmpty()
```java
	private static void validateEmpty(String Input) {
		if (Input.isEmpty()) {
			throw new IllegalArgumentException(MUST_NOT_EMPTY);
		}
	}
```
input에 null이 들어간다면 어떻게 될까요? (`I` 대문자도 수정해주세요!)

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/view/InputView.java
> +	private InputView(){}
### InputView.validateStandard()
```java
	private static void validateStandard(String input) {
		if (!input.contains(STANDARD_OF_ANSWER_NUMBERS)) {
			throw new IllegalArgumentException(WRONG_STANDARD_INPUT);
		}
	}
```
<img width="244" alt="스크린샷 2022-03-01 오후 2 43 40" src="https://user-images.githubusercontent.com/31095063/156125977-23c2dc3a-bee0-4b1f-9f20-681cff6f4e9d.png">

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/view/InputView.java
> +	private InputView(){}
### InputView.parseMultipleNumber()
```java
		private static List<Integer> parseMultipleNumber(String input) {
		List<Integer> answers = new ArrayList<>();
		String[] parsedInput = input.split(STANDARD_OF_ANSWER_NUMBERS);

		for (String eachInput : parsedInput) {
			validateNumber(eachInput);
			answers.add(Integer.parseInt(eachInput));
		}

		return answers;
	}
```
answers보다 더 좋은 이름이 있을 것 같아요.

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/view/OutputView.java
>  	}
`ErrorConstant`의 `START_ERROR`가 모든 에러 나는 곳에 등장하고 있어요! 결국 사용자에게 메세지를 보여줄 때 사용하기 위한 상수니 여기서 관리하는 건 어떨까요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/view/OutputView.java
> +		System.out.println("총 수익률은 " + ratio + "입니다.");
수익률을 소수점 아래 두자리에서 끊어볼까요!

2022-03-01 08:08 UTC, jnsorn commented on src/test/java/domain/AnswerLottoTicketTest.java
> +public class AnswerLottoTicketTest {
테스트 클래스 이름을 프로덕션 클래스 이름과 맞춰볼까요?

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/LottoNumbers.java
> +	public int calculateDuplicatedCount(List<LottoNumber> target) {
테스트코드 추가! 🔍

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/LottoNumbers.java
> +		return (int) numbers.stream().filter(n -> target.contains(n)).count();
target.contains 대신 만들어둔 메서드를 이용하면 어떨까요?

2022-03-01 08:08 UTC, jnsorn commented on src/test/java/domain/LottoNumberTest.java
> +	}
하나로 합칠 수 있지 않을까요? 중복을 제거하고, 경계값을 테스트해봐요. :)

2022-03-01 08:08 UTC, jnsorn commented on src/test/java/domain/LottoNumbersTest.java
> +public class LottoNumbersTest {
예외 테스트에 대해서는 메세지까지 비교해서 더 정확한 테스트를 해봅시다! (다른 테스트들도 수정해주세요)

2022-03-01 08:08 UTC, jnsorn commented on src/test/java/domain/LottoTicketTest.java
> +public class LottoTicketTest {
여기는 @DisplayName이 없네요. 일관성있는 코드는 가독성을 높일 수 있어요! 😎

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/Money.java
> +	public int calculateTotalCount() {
테스트 코드 추가! 🔍

2022-03-01 08:08 UTC, jnsorn commented on src/test/java/domain/ResultTest.java
> +	static Map<Result, Float> testCase = new HashMap<>();
접근제어자가 빠져있어요~ 🔍

2022-03-01 08:08 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +import static constant.LottoConstant.MIN_NUMBER;
해당 상수는 여기에서만 사용되고 있어요! LottoConstant에 있을 필요가 있을까요?

2022-03-02 05:46 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
> +	private final ArrayList<Integer> LottoNumberCandidates = new ArrayList<>();
추후에 구현클래스가 변경되더라도 해당 클래스를 이용하는 곳에서는 코드의 변화가 일어나지 않습니다! 알고있었는데 놓쳤네요ㅠ 더 꼼꼼하게 확인하겠습니다!

2022-03-02 05:47 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
> +		for (int eachNumber = 1; eachNumber <= 45; eachNumber++) {
로또 숫자의 최댓값과 최솟값입니다! 상수처리 완료했습니다.

2022-03-02 05:47 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
> +			randomLottoNumbers.add(LottoNumbers.of(LottoNumberCandidates.subList(0, 6)));
하나의 로또에 포함되는 숫자의 개수입니다! 상수처리 완료했습니다.

2022-03-02 05:48 UTC, ulimy commented on src/main/java/domain/AnswerLotto.java
> +	private final LottoNumber bonusNumber;
감사합니다 :)

2022-03-02 05:48 UTC, ulimy commented on src/main/java/domain/Money.java
> +public class Money {
감사합니다 :)

2022-03-02 05:49 UTC, ulimy commented on src/main/java/domain/Money.java
> +	private final int inputMoney;
Money라는 클래스안에 money라는 변수가 있는 것이 괜찮을까 고민했었는데 value를 이용하기도 하는군요! 더 좋은 네이밍인 것 같아 수정했습니다.

2022-03-02 05:50 UTC, ulimy commented on src/main/java/domain/ResultStatics.java
>  	NOTHING(0, 0, false),
등수로 관리하니 추후에 등수결정기준이 변경되더라도 네이밍이 변경 될 필요가 없겠네요! 수정했습니다 :)

2022-03-02 05:51 UTC, ulimy commented on src/main/java/view/InputView.java
> +		List<List<Integer>> inputs = new ArrayList<>();
수동으로 구매한 모든 번호를 담는 변수이니 totalManualNumbers 로 수정했습니다.

2022-03-02 05:51 UTC, ulimy commented on src/main/java/view/InputView.java
>  	public static List<Integer> inputAnsNumbers() {
놓친 부분이네요ㅠ 수정했습니다!

2022-03-02 05:52 UTC, ulimy commented on src/main/java/view/InputView.java
> +	private InputView(){}
실수로 삭제하지 못했던 purchase 프린트문 삭제 완료했습니다!

2022-03-02 05:52 UTC, ulimy commented on src/main/java/view/InputView.java
> +	private InputView(){}
answers는 parse완료된 숫자들을 담는 변수이므로 parsedMultipleNumbers 로 수정했습니다.

2022-03-02 05:53 UTC, ulimy commented on src/main/java/view/OutputView.java
>  	}
에러 시작메시지를 위한 클래스가 존재하는 것 같아 찜찜했는데 이렇게 간단한 방법이 있었군요! 부족한 자신임을 또 한번 깨닫습니다ㅜㅜ 수정했습니다!

2022-03-02 05:54 UTC, ulimy commented on src/test/java/domain/AnswerLottoTicketTest.java
> +public class AnswerLottoTicketTest {
수정했습니다.

2022-03-02 05:54 UTC, ulimy commented on src/test/java/domain/LottoTicketTest.java
> +public class LottoTicketTest {
놓친 부분이네요! 추가했습니다.

2022-03-02 05:54 UTC, ulimy commented on src/test/java/domain/ResultTest.java
> +	static Map<Result, Float> testCase = new HashMap<>();
추가했습니다!

2022-03-02 05:57 UTC, ulimy commented on src/main/java/domain/LottoNumber.java
> +import static constant.LottoConstant.MIN_NUMBER;
저도 같은 고민을 했었는데요! 추후에 최대, 최소 값이 변한다고 했을 때 그 상수가 사용 되는 곳을 찾아 수정하는 것보다 로또에 모든 상수가 관리되는 곳에 가서 수정하는 것이 더욱 직관적일 것 같아 LottoConstant에 선언했습니다. 또한 리팩토링을 진행하면서 로또번호 자동생성을 하는 곳에서도 사용되어 위치를 수정하지는 않았습니다.

2022-03-02 06:13 UTC, ulimy commented on src/main/java/domain/Result.java
>  	private Map<ResultStatics, Integer> results;
제가 final을 사용하는 기준은 초기화 된 이후 해당 값의 수정여부입니다. 따라서 profit의 경우 setProfit에서 초기화 된 이후 값이 변경되지 않으므로 final을 사용하였고, results의 경우 addResult를 통해 지속적으로 값이 수정되므로 final을 사용하지 않았습니다.

2022-03-02 07:27 UTC, ulimy commented on src/main/java/domain/LottoNumbers.java
> +		return (int) numbers.stream().filter(n -> target.contains(n)).count();
LottoNumbers에 구현되어있던 isExist를 이용하도록 수정했습니다!

2022-03-02 07:28 UTC, ulimy commented on src/main/java/domain/LottoTickets.java
> +	public Result generateResult(AnswerLotto answerLotto) {
작성했습니다!

2022-03-02 07:29 UTC, ulimy commented on src/main/java/domain/LottoNumbers.java
> +	public int calculateDuplicatedCount(List<LottoNumber> target) {
작성했습니다!

2022-03-02 07:29 UTC, ulimy commented on src/test/java/domain/LottoNumberTest.java
> +	}
합쳤습니다 :)

2022-03-02 07:30 UTC, ulimy commented on src/test/java/domain/LottoNumbersTest.java
> +public class LottoNumbersTest {
hasMessageContaining("") 이번 기회에 처음 알게되었습니다! 적용했습니다 :)

2022-03-02 07:30 UTC, ulimy commented on src/main/java/domain/Money.java
> +	public int calculateTotalCount() {
작성했습니다!

2022-03-02 08:34 UTC, ulimy commented on src/main/java/domain/LottoNumbers.java
> +	private final List<LottoNumber> numbers;
Set으로 변경했습니다 :)

2022-03-02 09:12 UTC, ulimy commented on src/main/java/view/InputView.java
> +	private InputView(){}
null이 입력되면 에러메시지가 출력되도록 수정했습니다! 다만 이를 어떻게 테스팅하면 좋을까요? InputStream에 null을 주입하는 방법을 찾지 못했습니다ㅠㅠ 혹시 제가 모르는 방법이 있을까요?

2022-03-02 09:12 UTC, ulimy commented on src/main/java/view/OutputView.java
> +		System.out.println("총 수익률은 " + ratio + "입니다.");
수정했습니다!

2022-03-02 13:05 UTC, ulimy commented on src/main/java/domain/LottoNumber.java
> +	}
null이거나 다른 클래스가 입력될 경우 에러가 발생하겠군요! 처음 알게되었습니다. 점검해줄 수 있는 코드 추가했습니다. 감사합니다 :)

2022-03-02 13:23 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
> +		printLottoTickets(manualCount, randomCount, this.lottoTickets);
특별히 생각해본적이 없어 공부해보았더니 세가지 정도의 기준을 알게되었습니다.
1. 인스턴스/클래스변수명과 매개변수명이 같은 경우
2. 클래스에 오버로딩된 다른 생성자를 호출하는 경우
3, 객체 자신의 참조값을 전달하고 싶은 경우
해당 기준에 맞게 전체적으로 수정했습니다!
다시보니 정말 제각각이더군요..ㅠㅠ

2022-03-02 14:26 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
>  public class LottoGameController {
Controller의 책임은 최대한 redirection만을 가져야 한다고 생각했습니다. 
하지만 자동차경주게임 미션을 진행하면서 필요하다면 컨트롤러에서도 로직을 수행할 수 있음을 알게되었고,
그 혼란이 가져온 결과인 것 같습니다ㅜㅜ 
다시 고민해본 결과 자동, 수동 로또티켓 생성은 LottoTicket에게 책임을 부여하는 것이 올바른 것 같아 책임을 이동했습니다. 
다만 다른 로직들은 아직 컨트롤러에 있습니다. 로직 분리를 위해 여러가지 방법을 고안해보았는데요.
i) service 추가구현 - view에 의존하지 않기위한 로직이 필요함. (자동/수동 로또 생성 개수 계산 후 반환  등)
ii) 구입금액, 로또 구매, 결과생성 등을 각각 책임지는 컨트롤러 추가구현 - 현재와 크게 다를 것이 없어보임.
이렇듯 두가지 방법 전부 올바른 방법은 아니라 생각됩니다.
현재 이대로도 충분한지, 혹은 제가 모르는 다른 방안이 있는지 또링의 의견을 여쭤보고싶습니다!

2022-03-02 14:29 UTC, ulimy commented on src/main/java/domain/Result.java
> +	private float profitRate;
다시 생각해보니 필요없는 변수로 판단되어 삭제했습니다!

2022-03-02 14:34 UTC, ulimy commented on src/main/java/domain/ResultStatics.java
>  		if (numberMatches == 6) {
numberMatches가 3개 미만인 경우 바로 NOTHING을 반환하고, 나머지의 경우 numberMatches와 hitBonus로 필터링 하여 반환하도록 수정하였습니다. 이때 LottoNumbers에서 로또숫자의 개수도 6개로 보장되어있고, LottoTicket에서 5개인 경우에만 hitBonus를 수정하도록 보장되어있으니 ResultStatics.of 에서 추가로 검증하지 않아도 괜찮을까요?

2022-03-03 17:00 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +	}
해당 클래스에 `cmd + n`을 누르면 자동으로 생성해주는 메서드들이 나와요. IDE 기능을 이용해서 생성하면 더 편하게 구현하실 수 있습니다. ☺️

2022-03-03 17:14 UTC, jnsorn commented on src/main/java/view/OutputView.java
>  	}
전혀 부족하지 않습니다 ㅎㅎ 잘하고 계세요 🥰

2022-03-03 19:13 UTC, jnsorn requested changes
안녕하세요, 아리! 리뷰 잘 반영해주셨네요 :) 많은 고민하신 게 느껴져요 👏🏻
조금 더 고민해보면 좋을 부분에 코멘트 남겼으니 확인해보시고 다시 요청주세요!

2022-03-03 19:13 UTC, jnsorn commented on src/main/java/domain/ResultStatics.java
>  		}
early return 👍🏼

2022-03-03 19:13 UTC, jnsorn commented on src/main/java/domain/LottoTicket.java
> +	}
기본 생성자는 자동 로또를 생성하고, 파라미터가 있는 생성자는 수동 로또를 생성하고 있어요. 
정적 팩토리 메서드를 통해 의도를 명확하게 표현해볼까요?

2022-03-03 19:13 UTC, jnsorn commented on src/main/java/domain/Result.java
>  		results.put(resultStatics, results.get(resultStatics) + 1);
(참고) `getOrDefault()`라는 메서드도 있어요.

2022-03-03 19:13 UTC, jnsorn commented on src/main/java/constant/LottoConstant.java
> +	public static final int NUMBER_FOR_WINNER = 3;
우승을 위한 최소한의 숫자라는 의미를 담아보면 어떨까요? `NUMBER_FOR_WINNER`는 우승 숫자의 느낌이..!

2022-03-03 19:13 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
>  public class LottoGameController {
많이 고민해보셨군요! 👍🏼 

저도 아리와 마찬가지로 컨트롤러는 도메인의 데이터를 뷰에 전달하고, 뷰의 데이터를 도메인에 전달하는 계층이라고 생각해요. 
그런 의미에서 제 눈에는 아직 컨트롤러의 역할이 아닌 코드가 보여요!

- `purchaseManualLotto` 는 입력 받은 수동 번호를 통해 `LottoNumbers`를 생성하고, `LottoNumbers`를 통해 `LottoTicket`을 발급하고 있어요.

- 또, `purchaseRandomLotto`는 특정 횟수만큼 `LottoTicket`을 발급하고 있구요. 

이렇게 로또 티켓을 발급하는 건 컨트롤러의 책임일까요? 아님 또 다른 객체의 책임일까요? 

혹시 제 답변이 애매하다면 DM주세요! 😃

2022-03-03 19:13 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +import static constant.LottoConstant.MIN_NUMBER;
이미 고민해보셨군요! 💯 말씀하신대로 하나의 클래스 안에서 상수를 관리하면 편하다는 이점이 있겠네요. 
하지만 `MIN_NUMBER`, `PRICE_OF_LOTTO` 등 도메인 규칙과 관련된 상수가 public하게 공개되어 이곳 저곳에서 사용한다면 어떤 일이 일어날까요? 분명 도메인 규칙과 관련된 상수임에도 해당 상수는 여러 로직에서 사용될 거예요. 그 의미는 한 곳에 모여있어야 할 로직들이 흩어지는 것을 의미해요. 이런 관점에서 저는 상수를 관련 도메인 객체 안에 private하게 넣어 사용합니다. :)

2022-03-03 19:13 UTC, jnsorn commented on src/main/java/domain/Result.java
>  	private Map<ResultStatics, Integer> results;
네 좋아요! 이와 더불어서 이번 단계에서는 불변에 대해서 알아보면 좋을 것 같아요. :) 
[방어적복사](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/), 깊은 복사에 대해 공부해보시고 이 프로그램에서는 어디에 어떻게 적용해야할지 고민해보세요 🤓 
(다음 요청에 반영해서 요청해주세요!)

2022-03-03 19:13 UTC, jnsorn commented on src/main/java/domain/ResultStatics.java
>  	}
> numberMatches가 3개 미만인 경우 바로 NOTHING을 반환하고, 나머지의 경우 numberMatches와 hitBonus로 필터링 하여 반환하도록 수정하였습니다. 이때 LottoNumbers에서 로또숫자의 개수도 6개로 보장되어있고, LottoTicket에서 5개인 경우에만 hitBonus를 수정하도록 보장되어있으니 ResultStatics.of 에서 추가로 검증하지 않아도 괜찮을까요?
```java
return Arrays.stream(ResultStatics.values())
			.filter(r -> ((r.getNumberMatches() == numberMatches) && (r.isHitBonus() == hitBonus)))
			.findFirst()
			.get();
```
네 괜찮습니다. 다만 filter 된 값이 없을 경우를 대비해 get()대신 orElse()를 사용해보면 좋을 것 같네요! 
추가로, ResultStatics 변수에 바로 접근할 수 있어요. :)  `r.getNumberMatches() -> r.numberMatches`

2022-03-03 19:16 UTC, jnsorn commented on src/main/java/view/InputView.java
> +	private InputView(){}
엇 이 부분은 저도 찾아봐야 할 것 같아요 😲 다만 이번 미션 요구사항은 도메인에 대한 테스트가 목표라 방법이 안보인다면 가볍게 넘어가도 괜찮을 것 같습니다ㅎㅎ

2022-03-04 14:51 UTC, ulimy commented on src/main/java/domain/ResultStatics.java
>  	}
넵 수정했습니다!

2022-03-04 15:00 UTC, ulimy commented on src/main/java/domain/Result.java
>  		results.put(resultStatics, results.get(resultStatics) + 1);
처음에는 getOrDefault()로 구현했습니다! 그렇게 구현해보니 당첨된 경우에만 results에 추가됨으로써 추후에 당첨통계를 출력할 때  각 ResultStatics별로 map 존재 여부를 판단하여 존재하지 않는 경우에는 0을 출력하는 로직이 필요했습니다. 개인적으로 이 방법보다는  사전에 전부 초기화해주고 OutputView에서는 출력만을 담당하는 것이 더 깔끔하게 느껴져 현재 적용된 방법을 택했습니다!

2022-03-04 15:02 UTC, ulimy commented on src/main/java/constant/LottoConstant.java
> +	public static final int NUMBER_FOR_WINNER = 3;
동의합니다..! MIN_NUMBER_TO_WIN 로 수정했습니다!

2022-03-04 15:05 UTC, ulimy commented on src/main/java/domain/LottoTicket.java
> +	}
정적팩토리메서드를 활용하여 byManual() , byRandom() 을 구현했습니다. 이때, byRandom의 경우 기본 생성자와 역할이 같기에 굳이 선언해주어야하나 고민했지만, 이를 호출하는 클래스의 입장에서 보았을 때 구현하는 것이 LottoTicket 생성의 일관성을 높이지 않을까 하는 마음이 구현해보았습니다. 이에 대한 또링의 의견은 어떤지 듣고싶습니다!

2022-03-04 15:12 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
>  public class LottoGameController {
로또 티켓 발급 및 결과 생성등을 책임지는 LottoMachine를 새롭게 생성하여 리팩토링 해보았습니다!

2022-03-04 15:13 UTC, ulimy commented on src/main/java/domain/LottoNumber.java
> +	}
단축어 꿀팁까지! 감사합니다 또링 :)

2022-03-04 15:13 UTC, ulimy commented on src/main/java/view/InputView.java
> +	private InputView(){}
넵 :)

2022-03-04 15:14 UTC, ulimy commented on src/main/java/view/OutputView.java
>  	}
감사합니다ㅠㅠ😍

2022-03-04 15:27 UTC, ulimy commented on src/main/java/domain/LottoNumber.java
> +import static constant.LottoConstant.MIN_NUMBER;
여러곳에서 무분별하게 사용될 수 있음은 생각하지 못했던 부분이네요.. 그런 관점에서 바라보니 가능하다면 사용하는 곳에서 private하게 선언하고 공유해야하는 상수만 모아 public하게 선언하는 방법이 더 좋은 것 같아 수정했습니다.

2022-03-04 15:27 UTC, ulimy commented on src/main/java/domain/ResultStatics.java
>  		}
감사합니다 :)

2022-03-04 16:44 UTC, ulimy commented on src/main/java/domain/Result.java
>  	private Map<ResultStatics, Integer> results;
불변..ㅠㅠㅠ 정말 어렵네요....ㅠㅠㅠ
불변을 보장하기 위해 new / Collections.unmodifiable / copyOf 세가지 방법에 대해 공부해보았습니다.
생성자의 인자로 전달받은 경우 new를, getter로 객체를 반환하는 경우  Collections.unmodifiable를 적용해보았습니다 :)

2022-03-05 17:22 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
>  public class LottoGameController {
게임 진행에 대한 책임을 `LottoMachine`이 갖게 되면서 `controller`가 정말 깔끔해졌어요! 💯👏🏻

2022-03-05 17:22 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
> +	LottoMachine lottoMachine;
접근제어자 🔍

2022-03-05 17:22 UTC, jnsorn commented on src/main/java/domain/LottoMachine.java
> +	List<LottoTicket> lottoTickets;
접근제어자 🔍

2022-03-05 17:22 UTC, jnsorn commented on src/main/java/controller/LottoGameController.java
> +			printResult(lottoMachine.generateResult(AnswerLotto.of(inputAnswerNumbers(), inputBonusNumber())));
로또 기계에 당첨 번호를 알려주면 결과를 계산해주네요! 너무 맘에 들어요 👍🏼

2022-03-05 17:22 UTC, jnsorn commented on src/main/java/domain/LottoTicket.java
> +	}
이 부분에 대해서는 왜 정적 팩토리 메서드를 사용하는지 조금 더 알아보면 좋을 것 같아요 :) 
참고 - [정적 팩토리 메서드(Static Factory Method)는 왜 사용할까?](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)

2022-03-05 17:25 UTC, jnsorn commented on src/main/java/domain/Result.java
>  		results.put(resultStatics, results.get(resultStatics) + 1);
크 그랬군요. 좋습니다!

2022-03-05 17:47 UTC, jnsorn commented on src/main/java/constant/LottoConstant.java
>  	public static final int NUMBER_OF_NUMBERS = 6;
> 여러곳에서 무분별하게 사용될 수 있음은 생각하지 못했던 부분이네요.. 그런 관점에서 바라보니 가능하다면 사용하는 곳에서 private하게 선언하고 공유해야하는 상수만 모아 public하게 선언하는 방법이 더 좋은 것 같아 수정했습니다.

좋습니다 👍🏼 이제 상수가 3개 남았는데, 이 상수들이 정말 여러 도메인에서 공유되어야 하는지 생각해보고 정말 공유되어야 한다면 아리의 기준대로 LottoConstant 클래스에서 관리하면 될 것 같아요!

1. `MIN_NUMBER`, `MAX_NUMBER`
💡LottoTicket에서 로또 번호를 캐싱하고, 해당 값들을 가지고 있는 이유는 무엇인가요?

2. `NUMBER_OF_NUMBERS`
💡LottoNumbers와 LottoTicket의 역할은 어떻게 다른가요? 두 객체의 역할과 책임이 다른가요?

2022-03-05 17:47 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +import static constant.LottoConstant.MIN_NUMBER;
좋습니다 👍🏼 이제 상수가 3개 남았는데, 이 상수들이 정말 여러 도메인에서 공유되어야 하는지 생각해보고 정말 공유되어야 한다면 아리의 기준대로 LottoConstant 클래스에서 관리하면 될 것 같아요!

1. `MIN_NUMBER`, `MAX_NUMBER`
💡LottoTicket에서 로또 번호를 캐싱하고, 해당 값들을 가지고 있는 이유는 무엇인가요?

2. `NUMBER_OF_NUMBERS`
💡LottoNumbers와 LottoTicket의 역할은 어떻게 다른가요? 두 객체의 역할과 책임이 다른가요?

2022-03-05 19:09 UTC, jnsorn requested changes
안녕하세요, 아리! 피드백 정말 잘 반영해주셨어요. 코드가 점점 더 깔끔해지고 있습니다. 😭👍🏼
조금 더 생각해보면 좋을 부분에 코멘트 남겼으니 확인해보시고 다시 리뷰 요청해주세요!
거의 다 왔으니 조금만 더 힘내봐요. 😃 혹시 코멘트 이해 안가거나 궁금한 점이 있다면 DM주셔도 좋아요!

2022-03-05 19:09 UTC, jnsorn commented on src/test/java/domain/AnswerLottoTest.java
> +			.hasMessageContaining("보너스 번호는 지난 주 당첨 번호 숫자들과 중복일 수 없습니다");
List 생성 방법이 `Arrays.asList()`에서 `List.of()`로 바뀌었네요 👍 
두 방법은 어떤 차이가 있나요?

2022-03-05 19:09 UTC, jnsorn commented on src/main/java/domain/LottoNumbers.java
> +		}
현재 로또가 생성될 때마다 `LottoNumber`를 생성해주고 있어요. `LottoNumber`는 계속 생성되어야 할까요? 미리 만들어두고 재사용하면 어떨까요?

2022-03-05 19:09 UTC, jnsorn commented on src/main/java/domain/Result.java
>  	private Map<ResultStatics, Integer> results;
어렵다고 하셨는데 대부분 잘 작성해주셨어요 💯 👏🏻
`Result`, `LottoMachine`도 불변객체로 만들 수 있지 않을까요? 
**Hint. 객체 생성 시점에 필요한 것들을 전달해주면 불완전한 상태로 생성되는 것을 막을 수 있어요!**

추가로 불변객체, 방어적복사, 깊은 복사 등을 적용해보면서 어떤 점을 느끼셨는지도 궁금합니다 :)

2022-03-05 19:12 UTC, jnsorn commented
코멘트가 너무 많아졌네요 😭 다음 리뷰 요청 시 아래 항목에 대해서는 꼭 반영해주세요.

- 불변 객체 https://github.com/woowacourse/java-lotto/pull/427#discussion_r820137704
- 상수 클래스 https://github.com/woowacourse/java-lotto/pull/427#discussion_r820130950
- 캐싱 https://github.com/woowacourse/java-lotto/pull/427#discussion_r820136694

2022-03-06 09:57 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
>  public class LottoGameController {
감사합니다

2022-03-06 09:59 UTC, ulimy commented on src/main/java/domain/LottoNumber.java
> +import static constant.LottoConstant.MIN_NUMBER;
LottoNumbers와 LottoTicket의 역할이 거의 같음을 깨닫고 두 클래스를 합치고나니 해당 상수 문제가 자연스럽게 해결되었습니다!

2022-03-06 09:59 UTC, ulimy commented on src/main/java/domain/Result.java
>  		results.put(resultStatics, results.get(resultStatics) + 1);
감사합니다😍

2022-03-06 10:00 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
> +	LottoMachine lottoMachine;
놓친 부분이네요ㅜㅜ 수정했습니다!

2022-03-06 10:00 UTC, ulimy commented on src/main/java/domain/LottoMachine.java
> +	List<LottoTicket> lottoTickets;
놓친 부분이네요ㅜㅜ 수정했습니다!

2022-03-06 10:00 UTC, ulimy commented on src/main/java/controller/LottoGameController.java
> +			printResult(lottoMachine.generateResult(AnswerLotto.of(inputAnswerNumbers(), inputBonusNumber())));
감사합니다😍

2022-03-06 10:05 UTC, ulimy commented on src/test/java/domain/AnswerLottoTest.java
> +			.hasMessageContaining("보너스 번호는 지난 주 당첨 번호 숫자들과 중복일 수 없습니다");
Arrays.asList()는 List.of()와 달리 요소의 변경이 가능하고 null이 허용됩니다!

2022-03-06 10:06 UTC, ulimy commented on src/main/java/domain/LottoNumbers.java
> +		}
LottoNumber에 전체 로또번호를 정의하고 이를 돌려주는 방식으로 리팩토링 해보았습니다 :)

2022-03-06 10:31 UTC, ulimy commented on src/main/java/domain/LottoTicket.java
> +	}
좋은 글을 공유해주신 덕분에 더욱 논리적인 견해를 가질 수 있게 되었습니다. 감사합니다!

2022-03-06 11:40 UTC, ulimy commented on src/main/java/domain/Result.java
>  	private Map<ResultStatics, Integer> results;
잘 작성했다고 말해주시니 마음이 놓이네요!
Result, LottoMachine 모두 생성시점에서 모든 필드가 초기화되고, 추후 변경은 일어나지 않도록 구현함으로써 불변객체가 되도록 리팩토링 해보았습니다.
이를 적용해보면서 가장 어려웠던 점은 각 개념의 선택기준이었습니다. 어느 시점에서 깊은 복사가 필요한지, 혹은 충분히 안전하다 판단되어 굳이 복사가 필요하지 않은지 또한 여러가지 복사 방법 중 어떤 것을 택하는 것이 적절한지(new, copyOf,unmodifiable 등) 을 결정하는 것이 가장 어렵게 느껴졌습니다.

2022-03-07 10:54 UTC, jnsorn approved these changes
안녕하세요, 아리! 피드백 정말 잘 반영해주셨네요. 😃

1단계에서 많은 이야기를 못나눈만큼 2단계에서 많은 이야기를 나눈 것 같아요. 늘 제가 제안한 아이디어에 아리만의 생각을 말해주어서 저도 더 재미있게 얘기 나눌 수 있었습니다. 또, 많이 배웠구요! 충분히 코드가 깔끔해진 것 같아서 로또 미션은 여기서 마무리하도록 할게요! 코멘트 살짝 남겨두었는데 확인해주시고, 궁금하거나 얘기 나누고 싶은 내용 있으면 언제든 DM주세요! 수고하셨어요. 👍🏼

2022-03-07 10:54 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +		.collect(toMap(identity(), LottoNumber::new));
stream 사용에 능숙해보이시네요 👍🏼

2022-03-07 10:54 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +	}
private 생성자와 캐싱된 값 반환까지 최고네요! 💯

2022-03-07 10:54 UTC, jnsorn commented on src/test/java/domain/LottoTicketPurchaseTest.java
> +public class LottoTicketPurchaseTest {
새로운 친구가 생겼네요!😎 아마 `LottoTicket`에 대한 테스트가 많아지면서 `LottoTicketResultTest`와 `LottoTicketPurchaseTest` 테스트로 나눠진 것 같아요. 이렇게 분리하면 하나의 테스트 클래스가 가벼워지는 장점이 있지만 반대로 `LottoTicket`에 대한 단위테스들이 흩어져있어 찾기 어려울 수 있어요.

보통 저는 하나의 클래스에 하나의 테스트 클래스를 생성합니다. 하나의 파일에 테스트가 너무 많은 것 같다는 생각이 들면, `@ValueSource`,`@CsvSource`,`@MethodSource`등을 이용해서 중복을 제거하면 어떨까요? 🙂

그래도 많다면 해당 객체가 너무 많은 책임을 가지고 있는 건 아닌지 생각해볼 수도 있어요 ㅎㅎ

2022-03-07 10:54 UTC, jnsorn commented on src/main/java/domain/LottoMachine.java
> +	}
> 잘 작성했다고 말해주시니 마음이 놓이네요! Result, LottoMachine 모두 생성시점에서 모든 필드가 초기화되고, 추후 변경은 일어나지 않도록 구현함으로써 불변객체가 되도록 리팩토링 해보았습니다.
> 이를 적용해보면서 가장 어려웠던 점은 각 개념의 선택기준이었습니다. 어느 시점에서 깊은 복사가 필요한지, 혹은 충분히 안전하다 판단되어 굳이 복사가 필요하지 않은지 또한 여러가지 복사 방법 중 어떤 것을 택하는 것이 적절한지(new, copyOf,unmodifiable 등) 을 결정하는 것이 가장 어렵게 느껴졌습니다.

이 부분은 저도 늘 고민되는 부분이에요. ㅎㅎ 호출하는 곳이 값을 변경하지 않을 것이라고 확신할 수 있을지, 성능은 괜찮을지 등등 다양한 고민을 해야하죠. 그래도 지금 코드에서는 잘 작성해주셨다는 생각이 들어요. 💯

`LottoTicket`의 경우 불변 객체로 만들었기 때문에 `getLottoTickets()`를 호출하는 외부에서 `LottoTicket`을 수정할 수 있는 방법이 없고, 그렇다면 굳이 깊은 복사가 아닌 `Collections.unmodifiableList()`로도 충분한거죠!

아마 미션을 더 진행하실 수록 이런 부분은 익숙해지실거예요. 선택해야하는 순간이 올 때 잘 선택하기 위해서, 지금은 각 복사 방법이 어떤식으로 복사를 하고 어떤 경우에 필요한지를 학습해두시면 좋을 것 같습니다!

2022-03-07 10:54 UTC, merged

2022-03-11 03:40 UTC, ulimy commented on src/main/java/domain/LottoNumber.java
> +		.collect(toMap(identity(), LottoNumber::new));
다른 크루의 도움이었습니다..ㅎ 감사합니다 :)

2022-03-11 03:40 UTC, ulimy commented on src/main/java/domain/LottoNumber.java
> +	}
감사합니다!!

2022-03-11 03:42 UTC, ulimy commented on src/test/java/domain/LottoTicketPurchaseTest.java
> +public class LottoTicketPurchaseTest {
단위테스트가 흩어진다는 단점.. 인정합니다. @MethodSource는 또링 덕분에 처음 알게되었습니다. 적용해보겠습니다!

2022-03-11 03:43 UTC, ulimy commented on src/main/java/domain/LottoMachine.java
> +	}
선택해야하는 순간이 올 때 잘 선택하기 위해서 충분히 학습해두기! 너무 좋은 이야기입니다. 감사합니다!