[2단계 - 로또(수동)] 디우(김동규) 미션 제출합니다.
woowacourse/java-lotto pull request #436
Opened 2022-03-01 11:01 UTC by tco0427

안녕하세요 닉! 디우입니다..ㅎㅎ 이번 피드백도 잘 부탁드립니다!

---

2단계를 구현하며 가장 크게 고인되었던 부분은 `수동`이라는 기능이 추가되면서 책임을 어느쪽에 부여하는게 적절한가였습니다..
우선 수동과 자동 로또 구매 개수를 계산하고 검증하는 책임은 LottoPurchaseMoney 쪽에 부여하였는데요. 이러한 과정에서 calculate() 라는 메소드의 기능이 단순 totalCount 계산에서 자동으로 구매한 로또 티켓의 개수를 계산하도록 변경하게 되었습니다.
다음으로는 LottoMachine에서 purchase() 할 때 LottoPurchaseMoney 뿐 아니라 수동으로 생성한 List<LottoTicket> 을 함께 받도록 수정하게 되었습니다.
그러면서 테스트 코드도 다음과 같이 변경하게 되었는데요,
```java
@DisplayName("로또 티켓의 갯수를 반환한다.")
    @Test
    void checkLottoCount() {
        // given
        int lottoCount = 14;
        LottoTicketGenerator lottoTicketGenerator = new AutoLottoTicketGenerator();

        // when
        LottoTickets lottoTickets = new LottoTickets(lottoCount, new ArrayList<>(0), lottoTicketGenerator);

        // then
        assertThat(lottoTickets.totalCount()).isEqualTo(lottoCount);
    }
```
이 때 LottoTickets 의 생성자로 현재 `new ArrayList<>(0)` 을 전달해주고 있는데 이것이 적절한지는 의문이 듭니다...제가 생각할 때 현재 LottoTickets의 생성자를 직접 로 null이 전달되는 경우는 없기 때문에 null에 대한 검증을 하는 코드를 두지 않았는데, 테스트 코드에서 `new ArrayList<>(0)` 을 전달하는 부분이 마음에 걸립니다...

---

1단계 마지막 피드백에서 말씀해주신 다음의 말씀이 잘 이해가 가지 않습니다...
```
이 부분에서 고민이 필요해 보여요.
일단 1 ~ 45의 로또 숫자를 미리 생성해서 캐싱해놓는다는 관점에서는 잘 하셨어요 👍
다만 그렇다면 다음 사항들을 추가로 고려해서 리팩토링 해보면 좋을 듯 해요.

LottoNumber를 생성하려는 경우, 이미 생성되어 캐싱된 인스턴스가 있을 경우 새로 만들지 않고 기존 인스턴스를 반환하도록 한다.
혹은 LottoNumber 내부에서가 아니라, LottoNumber 생성을 전담하는 Pool을 별도로 만들어도 좋다.
캐싱하는 자료구조가 List인데, 더 나은 자료구조는 없을까?
```

LottoNumber를 생성하려는 경우, 이미 생성되어 캐싱된 인스턴스가 있을 경우 새로 만들지 않고 기존 인스턴스를 반환하도록 한다. -> 싱글톤 패턴의 적용이라고 이해하면 될까요..?? 하지만 LottoNumber 생성시 인자로 int 값을 받고 이를 상태로 가진다는 점에서 어떻게 싱글톤을 적용해야할지 모르겠습니다...ㅠㅠ

LottoNumber 내부에서가 아니라, LottoNumber 생성을 전담하는 Pool을 별도로 만들어도 좋다. -> 혹시 참고할만한 자료가 있을까요..Pool을 별도록 만든다는 말씀이 어떤 말씀이신지 모르겠습니다..

---

따끔한 피드백 부탁드립니다..!!

2022-03-02 03:37 UTC, wbluke requested changes
안녕하세요 디우~ 2단계도 잘 구현해 주셨네요 ㅎㅎ
질문 주신 부분 코멘트 다시 좀 더 상세히 남겼는데요, 확인 부탁드릴게요 🙂

2022-03-02 03:37 UTC, wbluke commented on src/test/java/lotto/domain/LottoTicketsTest.java
> +        LottoTickets lottoTickets = new LottoTickets(lottoCount, new ArrayList<>(0), lottoTicketGenerator);
> 이 때 LottoTickets 의 생성자로 현재 `new ArrayList<>(0)` 을 전달해주고 있는데 이것이 적절한지는 의문이 듭니다...제가 생각할 때 현재 LottoTickets의 생성자를 직접 로 null이 전달되는 경우는 없기 때문에 null에 대한 검증을 하는 코드를 두지 않았는데, 테스트 코드에서 `new ArrayList<>(0)` 을 전달하는 부분이 마음에 걸립니다...

오호 어떤 이유에서 마음에 걸리는건지 궁금하네요.
수동 티켓 없이 totalCount()를 검증하고 싶다면 위와 같이 진행하면 되고, 수동 티켓도 포함해서 totalCount()를 검증하고 싶다면 티켓을 생성해서 넣어주면 되고요 ㅎㅎ
참고로 0 빼고 `new ArrayList<>()`만 해도 됩니다 :)

2022-03-02 03:37 UTC, wbluke commented on src/test/java/lotto/domain/LottoTicketsTest.java
>          assertThat(lottoTickets.totalCount()).isEqualTo(lottoCount);
그리고 지금 같은 경우는 when절에 있는 LottoTickets 생성 까지가 given절이고,
lottoTickets.totalCount()가 when절이어야 합니다.
실수셨던거 같긴 한데, 항상 검증의 대상이 되는 행위가 when절에 위치해야 한다는 점 잊지마세요 ㅎㅎ
(그래서 보통 when절은 한줄로 끝나는 경우가 대부분입니다.)

다른 테스트도 비슷한 경우가 있는지 한번 체크해주세요 :)

2022-03-02 03:37 UTC, wbluke commented on src/main/java/lotto/domain/LottoResult.java
> +    }
음 외부에서 넣어준 sum에 더하기보다, 그냥 당첨횟수만큼 prizeMoney를 곱해서 반환하면 되지 않을까요? 
그럼 파라미터 수나 로직도 더 간단해질 듯 합니다 :)

2022-03-02 03:37 UTC, wbluke commented on src/main/java/lotto/domain/LottoResult.java
> +    }
```java
int totalPrizeMoney = ranks.keySet()
        .stream()
        .mapToInt(Rank::getPrizeMoney)
        .sum();
```

엇 이 코드는 어디가고 다시 회귀했나요 ㅋㅋ

2022-03-02 03:37 UTC, wbluke commented on README.md
(PR에 LottoNumber 변경사항이 없어서 여기에 남겨요)

> 1단계 마지막 피드백에서 말씀해주신 다음의 말씀이 잘 이해가 가지 않습니다...
> 
> ```md
> 이 부분에서 고민이 필요해 보여요.
> 일단 1 ~ 45의 로또 숫자를 미리 생성해서 캐싱해놓는다는 관점에서는 잘 하셨어요 👍
> 다만 그렇다면 다음 사항들을 추가로 고려해서 리팩토링 해보면 좋을 듯 해요.
> 
> LottoNumber를 생성하려는 경우, 이미 생성되어 캐싱된 인스턴스가 있을 경우 새로 만들지 않고 기존 인스턴스를 반환하도록 한다.
> 혹은 LottoNumber 내부에서가 아니라, LottoNumber 생성을 전담하는 Pool을 별도로 만들어도 좋다.
> 캐싱하는 자료구조가 List인데, 더 나은 자료구조는 없을까?
> ```
> 
> LottoNumber를 생성하려는 경우, 이미 생성되어 캐싱된 인스턴스가 있을 경우 새로 만들지 않고 기존 인스턴스를 반환하도록 한다. -> 싱글톤 패턴의 적용이라고 이해하면 될까요..?? 하지만 LottoNumber 생성시 인자로 int 값을 받고 이를 상태로 가진다는 점에서 어떻게 싱글톤을 적용해야할지 모르겠습니다...ㅠㅠ
> 
> LottoNumber 내부에서가 아니라, LottoNumber 생성을 전담하는 Pool을 별도로 만들어도 좋다. -> 혹시 참고할만한 자료가 있을까요..Pool을 별도록 만든다는 말씀이 어떤 말씀이신지 모르겠습니다..

아이구 제가 다른 분들 피드백과 같이 드리다보니 너무 집약적으로 이야기를 했나봅니다. 미안해요!
Pool이니 뭐니 이런 용어들은 일단 제외하고 본질적인 부분만 먼저 이야기를 하도록 할게요.

현재는 `new LottoNumber(1)` 하면 매번 새로운 인스턴스를 만들어주고 있어요.
그런데 과연 매번 새로운 인스턴스를 만들 필요가 있을까요?
```java
LottoNumber number1 = new LottoNumber(1);
LottoNumber number2 = new LottoNumber(1);
```
number1과 number2가 의미하는 것은 같은 로또숫자 1번인데, 인스턴스는 각각 생성되고 있어요.
그렇다면 **한번 생성된 인스턴스를 어딘가에 저장해두고, 다음번에 동일한 요청이 왔을 때 기존에 저장해놓은 인스턴스를 반환해주면 어떨까?** 라는 질문이에요. 
이를 캐싱이라고 표현할게요. (싱글턴과는 의미가 달라요 ㅎㅎ)

- 캐싱한 인스턴스를 어디에 보관하면 좋을까요? LottoNumber 자체에 static으로 보관해도 좋고, 별도의 클래스로 빼도 좋아요.
- 생성자는 말그대로 인스턴스를 만들어주는 도구라서 생성자 자체에서 해당 기능을 제공하기는 어려울 것이고, 정적 팩토리 메서드를 사용해 보세요.

고민해보시고 잘 모르겠으면 DM으로 말씀주세요. 추가 설명 드릴게요 :)

2022-03-02 05:56 UTC, tco0427 commented on src/test/java/lotto/domain/LottoTicketsTest.java
> +        LottoTickets lottoTickets = new LottoTickets(lottoCount, new ArrayList<>(0), lottoTicketGenerator);
위와 같은 형태의 테스트 코드를 처음 작성하다보니 어색하다는 느낌이 들었던 것 같아요..!! (null을 주는 경험이 더 많았다 보니 그런 것 같습니다.ㅎㅎ) new ArrayList<>() 의 생성자로 0을 준 이유는 initialCapacity가 0임을 명시적으로 하고 싶어서 0을 붙여줬습니다!!

2022-03-02 05:58 UTC, tco0427 commented on src/test/java/lotto/domain/LottoTicketsTest.java
>          assertThat(lottoTickets.totalCount()).isEqualTo(lottoCount);
항상 given 과 when 의 경계가 모호하다는 생각을 했던 것 같아요..!! 그런데 닉의 `검증의 대상이 되는 행위`가 when절에 위치해야한다는 말씀을 들으니 조금 더 명확하게 이해가 됩니다..!! 다른 단위 테스트 부분들도 검토해보고 수정해보겠습니다!

2022-03-02 06:07 UTC, tco0427 commented on src/main/java/lotto/domain/LottoResult.java
> +    }
동의합니다..!! 메소드 추출(cmd + opt + m) 을 이용하다보니 코드에서 불필요한 매개변수등이 포함되게 된 것 같습니다..이런 단축키 사용 이후에 항상 한 번 더 확인하는 습관을 들여야하는데..앞으로 좀 더 주의하도록 하겠습니다!!

2022-03-02 06:08 UTC, tco0427 commented on src/main/java/lotto/domain/LottoResult.java
> +    }
맞는 말씀이십니다...ㅎㅎ 위의 getSum() 메소드를 수정하면서 getTotalPrizeMoney() 도 수정해보았습니다! 스트림을 활용하여 보다 가독성 있게 수정해보겠습니다!

2022-03-02 08:34 UTC, tco0427 commented on README.md
천천히 읽어보니 이해가 되어 코드에 반영해보았습니다..!!

```java
    private LottoNumber(int number) {
        this.number = number;
    }

    public static LottoNumber getInstance(int number) {
        validateNumberBoundary(number);

        LottoNumber lottoNumber = LOTTO_TOTAL_NUMBERS.get(number - 1);

        return Objects.requireNonNullElseGet(lottoNumber, () -> new LottoNumber(number));
    }
```

또한 동일 인스턴스인지에 대한 검사를 진행하는 단위 테스트 코드를 LottoNumberTest 에 추가해보았습니다.

확인 부탁드립니다!!😃 감사합니다!!

2022-03-03 12:39 UTC, wbluke requested changes
캐싱 전략 잘 적용해 주셨네요 ㅎㅎ
다만 아직 조금 더 개선할 부분이 보여요.
한번 더 확인 부탁드려요 🙂

2022-03-03 12:39 UTC, wbluke commented on src/main/java/lotto/domain/LottoResult.java
> +        return result;
음 이거 지난번 피드백에서 더 간단하게 하기로 하지 않았나요?
```java
Integer count = ranks.get(rank);
return count * rank.getPrizeMoney();
```

2022-03-03 12:39 UTC, wbluke commented on src/main/java/lotto/domain/vo/LottoNumber.java
> +    public static LottoNumber getInstance(int number) {
getInstance()는 보통 싱글턴 패턴에서 유일한 인스턴스를 반환할 때 사용하는 네이밍이고,
LottoNumber는 싱글턴이 아니니 적당한 정적 팩토리 메서드로 생각해서 네이밍해보면 좋겠어요. (ex. of())

2022-03-03 12:39 UTC, wbluke commented on src/main/java/lotto/domain/vo/LottoNumber.java
> +        LottoNumber lottoNumber = LOTTO_TOTAL_NUMBERS.get(number - 1);
잘 하셨네요! 👍 
이제 좀 더 개선해 봅시다.
로또숫자를 의미하는 number가 List의 index 역할도 하고 있어요.
의미를 추가적으로 해석해야할 뿐더러, 로또숫자 리스트가 불연속적이거나 형태가 변경된다면 굉장히 위험할 수도 있는 코드입니다.
어떻게 하면 좋을까요? :)

힌트) 더 적절한 자료구조는 없을까?

2022-03-03 12:39 UTC, wbluke commented on src/test/java/lotto/domain/vo/LottoNumberTest.java
> +        assertThat(sameInstance1).isEqualTo(sameInstance2);
음 동일 인스턴스를 검증하기 위한 테스트인데, 검증 방법이 잘못되었어요.
한번 다시 고민해 보셔요 :)

2022-03-03 13:30 UTC, tco0427 commented on src/main/java/lotto/domain/LottoResult.java
> +        return result;
아하..위와 같은 말씀이셨군요..
`5000원 당첨 2번일 때 반복해야하네` 라는 생각으로 로직을 변경하면서 `반복`에 너무 집착해서 닉이 말씀해주신 내용을 제대로 이해하지 못한 것 같습니다...스스로를 반성하게 되는 피드백이었습니다! 감사합니다!!

2022-03-03 13:33 UTC, tco0427 commented on src/main/java/lotto/domain/vo/LottoNumber.java
> +    public static LottoNumber getInstance(int number) {
이펙티브 자바를 확인해보니 getInstance 라는 네이밍은 `매개변수로 명시한 인스턴스를 반환하지만 같은 인스턴스임을 보장하지는 않는다.` 라고 명시되어 있네요.. of는 `여러 매개변수를 받아 적합한 타입의 인스턴스를 반환하는 집계 메소드`라고 명시되어있습니다.
저는 개인적으로 `매개변수를 하나 받아서 해당 타입의 인스턴스를 반환하는 형변환 메소드` 를 의미하는 from이 가장 적절하다고 생각되어 해당 네이밍으로 수정해보도록 하겠습니다.

2022-03-03 13:41 UTC, tco0427 commented on src/test/java/lotto/domain/vo/LottoNumberTest.java
> +        assertThat(sameInstance1).isEqualTo(sameInstance2);
isEqualsTo 는 실제 값이 지정된 값과 같은지를 검증합니다. 따라서 말씀해주신대로 동일 인스턴스인지를 검증하는데는 적절하지 못한 것 같습니다...!!
isSameAs 와 isNotSameAs를 이용하면 제가 원하던 테스트를 진행할 수 있을 것 같습니다. (Verifies that the actual value is the same as the given one, ie using == comparison.)
수정하도록 하겠습니다.

2022-03-03 13:54 UTC, tco0427 commented on src/main/java/lotto/domain/vo/LottoNumber.java
> +        LottoNumber lottoNumber = LOTTO_TOTAL_NUMBERS.get(number - 1);
아하..!! 이전에는 더 적절한 자료구조가 없을까요? 라는 질문을 받았을 때 '왜 닉께서 이런 질문을 하셨을까...' 감조차 안잡혔던 것 같습니다.
그런데 직접 getInstance() 메소드를 구현하면서 LOTTO_TOTAL_NUMBERS.get() 을 사용하면서 스스로 '과연 적절한 코드일까?' 생각은 들었지만 우선은 그냥 사용했었는데요(코드에 적절한 이유가 없었습니다..ㅠㅠ 반성합니다..)
닉께서 말씀해주시는 `의미를 추가적으로 해석해야할 뿐더러, 로또숫자 리스트가 불연속적이거나 형태가 변경된다면 굉장히 위험할 수도 있는 코드입니다.` 다음 말씀을 듣고, Map 자료구조를 사용하는게 더욱 적절하겠다 라는 결론을 낼 수 있었습니다!! 감사합니다~_~

2022-03-04 11:58 UTC, wbluke approved these changes
로또 미션 고생 많으셨어요! 👍 
다음 미션도 화이팅입니다 🙂

2022-03-04 11:58 UTC, wbluke commented on src/test/java/lotto/domain/vo/LottoNumberTest.java
> +        assertThat(sameInstance1).isSameAs(sameInstance2);
잘 캐치하셨네요 ㅎㅎ
실제로 isEqualTo()와 isSameAs() 둘 다를 놓고, LottoNumber의 equals 메서드에 디버거 포인트 걸어놓고 돌리면 차이를 명확하게 확인하실 수 있으니 한번 해보셔요 :)

2022-03-04 11:59 UTC, merged