[2단계 - 로또(수동)] 알렉스(이영환) 미션 제출합니다.
woowacourse/java-lotto pull request #453
Opened 2022-03-02 08:06 UTC by yxxnghwan

안녕하세요 또링! 1차 미션에서 섬세하게 피드백 해주셔서 너무너무 감사합니다😇
또링이 리뷰를 너무 잘 봐주시니 더 열심히 해야겠다는 자극을 받았어요🔥
우테코 시작하고 나서 저번 피드백과 이번 PR사이에 배운 것들이 가장 많은 것 같아요.

고친 점은 일단 

- 저번에 불편했던 View설계를 단순화 했고, 컨트롤러도 수정했습니다. View는 피드백 주신 대로 싱글턴으로 구현했습니다.
- 몇몇 클래스에서 로직이 꽤 복잡한 생성자를 가지고 있었는데요, 이런 클래스는 정적 팩토리 메서드로 인스턴스화 할 수 있게 변경했습니다.
- 그리고 몇몇 상수를 public으로 두었는데요, 저번 또링의 피드백에 테스트 코드에서 프로덕션의 상수를 사용하신다고 말해주셨는데 꼭 상수가 private이 아니어도 된다고 생각해보니까 중복되는 숫자들을 적절한 한 클래스에 넣어두고 public으로 사용하는게 관리 포인트를 줄일 수 있을 것 같아서 그렇게 했습니다.
- 접근제어자와 메서드 순서는 사람마다 너무 컨벤션이 달라서 어떻게 하는게 좋을지 모르겠네요 ㅠㅠ 일단 저는 `생성자 -> 클래스 함수 -> 메서드 -> equals, hashCode, toString -> getter, setter` 이렇게 생각하고 있는데요 또링은 순서를 어떻게 두시는걸 선호하시나요?

이번에도 잘 부탁드릴게요 또링!

2022-03-02 08:14 UTC, yxxnghwan commented on src/main/java/domain/Money.java
> +public class Money {
1단계 요구사항에 모든 원시값을 포장하라는 요구사항이 있었네요,, 1단계에서 놓친 것 같아 2단계에서 추가했습니다

2022-03-02 08:14 UTC, yxxnghwan commented on src/main/java/domain/LottoGame.java
> +    }
LottoGame에게 수익률을 구하도록 구현했는데요 이 수익률 구하는 부분을 WinningResult에게 넘겨야할지 고민입니다. 만약 WinningResult에게 넘긴다면 WinnigResult가 총 구매 금액을 알고 있어야 하는데요 당첨 결과를 나타내는 클래스는 당첨만 알고 있으면 되지 않나 하는 고민을 하고 있습니다. 또링은 어떻게 생각하시나요?

2022-03-03 02:42 UTC, jnsorn requested changes
안녕하세요, 알렉스! 이번에도 잘 구현해주셨네요. :) 
전체적으로 코드가 깔끔하다는 느낌이 들었어요. 테스트코드도 놓치지 않고 잘 추가해주셨구요. 👍🏼 
추가로 개선되면 좋을 부분에 코멘트 달아두었으니 확인해보시고 다시 요청 주세요.

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/controller/LottoController.java
> +            purchaseMoney -= selfPurchaseCount * LottoTicket.TICKET_PRICE;
😲

<img width="259" alt="image" src="https://user-images.githubusercontent.com/31095063/156474891-880afc16-b69d-4345-bc63-e6e0bbc2000d.png">

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/controller/LottoController.java
> +    private final NumberGenerateStrategy generateStrategy = new RandomNumberGenerateStrategy();
controller가 해당 변수를 갖고 있어야 하나요?

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/LottoTickets.java
> +    }
Money에 대한 검증이 LottoTickets에 있어요. 더 적절한 위치로 이동해볼까요?

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/LottoTickets.java
> +        int autoPurchaseCount = autoPurchaseMoney.getAmount() / LottoTicket.TICKET_PRICE;
Money의 값을 꺼내오지 않고 물어보면 어떨까요?

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/controller/LottoController.java
>  public class LottoController {
> 접근제어자와 메서드 순서는 사람마다 너무 컨벤션이 달라서 어떻게 하는게 좋을지 모르겠네요 ㅠㅠ 일단 저는 생성자 -> 클래스 함수 -> 메서드 -> equals, hashCode, toString -> getter, setter 이렇게 생각하고 있는데요 또링은 순서를 어떻게 두시는걸 선호하시나요?

저도 알렉스와 오버라이딩 메서드 ↔️ getter, setter 제외하고는 동일해요. :) 

```
1. 상수
2. 클래스 변수
3. 인스턴스 변수
4. 생성자
5. 팩토리 메서드
6. 일반 메서드
   6-1. public - protected - private 순으로 작성하지만, 관련 있는 메서드 끼리는 함께 위치시키는 것이 좋음
          (public A에서 호출하는 private B함수는 A다음에 위치)
7. getter, setter
8. toString, equals, hashCode 

```

사실 위 두 메서드는 어떤 순서를 가지든 큰 상관은 없는 것 같아요. 다만, 가독성을 위해 일관성을 지키는 것은 중요합니다. :) 
예를 들어, _일반 메서드들은 호출한 순으로 정렬한다. 함수가 많아지면 주요 로직(public) 메서드를 상단에 위치시킨다_ 등 어떻게 하면 읽는 사람이 흐름을 잘 파악할 수 있을지 늘 고민해보세요! 물론 가장 중요한 건 페어/팀의 컨벤션입니다. 😎 (이미 잘 알고 계시죠?ㅎㅎ)

그런 의미로 전체적인 메서드 순서를 일관성있게 고쳐봅시다!

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/view/InputView.java
> +    }
> 저번에 불편했던 View설계를 단순화 했고, 컨트롤러도 수정했습니다. View는 피드백 주신 대로 싱글턴으로 구현했습니다.

싱글턴으로 구현하면서 중요한 포인트를 놓치지 않으셨군요! 💯

여기서 고민해보면 좋을 포인트! 
💡InputView는 static 클래스가 적절할까 singleton 패턴이 적절할까?

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/WinningResult.java
> +    }
> 몇몇 클래스에서 로직이 꽤 복잡한 생성자를 가지고 있었는데요, 이런 클래스는 정적 팩토리 메서드로 인스턴스화 할 수 있게 변경했습니다.

생성자를 private으로 막아두셨네요. 💯

정적 팩토리 메서드로 구현하면서 생성자로 구현 했을 때와 어떤 차이를 느끼셨는지 궁금해요! 🧐

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/view/InputView.java
> +    public static final String INPUT_SELF_TICKET_COUNT_MESSAGE = "수동으로 구매할 로또 수를 입력해 주세요.";
순서, 개행, 네이밍 컨벤션 확인 🔍

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/LottoGame.java
> +    }
꼼꼼한 검증 👏🏻 너무 좋아요! 하지만 왜 인스턴스 변수에 대해 검증을 하게 되었을지 생각해볼까요? 🤔
`Hint. 객체 생성 시점에 필요한 것들을 전달해주면 불완전한 상태로 생성되는 것을 막을 수 있어요.`

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/LottoTicket.java
> +    }
잘 생성 되는지 테스트를 추가해볼까요?

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/WinningResult.java
> +    public int sumTotalReturn() {
테스트 추가 🔍

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/WinningResult.java
> +        Integer winningPrizeCount = result.get(winningPrize) + COUNT_UNIT;
Map의 `getOrDefault()`에 대해서도 알아볼까요?

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/WinningTicket.java
> +    private final Set<LottoNumber> winningNumbers;
이미 잘 만들어진 객체를 이용할 수 있을 것 같아요! 객체들을 조합해 `WinningTicket`을 만들어봐요 :)

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/WinningTicket.java
> +    public int compareMatchCount(LottoTicket lottoTicket) {
테스트 추가 🔍

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/WinningTicket.java
> +                .count();
(참고) Set에 `retainAll()`이라는 메서드도 있어요.

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/WinningTicket.java
> +    public boolean isMatchBonusNumber(LottoTicket lottoTicket) {
테스트 추가 🔍

2022-03-03 02:42 UTC, jnsorn commented on src/test/java/domain/LottoTicketsTest.java
> +    }
돈에 대한 테스트 아닌가요? 어쩌다 이 테스트코드가 LottoTickets에 위치하게 되었을지 생각해봐요 🤔

2022-03-03 02:42 UTC, jnsorn commented on src/test/java/domain/MoneyTest.java
> +                .hasMessage(Money.NOT_POSITIVE_ERROR_MESSAGE);
> Alex: 그리고 몇몇 상수를 public으로 두었는데요, 저번 또링의 피드백에 테스트 코드에서 프로덕션의 상수를 사용하신다고 말해주셨는데 꼭 상수가 private이 아니어도 된다고 생각해보니까 중복되는 숫자들을 적절한 한 클래스에 넣어두고 public으로 사용하는게 관리 포인트를 줄일 수 있을 것 같아서 그렇게 했습니다.

--- 
제가 지난 번 리뷰에서 아래와 같이 말씀드렸었는데요. 이 부분은 조금 더 생각해보면 좋을 것 같아요.

> 테스트 에러메세지 비교 시 프로덕션의 메세지를 사용하면 관리 포인트가 줄어든다. 에러 메세지를 테스트 하는 경우는 예외가 발생했을 때 왜 발생했는지에 대한 검증을 하는 것이지, 텍스트 하나하나를 비교해보자는 뜻은 아니다.

제가 리뷰를 하면서 테스트의 유지보수 관점에서만 생각하고 TDD 관점에서는 생각하지 못했어요. 😂
TDD로 프로그램을 작성한다면, 에러 메세지가 변경 시 당연히 테스트도 변경 되는 게 자연스러운 것 같습니다.

1. 에러메세지 변경 요구사항
2. 테스트코드에서 해당 에러 메세지를 수정
3. 실패하는 테스트 확인
4. 프로덕션의 에러 메세지 수정
5. 성공하는 테스트 확인

--- 

추가로, 도메인에 대한 상수값이 여러 클래스에서 중복으로 사용되고 있다는 것은 결국 도메인에서 관리되어야 할 값들이 여러 곳에서 사용 되고 있다는 것을 의미해요. 예를 들어 `LottoTicket.TICKET_PRICE`는 현재 아래와 같이 사용하고 있습니다.

`LottoController` 자동로또 금액 계산
`LottoGame` 입력 금액 계산
`LottoTickets` 입력 금액의 유효성 검증 

이 행위들이 어떤 객체와 관련이 있는지 고민해보면 좋을 것 같아요. 😃

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/LottoGame.java
> +    }
당첨 결과를 역할을 어떻게 볼 것인지가 관건일 것 같아요 :) 
`당첨 결과는 단지 당첨 결과일 뿐`이라고 한다면 알렉스처럼 생각할 수도 있고, `당첨 결과는 수익률까지 알고 있어야 한다`라고 생각한다면 로직이 안으로 들어갈 수도 있을 것 같아요. `LottoGame도 WinningResult의 역할도 아닌 것 같다`라고 한다면 결과 통계에 대한 새로운 객체가 만들어질수도 있을 것 같구요! 😃

2022-03-03 02:42 UTC, jnsorn commented on src/main/java/domain/strategy/RandomNumberGenerateStrategy.java
> +            .collect(Collectors.toList());
💯

2022-03-04 19:22 UTC, yxxnghwan commented
안녕하세요 또링! 섬세하게 케어해주셔서 너무 감사합니다!
밤 늦게 dm드렸는데도 잘 알려주셔서 너무 감동 받았어요😁

dm으로 불변에 대한 얘기를 해주셔서 혹시나 제가 불변이어야 하는 걸 불변으로 만들지 않았나 싶어 쭉 봤는데요,
혹시나 제가 복사에 실수를 하고 있나 찾아봤는데 처음엔 제가 아는 지식으로는 찾을 수 없었습니다.
찝찝해서 좀 더 알아본 결과 `Collections.unmodifiableXX`는 새로 받은 주소가 기존 컬렉션과 상관 관계가 있어서
새로 받은 곳에서 수정은 막아주지만, 원본 컬렉션을 변경하면 unmodifiableXX로 생성된 컬렉션은 영향을 받는다는걸 알게 되었습니다.
저는 방어적 복사를 하고 있다고 생각했고 컬렉션이 다루는 클래스도 불변으로 설계된 클래스여서 불변이라고 생각했는데, 원본 컬렉션과 관계가 끊어지지를 않았군요.
그래서 기존 `Collections.unmodifiableXX`을 사용하던 것들을 `copyOf`로 변경했어요.
또링 덕분에 하나 더 배울 수 있었습니다.

혹시나 제가 아직도 뭔가 잘못 알고 있다면 알려주세요...

그럼 이번에도 잘 부탁드립니다 또링!🙏

2022-03-04 19:29 UTC, yxxnghwan commented on src/main/java/domain/LottoGame.java
> +    }
기존 LottoGame이 너무 많은 일을 해서 일을 분리시켰더니, 
제가 LottoGame이 너무 아무 일도 안하는 것 같이 느껴져서 뭐라도 시켜야겠다는 생각이 있었던 것 같아요.
저는 결과를 나타내는 클래스가 수익률을 내는게 더 자연스럽게 느껴지는 것 같아 결국 LottoGame이 역할을 하지 않도록 했습니다.
대신 LottoGame이 상금 조건 전략을 가지도록 하여 결과를 얻으려면 LottoGame에 물어보게 하는 식으로 역할을 주었어요.
도메인 관점에서 바라보니 LottoGame이 번호 생성 전략, 상금 전략을 가지고 각 요청을 받아 결과를 알려주는게 자연스럽겠다는 생각을 했습니다.

2022-03-04 19:30 UTC, yxxnghwan commented on src/main/java/controller/LottoController.java
> +            purchaseMoney -= selfPurchaseCount * LottoTicket.TICKET_PRICE;
`selfPurchaseCount`를 객체로 포장하면서 문제를 해결했습니다!

2022-03-04 19:30 UTC, yxxnghwan commented on src/main/java/controller/LottoController.java
> +    private final NumberGenerateStrategy generateStrategy = new RandomNumberGenerateStrategy();
해당 변수는 LottoGame이 가지는게 자연스러울 것 같아서 LottoGame이 가지도록 했어요!

2022-03-04 19:31 UTC, yxxnghwan commented on src/main/java/domain/LottoTickets.java
> +    }
DM에서 말씀드린대로 LottoMoney로 클래스명을 수정하고 로또라는 도메인에 맞는 검증을 하도록 했습니다!

2022-03-04 19:37 UTC, yxxnghwan commented on src/main/java/domain/LottoTickets.java
> +        int autoPurchaseCount = autoPurchaseMoney.getAmount() / LottoTicket.TICKET_PRICE;
LottoMoney가 직접 계산해서 주는걸로 변경했습니다!

2022-03-04 19:40 UTC, yxxnghwan commented on src/main/java/controller/LottoController.java
>  public class LottoController {
꼼꼼히 순서 맞춰봤습니다! 또링이랑 선호하는 순서가 비슷하네요!

2022-03-04 19:45 UTC, yxxnghwan commented on src/main/java/view/InputView.java
> +    }
InputView와 OutputView는 상태를 가지는 것이 아니기에 굳이 인스턴스화를 할 필요가 없는 것 같습니다!
싱글톤 패턴으로 만들면 가장 큰 장점은 인터페이스 구현이 가능하다는 것으로 알고 있는데, 
저는 이미 인터페이스로 하려다 실패를 했기에..🤣

두 클래스는 스태틱 클래스로 만들었습니다.

2022-03-04 19:49 UTC, yxxnghwan commented on src/main/java/domain/WinningResult.java
> +    }
저번 리뷰요청에는 그냥 관용적인 메서드 네임을 부여했지만, 이번엔 좀 더 의미를 파악할 수 있도록 정적 팩토리 메서드 이름을 수정했습니다. 정적 팩토리 메서드로 구현한다면 원하는 이름을 붙여줘서 의미파악에 도움을 줄 수 있다는 장점이 있는 것 같아요.

정적 팩토리 메서드로 구현하고자 한 이유는 생성자가 들어온 매개변수로 뭔가 다른 작업을 거쳐서 객체 생성을 완성하는 것이 생성자의 역할을 초과하는 것이라고 생각되어서 그렇게 구현한 것인데요, 또링은 어떤 경우에 정적 팩토리 메서드로 객체를 생성하시나요?

2022-03-04 19:49 UTC, yxxnghwan commented on src/main/java/view/InputView.java
> +    public static final String INPUT_SELF_TICKET_COUNT_MESSAGE = "수동으로 구매할 로또 수를 입력해 주세요.";
에고.. 정신이..😂

2022-03-04 19:54 UTC, yxxnghwan commented on src/main/java/domain/LottoGame.java
> +    }
변경했습니다! 사실 LottoGame의 역할을 덜어내면서 더이상 전략패턴 인터페이스 이외의 상태를 가지지 않아서...
아마 저런 불완전한 객체를 만들었던건 `LottoGame에 사용자의 입력값을 순차적으로 세팅해서 결과를 뽑아야지~` 하는 생각으로 코드를 짜서 그렇게 되었던 것 같아요...

2022-03-04 19:54 UTC, yxxnghwan commented on src/main/java/domain/LottoTicket.java
> +    }
테스트 추가했습니다!

2022-03-04 19:55 UTC, yxxnghwan commented on src/main/java/domain/WinningResult.java
> +    public int sumTotalReturn() {
private 메서드로 잠기고 수익률 계산 메서드를 추가하면서 간접적으로 테스트 하도록 했습니다!

2022-03-04 19:56 UTC, yxxnghwan commented on src/main/java/domain/WinningResult.java
> +        Integer winningPrizeCount = result.get(winningPrize) + COUNT_UNIT;
`getOrDefault()`에 대해서 몰랐는데 알려주셔서 감사합니다 또링!
미션에 바로 적용시켜봤어요!

2022-03-04 19:57 UTC, yxxnghwan commented on src/main/java/domain/WinningTicket.java
> +    private final Set<LottoNumber> winningNumbers;
`LottoTicket`을 가지도록 변경했습니다!

2022-03-04 19:57 UTC, yxxnghwan commented on src/main/java/domain/WinningTicket.java
> +    public int compareMatchCount(LottoTicket lottoTicket) {
추가 완료!

2022-03-04 19:57 UTC, yxxnghwan commented on src/main/java/domain/WinningTicket.java
> +                .count();
알려주셔서 감사해요 또링! 덕분에 더 간결한 코드로 리팩토링할 수 있었어요!

2022-03-04 19:57 UTC, yxxnghwan commented on src/main/java/domain/WinningTicket.java
> +    public boolean isMatchBonusNumber(LottoTicket lottoTicket) {
추가 완료!

2022-03-04 19:59 UTC, yxxnghwan commented on src/test/java/domain/LottoTicketsTest.java
> +    }
LottoMoney가 테스트할 수 있게 변경되었기 때문에 LottoTickets의 테스트에서는 삭제했습니다!

2022-03-04 20:05 UTC, yxxnghwan commented on src/test/java/domain/MoneyTest.java
> +                .hasMessage(Money.NOT_POSITIVE_ERROR_MESSAGE);
앗.. TDD관점에서는 프로덕션의 상수로 메시지를 비교하는게 자연스럽지 않을 수 있군요...
TDD가 너무 어렵습니다😂 사실 정신을 차리고 보면 어느 순간부터는 테스트 코드를 안만지고 있더라구요...
일단은 또링처럼 프로덕션의 상수로 비교하도록 코드를 작성했는데요, 저도 글자 하나하나를 비교하는건 그렇게 의미있지는 않다고 생각해서 그렇게 한건데... TDD를 연습하는 미션이니 다시 테스트 코드와 따로 두는게 좋을까요??
또링 생각은 어떠신가요?

---

`TICKET_PRICE`는 여러 군데에서 필요로 하고 있는데, 문맥상 `LottoGame`이 갖는게 가장 자연스러워 보이네요
`LottoGame`이 갖도록 변경했습니다!

2022-03-05 20:02 UTC, jnsorn commented on src/main/java/view/InputView.java
> +    }
네 좋습니다 👍 앞으로 미션을 진행하다보면 상태를 가지지 않지만 singleton 패턴으로 관리되는 클래스들을 마주칠 수 있어요. 그럼 그 때 _'왜 이 클래스는 static 클래스가 아니라 singleton 패턴을 사용했는지'_ 를 고민해보시면 좋을 것 같습니다! 지금 당장은 알렉스의 기준도 아주 좋습니다.

2022-03-05 20:13 UTC, jnsorn commented on src/main/java/domain/WinningResult.java
> +    }
저도 비슷해요. 특히 생성자가 많아지면 외부에서는 어떤 생성자를 써야할지 혼란스러워지는데, 이 때 메서드 네이밍을 통해서 명확하게 알 수 있다는 점이 좋은 것 같아요!
(참고) [정적 팩토리 메서드는 왜 사용할까?](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)

2022-03-05 20:28 UTC, jnsorn commented on src/main/java/domain/LottoGame.java
> +    }
좋습니다. 객체가 필요한 값을 생성 시점에 넣어주어 변하지 않는 객체가 되었어요. 불변 객체의 다양한 이점을 누릴 수 있겠네요 👍

2022-03-05 20:32 UTC, jnsorn commented on src/test/java/domain/MoneyTest.java
> +                .hasMessage(Money.NOT_POSITIVE_ERROR_MESSAGE);
네 ㅎㅎ 현재는 TDD 방식에 익숙해져야하는 단계이고, 테스트를 통해 프로덕션을 개선해나가는 경험이 더 중요하다는 생각이 드네요. 그런 이유에서 테스트의 메세지는 따로 두는 게 좋을 것 같습니다. 😃

2022-03-05 21:11 UTC, jnsorn requested changes
알렉스, 리뷰 잘 반영해주셨네요. 짧은 시간에 많은 내용을 학습하시고, 고민하신 것 같아요! 💯
추가로 개선되면 좋을 부분에 대해 코멘트 남겼습니다. 😃 특히 제가 먼저 개선 방향을 말씀드리기 보다는 알렉스의 생각을 듣고 싶은 부분들이 있어서 질문을 남겼는데, 이 부분들도 함께 반영해서 리뷰 요청보내고 싶으시면 DM을 통해 얘기나눠도 좋습니다! 언제든 편히 DM주세요. :)

2022-03-05 21:11 UTC, jnsorn commented on src/main/java/controller/LottoController.java
>      }
1단계에서는 MainApplication과 Controller의 역할에 대해 이야기 나눴는데요, 
2단계에서는 LottoController와 LottoGame에 대해 이야기 나눠보면 좋을 것 같아요.

알렉스는 `LottoController`와 `LottoGame`의 역할이 무엇이라고 생각하시나요?

2022-03-05 21:11 UTC, jnsorn commented on src/main/java/domain/LottoTicket.java
> +        lottoNumberValues.forEach(number -> lottoNumbers.add(new LottoNumber(number)));
현재 로또티켓이 생성될 때마다 `LottoNumber`를 생성해주고 있어요. `LottoNumber`는 계속 생성되어야 할까요? 미리 만들어두고 재사용하면 어떨까요?

2022-03-05 21:11 UTC, jnsorn commented on src/main/java/domain/LottoTickets.java
> +    }
> dm으로 불변에 대한 얘기를 해주셔서 혹시나 제가 불변이어야 하는 걸 불변으로 만들지 않았나 싶어 쭉 봤는데요, 혹시나 제가 복사에 실수를 하고 있나 찾아봤는데 처음엔 제가 아는 지식으로는 찾을 수 없었습니다. 

제가 불변에 대해 말씀드릴 당시 LottoGame이 불변객체가 아니었고, 충분히 개선할 수 있을 것 같아 말씀드렸었습니다. 😃  https://github.com/woowacourse/java-lotto/pull/453#discussion_r818258886 

> 또링이 보내준 링크의 글을 보고 Collections.unmodifiableXX는 새로 받은 주소가 기존 컬렉션과 상관 관계가 있어서 새로 받은 곳에서 수정은 막아주지만, 원본 컬렉션을 변경하면 unmodifiableXX로 생성된 컬렉션은 영향을 받는다는걸 알게 되었습니다. 저는 방어적 복사를 하고 있다고 생각했고 컬렉션이 다루는 클래스도 불변으로 설계된 클래스여서 불변이라고 생각했는데, 원본 컬렉션과 관계가 끊어지지를 않았군요. 그래서 기존 Collections.unmodifiableXX을 사용하던 것들을 copyOf로 변경했어요. 또링 덕분에 하나 더 배울 수 있었습니다.

많은 내용을 학습 하셨네요! ㅎㅎ💯 다만 여기서는 한 가지 더 고민해보면 좋을 것 같아요. 
```suggestion
    public List<LottoTicket> getTickets() {
        return Collections.unmodifiableList(lottoTickets);
    }
```
여기서 정말 깊은복사가 필요할까요? 깊은 복사는 어떤 경우에 해야 하는 걸까요?

2022-03-05 21:11 UTC, jnsorn commented on src/main/java/domain/SelfPurchaseCount.java
> +    private final int count;
새로운 값객체가 생겼어요. 😮
개수에 대한 객체같은데 클래스는 `Count`, `LottoCount`, `LottoQuantity` 등과 같이 추상적으로 네이밍하고, 실제 사용할 때 `selfPurchaseCount`와 같이 명명하는 건 어떤가요?

2022-03-05 21:11 UTC, jnsorn commented on src/main/java/domain/SelfPurchaseCount.java
> +    private final int count;
클래스 변수와 인스턴스 변수 사이는 개행을 통해 구분해주세요.

2022-03-05 21:11 UTC, jnsorn commented on src/main/java/domain/LottoResult.java
> +    }
파라미터로 money를 받으면 어떨까요?

2022-03-06 20:15 UTC, yxxnghwan commented on src/test/java/domain/MoneyTest.java
> +                .hasMessage(Money.NOT_POSITIVE_ERROR_MESSAGE);
네! 다시 프로덕션의 상수를 private으로 바꾸고 테스트 코드에선 따로 메서드를 비교하도록 변경했습니다.

2022-03-06 20:20 UTC, yxxnghwan commented on src/main/java/controller/LottoController.java
>      }
`LottoGame`에게 너무 애매한 역할이 부여되고 있었던 것 같아요.. 설계를 바꿔서 `LottoMachine`이라는 클래스로 바꾸고,
View에서 입력된 파라미터로 티켓을 발행하는 역할만 부여했습니다.
그 외에 `WinningPrize`가 상금을 도출하고, `WinningResult`가 결과를 계산하도록 각각의 역할에 충실하게 변경했습니다.
더더욱 LottoGame이 역할이 없어져서 삭제했고 컨트롤러의 로직은 최대한 깔끔하게 정리해봤어요.

2022-03-06 20:21 UTC, yxxnghwan commented on src/main/java/domain/LottoTicket.java
> +        lottoNumberValues.forEach(number -> lottoNumbers.add(new LottoNumber(number)));
LottoTicket에서 미리 1~45를 캐싱하여 가지고 있다가 정적 팩토리 메서드로 객체 생성 없이 캐싱된 객체를 반환하도록 했습니다.
또링이 보내준 정적 팩토리 메서드에 대한 글을 참고했어요! 감사합니다 또링!

2022-03-06 20:23 UTC, yxxnghwan commented on src/main/java/domain/LottoTickets.java
> +    }
위 경우엔 이미 LottoTicket이 불변인 객체이기 때문에 `unmodifiableList()`로 리스트의 변경만 막아도 충분히 불변성을 가질 것 같아요! 다시 원래대로 `unmodifiableList()`를 사용했습니다.

2022-03-06 20:23 UTC, yxxnghwan commented on src/main/java/domain/SelfPurchaseCount.java
> +    private final int count;
`LottoCount`라는 네이밍으로 수정했어요! 개행도 바꿨습니다😉

2022-03-06 20:23 UTC, yxxnghwan commented on src/main/java/domain/LottoResult.java
> +    }
수정했습니다!😁

2022-03-06 20:38 UTC, yxxnghwan commented
안녕하세요 또링! 항상 너무 감사합니다🙇🏻‍♂️

저번 피드백 내용 반영과 코드 설계를 변경했습니다.
일단 제가 너무 enum을 객체 지향적으로 사용하지 않고 상수처럼 사용했다고 생각이 들었어요.
`WinningStrategy`를 삭제해서 전략패턴을 빼고 `WinningPrize`가 그 로직을 가지도록 설계했어요.
그러다보니 LottoGame의 역할이 점점 애매해졌고 결국 `LottoTickets`을 발행해주는 클래스 하나만 있으면 되겠더라구요.
`LottoMachine`이라는 클래스를 정의하고 LottoGame은 삭제했습니다.

컨트롤러의 내부 로직은...🤔
게임 진행에 대한 책임을 완전히 걷어내지는 못했습니다. 입력 값을 가지고 티켓을 구매하는 부분만 LottoMachine을 통해 구매했고
각각의 도메인에서 본인에 충실한 역할을 수행하기에 컨트롤러 그 자체에서 로직을 호출하게 되었습니다.
LottoGame을 남겨서 LottoGame이 각 역할을 수행하도록 메서드를 포장할 수 있지만, 
결국 다른 도메인의 메서드를 호출하는 것이 되고 단 한줄의 메서드를 포장하는건 무의미하다고 생각이 되어서 LottoGame은 삭제하게 되었습니다.
또링이 생각하시던 결과가 아닐 것 같아 걱정이 되는군요..😢

이번 피드백도 잘 부탁드립니다! 늦은 시간에도 잘 봐주시고 답장해주셔서 너무 감사해요 또링!😁

2022-03-07 15:13 UTC, jnsorn approved these changes
안녕하세요, 알렉스! 리뷰 반영해주신 부분 확인했어요.
확실히 코드가 처음보다 깔끔해진 것 같네요. 💯 미션은 여기서 마무리해도 될 것 같습니다. 
알렉스와 이야기 주고받으면서 많은 고민을 하고, 열심히 학습하고 계신 것이 느껴졌어요. 
앞으로도 지금처럼만 하시면 더 성장하실 수 있을거예요! 로또 미션 고생하셨어요~

2022-03-07 15:13 UTC, jnsorn commented on src/main/java/domain/LottoMachine.java
> +    public static final int TICKET_PRICE = 1000;
해당 상수를 사용하는 곳으로 옮기고 private으로 관리하면 어떨까요?

2022-03-07 15:13 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +    }};
```suggestion
    private static final Map<Integer, LottoNumber> lottoNumberCache = new HashMap<>() {{
        IntStream.rangeClosed(MIN_VALUE, MAX_VALUE)
                .mapToObj(LottoNumber::new)
                .forEach(lottoNumber -> put(lottoNumber.getValue(), lottoNumber));
    }};
```

(참고) `Collectors.toMap()`을 이용할 수도 있어요!

2022-03-07 15:13 UTC, jnsorn commented on src/main/java/domain/LottoNumber.java
> +    }
private 생성자, 적절한 자료구조(Map)를 통한 사용성 증가💯

2022-03-07 15:13 UTC, jnsorn commented on src/main/java/domain/WinningResult.java
> +            result.merge(winningPrize, COUNT_UNIT, Integer::sum);
적절한 메서드 활용 💯

2022-03-07 15:13 UTC, jnsorn commented on src/main/java/domain/WinningPrize.java
> +    public static WinningPrize findWinningPrize(int matchCount, boolean matchBonus) {
> 일단 제가 너무 enum을 객체 지향적으로 사용하지 않고 상수처럼 사용했다고 생각이 들었어요. WinningStrategy를 삭제해서 전략패턴을 빼고 WinningPrize가 그 로직을 가지도록 설계했어요.

불필요하게 분리된 부분을 하나로 합치면서 훨씬 더 풍부한 객체가 된 것 같아요 👍🏼

2022-03-07 15:13 UTC, jnsorn commented on src/main/java/controller/LottoController.java
>      }
> 컨트롤러의 내부 로직은...🤔
> 게임 진행에 대한 책임을 완전히 걷어내지는 못했습니다. 입력 값을 가지고 티켓을 구매하는 부분만 LottoMachine을 통해 구매했고
> 각각의 도메인에서 본인에 충실한 역할을 수행하기에 컨트롤러 그 자체에서 로직을 호출하게 되었습니다.
> LottoGame을 남겨서 LottoGame이 각 역할을 수행하도록 메서드를 포장할 수 있지만,
> 결국 다른 도메인의 메서드를 호출하는 것이 되고 단 한줄의 메서드를 포장하는건 무의미하다고 생각이 되어서 LottoGame은 삭제하게 되었습니다.
> 또링이 생각하시던 결과가 아닐 것 같아 걱정이 되는군요..😢

`Controller`와 `LottoMachine`의 역할에 대해 많이 고민하신 것 같아요. 😄

제가 생각하는 `controller`는 뷰에서 전달받은 값을 도메인에 넘겨주고, 도메인의 값을 뷰에 넘겨주는 객체예요. 이런 책임을 가진 객체에서는 당첨결과를 어떻게 생성하는지는 몰라도 됩니다. 하지만 지금은 컨트롤러에서 `winningNumbers`와 `bonusNumber`를 입력받아 `WinningTicket`을 생성하고, 또 `lottoTickets`와 `winningTickets`를 입력받아 `WinningResult`를 생성하고 있어요. 
즉, 당첨결과에 대한 로직이 컨트롤러에 노출되고 있습니다. 이런 세세한 로직들은 `Controller`보다 게임을 진행하는 `LottoMachine`이 알고 있는게 더 적절하지 않을까요? `LottoMachine`에게 당첨번호와 보너스번호를 넘겨주면 결과를 전달받는 형태로 변경해봐도 좋을 것 같아요! 만약 알렉스가 생각하는 `controller`와 `LottoMachine`의 역할이 다르다면 제 얘기는 무시하셔도 좋구요. 🙂

가끔 객체의 역할이 애매할때는 코드가 아닌 요구사항을 보고 다시 객체들의 역할을 정리해보는 것도 좋아요. 정리한 뒤 코드를 보며 객체마다 적절하지 않은 행위는 적절한 객체로 이동시키는 거죠. 설계에서 가장 중요한 건 객체들의 책임을 확실히 하는 것이라고 생각해요 😃

2022-03-07 15:14 UTC, merged