[2단계 - 로또(수동)] 엘리(한해리) 미션 제출합니다.
woowacourse/java-lotto pull request #455
Opened 2022-03-02 08:45 UTC by RIANAEH

안녕하세요 럿고!!

이번에는 수동 생성 기능을 추가하고, 
럿고의 코드 리뷰를 통해 학습한 내용들을 적용해보려고 노렸해봤어요 😄

1단계에서 해결하지 못 한 리뷰에 대해서는 1단계 PR에 이어서 코멘트를 달아놨어요!!

### Money
그리고 아직 Moeny 객체를 생성해서 구입 금액과 상금에 어떻게 적용해야할지 모르겠어서 이 부분은 적용하지 못했어요ㅠㅠ 
감이 안 잡혀서 다른 크루들을 코드들도 살펴봤는데 많은 크루들이 이름은 Money를 사용하지만 상금에까지 적용한 사례를 찾기 힘들더라구요ㅠㅠ
조금 더 조사해보겠습니다!!
### 에러 메시지 Enum
정확한 방법을 모르겠어서 일단 임시적으로 하나만 적용해봤는데 확인해주실수 있으신가요..? 

2단계 리뷰도 잘 부탁드립니다 🙇‍♀️

2022-03-03 12:26 UTC, ksy90101 requested changes
안녕하세요 엘리 :) 리뷰어 럿고입니다.
2단계도 너무 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니, 한번 확인해보시겠어요?

질문은 언제든지 DM이나 댓글을 통해 해주시면 감사하겠습니다~

2022-03-03 12:26 UTC, ksy90101 commented on src/main/java/lotto/domain/Exception.java
> +public enum Exception {
이건 Message를 나타내는거 같아요.
Exception이면 메시지보다 예외라는 것이 더 의미하는것 같습니다. 
이름을 바꿔보시면 어떨까요?

2022-03-03 12:26 UTC, ksy90101 commented on src/main/java/lotto/domain/Lotto.java
> +        final Set<LottoNumber> lottoNumbers = new HashSet<>(lottoGenerator.makeLottos());
지금 다 final로 바꾸셨는데, final로 바꾸신 이유가 있나요?

2022-03-03 12:26 UTC, ksy90101 commented on src/main/java/lotto/controller/LottoController.java
>          OutputView.printResult(rankBoard, rankBoard.calculateProfitRatio(purchaseAmount.getAmount()));
요구사항과 실제 출력되는거랑 다른거 같습니다.
한번 확인해보세요. 요구사항을 지키는것도 중요한것이라고 생각이 듭니다.

2022-03-03 12:26 UTC, ksy90101 commented on src/main/java/lotto/controller/LottoController.java
>          OutputView.printResult(rankBoard, rankBoard.calculateProfitRatio(purchaseAmount.getAmount()));
내가 만원을 구매하고, 1등 두번 당첨이 되면 수익률이 어떻게 나올까요?
한번 확인해보세요~

2022-03-03 12:26 UTC, ksy90101 commented on src/main/java/lotto/controller/LottoController.java
>          OutputView.printResult(rankBoard, rankBoard.calculateProfitRatio(purchaseAmount.getAmount()));
<img width="564" alt="image" src="https://user-images.githubusercontent.com/53366407/156561248-89db7249-07cf-452b-885b-b15dc8aa57a7.png">

2022-03-03 12:26 UTC, ksy90101 commented on src/main/java/lotto/domain/Rank.java
>          if (size == 5 && isBonusBallMatched) {
매직넘버 :)

2022-03-03 12:26 UTC, ksy90101 commented on src/main/java/lotto/domain/Exception.java
> +public enum Exception {
해당 enum이 domain이 맞을까요?
어떻게 패키지를 분리하면 좋을지 고민해보시면 좋을거 같습니다 :)

2022-03-03 12:26 UTC, ksy90101 commented on src/main/java/lotto/domain/RankBoard.java
>      private final Map<Rank, Integer> board = new HashMap<>();
EnumMap을 한번 알아보고, 적용해볼 수 잇으면 적용해볼까요?

2022-03-03 12:26 UTC, ksy90101 commented on src/test/java/lotto/domain/LottoGameTest.java
> +    @ParameterizedTest
해당테스트는 실제 돌려서 보면, 아래 사진처럼 나오는데요.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/53366407/156564307-74219898-42e5-41b9-a9c3-7cf8d7a083e2.png">
해당 어노테이션에 인자에 특정한 방법을 이용하면 원하는 대로 나오게 할 수 있습니다 :) 한번 알아볼까요?

2022-03-04 13:47 UTC, RIANAEH commented on src/main/java/lotto/controller/LottoController.java
>          OutputView.printResult(rankBoard, rankBoard.calculateProfitRatio(purchaseAmount.getAmount()));
1등 당첨금이 20억 인데 
총 수익금을 저장하는 변수 타입을 int 형으로 지정해서 생긴 문제라(int의 경우 최대 21억 정도까지 지원) 
최대 2^63-1까지 지원하는 long으로 타입을 변경했어요!! 
너무 아무 생각없이 int를 사용했네요..ㅜ

![image](https://user-images.githubusercontent.com/45311765/156774483-29975790-5323-4399-bc0f-8132dc902e6f.png)

지나칠 뻔 했는데 발견해주셔서 감사합니다 👍

2022-03-04 13:51 UTC, RIANAEH commented on src/main/java/lotto/domain/Lotto.java
> +        final Set<LottoNumber> lottoNumbers = new HashSet<>(lottoGenerator.makeLottos());
이전에 네오 수업에서 네오가 보통 `final`로 선언해 불변임을 알려주는게 불안감을 해소시켜주는? 방법이라는 얘기를 듣고 자동차 미션에 적용했었는데, 당시에는 그말이 와닿지가 않았어서 그런가 잊고 있었더라구요.. ㅎㅎ

이번에 이펙티브 자바를 읽다 `불변 객체`, `방어적 복사` 파트를 읽다보니 왜 객체의 불변이 보장되지 않으면 불안한지 저도 어느정도 이해가 가더라구요!! 그래서 이번에 다시 적용해봤어요!!

2022-03-06 07:11 UTC, RIANAEH commented on src/main/java/lotto/domain/RankBoard.java
>      private final Map<Rank, Integer> board = new HashMap<>();
이펙티브 자바에서 EnumMap을 보고 적용해야지.. 하고 잊고 있었네요ㅎㅎ
Enum 타입을 키로 사용할 떄는 확실히 EnumMap을 사용하는게 좋겠네요!!
감사합니다 👍

2022-03-07 23:18 UTC, ksy90101 commented on src/main/java/lotto/domain/Lotto.java
> +        final Set<LottoNumber> lottoNumbers = new HashSet<>(lottoGenerator.makeLottos());
네 :) 좋습니다!

2022-03-07 23:25 UTC, ksy90101 approved these changes
엘리 안녕하세요 :) 리뷰어 럿고입니다.
피드백을 너무 잘 적용해주셨네요. 고생 많으셨습니다 💯 
로또는 이만 마무리 할게요.
그래도 몇가지 고민해보면 좋을거 같아서 피드백을 남기긴 했습니다. 수정하시고 궁금하신점이 있다면 슬랙 DM으로 연락주세요!

2022-03-07 23:25 UTC, ksy90101 commented on src/main/java/lotto/constant/ErrorMessage.java
> +public enum ErrorMessage {
너무 잘 해주셨네요 :) 
나중에는 각 도메인별로 Message를 나눠서 작성하면 관리하기가 더 용이합니다 :) 
이건 참고만 해주세요 지금은 많지는 않으니 괜찮을거 같아요!

2022-03-07 23:25 UTC, ksy90101 commented on src/main/java/lotto/domain/FixedLottoGenerator.java
> +                .collect(toList());
차후 바뀌면 안되니, 여기도 불변을 적용해보면 어떨까요!?

2022-03-07 23:25 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final int value;
👍

2022-03-07 23:25 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
이게 사실 LottoNumber에 있어야 할지는 한번 고민해보세요.
CACHE 부분을 객체로 빼서 사용하는 방식이 더 관리하기가 용이할 수 있습니다 :)

2022-03-07 23:25 UTC, ksy90101 commented on src/test/java/lotto/domain/LottoMachineTest.java
> +    @ParameterizedTest(name = "[{index}] {0}개")
👍

2022-03-07 23:25 UTC, merged

2022-03-08 13:52 UTC, RIANAEH commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
생각해보지 못한 부분이었네요!! 👍