[로또] 아이크 미션 제출합니다.
woowacourse/java-lotto pull request #46
Opened 2019-06-06 13:19 UTC by ike5923

2019-06-08 10:50 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적으로 잘 구현해주셨네요 👍
다만 static factory method를 의습없이 너무 많이 사용한 것 같은 점과
객체간의 응집도가 떨어지는 점 등 몇가지 피드백 추가했습니다.
확인 부탁드리고 궁금하신 점 있으시면 언제든지 연락주세요. :)

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/controller/LottoShop.java
> +        return InputView.inputManualLottoTickets(InputView.inputManualLottoAmount())
LottoShop 자체가 다른 객체들을 facade해주는 역할로 보이는데요.
너무 많은 비즈니스 로직이 들어가있는 것 같습니다.
이를 조금 더 추상화해보면 어떨까요?

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/controller/LottoShop.java
> +    private WinningLotto getWinningLotto() {
getUserTickets, getWinningLotto, getBonusBall, getWinningResult
들은 이미 충분히 추상화되어있는 것 같은데 의미없이 메서드로 한번 더 추상화 한 것 같습니다. :)

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoConstant.java
> +    static final int LIMIT_MIN_NUM = 1;
LottoConstant 클래스를 별도로 분리하는것은 그닥 추천드리지 않습니다. 
전역변수의 의미로 사용 될 수 있기 때문인데요.
각자 책임을 가지고있는 객체가 가지고 있도록 하면 더 좋을 것 같습니다.

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/utils/NullCheckUtil.java
> +public class NullCheckUtil {
해당 객체도 전역적으로 쓰이는 유틸클래스가 아닌 비즈니스가 녹아있는 유틸클래스로 보입니다.
컬렉션에 대한 체크나 객체 자체에 대한 체크(Preconditions, Objects)의 경우 의미는 있겠으나
특정 객체에 의존적인 검증같은경우는 해당 객체 스스로가 가지고있는것이 맞습니다.

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoTicket.java
> +    public static LottoTicket createLottoTicket(List<LottoNumber> lottoNumbers) {
static factory method를 너무 많이 사용하신 것 같습니다.
static factory method의 용도와 장점에 대해 다시 한번 찾아보시고 필요 없는 부분에 대해서는 생성자를 사용하시는걸 추천드릴게요!

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoCreator.java
> +        List<LottoNumber> convertedLottoNumbers = lottoNumbers.stream()
LottoTicket의 생성자가  Integer List를 받고 생성할 수도 있지 않을까요? :)

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoNumber.java
> +    private Integer lottoNumber;
`이펙티브 자바 아이템 61. 박싱된 기본 타입보다는 기본 타입을 사용하라`
참고 부탁드릴게요! :)

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoNumber.java
> +    public static LottoNumber createLottoNumber(Integer number) {
LottoNumber createLottoNumber(int number)가 현재도 여전히 pulic으로 공개되어있어요!
이러면 별도 pool을 만드는게 크게 의미가 없을수도 있는데요.
방법은 두가지가 있을 것 같습니다.

1. LottoNumber createLottoNumber(int number)를 package-private으로 만들고, LottoCreator을 통해서만 생성하도록 한다.
2. pool 자체를 LottoNumber createLottoNumber(int number)에서 사용하도록 한다. 즉 Lo

static factory method의 장점은 생성자랑 달리 객체를 재사용해서 돌려줄 수 있다는 점도 있습니다. :)
이를 활용해보셔도 좋을 것 같아요.

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoTicket.java
> +    public Boolean isContainedNumbers(LottoNumber lottoNumber) {
`이펙티브 자바 아이템 61. 박싱된 기본 타입보다는 기본 타입을 사용하라`
참고 부탁드릴게요! :)

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/result/WinningResult.java
> +    private WinningResult(UserTickets tickets, WinningLotto winningLotto, BonusBall bonus) {
WinningLotto 내부 속성에 BonusBall 또한 포함되는 내용이 아닐까요? :)

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/winning/BonusBall.java
> +    private void checkOverlapWithWinningNumbers(LottoNumber bonusBall, WinningLotto winningLotto) {
BonusBall이 WinningLotto에 의존적인 객체인데 따로 생성되어 관리되니 복잡도가 늘어나는 것 같네요. :)
전달받은 WinningLotto에 의존되어 객체가 생성되는데(결합도가 높은데) 응집도가 낮아 
잘못 사용 될 경우 여기에서 의도하는 validiation이 의미가 없을 것 같습니다.

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/winning/BonusBall.java
> +    public static BonusBall createBonusBall(Integer bonusBall, WinningLotto winningLotto) {
굳이 필요한 static factory method인가? 고민해보시면 좋을 것 같아요!

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/user/UserTickets.java
> +    private Rank getRank(WinningLotto winningLotto, BonusBall bonusBall, LottoTicket userTicket) {
Rank = winningLotto.match(userTicket) 같이 풀어낼 수 있지 않을까요?
객체간에 결합도가 높고 응집도가 낮아서 복잡해진 부분이 있는 것 같아요!

2019-06-08 10:50 UTC, phs1116 commented on src/main/java/lotto/domain/user/UserTickets.java
> +    public static UserTickets createUserTickets(List<LottoTicket> manualTickets, PurchaseAmount purchaseAmount
1. static factory method가 정말 필요한 부분인가.
2. Shuffle autoShuffle에 대해서 UserTickets이 필요한 부분인가.
3. shuffle은 UserTickets가 아닌 별도 팩토리가 의존해야하는 부분이 아닌지 고민해보시면 좋을 것 같습니다.
4. autoShuffle은 너무 자동 셔플에 대해 의존적인 이름인 것 같습니다.

2019-06-08 13:53 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoConstant.java
> +    static final int LIMIT_MIN_NUM = 1;
수정했습니다!

2019-06-08 14:40 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoNumber.java
> +    private Integer lottoNumber;
막연하게 모든 변수를 박싱하여 사용했던것 같습니다. 
null 값을 가지지 않고 시간과 메모리 성능 면에서 효율적인 기본타입.
이펙티브 자바 공부하겠습니다!!!

2019-06-08 14:40 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoTicket.java
> +    public Boolean isContainedNumbers(LottoNumber lottoNumber) {
수정했습니다.

2019-06-08 15:46 UTC, ike5923 commented on src/main/java/lotto/utils/NullCheckUtil.java
> +public class NullCheckUtil {
인자로 들어오는 객체나 컬렉션에 대해 각각의 객체나 method 내에서 null check를 할 수 있도록 변경하였습니다.

2019-06-10 07:12 UTC, ike5923 commented on src/main/java/lotto/controller/LottoShop.java
> +        return InputView.inputManualLottoTickets(InputView.inputManualLottoAmount())
수동 로또 생성하는 부분을 Model의 User 티켓 생성하는 과정에서 진행할 수 있도록 변경하였습니다.

2019-06-10 07:12 UTC, ike5923 commented on src/main/java/lotto/controller/LottoShop.java
> +    private WinningLotto getWinningLotto() {
수정했습니다!

2019-06-10 07:14 UTC, ike5923 commented on src/main/java/lotto/domain/result/WinningResult.java
> +    private WinningResult(UserTickets tickets, WinningLotto winningLotto, BonusBall bonus) {
WinningLotto가 BonusBall을 관리하도록 구조를 변경했습니다.

2019-06-10 07:19 UTC, ike5923 commented on src/main/java/lotto/domain/winning/BonusBall.java
> +    private void checkOverlapWithWinningNumbers(LottoNumber bonusBall, WinningLotto winningLotto) {
BonusBall의 class를 생성하여 추가구현하면서 메서드 복잡도가 증가하는 것을 느꼈었는데 WinningLotto가 가지도록 구조를 변경했더니 한결 간단해지는 것을 느꼈습니다. 기능을 추가할 때는 무작정 새로 만들기 보단 구조적으로 최대한 유용하고 효율적으로 구현할 수 있도록 고민을 많이 해봐야겠습니다. 구조를 변경하면서 느낀점이 많았어요 감사합니다!!!

2019-06-10 07:44 UTC, ike5923 commented on src/main/java/lotto/domain/user/UserTickets.java
> +    private Rank getRank(WinningLotto winningLotto, BonusBall bonusBall, LottoTicket userTicket) {
수정했습니다!

2019-06-10 08:36 UTC, ike5923 commented on src/main/java/lotto/domain/user/UserTickets.java
> +    public static UserTickets createUserTickets(List<LottoTicket> manualTickets, PurchaseAmount purchaseAmount
UserTicket이 아닌 LottoCreator에서 shuffle을 의존하도록 변경했습니다.

2019-06-10 09:20 UTC, ike5923 commented on src/main/java/lotto/domain/winning/BonusBall.java
> +    public static BonusBall createBonusBall(Integer bonusBall, WinningLotto winningLotto) {
BonusBall class를 삭제했습니다.

2019-06-10 09:25 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoCreator.java
> +        List<LottoNumber> convertedLottoNumbers = lottoNumbers.stream()
LottoTicket의 static factory method를 이용하여 다른 type의 list를 받아 ticket을 생성하도록 변경하였습니다.

2019-06-10 09:33 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoNumber.java
> +    public static LottoNumber createLottoNumber(Integer number) {
LottoNumber를 package-private하게 변경하고 LottoCreator를 통해 생성하도록 변경했습니다.

2019-06-10 09:35 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoTicket.java
> +    public static LottoTicket createLottoTicket(List<LottoNumber> lottoNumbers) {
자동/수동에 따라서 ticket을 생성하는 LottoTicket을 제외하고 생성자를 이용하도록 변경했습니다!

2019-06-10 13:02 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
피드백 매우 잘 반영해주신 것 같습니다. 💯 
다만 추상화를 조금 더 할 수 있을 것 같은 점,
조금 더 기능적으로 개선 할 수 있을 것 같은 점이 있어
피드백 몇가지 추가하였습니다.
참고 부탁드리고 궁금하신 점 있으시면 언제든지 DM 주세요. :)

2019-06-10 13:02 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoCreator.java
> +    public static LottoTicket createAutoTickets(Shuffle shuffle) {
createAutoTickets, createManualTickets에 대해서 한번만 더 추상화를 도전해보셨으면 좋을 것 같습니다. :)
LottoCreator를 인터페이스로 표현하여 한번 더 추상화하고, 구현이 어떻게 됬냐에 따라 자동으로 생성해주는 객체를 돌려주거나 매뉴얼로 돌려주거나 표현이 가능하게요!

2019-06-10 13:02 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoCreator.java
> +        return new LottoNumber(bonusBall);
보너스 볼 또한 possibleNumbers내에 포함되어있는 객체인데 한번 더 생성되는 것 같습니다. :)
재사용해볼 수 있도록 구조를 조금 수정해보면 좋을 것 같아요!
그리고 굳이 createBonusBall라고 별도 이름을 가진 메서드로 분리될 필요가 없는 것 같습니다.
LottoNumber를 생성하는 객체로 보이고 그냥 생서자를 사용해도 무방해보입니다.

2019-06-10 13:02 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoTicket.java
> +        List<LottoNumber> lottoNumbers = numbers.stream()
LottoNumber를 매번 재생성하는데 이미 생성된 LottoNumber를 재사용하도록 해보면 어떨까요?

2019-06-10 13:02 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoTicket.java
> +        lottoNumbers.forEach(LottoTicket::checkNullLottoNumber);
잘 추상화하면 createManualTicket와 하나의 메서드로 관리 할 수 있을 것 같습니다.
메서드의 기능 상으로는 꼭 auto일 필요가 없어보입니다. :)

2019-06-10 13:02 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/LottoCreator.java
> +public class LottoCreator {
LottoCreator가 너무 많은 역할을 하는 것 같습니다.
LottoNumber를 만들어주는 객채외 LottoTicket을 생성하는 객체를 분리해보면 어떨까요?

2019-06-16 18:27 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoCreator.java
> +        return new LottoNumber(bonusBall);
재사용할 수 있도록 수정했습니다.

2019-06-16 18:28 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoTicket.java
> +        List<LottoNumber> lottoNumbers = numbers.stream()
수정했습니다.

2019-06-16 18:29 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoTicket.java
> +        lottoNumbers.forEach(LottoTicket::checkNullLottoNumber);
추상화 과정에서 없앨 수 있었습니다.

2019-06-16 18:30 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoCreator.java
> +public class LottoCreator {
LottoNumberManager라는 class를 생성하여 LottoNumber로 박싱하고 재사용할 수 있도록 변경했습니다.

2019-06-16 18:41 UTC, ike5923 commented on src/main/java/lotto/domain/lottomanager/LottoCreator.java
> +    public static LottoTicket createAutoTickets(Shuffle shuffle) {
요구하는 argument와 return type이 서로 달라서 추상화하는 과정에서 고민을 많이 했던것 같습니다.
맞는 방법인지는 모르겠지만, 생성자로 서로다른 인자를 초기화해서 티켓을 생성하였습니다.
다만, 수동생성의 경우 한장의 로또를 만들때마다 ManualCreator의 생성자를 호출하도록 되어있는데 좋은 방법을 찾지 못했습니다. 피드백 부탁드려요ㅠ

2019-06-17 14:11 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 화투입니다.
피드백 반영 감사합니다. 👍 
깔끔하게 잘 구현하신 것 같아요!
이번 단계 머지할게요! 
질문 사항에 대해서 간단한 피드백 하나 남겼는데요, 참고해주세요 :)

2019-06-17 14:11 UTC, phs1116 commented on src/main/java/lotto/domain/lottomanager/ManualCreator.java
> +        return new LottoTicket(lottoNumbers);
ManualCreator, AutoCreator를 둘로 나누어서 추상화 하신것도 정말 잘 하신 것 같아요. :)
둘을 포함하는, 혹은 둘중 하나가 다른 하나를 포함하는 Creator 객체를 만들어서도 사용할 수 있을것 같네요!
그리고 ManualCreator는 값을 전달해서 생성하는게 신경쓰이신다면 조금 더 추상화해서
LottoNumber를 돌려주는 Supplier를 구현해보는것도 방법일 수 있을것 같아요!

2019-06-17 14:11 UTC, merged