[2단계 - 로또(수동)] 바니(사현빈) 미션 제출합니다.
woowacourse/java-lotto pull request #464
Opened 2022-03-02 13:49 UTC by HyeonbinSa

안녕하세요! 범블비! 

지난 1단계 미션에서 추가로 피드백 주신 내용과 함께 2단계 미션 구현하여 리뷰 요청드립니다! 

이번에도 잘 부탁드리겠습니다! 감사합니다.

2022-03-02 15:04 UTC, ddaaac requested changes
안녕하세요 바니!

전반적으로 코드에 큰 변화없이 깔끔하게 구현해주셨습니다.

몇 가지 간단한 코멘트 남겼으니 확인 부탁드려요 :)

2022-03-02 15:04 UTC, ddaaac commented on src/main/java/domain/Lotto.java
> +    private final Numbers numbers;
컴포지션 사용 👍

2022-03-02 15:04 UTC, ddaaac commented on src/main/java/domain/UserCount.java
> +    private final int manualCount;
상수와 필드는 한 줄 띄워주면 보기 더 좋습니다 :)

2022-03-02 15:04 UTC, ddaaac commented on src/main/java/domain/UserCount.java
> +    private final int totalCount;
이 필드가 필요할까요?

2022-03-02 15:04 UTC, ddaaac commented on src/main/java/domain/UserCount.java
> +public class UserCount {
Count를 담당하는 객체 잘 생성해주셨습니다. 덕분에 큰 변화없이 2단계 구현이 가능하네요.

2022-03-02 15:04 UTC, ddaaac commented on src/main/java/domain/Lottos.java
> +    public static Lottos generateLottos(List<Lotto> manualList, int count) {
`Lottos` 입장에서 이 로또 리스트가 수동이란걸 알 필요는 없을 거 같아요.
그냥 로또 리스트와 내가 생성해야할 갯수를 받는다고 표현하는게 조금 더 적절하지 않을까요?

2022-03-02 15:04 UTC, ddaaac commented on src/test/java/domain/UserCountTest.java
> +public class UserCountTest {
예외상황 말고도 정상적으로 생성되었을 때의 테스트도 있으면 좋을 것 같네요.

2022-03-02 15:04 UTC, ddaaac commented on src/test/java/domain/LottosTest.java
>      }
이 테스트는 당첨 결과를 테스트하기보다는 전체 갯수가 5개인지만 확인하는 테스트 같아요.
https://github.com/woowacourse/java-lotto/pull/337#discussion_r815829304 에서 생성자를 열어서 원하는 로또 번호들을 직접 넣는 것도 괜찮을 것 같다는 코멘트를 남겼었는데, 혹시 생성자를 닫기로 결정하신 이유가 있을까요?

2022-03-02 15:25 UTC, HyeonbinSa commented on src/main/java/domain/UserCount.java
> +    private final int totalCount;
피드백 주신 것과 같이 다른 곳에서 사용하지 않고 해당 필드가 필요하지 않아 제거하였습니다!!

2022-03-02 16:18 UTC, HyeonbinSa commented on src/test/java/domain/UserCountTest.java
> +public class UserCountTest {
정상적으로 생성하는 경우의 테스트 추가하였습니다!

미처 작성하지 못했던 `Numbers`나 `UserCount`의 테스트 코드를 작성하면서 궁금한 것이 생겨 질문드립니다 ㅎㅎ

`UserCount`클래스를 예로 들었을 때, 범블비의 경우에 정상적으로 생성되었을 경우를 테스트한다면 
`assertDoesNotThrow​()`를 사용하여 예외가 발생하지 않는 것을 테스트하시나요?? 아니면
```java
UserCount userCount = new UserCount(totalCount, manualCount);
assertEquals(userCount.getAutoCount(), 2);
```
와 같이 필드의 값을 비교하여 판단하시나요 ??

2022-03-02 16:18 UTC, HyeonbinSa commented on src/main/java/domain/UserCount.java
> +public class UserCount {
😀 감사합니다

2022-03-02 16:40 UTC, HyeonbinSa commented on src/test/java/domain/LottosTest.java
>      }
우선, 어떤 방식이 옳은 접근인지 고민하면서 확실히 정하지 못하였고 2단계 기능 구현을 중점적으로 다루다보니 테스트코드 작성에 있어서 놓쳤던 것같습니다... 죄송합니다;;
그래서 범블비가 말씀해주신대로 테스트를 위해 `public`으로 설정하여 테스트하였습니다. (public으로 변경했을 때 발생하는 문제점이나 합당한가에 대한 고민은 다른 동료들과 얘기도 해보고 다시 한번 고민해보도록하겠습니다🧐)
여기서 2단계 - 수동 구매 를 적용하며 아래 코드와 같이 생성자를 사용하지 않고 테스트할 수 있어 다시 `private`으로 수정하였습니다.
```java
Lottos lottos = Lottos.generateLottos(lottoList, 0);
```

2022-03-02 16:46 UTC, HyeonbinSa commented
안녕하세요! 

늦은 시간에 빠르게 리뷰해주셔서 정말 감사드립니다!

피드백 주신 내용을 기반으로 수정해서 다시 리뷰 요청드립니다!

오늘도 좋은 하루되세요~

2022-03-02 17:15 UTC, ddaaac requested changes
안녕하세요 바니!

빠르게 리뷰 반영해주셨네요 💯

저도 빠르게 리뷰 몇 가지 남겼습니다. 확인 부탁드려요.

2022-03-02 17:15 UTC, ddaaac commented on src/main/java/domain/Numbers.java
> +    public List<LottoNumber> getNumbers() {
getter는 로직 아래 두는 게 좋을 것 같아요 :)

2022-03-02 17:15 UTC, ddaaac commented on src/main/java/domain/Lotto.java
> +        return (int) numbers.getNumbers().stream().filter(winningNumber::contains).count();
여기 getter를 제거할 수 있을까요? 한 번 도전해보면 좋을 거 같네요 :)

2022-03-02 17:15 UTC, ddaaac commented on src/test/java/domain/LottosTest.java
> +
- 변수명에 신경써주세요 😀
- list 내부가 길어지면 한 줄에 한 개의 원소만 배치해주세요. 인덴트가 모두 같아야 이 인덴트에 있는 건 리스트의 원소구나 하고 파악이 쉽답니다.

2022-03-02 17:15 UTC, ddaaac commented on src/test/java/domain/LottosTest.java
> +    public void getWinningStatisticsTestByRank(int number1, int number2, int number3, int number4, int number5, int number6, String rank) {
여러가지 경우에 대해서 테스트 잘 해주셨어요 👍
이 경우는 `@MethodSource`를 사용하는게 조금 더 깔끔할 거 같다는 생각도 드네요.

2022-03-02 17:18 UTC, ddaaac commented on src/test/java/domain/LottosTest.java
> +    public void getWinningStatisticsTestByRank(int number1, int number2, int number3, int number4, int number5, int number6, String rank) {
```suggestion
    @CsvSource(value = {"1,2,3,4,5,6,FIRST", "1,2,3,4,5,7,SECOND", "1,2,3,4,5,8,THIRD",
        "1,2,3,4,7,8,FOURTH", "1,2,3,8,9,10,FIFTH", "1,2,9,10,11,12,SIXTH"})
    public void getWinningStatisticsTestByRank(int number1, int number2, int number3, int number4, int number5, int number6, Rank rank) {
```
요렇게 바로 enum 타입을 선언할 수도 있습니다.

2022-03-03 10:23 UTC, HyeonbinSa commented
안녕하세요! 범블비 

작성해주신 피드백을 토대로 수정해보았습니다! 다시 한번 리뷰 요청드릴게요!
지난 피드백에서 [통과 테스트 관련 질문](https://github.com/woowacourse/java-lotto/pull/464#discussion_r817860643)을 드렸는데 범블비의 의견 부탁드릴게요~

감사합니다!

2022-03-04 12:47 UTC, ddaaac commented on src/test/java/domain/UserCountTest.java
> +public class UserCountTest {
이 코멘트를 놓쳤네요. 죄송합니다 😅

테스트의 의도에 따라 달라질 것 같네요. 내부 값이 정상적으로 세팅됐는지 확인하려면 후자의 방법을 사용할 것 같고 단순히 검증을 통과한다는 걸 테스트하고 싶다면 전자의 방법을 사용할 것 같습니다.

2022-03-04 12:51 UTC, ddaaac approved these changes
안녕하세요 바니!

리뷰 잘 반영해주셨습니다! 이쯤에서 머지해도 충분할 거 같아요 😀

피드백을 따로 정리하는 모습이 정말 인상적이었습니다. 좋은 습관 쭈욱 이어나가시길 바랍니다.

질문에 대한 답변과 가볍게 고민할만한 질문 하나 남기고 마무리 짓겠습니다.

고생하셨어요!

2022-03-04 12:51 UTC, ddaaac commented on src/main/java/domain/Numbers.java
> +        return (int) numbers.stream().filter(winningNumber::contains).count();
잘 작성해주셨습니다. 💯

만약 시간이 남으시면 고민해볼만한 주제를 하나 던지고 마무리 할게요.
지금은 Numbers에서도 WinnerNumber를 알고 있고, WinnerNumber에도 Numbers를 알고 있습니다. 이런 구조가 어떤 문제가 있을지, 여기서는 어떻게 해결할 수 있을지 가볍게 고민해보시면 좋을 것 같아요.

2022-03-04 12:51 UTC, merged