[2단계 - 로또(수동)] 잉(유영우) 미션 제출합니다.
woowacourse/java-lotto pull request #466
Opened 2022-03-02 14:48 UTC by Yboyu0u

안녕하세요. 에단🙃🙃 2차로 또 뵙게 되네요. 반가워요. 

우선, 1차에서 패드백주셨던 부분 

**1. 모델의 상수를 모두 private으로 선언해보기**
이 부분에 대해서는 더 공부해 봐야 할 것 같습니다. 중복되는 상수를 public말고 private으로 관리할 수 있는 방법......
상수class를 따로 만들고 다른 class들에 주입해 getter()로 꺼내는 방법이 떠오르네요. 
근데 이렇게 하는 것이 옳은 방법인거 같지는 않아서 적용해 보지는 않았습니다. 로또 프로그램에서 상수를 공유하는 부분이 2,3개 정도 밖에는 없더라고요. 
다른 방법에 대해서 계속 생각해 보겠습니다!!

**2. domain 패키지의 모든 클래스를 불변(immutable)로 만들어보기**
이 부분은 적용해 보려고 시도했습니다! 
1. 클래스의 변수를 final 선언한다.
2. Collection으로 되어 있는 변수는  Collectors.toUnmodifiableList()를 사용해 변경을 막는다. 
3. getter로 값을 내보낼 때 Collections.unmodifiableList()로 감싼다. 
이렇게 세가지 단계로 진행해 보았습니다!! 

클래스를 불변으로 만들었을 때의 장점은 
1. 외부에서 주입받은 객체들이 외부에서 변경되더라도 중요한 domain의 값은 불변을 지킬 수 있다. 
2. getter를 통해 값을 꺼내도 UnsupportedOperationException이 발생해 불변을 지킬 수 있다.
결론적으로 외부에서 값의 변경을 완전히 차단해 중요한 domain 객체를 지킬 수 있는 것이 큰 장점이라고 생각합니다. 

추가로 View의 인터페이스화에 대한  첨언은 다음 PR과 함꼐 고민해 보도록 하겠습니다🙏 
(이번에는 기능 구현에만 중점을 두고 미션을 진행했네요🥲) 

### 추가사항
1. TicketMachine class 추가
로또 구입의 수동식 방법이 추가됨에 따라 Tickets에서 처리해야 할 역할이 너무 커졌다고 생각해서 다음과 같은 class를 만들었습니다. 

수동로또를 먼저 생성하고 남은 금액으로 자동으로 로또를 생성해 Tickets를 반환해주는 역할을 하는 class입니다. Tickets는 List<Ticket>을 주입받아 생성되는 로직으로 변경하였습니다. 

2. TicketCounter class 추가 
이 또한 Tickets에서 해야할 것이 많아졌다고 생각해서 개수와 투입 금액을 검증하고 처리하는 로직을 담당하는 다음과 같은 class를 만들었습니다. 

감사합니다.
많은 지적 부탁드릴게요🥲

2022-03-03 10:42 UTC, Laterality requested changes
안녕하세요 잉,

1단계에서 코멘트 남겨드린 부분도 잘 구현해주셨고, 전반적으로 역할 분리도 잘 돼있어서 리뷰할 게 많지 않네요 💯 

몇군데 코멘트 남겨드린 부분만 확인해주세요!

## 참고

불변 객체에 대해 잘 이해하셨네요.

다만, 알고 계신 것처럼 `Collections.unmodifiableXXX`로 생성되는 컬렉션은 자신에 대한 `add`, `set`, `put`등과 같은 변형 메서드 호출시 예외를 던져서 컬렉션의 조작을 막는데요. 클라이언트가 이 컬렉션 인스턴스를 테스트에서 조작해보지 않으면 예외가 발생한다는 걸 모른 채 사용할 수 있고, 최악의 경우에는 실행 시점에 예외가 발생할 가능성도 있습니다. 물론 테스트를 꼼꼼히 작성하면 충분히 인지할 수 있는 부분이지만 경우에 따라서는 이런 상황도 생길 수 있다는 점만 알아두시면 좋겠어요.

2022-03-03 10:42 UTC, Laterality commented on src/main/java/domain/Ticket.java
>  	private static final int CONDITION_FOR_CHECK_BONUS_BALL = 5;
이 상수는 `Rank`와 더 관련이 깊지 않을까요?

2022-03-03 10:42 UTC, Laterality commented on src/main/java/domain/Ticket.java
>  			.collect(Collectors.toList());
뷰의 출력 형식을 `Ball`이 알고 있는 걸까요?

2022-03-03 10:42 UTC, Laterality commented on src/main/java/domain/TicketMachine.java
> +	private static List<Ticket> manual(final TicketCounter ticketCounter, final List<List<Integer>> lottoTickets) {
1. `ticketCounter`는 사용되지 않는 인자네요.
2. 메서드 이름은 동사로 시작하면 어떨까요?

2022-03-03 10:42 UTC, Laterality commented on src/test/java/practice/ImmutableObjectTest.java
> +	@DisplayName("Ticket 불변 객체 테스트")
관련된 클래스의 테스트 클래스로 옮기면 어떨까요?

2022-03-03 10:42 UTC, Laterality commented on src/main/java/domain/TicketMachine.java
> +	public static Tickets generateTickets(final TicketCounter ticketCounter, final List<List<Integer>> manualLottoTickets,
`List<List<Integer>>`처럼 타입 파라미터가 중첩되면 타입을 한눈에 파악하기 어려울 수 있습니다. DTO를 사용해보면 어떨까요?

2022-03-03 16:29 UTC, Yboyu0u commented on src/main/java/domain/Ticket.java
>  			.collect(Collectors.toList());
```
@Override
public String toString() {
	return String.valueOf(number);
}
```
Ball의 toString() 메서드를 다음과 같이 오버라이드하여 사용하고 있어요. 
저정도는 domain 객체가 view의 출력형식을 알고 있다기보다 int형 변수를 string으로 그저 변환하는 정도라고 생각해서 저렇게 했습니다!
저 정도의 toString()정의도 잘못된 것일까요??

2022-03-04 22:58 UTC, Yboyu0u commented on src/main/java/domain/Ticket.java
>  	private static final int CONDITION_FOR_CHECK_BONUS_BALL = 5;
문맥상 Rank와 관련 깊다고 생각하여 Rank로 옮겼습니다!
그런데 저 상수가 Ball에서만 사용되고 있어서 현재 Rank에서 public으로 가져와 사용되고 있습니다. 
뭐가 좋은 방법인지는 모르겠네요.....

2022-03-05 05:25 UTC, Laterality requested changes
안녕하세요 잉,

잘 고쳐주셨네요 👍 

추가로 몇군데 코멘트를 더 남겨드렸으니 확인 부탁드려요!

2022-03-05 05:25 UTC, Laterality commented on src/main/java/domain/TicketMachine.java
> +	private static List<Ticket> doManually(final List<List<Integer>> lottoTickets) {
메서드 이름의 `do`는 아무런 의미도 나타내지 못하고 있네요. 더 적절한 이름은 없을까요?

2022-03-05 05:25 UTC, Laterality commented on src/main/java/domain/TicketMachine.java
> +	public static Tickets generateTickets(final TicketCounter ticketCounter,
static 메서드로 선언하신 이유가 있을까요?

2022-03-05 05:25 UTC, Laterality commented on src/main/java/domain/Ticket.java
>  			.collect(Collectors.toList());
`toString`은 뷰 뿐만 아니라 여러 용도로도 사용되는데요.

특히 로깅과 같은 출력 메서드에 객체를 인자로 넘기면 해당 객체의 `toString` 메서드의 반환값이 출력되는데요.

때문에 주로 디버깅을 위해 객체의 상태를 출력하는 목적으로 사용하는 경우가 많습니다.

즉, 객체의 구조가 바뀌거나 디버깅을 위해 해당 객체에 대한 추가 정보가 필요하다면 뷰의 요구사항과는 관계없이 `toString`의 구현은 언제든 바뀔 수 있습니다.

2022-03-05 05:25 UTC, Laterality commented on src/main/java/domain/Ticket.java
>  	private static final int CONDITION_FOR_CHECK_BONUS_BALL = 5;
상수가 사용되는 부분도 `Rank`로 옮겨보면 어떨까요?

2022-03-05 05:25 UTC, Laterality commented on src/main/java/domain/dto/ManualTicketsDto.java
> +		return manualTickets;
새 컬렉션으로 감싸서 반환하면 어떨까요? 컬렉션의 컬렉션은 어떻게 반환해야 안전할까요?

2022-03-05 05:25 UTC, Laterality commented on src/main/java/domain/Rank.java
>  			.orElseGet(() -> null);
`orElse(null)`로 사용해도 되겠네요.

`orElse`와 `orElseGet`은 각각 어떤 상황에 사용하는 것이 좋을까요?

2022-03-05 05:25 UTC, Laterality commented on src/main/java/domain/Tickets.java
> +		this.tickets = tickets;
새 컬렉션에 담아서 필드에 대입하면 어떨까요?

2022-03-05 05:25 UTC, Laterality commented on src/main/java/domain/WinningAnalyze.java
>  		return analyzeResult;
[참고] `Map<Rank, Long>` 타입을 사용하게 되지만 아래와 같은 방식으로도 결과를 계산할 수 있습니다. 

```java
        Map<Rank, Long> countByRank = tickets.getRanks(winningNumber)
                .stream()
                .collect(Collectors.groupingBy(r -> r, Collectors.counting()));

        double profitRate = calculateProfitRate(countByRank);

        return new WinningAnalyzeDto(countByRank, profitRate);
```

2022-03-05 06:27 UTC, Yboyu0u commented on src/main/java/domain/TicketMachine.java
> +	private static List<Ticket> doManually(final List<List<Integer>> lottoTickets) {
TicketMachine().buyTickets()
    .generateManualTickets() 와 .generateAutoTickets()로 변경하였습니다!

2022-03-05 06:46 UTC, Yboyu0u commented on src/main/java/domain/TicketMachine.java
> +	public static Tickets generateTickets(final TicketCounter ticketCounter,
저의 얕은 견해로 static을 선언하는 기준을 상태를 갖느냐 마느냐로 정하고 있는데, 
TicketMachine은 상태를 가지지 않고 그저 Ticket들을 만들어주는 공장같은 역할만을 하고 있다고 생각하여 static 메서드로 선언하였습니다.

2022-03-05 07:24 UTC, Yboyu0u commented on src/main/java/domain/dto/ManualTicketsDto.java
> +		return manualTickets;
```
public class ManualTicketDto {
	private final List<Integer> ticket;

	public ManualTicketDto(List<Integer> ticket) {
		this.ticket = List.copyOf(ticket);
	}

	public List<Integer> getTicket() {
		return ticket;
	}
}
```
위와 같은 dto를 하나서 만들어서 감쌌습니다. 
저렇게 하면 View에서 받은 중요한 티켓 정보가 더 안전하게 보존될 수 있겠네요!

2022-03-05 07:37 UTC, Yboyu0u commented on src/main/java/domain/Tickets.java
> +		this.tickets = tickets;
컬렉션을 받을 때 List.copyOf()로 복사한 후 필드에 대입하도록 수정했습니다!

2022-03-05 07:40 UTC, Yboyu0u commented on src/main/java/domain/WinningAnalyze.java
>  		return analyzeResult;
앗 감사합니다!!

2022-03-05 12:27 UTC, Yboyu0u commented on src/main/java/domain/Ticket.java
>  	private static final int CONDITION_FOR_CHECK_BONUS_BALL = 5;
Rank를 구하는 로직을 Rank로 위임했습니다!

2022-03-05 12:57 UTC, Yboyu0u commented on src/main/java/domain/Rank.java
>  			.orElseGet(() -> null);
알아본 결과, orElseGet은 null일 경우에만 Supplier를 호출하는 것이고 orElse는 null이 아니여도 호출되는 것이네요. 
orElse는 의도치 않은 함수 호출을 주의해야 하지만 저 부분에선 위에서 filtering을 해주기 때문에 간단하게 orElse를 쓰는 것이 옳아보입니다!

2022-03-05 15:34 UTC, Laterality approved these changes
안녕하세요 잉,

잘 수정해주셨네요 👍 

코멘트 드릴만한 곳이 별로 없어서, 이번 미션은 이만 머지하도록 할게요.

고생 많으셨습니다 :)

2022-03-05 15:34 UTC, Laterality commented on src/main/java/domain/dto/ManualTicketsDto.java
> +import java.util.Collections;
사용하지 않는 `import`는 지워주세요~

2022-03-05 15:34 UTC, Laterality commented on src/main/java/domain/TicketMachine.java
> +	public static Tickets generateTickets(final TicketCounter ticketCounter,
나름대로 기준을 가지고 만드신 거라면 그걸로 충분합니다 👍 

참고로, static 메서드는 자식 클래스에서 오버라이딩할 수 없다는 특징이 있어요.

2022-03-05 15:34 UTC, Laterality commented on src/main/java/domain/Rank.java
> +	}
아래 테스트를 실행해보면 어떤 결과가 나올까요?

```java
        Tickets tickets = new Tickets(Arrays.asList(new Ticket(Arrays.asList(1,2,3,4,5,6))));
        WinningNumber wn = new WinningNumber(Arrays.asList(1,2,3,4,5,7), 9); // 5개 일치, 보너스 미일치
        assertThat(Rank.getRanks(tickets, wn)).isEqualTo(Rank.THIRD_GRADE);
```

2022-03-05 15:35 UTC, merged