[2단계 - 로또(수동)] 토닉(최우석) 미션 제출합니다.
woowacourse/java-lotto pull request #467
Opened 2022-03-02 15:26 UTC by tonic523

안녕하세요 카일!
1단계 때 받았던 피드백을 기반으로 2단계를 구현했어요.
2단계 구현에서는 `객체에게 메시지를 보낸다!` 라는 목표를 가지고 진행했어요.
```java
public Result(Lottos lottos, WinningLotto winningLotto) {
        for (Lotto lotto : lottos.getLottos()) {
            // 로직
        }
    }
```
- Lottos와 Result 중 어디에 있으면 좋을지 한 번 더 고민해보고 공유해주시면 좋을 것 같아요.

처음엔 이해하지 못했는데 단점은 찾을 수 있었어요.
위 코드에서는 Result가 당첨 번호와 로또들을 가지고 와서 직접 비교하는 것인데 이 때 Lottos의 컬렉션을 가지고 와서 직접 구현해야 하는게 역할에 맞지 않다고 생각이 듭니다. 그리고 도메인 사이에서 멤버(컬렉션)을 주고 받는 것도 좋지 않은 방법이라고 생각이 들었어요.
```java
// Lottos 클래스
    public Result getResult(WinningLotto winningLotto) {
        Result result = new Result();
        for (Lotto lotto : lottos) {
            LottoRanking ranking = winningLotto.getLottoRanking(lotto);
            result.add(ranking);
        }
        return result;
    }
```
위 코드처럼 Lottos가 당첨번호를 받아오면 내부에서 각 로또들과 비교하여 결과를 반환하는 방법이 조금 더 역할에 맞는 기능을 수행하는 것 같습니다. 제 의견은 이런데 카일은 어떻게 생각하는지 궁금해요!

2022-03-03 11:58 UTC, KIMSIYOUNG requested changes
안녕하세요 토닉!
전체적으로 역할이 잘 분리되어 있어서 가독성이 참 좋은 것 같습니다🙂
고민하셨던 부분에 대한 답변은 코멘트로 남겼습니다. 추가적인 코멘트 조금 남겼는데 확인 부탁드려요.

궁금하신 내용은 언제든 말씀주세요.

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = buyLottos();
로또 구매와 결과 출력 두가지만으로 로또 프로그램을 설명하기엔 어려움이 있는 것 같아요.
아래와 같은 행위들도 드러날 수 있도록 메소드가 담당하고 있는 기능을 조금 줄여보는 건 어떨까요?

- 로또를 구매하기 위한 금액을 입력받는 행위 
- 각 과정을 출력하는 행위
- 당첨번호를 입력받고 결과를 생성하는 행위

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +            money.pay(Lotto.PRICE, count);
토닉에게는 `당연히 수동로또를 산 만큼 돈을 깎아야지`라는 생각이 있을 수 있지만, 누군가는 원래의 금액을 그대로 두고 장수만을 살 수도 있을 것 같아요.

그렇기때문에 해당 메소드는 `수동로또갯수를 요청한다`라는 메소드로 설명할 수 없는 (예상하지 못한 동작) 행위를 하고 있는 것 같아요.

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +        requestBuyManualLottoNumbers(manualLottoCount, lottos);
로또프로그램에서 구매할 수 있는 로또갯수를 기준으로, 전체갯수 - 수동으로 입력한 갯수가 자동로또의 갯수가 되는데요.

해당 요구사항을 명확하게 드러낼 수 있는 객체를 추가해보면 어떨까요?

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +            Number bonusNumber = NumberFactory.valueOf(input);
자동로또의 경우 `auto`라는 메소드를 사용하는데 요 부분은 `valueOf`를 사용하는 이유가 있으실까요?

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Lottos.java
> +        Result result = new Result();
저도 동일하게 생각했어요🙂

결과객체가 각 로또와 우승번호를 비교하기 위해서는 로또들의 값을 꺼내와서 비교하는 형태로 진행될 것 같아요(기존에 토닉의 코드)
로또를 관리하고 있는 `Lottos`에서 각 값들을 계산해서 Result를 생성한다면 자신이 가지고 있는 로또의 결과값을 직접 메시지를 보낼 수 있기에 적절하지 않나 생각했어요.

추가로 `Result` 객체를 생성과 동시에 결과를 만들어내는 것과 (생성자를 통한 결과완성) 현재처럼 생성 후 각 결과값들을 넣어주는 방식의 장단점도 같이 고민해보면 좋을 것 같아요.

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Lottos.java
> +        return new Money(lottos.size() * Lotto.PRICE);
기존에 `구매금액` 이라는 값을 수동로또를 생성하며 금액을 차감했기 때문에 `Lottos`는 로또 한장의 가격까지 알아야하는 의존이 생긴 것 같아요. 

우리의 프로그램에서 거스름돈을 줘야한다는 요구사항이 없는만큼 기존 금액을 차감하지 않고 다른 코멘트에서 드린 것 처럼 장수로만 제어한다면 해당 의존도 없어질 수 있을 것 같아요. 

만약 거스름돈이라는 요구사항이 추가된다 하더라도 `Money`라는 값을 불변객체로 가져간다면 보다 현재와 같이 추가적인 의존이나,  금액이 차감되었기에 추가되는 로직들 없이 조금 더 가독성 좋은 코드를 만들 수 있을 것 같아요🙂

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Lottos.java
> +    public void add(Lotto lotto) {
일급컬렉션은 말 그대로 컬렉션의 역할도 존재하기 때문에 `add`라는 메소드도 자연스러운 것 같아요. 다만 `Result`에 남겼던 코멘트처럼 생성과 동시에 완성된 형태로 나오는 것과, 이렇게 각각 넣어주는 것의 장단점을 같이 고민해보면 좋을 것 같아요.

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/Money.java
>  public class Money {
`Lotto`라는 프로그램내에서의 `Money`지만 고민해보면 좋을 것 같은 포인트같아 말씀드려요.

제가 토닉의 코드를 이어받아 추가적으로 로직을 개발한다고 하면, `Money`라는 네이밍을 보면 아 금액을 포장한 값객체겠구나, Money끼리 연산을 지원하겠구나 라고 생각할 것 같아요. 

하지만 지금 Money는 로또를 구매하기 위한 금액이기 때문에 `1000`으로 나누어떨어져야한다는 제약사항이 있어요. 순수한 `Money`는 아니게 되는거죠.

그렇기때문에 개인적으로는 LottoMoney / PurchaseMoney 와 같이 이 금액은 구매를 위한 금액이고 제약사항이 있다라는 것을 명시할 수 있는 이름을 사용할 것 같아요.

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoRanking.java
> +        public boolean match(int count, boolean containsBonus) {
요 부분은 내부적으로 가지고 있는 필드값들을 비교하고 있는데 해당 방식으로 구현하신 이유가 있으실까요?

2022-03-03 11:58 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/factory/LottoFactory.java
>  public class LottoFactory {
Lotto와 같이 생성과정이 복잡하고 그 자체로 중요한 로직을 담고 있다면 지금과 같이 `Factory`의 형태로 분리하는 것도 좋은 것 같아요. 

다만 `MoneyFactory`와 `NumberFactory`가 분리하신 이유는 어떤것인지 공유해주실 수 있나요?

2022-03-04 04:10 UTC, tonic523 reviewed
이번 피드백에서는 주로 이름이 클래스, 메소드 역할에 적합한지? 에 대해 물어보셨던 것 같아요!

> 불변 객체

add라는 메소드로 언제든 변할 수 있는 컬렉션을 가지고 있었어요. 그러다보니 해당 객체를 사용하는 입장에서 변할 수 있는 데이터라는 불안감이 있을 것 같습니다. 처음엔 추가하는 기능도 이 객체가 담당해야 한다고 생각했는데 불변한 객체가 조금 더 우선순위에 있는 것 같아요.

> 역할에 맞는 이름

이 부분이 저는 많이 헷갈리는 것 같아요
- 컨트롤러 메소드의 이름은 비즈니스 로직이어야 하는가? 아님 메소드가 실제 하는 행위를 담고 있어야 하는가?
- lotto 패키지 내부에 있는 클래스에도 Lotto 를 붙여줘야 할까?

우선 저는 요청과 출력을 기준으로 나누어 구현했습니다. 그리고 패키지 내부에 있는 클래스는 그래도 패키지 내부에 있기 때문에 굳이 작성하지 않아도 괜찮지 않을까? 라는 생각입니다!
그리고 팩토리는 정적 팩토리 메소드를 묶어 놓은 곳 이라는 의미로 다른 클래스도 뺐어요. 생성이 복잡하진 않지만, 사용자의 통일성을 위해 분리했습니다.

> Count

저는 이 객체의 역할을 로또를 구매할 개수 그리고 개수만큼 구매해주는 역할로 정했어요.

2022-03-04 04:10 UTC, tonic523 commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = buyLottos();
메소드의 이름만으로 행위를 드러내려면 카일 의견이 맞는 것 같아요!

> 로또를 구매하기 위한 금액을 입력받는다.

- 로또를 구매하기 위한 금액을 입력

> 로또를 구매한다

- 수동 로또를 사기 위해 요청하는 기능
- 수동과 자동을 가진 로또 객체 생성
- 구매한 로또를 출력

> 당첨 번호를 입력한다

- 당첨 번호 입력, 보너스 번호 입력

> 결과를 알려준다.
- 결과 출력

쓰다보니 카일 의견이 무슨 의미인지 알 것 같아요! 그런데 저 묶음 단위로 구현하면 출력도 포함되어야 한다고 생각하는데 카일 의견은 어떤가요? 컨트롤러의 메소드는 비즈니스 내용이 담긴 이름을 작성해야 한다는 생각도 있어요

2022-03-04 04:10 UTC, tonic523 commented on src/main/java/lotto/controller/LottoController.java
> +            money.pay(Lotto.PRICE, count);
네.. 이 부분은 작성하면서도 찝찝했어요 주어진 돈으로 얼만큼 수동을 살 수 있는지, 수동이 몇장이면 자동은 몇장이야 라는 역할을 어떤 객체가 담당해야할지 어려웠네요. 장수를 담당하는 Count 객체를 구현해서 위 역할을 맡게 하면 좋을 것 같아요!

2022-03-04 04:10 UTC, tonic523 commented on src/main/java/lotto/controller/LottoController.java
> +            Number bonusNumber = NumberFactory.valueOf(input);
문자열을 파싱하는 의미에서 해당 변수명이 좋다고 생각했고 이펙티브 자바에서 표준화된 방식을 선택한 것도 이유 중 하나에요. 그런데 로또라는 객체에선 자동을 auto로 지었으니 manual로 하는 것이 더 이해하기 좋을 것 같군요!

2022-03-04 04:10 UTC, tonic523 commented on src/main/java/lotto/domain/LottoRanking.java
> +        public boolean match(int count, boolean containsBonus) {
각 순위가 매칭이 되는지 비교하는게 맞는 역할이라고 생각했어요. 다른 순위는 단순히 개수만 비교하면 됐는데 2등과 3등이 보너스 번호의 매칭 유무도 판단해야했는데 이 부분을 한 메소드에서 구현하려고 하니 모든 순위의 역할을 한 곳에 모은 느낌이더라구요. 정말 만약에 순위의 매칭 조건이 달라지더라도 각 순위의 매칭 기준만 오버라이딩으로 바꿔주면 되니 수정에도 용이하다고 생각했습니다!

2022-03-04 04:10 UTC, tonic523 commented on src/main/java/lotto/domain/Money.java
>  public class Money {
네 확실히 그냥 Money라고 하면 오해할 수 있겠네요..
지금은 Money가 domain/lotto 밖에 있는데 이 패키지 안에 넣어줬을 때 고민이 있습니다.
1. lotto 패키지 안에 Money이니 로또에 관한 Money구나
2. 그래도 사용할 땐 Money이니 클래스이름에 명시해줘야지!

이 두가지에서 카일은 어떤 의견인가요? 혹시 다른 이유가 있다면 알려주시면 감사하겠습니다!

2022-03-04 04:10 UTC, tonic523 commented on src/main/java/lotto/domain/factory/LottoFactory.java
>  public class LottoFactory {
통일성 때문에 분리했어요. 생성과정이 복잡하진 않지만 Lotto에서 정적 팩토리 메소드를 팩토리에 모았으니 다른 클래스의 팩토리 메소드도 팩토리에 모아야하지 않을까? 라는 의견입니다.

2022-03-04 04:10 UTC, tonic523 commented on src/main/java/lotto/domain/lotto/Lottos.java
> +    public void add(Lotto lotto) {
add를 통해 외부에서 컬렉션에 데이터를 변경할 수 있을 것 같아요. 생성과 동시에 완성된 형태라면, 이 객체는 불변하다는 보장이 있어 객체를 사용하는 입장에서 편할 것 같습니다.

2022-03-05 13:16 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos lottos = buyLottos();
비즈니스로직을 실행하는 행위와 출력하는 행위는 분리되는 것이 관심사가 분리되는 것이라 생각이 되어요. 

두 가지의 역할이 하나의 메소드에 들어가는 것 보단, 각각 관리될 때 역할이 하나기 때문에 유지보수하기 용이한 코드가 아닐까 라는 생각을 하고 있습니다.🙂

2022-03-05 13:17 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +            Number bonusNumber = NumberFactory.valueOf(input);
맞아요🙂 정적팩토리메소드의 이름의 표준패턴을 사용하신 것은 좋지만, 현재는 자동로또와 수동로또라는 대립되는 개념이 있기 때문에 manual 로 작성하는 것이 더 가독성이 좋을 것 같습니다.

2022-03-05 13:19 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Lottos.java
> +    public void add(Lotto lotto) {
저도 동일하게 생각이 되어요🙂 

생성시 결과값 생성에 필요한 모든 데이터를 전달하고, 이를 통해 불변하는 결과값을 만들어 낸다면 버그 가능성이 줄어들 수 있을 것 같아요. 값을 하나씩 더해주는 구조라면 실수나 잘못된 이해로 인해 다른 결과값을 충분히 만들어낼 수 있으니까요!

2022-03-05 13:20 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/Money.java
>  public class Money {
저는 개인적으로 후자를 선호하는 편이에요.

현재는 작은 프로그램이지만 앞으로 프로그램이 커질 때 각 클래스들의 패키지를 잘 안보게 되기도 하고, 코드 자체에서 드러나지 않기 때문에 놓치는 경우가 많더라구요. 
이런 부분을 지양하고자 저는 후자를 선호합니다🙂 다만 네이밍이 길어지는 단점도 분명 존재하는 것 같습니다.

2022-03-05 13:21 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/LottoRanking.java
> +        public boolean match(int count, boolean containsBonus) {
2등과 3등에게만 특별한 역할이 존재한다는 것이 잘 드러나는 형태인 것 같습니다. 👏 말씀하신대로 각 등수에 다른 로직들이 들어갔을 때 그 부분만 수정할 수 있기에 더 좋은 것 같아요.

2022-03-05 13:24 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/factory/LottoFactory.java
>  public class LottoFactory {
좋은 방법인 것 같습니다. 다만 개인적으로 생성자를 통한 생성과 팩토리를 통한 생성 두가지가 모두 가능할 때, 이 코드를 유지보수하는 사람이 이 두가지를 적절하게 잘 이용하기 어렵다는 단점도 있을 것 같아요. (객체 생성에 대한 역할을 두 곳에서 관리하고 있기 때문에)

그래서 저는 개인적으로는 객체생성의 롤을 객체에게 전담하도록 하는 편이고,  Lotto 와 같이 생성이 복잡한 일부분에 대해서만 팩토리를 사용하는 편이에요. 참고만 부탁드립니다🙂

2022-03-05 13:57 UTC, KIMSIYOUNG requested changes
안녕하세요 토닉!
이미 잘 구현해주셔서 많은 부분이 달라지진 않은 것 같아요.
Count 객체와 Controller의 메소드단위의 역할에 대해서 제 의견은 코멘트로 달아두었습니다. 궁금하신 내용은 언제든 말씀해주세요!

2022-03-05 13:57 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Lottos.java
> +    public Money totalPrice() {
첫 구매금액을 불변으로 만들었기 때문에 이제 해당 메소드가 필요없을 것 같아요🙂

그리고 로또 한장이 1000원이다라는 상수값도 Lotto가 아닌 Amount에서 관리할 수 있을 것 같습니다.

2022-03-05 13:57 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Count.java
> +    public void play(List<Lotto> lottos, Consumer<List<Lotto>> action) {
값객체로 갯수를 잘 포장해주셨네요🙂 두 번째 파라미터로 수동 또는 자동로또를 추가하는 행위를 담당하는 람다를 받고 있는데요.

현재 `Count`객체는 단순히 값을 포장한 객체의 역할정도만을 담당하고 있는 것 같아요. 즉 전체 구매장수에서 수동로또를 뺀 만큼이 자동로또의 가격이다 등의 비즈니스 로직이 없는 객체 같아요. 

객체의 역할을 만약 단순히 값을 포장한 객체정도로만 바라본다면 로또를 추가하는 행위도 여기서 이뤄지면 안된다라는 생각이 들어요. 다만 비즈니스로직을 포함한다면(자동과 수동의 갯수를 구하는 로직 등) 이 객체의 역할을 조금 더 넓게보아서 로또를 추가하는 행위를 전달받고 각 장수에 맞게 생성한다까지 담당하는 객체가 될 수 있을 것 같아요.

2022-03-05 13:57 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Count.java
> +    public void play(List<Lotto> lottos, Consumer<List<Lotto>> action) {
추가로 Count라는 객체에서 로또를 추가하는 행위를 람다로 받아 실행해주는 부분이 조금은 어색하게 느껴지는 것 같아요. 

LottosFactory 혹은 LottoFactory에서 Count라는 객체에게 수동로또와 자동로또의 갯수를 물어보고 그 갯수에 따라 Lottos를 생성하는 건 어떨까요?

2022-03-05 13:57 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +    private void printResult(Lottos lottos, WinningLotto winningLotto) {
요 부분은 아직 비즈니스행위를 호출하는 것과 출력하는 것이 같이 있는 것 같아요. 

토닉이 작성해준, 컨트롤러의 메소드이름은 비즈니스로직이어야하는가, 실제하고 있는 행위인가 라는 것에서 실제하고 있는 행위가 어떤 것을 의미하는 지 알 수 있을까요?

저는 비즈니스메소드를 호출하는 행위와 출력하는 행위가 분리되어 있을 때 보다 가독성이 좋고 역할이 작아진다고 생각하고, 그런 형태로 말씀드렸었어요.

2022-03-07 07:21 UTC, tonic523 commented on src/main/java/lotto/domain/lotto/Lottos.java
> +    public Money totalPrice() {
네 제가 구현한 Money는 로또의 가격 단위로 했기 때문에 해당 메소드가 필요없을 것 같아요.
만약 구매한 로또의 총합 금액을 기준으로 본다고 했을 땐 위 로직이 필요하다고 생각합니다.
그리고 로또의 가격을 로또가 알아야지 라는 생각이여서 public으로 열어놓았는데 가격에 대한 부분은 Money에서 대부분 이루어지기 때문에 Money에서 알아야 하는 상수인 것 같네요.

2022-03-07 08:09 UTC, tonic523 commented on src/main/java/lotto/controller/LottoController.java
> +    private void printResult(Lottos lottos, WinningLotto winningLotto) {
아 저는 컨트롤러에서 비즈니스 메소드엔 출력도 포함될 수 있다고 얘기드리고 싶었는데 잘못 전달한 것 같네요 ㅠㅠ 출력까지 비즈니스 로직에 합친다면 컨트롤러 내부에서 깔끔하게 보일 수 있다고 생각을 했었는데 생각을 정리해보니 분리하는게 맞는 것 같아요.
컨트롤러에서 뷰와 모델의 데이터를 전달하는 역할이기 때문에 메소드에서도 확실하게 모델(도메인)끼리의 데이터를 가공하는 과정과 출력하는 부분은 분리하는게 맞는 것 같습니다.

2022-03-07 08:13 UTC, tonic523 commented on src/main/java/lotto/domain/lotto/Count.java
> +    public void play(List<Lotto> lottos, Consumer<List<Lotto>> action) {
컨트롤러에서 count의 값을 꺼내와서 직접 while문을 통해 add하는 것이 비즈니스 로직이라고 생각했고 반복해주는 역할로 Count에 구현했는데, 저도 구현하면서 어색하다고 느꼈습니다.. 
Count에서 로또를 추가하는 행위를 팩토리에도 해보려 했지만, 수동은 입력을 요청해야 하는 로직 때문에 컨트롤러에서 담당해야 할 것 같아요. 혹시 이 부분에 적합한 객체나 방법이 있다면 알려주시면 감사하겠습니다!
Count 관련해서 하다보니 구입 금액과 수동 로또 개수를 통해 자동 로또 개수를 구하는 역할을 하는 객체가 필요하다고 생각했어요. Count의 단순히 값을 포장한 객체의 역할을 유지한채 앞서 얘기한 기능을 수행하는 LottoCountToBuy라는 클래스를 구현해보았습니다.

2022-03-07 08:30 UTC, tonic523 commented
카일 2단계까지 리뷰해주셔서 정말 감사드려요!
리뷰하는 동안 의견을 물어봐주시고 카일의 의견도 들을 수 있어서 너무 좋았습니다.
`객체에 메시지를 보내라` 라는 것과 변수, 메소드 명 작성의 중요성을 알게 된 것 같아요.
아직 객체지향 관점에서의 프로그래밍이 낮설고 어렵게 느껴져서 관련 책들을 읽어보면서 객체 설계의 관점에서 많이 배워야겠다고 느꼈습니다.
거의 마감 시간에 리뷰요청을 드려 아쉬움이 많네요.. 혹시 현재 제가 알아야 할 내용이나 부족한 점들을 알려주시면 다음 미션 때 방향을 잡는데 도움이 될 것 같아요! 마지막으로 확인해주시고 알려주시면 정말 감사하겠습니다 ㅎㅎ

2022-03-09 07:22 UTC, KIMSIYOUNG approved these changes
안녕하세요 토닉!
리뷰 잘 반영해주셨네요🙂
1, 2 단계동안 고생많으셨습니다!
 궁금하신 내용은 언제나 편하게 말씀주세요!

2022-03-09 07:22 UTC, merged

2022-03-09 13:15 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Lottos.java
> +    public Money totalPrice() {
좋은 관점에서 접근해보신 것 같아요. 저는 해당 메소드에 대한 부작용중 가장 큰 부분이 두가지 인 것 같아요.
- 실제로 사용자가 입력한 금액이지만, 그 금액은 다른 로직에 의해 변경되고 / 변경된 로직을 역추적하여 실제 사용자가 입력했던 값을 알아내는 행위 자체가 비즈니스 로직을 과도하게 복잡하게 하는 것 같아요. 물론 가능한 구조이고 이 방법밖에 없다면 사용할 수 밖에 없겠지만, 비즈니스 로직이 필요이상으로 과도하게 복잡해지는 건 지양할 수 있으면 지양하자라는 관점이에요🙂
- 그리고 말씀해주신대로 `로또의 가격을 로또가 알아야지` 가 아니라 로또의 가격에 대한 부분은 `Money`에서 담당하는 역할이 맞고 가격에 대한 의존이 두 객체 모두에게 전파되기 때문에 위험한 것 같아요

결론적으로는 비슷한 의견으로 비슷한 코드형태로 변경된 것 같습니다🙂

2022-03-09 13:24 UTC, KIMSIYOUNG commented on src/main/java/lotto/domain/lotto/Count.java
> +    public void play(List<Lotto> lottos, Consumer<List<Lotto>> action) {
갯수에 대한 비즈니스 로직(전체 갯수 - 수동로또의 갯수 = 자동로또)가 해당 객체로 드러나기 때문에 잘 포장해주신 것 같아요🙂


혹시 이 부분에 적합한 객체나 방법이 있다면 알려주시면 감사하겠습니다!
- 로또를 생성하는 행위는 LottoFactory 에서 담당하지만 몇개를 얼마나 생성할 것인지는 누가 담당해야하는가? 는 누구의 로직인가 라는 질문으로 이어지는 것 같아요. 
- 이 부분에 대해서 정답은 없지만 개인적으로는 LottoFactory 에서 로또 하나를 생성하는 메소드가 아닌, 총 생성하려는 갯수와 생성을 위한 값 (List<Number>)를 여러개를 받는다면 LottoFactory 를 사용하는 사람도 하나를 생성할 때, 여러개를 생성할 때 두가지 다 유연하게 사용할 수 있을 것 같아요.
- 반대로 몇개를 생성할 것인지에 대한 룰은 사용자입력기반이기에 컨트롤러에서 반복적으로 수행하는 것(직접 While문을 도는 것)도 괜찮은 역할이라는 생각이 들어요. 모든 역할들을 도메인으로 분리하려는 것도 좋지만 우리 `프로그램의 실행흐름`을 제어하는 역할은 `Controller`이기에 입력기반의 도메인 호출의 횟수를 정하는 것은 `Controller`에서 해도 되지 않을까 생각합니다.

두 가지 의견중 개인적으로는 전자를 선호해요🙂 컨트롤러에게 몇 번 실행하는 것인가에 대한 역할을 위임하면서도 다른 객체들이 해당 메소드를 사용할 때도 보다 다양한 형태로 사용할 수 있기 때문에 그런 것 같습니다.

2022-03-09 13:32 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +    private void printResult(Lottos lottos, WinningLotto winningLotto) {
앗 저도 토닉의 의견에 일부 공감합니다! 

컨트롤러에서 행위와 출력이 같이 되는 경우가 자연스러울 때도 있는 것 같아요. 다만 그 부분은 `조회`에 한정했을 때 조금 더 자연스러운 것 같아요. 일반적으로 웹에서 예를 들면, 결과를 만들어내는 행위는 응답값이 없지만 만들어진 결과를 호출하는 메소드의 경우 조회와 출력과 함께 있는 경우가 많은 것 같습니다.

하지만 현재는 결과를 만들어내는 로직이기 때문에 출력과 분리하는 것이 조금 더 역할의 선을 명확하게 긋는 것이 아닐까 라는 생각이 들어요🙂

2022-03-09 13:34 UTC, KIMSIYOUNG reviewed
안녕하세요 토닉!

답변해주신 부분에 대한 제 의견도 추가해두었습니다🙂 1, 2단계동안 너무 고생하셨습니다. 코드가 매우 깔끔한 것 같아요!!👏