[2단계 - 로또(수동)] 범고래(조충범) 미션 제출합니다.
woowacourse/java-lotto pull request #469
Opened 2022-03-02 16:19 UTC by cndqjacndqja

<b>안녕하세요 스티치~ 범고래입니다 😊 </b>

1단계 피드백 감사합니다! 2단계도 잘 부탁드립니다🙏

### 추가 질문
이번에 크게 수정된 부분은 Main메소드와 LotteryConverter입니다.
메인 메소드는 프로세스의 시작 지점이니, 코드를 보았을 때 가독성이 좋아야 할 것 같았는데요!
이전에 ```InputView를 호출하고 객체를 생성하는 부분```이 Main에 있다 보니, 코드를 깔끔하게 하고 싶었지만 방법을 찾지 못했었습니다 😂

그래서 ```InputView를 호출하고 객체를 생성하는 부분```을 LotteryConverter가 수행하게 해주었습니다.
클래스 파일 위치는 Main에서 의존하고 있다고 생각하여 Main과 동일한 곳에 위치하게 했습니다.

혹시 해당 역할을 다른 클래스에 위임하는 것이 괜찮을까요?
구체적인 이유는 의문점이 들었던 코드에 코멘트로 달겠습니다!

+ 아 그리고 혹시.. 미션이 끝나기 전까지 해결하지 못한 궁금한 점이 생기면 DM으로 여쭤봐도 될까요?!🤭

2022-03-02 16:22 UTC, cndqjacndqja commented on src/main/java/lotterymachine/LotteryConverter.java
> +    }
여기서 InputView를 호출해서 List<LotteryTicket>을 만드는 createPassivityLotteryTickets(), createAutoLotteryTickets() 두 개가 존재하는데요!
이런 방식은 하나의 메소드에서 두 가지 일을 한다는 시점에서 지양해야 할까요??
아니면 LotteryTickets를 만든다는 관점에서 하나의 일을 수행한다고 봐도 무방할까요??🤣

2022-03-02 16:24 UTC, cndqjacndqja commented on src/main/java/lotterymachine/LotteryConverter.java
> +    }
여기서 "수동으로 구매할 번호를 입력해 주세요."라는 출력문도 사용했는데, 이 부분은 OutputView로 빼주는 것이 좋을까요?
아니면 createPassivityLotteryTickets()내에서 수행해야 한다는 관점에서 해당 메소드에서 바로 출력을 하는게 좋을까요?!
정답이 없을 수 있겠지만, 스티치의 생각이 궁금합니다!😊

2022-03-02 16:28 UTC, cndqjacndqja commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    private final int passivityCount;
처음에는 LotteryPurchase가 로또 구매라는 이름으로 지었기 때문에, Money를 가지고 있어도 된다고 생각하여 작성했습니다!
하지만 Money, 자동 구매 개수, 수동 구매 개수 라는 세 가지 속성을 가져도 되는건가? 생각이 들었습니다. LotteryPurchase가 해당 필드를 가지고 있어도 괜찮을까요??

이와 관련해서 지난 번 스티치의 피드백을 다시 언급하자면, "해당 클래스가 ticketCount를 맴버 변수로 가지고 있는 것이 어색한 것 같아요!!" 와 같은 생각에 저도 동의 했습니다!
하지만 명확한 이유보다는 어색하다는 느낌이 더 크게 드는 것 같습니다...!
이렇게 해당 객체가 가지는 속성해 대해 판단할 때는 이름, 해당 객체의 역할 등등을 고려하여 판단하는 것 일까요?

2022-03-02 16:31 UTC, cndqjacndqja commented on src/main/java/lotterymachine/domain/LotteryNumber.java
> +    }
1단계에서 말씀해주신 "IntegerCache 클래스를 참고해 보고 캐싱해서 가지는 것은 어떨까요?"의 피드백을 반영해 본 것인데요!
혹시 이런 방식이 맞을까요~?!

2022-03-03 15:43 UTC, lxxjn0 requested changes
범고래, 2단계 미션 구현하느라 수고하셨어요!!

클래스를 다양하게 나눠보고 개선하려는 부분들이 잘 보였습니다!! 이번에도 클래스를 어떻게 적절하게 나눌 수 있는지와 이전에 누락했던 테스트 부분에 대한 피드백을 집중해서 남겨두었습니다!!!

한번 프로그램도 실행해봤는데 1000원 단위가 아닌 금액에 대해서도 코드가 정상적으로 실행되더라구요. 해당 부분도 이번에 한번 고쳐주시면 좋을 것 같아요!!

테스트 코드의 경우 작성한 모든 로직에 대해서 테스트가 작성되지 않은 것 같아요!! 이번에 한번 과하다 싶을 정도로 테스트를 짜보면 좋을 것 같아요!! 엣지 케이스도 한번 확인해보고 유효성 검증도 잘 되는지도 확인해보구요!! 테스트를 많이 짜보면 짜볼수록 속도는 점점 더 빨라질겁니다!! 트레이닝을 해본다고 생각하고 한번 짜보면 좋을 것 같아요!!

추가로 남겨주신 질물에 대해서도 코멘트 남겨두었습니다!! 확인 부탁드려요 :)

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryMachine.java
>  public class LotteryMachine {
main 메서드를 가지는 애플리케이션 클래스의 이름은 보통 `xxxApplication`의 양식을 따라갑니다. 해당 클래스도 애플리케이션 코드가 실행되는 클래스이므로 `LotteryMachineApplication`이라고 이름을 지어주면 좋을 것 같아요!! 
그렇게 하면 코드를 읽는 사람이 어떠한 클래스가 Application 코드가 실행되는 클래스인지 파악하기 쉬울 것 같습니다!! (저도 처음 코드를 봤을 때 조금 해매었거든요 ㅠㅠ)

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryConverter.java
> +public class LotteryConverter {
Converter라는 이름은 보통 데이터를 특정한 타입이나 포맷으로 변경해주는 역할을 하는 클래스에 붙입니다. 현재 클래스의 경우 객체를 생성하는 책임을 가지고 있어서 Converter라는 이름은 조금 적절하지 않은 것 같아요!!

그리고 현재 클래스의 경우 너무 많은 책임을 가지고 있어요. 다양한 인스턴스를 모두 생성하는 역할을 하고 있는데, Application에 다시 해당 코드들을 위치시키고 다른 방법으로 한번 코드를 다시 풀어보는 것도 좋을 것 같습니다 :) Application이 '전체 코드의 흐름을 제어하는 책임을 가진다' 라고 하면 기존의 코드도 나쁘지 않은 코드라고 생각해요. 

클래스를 만들 때 어떠한 책임을 가지는 지를 먼저 정의하고 클래스를 만들어보는 연습을 이번에 해보면 좋을 것 같아요!! 단순히 '클래스가 비대해져서 코드가 보기 지저분하다. 그래서 이를 구분지어서 분리해보자'라는 맥락보다는 '해당 클래스는 어떠한 역할을 하는 클래스야, 그래서 이런 코드들을 위치시키면 될 것 같아'와 같이 개선을 해보면 어떨까요???

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    public LotteryPurchase(int amount, int passivityCount) {
해당 클래스는 어떠한 책임을 가지고 있나요?? 로또를 구매할 때 필요한 값들을 관리한다고 보기엔 너무 객체가 가지는 행위가 적은 것 같아요.
만약 count에 대한 유효성 검증만 이뤄진다면 오히려 Count라는 객체를 만드는 것이 더 합리적이지 않을까요?? 정말 해당 클래스가 객체로 관리되어야 하는지, 그렇지 않다면 어떻게 클래스를 나눠야하는지 한번 고민해보면 좋을 것 같아요!! 👍🏼

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
> +    public static final List<LotteryNumber> numbers;
상수 네이밍 컨벤션에 맞지 않아요!!

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/Money.java
> +public class Money {
현재 Money가 가장 바깥 패키지에 위치하는데 실제로 가지는 성격은 도메인에 가깝다고 생각이 들어요. 혹시 도메인 패키지 밖에 둔 이유가 있을까요??

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
> +                .collect(Collectors.toList());
boxed를 하지 않고도 IntStream의 map 관련 중간 연산을 사용하면 해결할 수 있을 것 같아요!! :)

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
> +    }
생성자를 private로 막은 것 굿입니다!! 👍🏼 하지만 전체적으로 코드의 위치가 적절하지 않은 것 같아요!!

static 스코프 => 생성자 => static 메서드 => instance 메서드 순으로 나열되면 될 것 같아요!!!

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
> +    }
<img width="632" alt="image" src="https://user-images.githubusercontent.com/48052622/156585629-8d06f980-aee9-40d1-896c-311a5623296d.png">

intellij에서 해당 부분을 클릭 후 rearrange를 체크하고 실행하면 적절한 순서에 맞게 배열을 해줍니다!! IDE의 다양한 툴을 통해 많은 도움을 받을 수 있어요 :)

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTickets.java
>  package lotterymachine.domain;
불필요한 공백은 삭제해주세요 :)

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTickets.java
>  public class LotteryTickets {
현재 해당 클래스의 역할이 너무 없어보여요. 정적 팩토리 메서드를 구현해서 LotteryConverter가 가지던 LottoTickets 생성 책임을 해당 도메인이 가지도록 하는 건 어떨까요?? 다양한 생성 메서드를 지원해주는 것으로도 도메인이 풍부해질 것 같아요!!
추가로 해당 도메인을 사용할 수 있는 방법도 함께 고민해보면 좋을 것 같습니다 :)

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/WinningLottery.java
>  public class WinningLottery {
해당 클래스의 numbers 맴버 변수가 List<LotteryNumber> 타입으로 관리되고 있어요!! 이걸 LotteryTicket 타입으로 관리하면 어떨까요?? 지금 코드에서 어떠한 이점을 가져갈 수 있을지도 한 번 확인해보면 좋을 것 같아요!!

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryConverter.java
> +    }
해당 메서드가 LotteryTickets를 만드는 역할이라면 지금의 메서드는 적절한 것 같아요!! 결국은 특정 메서드에서 createPassivityLotteryTickets, createAutoLotteryTickets 메서드의 결과를 합쳐야 하기 때문이죠. 

메서드의 역할만 명확히 한다면 지금의 코드는 적절한 것으로 보입니다!!

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/WinningLotteryRank.java
> +    }
this로 해당 클래스의 생성자를 호출할 수 있어요!! this로 생성자를 호출하는 방법을 한번 찾아보고 개선해보면 좋을 것 같아요!! :)

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryConverter.java
> +    }
특정한 코드가 현재 클래스에 위치를 하는게 어색하다고 느껴진다면 클래스를 다시 돌아보면 좋을 것 같아요. 왜 지금 클래스에서 출력문이 등장하는게 어색하지? 지금 클래스의 책임은 뭐지? 그렇다면 지금 코드는 어떻게 되야하지?? 클래스를 다시 구분해야하나? 이런 식으로요!!!

LotteryConverter 클래스에 대한 저의 생각을 위에 코멘트에서 남겨놨으므로 한번 참고해보시면 좋을 것 같아요!!! :) 만약 범고래가 '현재의 제가 가지는 생각'이 궁금하다면 '현재 클래스가 적절하지 못한 것 같다. 너무 다양한 책임을 가지고 있어서 이런 부분에서 혼란이 오는 것으로 느껴진다. 만약 해당 코드들이 전체 프로그램의 프로세스가 구현된 곳에서 사용되었다면 어색하지 않았을 것이다. 현재는 생성을 책임지는 곳에서 출력과 입력까지 담당하고 있으므로 코드가 어색하게 느껴지는 것같다'라고 답할 수 있을 것 같아요!!

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/WinningResult.java
> +    private final WinningLottery winningLottery;
코드를 보니 해당 맴버 변수들은 해당 클래스에서 관리될 필요가 없을 것 같아요!! 객체는 객체가 가지는 맴버 변수가 해당 객체의 존재 의의를 나타냅니다.
그런 관점에서 해당 맴버 변수들이 정말 WinningResult가 가져야 할 값일까요?? 맴버 변수는 최소한으로 유지하는 것이 좋습니다!! 해당 클래스를 한번 개선해보면 좋을 것 같아요!! 👍🏼

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/utils/LotteryCalculator.java
>  public class LotteryCalculator {
범고래는 유틸리티 클래스를 어떠한 상황에서 만드는 것이 적절하다고 생각하나요??

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/utils/LotteryNumbersGenerator.java
>      }
LotteryNumbersGenerator의 역할을 LotteryNumber가 대신할 수 있을 것 같은데 어떤까요?? 만약 LotteryNumber에서 랜덤한 6개의 번호를 뽑아내는 기능이 과하다고 생각이 된다면 캐싱된 값만 가져와서 활용해봐도 괜찮을 것 같아요!! (그런데 이런 구조로 작성한다면 Generator의 크기가 너무 작아서 LottoNumber에 두는 게 낫다고 생각할 수도 있을 것 같네요.. 😭 )

한번 범고래가 코드를 개선해보고 차이점을 느껴보면 좋을 것 같아요. (이전 코드가 나은지, 개선한 코드가 나은지도 한번 같이 이야기해보면 좋을 것 같아요!! )

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
>      public static List<LotteryNumber> getWinningLotteryNumbers() {
현재의 View는 너무 많은 책임을 가지고 있어요!! 입력을 받는 것부터 객체를 생성하는 책임까지 가지고 있습니다!! 보다 객체지향적인 관점으로 코드를 개선해보면 좋을 것 같아요!! 입력을 받아오는 view의 책임은 어디까지고 역할은 어디까지인지, 받아온 입력을 생성하는 책임은 어디서 가지고 있어야 할지 등등 고민해보면 많은 도움이 될 것 같아요!!

2022-03-03 15:43 UTC, lxxjn0 commented on src/test/java/lotterymachine/LotteryPurchaseTest.java
> +class LotteryPurchaseTest {
해당 클래스의 유효성 검증에 대한 부분은 테스트가 되지 않고 있어요!!

2022-03-03 15:43 UTC, lxxjn0 commented on src/test/java/lotterymachine/domain/LotteryNumberTest.java
>  class LotteryNumberTest {
Comparable도 구현하였고 캐싱 기능도 추가했는데 테스트가 없습니다.. ㅠㅠ

2022-03-03 15:43 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
>      }
추가로 확인해보니 현재는 get으로 값을 가져오기 위해서 필요하지 않은 0에 대한 LottoNumber도 생성하고 있네요. 만약 numbers에서 실수로 1에 해당하는 LottoNumber를 지우고 다시 추가하면 현재 메서드는 모두 틀린 LottoNumber를 반환해줄 것 같네요. 

정수를 받았을 때 그에 맞는 올바른 LottoNumber를 항상 받을 수 있도록 코드를 개선해보면 좋을 것 같아요!!

2022-03-03 15:43 UTC, lxxjn0 commented on src/test/java/lotterymachine/domain/LotteryTicketTest.java
>      void countMatchingNumbers(String winningNumbers, int expected) {
해당 클래스에도 모든 테스트가 꼼꼼히 구현되어 있지 않은 것 같아요!! 한번 확인 부탁드릴게요!!

2022-03-03 15:44 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
> +    }
넵넵!! 맞습니다. 하지만 해당 코드에서 추가로 개선이 필요할 것 같은데 리뷰 참고 부탁드릴게요!! :)

2022-03-03 15:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    private final int passivityCount;
객체로 관리할 클래스의 경우 '해당 클래스를 객체로 관리했을 때 과연 적절한가?'를 한번 생각해보면 좋을 것 같아요!! 객체로 구현한다는 것은 책임을 가지면서 그에 맞는 적절한 행위들을 한다고 봐야합니다. 

그러나 현재 LotteryPurchase의 경우는 행위가 거의 존재하지 않습니다. 단순한 유효성 검증인데 이 또한 Count에 대한 유효성 검증에 불과합니다. 만약 유효성 검증을 위해서 클래스를 구분했다면 count만을 감싸는 클래스를 구현해도 충분했을 것 같아요.

또한 사용되는 부분을 보더라도 사실 LotteryPurchase 객체가 아닌 개별적인 요소로 사용되어도 무리가 없어보이는 부분들이 많았어요. 그냥 묶어서 관리하고 싶어서 만들어낸 클래스 정도에 지나지 않는다는 생각은 들었습니다!! 과연 해당 객체가 가지는 맴버 변수들이 LotteryPurchase라는 이름의 객체가 가지기에 적절한지 한번 고민해본다면 보다 좋은 객체 단위로 구현이 가능할 것 같아요!!

2022-03-05 15:37 UTC, cndqjacndqja commented on src/main/java/lotterymachine/LotteryConverter.java
> +public class LotteryConverter {
현재는 Converter에서 해주는 역할을 Main이 아닌 각 클래스에 역할을 위임하여 해결해 본 상태입니다.
하지만 언급해 주신 “저 부분을 Application이 전체 코드의 흐름을 제어하는 책임을 가진다 라고 하면 기존의 코드도 나쁘지 않은 코드가 아니라고 생각해요” -> 이 부분에 대해서 생각이 많아지게 되었는데요 🤣

Converter의 역할 자체가 많다면 Main으로 옮기더라도 똑같은 상황이 되는 것이 아닌가 했습니다.
만약 Converter가 "전체 코드의 흐름을 제어하는 책임을 가진다"의 의미를 포함한 이름으로 변경된다면, 해당 역할을 Application으로 옮겼을 때 처럼 나쁘지 않은 코드가 되는 것일까요??

2022-03-05 15:57 UTC, cndqjacndqja commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    public LotteryPurchase(int amount, int passivityCount) {
현재는 vo 패키지의 Count, Money로 나누어 해결해 본 상태입니다.
하지만 스티치가 의도한대로 생각하고 행동하지는 못한 것 같습니다😭

**문제 인식 과정**
1. LooteryPurchase의 이름에 맞지 않는 역할을 하는 것 같다.
2. 해당 클래스의 역할과 책임에 대해 명확하게 정의하지 못하겠다.

**해결하기 위한 생각 과정**
Count라는 로또 구매 개수를 표현하는 클래스를 만들자.
-> 수동 구매 개수, 자동 구매 개수에 대한 정보를 클래스로 만들지 않으면,  Main에서 int passivityCount, autoCount와 같은 변수로 표현하게 될 것 같은데, 의미 전달이 잘 안될 것 같다.

--- 
스티치의 피드백의 의도를 생각했을 때는 "각 객체가 어떤 역할을 수행해야 하는지를 먼저 생각해 본 후, 그것에 맞는 메서드(메세지를 보내 결과를 얻어 내는 것)를 구현해 보는 것"이 아닌가 싶었습니다.

현재 "Count라는 로또 구매 개수를 표현하는 클래스를 만들자."와 같은 생각은 객체 지향 설계를 하는 것과는 조금 멀어지는 생각 일까요??

2022-03-05 16:06 UTC, cndqjacndqja commented on src/main/java/lotterymachine/Money.java
> +public class Money {
저는 클래스의 위치를 생각할 때, 해당 클래스를 의존하는(사용하는) 클래스와 동일 위치에 두려고 했었습니다.
이유는 다른 클래스에 위치한다면 불필요한 import를 해줘야 한다고 생각했고, 해당 클래스들이 서로 영향을 주는(의존하고 있는) 클래스임을 알 수 있게 해준다고 생각했습니다.

스티치가 Money가 도메인 패키지 성격에 가깝다고 생각하신 이유는 로또 게임의 문제 해결 영역 중 일부라고 생각하셔서 도메인에 가깝다고 생각하신 걸까요??
도메인이라는 용어가 저에게는 조금 추상적이네요 😂

2022-03-05 16:25 UTC, cndqjacndqja commented on src/main/java/lotterymachine/domain/LotteryTickets.java
>  public class LotteryTickets {
현재는 수동 로또 리스트, 자동 로또 리스트를 매개 변수로 받아 LotteryTickets를 생성하는 정적 팩토리 메서드를 만든 상태입니다 😊

2022-03-05 16:28 UTC, cndqjacndqja commented on src/main/java/lotterymachine/domain/WinningLottery.java
>  public class WinningLottery {
이 부분은 변경하기 전에는 이유를 찾지 못해서, 일단 적용해 봤더니 알게 됐습니다.
이전에 numbers에 대한 검증을 WinningLottery에서 해주었는데, 이 역할을 이미 LotteryTicket에서 해주고 있어서
LotteryTicket 타입으로 관리했더니 중복된 검증이 사라지게 됐습니다 :)
혹시 언급해 주신 이점이 이런 이유가 맞을까요~?

2022-03-05 16:32 UTC, cndqjacndqja commented on src/main/java/lotterymachine/domain/WinningResult.java
> +    private final WinningLottery winningLottery;
```java
public static WinningResult create(LotteryTickets lotteryTickets, WinningLottery winningLottery) {
        initResult();
        for (LotteryTicket lotteryTicket : lotteryTickets.getLotteryTickets()) {
            WinningLotteryRank winningLotteryRank = winningLottery.getWinningLotteryRank(lotteryTicket);
            result.put(winningLotteryRank, result.get(winningLotteryRank) + 1);
        }
        return new WinningResult();
    }
```
위와 같은 정적 팩토리 메서드를 추가한 후, 해당 멤버 변수들은 제거했습니다.
WinningResult는 당첨 결과만 알면 되기 때문에, 나머지 두개의 멤버 변수를 관리할 필요는 없다고 생각하게 됐습니다.

2022-03-05 16:54 UTC, cndqjacndqja commented on src/main/java/lotterymachine/utils/LotteryCalculator.java
>  public class LotteryCalculator {
처음에는 divideByLotteryPrice, calculateProfitRate과 같은 연산 메서드를 유틸리티 클래스로 나눠주어도 괜찮을 것 같다고 생각했었습니다.
하지만 여러 클래스에서 공통적으로 사용되는 메서드가 아닐 뿐더러, 생성자 또한 private으로 하지 않았었네요 🤣

"범고래는 유틸리티 클래스를 어떠한 상황에서 만드는 것이 적절하다고 생각하나요??"
-> 현재는 많은 클래스에서 자주 사용되는 정적 메서드를 한 클래스에서 선언하여 관리하는 상활일 때가 적합할 것 같다고 생각하고 있습니다.

2022-03-05 17:02 UTC, cndqjacndqja commented on src/main/java/lotterymachine/utils/LotteryNumbersGenerator.java
>      }
```java
public static List<LotteryNumber> getAutoValues() {
        ArrayList<Integer> value = new ArrayList<>(numbers.keySet());
        Collections.shuffle(value);
        return value.stream()
                .limit(LotteryTicket.TICKET_SIZE)
                .map(numbers::get)
                .collect(Collectors.toList());
    }
```

위와 같이 LotteryNumber에서 랜덤한 6개의 번호를 뽑아내는 기능을 작성해 봤었습니다.
하지만 자동 로또 생성하는 부분을 테스트 하기도 어려웠고, 말씀해주신 대로 LotteryNumber의 기능이 많다고 느끼게 됐습니다.

그래서 현재 상태로 유지하게 되었고, 추가로 "자동 로또 생성하는 부분을 테스트 하기도 어려웠고" 이 부분을 해결하기 위해 LotteryNumbersGenerator를 인터페이스로 만든 후, RandomLotteryNumbersGenerator를 구현체로 만들었습니다.

2022-03-05 17:05 UTC, cndqjacndqja commented on src/main/java/lotterymachine/domain/LotteryNumber.java
>      }
이 부분은 Map<Integer, LotteryNumber> NUMBERS으로 변경해 보았습니다 😊

2022-03-05 17:09 UTC, cndqjacndqja commented
안녕하세요 스티치~ 범고래입니다.
꼼꼼한 피드백 감사합니다😊

피드백 반영 후, 다시 리뷰 요청 드립니다 :)

관련 질문들은 코멘트에 댓글로 남겼습니다.

[노션 링크](https://beomwhale.oopy.io/87ae988b-8b7a-415c-acf8-36482c7b76d5)

2022-03-06 15:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryConverter.java
> +public class LotteryConverter {
객체지향적인 설계를 한다는 것은 각각의 클래스가 자신의 책임을 가지도록 설계하는 것을 의미합니다. Lotto는 로또 티켓에 대한 책임을, LottoNumber는 로또 번호에 대한 책임을 가지는 것 처럼요. 그런 맥락에서 Application은 로또 게임을 실행하는 책임을 가지고 있다고 보면 될 것 같아요!! 

지금 구현하고 있는 로또 미션은 '사용자로부터 돈을 입력 -> 구매하고자 하는 수동 로또의 개수를 입력 -> ... -> 로또 결과 발표'와 같은 비즈니스를 가지고 있습니다. 즉 이러한 일련의 과정을 실행해줄 클래스도 반드시 필요하게 되는 것이죠. 여기서는 Application이 해당 책임을 가지고 있고요. 

Converter가 역할이 많다는 말은 명확히 규정지어진 책임을 가지지 않았기 때문입니다. '순차적인 명령을 실행하는 책임을 가지는 Application 클래스'와는 다르게 Converter는 입력을 받아서 사용해야 할 다양한 객체들을 생성하고 있었기 때문이죠. 물론 이를 책임이라고 할 수 있지만, 해당 책임들을 한 클래스에서 가지기에는 너무 많다는 말이었습니다. 

Application에 해당 코드가 존재했을 때는 이러한 책임(입력을 받고 객체를 생성하고...) Application 상위로 더는 넘겨줄 수 있는 상황이 아니기도 했고, 순차적인 명령을 실행하는 책임에도 그리 부합되지 않는 행위들은 아니라고 생각해서 이러한 피드백을 남겨드렸습니다!! :)

여기서 범고래가 한 '전체 코드의 흐름을 제어하는 책임을 가지는 객체'를 만들어본다면? Application 클래스의 책임을 다르게 정의해서 사용할 수도 있겠죠! 만약 Application 클래스를 '외부에서 받은 입력을 게임 진행 프로세스를 관리하는 클래스에 넘겨주는 책임을 가진다'라고 명시하고 controller를 만들어서 '로또 게임의 프로세스들을 관리하는 책임을 가진다'라고 한다면 Application 클래스의 책임이 조금은 나눠진 거라고 볼 수도 있겠죠?

하지만 기존의 Converter 코드에서 단순히 이름을 바꾼다고 해당 클래스의 책임이 달라지진 않습니다. 이름은 해당 클래스를 표현하기 위한 수단이고 책임에 맞는 적절한 이름을 정하는 것이 중요한 것이지 이름을 적절하게 정했다고 이름에 맞는 행위를 한다는 말은 아니기 때문이죠. 

만약 Converter가 이러한 로또 게임의 프로세스들을 관리하는 클래스였다면 아마 명명의 변경을 제안드렸을 거에요!! 하지만 기존의 코드는 외부에서 입력을 받아서 서비스에서 필요한 다양한 객체들을 생성하는 책임을 가지고 있었습니다. 다양한 객체를 생성한다는 것이 책임이 될 수도 있지만, 이는 도메인에게 위임하면 충분히 해결 가능한 책임들이었고, 그런 관점에서 해당 클래스는 다른 도메인들이 가져야 할 책임을 모아둔 느낌이 들었기에 제가 이러한 피드백을 남겨두었던 것 같아요!!

제가 말씀드린 이런 관점들을 한번 고민해보면서 이번에 로또 프로세스를 관리하는 클래스를 하나 만들어본다면 어떨까요??

2022-03-06 15:59 UTC, lxxjn0 commented on src/main/java/lotterymachine/LotteryPurchase.java
> +    public LotteryPurchase(int amount, int passivityCount) {
> 현재 "Count라는 로또 구매 개수를 표현하는 클래스를 만들자."와 같은 생각은 객체 지향 설계를 하는 것과는 조금 멀어지는 생각 일까요??

아닙니다!! 위에서 말한 것처럼 특정한 책임을 가지도록 클래스를 구현하였다면 객체지향적인 설계의 방향으로 나아가고 있는 것이죠!!! Count는 로또 구매 개수를 관리하는 클래스입니다! 즉 존재해야 할 이유가 있고 책임이 있죠. 그에 따른 행위로 생성 시에 유효성을 검증한다고 볼 수 있구요!! 

조금 더 개선을 해본다면 클래스 명을 클래스가 가지는 책임을 명확히 보여주도록 명명을 하면 더 좋을 것 같아요!!! count와 같은 이름이 간결하고 코드를 구성하는데는 더 깔끔하게 보여질 것입니다. 그래서 이러한 명명을 사용한 것일 수 있고요. 하지만 사용자의 입장에서 `new Count()`로 생성하면 어떤 카운트인지 알 수 있을까요?? 로또 구매 개수를 관리하는 카운트? 생성된 로또 개수를 관리하는 카운트? 이처럼 명확하지 못한 이름은 사용자로 하여금 해당 객체를 이해하는데 혼란을 주게 됩니다. 하지만, 만약 해당 클래스의 이름이 LotteryPurchaseCount 였다면 어땠을까요?? 사용자는 코드를 들여다 보지 않아도 충분히 이해가 가능할 것입니다!!

객체지향적인 설계를 하면서 클래스를 분리한다면 해당 클래스가 가져야 할 책임을 명확히 정의하는 것도 중요하고 그 못지않게 그러한 책임이 드러나도록 명명을 하는 것도 중요하다! 라고 생각을 해주시면 좋을 것 같네요 👍🏼

2022-03-06 16:13 UTC, lxxjn0 commented on src/main/java/lotterymachine/Money.java
> +public class Money {
도메인이라는 것은 저도 아직 명확히 이해하긴 어려운 것 같아요 ㅠㅠ 

도메인은 보통 해결하고자 하는 문제의 영역이라고 흔히들 말합니다. 우리는 현재 로또 게임이라는 문제를 해결하고자 해요. 즉 로또 게임이 도메인이 될 수 있겠죠. 그 하위에는 또 다양한 도메인이 존재합니다. 로또 게임에서 로또 티켓은? 로또 번호는? 사용자의 구매 금액은? 당첨 번호는? 이런 것들이 모두 다 도메인이 될 수 있겠죠!! 이러한 것들에 대한 개념적인 부분들 정의한 코드들을 보통은 도메인 모델이라고 부릅니다. 그렇기에 Money는 도메인 모델이라고 볼 수 있죠!!

그렇다면 사용자의 입력을 받는 것은 도메인일까요? 물론 로또 게임이라는 도메인을 구현하는데 필요한 부분은 맞습니다!! 하지만 지금 우리는 사용자에게 올바른 숫자를 입력받는 것이 해결하고자 하는 문제는 아니죠! 단지 로또 게임이라는 문제를 해결하는 데 있어서 사용자의 입력이 필요한 것입니다. 그래서 입력을 받는 레이어를 도메인이 아닌 레이어로 관리하는 것이구요. Application도 이러한 관점에서 볼 수 있겠죠??

패키지는 이렇게 우리가 구현한 코드와 그 코드들이 이루는 구조를 보다 이해하기 쉽고 명확하게 보여줄 수 있는 방법입니다. 도메인은 도메인 패키지에 관리해서 사용자로 하여금 '해당 패키지 내의 클래스는 모두 도메인 모델이구나'를 알려주는 것이죠. 이렇게 코드에 대한 의도를 추가로 보여줄 수 있는 방법으로 패키지를 사용한다고 보시면 될 것 같아요!! 단순히 의존을 하게 되는 대상들이 편하기 위해서 패키지를 구분하기 보다는 이러한 관점으로 패키지를 구분하면 더 좋을 것 같습니다!!!

2022-03-06 16:51 UTC, lxxjn0 requested changes
범고래, 리뷰 반영한 코드 잘 봤습니다!!!

제가 앞서 1000원 금액 단위에 대해서 말씀드린건 1500원일 경우 거스름돈에 대한 요구사항이 없기 때문에 불가능하게 처리되야 한다라고 생각했는데, 미션에서는 1500을 받을 경우 1개만 구매 가능하도록 한다라고 하였군요.. ㅠㅠ 제가 해당 부분을 확인하지 못하고 괜히 진행하는데 혼동을 드렸네요. 죄송합니다 🙇🏼‍♂️ 

앞선 리뷰의 코멘트들에 필요한 추가 코멘트 남겨놓았습니다!! 이번 미션과 함께 확인해보시면 좋을 것 같아요!! :)

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
> +    private LotteryNumber(int number) {
생성자를 private로 막아서 정적 팩토리 메서드로만 객체 사용이 가능하도록 했네요 👍🏼

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
>  public class LotteryNumber implements Comparable<LotteryNumber> {
캐싱된 LottoNumber만 사용하게 한다면 equals와 hashcode는 없어도 되지 않을까요?

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryNumber.java
>      }
해당 메서드를 사용하는 곳에 가깝게 위치하면 코드를 읽는 데 더 편리할 것 같아요!!

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTicket.java
>      }
이러한 정적 팩토리 메서드를 지원해 줌으로서 LotteryTicket 도메인이 한층 더 풍부해진 것 같네요 👍🏼

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTicket.java
> +    public static List<LotteryTicket> getLotteryTickets(List<List<Integer>> value) {
해당 메서드 명이 getter 양식과 비슷해서 사용하는 사람이 해당 메서드의 행위를 이해하기 어려울 것 같아요!! 적절한 이름으로 바꿔보면 좋을 것 같아요!!

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTicket.java
> +    public static List<LotteryTicket> createAutoLotteryTickets(int count, LotteryNumbersGenerator lotteryNumbersGenerator) {
LotteryTicket은 로또 티켓을 관리하는 객체입니다. 그런데 해당 메서드는 자동으로 로또를 생성한다는 비즈니스 로직을 행하고 있는 것으로 보여요!! 해당 클래스가 가지는 책임으로 적절한가요?

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTicket.java
> +    public int countMatchingNumbers(LotteryTicket numbers) {
파라미터 타입과 명이 일치하지 않는 것 같아요!! 이런 부분도 신경써주면 훨씬 더 가독성 좋은 코드가 될 것 같습니다!!

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTickets.java
>  public class LotteryTickets {
해당 객체의 책임은 무엇인가요? 만약 로또 티켓들을 관리하는 책임을 가진다면 그에 걸맞는 행위를 가지고 있나요?

단순히 행위를 가진다는 것이 해당 객체의 존재 가치를 입증한다고는 보기 어려워요. 지금은 로또 티켓들을 가지고 행위를 하지 않아요. 정적 팩토리 메서드는 단지 해당 객체를 생성하는 새로운 방법이지 해당 메서드가 특별한 가치를 지니지는 않습니다.

Count는 기본적인 행위인 생성의 행위에서 여러 유효성을 검증하고 있어요. 즉 해당 객체는 유효한 카운트를 관리하는 책임을 가지고, 그에 맞는 유효성 검증이라는 행위를 지니고 있습니다. 단지 생성 시에 그러한 행위를 진행하기 때문에 별다른 메서드가 없는 것처럼 보여질 수는 있죠.

LottoTickets는 그런 관점에서 어떠한 행위를 하고 있나요? 단순히 생성하는 방법을 다양하게 하는 것으로 해당 객체의 존재 가치를 보여주기는 어렵습니다. 정말 해당 객체가 존재해야만 하는지 한번 고민해보고 개선해보면 좋을 것 같습니다!!

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/RandomLotteryNumbersGenerator.java
> +    }
LottoNumber의 CACHE에서 values만 가져온다면 이러한 로직이 없어도 되지 않을까요??

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/Yield.java
> +    private final double profitRate;
공백 컨벤션을 확인해보면 좋을 것 같아요 :)

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/WinningResult.java
> +    private static final Map<WinningLotteryRank, Integer> result = new EnumMap<>(WinningLotteryRank.class);
현재 result 값이 상수로 관리되는 것 같은데 이렇게 되면 WinningResult를 여러 개 생성하게 되는 경우에는 문제가 발생하지 않을까요?? WinningResult를 객체로 생성해서 사용하고자 한다면 어떻게 하면 좋을까요?

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/vo/Count.java
> +public class Count {
VO 객체는 해당 객체가 어떠한 의도로 관리되는 지를 설명하는 단어이고 따로 vo라는 패키지를 만들어서 VO 객체들을 관리하지는 않습니다 :)

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/vo/Count.java
> +    }
현재 Count는 로또 구매 개수를 관리하는 객체로 보여져요. 해당 객체에서 굳이 totalValue를 받아서 내부에서 계산할 만큼 로직이 복잡하진 않다고 생각이 드는데 어떻게 생각하나요?

추가적으로 만약 생성 시점에서 `new Count(passivityValue, totaValue - passivityValue)`와 같이 충분히 생성이 가능할 것 같고, 그렇다면 validate 로직은 다른 방법으로 해결이 가능할 것 같아요!!!

그리고 passivity의 뜻을 찾아봤는데 이 단어가 의미하는 수동과 수동 로또에서의 수동은 조금 다른 의미로 보여져요. passivity는 소극적인, 수동적인의 의미를 가지는데 우리가 사용하는 수동의 의미는 손으로 하는 이라는 의미로 보여집니다. 한번 적절한 단어를 찾아서 명명을 수정해보면 좋을 것 같아요!!

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/vo/Money.java
> +    private final int value;
해당 변수명도 단순히 value라는 너무 포괄적인 단어를 사용하기 보다는 amount와 같이 조금 더 명시적인 단어를 쓰면 좋을 것 같아요!!

2022-03-06 16:51 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +    public static int getPassivityPurchaseCount() {
view에서 int 타입으로 변경하는 로직을 가지고 그에 따른 유효성 검사를 하는 것보다 각각의 도메인에서 생성 메서드를 풍부하게 제공해보는 것이 어떨까요??

간단한 예로 Java에서 LocalDateTime 객체를 생성할 때 문자열이나 정수 등 다양한 타입을 넘겨서 생성할 수 있습니다. 문자열을 넘겨주는 방법만 예시를 들어보면, 저희가 LocalDateTime을 문자열을 통해 생성할 때 전달하는 문자열이 적절한 시간 형식으로 이뤄졌는지, 유효한 시간 범위를 만족하는지 등을 모두 검사하고 생성을 할까요?? 저희는 생성할 때 어떤 문자열이든 LocalDateTime이 판단하도록 넘겨줍니다. 만약 해당 문자열이 LocalDateTime을 생성하기에 적절하지 않은 형태라면 알아서 적절한 예외를 던져주죠.

이는 LocalDateTime 클래스에서 풍부하게 생성 관련 메서드를 제공함으로서 우리가 얻는 이득입니다. 이처럼 범고래가 관리하는 많은 도메인들도 이렇게 사용자에게 풍부한 생성 메서드를 제공해주도록 개선해보면 어떨까요???

2022-03-07 05:57 UTC, cndqjacndqja commented on src/main/java/lotterymachine/domain/LotteryTicket.java
>      }
코드를 전체적으로 다시 보다가 문득 왜 정적 팩토리 메서드를 쓴건지 되돌아 보게 되었습니다.

LotteryNumber에서 정적 팩토리 메서드를 사용한 이유는
"생성자를 private으로 한 후, 외부에서 생성할 때는 캐싱된 데이터만을 생성하게 강제할 수 있다."는 점에서 사용했습니다.

하지만 LotteryTicket 같은 경우는, 정적 팩토리 메서드를 사용해서 얻는 이점이 무엇인지 잘 모르겠네요 😱
저는 static과 같은 정적 메소드, 필드는 JVM메모리에 메소드 영역에 위치하기 때문에(GC가 관리하지 않는다고 생각하여) 다른 이점이 없다면 지양하는 것이 좋다고 생각 했었는데요! 

때문에 해당 부분은 생성자로 바꾸어 주는 것이 더 좋은가 생각이 드는데 스티치의 생각은 어떠신가요??🤭

2022-03-07 14:35 UTC, cndqjacndqja commented on src/main/java/lotterymachine/domain/LotteryTicket.java
> +    public static List<LotteryTicket> createAutoLotteryTickets(int count, LotteryNumbersGenerator lotteryNumbersGenerator) {
이 부분은 말씀해 주신대로 객체의 역할과 책임을 먼저 생각해 보고 코드를 짜보았습니다.
"입력 받은 숫자에 따라 자동 로또 티켓을 생성해준다."라는 역할을 생각 했을 때, 존재하는 객체 중에는 어울리지 않는다고 생각하여 AutoLotteryTicketGenerator 클래스에서 처리하게 했습니다!

2022-03-07 14:40 UTC, cndqjacndqja commented on src/main/java/lotterymachine/view/InputView.java
> +    public static int getPassivityPurchaseCount() {
LocalDateTime를 참고해 본 후, 그에 따라 수정을 해보았습니다.
수정 후, 코드를 보니 도메인에서 여러 역할들이 생기며 생성 메서드가 풍부해지는 것은 공감이 되었으나, InputView에서는 그저 Scanner.nextLine()만을 호출하는 클래스가 됐었습니다. 그러다 보니 InputView의 역할이 없어지는 느낌을 받았고, int or String에 대한 검증 로직은 View에서 해주는 것이 더 적절하다고 생각이 들어 다시 수정하게 됐습니다 😊

2022-03-07 16:52 UTC, lxxjn0 commented on src/main/java/lotterymachine/domain/LotteryTicket.java
>      }
저 같은 경우에는 생성자는 순수하게 맴버 변수에 대한 데이터를 받아서 생성하는 경우 사용하고 정적 팩토리 메서드는 추가적인 가공을 통해서 객체를 생성해야 할 경우에만 사용하고 있습니다. 그런 관점에서 해당 생성 로직이 정적 팩토리 메서드로 관리되기엔 적절하다고 생각했어요!! :)

추가적으로 무분별하게 너무 많은 static 메서드, 필드를 사용하면 메모리 상에 문제가 될 수도 있지만 현재의 하드웨어 성능 수준에서 이러한 고민은 크게 중요하지 않을 것으로 보여요 (물론 이런 부분을 이해하고 있으면서 고려하지 않는 것과 전혀 몰라서 고려하지 않는 것은 분명한 차이가 있죠 😄). 해당 부분에 대한 비용보다는 유지보수하기 좋은 클린 코드를 사용하여서 줄일 수 있는 비용이 더 크다고 생각하기 때문에 저는 범고래가 따로 메모리 고민하지 않고 상황에 맞는 적절한 static 메서드, 필드를 사용해도 괜찮다고 생각해요 :)

2022-03-07 16:54 UTC, lxxjn0 commented on src/main/java/lotterymachine/view/InputView.java
> +    public static int getPassivityPurchaseCount() {
제가 생각하기에 view는 외부의 입력을 받아오는 역할만으로도 충분히 자신의 역할을 다 한다고 생각해요!! 물론 범고래가 한 방법이 잘못된 것은 아닙니다! 저의 생각에는 이러한 방법으로 구현하는 것도 좋을 것 같다는 제안 정도니 범고래가 더 다양하게 구현도 해보고 바꿔도 보면서 본인이 생각하는 코드의 가치관에 맞는 코드를 작성하면 될 것 같아요!! :)

2022-03-07 16:57 UTC, lxxjn0 approved these changes
범고래, 리뷰 반영하느라 수고 많으셨습니다 👍🏼 

이번 미션을 진행하면서 처음에 비해서 훨씬 더 좋은 코드로 마무리 하였네요 :) 미션 진행 동안에도 실력이 향상하는 범고래를 볼 수 있어서 좋았습니다 😄 

앞선 코멘트에 대한 의견은 제가 추가로 남겨두었고 이번 미션은 여기서 마무리해도 될 것 같네요 :) 수고 많으셨습니다

2022-03-07 16:57 UTC, merged