[2단계 - 로또(수동)] 헌치(박지우) 미션 제출합니다.
woowacourse/java-lotto pull request #480
Opened 2022-03-03 08:13 UTC by BETTERFUTURE4

안녕하세요 제이😄
피드백 주신 부분들에 대한 개선을 적용했고, 2단계 구현사항에 맞춰 작업했습니다!

다음은 고려했던 사항들 입니다!
- 생성자를 정적 팩토리 메소드로 전환
- 검증 로직을 생성자 안으로 이동
- 컨트롤러의 domain 생성 메서드를 LottoFactory 안으로 이동
- 커스텀 예외/메세지 적용, 테스트 코드에서 검증
- 접근제한자 private, 변수/인수 final로 변환

2단계 리뷰도 잘 부탁드립니다!
궁금한 사항은 코멘트로 추가해 두겠습니다!

2022-03-03 08:25 UTC, BETTERFUTURE4 commented on src/main/java/domain/lotto/LottoNumber.java
> +
`LOTTO_NUMBER_CACHE`를 현재 LottoNumber 안에 두었는데
LottoFactory로 빼서 구현하신 분들도 있었습니다.

이러한 캐시들을 두는 방법으로 3개를 생각해봤습니다. 
1. 객체 클래스 내부에 두기(LottoNumber)
2. 외부에 따로 생성 클래스를 두어 저장(LottoFactory)
3. 저장만을 목적으로 하는 클래스 생성 후 캐시 저장(LottoRepository)

셋 중 어떤 방법이 주로 쓰이는지, 제이님의 의견은 어떠한지 궁금합니다!

2022-03-03 08:30 UTC, BETTERFUTURE4 commented on src/main/java/view/InputView.java
> +            final Scanner scanner = new Scanner(System.in);
처음에는 `scanner`를 상수로 따로 뺐는데
실행 시 `nextInt()`로 받은 값이 스캐너에 계속 남아있어 오류가 났습니다.
결국 스캐너를 다시 메서드 변수로 만드는 방식으로 변경했습니다.
해당 오류를 해결할 수 있는 방법이 있을까요?

2022-03-03 08:30 UTC, BETTERFUTURE4 commented on src/main/java/view/InputView.java
> +            return scanner.nextInt();
처음에는 `scanner`를 상수로 따로 뺐는데
실행 시 `nextInt()`로 받은 값이 스캐너에 계속 남아있어 오류가 났습니다.
결국 스캐너를 다시 메서드 변수로 만드는 방식으로 변경했습니다.
해당 오류를 해결할 수 있는 방법이 있을까요?

2022-03-03 23:52 UTC, JunHoPark93 requested changes
안녕하세요 헌치!
2단계 미션 잘 구현해주셨네요.
전체적으로 깔끔하게 잘 해주신거같아요. 이번미션에 고려해주셨던 사항들이 적절하게 잘 들어가있네요!
몇가지 코멘트 남겨두었는데 확인부탁드려요.
궁금한점 편하게 남겨주세요~

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/controller/MainController.java
> +        final List<Lotto> lottoTickets = makeLottos(count);
이번미션에서 자료구조형태도 전부 포장을 해보는데 의의가 있는데요, 발급된 로또들을 관리하는 도메인을 만들어보면 어떨까요? 🤔

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/domain/lotto/Lotto.java
> +    private static final int LOTTO_NUMS_SIZE = 6;
적절한 위치로 잘 옮겨주셨네요 👍

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/domain/lotto/LottoFactory.java
> +            lottos.add(Lotto.from(NumsGenerator.generate(nums)));
적절한 구조로 잘 변경해주셨네요 👍

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/domain/lotto/Lotto.java
> +            throw new LottoNumDuplicatedException();
> 커스텀 예외/메세지 적용, 테스트 코드에서 검증

넵 잘해주셨어요, 추가적으로 잘못된 사이즈에 대한 정보를 같이 넘겨주면 추후 예외 추적에 유리합니다 :)

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/domain/lotto/LottoMoney.java
> +        return lottoMoney / 1000;
정의해주신 상수를 사용해도 될 것같아요!

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/domain/lotto/LottoNumber.java
> +    }
`접근제한자 private, 변수/인수 final로 변환`
말씀주신 부분은 잘해주셨어요!

새로이 자료구조를 만들어서 return하는건 어떨까요? 외부에서 본 자료구조를 수정할 여지가 있어보여요.

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/domain/lotto/LottoTicketCount.java
> +        validate(manualTicketCount, autoTicketCount);
이것도 적절한 검증과 함께 잘 포장해주셨네요!

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/domain/lotto/LottoNumber.java
> +    private static final Map<Integer, LottoNumber> LOTTO_NUMBER_CACHE = new HashMap<>();
> LOTTO_NUMBER_CACHE를 현재 LottoNumber 안에 두었는데
> LottoFactory로 빼서 구현하신 분들도 있었습니다.
> 
> 이러한 캐시들을 두는 방법으로 3개를 생각해봤습니다.
> 
> 객체 클래스 내부에 두기(LottoNumber)
> 외부에 따로 생성 클래스를 두어 저장(LottoFactory)
> 저장만을 목적으로 하는 클래스 생성 후 캐시 저장(LottoRepository)

저는 지금처럼 상수로 정의를 해두거나 객체 내부에 클래스를 둬도 될 것 같아요. 외부에 빼기에는 오버엔지니어링이라고 생각하는게 로또 번호가 바뀔 여지가 거의 없기 때문이에요. LottoNumber안에서만 책임을 가지는게 관리포인트에서도 훨씬 간단해진다고 생각합니다.
참고로 Integer.java에 IntegerCache 부분도 한번 참고해보시면 좋을 것 같아요!

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/view/InputView.java
> +            final Scanner scanner = new Scanner(System.in);
> 처음에는 scanner를 상수로 따로 뺐는데
> 실행 시 nextInt()로 받은 값이 스캐너에 계속 남아있어 오류가 났습니다.
> 결국 스캐너를 다시 메서드 변수로 만드는 방식으로 변경했습니다.
> 해당 오류를 해결할 수 있는 방법이 있을까요?

음 어떤 경로에서 남아있었나요? 읽어들일때 다 안읽어들여서 그런거같기도한데, 단계마다 nextLine()등으로 버퍼를 비워주는 작업을 넣는것도 방법이 될 것 같아요. 하지만 지금 구조도 괜찮다고 생각해요~
꼭 트래킹을 해보고싶으시면 상황을 다시 남겨주셔요!

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/domain/lotto/LottoNumber.java
> +
해당 코드부분에 남겨두었어요!

2022-03-03 23:52 UTC, JunHoPark93 commented on src/main/java/view/InputView.java
> +            return scanner.nextInt();
해당 코드부분에 남겨두었어요!

2022-03-07 06:11 UTC, BETTERFUTURE4 commented on src/main/java/controller/MainController.java
> +        final List<Lotto> lottoTickets = makeLottos(count);
발급된 로또들을 관리하는 도메인 `LottoGroup`을 만들었습니다!

2022-03-07 06:14 UTC, BETTERFUTURE4 commented on src/main/java/domain/lotto/Lotto.java
> +            throw new LottoNumDuplicatedException();
커스텀 예외 처리 시 관련 변수를 같이 메세지로 출력하도록 수정했습니다!

2022-03-07 06:20 UTC, BETTERFUTURE4 commented on src/main/java/domain/lotto/LottoMoney.java
> +        return lottoMoney / 1000;
위의 `DIVIDE_UNIT`상수로 변환했습니다!

2022-03-07 06:22 UTC, BETTERFUTURE4 commented on src/main/java/domain/lotto/LottoNumber.java
> +    }
`Map.copyOf()` 메소드를 사용해 복사본을 만들었습니다!

2022-03-07 06:29 UTC, BETTERFUTURE4 commented on src/main/java/domain/lotto/LottoNumber.java
> +    private static final Map<Integer, LottoNumber> LOTTO_NUMBER_CACHE = new HashMap<>();
감사합니다! `IntegerCache `의 경우 해당 캐쉬를 내부 클래스로 따로 빼서 저장했네요! 나중에 해당 방법도 고려해볼게요👀

2022-03-07 06:33 UTC, BETTERFUTURE4 commented on src/main/java/view/InputView.java
> +            final Scanner scanner = new Scanner(System.in);
`nextLine()`으로 버퍼를 비워주었더니 해당 문제가 해결되었어요!

2022-03-07 06:54 UTC, BETTERFUTURE4 commented
안녕하세요 제이😄 아마 마지막 pr이네요ㅎㅎ
지난번 이후 한번 더 pr하려다가 주말이 껴 있어 타이밍을 놓쳤네요ㅠㅠ

이번에도 제이님의 2단계 피드백들과 
강의 등으로 추가 학습한 부분들을 참고해 리팩토링 해보았습니다ㅎㅎ

다음은 이번 리팩토링 때에 초첨을 맞춘 사항들 입니다!

## 피드백 적용
- [x] List<Lotto>의 래핑 클래스를 도메인에 추가 구현, 로직 이동
- [x] CACHE 게터에서 새로이 자료구조 만들어 리턴(수정가능성 차단!!)
- [x] 스캐너 상수화 후 단계마다 nextLine()등으로 버퍼를 비워주는 작업
- [x] LottoMoney의 toLottoCount() 속 매직넘버 상수로 변경
- [x] 커스텀 예외/메세지에 정보를 같이 넘기기(Lotto)

## 그외 수정사항
- [x] Rank 클래스에서 Bipredicate를 사용해보자
- [x] 변수명 변경
    - [x] VO 변수명 value로 변경
    - [x] 래핑 전 변수명에 raw 붙이기
    - [x] 인자 값을 메서드 내 역할에 맞게 명명
    - [x] winLotto winningLotto로 이름 변경
- [x] set 변수 간소화
- [x] copyOf 통해 리스트 불변성 추가
- [x] 클라이언트를 편하게 하기 위해 테스트클래스에 날것 변환용 메서드 생성

지금까지 친절한 피드백 해주셔서 감사해요! 🥺
괜찮다면 수정이 필요한 부분에 대해 추가적인 코멘트 부탁드려요!

2022-03-07 12:43 UTC, JunHoPark93 approved these changes
안녕하세요 헌치!
리뷰 반영하시느라 고생많으셨어요 👍
정리를 굉장히 잘하시네요! 피드백도 잘 반영해주셨습니다.
마지막으로 코멘트 하나 남겨두었는데 다음 미션 진행하실때 참고부탁드려요!
다음 미션도 화이팅입니다~

2022-03-07 12:43 UTC, JunHoPark93 commented on README.md
> +- [x] CACHE 게터에서 새로이 자료구조 만들어 리턴(수정가능성 차단!!)
피드백까지 정리를 하셨네요!
이렇게 까지 하신다면 매 미션마다 스스로 정말로 많은 것들을 정리하실수있을것 같아요.
저도 배워갑니다.

2022-03-07 12:43 UTC, JunHoPark93 commented on src/main/java/domain/lotto/LottoNumber.java
> +        return Map.copyOf(CACHE);
👍

2022-03-07 12:43 UTC, JunHoPark93 commented on src/main/java/controller/MainController.java
> +    }
컨트롤러에 요런 로직들이 추가가 되었네요! 수익을 구하는 책임을 가진 도메인에게 위임해보는건 어떨까요?
다음 미션을 진행하시면서 컨트롤러에 로직이 들어가게 된다면 해당 로직을 담당하는 친구는 누구일까 고민해나가면서 하면 좋을 것 같아요.

2022-03-07 12:43 UTC, JunHoPark93 commented on src/main/java/controller/MainController.java
> +                InputView.inputManualTicketCount());
전개가 더 깔끔해진거같네요!

2022-03-07 12:45 UTC, JunHoPark93 commented on src/main/java/domain/lotto/LottoGroup.java
> +        }
여기 지나쳤네요.
isEmpty() 도 있어요~ 그리고 예외를 좀 더 명시적으로 만들면 더 좋을것같아요. 널포인터예외처럼 보여서요!

2022-03-07 12:45 UTC, JunHoPark93 commented on src/main/java/controller/MainController.java
> +        final List<Lotto> lottoTickets = makeLottos(count);
훨씬 좋아졌습니다!

2022-03-07 12:46 UTC, merged