[2단계 - 로또(수동)] 파랑(이하은) 미션 제출합니다.
woowacourse/java-lotto pull request #492
Opened 2022-03-03 16:55 UTC by summerlunaa

안녕하세요! 파랑입니다.

이전에 말씀해 주신 리뷰들을 최대한 반영하려고 노력했습니다.

가장 크게 바뀐 부분은 LottoNumber가 enum에서 Integer cache로 변경된 부분과 LottoGenerator, LottoCounter가 생성된 부분인 것 같습니다.

추가적으로 궁금한 점은 저번에 남긴 내용과 같은데 답변을 못 받은 것 같아서 한 번 더 질문드리겠습니다ㅎㅎ.

문자열을 받아 정수/자연수인지 검증하여 반환하는 부분을 누가 가져가야하는지 헷갈립니다. 우선은 InputView에서 InputConvertor를 호출해 반환한 값을 controller에 넘겨주는 것으로 구현했는데 이렇게 하면 InputView가 단순히 입력만 받는 것이 아니라 검증하고 반환까지 하는 것 같아서 이 부분을 InputView에서 하는 게 맞을지, 아니면 controller에서 해야할지.. 혹은 또 다른 클래스가 필요한 것인지 궁금합니다!

그리고 OutputView에서 도메인의 객체들에 많이 의존하고 있는데 이렇게 해도 괜찮을까요? 아니면 DTO 등을 사용해서 의존을 없애는 것이 좋을까요?

감사합니다!

2022-03-05 16:27 UTC, lxxjn0 requested changes
파랑, 2단계 미션 구현 코드 잘 봤습니다!! :)

더 많은 객체 분리를 하기 위해서 노력한 부분들이 잘 보이는 코드였어요. 그래서 도메인 분리와 코드적인 관점에서 조금 더 생각해보면 좋을 것 같은 부분들을 추가로 코맨트 남겨봤습니다!! 

이번에 피드백을 반영하면서 추가적으로 해당 객체는 어떤 책임을 가질까? 그리고 어떤 행위들을 하고 있을까? 해당 객체가 가지는 맴버 변수가 정말 꼭 가져야만 하는 건가? 책임을 벗어나는 부분은 아닌가? 행위가 해당 객체에서 하기엔 범위를 벗어나는 행위는 아닐까? 등의 다양한 고민을 해보면서 다시 코드를 읽어보는 것도 추천드릴게요. 이런 고민들을 계속 하다보면 더 적절한 단위로 클래스 분리가 가능할 것 같아요!!

그리고 질문한 부분에서 '정수/자연수'인지 검증하는 부분에 대해서는 이번에 남긴 코멘트에 관련된 의견이 포함되어 있을 것 같아요!! 그래서 해당 코멘트를 읽고 한번 반영해보면 좋을 것 같습니다!!

2번째 질문인 'view에서 도메인의 객체를 많이 의존하고 있는데 괜찮을까요?'라는 부분에서는 상관 없다고 봐도 될 것 같습니다!! 물론 dto를 사용해서 출력에 맞는 적절한 형태의 객체를 쓰는 것도 좋고, view에서 도메인을 노출하기 싫어서 dto로 감싸서 넘겨주고 싶은 생각도 좋습니다.

그러나 이번 미션을 진행할 때는 이런 dto 부분에 대한 구현 등은 생각하지 않고 미션을 진행하는 것이 더 많은 도움이 될 것 같아요!! 도메인 객체가 view를 의존한다면 절대 안되지만 의존의 방향이 view에서 도메인으로 향하는 것은 상관없을 것 같습니다!!

추가로 저의 의견은 레벨 1 미션 전체에 대해서도 동일한 생각입니다. 레벨 1은 어떻게 하면 테스트 코드를 더 많이 잘 짜고 객체지향적으로 코드를 작성할 수 있는가에 대해서 고민하는 시기라고 생각해요!!

그래서 굳이 controller, view, domain 이상의 분리는 하지 않는게 더 좋을 것 같고 그런 분리와 dto 등 추가적인 부분에 대한 고민 대신에 정말 도메인이 적절한 지, 어떻게 하면 더 풍부하게 도메인들을 사용할 수 있는지 등에 대해서 고민을 하는데 집중하면 좋을 것 같습니다!! 그런 고민들이 dto를 사용하고 레이어를 분리하는 경험보다 앞으로의 파랑의 코드와 개발에 있어서 더 좋은 영향을 가져올 수 있을 것 같아요!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/controller/Controller.java
>              return new Money(inputMoney);
현재는 InputView에서 모든 검증(숫자 그리고 양수)이 완료된, 검증된 정수를 반환해주고 그것을 사용해서 Money를 생성합니다. 이번에는 Money 도메인을 조금 더 풍부하게 만들어주기 위해서 Money 생성에 대한 유효성 검증, 책임을 모두 Money 객체에게 넘겨줘보는 건 어떨까요??

예를 들어 Java에서 LocalDateTime 객체를 생성할 때 문자열이나 정수 등 다양한 타입을 넘겨서 생성할 수 있습니다. 문자열을 넘겨주는 방법만 예시를 들어보면, 저희가 LocalDateTime을 문자열을 통해 생성할 때 전달하는 문자열이 적절한 시간 형식으로 이뤄졌는지, 유효한 시간 범위를 만족하는지 등을 모두 검사하고 생성을 할까요?? 저희는 생성할 때 어떤 문자열이든 LocalDateTime이 판단하도록 넘겨줍니다. 만약 해당 문자열이 LocalDateTime을 생성하기에 적절하지 않은 형태라면 알아서 적절한 예외를 던져주죠. 

그런 관점에서 Money 도메인도 이처럼 다양한 타입을 받을 수 있는 생성자를 만들어둔다면 어떨까요?? 어떤 장점을 얻을 수 있는지 한번 고민해보면 좋을 것 같아요!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/controller/Controller.java
>              return new Money(inputMoney);
이와 비슷한 로직들에 대해서는 모두 동일한 고민을 해보고 개선해보면 좋을 것 같아요!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/LottoCounter.java
> +public class LottoCounter {
LottoCounter 객체는 수동/자동 로또 개수를 관리하는 객체로 보여집니다. 그런데 LottoCounter라는 이름은 로또를 세는 역할을 하는 객체처럼 느껴져요. 조금 더 객체의 책임을 드러낼 수 있는 이름을 고민해보면 좋을 것 같아요!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/LottoCounter.java
> +    public LottoCounter(Money money, int manualLottoCount) {
현재 객체는 생성 시점에 '수동/자동 로또 구매 가능 개수를 검증'하는 역할을 가지고 있는 것 같아요. 그런 관점에서 현재의 생성자는 '돈이랑 수동 로또 생성 개수를 줄테니 알아서 잘 계산하고 검증까지 해줘'의 역할을 하는 것 같습니다!! 

사실 돈을 가지고 구매할 수 있는 로또의 개수는 충분히 외부에서 계산이 가능할 것 같아요!! 해당 객체가 자신이 가져야 할 책임, 역할을 할 수 있도록 적절한 값을 생성자에 넘겨주면 어떨까요? 

파랑이 이해하기 쉽게 조금 더 풀어서 생각해보면 해당 생성자에서는 '돈으로 구매 가능한 로또 개수를 구한다'는 비즈니스 로직까지 알고 있는 상태에요. 그런데 로또 생성 개수의 검증을 하는 객체에서 해당 비즈니스 로직까지 관리하는게 적절할까? 생각해보면 저는 아니라고 생각합니다!! 한번 파랑도 해당 부분에 대해서 고민을 해보고 한번 개선해보면 좋을 것 같아요!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/LottoNumber.java
>      }
LottoNumber를 캐싱해서 관리하는 것 👍🏼

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/LottoNumber.java
>      }
현재 LottoNumber는 캐싱된 값을 사용하려고 하는데 생성자가 public으로 열려있어요. 그렇다면 우리가 캐싱해둔 LottoNumber가 아닌 LottoNumber를 추가로 생성해서 사용할 수 있습니다!! 어떻게 이러한 상황을 막을 수 있을까요??

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/LottoNumber.java
>      }
현재는 Cache의 index에 따라서 값을 반환하고 있는데 만약 List의 순서에 조금이라도 변경이 생긴다면 해당 메서드는 정상적인 동작을 못하게 됩니다!! 만약 LottoNumber로 원하는 숫자를 받았을 때, 무조건 해당 숫자와 동일한 LottoNumber를 반환하려면 어떻게 개선해야 할까요??

추가적으로 [정적 팩토리 메서드 네이밍 규칙](https://ocblog.tistory.com/52)에 대해서도 한번 보면 좋을 것 같아요!! 물론 해당 규칙으로만 꼭 명명을 해야하는 것은 아니지만 대부분 해당 규칙에 따라서 명명을 많이 하기 때문에 코드를 읽는 사람으로 하여금 더 이해하기(파악하기) 좋은 정적 팩토리 메서드를 제공할 수 있어요!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/generator/LottoGenerator.java
> +    }
해당 메서드를 보면 LOTTO_NUMBERS는 굳이 상수로 관리될 필요가 없을 것 같아요!! 만약 메서드 내에서 이해 가능한 변수로 할당해서 사용이 가능하다면 굳이 상수로 관리할 필요는 없을 것 같습니다!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/Lottos.java
>  public class Lottos {
해당 클래스는 현재 가지는 도메인 로직이 빈약해보여요. 지금은 Lottos라는 이름에 비해 내부에서 하는 역할은 수동, 자동 로또 생성의 역할만 하고 있습니다!! 일급 컬렉션으로 관리해서 얻을 수 있는 장점은 따로 없어보여요!! 

현재의 로직이라면 오히려 외부에서 바로 LottoGenerator를 사용해서 로또를 생성하거나, 또는 LottoGenerator에 추가적인 List<Lotto>를 만드는 메서드를 둬서 해결하는 것이 더 적절해 보입니다!!

만약 해당 객체를 조금 더 일급 컬렉션의 목적에 맞게 사용할 수 있는 방법을 찾아보거나, 아니면 오히려 LottoGenerator 클래스의 메서드를 풍부하게 만들어서 해결하는게 더 좋을 것 같아요!!

파랑의 생각은 어떤가요??

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/Money.java
> +        checkUnit(input);
해당 검증만 진행하면 0원이 들어오는 상황에 대해서는 검증이 어려울 것 같아요!!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/Money.java
> +    }
갑자기 든 생각인데, 단순히 Money라는 클래스 명에서 해당 함수를 호출하면 어색하지 않은가? 라는 생각이 들었어요. 사용하는 입장에서 `new Money(1000).calculateProfitRate(10000)`와 같이 사용했을 때, 단순한 money라는 객체에게 '수익률을 계산해라'라는 행위가 어색하게 느껴졌습니다.

만약 Money가 아닌 LottoPurchaseMoney라면 로또 구매 금액에게 수익률을 계산해 달라고 해도 적절할 것 같다는 생각이 들었어요!! 혹시 파랑은 저의 이러한 생각에 대해서 어떻게 생각하나요?? ㅎㅅㅎ

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/Rank.java
> +        if (winningNumbersMatchCount == 5 && bonusNumberMatch == true) {
마지막에 `bonusNumberMatch == true`는 그냥 `bounsNumberMatch`로 변경해도 될 것 같아요!!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/Rank.java
> +        if (winningNumbersMatchCount == 5 && bonusNumberMatch == true) {
해당 메서드 명도 정적 팩토리 메서드 명명을 참고해보면 좋을 것 같아요!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/view/OutputView.java
> +                        rank.toStringPrize(), rankCounter.getCountOfRank(rank)));
rank의 해당 메서드들은 format 문자열만 적절히 수정하면 필요없는 메서드로 보이는데 한번 확인해보면 좋을 것 같습니다!!

2022-03-05 16:27 UTC, lxxjn0 commented on src/main/java/lotto/domain/RankCounter.java
> +    }
> 해당 코멘트는 저의 주관적인 관점이니 한번 읽어보고 참고만 해주세요 :)

파랑의 코드들을 보면 대부분 생성자에서 다양한 변경 로직을 가지고 있어요. 물론 생성자에서 맴버 변수가 될 값에 대한 검증은 위치하는 것이 적절하다고 생각합니다. 하지만 저의 경우 개인적인 기준을 통해서 생성자와 정적 팩토리 메서드를 사용하고 있습니다.

앞서 말한 것처럼 해당 객체가 가지는 맴버 변수에 대한 검증 관련 로직은 생성자에 두지만 매개변수로 전달받은 값에 대한 변경이 필요한 경우는 대부분 정적 팩토리 메서드를 사용하고 있어요!!

예를 들면 RankCounter 객체의 생성자는 RankCounter의 맴버 변수에 대한 값만 받도록 생성합니다. 아래와 같이요!

```java
public class RankCounter {

    private final Map<Rank, Integer> rankCount;

    public RankCounter(final Map<Rank, Integer> rankCount) {
        this.rankCount = rankCount;
    }
}
```

만약 맴버 변수가 여러 개라면 그에 맞는 생성자들을 적절히 생성해서 사용할 거에요. 그러나 지금 파랑이 생성자에서 가지는 로직의 경우 전달받은 값에 대한 다양한 변경 처리가 일어난 후 생성을 합니다!! 

그런 경우에 저는 정적 팩토리 메서드를 사용합니다. 보통 팩토리 패턴이나 정적 팩토리 메서드의 경우 객체를 생성하는 책임을 가지는 클래스나 메서드를 말합니다. 하지만 단순히 생성자와 동일하게 '객체만 생성'한다면 해당 클래스와 메서드가 필요 없을 것이라고 생각했습니다! 그래서 '객체를 생성하는데 단순히 생성자로 생성할 수 있는 이상을 필요로 한다'라는 상황에 대해서는 팩토리 패턴이나 정적 팩토리 메서드를 사용하는게 적절하다고 생각하고, 그렇게 구분지어서 사용하고 있습니다!

물론 이런 생각은 정답도 아니고 무조건 좋은 방법도 아닐 수 있어요. 그러나 단지 생성자로 표현할 수 있는 그 이상의 의미를 '정적 팩토리 메서드'를 사용하는 것만으로도 전달이 가능하다고 생각해서 저는 이렇게 사용하고 있습니다!! 파랑도 만약 이런 관점들을 한번 읽어보고 괜찮다고 생각해서 적용해보면 어떨까?? 싶어서 의견을 남겨봅니다!! :)

2022-03-07 07:13 UTC, summerlunaa commented on src/main/java/lotto/domain/Money.java
> +        checkUnit(input);
Money에 자연수가 넘어가도록 구현해놔서 0인 경우 자연수를 입력하라고 뜰 것 같습니다!
그런데 이 코멘트를 보고 다른 사람이 이 코드를 봤을 때 충분히 0인 경우에 대해서 체크가 안 된다고 오해할 것 같은데ㅠㅠ 음 자연수 검증을 Money 객체 안으로 넣는 게 좋을까요?

2022-03-07 07:14 UTC, summerlunaa commented on src/main/java/lotto/domain/Money.java
> +    }
저도 그냥 Money라고 하면 헷갈릴 수 있을 것 같아서 LottoPurchaseMoney로 이름을 수정했습니다. 감사합니다ㅎㅎ

2022-03-07 07:14 UTC, summerlunaa commented on src/main/java/lotto/view/OutputView.java
> +                        rank.toStringPrize(), rankCounter.getCountOfRank(rank)));
고민해봤는데 어떻게 수정할 수 있을지 감이 잘 안 잡히네요ㅠㅠ 혹시 조금 더 자세히 알려주실 수 있을까요?🥲

2022-03-07 07:26 UTC, summerlunaa commented on src/main/java/lotto/domain/LottoCounter.java
> +public class LottoCounter {
다시 LottoCount로 이름 변경했습니다😂

2022-03-07 08:20 UTC, summerlunaa commented
안녕하세요 파람입니다!

최대한 리뷰를 반영해보려고 노력했으나 시간이 모자라서 완벽히 반영하지는 못했습니다ㅠㅠ. 이 점이 많이 아쉽네요.

객체의 역할, 생성자에 대한 코멘트를 많이 남겨주셔서 그 부분에 대해서 많이 고민해볼 수 있는 시간이었던 것 같습니다.

2단계 하면서 궁금했던 점들은 이전에 남겨주신 피드백에 댓글로 달아놓았습니다. 확인부탁드립니다! 감사합니다.

2022-03-07 08:22 UTC, summerlunaa commented on src/main/java/lotto/domain/LottoNumber.java
>      }
private 으로 수정했습니다!

2022-03-07 08:30 UTC, summerlunaa commented on src/main/java/lotto/controller/Controller.java
>              return new Money(inputMoney);
LocalDateTime처럼 문자열이나 정수 등 다양한 타입을 모두 커버할 수 있도록 생성자를 만들어주면 좋을 것 같습니다! 우선 LottoPurchaseMoney에서 문자열을 받은 경우도 처리할 수 있도록 수정하였습니다. 다른 로직들에도 적용시키고 싶었지만 시간이 촉박해서 다른 부분들에는 적용시키지 못해서 아쉽습니다ㅠㅠ.

다만 피드백을 보고 궁금했던 점은 이전 1단계 피드백에서 `Money 입장에서 사용자가 입력한 문자열이 정수인지 아닌지는 도메인이 관리해야 하는 부분은 아니라고 생각해요!!`라고 하셨는데 이번 피드백과 이전의 피드백 내용이 반대되는 것 같아서 조금 헷갈립니다!! 어떻게 이해하면 좋을까요!?

2022-03-07 08:35 UTC, summerlunaa commented on src/main/java/lotto/domain/LottoCounter.java
> +    public LottoCounter(Money money, int manualLottoCount) {
(돈, 수동로또개수)에서 (전체로또개수, 수동로또개수)를 받도록 수정했습니다. 어차피 돈으로 구매가능한 로또 개수는 LottoPurchaseMoney에서 계산하는 메서드를 갖고 있어서 LottoPurchaseMoney 객체에서 계산한 전체 로또 개수를 넘겨주는 방식으로 수정했습니다.

2022-03-07 08:36 UTC, summerlunaa commented on src/main/java/lotto/domain/LottoNumber.java
>      }
HashMap으로 변경하여 index와 관계 없이 값을 반환할 수 있도록 수정했습니다!!

2022-03-07 08:39 UTC, summerlunaa commented on src/main/java/lotto/domain/Lottos.java
>  public class Lottos {
흠 저도 도메인 로직이 빈약해보이는데 아예 없애기에는 조금 찝찝한 기분이 들어서 우선 생성자를 수정하고, 정적 팩토리 메서드를 만들고, 두 개의 Lottos를 합치는 메서드를 추가했습니다. 그런데 아직도 빈약한지 아닌지 잘 모르겠습니다. 어떤 것 같나요!?

2022-03-07 08:59 UTC, summerlunaa commented on src/main/java/lotto/domain/Money.java
> +        checkUnit(input);
원래 검증된 자연수를 넘겨주는 거라서 0이 들어오는 경우에 자연수를 입력하라고 나옵니다!
그런데 그렇게 하면 헷갈릴 것 같아서 이번에 수정하면서 양수인지 검증하는 부분을 Money안에 포함시켰습니다!

2022-03-07 09:04 UTC, summerlunaa commented on src/main/java/lotto/domain/RankCounter.java
> +    }
정말 자세하게 설명해주셔서 생성자와 정적 팩토리 메서드의 책임과 필요성에 대해 조금 더 알게된 것 같습니다 감사합니다(감동)🥲  
이번에 수정하면서 반영해보려고 노력했습니다! 생성자가 좀 더 깔끔해지고 정적 팩토리 메서드를 통해 다양한 방식으로 객체를 생성할 수 있어서 좋은 것 같다고 느꼈습니다👍

2022-03-07 16:12 UTC, lxxjn0 commented on src/main/java/lotto/controller/Controller.java
>              return new Money(inputMoney);
제가 미션 진행에 혼란을 드려서 죄송합니다.. ㅠㅠ 

> 다만 피드백을 보고 궁금했던 점은 이전 1단계 피드백에서 Money 입장에서 사용자가 입력한 문자열이 정수인지 아닌지는 도메인이 관리해야 하는 부분은 아니라고 생각해요!!라고 하셨는데 이번 피드백과 이전의 피드백 내용이 반대되는 것 같아서 조금 헷갈립니다!! 어떻게 이해하면 좋을까요!?

해당 부분은 제가 처음 피드백 드리는 당시는 위와 같이 생각했는데 이번 미션에 대해서 다른 동기들과 이야기를 하다보니 생각이 조금 달라지면서 기존의 피드백과 상반되는 피드백을 드렸던 것 같네요.. ㅠㅠ

저도 아직 부족한 점이 많아서 리뷰를 드리면서 공부를 하다보니 기존의 생각에서 조금씩 변화가 생기는 부분들이 있는 것 같아요.. ㅠㅠ 파랑이 이해해주시면 감사하겠습니다 🙇🏼‍♂️

2022-03-07 16:16 UTC, lxxjn0 commented on src/main/java/lotto/view/OutputView.java
> +                        rank.toStringPrize(), rankCounter.getCountOfRank(rank)));
기존에 rank의 맴버 변수들을 String으로 변경하지 말고 메시지 포멧에서 `%d`로 받아준다면 `toStringXXX`과 같은 메서드가 없어도 될 것 같아요!! 👍🏼

2022-03-07 16:30 UTC, lxxjn0 approved these changes
파랑, 리뷰 반영하느라 수고 많으셨습니다!!!

이번 미션을 진행하면서 처음 코드에 비해서 정말 많은 향상이 느껴졌어요!! 이번 미션을 진행하면서 클래스를 분리할 때 항상 어떠한 책임을 가질 것인지, 그리고 그에 따른 행위를 풍부하게 제공해줄 수 있는지 등을 고민하고 그에 대한 코드 개선을 진행하느라 정말 고생하셨습니다 👍🏼 

다음 번에 더 발전한 파랑으로 만나길 기대하면서 이번 미션은 여기서 마무리하도록 하겠습니다!! 수고하셨어요 😄

2022-03-07 16:30 UTC, lxxjn0 commented on src/main/java/lotto/controller/Controller.java
> +        LottoCount lottoCounter = getLottoCounter(lottoPurchaseMoney);
메서드 명과 변수 명도 다음에 같이 확인해보면 좋을 것 같아요 :)

2022-03-07 16:30 UTC, lxxjn0 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final Map<Integer, LottoNumber> CACHE = new HashMap<>();
CACHE를 static 스코프 내에서 불변으로 생성해서 할당해주면 보다 안전한 CACHE를 사용할 수 있을 것 같아요!! :)

2022-03-07 16:30 UTC, lxxjn0 commented on src/main/java/lotto/domain/Lottos.java
>  public class Lottos {
제가 생각하기에는 lotto 리스트를 가지고 있음으로 할 수 있는 행위가 없는 것 같아서 도메인으로 유지되긴 적절하지 않다고 생각해요 ㅠㅠ 만약 맴버 변수로 관리하는 lottos에게 어떠한 행위가 할당되어 진다면 객체로서의 가치가 있을 것 같은데 현재는 단순히 감싸고 있는 역할만 하는 객체로 보여서 도메인으로 유지되기에는 그 이유가 부족하다고 보여집니다. (만약 `lottos.compare(winningLotto)`와 같이 결과를 비교하는 로직이 있었다면 충분한 행위를 가지고 있어서 도메인으로 유지되어져도 괜찮았을 것 같아요!!)

2022-03-07 16:48 UTC, merged