[2단계 - 로또(수동)] 소주캉(강승주) 미션 제출합니다.
woowacourse/java-lotto pull request #499
Opened 2022-03-05 05:49 UTC by sojukang

안녕하세요👋👋 `카일`!! 다시 한번 리뷰 부탁드리게 된 `소주캉`입니다. 
2단계는 기본적으로 `카일`이 남겨주신 피드백을 바탕으로 리팩토링한 뒤, 기능을 추가하며 리팩토링 하였습니다. 
2단계에서 고려한 사항은 다음과 같습니다. 
1. 최대한 객체를 불변화하기 위해 객체 내, 외로 `Collection`등 참조 형 객체를 전달할 때 `List.copyOf`로 복사
2. 최초 생성 시점 이후 객체의 상태를 변경하지 못하도록 함
3. 인스턴스 메소드로 가능한 경우 static 메소드보다 `인스턴스 메소드`를 먼저 고려
4. 각 객체에서 2개 이상의 메소드에 의해 사용되는 경우에만 `필드`로 갖는 것을 고려
5. 객체 사이 책임 분산 
6. `View`와 관계 없이 객체의 특성을 잘 나타낼 수 있는 경우 `toString` 사용, `Lotto`의 `toString`으로 번호를 담은 `String`을 반환하는 것은 객체에게 기대하는 자연스러운 행동이므로 이런 경우 `toString`을 정의하여 `View`에도 사용하였습니다. 
7. 로또 번호를 생성해주는 `LottoNumberGenerator` 인터페이스화

이번에도 잘 부탁드립니다🙏🙏✨!

2022-03-05 05:56 UTC, sojukang commented on src/main/java/lotto/model/LottoResult.java
>              .collect(groupingBy(rank -> rank, () -> new EnumMap<>(Rank.class), counting())));
`() -> new EnumMap<>(Rank.class)` 부분이 중복인지 찾아보았는데, `groupingBy()` 메소드의 2번째 인자(`Supplier`)가 없을 경우 2번째 인자의 기본 값으로  `hashMap::new`을 사용하더라구요!  그래서 `EnumMap`으로 만들기 위해 2번째 인자로 `Supplier`타입으로 `() -> new EnumMap<>(Rank.class)` 를 넣어주었고, 이를 수정하지 못하게 하기 위해서 `Map.copyOf()`로 복사하여 리턴하였습니다. 제가 미처 고려하지 못한 부분이 있을까요😥?

2022-03-06 09:52 UTC, KIMSIYOUNG requested changes
안녕하세요 소주캉! 
많은 부분들을 고려해주셨네요🙂
조금 더 고민해보면 좋을 부분에 대해서 코멘트 남겼으니 확인 부탁드립니당!
불변적 복사에 대해서는 최소한의 기준으로 수정해보시면 좋을 것 같아요!

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/numbergenerator/ShuffleGenerator.java
> +    public List<Integer> generate() {
해당 객체의 역할을 어디까지 가져갈 것 인가에 대해서 조금 더 고민해보면 좋을 것 같아요. 아래의 역할이 모두 `ShuffleGenerator`의 역할인지, 일부는 `Lotto`의 역할인지 고민해보면 좋을 것 같습니다. 🙂

- 난수의 로또번호를 생성하는 행위
- 생성된 로또번호 6자리를 섞는 행위
- 이를 순서대로 정렬하는 행위

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/numbergenerator/ManualGenerator.java
> +    public ManualGenerator(List<List<Integer>> manualLottos) {
전략패턴을 통해서 잘 구현해주셨네요🙂

여기서도 `ShuffleGenerator`와 동일하게 역할을 어디까지 가져갈 것인지 조금 더 고민해보면 좋을 것 같습니다.

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/numbergenerator/LottoNumberGenerator.java
> +    List<Integer> generate();
LottoNumberGenerator 임에도 List<Integer>을 사용하고 있어요🙂 혹시 LottoNumber를 생성하지 않고 Integer를 사용하시는 이유가 있으실까요?

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/numbergenerator/ManualGenerator.java
> +        this.manualLottos = List.copyOf(copyOfManualLottos.stream()
방어적 복사를 통해서 사이드이펙트를 최소화하고 계시네요🙂 

방어적복사나 불변객체도 좋지만 가독성도 중요한 것 같아요. 파라미터로 넘어온 값은 이미 복사하여 사용하고 있고, 스트림에서 생성되는 값은 생성자에서만 사용되는데 추가적인 복사를 할 이유는 없는 것 같아요.

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/numbergenerator/ShuffleGenerator.java
> +    public List<Integer> generate() {
저라면, 두가지 선택지가 있는 것 같아요. LottoFactory 라는 인터페이스로 변경하고 로또 생성의 전체 책임을 이관받아, 로또 자체를 반환하는 형태로 만들거나 또는 LottoNumber만을 생성하는 역할로 간주한다면 실질적으로 로또를 만들기 위한 정렬 등의 행위는 로또로 옮겨볼 것 같아요.

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
>          validateDuplicationLottoNumbers(lottoNumbers);
중복이 없는 자료형을 사용한다면 해당 검증은 사라지고 보다 분명하게 로또번호는 중복되지 않는다는 것을 드러낼 수 있을 것 같아요.

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lotto.java
> +        return List.copyOf(integers.stream()
방어적 복사는 좋지만 대부분의 메소드에서 방어적 복사를 사용한다면 오히려 가독성을 해칠 수 있어요.

가장 필요한 곳에 한 번만 호출하는 것으로 충분하다고 생각이 드는데 소주캉의 의견은 어떠신가요?

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/controller/LottoController.java
> +        Lottos manualLottos = lottoGame.buyManualLottos(inputManualLottos(numberOfManualLottos));
수동로또를 반환받고 아래에서 다시 수동로또들을 메소드의 파라미터로 넣어주고 있네요🙂

해당 객체를 만들어내고 메시지를 보내는 역할이 `LottoGame`이라고 생각한다면, LottoGame이 해당 객체를 직접가지는 건 어떨까요? 

불필요한 필드값을 가지고 있다는 생각이 든다면, Lottos의 필드변수를 Map<LottoType, List<Lotto>> 와 같은 형태로 가지고 있는 것도 좋은 방법일 것 같아요.

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoMoney.java
> +        return Math.toIntExact(lottoMoney / LOTTO_PRICE - numberOfManualLottos);
자동로또의 갯수는 필드값으로 가지지 않고 수동로또의 갯수만 필드값으로 가지는 이유가 있을까요? 

소주캉의 필드로 선언하는 기준이 궁금해요🙂

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lottos.java
> +        return List.copyOf(thisLottos);
이 부분도 방어적 복사가 꼭 필요한지 고민해봐주세요🙂

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lottos.java
> +        validateNullCollection(this.lottos);
인스턴스변수에 할당한 이후에 해당 값을 검증하는 이유가 있을까요?

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/Lottos.java
> +    Lottos(LottoNumberGenerator lottoNumberGenerator, int count) {
수동로또와 자동로또를 생성하기 위해서는 로또 생성자를 2번 호출해야겠네요🙂 

현재 구조에서 충분히 좋은 구조라고 생각되지만, 한 번에 생성하고 조회시에만 수동과 자동을 구분하여 반환할 수 있다면 더 좋을 것 같아요. (로또내에서 수동과 자동을 구분하는 해당 코멘트는 미션 요구사항과 조금 벗어나기 때문에 추후에 해보셔도 좋을 것 같아요.)

2022-03-06 09:52 UTC, KIMSIYOUNG commented on src/main/java/lotto/ValidationUtils.java
> +    public static void validateNullCollection(Collection<?> collection) {
유틸성클래스로 일반적인 검증들을 모아주셨네요👏

2022-03-06 09:53 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoResult.java
>              .collect(groupingBy(rank -> rank, () -> new EnumMap<>(Rank.class), counting())));
요 부분에서 어떤 부분을 궁금해하시는지 잘 이해를 못했습니다ㅠㅠ 조금 더 설명해주실 수 있나요?

2022-03-07 07:22 UTC, sojukang commented on src/main/java/lotto/model/LottoMoney.java
> +        return Math.toIntExact(lottoMoney / LOTTO_PRICE - numberOfManualLottos);
자동 로또의 갯수는 `LottoGame`에 의해 단 한번 쓰이며, `LottoMoney`내의 다른 메서드에서 전혀 쓰이지 않고, 수동 로또의 개수로 계산할 수 있기 때문에 이번에는 두지 않았습니다!!

2022-03-07 07:26 UTC, sojukang commented on src/main/java/lotto/model/Lottos.java
> +        validateNullCollection(this.lottos);
이 부분은 `이펙티브 자바 Item 50 적시에 방어적 복사본을 만들라`에서 
> 매개변수의 유효성을 검사하기 전에 방어적 복사본을 만들고, 이 복사본으로 유효성을 검사한 점에 주목하자. 순서가 부자연스러워 보이겠지만 반드시 이렇게 작성해야 한다. 멀티스레딩 환경이라면 원본 객체의 유효성을 검사한 후 복사본을 만드는 그 찰나의 취약한 순간에 다른 스레드가 원본 객체를 수정할 위험이 있기 때문이다. 

이를 수용하여 다른 부작용이 없다고 판단하여 검증을 후에 작성하였습니다!

2022-03-07 07:34 UTC, sojukang commented on src/main/java/lotto/model/LottoResult.java
>              .collect(groupingBy(rank -> rank, () -> new EnumMap<>(Rank.class), counting())));
앗! 이 코드는 저번 리뷰에서 `카일`이 작성해주신
`() -> new EnumMap<>(Rank.class)`가 중복인 것 같다는 코멘트를 보고 찾아본 내용입니다!

2022-03-07 07:36 UTC, sojukang commented
안녕하세요👏👏🤸‍♂️ `카일`!! 2 단계 리뷰도 정말 감사드립니다. 
이번 리팩토링을 진행하며 고려한 내용은 다음과 같습니다. 
1. `LottoFactory`를 두어 로또 생성 역할을 전부 담당할지, 기존의 `LottoNumberGenerator`를 유지하며 책임을 분산할지 두 방법 모두 사용하여 비교한 결과 `LottoFactory`를 두는 방법이 적절한 역할과 책임의 분배, 독립성이라는 객체지향을 더 잘 준수한다고 판단하여 결정하였습니다. 
2. 필요한 곳에서 방어적 복사를 하기로 제한 
3. `Lotto`의 자료형을 `TreeSet`으로 사용하여 중복, 정렬 문제 해결
4. `LottoGame`이 `Map<LottoType, Lottos>`을 가지고 전달하기로 변경 

이번 미션을 `카일`과 함께 진행하면서 객체의 역할 분담, 객체를 불변으로 만드는 방법 등 많이 공부하며 성장한 것 같습니다! 
다시 한번 감사드립니다👍✨.

2022-03-09 07:21 UTC, KIMSIYOUNG approved these changes
안녕하세요 소주캉!
리뷰 잘 반영해주셨네요🙂
1, 2 단계동안 고생많으셨습니다! 궁금하신 내용은 언제나 편하게 말씀주세요!

2022-03-09 07:21 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoMoney.java
> +        return Math.toIntExact(lottoMoney / LOTTO_PRICE - numberOfManualLottos);
다른 필드로 충분히 유추할 수 있는 값이기에 좋은 방법인 것 같아요🙂 

다만 자동로또와 수동로또가 존재한다라는 것을 조금 더 명확하게 명시해주는 방법 + 재계산을 방지하는 형태로 필드로 가지고 있는 것도 방법이 될 수 있습니다. 참고만 부탁드려요🙂

2022-03-09 07:22 UTC, merged

2022-03-09 07:25 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/lottofactory/Lotto.java
> +    Lotto(Set<LottoNumber> inputLottoNumbers) {
패키지 프라이빗을 통해서 로또생성에 대한 역할은 항상 팩토리를 통해 사용할 수 있도록 해주셨네요👏

파라미터로 로또팩토리라는 인자를 받아서 생성하는 것도 보다 열린 방법으로 로또를 생성하는 가능성을 열어줄 수 있을 것 같아요.

2022-03-09 07:38 UTC, KIMSIYOUNG reviewed
전체적으로 코드가 깔끔하네요🙂
조금 더 리팩토링한다면 `LottoResult` 객체의 메소드네이밍을 조금 변경해서 가독성 좋은 코드로 만들어볼 수 있을 것 같아요.

2022-03-09 07:38 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoGame.java
> +    private void buyManualLottos(List<List<Integer>> inputManualLottos) {
요 부분에서 수동으로 생성하는 것도 주입을 통해서 할 수 있으면 통일성있는 코드가 될 것 같아요. 

추가로 List<List<Integer>> 형태로 파라미터를 받는 이유가 있을까요?

2022-03-09 07:38 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoResult.java
> +        List<Integer> copyOfRawWinningNumbers = List.copyOf(rawWinningNumbers);
방어적복사를 최소화하는 형태로 변경해주셨네요🙂

개인적인 취향이지만 방어적 복사를 사용하고 있다는 걸 명시적으로 드러내기 위해서 가장 상단에 새로운 변수로 선언하고 이를 사용하는 것을 선호하는데 소주캉은 어떠신가요?🙂

2022-03-09 07:38 UTC, KIMSIYOUNG commented on src/main/java/lotto/model/LottoResult.java
> +    LottoResult(Map<LottoType, Lottos> lottosMap, List<Integer> rawWinningNumbers, int bonusNumber) {
우승번호를 Lotto에서 List<Integer>타입으로 변경하도록 하는 형태로 변경해주셨는데 이유가 있을까요? 

수동로또의 맥락으로 본다면 동일할 것 같아서요🙂