[2단계 - 로또(수동)] 승팡(김승래) 미션 제출합니다.
woowacourse/java-lotto pull request #501
Opened 2022-03-06 02:05 UTC by Seungpang

안녕하세요. 던! 승팡입니다. 🤗
제가 장염으로 인한 컨디션 관리 실패로
늦게 미션을 제출하게 된점 죄송하게 생각합니다 ㅠㅠ
2단계 미션에서 추가된 요구사항을 반영하면서 기존 코드에 대한 재사용성을 높이는 방향으로 리팩토링을 진행해 봤습니다.

그리고 1단계 미션 마지막 피드백에 대한 답과 궁금증은 해당부분에 코멘트로 달아 놓겠습니다.
이번 리뷰도 잘 부탁드립니다
던도 건강 조심하세요 ㅠㅠ

2022-03-06 03:47 UTC, Seungpang commented on src/test/java/lotto/domain/LottoStatisticsTest.java
> +        assertThat(statistics.calculateEarningRates(money)).isEqualTo("1.66");
처음에는 (double) 5000 / 3000으로 작성하였다가 하드코딩으로 작성하였다가
money.divideByAmount(5000L)을 사용하는 로직으로 변경하였습니다.
하지만 던이 당첨등급의 당첨금액이 변경되더라도 테스트 코드 수정없이 테스트 코드가 통과하도록 변경해보라고 해서
```java
        int fifthPrize = LottoRank.FIFTH.getPrize();
        int sixthPrize = LottoRank.SIXTH.getPrize();
        long totalPrize = fifthPrize + sixthPrize + sixthPrize;
        double expected = money.divideByAmount(totalPrize);

```
위와 같은 방식으로 생각했습니다.

그런데 수익률 계산하는 부분에서 소수점 자리수 버림으로 처리해야해서 그 책임을 어디로 둘까 하다가
LottoStatistics로 생각해서 로직을 수정하니 이 테스트 코드에 대한 고민이 깊어졌습니다.
무언가 값이 변경되어도 테스트 코드 수정없이 테스트 코드가 통과하도록 하려고하니 
프로덕션 코드와 결합이 강해지는 느낌을 받았습니다.

그래서 검증부에 어떤 방식으로 하는게 좋을까 고민하다가 [이 글](https://jojoldu.tistory.com/615?category=1036934)을 읽고 최종적으로 결과값을 하드 코딩했습니다.
내용을 요약해 보면 소프트 코드(도메인 로직이 포함된) 검증문을 사용하면
+ 무의미한 검증
    + 사실상 프로덕션 코드를 복사 & 붙여넣기 한 것 외에는 없다.
+ 구현코드와의 강결합
+ 거짓 성공
    + 도메인 로직 자체가 버그인 경우에도 테스트가 실패하지 않는다.
+ 결과 예측의 어려움
+ Test First 개발의 어려움

이러한 문제점들이 있어서 하드코딩을 했습니다. 어쩌면 제가 잘못된 이해로 다른 고민에 빠진 걸 수도 있지만
이번 기회에 검증문에 어떤 방식으로 할지 고민해 볼 수 있었던 시간이었습니다.

다른 방법이나 좋은 의견이 있으시면 알려주시면 감사하겠습니다.

2022-03-06 04:25 UTC, Seungpang commented on src/main/java/lotto/controller/LottoController.java
>          StatisticsResult result = getStatisticsResult(money, lottoTickets, winningTicket);
`Money, WinningTicket, StatisticsResult 객체를 컨트롤러에서 생성한 이유가 있을까요?`
`컨트롤러에서는 어떤 로직들이 처리되어야한다고 생각하시나요~?`

저는 controller가 view와 domain의 연결 지점이라고 생각하고 view에 입력받은 값으로
객체를 생성하고 로직을 실행한 뒤 다시 결과를 생성하여 view로 넘겨주는 역할을 하고 있습니다.

아마 질문주신 의도는 레이어 아키텍처 관점에서 controller가 Presentation Layer라 비즈니스 로직은
Service Layer로 위임하고 처리된 결과를 controller가 받는 그런 구조여서 일까요..?
일단 저는 지금같이 기능이 작은 경우에는 오히려 service를 사용하는것보다 단순한 MVC구조가 더 기능 파악하기 쉽다고 생각하여
단순 Controller만 있습니다.

2022-03-07 03:29 UTC, gch01410 requested changes
안녕하세요 승팡!
깔끔하게 설계하셔서 코드가 잘 읽히네요 👍 
더 개선해볼만한 부분이 보여 코멘트 남겼습니다.
그리고 몸조리 잘 하시길 바랍니다! 💪

2022-03-07 03:29 UTC, ghost commented on src/main/java/lotto/domain/LottoStatistics.java
> +            * DECIMAL_POINT_CHANGE_NUMBER) / DECIMAL_POINT_CHANGE_NUMBER);
이 메서드 안에서 단순 변환뿐 아니라 수익률을 계산하는 로직도 포함되어 있어서 convertFormat 이라는 네이밍이 어색해보이네요

2022-03-07 03:29 UTC, gch01410 commented on src/main/java/lotto/controller/LottoController.java
>          StatisticsResult result = getStatisticsResult(money, lottoTickets, winningTicket);
승팡이 설계한 구조는 컨트롤러가 게임진행의 역할도 일부 하는것으로 이해하면 될까요?
model영역으로 넘긴 값이 어떤식으로 처리되고 관리되는지는 컨트롤러가 알고 있을 필요는 없다고 생각해서 말씀드렸어요! (구입금액이라는 값이 Money라는 객체로 관리된다.. 등)
말씀하신대로 지금 구조가 기능파악이 쉽다고 생각하시면 지금처럼 하셔도 괜찮습니다~

2022-03-07 03:29 UTC, gch01410 commented on src/test/java/lotto/domain/LottoStatisticsTest.java
> +        assertThat(statistics.calculateEarningRates(money)).isEqualTo("1.66");
오 좋은 관점의 글이네요!
특히 `Test First 개발의 어려움` 은 TDD를 하고 있다면 직접적으로 와닿을 수 있겠어요.
그 외에 다른 이유는 하드코딩을 해도 비슷한 문제가 발생하는게 아닌지..? 하는 생각은 드네요.
그치만 TDD를 하고 있는 지금상황에서는 마지막 이유만으로도 하드코딩이 더 나을 수 있겠네요!

2022-03-07 03:29 UTC, gch01410 commented on src/main/java/lotto/domain/LottoTicket.java
>      }
LottoTicket 객체는 숫자들이 입력될때 ','로 구분되어있다는것은 몰라도 되지않을까요~?
LottoTicket은 숫자로된 리스트를 받아서 로또번호 리스트를 생성하기만 하면 될 것 같네요

2022-03-07 03:29 UTC, gch01410 commented on src/main/java/lotto/domain/LottoTicket.java
>      }
LottoTicket에서 수동생성, 자동생성 로또를 생성하는 방법이 각각 다르네요!
하나로 통일해볼 수 있을까요?

2022-03-07 10:22 UTC, Seungpang commented on src/main/java/lotto/domain/LottoTicket.java
>      }
기존에 있는 로직을 재사용하려고 하다보니 이렇게 리팩토링이 된 것 같습니다.
수동, 자동 구매 로직을 합치면서 제거했습니다.

2022-03-07 10:23 UTC, Seungpang commented on src/main/java/lotto/domain/LottoTicket.java
>      }
네 수동과 자동에 대한 부분을 하나로 통일하고 
기존에 NumberGenerator를 이용하여 통일하였습니다.

2022-03-07 10:24 UTC, Seungpang commented on src/main/java/lotto/domain/LottoStatistics.java
> +            * DECIMAL_POINT_CHANGE_NUMBER) / DECIMAL_POINT_CHANGE_NUMBER);
네. Format에 너무 초점을 맞췄던것 같습니다. ㅠㅠ
수정하겠습니다.

2022-03-07 10:31 UTC, Seungpang commented on src/test/java/lotto/domain/LottoStatisticsTest.java
> +        assertThat(statistics.calculateEarningRates(money)).isEqualTo("1.66");
이 부분에 대해서는 계속 고민하고 있습니다. 이 말이 정확하게 다 맞아는 아니지만
어떤 변경에 대해서 테스트 코드를 수정할 때 어떤 방식이 이점이 있을까?를 생각하며
고쳐 나가면서 저만의 근거를 하나씩 찾아나가볼 생각입니다.

2022-03-07 10:50 UTC, Seungpang commented on src/main/java/lotto/controller/LottoController.java
>          StatisticsResult result = getStatisticsResult(money, lottoTickets, winningTicket);
네 맞습니다.
이전 미션에는 기능이 작아도 서비스 레이어와 프레젠테이션 레이어를 분리했습니다.
그런데 미션을 진행하면서 아직 TTD나 OOP도 충분하지 않는데 dto, 아키텍처 레이어 등등
다른 것들에 더 눈을 두고있는건 아닌가? 라는 생각이 들기도 했습니다.
그래도 여러가지를 시도해보고 싶고 사실 다 분리하려고 했는데 컨디션 관리를 실패했습니다...
여기까지 저의 푸념이였습니다 ㅠㅠ

2022-03-07 11:38 UTC, Seungpang commented
안녕하세요 던! 승팡입니다.
피드백 주신 내용을 빠르게 반영하려고 노력했습니다.
기존에 빠르게 pr을 보내지 못한 것에 아쉬움이 계속 남는 것 같습니다.

이번 리뷰도 잘 부탁 드립니다.

2022-03-07 12:55 UTC, gch01410 approved these changes
안녕하세요 승팡!
아쉽게도 PR 마감기간이 지나서 이만 머지하도록 하겠습니다!
잘 구현해주셔서 코멘트 남길만한 부분도 딱히 안보이네요ㅎ 💯 
로또게임 구현하시느라 고생많으셨습니다!
우테코 기간동안 몸 조리 잘하시길 바랍니다!

2022-03-07 12:55 UTC, merged