[로또] 도넛 미션 제출합니다.
woowacourse/java-lotto pull request #55
Opened 2019-06-11 05:43 UTC by codeanddonuts

감사합니다 .. ㅠㅠ

2019-06-15 13:08 UTC, kang-hyungu requested changes
안녕하세요 리뷰어 강현구입니다.
피드백이 길어져서 한 번 끊고 갈게요.
패키지는 mvc로 나눠두셨는데 실제 클래스들은 mvc로 나눠지진 않았네요
WebUILottoApplication을 컨트롤러로 나눠보시고 model에 필요한 클래스들을 더 추가해보아요
그리고 테스트 코드도 깨지니까 한 번 점검해보세요
model 관련 코드 정리가 되면 나머지 피드백 진행할게요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersFactory.java
> +public class WinningNumbersFactory {
정적 팩터리 메서드만 사용하도록 기본 생성자는 private으로 막아두면 어떨까요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
>  public class WebUILottoApplication {
각 기능별로 컨트롤러를 나눌 수 있지 않을까요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
> +    private static String orThrowError(SupplierWithExceptions<String, Exception> f, Response res) {
에러 페이지 처리를 위한 클래스를 따로 만드는건 어떨까요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
> +    private static String main() {
main 메서드랑 다른 역할인데 이름이 같아서 코드 읽기 어렵네요
index 메서드가 어울리지 않을까요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
> +        JsonElement el = new JsonParser().parse(req.body());
form data가 아닌 json으로 받는 이유가 있을까요?
지금 구조에서는 굳이 json으로 받을 필요는 없어보여서요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
> +    private static List<Lotto> parseManualLottos(Request req) {
이 메서드는 모델 계층에서 도메인에게 요청해서 List<Lotto>를 받아오게 바꿔야겠네요
컨트롤러는 다른 계층에 연결해주는 역할만 주는게 좋아요
그리고 Request 객체 그대로 모델로 전달하지 말고 필요한 값만 꺼내서 전달해주세요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
> +        final Lottos lottos = new Lottos(
모델에서 처리할 수 있을 것 같네요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
> +        PurchaseHistory.writeLog(lottos, round, result);
모델에서 처리할 수 없을까요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
> +            put("winningNumbers", WebView.formatWinningNumbers(winningNumbers));
모델은 데이터만 가지고 있어야합니다.
html 코드는 view에서 처리해주세요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/DB.java
> +public class DB {
DB가 맞을까요?
DAO라는 이름으로 안한 이유가 있을까요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/Lotto.java
> +    private static final int RECENT_ROUND = 862;
이 값들은 무엇을 의미하는건가요??
하드코딩한 값들 같은데... 최근 로또 회차인가요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/Lotto.java
> +    private static final int RECENT_ROUND = 862;
로또 회차는 시간이 흐르면 계속 변경되는 값인데 상수로 가지고 있는게 맞을까요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/Lotto.java
> +        return RECENT_ROUND + Period.between(RECENT_DATE, LocalDate.now()).getDays() / WEEK;
하드코딩한 값으로 지금 몇회인지 계산해주는 로직 같은데... 1회차부터 계산하면 회차가 안맞나보네요
그렇다면 로또가 무조건 매주 한다는게 아닐수도 있겠네요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/Lotto.java
> +    public String encodeToDB() {
이 메서드는 도메인 객체에 있으면 안됩니다.

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/LottoResult.java
> +    public Money purchasedAmount() {
이럴땐 getter로 써주세요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/Lottos.java
> +                Stream.of(encoded.split("]"))
대괄호로 split 해야되는 로직이 필요하다면... 입력 받을 때 대괄호를 걸러서 받으면 되지 않나요?
대괄호가 아닌 다른 값으로 입력이 들어오면 또 수정해야되지 않을까요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/Lottos.java
> +    public String encodeToDB() {
이 메서드도 없애야합니다

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/PurchaseHistory.java
> +public class PurchaseHistory {
데이터베이스에 연결하는 다른 클래스들은 DB가 붙어있는데 이 클래스는 없네요
클래스명에 일관성이 있어서 역할 구분이 용이합니다

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/PurchaseHistory.java
> +    public static void writeLog(Lottos lottos, int round, LottoResult result) {
result는 안쓰는 파라미터네요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/PurchaseHistory.java
> +            pstmt.setString(2, lottos.encodeToDB());
로또 히스토리를 저장하는 클래스를 따로 만들어서 그 객체가 encodeToDb를 처리하게 해주세요.

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/PurchaseHistory.java
> +            final PreparedStatement pstmt = db.connect().prepareStatement("SELECT date FROM purchase_history");
**모든 데이터를 조회하는 쿼리는 절대 작성하지 마세요.**
서비스 장애 납니다.
날짜 범위로 조회하게 하세요.

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/PurchaseHistory.java
> +                fetched.add(result.getTimestamp(1));
이 로직이 잘 이해가 안가는데... 어떤걸 하려는건가요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/PurchaseHistory.java
> +        final PreparedStatement pstmt = db.connect().prepareStatement("SELECT round, lottos FROM purchase_history WHERE date=?");
```suggestion
        final PreparedStatement pstmt = db.connect().prepareStatement("SELECT round, lottos FROM purchase_history WHERE date = ?");
```

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/PurchaseHistory.java
> +            this.round = result.getInt(1);
데이터 조회 결과를 받는 Dto를 하나 만들어서 화면으로 전달하세요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersDB.java
> +        final PreparedStatement pstmt = db.connect().prepareStatement("SELECT * FROM winning_numbers WHERE round=?");
```suggestion
        final PreparedStatement pstmt = db.connect().prepareStatement("SELECT * FROM winning_numbers WHERE round = ?");
```

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersDB.java
> +        final PreparedStatement pstmt = db.connect().prepareStatement("SELECT * FROM winning_numbers WHERE round=?");
**절대 \*만 쓰지 마세요**
디비 스키마가 바뀌면 장애 납니다.
내가 조회할 필드명을 꼭 명시하세요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersDB.java
> +    private List<Integer> fetchFromResult(ResultSet result) throws SQLException {
dao에서는 데이터 조회만 해오고 결과를 가공하는건 모델에서 해주세요

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersDB.java
> +    protected static void register(WinningNumbers winningNumbers, int round) {
WinningNumbersFactory가 이 메서드 호출하면 팩터리 메서드 역할을 벗어나는게 아닌가요?

2019-06-15 13:08 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersDB.java
> +public class WinningNumbersDB implements WinningNumbers {
도메인, 모델 계층 철저하게 분리하셔야 코드 복잡성을 줄일 수 있습니다.
WinningNumbers를 implements해야될 이유가 무엇인가요

2019-06-22 15:07 UTC, codeanddonuts commented on src/main/java/controller/WebUILottoApplication.java
> +        JsonElement el = new JsonParser().parse(req.body());
req.queryParams() 같은 함수로는 인식을 못해서 어쩔 수 없이 썼습니다

2019-06-22 15:08 UTC, codeanddonuts commented on src/main/java/model/LottoResult.java
> +    public Money purchasedAmount() {
무슨 뜻인지 잘 모르겠습니다

2019-06-22 15:08 UTC, codeanddonuts commented on src/main/java/model/PurchaseHistory.java
> +                fetched.add(result.getTimestamp(1));
DB의 히스토리에서 구매한 날짜를 가저오는 로직입니다

2019-06-22 15:09 UTC, codeanddonuts commented
제가 처음 만들던 당시에 DAO, DTO, VO, 서비스 레이어 등의 개념을 아직 접하지 못하였어서 최대한 배운 대로 고쳐보았습니다

2019-06-22 15:11 UTC, codeanddonuts commented on src/main/java/model/Lotto.java
> +        return RECENT_ROUND + Period.between(RECENT_DATE, LocalDate.now()).getDays() / WEEK;
만들었던 때의 회차가 862회였어서 그런 거고 1회부터도 맞는 것 같긴 하지만 회차도 웹에서 불러오도록 새로 구현하였습니다

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersFactory.java
> +            WinningNumbersWeb fetched = new WinningNumbersWeb(round);
fetched.isEmpty()일 때 SQLException을 사용하면 안됩니다.
그냥 빈 리스트로 반환하고 그 처리를 따로 해주시는게 좋아요
이펙티브 자바 3판 아이템 69 예외는 진짜 예외 상황에만 사용하라를 참고하세요

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersFactory.java
> +    public static WinningNumbers of() {
정적 팩터리 메서드의 장점을 활용해보아요
ofDefault나 ofZero 같은 이름을 주면 어떤 객체를 생성하는지 구분하기 좋을 거에요

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersFactory.java
> +    public static WinningNumbers of(String input) {
ofManual 정도로 바꾸면 훨씬 이해하기 좋겠네요

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersManual.java
> +    protected WinningNumbersManual(Set<LottoNumber> mainNumbers, LottoNumber bonusNumber) {
1. 사용하는 곳이 없다고 나오네요
2. WinningNumbersManual(String input) 생성자에 중복된 코드가 보이네요. this(mainNumbers, bonusNumber)를 쓰면 중복 제거할 수 있을거에요

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersRecentRound.java
> +        LocalDateTime candidateA = LocalDateTime.now().with(
불용어를 쓰지 맙시다
nextStaurday, currentStaurday 같은 단어로 표현할 수 있지 않을까요?

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersRecentRound.java
> +        return recentRound;
값을 반환할 필요는 없겠네요

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersWeb.java
> +            throw new RuntimeException();
e 객체를 누락시키면 안됩니다.
예외가 발생한 상황을 로그로 남기거나 new RuntimeException(e)로 전달하세요
new RuntimeException()만 하면 무슨 이유로 예외가 발생했는지 찾을 방법이 없어요

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/model/WinningNumbersWeb.java
> +            if (numbers.isEmpty()) {
1. 로또 사이트가 개편해서 >숫자< 구조가 깨지면 무한루프도 빠지는 구조네요.
2. numbers.isEmpty() || round == 0로 조건 바꾸고 round == 0 조건절에 있는 구문을 그대로 수행하면 의도한 로직대로 동작하지 않을까요?

2019-06-24 00:38 UTC, kang-hyungu commented on src/main/java/controller/WebUILottoApplication.java
> +        JsonElement el = new JsonParser().parse(req.body());
view에서 axios를 사용해서 json 포멧으로 보내는 구조로 만드셨군요
rest api 관련해서는 다음 과정들 진행할 때 더 이야기해보아요

2019-06-24 00:43 UTC, kang-hyungu commented on src/main/java/model/LottoResult.java
> +    public Money purchasedAmount() {
인스턴스변수를 단순 반환하는 메서드는 getPurchasedAmount로 쓰자는 뜻이었어요
get을 붙여두면 단순 값 조회 용도인 getter로 이해하기 쉬울테니깐요

2019-06-24 01:05 UTC, kang-hyungu requested changes
피드백 반영한 내용 확인했어요!
훨씬 코드 퀄리티가 좋아졌어요 :+1: 
몇가지 피드백 남겼으니 참고하세요
mvc 구조로 구현하는건 아직 익숙하시지 않은 것 같으니 다음 과정 진행하실 때 좀더 이야기해보아요
머지를 해도 괜찮을 것 같은데 간단한 피드백이니 한 번 보시고 재요청주세요!

2019-06-24 01:05 UTC, kang-hyungu commented on src/main/java/model/LottoHistoryDAO.java
> +                    "SELECT date FROM purchase_history LIMIT 1000"
limit으로 갯수 제한하려면 orber by로 꼭 정렬해주세요
집합론을 기반으로 만들어진 rdb는 조회 순서를 보장하지 않습니다.
조회할 때마다 오름차순, 내림차순으로 보여주는건 ide나 db툴에서 제공하는 사용자 편의 기능입니다.

2019-06-25 11:52 UTC, kang-hyungu approved these changes
피드백 반영 확인했어요!
코드 구현하느라 고생하셨습니다 :+1: 
로또는 머지 할게요 체스 미션 마무리 잘 하세요!

2019-06-25 11:52 UTC, merged