[로또 - 웹, DB] 루피 미션 제출합니다.
woowacourse/java-lotto pull request #57
Opened 2019-06-11 15:47 UTC by MrKwon

Spark Java 와 HTML UI 까지 구현해보았습니다. 항상 감사드립니다.

2019-06-12 01:19 UTC, pobiconan requested changes
도메인 객체의 변경을 최소화하면서 웹 UI 적용 잘 했네요. 💯 
추가 연습과 개선을 위한 피드백 남겼어요.

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/GameDAO.java
> +    public Connection getConnection() {
이 메소드는 향후 다수의 DAO 클래스에서 쓸 수 있기 때문에 클래스를 분리하는 것이 어떨까?

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/GameDAO.java
> +    public Connection getConnection() {
이 메소드를 굳이 인스턴스 메소드로 구현할 필요가 있을까?

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/GameDAO.java
> +            System.out.println(gameDTO.getReturnRate());
모든 데이터 하나에 대해 값을 출력하기 보다 GameDTO에 toString() 메소드를 구현한 후 모든 값을 추가한 후 GameDTO 하나만 출력하는 것은 어떨까?

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/GameDAO.java
> +    public GameDTO getGameInformation(int id) throws SQLException {
select query와 같은 경우 db 접속을 위해 중복되는 부분이 중복을 제거하는 좋은 방법은 없을까?

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/WebUILottoApplication.java
> +            model.put("return_amount", gameDTO1.getReturnAmount());
model에 너무 많은 값을 전달하는 것이 좋은 것은 아니다.
GameDTO의 값을 하나씩 꺼내 전달하기 보다 GameDTO 하나만 전달하고 html에서 데이터를 꺼내는 방법을 찾아본다.

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/WebUILottoApplication.java
> +            GameDAO gameDAO = new GameDAO();
GameDAO는 상태 값(인스턴스 변수)이 없다.
이와 같이 상태 값이 없는 경우 매번 인스턴스를 생성할 필요가 없다.
singleton 패턴을 학습해 매번 인스턴스를 생성하지 않도록 구현해 본다.

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/WebUILottoApplication.java
>  public class WebUILottoApplication {
WebUILottoApplication을 보면 url path와 이에 대한 실행을 담당하는 부분이 있다.
로또의 경우 기능이 많지 않아 문제가 되지 않을 수 있다.
그런데 기능이 많아지는 경우 이 클래스가 너무 커질 수 있다.
이 경우 어떻게 개선하면 좋을까?

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/WebUILottoApplication.java
> +    private static final GameDTO gameDTO = new GameDTO();
이 객체의 경우 상태 값을 가진다.
멀티쓰레드에서 상태를 가지는  객체의 경우  인스턴스를 공유할 경우 문제가 발생할 수 있다.
이와 같이 구현하지 말고 매 요청마다 인스턴스를 생성하는 방식으로 구현해 본다.

2019-06-12 01:19 UTC, pobiconan commented on src/main/java/lotto/GameDAO.java
> +public class GameDAO {
테이블 생성을 위한 sql 파일도 git에서 관리하는 것이 어떨까?

2019-06-12 02:13 UTC, MrKwon commented on src/main/java/lotto/GameDAO.java
> +            System.out.println(gameDTO.getReturnRate());
앗.. 이건 필요 없는 print 문인데 제가 지우지 않았네요 😂 수정하였습니다.

2019-06-13 01:53 UTC, MrKwon commented on src/main/java/lotto/WebUILottoApplication.java
> +            model.put("return_amount", gameDTO1.getReturnAmount());
템플릿 엔진을 통해 해결하였습니다 !!!!

2019-06-13 01:53 UTC, MrKwon commented on src/main/java/lotto/WebUILottoApplication.java
> +            GameDAO gameDAO = new GameDAO();
singleton 패턴을 학습하여 피드백 반영했습니다 !

2019-06-13 01:59 UTC, MrKwon commented on src/main/java/lotto/WebUILottoApplication.java
> +    private static final GameDTO gameDTO = new GameDTO();
GameDTO 는 필요가 없는 부분이었고, WebUILottoData 는 구매 페이지로 넘어가는 시점에 인스턴스 생성을 하도록 변경하였습니다 !

2019-06-13 03:40 UTC, MrKwon commented on src/main/java/lotto/GameDAO.java
> +    public GameDTO getGameInformation(int id) throws SQLException {
selectQuery(String label) 라는 메소드를 만들어 label 로 select 하고 싶은 부분을 전달하는 방식으로 구현해보았습니다.

2019-06-13 03:42 UTC, MrKwon commented on src/main/java/lotto/GameDAO.java
> +    public Connection getConnection() {
다른 부분에서 singleton 에 대해 피드백 주신 내용을 공부해보니 jdbc connection 도 singleton 으로 구현하는 것도 괜찮을 것 같다고 생각하여 singleton 을 이용해 구현해보았습니다.

2019-06-13 03:43 UTC, MrKwon commented on src/main/java/lotto/GameDAO.java
> +    public Connection getConnection() {
피드백 반영하였습니다 !

2019-06-13 03:45 UTC, MrKwon commented on src/main/java/lotto/WebUILottoApplication.java
>  public class WebUILottoApplication {
구매에 관련된 기능들(BuyLottoAPI), 조회에 관련된 기능들(InquireLottoAPI), DB 등록(EnrollLottoAPI)에 관련된 기능을 각각 클래스를 생성하여 static 메소드로 구현해 보았습니다. 더 나아가 model 을 생성하는 부분들도 각 클래스 내의 private 메소드로 분리하여 구현해보았습니다.

2019-06-13 03:49 UTC, MrKwon commented on src/main/java/lotto/GameDAO.java
> +public class GameDAO {
만들어서 push 하였습니다 !

2019-06-13 04:36 UTC, MrKwon commented
포비님 ! 피드백 감사드립니다 ! 😁

Spark Java 를 처음 써봐서 어떻게 해야하는지 감을 잡지 못해서 리뷰를 받기 전에는 기능 구현에만 집중에서 리뷰 요청을 보냈습니다.

리뷰를 보고 이번 피드백을 반영하면서 계속 연습하던 메서드 분리에 대하여 신경써서 리팩토링하였습니다.
또한 피드백 주신 singleton 패턴에 대하여 학습하고 적용해보았습니다.

2019-06-13 05:01 UTC, pobiconan approved these changes
피드백 반영 잘 했네요. 💯 
다소 아쉬운 점은 있지만 새로운 개념 적용하는데 어려움이 있었을 것이라 생각해요.
새로운 기술은 조금은 익숙해진 만큼 다음 미션인 체스 게임 구현할 때 한 단계 더 개선해 보기를 기대합니다.

2019-06-13 05:01 UTC, merged