[로또(웹/DB)] 에단 미션 제출합니다.
woowacourse/java-lotto pull request #63
Opened 2019-06-12 08:38 UTC by Laterality

2019-06-24 00:44 UTC, pobiconan requested changes
전체적으로 깔끔하게 구현 잘 했네요. 💯 
특히 DAO의 메소드를 정말 작은 단위로 분리한 점이 인상적이네요.
피드백 몇 개 남겨요.

2019-06-24 00:44 UTC, pobiconan commented on src/main/java/com/woowacourse/lotto/persistence/DataSourceFactory.java
> +    public DataSource createDataSource() {
클래스 메소드로 구현해도 되지 않을까?

2019-06-24 00:44 UTC, pobiconan commented on src/main/java/com/woowacourse/lotto/persistence/DataSourceFactory.java
> +public class DataSourceFactory implements AbstractDataSourceFactory{
space convention 위반

2019-06-24 00:44 UTC, pobiconan commented on src/main/java/com/woowacourse/lotto/persistence/dao/AggregationDao.java
> +    public AggregationDao(DataSource ds) {
DataSource를 외부에서 전달한 것은 👍

2019-06-24 00:44 UTC, pobiconan commented on src/main/java/com/woowacourse/lotto/persistence/dao/AggregationDao.java
> +public class AggregationDao {
메소드를 작은 단위로 나눈 점 👍

2019-06-24 00:44 UTC, pobiconan commented on src/main/java/com/woowacourse/lotto/service/LottoService.java
> +public class LottoService {
각 DAO들도 상태를 가지지 않는다면 singleton 패턴을 적용해 인스턴스 하나를 재사용 가능하도록 구현해 본다.

2019-06-24 00:44 UTC, pobiconan commented on src/test/java/com/woowacourse/lotto/persistence/dao/AggregationDaoTest.java
> +        TEMP_WINNING_LOTTO.setWinningBonusNumber(7);
각 값을 set 하기보다 DTO에도 생성자를 만들어 구현해 보는 것은 어떨까?

2019-06-24 05:45 UTC, Laterality commented
리뷰 감사합니다! Dto에 팩터리 메서드를 추가해서 테스트 코드에서 테스트 케이스를 생성하는 코드 길이를 상당히 줄일 수 있었습니다. 기존의 `DataSourceFactory`는 하나의 service 클래스에서만 사용하고 있어 생성 메서드를 이 클래스로 이동했습니다.

2019-06-26 08:25 UTC, woowahan-pjs requested changes
아래의 글이 도움 되면 좋겠어요.

- https://octoperf.com/blog/2016/10/27/impl-classes-are-evil
- https://beji.tistory.com/entry/ORM-Object-Relational-Mapping-과-SQL-Mapper-정의
- https://gmlwjd9405.github.io/2018/12/25/difference-jdbc-jpa-mybatis.html

2019-06-26 08:25 UTC, woowahan-pjs commented on sample/schema.sql
> +USE wtc_lotto_test_db;
테스트 전용 데이터베이스 👍

2019-06-26 08:25 UTC, woowahan-pjs commented on src/main/java/com/woowacourse/lotto/controller/dto/AutoLottoBuyingRequestDto.java
> +public class AutoLottoBuyingRequestDto {
지금은 사용하지 않는 코드인 것 같아요.

2019-06-26 08:25 UTC, woowahan-pjs commented on src/main/java/com/woowacourse/lotto/controller/dto/ManualLottoBuyingRequestDto.java
> +public class ManualLottoBuyingRequestDto {
지금은 사용하지 않는 코드인 것 같아요.

2019-06-26 08:25 UTC, woowahan-pjs commented on src/main/java/com/woowacourse/lotto/service/LottoService.java
> +import com.mysql.cj.jdbc.MysqlDataSource;
사용하지 않는 import

2019-06-26 08:25 UTC, woowahan-pjs commented on src/main/java/com/woowacourse/lotto/persistence/DataSourceFactory.java
> +    private static DataSource dataSource;
싱글톤 패턴 👍

2019-06-26 08:25 UTC, woowahan-pjs commented on src/main/java/com/woowacourse/lotto/service/LottoService.java
> +        } catch (SQLException e) {
아래의 글을 읽고 코드에 반영하면 어떨까요?
http://wonwoo.ml/index.php/post/878

2019-06-26 08:25 UTC, woowahan-pjs commented on src/main/java/com/woowacourse/lotto/controller/LottoWebController.java
> +        if (totalQuantity.compareTo(LottoQuantity.of(lottos.size())) == -1) {
`LottoQuantity`에 메시지를 던지도록 구조를 바꿔 보면 어떨까요? 객체에 메시지를 보내 데이터를 가지는 객체가 일하도록 해보세요.

2019-06-26 14:39 UTC, Laterality commented
리뷰 감사합니다. 함께 주신 자료 보면서 Dao도 좀 더 개선해볼 수 있을지 고민해보고 있습니다. `SQLException`을 런타임 예외로 바꿔서 던지니까 Service 계층 코드도 눈에 띄게 단순해졌네요!

2019-06-27 00:30 UTC, woowahan-pjs approved these changes
수많은 피드백을 반영하고자 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-06-27 00:30 UTC, merged