[로또 - 웹, DB] 이바 미션 제출합니다.
woowacourse/java-lotto pull request #65
Opened 2019-06-12 12:39 UTC by seonghun127

많이 부족하지만 MVC 패턴을 적용하려고 노력했습니다.
전체적으로 웹 UI 보단 서버 구현에 신경을 썼습니다. 
Controller, Service, Dao와 같이 3 layer를 나눠보는 연습을 많이 할 수 있었습니다.
부족한 부분은 가차없이 지적해주시면 감사하겠습니다.

2019-06-15 02:46 UTC, gracefulBrown requested changes
안녕하세요. 리뷰어 브라운 입니다.
웹UI와 DB연동을 하면서 전체적으로 코드가 많이 추가되었네요!
전체적인 구조나 레이어 분리 등 고민을 많이 하신것을 보입니다 👍 
몇가지 피드백포함하여 코멘트 남겼으니 확인해보세요~
궁금한 점 있으면 언제든 DM 주세요 :)

2019-06-15 02:46 UTC, gracefulBrown commented on src/main/java/lotto/Controller/RoundController.java
> +import lotto.dao.RoundDAO;
Optimize imports 기능을 사용해보세요 :)

2019-06-15 02:46 UTC, gracefulBrown commented on src/main/java/lotto/WebUILottoApplication.java
> +        get("/", RoundController.MAX_ROUND);
아래의 Controller들의 function들은 행위를 의미하는 네이밍인것과 달리 MAX_ROUND만 명사같네요 ㅎㅎ;;

2019-06-15 02:46 UTC, gracefulBrown commented on src/main/java/lotto/service/LottoService.java
> +    public LottosDTO.Create createLottos(String manualLottoNumbers) throws SQLException {
WebUiController와 ConsoleController 모두 LottoService를 사용해야 하는것 같은데 manualLottos 에 대한 전처리는 컨트롤러 레이어에서 하면 어떨까요?

2019-06-15 02:46 UTC, gracefulBrown commented on src/main/java/lotto/service/LottoService.java
> +        logger.info("create lotto!");
log를 남기는 목적이 디버깅의 목적이라면
디버깅 툴을 이용하는 것을 추천드립니다 :)

2019-06-15 02:46 UTC, gracefulBrown commented on src/main/java/lotto/LottoApplication.java
>          OutputView.outputLottos(lottos);
lottos의 toString에 출력 로직을 정의할 경우 ConsoleUI에 종속될 수 있습니다 ㅠㅠ

2019-06-15 02:46 UTC, gracefulBrown commented on src/main/java/lotto/service/LottoService.java
> +    public LottosDTO.Create findLottosByRound(int round) throws SQLException {
SQLException처리는 어디서 하나요?
Exception을 발생 시 처리 로직도 포함되면 좋을 것 같아요 :)

2019-06-15 12:37 UTC, seonghun127 commented
피드백을 전부 반영하려고 노력했습니다.
console application에서도 db에 저장하는 방식으로 변경했습니다.
추가로 손 볼 필요가 있는 부분은 많이많이 지적해주세요! 감사합니다 👍

2019-06-19 01:56 UTC, gracefulBrown approved these changes
피드백 반영 잘 해주셨습니다 👍 
몇가지 피드백 남겼으니 확인해주세요 ^^
추가적인 부분은 오프라인으로 전달하겠습니다 :)

2019-06-19 01:56 UTC, gracefulBrown commented on src/main/java/lotto/domain/LottoFactory.java
> +    public static List<Lotto> createLottos(List<String> manualLottoNumbers, int countOfPurchase) {
현재 Lottos는 WinningLotto관련해서만 사용하고 있나요?
createLottos의 리턴으로 Lottos를 응답하면 어떨지 고민해 보면 좋을 것 같아요 :)

2019-06-19 01:56 UTC, gracefulBrown commented on src/main/java/lotto/dao/LottoDAO.java
> +            int nextRound = new RoundDAO().findMaxRound();
Dao에서 다른 DAO를 호출 한다면 Dao간 순환참조 현상이 발생 될 가능성이 높습니다.
nextRound값은 파라미터로 넘겨받는 걸 추천합니다 :)

2019-06-19 01:56 UTC, gracefulBrown commented on src/main/java/lotto/dao/WinningLottoDAO.java
> +            int nextRound = new RoundDAO().findMaxRound();
Dao, Service의 경우 상태가 없어서 매번 새로 생성해줄 필요가 없습니다.
싱글톤 패턴으로 구현하는거에 대해서 고민해보세요 ^^

2019-06-20 10:47 UTC, seonghun127 commented on src/main/java/lotto/LottoApplication.java
>          OutputView.outputLottos(lottos);
`Lottos` 클래스에 `getLottos()` 메서드를 추가하고 이를 view에 전달하는 방식으로 지적해주신 부분을 해결했습니다.
피드백을 반영하면서 궁금한 사항이 생겼습니다. 기존에 `Lottos`  클래스의 `toString()` 메서드를 재정의하고 이를 view에서 사용하는 방식이었습니다.
```
StringBuilder sb = new StringBuilder();
for (Lotto lotto : lottos) {
     sb.append(lotto);
     sb.append("\n");
}
return sb.toString();
```
근데 위 코드에서 `sb.append(lotto)` 부분도 `Lotto` 클래스에서 `toString()` 메서드를 재정의하고 사용하는 방식인데, 그럼 그 부분도 view에 종속적인 코드가 되는 건가요? `Lotto` 클래스의 `toString()` 메서드는 로또 번호가 [1, 2, 3, 4, 5, 6] 이런 식으로 출력하기 위해 구현한 상태입니다.
`toString()` 메서드를 재정의하는 이유는 해당 클래스의 정보를 유용하게 출력하기 위함이라고 알고있습니다. 그래서 `Lotto` 클래스에서 로또 6자리 번호가 모두 출력될 수 있도록 재정의를 한 것인데 그 부분을 콘솔 view 에서 출력할 때 사용하는 것도 view에 종속적이게 되는 것인지가 궁금하네요.

2019-06-20 10:47 UTC, seonghun127 commented on src/main/java/lotto/WebUILottoApplication.java
> +        get("/", RoundController.MAX_ROUND);
`GET_MAX_ROUND` 라는 이름으로 변경했습니다.
저는 Controller에 있는 필드들이 상수라고 생각하는데 보니까 동사로 시작하는 네이밍을 했더군요...
이들도 하나의 객체이기때문에 동사로 이름을 짓는것은 convention에 어긋나는 것이라고 생각합니다.
근데 이름으로 이들의 역할을 명확히하려면 지금처럼 동사가 들어가는게 좋다고 생각도 듭니다.
이 부분에 대해서는 어떻게 생각하시나요?

2019-06-20 10:47 UTC, seonghun127 commented on src/main/java/lotto/service/LottoService.java
> +        logger.info("create lotto!");
반영했습니다!

2019-06-20 10:47 UTC, seonghun127 commented on src/main/java/lotto/service/LottoService.java
> +    public LottosDTO.Create findLottosByRound(int round) throws SQLException {
반영했습니다!

2019-06-20 10:47 UTC, seonghun127 commented on src/main/java/lotto/Controller/RoundController.java
> +import lotto.dao.RoundDAO;
반영했습니다!

2019-06-20 10:47 UTC, seonghun127 commented on src/main/java/lotto/service/LottoService.java
> +    public LottosDTO.Create createLottos(String manualLottoNumbers) throws SQLException {
Console 방식과 Web 방식이 view를 어떤 형식(콘솔이냐, 웹 브라우져냐)으로 출력하나의 차이만 있고 내부 로직이 돌아가는 방식은 같다고 생각해서 피드백 주신 방식대로 수정했습니다.
구현한 Service 클래스도 LottoApplication (Console 방식)에서도 잘 돌아가야하기에 service의 `createLotto()` 와 `createWinningLotto()` 메서드가 모두 `List<String>` 타입으로 인자를 받는 것이 맞다고 생각이 들었습니다.
근데 여기서 궁금한 점은 Controller 단에서 view 에서 넘어온 인자를 (형변환과 같은)가공을 해도 상관이 없는 것인가요? 만약 가공하는 과정에서 예외가 발생하면 그 부분을 처리하는 로직도 추가해야할텐데 그러면 Controller 가 하는 역할이 불어나는것이 아닌가라는 생각이 들었습니다.

2019-06-23 16:47 UTC, seonghun127 commented on src/main/java/lotto/dao/WinningLottoDAO.java
> +            int nextRound = new RoundDAO().findMaxRound();
적용했습니다!

2019-06-23 16:47 UTC, seonghun127 commented on src/main/java/lotto/dao/LottoDAO.java
> +            int nextRound = new RoundDAO().findMaxRound();
적용했습니다!

2019-06-23 16:47 UTC, seonghun127 commented on src/main/java/lotto/domain/LottoFactory.java
> +    public static List<Lotto> createLottos(List<String> manualLottoNumbers, int countOfPurchase) {
적용했습니다!

2019-06-23 16:50 UTC, seonghun127 commented
싱글톤 패턴 적용방법을 찾아보면서 이전에 적용했던 방식과 다른 방식으로 적용해봤습니다. 
Holder 이름의 inner class로 두는 방식을 공부할 수 있었습니다.

순환 참조에 대해 공부할 수 있었습니다. DAO, Service layer에서 순환 참조가 일어나지 않게 프로그램을 짜야한다는 것을 알게되었습니다.

2019-06-25 09:16 UTC, gracefulBrown approved these changes
피드백 반영하시느라 고생하셨습니다 👍 
로직에 비해 테스트 코드가 적은것 같아서 아쉽지만 전체적으로 구조가 잘 짜여진것같아요 :)
몇가지 도움이 될 수 있는 피드백 남기니 다음 미션에서 고려해보면 좋을 것 같아요!
수고하셨습니다.

2019-06-25 09:16 UTC, gracefulBrown commented on src/main/java/lotto/service/LottoService.java
> +public class LottoService {
Service 로직에 대한 테스트코드가 없네요ㅠㅠ

2019-06-25 09:16 UTC, gracefulBrown commented on src/main/java/lotto/dao/DatabaseConnection.java
> +package lotto.dao;
dao보다는 util쪽으로 옮기는게 좋을 것 같아요 :)

2019-06-25 09:16 UTC, gracefulBrown commented on src/main/java/lotto/dao/LottoDAO.java
> +        try (Connection connection = DatabaseConnection.getConnection();
DAO로직에서 코드 중복이 많이 발생하고 있네요 ^^
다음에 시도할 때 중복제거도 같이 고려해보면 좋을 것 같아요 :)

2019-06-25 09:16 UTC, merged