[로또] 비모 미션 제출합니다.
woowacourse/java-lotto pull request #7
Opened 2019-05-29 12:05 UTC by SEOKHYOENCHOI

2019-05-30 01:37 UTC, pobiconan requested changes
지금까지 학습한 내용을 바탕으로 미션 진행 잘 했네요. 💯 
특히 유효성 체크를 여러 객체로 분산해 처리한 점이 인상적이네요.
피드백 몇 개 남겼고요. 다음 리뷰 요청을 보내기 전에 https://github.com/woowacourse/woowacourse-docs/blob/master/cleancode/pr_checklist.md 에 있는 체크리스트를 참고해 자체 검증을 한 후 리뷰 요청 보내면 좋겠어요.

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/customer/CustomLottoNumbers.java
> +    private List<List<Integer>> customLottoNumbers;
`List<Integer>`을 일급 콜렉션으로 구현하는 것은 어떨까?
generic이 이중으로 사용되고 있어 복잡한 느낌이다.

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/customer/PurchaseAmount.java
> +    private static final int ZERO = 0;
convention 위반

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/customer/PurchaseAmount.java
> +public class PurchaseAmount {
원시 값 포장 👍

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/lotto/BonusNumber.java
> +public class BonusNumber extends LottoNumber {
굳이 로직도 없는데 BonusNumber를 생성할 필요가 있을까?

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/lotto/LottoNumber.java
> +    private static final int MAX_LOTTO_NUMBER = 45;
convention 위반

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/lotto/LottoNumber.java
> +    protected final int number;
인스턴스 변수는 특별한 이유가 없는 한 private으로 구현한다.

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/lotto/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
인스턴스를 매번 생성하기보다 45개의 숫자에 해당하는 LottoNumber를 생성해 놓고 재사용 가능한 구조로 개발해 본다.

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/lotto/LottoTicket.java
> +    private final List<LottoNumber> lottoTicket;
값을 중복을 생각하면 Set 자료구조로 구현할 수는 없을까?

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/lottorank/LottoRank.java
> +public enum LottoRank {
굳이 3개의 enum을 생성해야 하나?
LottoRank enum하나로 구현하는 것은 어떨까?
enum을 분리하니 오히려 복잡도가 높아진 느낌이 든다.

2019-05-30 01:37 UTC, pobiconan commented on src/main/java/lotto/model/winninglotto/WinningLotto.java
> +public class WinningLotto {
전체적으로 유효성 체크 👍 
객체 한 곳이 아니라 여러 곳에 분산에 처리 잘 했음.

2019-06-01 14:57 UTC, SEOKHYOENCHOI commented on src/main/java/lotto/model/lotto/BonusNumber.java
> +public class BonusNumber extends LottoNumber {
BonusNumber가 변수명만 다른 LottoNumber가 아닌 따로 클래스를 가지는 것이 보기에 명확하다고 생각해서 클래스를 만들었습니다.
하지만 BonusNumber는 LottoNumber와 같은 기능을 하기 때문에 추가적인 검증 로직이 필요하지 않도록 상속을 이용했습니다.

`LottoNumber bonusNumber`와 같은 방식으로 만드는 것이 더 나은 방향이었을까요?
이런 방식의 설계에 대한 문제점이 궁금합니다.

2019-06-01 14:58 UTC, SEOKHYOENCHOI commented on src/main/java/lotto/model/lotto/LottoNumber.java
> +    protected final int number;
상속을 이용할 때 접근했다가 수정하지 못했습니다.
수정했습니다.

2019-06-01 14:59 UTC, SEOKHYOENCHOI commented on src/main/java/lotto/model/lotto/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
LottoNumberRepository를 만들어서 미리 LottoNumber를 생성하는 방식으로 수정했습니다.

2019-06-01 15:01 UTC, SEOKHYOENCHOI commented on src/main/java/lotto/model/lotto/LottoTicket.java
> +    private final List<LottoNumber> lottoTicket;
Set을 이용하는 방법 좋은 것 같아요.
추가로, 별도의 로또 번호 정렬이 필요하지 않도록 생성 시 TreeSet을 전달하는 방향으로 바꿔봤습니다.

2019-06-01 16:05 UTC, SEOKHYOENCHOI commented on src/main/java/lotto/model/lottorank/LottoRank.java
> +public enum LottoRank {
최대한 많이 분리해보면서 진행했더니 과하게 분리된 부분도 있는 것 같습니다.
수정했습니다.

2019-06-01 16:12 UTC, SEOKHYOENCHOI commented on src/main/java/lotto/model/customer/CustomLottoNumbers.java
> +    private List<List<Integer>> customLottoNumbers;
사용자가 입력한 번호만 가지는 클래스를 만들어보려고 했어요.
일급콜렉션을 따로 만들자니 추가로 LottoTicket을 생성하는 로직을 넣어야 해서 더 복잡해지는 느낌이고, List<LottoTicket>을 사용하려니 사용자가 입력한 번호에 대한 직관성이 떨어지는 느낌이었어요.
자동, 수동 모두 LottoTickets로 통일하는 방식으로 변경했습니다.

2019-06-01 16:21 UTC, SEOKHYOENCHOI commented
전체적으로 Convention을 위반하는 부분이 많았습니다. 앞으로는 더 신경써서 코딩하도록 노력하겠습니다.
추가로, 생성자를 사용하는 모든 부분에 정적 팩토리 메소드를 적용해봤어요.

랜덤 로또 번호를 만드는 부분과 LottoNumber를 상속받은 BonusNumber에 대해 궁금한 점이 있어 코멘트 남겼어요. 이 부분은 명확하게 알게됐을 때 수정하고 다시 PR 보내겠습니다.

2019-06-01 22:10 UTC, pobiconan commented on src/main/java/lotto/model/lotto/BonusNumber.java
> +public class BonusNumber extends LottoNumber {
의도를 드러내기 위해 이와 같이 상속을 사용하는 것도 괜찮은데요.
아무 로직도 없는 이런 클래스가 많아진다면 LottoNumber를 상속하는 클래스가 많아지지 않을까요?
BonusNumber에 추가 로직이 있다면 모르겠지만 그렇지 않다면 변수 이름을 통해서도 충분히 의도를 드러낼 수 있다고 생각해요.

2019-06-01 22:24 UTC, pobiconan approved these changes
피드백 반영 잘했네요. 💯 
질문에 대한 답변도 남겼고요. 소소한 피드백 몇개 남겼는데 다음 단계 진행할 때 적용해 보세요.
코드가 merge된 후 다음 단계를 진행하려면 woowacouse에 merge된 코드에서 다시 시작해야 충돌이 발생하지 않을 겁니다.
다음과 같은 과정을 진행한 후 다음 단계 진행할 것을 추천해요.
"git remote add upstream" -> "git fetch upstream 자신의 github_id" -> "git reset --hard upstream/자신의 github_id"
웹 UI/DB 적용 코드도 기대해 봅니다.

2019-06-01 22:24 UTC, pobiconan commented on src/main/java/lotto/model/lotto/LottoRank.java
> +public enum LottoRank {
👍

2019-06-01 22:24 UTC, pobiconan commented on src/main/java/lotto/model/winninglotto/WinningStatistics.java
> +    private EnumMap<LottoRank, Long> rankCountMap;
EnumMap을 찾았군요. 👍

2019-06-01 22:24 UTC, pobiconan commented on src/test/java/lotto/model/winninglotto/WinningStatisticsTest.java
> +        List<LottoNumber> lottoNumber = Arrays.asList(LottoNumberRepository.fromNumber(1)
이와 같이 구현하니 코드량이 많아지는데 fromNumber()를 static import로 구현하는 것도 좋은 방법일 수 있겠다.

2019-06-01 22:25 UTC, merged