[로또 - 웹, DB] 철시 미션 제출합니다.
woowacourse/java-lotto pull request #70
Opened 2019-06-13 08:47 UTC by pkch93

현재 페이지 스타일링은 거의 하지않고 서버에서 주고 받은 데이터만 보여주고 있습니다.
백엔드 구성에 대해서 써머님께 빨리 피드백 받고싶어서 먼저 리뷰요청을 보냅니다,
스타일링은 PR 보낸 후 빠르게 처리하겠습니다!

현재 제가 구성한 백엔드 구조에 대해 의문점이 있습니다.

먼저 사용자 입력값을 Dto로 바꿔서 DB에 저장함과 동시에 도메인 객체를 만들고 있는데 옳은 방법인지 궁금합니다.
(LottoService 객체에서 입력값을 받아 Dto로 만들어 DB에 저장하고 도메인 객체를 만들어 return하고 있습니다.)

그리고 WinningNumber와 Result가 LottoGame에 대해 1:1관계를 맺고 있어 LottoGameDao에 WinningNumber와 Result 관련 로직도 넣었는데 분리하는게 맞는지 의견을 여쭙고 싶습니다.

많이 부족한 코드입니다,, 많은 지적 부탁드립니다. 감사합니다 :)

2019-06-13 15:37 UTC, jihan805 requested changes
안녕하세요 철시님!
앞단계 피드백까지 반영 잘 해주셨네요 👍 
피드백 남겼으니 확인 부탁드려요 :)

2019-06-13 15:37 UTC, jihan805 commented on src/main/java/lotto/dao/LottoGameDao.java
> +    private static final int WINNING_START_INDEX = 2;
이 부분은 테이블 관련 정보가 없어서 추가로 첨부해주시면 다시 보도록 할게요.
Dao의 경우 하나이 저장소인데 저장소별로 나누는 것이 더 깔끔할것 같아요!

2019-06-13 15:37 UTC, jihan805 commented on src/main/java/lotto/domain/Money.java
> +        if (buyPrice < BoughtLottos.BUY_PRICE) {
validation을 각 클래스로 위임하였네요 👍

2019-06-13 15:37 UTC, jihan805 commented on src/main/java/lotto/service/LottoService.java
> +public class LottoService {
서비스 분리 👍 
하지만 클래스가 너무 거대한것 같아요!
로또를 구입 및 생성을 담당하는 LottoService와 결과등을 담당하는 LottoResultService등과 같이 나누어 보면 어떨까요?

2019-06-13 15:37 UTC, jihan805 commented on src/main/java/lotto/service/LottoService.java
> +    public Map<String, Object> findAllDataOfRound(int round) throws SQLException {
model에 대한 매핑을 서비스에서 하면 어떤 단점이 있을까요?

2019-06-14 13:19 UTC, jihan805 commented on src/main/java/lotto/dao/LottoGameDao.java
> +    private static final int WINNING_START_INDEX = 2;
추가로 싱글톤과 DAO에 대해 찾아보고 적용해보면 좋을 것 같아요!

2019-06-15 02:36 UTC, pkch93 commented on src/main/java/lotto/dao/LottoGameDao.java
> +    private static final int WINNING_START_INDEX = 2;
http://www.okjsp.net:8080/article/131372
https://okky.kr/article/583814

주신 피드백을 바탕으로 몇가지 글들을 찾아봤습니다. DAO는 stateless 한 객체이기 때문에 싱글톤으로 보통 사용하는 것을 알 수 있었습니다.

이때, 의문점이 그러면 static 메서드로 사용하면 안되나였는데 (stateless하기 때문에,,) 이에 대해서는 아래 링크를 통해 싱글톤이 static에 비해 OOP적인 측면에서 이점이 있기 때문에 Dao에서 싱글톤을 사용함을 알 수 있었습니다.
https://stackoverflow.com/questions/519520/difference-between-static-class-and-singleton-pattern

좋은 피드백 감사합니다! 혹시라도 제가 잘못 깨우친게 있다면 피드백 부탁드리겠습니다 !!

2019-06-15 02:54 UTC, pkch93 commented on src/main/java/lotto/service/LottoService.java
> +public class LottoService {
피드백을 반영하면서 LottoGameService와 ResultService로 분리하였습니다.

LottoGameService에서 담당해야하는 비즈니스 로직이 로또 구입 및 생성, 결과 도출까지는 필요하다고 생각하였습니다.
반면, ResultService는 뷰에서 해당 round의 결과를 보여주는 데 필요한 정보를 반환하도록 하는 역할을 하도록 구현하고자 했습니다.

2019-06-15 02:57 UTC, pkch93 commented on src/main/java/lotto/service/LottoService.java
> +    public Map<String, Object> findAllDataOfRound(int round) throws SQLException {
https://stackoverflow.com/questions/52423080/is-it-good-to-have-model-mapping-and-more-logics-in-a-mvc-controller

위 링크를 찾아보며 문제점을 찾을 수 있었습니다.
서비스에서 다수의 데이터를 매핑하게 되는 경우 다른 요구사항으로 필요한 데이터를 매핑하는 경우 중복된 코드가 발생하게 되는 문제점이 있을 수 있음을 깨달았습니다,

때문에 각각의 필요한 정보를 (response에 필요한 정보) 반환하고 Mapping 단계를 컨트롤러에서 하게 되었습니다.

주신 피드백에 대해 제가 알아보고 깨달은 부분은 위와 같습니다. 혹시라도 잘못된 부분이 있다면 피드백 부탁드리겠습니다!!

2019-06-16 15:02 UTC, jihan805 commented on src/main/java/lotto/WebUILottoApplication.java
> +    public static void main(String[] args) throws SQLException {
해당 클래스가 모든 path를 매핑하고 있어요.
로또 게임이 가지는 기능이 커지면 해당 클래스가 너무 복잡할것 같아요!

2019-06-16 15:02 UTC, jihan805 commented on src/main/java/lotto/dao/LottoDao.java
> +            pstmt.setInt(i + 1, lottoDtos.get(dtoIndex).getLottoNumbers().get(i));
한줄에 너무 많은 "."을 사용하지 않도록 해요.
(객체지향생활체조원칙을 참고해보면 좋을 것 같아요)

2019-06-16 15:02 UTC, jihan805 commented on src/main/java/lotto/service/LottoService.java
> +public class LottoService {
분리 👍 
현재는 LottoGameService 에서 로또 구입 ~ 결과 도출까지 모든 것들을 담당하고 있어요!
하지만, 너무 많은 일들을 하고 있기에 분리해도 좋을 것 같아요!

2019-06-16 15:05 UTC, jihan805 approved these changes
안녕하세요 철시님!
피드백 반영 잘하셨어요 💯
간단한 피드백 남겼으니 확인 부탁드려요. 머지 진행할게요 :)

2019-06-16 15:05 UTC, merged