[로또 - 웹 / DB] 닉 미션 제출합니다.
woowacourse/java-lotto pull request #72
Opened 2019-06-13 14:27 UTC by wbluke

AJAX와 자바스크립트 등을 공부하면서 해보려고 하다가 많이 늦었습니다 ㅜㅜ
sql 파일 포함하였습니다.
패키지 구조와 클래스 등은 [링크](https://buildplease.com/pages/repositories-dto/) 참조하여 
Controller - Service - Assembler 로 구성해보려고 하였습니다. 
이번에도 잘 부탁드립니다...! :)

2019-06-15 10:10 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다.
각 레이어를 분리하면서 많은 고민을 하신게 눈에 보이네요 👍 
기존 도메인에 대한 수정도 없이 잘 구현하신 것 같습니다.
간단한 피드백 몇가지 추가했는데요, 참고 부탁드릴게요 :) 
궁금한 점 있으시면 언제든지 DM주세요!

2019-06-15 10:10 UTC, phs1116 commented on src/main/java/lotto/application/LottoDAO.java
> +public class LottoDAO {
이름은 DAO인데 커넥션을 관리하는 객체이네요. :)
적당한 이름으로 수정하면 좋을 것 같습니다.

2019-06-15 10:10 UTC, phs1116 commented on src/main/java/lotto/application/lottoresult/LottoResultDAO.java
> +            LottoDAO.closeConnection(connection);
try-with-resources 한번 살펴보시면 좋을 것 같네요. :)

2019-06-15 10:10 UTC, phs1116 commented on src/main/java/lotto/application/lottomoney/LottoMoneyService.java
> +    public static LottoMoneyDTO makeLottoMoneyDto(String purchasePrice) {
static method와 싱글톤에 대한 차이에 대해서 공부해보시면 좋을 것 같아요. :)

2019-06-15 10:10 UTC, phs1116 commented on src/main/java/lotto/controller/JsonUtil.java
> +public class JsonUtil {
유틸 클래스인데도 패키지가 그냥 컨트롤러에 들어있네요. :)
적합한 패키지로 분리해보는건 어떨까요?

2019-06-15 10:10 UTC, phs1116 commented on src/main/java/lotto/controller/Path.java
> +    public static final String INDEX = "/";
Path에 대한 전역 클래스가 필요할까요?
이 Path에 대해서 연관되어있는 클래스가 가지고있는게 사용하는 측면에서도 그렇고, 응집도가 높지 않을까요?

2019-06-15 10:10 UTC, phs1116 commented on src/main/java/lotto/domain/lottoticket/dto/LottoTicketDTO.java
> +    private int firstNum;
배열을 통해 받을수도 있을 것 같네요. :)

2019-06-15 10:10 UTC, phs1116 commented on src/main/java/lotto/application/lottoresult/LottoResultAssembler.java
> +        LottoTicketDTO lottoTicketDto = LottoTicketService.getLottoTicketDto(winningLotto.getWinningTicket());
지금 얘기하기에 이른 경향도 있습니다만
첨부해주신 문서에서도 언급하기를 Assembler는 Application Service 레이어나 프레젠테이션 레이어에 속할 수 있다고 하네요. 
`프레젠테이션 레이어(컨트롤러) -> 어플리케이션 레이어(어플리케이션 서비스 -> 어셈블러) -> 도메인 레이어(도메인 서비스, 모델, Repository)`
각 상위 레이어는 하위 레이어에 대해 알 수 있지만 하위 레이어는 상위 레이어에 대해서 알 수 없다는게 일반적인데요.
지금 당장은 다 지키기 어렵지만 나중에 괜찮으시면 공부하시면서 반영해봐도 좋을 것 같아요. :)

2019-06-17 03:23 UTC, wbluke commented on src/main/java/lotto/application/lottomoney/LottoMoneyService.java
> +    public static LottoMoneyDTO makeLottoMoneyDto(String purchasePrice) {
질문이 있습니다! :)
저는 싱글톤을 DAO에서만 적용했고, 지금같은 LottoMoneyService에서는 LottoMoneyDTO를 만들어주는 로직에서 싱글톤이 아니라 일반적인 static 메소드로 Service의 인스턴스 생성 없이 메소드를 사용해야겠다고 생각해서 위와 같이 구현했었는데요.ㅎㅎ
혹시 남겨주신 코멘트에 대해 어떤 의도로 말씀해주셨는지 설명을 부탁드려도 될까요...? :)

2019-06-17 03:26 UTC, wbluke commented on src/main/java/lotto/application/lottoresult/LottoResultAssembler.java
> +        LottoTicketDTO lottoTicketDto = LottoTicketService.getLottoTicketDto(winningLotto.getWinningTicket());
질문이 있습니다! ㅎㅎ
이번에 Service와 Assembler에 대해서 처음 알게 되어서 한번 적용해본 것이었는데요,
제가 이해했던 바로는 제 코드의 Service와 Assembler가 동등한 레벨의 어플리케이션 레이어라고 생각해서 
LottoResultAssembler가 LottoTicketDTO를 만들기 위해 LottoTicketService를 호출하게 되었는데,
남겨주신 코멘트에 따르면 Assembler는 Service를 아예 몰라야한다는 말씀이신가요? :)

2019-06-17 03:28 UTC, wbluke commented
리뷰 감사합니다!
자바7에 try-with-resources 라는 구문을 처음 알게 되어서 너무 신세계였습니다...ㅋㅋ 재밌었어요
코멘트에 두 가지 질문 남겨놓았습니다 :) 
다시 한 번 부탁드립니다ㅎㅎ

2019-06-17 14:32 UTC, phs1116 requested changes
안녕하세요 리뷰어 화투입니다. :)
피드백 반영 감사합니다. 👍 
질문하신 부분에 대해서도 답변 드렸구요,
몇가지 피드백 더 추가했어요. :)
참고 부탁드리고 궁금하신 점 있으시면 연락주세요!

2019-06-17 14:32 UTC, phs1116 commented on src/main/java/lotto/application/lottomoney/LottoMoneyService.java
> +    public static LottoMoneyDTO makeLottoMoneyDto(String purchasePrice) {
넵. 가장 큰 차이점은 static으로 구현된 서비스는 인터페이스를 활용 할 수 없다.
그리고 외부에 의존이 있는 서비스를 주입받기에 용이하지 않다(의존성 주입)이 있을 것 같아요!
이는 결국엔 이 서비스를 확장하기 매우 어렵다는 의미도 될 수 있을것 같구요.

스프링 같은 프레임워크 같은경우에는 내부적으로 컨테이너가 직접 싱글턴을 보장해주고 생성해서 관리해주고 있지만
현재 단계에서는 직접 구현해서 확장하기 쉬운 구조로 만들어보면 좋을 것 같아서 말씀드렸어요 :)

2019-06-17 14:32 UTC, phs1116 commented on src/main/java/lotto/application/lottoresult/LottoResultAssembler.java
> +        LottoTicketDTO lottoTicketDto = LottoTicketService.getLottoTicketDto(winningLotto.getWinningTicket());
네. :) 이부분에 대해서는 저도 공부를 해봐야 할 것 같은데요,
첨부해주신 내용 상으로는 어플리케이션 레이어에서 DTO를 만들면서 더럽혀질수 밖에 없는 부분을 
Assembler라는 걸로 분리해서 위임하는걸로 보여서요!
그려진 그림과 알아본 내용에 대해서도 서비스 자체에 의존하기보다는 전달받은 엔티티에 의존해서 DTO를 조립하는 객체로 보이네요. :)

2019-06-17 14:32 UTC, phs1116 commented on src/main/java/lotto/application/lottoresult/LottoResultDAO.java
> +        try (Connection connection = LottoJDBCDriverConnector.getConnection();
현재 DAO에서 상당부분 중복된 부분들이 많은데요,
대표적으로  try - catch  rnansrhk 커넥션 생성, PreparedStatement 생성, execute 하는 부분입니다.
이런 부분들을 공통적으로 추상화하여 뽑아내보면 어떨까요?

2019-06-17 14:32 UTC, phs1116 commented on src/main/java/lotto/application/lottoresult/LottoResultDAO.java
> +             ResultSet rs = pstmt.executeQuery()) {
resultSet에서도 꼭 닫아주세요!

2019-06-17 14:32 UTC, phs1116 commented on src/main/java/lotto/application/lottoresult/LottoResultDAO.java
> +            e.printStackTrace();
e.printStackTrace()는 일반적으로 안티패턴입니다. :)

2019-06-17 14:32 UTC, phs1116 commented on src/main/java/lotto/application/lottoresult/LottoResultDAO.java
> +    private PreparedStatement createPreparedStatement(Connection con, int userId) throws SQLException {
SQLException이라는 checked exception을 그냥 던지고 있는데요,
이도 현재 안티패턴으로 사용되고 있는 부분중 하나입니다.
아래 글 참고하셔서 공부해보시면 좋을 것 같아요. :)
http://wonwoo.ml/index.php/post/878

2019-06-17 14:32 UTC, merged