[로또 - 웹, DB] 션 미션 제출합니다.
woowacourse/java-lotto pull request #79
Opened 2019-06-14 14:40 UTC by os94

부족한점이 많지만, 차근차근 알아가겠습니다...!

2019-06-16 12:20 UTC, kang-hyungu requested changes
안녕하세요 리뷰어 강현구입니다.
기존 도메인 로직 크게 수정하지 않고 웹, DB 잘 반영하셨어요 :+1: 
몇 가지 수정하면 좋을 부분에 코멘트 남겼으니 확인해보세요
궁금한 점 생기면 연락주세요!

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/java/lotto/LottoGameService.java
> +public class LottoGameService {
몇몇 파라미터들이 자바 컨벤션에 어긋나네요
규칙에 맞게 수정해보아요

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/java/lotto/LottoGameService.java
> +        return new RoundDAO().recentRound();
new RoundDAO()로 매번 새로 객체 생성하지 말고 LottoGameService 객체 생성할 때 미리 생성해두는건 어떨까요

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/java/lotto/WebUILottoApplication.java
> +                new LottoGameService().registerWinningLotto(req.queryParams("input_winning_lotto"), req.queryParams("input_bonus"));
new LottoGameService()도 계속 객체를 생성해야될 필요가 있을까요?

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/java/lotto/WebUILottoApplication.java
> +            post("/registerWinningLotto", (req, res) -> {
uri는 대문자, 언더바를 안쓰는게 좋아요
/register-winning-lotto
이런식으로 바꿔보아요

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/java/lotto/model/dao/LottosDAO.java
> +            String query = "SELECT * FROM lottos_tb WHERE fk_lottos_round = ?";
select할 필드명은 전부 명시해주는게 좋습니다.
lottos_tb 테이블 스키마가 변경할 때 코드 수정하지 않으면 장애 발생 원인이 될 수 있습니다

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/java/lotto/model/dao/RoundDAO.java
> +            String query = "select count(*) from round_tb";
```suggestion
            String query = "select count(*) as total from round_tb";
```
별칭을 주고 resultSet.getInt("total"); 하면 나오지 않나요?

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/resources/sql/lotto_lottos_tb.sql
> +DROP TABLE IF EXISTS `lottos_tb`;
접미사로 _tb를 붙일 필요가 있을까요?
당연히 테이블이라서 굳이 표시 안해줘도될 것 같네요

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/resources/sql/lotto_lottos_tb.sql
> +  CONSTRAINT `fk_lottos_round` FOREIGN KEY (`fk_lottos_round`) REFERENCES `round_tb` (`round`) ON DELETE CASCADE
이론적으로는 fk를 거는게 좋은데 실무에서는 잘 안써요
fk 때문에 테이블간 의존성이 생겨버려서 스키마 변경이 필요하거나 데이터 수정할 때 어렵게 만들어요

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/resources/sql/lotto_lottos_tb.sql
> +-- MySQL dump 10.13  Distrib 8.0.16, for Win64 (x86_64)
불필요한 주석은 제거해도 되지 않을까요?

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/resources/sql/lotto_round_tb.sql
> +  `money` int(11) NOT NULL,
bigint가 어떨까요
로또 금액이 생각보다 커요

2019-06-16 12:20 UTC, kang-hyungu commented on src/main/java/lotto/WebUILottoApplication.java
> +                model.put("round", new LottoGameService().recentRound() + 1);
+1도 일종의 도메인 로직 아닐까요?
뷰에서 처리할 방법 없을까요?

2019-06-17 13:49 UTC, kang-hyungu commented on src/main/java/lotto/model/dao/DBManager.java
> +public class DBManager {
코멘트를 빼먹었네요
싱글톤으로 만들면 매번 새로 디비 연결하지 않고 쓸 수 있지 않을까요?
디비 연결했다 끊는게 비용이 많이 드는 작업이에요

2019-06-23 07:00 UTC, os94 commented on src/main/java/lotto/LottoGameService.java
> +public class LottoGameService {
웹이 섞여서 헷갈렸던것같습니다. 수정했습니다!

2019-06-23 07:01 UTC, os94 commented on src/main/java/lotto/WebUILottoApplication.java
> +            post("/registerWinningLotto", (req, res) -> {
몰랐는데 알려주셔서 감사합니다!

2019-06-23 07:01 UTC, os94 commented on src/main/java/lotto/LottoGameService.java
> +        return new RoundDAO().recentRound();
new를 신경쓰지못하고 너무 남발했던것 같습니다. 수정해보았습니다!

2019-06-23 07:01 UTC, os94 commented on src/main/java/lotto/WebUILottoApplication.java
> +                new LottoGameService().registerWinningLotto(req.queryParams("input_winning_lotto"), req.queryParams("input_bonus"));
수정했습니다!

2019-06-23 07:02 UTC, os94 commented on src/main/java/lotto/model/dao/LottosDAO.java
> +            String query = "SELECT * FROM lottos_tb WHERE fk_lottos_round = ?";
수정했습니다.

2019-06-23 07:05 UTC, os94 commented on src/main/java/lotto/model/dao/RoundDAO.java
> +            String query = "select count(*) from round_tb";
생각치못했습니다, 알려주셔서 감사합니다.
논외로, 전반적으로 DB를 잘 모르다보니 부족한점이 많습니다, 방학시간을 비롯해 좀더 DB공부를 해보아야겠습니다..!

2019-06-23 07:05 UTC, os94 commented on src/main/resources/sql/lotto_lottos_tb.sql
> +DROP TABLE IF EXISTS `lottos_tb`;
수정했습니다.

2019-06-23 07:07 UTC, os94 commented on src/main/resources/sql/lotto_lottos_tb.sql
> +  CONSTRAINT `fk_lottos_round` FOREIGN KEY (`fk_lottos_round`) REFERENCES `round_tb` (`round`) ON DELETE CASCADE
책에는 나오지않는 실질적인 피드백을 알려주셔서 감사합니다,
요번에는 db를 처음써보기도하고 강의시간에 fk를 배우기도해서
한번 써보았습니다.!

2019-06-23 07:12 UTC, os94 commented on src/main/resources/sql/lotto_round_tb.sql
> +  `money` int(11) NOT NULL,
해당 money칼럼이 사용자가 구입한 금액을 의미하다보니 일단은 int로 유지해도 될것 같습니다.
int형은 최대 21억까지라고 하니, 나중에 당첨금액을 저장하게 된다면 1등금액이 20억이므로 bigint를 사용해도 좋을것 같습니다. 범위에 대해선 생각해보지 않았는데, 알려주셔서 감사합니다!
![image](https://user-images.githubusercontent.com/38856352/59972859-81ce5f80-95d1-11e9-8f09-299b4eb9b222.png)

2019-06-23 07:13 UTC, os94 commented on src/main/java/lotto/WebUILottoApplication.java
> +                model.put("round", new LottoGameService().recentRound() + 1);
MVC에 어느정도 익숙해졌다고 생각했었는데, 여전히 허점이 있었군요!
LottoGameService에 메소드를 추가로 만들까하다가, 뷰로 옮겨서 분리해보았습니다!

2019-06-23 07:17 UTC, os94 commented on src/main/java/lotto/model/dao/DBManager.java
> +public class DBManager {
역시 db에 익숙치않다보니 그런것같습니다.
싱글턴으로 만드는것까진 좋았는데, 그러면 close를 어디에서 사용해야할지 혼란이 왔습니다.
close를 한번이라도 호출해버리면 `No operations allowed after connection closed.` 에러가 나서
일단 connection을 닫는부분은 삭제하였습니다..! 😅

2019-06-23 07:31 UTC, os94 commented on src/main/resources/sql/lotto_lottos_tb.sql
> +-- MySQL dump 10.13  Distrib 8.0.16, for Win64 (x86_64)
수정했습니다.

2019-06-24 01:33 UTC, kang-hyungu commented on src/main/java/lotto/model/dao/DBManager.java
> +public class DBManager {
connection close는 프로그램 종료할 때 끊으면 될거에요 :)
connection을 닫지 않으면 dbms에 불필요한 연결이 남아있을 수 있으니 꼭 close 시키는게 좋아요
웹서버에 연결할 수 있는 숫자가 제한되어 있는 것처럼 디비도 연결할 수 있는 수가 한정되어 있어서 연결을 닫아야합니다.

2019-06-24 01:36 UTC, kang-hyungu approved these changes
피드백 반영하신 부분 확인했습니다
코드 깔끔하게 잘 구현하셨어요 :100: 
db 관련 내용은 다음 과정 진행하면서 좀더 이야기해보아요
구현하느라 수고하셨어요!

2019-06-24 01:36 UTC, merged